### ISSUE TITLE
Error al syncronizar complementos

### ISSUE THREAD

**Issue by Dazmed707** [MrAlex94/Waterfox#1007]
Al syncronizar con mi cuenta de mozilla en waterfox 68 alpha no se syncronizan los complementos, solamente los links y contraseñas

**Comment by ibuprophen1** [comment]
Translation... 

TITLE: Error synchronizing add-ons

DETAILS: When synchronizing with my mozilla account in waterfox 68 alpha the add-ons are not synchronized, only the links and passwords. 


~Ibuprophen
