### ISSUE TITLE
v68: Restore cookie manager

### ISSUE THREAD

**Issue by devarped** [MrAlex94/Waterfox#1026]
Since Firefox 61, the ability to manage individual site cookies from address bar (click on info button -> "More Information" -> "View Cookies") was removed, and you can only remove cookies of the same site you've visited. The same cookie manages was available on chrome://browser/content/preferences/cookies.xul page. 

This function was pretty useful. Is it possible to restore it for Waterfox 68?

**Comment by grahamperrin** [comment]
Would an extension be enough? 

Probably fewer clicks with e.g. [Cookie Quick Manager](https://addons.mozilla.orgaddon/cookie-quick-manager/)

**Comment by devarped** [comment]
> Would an extension be enough?
> 
> Probably fewer clicks with e.g. [Cookie Quick Manager](https://addons.mozilla.orgaddon/cookie-quick-manager/)

Yeah, I tried it and it does everything I need. But still, having a built-in functionality would be nice. I assume it won't be too much hassle to restore it.

**Comment by grahamperrin** [comment]
Thanks, 

> … a built-in functionality would be nice.…

I'm aware of (but don't use) the developer feature. 

A shot from Waterfox Classic (I don't have 68.0a1 handy):  

![image](https://user-images.githubusercontent.com/192271/59588402-6b129f00-90df-11e9-9e39-5ba474f2160d.png)

Some background at https://www.reddit.com/r/firefox/comments/80bhv7/new_cookie_management_or_lack_of_in_nightly/duumo43/
