### ISSUE TITLE
Crashing Tabs In WaterFox 68.0

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1183]
WaterFox's tabs keep crashing when there is enough memory to use. I was just watching a youtube video and the tab just crashed.

**Comment by grahamperrin** [comment]
Please let us have troubleshooting information. 

Use the **Copy text to clipboard** button at: 

- about:support

If you paste the text here (in GitHub) you can make it easier to read by 'fencing' the text. One line above, one line below as described at https://guides.github.com/features/mastering-markdown/#examples ▶ **Code**

Thanks
