### ISSUE TITLE
FTL Playback Support

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1184]
Currently, WaterFox 68.0b1 does not support FTL Livestreams for playback and this needs to be fixed. This was tested by streaming on https://www.mixer.com in FTL Mode and the "Low Latency" Option was greyed out, meaning that WaterFox does not support FTL Playback.

**Comment by grahamperrin** [comment]
Which OS?

https://watchbeam.zendesk.com/hc/articles/209659623-FTL-Faster-Than-Light-streaming-protocol-

**Comment by ghost** [comment]
I am using Windows 10 1903 64bit as my OS

**Comment by hawkeye116477** [comment]
Related => https://bugzilla.mozilla.org/show_bug.cgi?id=1559678.

**Comment by ghost** [comment]
Just for proof of the error
![waterfox_3Ge0VOoLi2](https://user-images.githubusercontent.com/37266538/66641893-e57da680-ec1b-11e9-92b1-d92dfa82c79c.png)
