### ISSUE TITLE
LastPass problems with Waterfox Current 68.0b1

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1186]
[LastPass: Free Password Manager](https://addons.mozilla.org/addon/lastpass-password-manager/) 4.33.5.12 with build 20190906171246 of 68.0b1 on Lubuntu and on Manjaro. 

In both cases: after initial installation of the extension, initial use of the toolbar button presents a pop-up through which permissions should be allowed. Following the allowance, an extension page offers a log in option. 

### Problems

A click on the **Log In** button is recognised (there appears a blue border to the red button) but beyond that, no progress; no log in. 

Most if not all subsequent clicks on the toolbar button fail to present a pop-up. 

### Reproducibility

Not reproducible with Firefox 69.0.2 on FreeBSD-CURRENT. 

A click on the red **Log In** button is followed by an in-page rotating asynchronous progress indicator, and log in succeeds. 

Meta, tracking: #538

**Comment by grahamperrin** [comment]
Screen recordings available on request. 

PS I did quickly browse the most recent topic titles at page one of https://forums.lastpass.com/viewforum.php?f=14 … unless I'm missing something, nothing like the problems that I see with 68.0b1 on Linux.

**Comment by hawkeye116477** [comment]
Maybe try mozregression tool and write results from it :smile:.

**Comment by grahamperrin** [comment]
> mozregression

I used it a few times, a year or so ago, probably with Mavericks on an old MacBook Pro that I had to one side. 

IIRC mozregression is not usable with FreeBSD and it's not really practical for me to run it in a virtual machine on the available hardware … but thanks!

I'll await the next binary, with which I imagine the issue will be no long reproducible.
