### ISSUE TITLE
about:crashes – Waterfox Current can not present crash information

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1191]
https://github.com/MrAlex94/Waterfox/issues/607#issuecomment-471851470

68.0b1: 

![wrong, wrong, wrong, wrong, wrong](https://user-images.githubusercontent.com/192271/66709923-e6baea80-ed65-11e9-96b5-8fe43484bc08.png)

From https://old.reddit.com/comments/dgquog/-/f3eyr62/?context=1

>> For the community, I hope to find support for: … crash reporting – if too much is removed from the application, it will be unreasonably difficult to troubleshoot

**Comment by MrAlex94** [comment]
You aren’t wrong; but I haven’t found the time to decouple the crash reporter from sending reports back to Mozilla - that would cause too many problems.

**Comment by grahamperrin** [comment]
Thanks. Sane to not systematically _send_ 👍 – https://github.com/MrAlex94/Waterfox/pull/1124/files#diff-61cac4855c1bb1dd3e264ed799753d4fR3325

Just, for the end user to _have_ a report<strike>; that's the essence here</strike>. Availability. Cross reference: 

* [Where the hell are your crash logs, Waterfox?](https://www.reddit.com/r/waterfox/comments/e5hs1u/where_the_hell_are_your_crash_logs_waterfox/)

**Comment by MrAlex94** [comment]
Of course - the issue is if I don't do things properly, I can get in real
trouble. It's better to err on the side of caution.

**Comment by grahamperrin** [comment]
Alex and all, I apologise for the bluntness when I raised this issue. 

The bluntness was almost entirely an after-midnight reaction to #1190 where an equally blunt response, to a problem that I _probably_ brought upon myself, could have been: 

1. "refresh"
2. close (not a bug). 

----

All emotion aside: information reigns. 

Info from `about:support` often gets things resolved (or at least understood) quickly and with minimal noise. 

Info from `about:crashes` … I can't pretend that this type of data will _always_ lead to an understanding, but it should be a good starting point in most cases. 

TIA

**Comment by timur-g** [comment]
Waterfox Classic also doesn't have about:crashes.

**Comment by grahamperrin** [comment]
Thanks, 

> Waterfox Classic

That's #607, linked from the head of the opening post here.
