### ISSUE TITLE
Waterfox Current: Expose `extensions.getAddons.showPane` in about:config by default

### ISSUE THREAD

**Issue by laniakea64** [MrAlex94/Waterfox#1192]
There is a hidden `about:config` pref `extensions.getAddons.showPane` which toggles whether the Recommendations panel is available in the Add-ons Manager.  Since Waterfox favors user choice, this pref should be visible in `about:config` by default.

I didn't submit a pull request because I'm not sure what would be a good default for Waterfox.  The current default is `true`, but on the other hand the Recommendations panel doesn't actually show recommendations.

**Comment by grahamperrin** [comment]
> … on the other hand the Recommendations panel doesn't actually show recommendations.

Without looking at any recent code: I _guess_ that the absence of recommendations originally went hand-in-hand with the absence of URLs for updates to extensions and so on. Recalling the (2018-04) [vision of an independent add-on store](https://www.waterfox.net/blog/waterfox-its-legacy-and-looking-to-the-future) … 

HTH

**Comment by laniakea64** [comment]
Hi @hawkeye116477 , regarding your comment https://github.com/MrAlex94/Waterfox/pull/1041#issuecomment-552227228 ...

> There is also leftover on about:addons page
> https://github.com/MrAlex94/Waterfox/pull/1213/commits/fa27e2df1e02a7c721d518b3cd515960a99fd863

... will that commit from https://github.com/MrAlex94/Waterfox/pull/1213 make this issue moot?

**Comment by hawkeye116477** [comment]
@laniakea64 Yes, recommendations doesn't work, so I removed it and I though that we don't want them :smile:. If not, then I will restore it and just hide.
