### ISSUE TITLE
Waterfox Classic - add-ons are broken

### ISSUE THREAD

**Issue by strotee** [MrAlex94/Waterfox#1199]
I installed Classic today (2019.10) only to find out my add-ons are broken. This has made me revert back to 56.2.14. The add-on either loads a broken options page or doesn't load at all. They include but not limited to: uBlock Origin, Privacy Badger, Cookie AutoDelete.

I even installed 2019.10 in a fresh VM and it had similar issues.

**Comment by MrAlex94** [comment]
Hmm that’s not good at all. I did an upgrade from 56.2.14 -> 2019.10 and
had uBlock Origin and Privacy Badger installed when upgrading and they work
as previous.

Is this on Windows?

**Comment by strotee** [comment]
Yes, LTSC 17763.832. It may be something I did wrong, that's always a possibility. 

I just tried to load uBO in my VM (10 LTSC 17763.805) and this is what options looks like:

https://i.imgur.com/zRQjRWQ.png

Edit: I'm not sure what happened. I may have accidentally closed the issue, thanks for re-opening.

**Comment by MrAlex94** [comment]
I think this was closed by accident? I can reproduce in certain scenarios.

**Comment by MrAlex94** [comment]
Seems like this only happens on Windows? Am running a `git bisect` to see what commit, if any caused this change.

**Comment by ghost** [comment]
No extensions work?

**Comment by strotee** [comment]
I never tested every single extension but of my dozen or so installed, it was enough for me to make an issue about it. YMMV

**Comment by colin1951uk** [comment]
I'm noticing add-ons don't work for me to. I only use two, Video DownloadHelper and GoodTwitter. DownloadHelper works on the odd site, but many are broken. GoodTwitter doesn't work at all. I've tried both an upgrade and new install and neither is any good. What with Youtube the Windows new Classic version has problems.

**Comment by MrAlex94** [comment]
Has been fixed https://github.com/MrAlex94/Waterfox/commit/68014c079a1d4afa26aaad13466fcc76d0f6dcc4

**Comment by MrAlex94** [comment]
[Here](https://send.firefox.com/download/12409f4e353eefe3/#OC3oAuh59J0JbB4YQlB0XA) is the new final build. Please let me know if there are still issues.

**Comment by grahamperrin** [comment]
Thanks. 

Unofficial https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads#201910-classic round one complete. I'll not insert more URLs etc. until after things are settled at and around https://www.waterfox.net/releases/

**Comment by strotee** [comment]
All of the add-ons that I reported are now working (in fact, they seem to be all working) with the version you provided in a previous message. Thanks.

It also integrated into my previous installation folder so I could continue to use my previous settings/add-ons/etc.

**Comment by ghost** [comment]
Youtube does not work.
https://images89.fotosik.pl/266/fb6001c6291643b8gen.png

**Comment by grahamperrin** [comment]
### YouTube playback

@jorg35 subscribe to #1205
