### ISSUE TITLE
Theme issue with Light/Dark when using custom userchrome.css

### ISSUE THREAD

**Issue by troysjanda** [MrAlex94/Waterfox#1200]
![66886238-a0b48f80-efce-11e9-8301-eca66caa63b3](https://user-images.githubusercontent.com/24624945/66890622-9200b500-ef9b-11e9-9ec1-93cc680e939f.png)

Waterfox 2019.10 Current - Windows 10 1909 18363.418

When there is a userChrome.css being used seems to cause the above issue if using the light or dark default themes. The default theme seems unaffected.

**Comment by grahamperrin** [comment]
Thanks, 

![image](https://user-images.githubusercontent.com/192271/66886238-a0b48f80-efce-11e9-8301-eca66caa63b3.png)

I can't run my test environment at the moment …

Recalling the trigger in #1131. If you close `about:addons` before a quit, then is the next run of 2019.10-current free from the bug until you revisit `about:addons`?

**Comment by troysjanda** [comment]
No, accessing about:settings or about:addons does not trigger this behavior.  This was a fresh install of Waterfox 2019.10 Current with the userchrome.css in use using either the light, or the dark will trigger this however the default theme seems to be unaffected.

Here was my process, 

- I downloaded and fresh installed Waterfox 2019.10 Current. 
- I placed my userChrome.css in to the profile sub directory folder chrome
- started Waterfox, the above image was the result.
- I accessed the hamburger menu, about:addons > theme and selected the default and the issue subsided.
- I Tested the dark theme as well with the same result as the light as shown in the image.
- I then went to the Firefox addons site and chose the White theme to install and did not suffer the same issue as light & dark.

I do not see any issue in this release related to my closed issue #1131 when accessing either about:settings or about:addons.

**Comment by grahamperrin** [comment]
Thanks, 

> downloaded 

Is there a link to a binary, or did you build yourself? 

(<https://www.waterfox.net/releases/> is very recently without a Current section. <https://www.waterfox.net/blog/waterfox-2019.10-release-download/> announces availability so I guess I simply hit the `/releases/` page at an unlucky time.)

**Comment by troysjanda** [comment]
> Is there a link to a binary, or did you build yourself?

I downloaded from the `https://www.waterfox.net/releases/`

Looks like he may have taken it down, was listed there this AM @about 1130 hours

Wont let me attach it here, I uploaded it to a host here is the link

Removed for discretion.

**Comment by grahamperrin** [comment]
Thanks, 

> Wont let me attach it here,

Maybe use https://send.firefox.com/ and share the link discreetly with me, through a private message in Reddit? 

> may have taken it down,

OK, re: `https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-536193316` I guess, the likeliest explanation is that a separate page for Current is in the pipeline. If this is true then discretion is not required `:-)` but let's be discreet, just in case. Thanks. 

PS my note re: discretion crossed paths with your edition :-)

**Comment by troysjanda** [comment]
> PS my note re: discretion crossed paths with your edition :-)

Had already posted prior to seeing your reply. once you download ill edit my post and remove this link

**Comment by grahamperrin** [comment]
@troysjanda got it now. Thanks.

**Comment by troysjanda** [comment]
There is a user on reddit that has a possible fix that seems to be working

https://www.reddit.com/r/waterfox/comments/djtq91/i_fixed_the_userchromecss_issue_with_waterfox/

I Confirmed this as a fix, all themes working with userChrome.css in use.

this is the Dark Theme ![](https://i.postimg.cc/yxbGGHtS/dark.png)
This is the Light Theme ![](https://i.postimg.cc/KcqCjPjv/light.png)

Download ( not my creation nor my work )
[7fZ5eLh.zip](https://github.com/MrAlex94/Waterfox/files/3746026/7fZ5eLh.zip)

Instruction on how to use,

> Go to "C:\Program Files\Waterfox Current\browser" Assuming you kept the default install directory and replace the file "omni.ja" with this modified "omni.ja" 

This is his explanation on what was changed,

> If you want to know what I edited, I copied the browser UI files from Firefox ESR 68.1.0, which is stored in "omni.ja" into Waterfox Current's "omni.ja" and it works

**Comment by grahamperrin** [comment]
Nit: your link at the head of https://github.com/MrAlex94/Waterfox/issues/1200#issuecomment-544022535 is broken

**Comment by grahamperrin** [comment]
>  a possible fix 

Breaks the menu bar on Linux: 

![VirtualBox_Manjaro_21_10_2019_03_05_16](https://user-images.githubusercontent.com/192271/67171618-d29f6a80-f3af-11e9-9cb1-73b3236bbbe9.png)

Not surprising, for a file that was taken from a Windows installation.

**Comment by troysjanda** [comment]
> 
> 
> Nit: your link at the head of [#1200 (comment)](https://github.com/MrAlex94/Waterfox/issues/1200#issuecomment-544022535) is broken

Fixed.

**Comment by troysjanda** [comment]
I downloaded the new build -- BuildID=20191022131008-- from `https://www.waterfox.net/releases/` this issue was not fixed. However the omni.ja still works.

**Comment by grahamperrin** [comment]
Meta, tracking: #538
