### ISSUE TITLE
Waterfox Classic and Current uninstall failures – an error in a system binary was detected

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1201]
68.0b1, 

`C:\Program Files\Waterfox Current\uninstall\helper.exe`

> An error in a system binary was detected. Try refreshing the PC to fix the problem. 

![2019-10-16 05:41:52](https://user-images.githubusercontent.com/192271/66889246-96e45980-efd9-11e9-9d93-3a5deb2087a4.png)

`uninstall.log` comprises: 

```text
File: \Accessible.tlb
File: \AccessibleHandler.dll
File: \AccessibleMarshal.dll
File: \api-ms-win-core-file-l1-2-0.dll
File: \api-ms-win-core-file-l2-1-0.dll
File: \api-ms-win-core-localization-l1-2-0.dll
File: \api-ms-win-core-processthreads-l1-1-1.dll
File: \api-ms-win-core-synch-l1-2-0.dll
File: \api-ms-win-core-timezone-l1-1-0.dll
File: \api-ms-win-crt-conio-l1-1-0.dll
File: \api-ms-win-crt-convert-l1-1-0.dll
File: \api-ms-win-crt-environment-l1-1-0.dll
File: \api-ms-win-crt-filesystem-l1-1-0.dll
File: \api-ms-win-crt-heap-l1-1-0.dll
File: \api-ms-win-crt-locale-l1-1-0.dll
File: \api-ms-win-crt-math-l1-1-0.dll
File: \api-ms-win-crt-multibyte-l1-1-0.dll
File: \api-ms-win-crt-private-l1-1-0.dll
File: \api-ms-win-crt-process-l1-1-0.dll
File: \api-ms-win-crt-runtime-l1-1-0.dll
File: \api-ms-win-crt-stdio-l1-1-0.dll
File: \api-ms-win-crt-string-l1-1-0.dll
File: \api-ms-win-crt-time-l1-1-0.dll
File: \api-ms-win-crt-utility-l1-1-0.dll
File: \application.ini
File: \chrome.manifest
File: \d3dcompiler_47.dll
File: \dependentlibs.list
File: \firefox.VisualElementsManifest.xml
File: \freebl3.chk
File: \freebl3.dll
File: \IA2Marshal.dll
File: \lgpllibs.dll
File: \libEGL.dll
File: \libGLESv2.dll
File: \mozavcodec.dll
File: \mozavutil.dll
File: \mozglue.dll
File: \msvcp140.dll
File: \nss3.dll
File: \nssckbi.dll
File: \nssdbm3.chk
File: \nssdbm3.dll
File: \omni.ja
File: \platform.ini
File: \plugin-container.exe
File: \plugin-hang-ui.exe
File: \precomplete
File: \qipcap64.dll
File: \removed-files
File: \softokn3.chk
File: \softokn3.dll
File: \ucrtbase.dll
File: \update-settings.ini
File: \updater.exe
File: \updater.ini
File: \vcruntime140.dll
File: \waterfox.exe
File: \xul.dll
File: \uninstall\helper.exe
File: \gmp-clearkey\0.1\clearkey.dll
File: \gmp-clearkey\0.1\manifest.json
File: \fonts\TwemojiMozilla.ttf
File: \defaults\pref\channel-prefs.js
File: \browser\blocklist.xml
File: \browser\chrome.manifest
File: \browser\omni.ja
File: \browser\VisualElements\VisualElements_150.png
File: \browser\VisualElements\VisualElements_70.png
File: \browser\features\formautofill@mozilla.org.xpi
File: \browser\features\screenshots@mozilla.org.xpi
DLLReg: \AccessibleMarshal.dll
DLLReg: \AccessibleHandler.dll
```

2019.10-current not yet tested.

**Comment by grahamperrin** [comment]
I have the same error for attempted uninstallation of Waterfox Classic 56.2.14. 

Taking a hint from https://www.thesaurus.com/browse/refreshing I'll take Microsoft's hint as meaning that my installation of Windows 10 has become _boring_ or _depressing_, so I'll _refresh_ it (whatever TF that means) and close this issue with an assumption that no other user will be <strike>bugged</strike>bored `:-/`

**Comment by MrAlex94** [comment]
I can't seem to reproduce - but would be interested to know why it might
occur 🤔

**Comment by grahamperrin** [comment]
> an error in a system binary was detected

This seems to be spurious. AFAICT the problem (probably PEBKAM) occurs when trying to uninstall, without admin privileges, a Waterfox that was installed **with** admin privileges. 

Off campus I can't get a view of what's required –

![2019-10-16 07:44 Administrators](https://user-images.githubusercontent.com/192271/66951268-e7979900-f051-11e9-8c43-9b5c5182f97f.png)

– to tell whether my memory re: group membership was mistaken but in a nutshell: 

- using a known good admin account (e.g. the one at the foot of the list in the screenshot above), each uninstallation succeeded. 

Sorry for the noise!
