### ISSUE TITLE
Automated presentation of https://www.waterfox.net/blog/waterfox-2019.10-release/?new 404 not found

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1202]
Installation then first run of Waterfox Classic `2019.10` is followed by automated opening of: 

- https://www.waterfox.net/blog/waterfox-2019.10-release/?new

– 404, not found 

Re: #582 @MrAlex94 for now (for simplicity) you might like to add a redirect to:

- https://www.waterfox.net/blog/waterfox-2019.10-release-download/

I see a recent tradition of `…-release-download` URLs so re: #538 if this tradition is to continue, the next version (or distributed build) of <strike>Waterfox </strike>Waterfox Classic might benefit from a code change. 

Thanks

**Comment by grahamperrin** [comment]
Probably specific to Classic. 

Installation of Waterfox _Current_ `2019.10` seems to be not similarly bugged. Borrowing from a recently closed issue: 

![image](https://user-images.githubusercontent.com/192271/66894878-686e7a80-efe9-11e9-9294-434adf3deb71.png)

**Comment by grahamperrin** [comment]
https://waterfox.net/blog/waterfox-2019.10-release/?new redirects to https://www.waterfox.net/blog/waterfox-2019.10-release-download/

Thanks

**Comment by MrAlex94** [comment]
😁
