### ISSUE TITLE
Waterfox Classic 2019.10 (20191014144542) and Waterfox Current 2019.10 (20191011232540) misrepresented as 56.3 and 68.0 respectively

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1204]
_Apps & Features_, Windows 10: 

![image](https://user-images.githubusercontent.com/192271/66962856-fee28080-f069-11e9-8657-c409f3ac8cb6.png)

**Comment by MrAlex94** [comment]
For all intents and purposes, this is by design for now.

**Comment by grahamperrin** [comment]
OK, thanks, so I removed the reference to (bug tracking) issue 538. 

Leave this open as a documentation issue? Or close and roll it into #582 under web site issues?

**Comment by grahamperrin** [comment]
From <https://redd.it/dn9yeb>: 

> … bound to lead to some confusion. If changing the versioning was meant to simplify things, then the displayed version should display the same everywhere, not just in the About Waterfox Classic box.

**Comment by MrAlex94** [comment]
Leave it open for now. Internal versioning needs to stay as 56 and 68. It would be a mess if add-ons etc started thinking the version actually was 2019.
