### ISSUE TITLE
[Bug] Theme Issues

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1208]
So WaterFox 56.2.14 has a problem where i cannot see my Downloaded Themes in the customize tab, not does the custom theme not apply. Here is a video of that :
![HnY9jbD4vw](https://user-images.githubusercontent.com/37266538/67083779-1588f480-f19c-11e9-971d-06e36136c472.gif)

**Comment by grahamperrin** [comment]
> 56.2.14

What's the build ID, and OS?

Is that [Futuristic Theme](https://addons.mozilla.org/addon/futuristic-theme/) 1.1 in your recording? 

Can you reproduce the bug with version 1.0? 

From a recording that I took for myself: 

![2019-10-18 19:24:46 frame](https://user-images.githubusercontent.com/192271/67119136-6faaa980-f1de-11e9-9f9d-b0686b0fcd29.png)

Can you reproduce the bug with any of these three? Attention to the versions:

- [Terminal Dark Grey …](https://addons.mozilla.org/addon/terminal-dark-grey/) 2.0 by HK-9000
- [Material Grey Dark](https://addons.mozilla.org/addon/material-greydark/) 2.0 by Firefox user 13327499
- [blacker than balck](https://addons.mozilla.org/addon/blacker-than-balck/) 2.0 by Firefox user 12828780

I have: 

- Terminal Dark Grey 1.0 by Jordan9000, ID `595720@personas.mozilla.org`
- Material Grey Dark 1.0 by Kisho, ID `861050@personas.mozilla.org`
- blacker than balck 1.0 by Anonymous user df5b42, ID `784041@personas.mozilla.org`

**Comment by ghost** [comment]
> What's the build ID, and OS?

I am running Windows 10 1903 64bit with the Build ID of 18362.418

> Is that [Futuristic Theme](https://addons.mozilla.org/addon/futuristic-theme/) 1.1 in your recording?

Yes, that is the Futuristic Theme 1.1 in the recording

> Can you reproduce the bug with version 1.0?

No, i cannot, I could not find the previous version there

> Can you reproduce the bug with any of these three? Attention to the versions:

All 3 themes worked but for some reason, they are not showing on the list of available themes in Customise

**Comment by grahamperrin** [comment]
> could not find the previous version there

Scroll down ▶ Version history ▶ See all versions

For convenience: 

- https://addons.mozilla.org/addon/futuristic-theme/versions/

> All 3 themes worked but for some reason, they are not showing on the list of available themes in Customise

Thanks, try the outdated versions: 

- https://addons.mozilla.org/addon/terminal-dark-grey/versions/
- https://addons.mozilla.org/addon/material-greydark/versions/
- https://addons.mozilla.org/addon/blacker-than-balck/versions/

**Comment by ghost** [comment]
>Scroll down ▶ Version history ▶ See all versions

Found it thank you

> Thanks, try the outdated versions:

2 of the themes were successful but Material Grey Dark failed to show the change
