### ISSUE TITLE
Waterfox Classic using the icon for Current; elsewhere, Waterfox Current using the icon for Classic

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1211]
Bugging builds 20191015002329 (Classic) and 20191015121210 (Current) on KDE Plasma: 

![2019-10-19 09:06:48](https://user-images.githubusercontent.com/192271/67140213-2f840f00-f250-11e9-8877-a25e36af7059.png)

1. Waterfox Classic 2019.10 (20191015002329) in the window to the left
2. Waterfox Current 2019.10 (20191015121210) to the right. 

Also, both applications appear as a single task in Task Manager: 

![2019-10-19 09:07:29](https://user-images.githubusercontent.com/192271/67140260-d7014180-f250-11e9-9330-579a08279857.png)

- Waterfox Classic misusing the icon for Waterfox Current
- Waterfox Classic appearing as _Waterfox_ (not Classic)
- <strike>Waterfox Current apparently nameless</strike> my mistake, I misunderstood the GUI of Task Manager.

Some overlap with: 

- <strike>`#769` (Firefox branding still shown in Waterfox)</strike>
- #1210 (If Waterfox Current 2019.10 runs first, then Waterfox Classic 2019.10 will not run). 

Meta, tracking: #538

**Comment by hawkeye116477** [comment]
I have another situation, Waterfox Current uses Classic icon.

**Comment by grahamperrin** [comment]
LOL poor Alex, poor you! 

What are the build IDs and desktop enviroment in your case?

**Comment by hawkeye116477** [comment]
It's my own build from newest commit and I'm on KDE Plasma.

**Comment by hawkeye116477** [comment]
`misrepresented as Mozilla Firefox in title bars,`
I guess that's after installing langpack from AMO.

**Comment by grahamperrin** [comment]
> I guess that's after installing langpack from AMO.

Exactly! Now I understand, thanks. https://github.com/MrAlex94/Waterfox/pull/1213#issuecomment-544143709 down-voting myself. 

A screen recording – beginning with a preference for English (United Kingdom), switching to English (United States): 

- [2019-10-19 19:01.zip](https://github.com/MrAlex94/Waterfox/files/3747035/2019-10-19.19.01.zip)

**Comment by aquaspy** [comment]
Any fix to this? :(

**Comment by grahamperrin** [comment]
@aquaspy does Waterfox Classic 2019.12 have the issue?

**Comment by grahamperrin** [comment]
Waterfox Classic 2019.10 to the left, Waterfox Classic 2019.12 to the right: 

![Waterfox Classic 2019 10, Waterfox Classic 2019 12, Manjaro Linux](https://user-images.githubusercontent.com/192271/70595595-ad72ef80-1bdb-11ea-9dfc-7161dccc73d6.png)

**Comment by grahamperrin** [comment]
Waterfox Classic `2020.03.1 (20200312161605)` on Linux:

![image](https://user-images.githubusercontent.com/192271/77849584-be646280-71c4-11ea-8276-cdc7c75990d1.png)

**Comment by hawkeye116477** [comment]
@grahamperrin I can't reproduce that now, from latest version it uses correct icon.

**Comment by grahamperrin** [comment]
> … latest version …

Build `20200312161605`, yes?

**Comment by hawkeye116477** [comment]
@grahamperrin Yes
