### ISSUE TITLE
Request: Allow webextensions to run on built-in pages (Waterfox-Current)

### ISSUE THREAD

**Issue by VelvetShadows** [MrAlex94/Waterfox#1214]
I am using a mouse gestures extension and it is unable to run on pages like the Firefox new tab page, about:config, etc.
Not running on the new tab page is especially annoying, and really breaks the usage patterns I've developed when all the gestures I use everywhere else to navigate/close/open a tab cease working.  

Is there any way Waterfox can ever allow webextensions to run on these pages?

**Comment by grahamperrin** [comment]
Mozilla bug [1269456 - [meta] Add permission to allow extensions to load semi-privileged URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1269456) (NEW)

In the dependency tree: 

- [1420105 - allow extensions to load about:downloads](https://bugzilla.mozilla.org/show_bug.cgi?id=1420105) (UNCONFIRMED)
- [1420405 - allow extensions to open the default new tab page (about:newtab)](https://bugzilla.mozilla.org/show_bug.cgi?id=1420405) (UNCONFIRMED)
- [1420406 - allow extensions to open about:addons](https://bugzilla.mozilla.org/show_bug.cgi?id=1420406) (UNCONFIRMED) with gesture add-ons mentioned in [comment 2](https://bugzilla.mozilla.org/show_bug.cgi?id=1420406#c2). 

Linked but not in the tree: 

- [1266960 - Extensions can not load file: URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1266960) (NEW)
- [1317166 - Allow opening data: URIs from tabs.create](https://bugzilla.mozilla.org/show_bug.cgi?id=1317166) (NEW)

All six have my vote. 

I'd like the same for Waterfox Current. I should not expect all such allowances to be a default.

**Comment by casmodin** [comment]
Yes!  Please add this. Is it possible?
This is the a real inhibiting factor to using Waterfox Current.
