### ISSUE TITLE
many addons stopped working properly

### ISSUE THREAD

**Issue by dagaz** [MrAlex94/Waterfox#1219]
Since the update from waterfox-kde 56.2.14 to 2019.10 (Arch Linux) many addons stopped working properly:

For example:
uBlock origin: the element picker is not longer opening
Tampermonkey: user scripts won't load

In Waterfox current the problem was the same. But If you disable content blocking, everything works fine again. 
Sadly in waterfox-kde there is no option for that.

**Comment by strotee** [comment]
https://github.com/MrAlex94/Waterfox/issues/1199

**Comment by hawkeye116477** [comment]
@dagaz Try new release.

**Comment by dagaz** [comment]
Thanks for the effort - but it still does not work.
```
$ waterfox --version
Mozilla Waterfox 56.3
```
The installed Waterfox version is:
```
$ pacman -Q waterfox waterfox-i18n-de 
waterfox-kde 2019.10-1
waterfox-i18n-de 2019.10-1
```
KDE Plasma is version 5.17.1-1, Kernel is 5.3.7-arch1-1-ARCH. 

Tampermonkey does still not load scrips (example: youtube.com and the [viewtube-Script](http://sebaro.pro/viewtube/files/viewtube.user.js) from [sebaro](http://sebaro.pro/viewtube/?ln=en)
Still the same Problem with uBlock Origin: I can not open the element picker

Is there a config option that might be set wrong?

**Comment by hawkeye116477** [comment]
@dagaz Sorry, looks like I hurried up a little and selected wrong commit, but proper release no 2 should be in about 1-2 hours.

Update: Looks like OBS worker made me joke and not send new release to repo and triggered rebuild by itself, so update maybe little later. Sorry for delay. Usually build for Classic takes about an hour, but sometimes it doesn't push instantly updated version to repo.

**Comment by dagaz** [comment]
Thats fine and I can wait. (The downgraded version works fine.)

I just check https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/Arch/x86_64/ if the new package arrives and write if it works here when I get it.

**Comment by hawkeye116477** [comment]
Ok, however if you want you can also download it manually from https://build.opensuse.org/package/binaries/home:hawkeye116477:waterfox/waterfox-kde/Arch and install it with pamac, but you will need account registered.
Today it made me that joke again and rebuilded by itself. Seems that something is not right on SUSE's side, even packages for Debian aren't picked by scheduler (usually they were picked in  about few hours).

**Comment by dagaz** [comment]
The build arrived in the repo just now. 

Very good, everything is working again as it should.

Thank you for fixing!
