### ISSUE TITLE
Current Version

### ISSUE THREAD

**Issue by topnotchaero** [MrAlex94/Waterfox#1227]
Will legacy add-ons work with the current version?

**Comment by hawkeye116477** [comment]
They will work if someone modify it.
https://github.com/MrAlex94/Waterfox/wiki

**Comment by Telmesomething** [comment]
> Will legacy add-ons work with the current version?

Well, if you think about it there wouldn't be any point in maintaining the Classic version if the new flavor supported legacy extensions.

**Comment by Telmesomething** [comment]
Oddly enough I was able to install both CTR and uBlock Origin on 2019.10

![CTR installed on 2019-10](https://user-images.githubusercontent.com/33827636/67600159-c16caa00-f771-11e9-8ff1-8d2754e3cc2d.jpg)

However, I couldn't do much with either of them. With CTR buttons couldn't be moved and spaces couldn't be added. With uBlock no menus were available. 

Worst of all though 56.2.14 didn't appear to be installed anymore having been completely overwritten by the new flavour. I ran Windows 8.1 System Restore to get back to 56.2.14 again. I'll let somebody else be the guinea pig now.

**Comment by hawkeye116477** [comment]
@Telmesomething It was fixed, you might have some old buildid.

**Comment by grahamperrin** [comment]
This issue is for Waterfox _Current_, not for Waterfox Classic. 

@Telmesomething please raise a separate issue. Thanks

**Comment by grahamperrin** [comment]
PS, maybe some misunderstanding around the new approach to versioning. 

2019.10 = two quite different flavours of Waterfox (if we think of Classic and Current as _flavours_). 

The first screenshot at https://new.reddit.com/r/waterfox/comments/dmtmpq/-/ might help to tell the difference.

**Comment by Telmesomething** [comment]
Sorry Graham, I have to apologize. I downloaded Classic instead of Current simply because I didn't scroll further down the releases page. I've now installed the correct one and it works just fine. 

Maybe it might be a good idea to reverse the layout so that Current appears at the top?

**Comment by grahamperrin** [comment]
Thanks, 

> layout

▶ https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-541384643 – I'll quote you and reply there.
