### ISSUE TITLE
Can both versions be installed on the same machine?

### ISSUE THREAD

**Issue by Telmesomething** [MrAlex94/Waterfox#1228]
I understand from an article on [ghacks.net](https://www.ghacks.net/2019/10/25/waterfox-development-splits-into-classic-and-current-branches/) that the Classic version will be maintained indefinitely even though the new version called Current will also be available. 

But can both versions be installed on the same machine and if so, what would the correct procedure be?

Also, if both versions are to be maintained how will the Classic version be updated now that the later version has become available? In that respect the option to update to Current is available via the Help ---> About Waterfox menu tree.

My system is Windows 8.1 fully patched.

**Comment by grahamperrin** [comment]
> Can both versions be installed on the same machine?

Yes. Please see the support area, in particular: 

- answers to yesterday's https://redd.it/dmmfxv 

Also, amongst recent issues: 

- #1210

**Comment by Telmesomething** [comment]
Thanks Graham

**Comment by grahamperrin** [comment]
@Telmesomething I overlooked **Waterfox Profile Manager** and `about:profiles` use cases. 

https://www.reddit.com/comments/dmmfxv/-/f5zhu3h/ – there's a sticky and FYI: 

- [Waterfox Current (and Firefox Quantum) cause loss of some types of legacy extension when used to open Waterfox Classic profiles · Issue #983](https://github.com/MrAlex94/Waterfox/issues/983)
- [Backport (Firefox 67) downgrade protection to Waterfox Classic · Issue #1246 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/1246)
