### ISSUE TITLE
Consider flipping media.suspend-bkgnd-video.enabled on Waterfox Classic to return <55 and >57 behavior

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox#1229]
For god knows what reason this was disabled on Firefox 55 and 56, but is enabled on 54 and lower, and 57 and higher.

The 55/56 setting means every video open but paused is taking space in memory.

This could go a fair way into relieving Classic memory pressure.

**Comment by grahamperrin** [comment]
> 55

Maybe these two, the first of which was P1: 

- [1274919 - Resume suspended video decoders on tab mouse hover.](https://bugzilla.mozilla.org/show_bug.cgi?id=1274919)
- [1383653 - [Shutdown Decoder] video can only be suspended once.](https://bugzilla.mozilla.org/show_bug.cgi?id=1383653)

**Comment by Squall-Leonhart** [comment]
i found the reason and it was telemetry related


* [1380584 - [Shield] Pref Flip Study: Shutdown decoder.](https://bugzilla.mozilla.org/show_bug.cgi?id=1380584)
