### ISSUE TITLE
PoroFessor.gg not functional

### ISSUE THREAD

**Issue by SpellingSword** [MrAlex94/Waterfox#1231]
https://porofessor.gg/

League of Legends match look-up website PoroFessor doesn't work properly.

Looking up ANY game or lobby results in "The summoner is not in-game, please retry later. The game must be on the loading screen or it must have started"

It works in other browsers, so it must be Waterfox related.

**Comment by grahamperrin** [comment]
> Waterfox

Please describe what you use. 

The first screenshot at https://new.reddit.com/comments/dmtmpq/-/ may help you to describe which version of Waterfox you use.
