### ISSUE TITLE
Linux Mint 18.3 waterfox-classic-kpe but it is not going to be installed Error

### ISSUE THREAD

**Issue by LinuxUserNewbieForever** [MrAlex94/Waterfox#1232]
While I'm reporting this on my Linux Mint 18.3 XFCE based on Ubuntu 16.04 install, I also ran into the same problem on Xubuntu 18.04!

Waterfox has been running on my system for over a year without any problems.  Today I noticed that it said that there is an upgrade but it is not going to be upgraded.  I decided to try to figure out why.  It appears that I can not use waterfox-classic-kpe.  or even the old package simply called waterfox any more.  

**Follwing these Instructions:**
Link: https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox

For xUbuntu 16.04 run the following:
Keep in mind that the owner of the key may distribute updates, packages and repositories that your system will trust (more information).

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_16.04/ /' > /etc/apt/sources.list.d/home:hawkeye116477:waterfox.list"
wget -nv https://download.opensuse.org/repositories/home:hawkeye116477:waterfox/xUbuntu_16.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install waterfox

**My Result:**
sudo apt-get install waterfox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 waterfox : Depends: waterfox-classic-kpe but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by LinuxUserNewbieForever** [comment]
**More Info**
Preconfiguring packages ...
Selecting previously unselected package waterfox-classic-kpe.
(Reading database ... 778305 files and directories currently installed.)
Preparing to unpack .../waterfox-classic-kpe_2019.10-1_amd64.deb ...
Unpacking waterfox-classic-kpe (2019.10-1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1.1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22+linuxmint1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up waterfox-classic-kpe (2019.10-1) ...
update-alternatives: error: alternative path /usr/bin/waterfox-classic doesn't exist
dpkg: error processing package waterfox-classic-kpe (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 waterfox-classic-kpe
E: Sub-process /usr/bin/dpkg returned an error code (1)
A package failed to install.  Trying to recover:
Setting up waterfox-classic-kpe (2019.10-1) ...
update-alternatives: error: alternative path /usr/bin/waterfox-classic doesn't exist
dpkg: error processing package waterfox-classic-kpe (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 waterfox-classic-kpe

**Comment by hawkeye116477** [comment]
@LinuxUserNewbieForever  Please track https://github.com/hawkeye116477/waterfox-deb/issues/29

**Comment by hawkeye116477** [comment]
@LinuxUserNewbieForever If this fixed, then you can close issue

**Comment by LinuxUserNewbieForever** [comment]
@hawkeye116477 It seems to be fixed.  At least I'm not having any more problems.  Thanks for all you do!  I'm closing the issue.
