### ISSUE TITLE
Waterfox for android and google play

### ISSUE THREAD

**Issue by sfilie03** [MrAlex94/Waterfox#1233]
Hi, if you go to waterfox's main website you can see that there's a button on it to download waterfox for android from google play, but when you click it, it says "We're sorry, the requested URL was not found on this server.". So why does it say that, and how do you download waterfox for android? Thanks.

![waterfox website](https://user-images.githubusercontent.com/35790889/67627206-993e8300-f825-11e9-9988-0765bf0b3efe.jpg)

![waterfox for android google play](https://user-images.githubusercontent.com/35790889/67627208-9d6aa080-f825-11e9-95b9-bab2e87ca711.jpg)

waterfox 2019.10 (64-bit)

**Comment by grahamperrin** [comment]
Please join the earlier issue: 

- [I can't see Waterfox in Android Playstore · Issue WaterfoxCo/Waterfox#1085 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/1085)

Other Android-related issues (found by searching) include: 

- [F-Droid · Issue WaterfoxCo/Waterfox-Android#40](https://github.com/MrAlex94/Waterfox/issues/234)

**Comment by Telmesomething** [comment]
It may be the case that you have a 32-bit OS running on a 64-bit phone. This [article](https://www.howtogeek.com/253461/how-to-find-out-if-your-device-is-running-32-bit-or-64-bit-android/) explains how to check that. 

Without wishing to state the obvious if you have a 32-bit OS you won't be able to install Waterfox since the latter is 64-bit only.

**Comment by grahamperrin** [comment]
Please join the earlier issue, NB https://github.com/MrAlex94/Waterfox/issues/1085#issuecomment-546717292

**Comment by Ibuprophen** [comment]
Just to help spread the word regarding the 32-bit (ARM) Waterfox App,... 

The Beta version is still available on the Play Store that can only be seen/obtained by following the steps (outlined on the following post) requiring your signing up for the Beta version "first" and then you'll be able to see it on the Play Store. 

https://github.com/MrAlex94/Waterfox/issues/730#issuecomment-421647220 


Good Luck! 



~Ibuprophen

**Comment by sfilie03** [comment]
Ok, so how do you get the latest waterfox for android version on google play? Also, why isn't it on apkpure.com, or available directly from https://www.waterfox.net/releases/ and is there a way to get it on those websites? That would make it much easier for people to find and download it. Thanks, and have a nice day.

**Comment by grahamperrin** [comment]
> the latest 

Do you mean, 2019.10?

**Comment by Telmesomething** [comment]
> Just to help spread the word regarding the 32-bit (ARM) Waterfox App,...

How exactly does one track that version down _Ibuprophen_? It doesn't appear in the list when I search the Play store presumably because the Android version installed on my phone is 32-bit.

**Comment by Ibuprophen** [comment]
@Telmesomething, the following is how to obtain it... 

NOTE 1: This is for those who has a device and/or Firmware on your device that's specific to the ARM/ARMv7. I specified Firmware (above) as I do know that there's many devices that are ARM64 capable, but the manufacturer (for whatever reason) only provides ARM/ARMv7 specific Firmware. 

First subscribe by going the following link and select/click on the "Become a Tester" button.

https://play.google.com/apps/testing/org.waterfoxproject.waterfox

Once successful, go to the following Play Store link and you should see it now. 

https://play.google.com/store/apps/details?id=org.waterfoxproject.waterfox

I just tested the procedure again and it all still looks good to go. 

NOTE 2: If you ever select the "LEAVE" option (at the bottom portion within the Google Play Store), you will have to wait up to 15 minutes or so and start from the first step (above) to sign up again for the Beta to begin seeing the beta version on the Play Store. 

Good Luck and Enjoy! :-) 


~Ibuprophen

**Comment by grahamperrin** [comment]
<https://www.reddit.com/comments/dp49jk/-/f5uj1ne/?context=1>: 

>> …  apks directly in the download section there https://www.waterfox.net/releases/ …

> True, might as well do that at this stage. I’ll get a new build spun up.

**Comment by Telmesomething** [comment]
Thanks ~Ibuprophen.

**Comment by 09dgceph** [comment]
> 
> 
> https://www.reddit.com/comments/dp49jk/-/f5uj1ne/?context=1:
> 
> > > …  apks directly in the download section there https://www.waterfox.net/releases/ …
> 
> > True, might as well do that at this stage. I’ll get a new build spun up.

@MrAlex94 any word on a new build to be hosted on your site?
