### ISSUE TITLE
waterfox Website does not explain the differnce beetween waterfox editions (classic vs current)

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [MrAlex94/Waterfox#1235]
https://www.waterfox.net/releases/

it does not indicate anywhere what are the different features and design goals of each edition

P.S. i do not know what is the best place for me to post it i know it is not a code issue

**Comment by Telmesomething** [comment]
Suggest you read this very informative article on [ghacks.net](https://www.ghacks.net/2019/10/25/waterfox-development-splits-into-classic-and-current-branches/)

**Comment by MrAlex94** [comment]
I’m updating the website to make it a little more clear :-)

**Comment by grahamperrin** [comment]
@MrAlex94 thanks @Kallinteris-Andreas @Telmesomething FYI https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-546688254
