### ISSUE TITLE
ADP prepaid site shows up as not found on Waterfox, works fine on other browsers.

### ISSUE THREAD

**Issue by derram** [MrAlex94/Waterfox#1239]
https://www.visaprepaidprocessing.com/ADP/PayRoll/Home/Index

Just started happening within the last few days, so I believe it's a change on their end.

**Comment by hawkeye116477** [comment]
It works fine for me.

**Comment by derram** [comment]
Might be something specific to the Linux build then.

It's happening for me across two different machines and even after restarting with add-ons disabled. 

Site is just redirecting to https://www.visaprepaidprocessing.com/PageNotFound.html

**Comment by hawkeye116477** [comment]
@derram But I'm on Linux. 
Are you using Classic or Current and which version?

**Comment by derram** [comment]
Classic and 2019.10 (64-bit)

**Comment by derram** [comment]
Restarting in safe mode and then selecting "Refresh Waterfox" fixed the issue.

Bit annoying to have to redo some things, but I was having issues with other sites like Twitter as well so it had to be done.
