### ISSUE TITLE
Amazon Music no audio playback

### ISSUE THREAD

**Issue by storm37000** [MrAlex94/Waterfox#1243]
Media resource could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) Details: void __cdecl mozilla::EMEDecryptor::Decrypted(const struct mozilla::DecryptResult &): decrypted.mStatus=3

**Comment by storm37000** [comment]
Im using Waterfox Classic 2019.10

**Comment by hawkeye116477** [comment]
Maybe related => https://bugzilla.mozilla.org/show_bug.cgi?id=1379928.
@storm37000 What OS and build id (`about:support`) ?

**Comment by storm37000** [comment]
Build ID 	20191022125504
OS 	Windows_NT 10.0

**Comment by hawkeye116477** [comment]
@storm37000 Strange, in case of me, shows pop-up with some decoding error, but after closing it, works fine.
Can you tell song's title which doesn't play for you?

**Comment by storm37000** [comment]
https://music.amazon.com/albums/B01NBTUM2N
