### ISSUE TITLE
Waterfox Classic 2019.10 breaks functionality of Tab Groups Manager revived

### ISSUE THREAD

**Issue by JulianRagan** [MrAlex94/Waterfox#1244]
Hi!
The new release broke Tab Groups Manager's ability to open a bookmark folder in new tab group (tabs open in the current group, can be moved to new group) and it fails to load hibernated tabs (it opens new group, but does not reopen tabs).

**Comment by grahamperrin** [comment]
> open a bookmark folder in new tab group 

`TypeError: TabGroupsManager.overrideMethod is undefined` `  TabGroupsManager.js:1139:11`
▼
`TabGroupsManager.Places.prototype.allOpenInNewGroup` `chrome://tabgroupsmanager/content/TabGroupsManager.js:1139:11`
`allOpenInNewGroup` `chrome://tabgroupsmanager/content/TgmPlaces.js:23:5`
`oncommand` `chrome://browser/content/browser.xul:1:1`

----

> fails to load hibernated tabs

`TypeError: TabGroupsManager.overrideMethod is undefined` `TabGroupsManager.js:3549:7`
▼
`TabGroupsManager.GroupClass.prototype.restoreTabs` `chrome://tabgroupsmanager/content/TabGroupsManager.js:3549:7`
`TabGroupsManager.GroupClass.prototype.setGroupDataWithAllTabs` `chrome://tabgroupsmanager/content/TabGroupsManager.js:3725:7`
`TabGroupsManager.GroupsStore.prototype.restoreGroup` `chrome://tabgroupsmanager/content/TabGroupsManager.js:4751:5`
`TabGroupsManager.GroupsStore.prototype.onMenuitemCommand` `chrome://tabgroupsmanager/content/TabGroupsManager.js:4845:3`
`TabGroupsManager.GroupsStore/this.menuitemCommandEvent` `chrome://tabgroupsmanager/content/TabGroupsManager.js:4702:47`

----

Apparent regression confirmed with Waterfox Classic 2019.10 (20191023220600) on Linux. 


Meta, tracking: #538

Tags: 

- `2019.10-classic-1` (`20191023220600` is a match)
- `2019.10-classic` (below, https://github.com/MrAlex94/Waterfox/issues/1244#issuecomment-547688227).

**Comment by grahamperrin** [comment]
- caa:addon/tabgroups-manager-revived
- https://bitbucket.org/tabgroupsmanager/

I wondered whether we have a GitHub ID for any the four developers. Taking the four links from https://web.archive.org/web/20160731032921/https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager-revived/ finds no association with any other extension. 

https://bitbucket.org/tabgroupsmanager/tabgroupsmanager/src/135bf5aab07b52092568ca102e38c14b0433e469/chrome/content/TabGroupsManager.js?at=develop#TabGroupsManager.js-5418

**Comment by grahamperrin** [comment]
At quit time, a JavaScript modal dialogue: 

> TabGroups Manager failed to save the session correctly. 
> 
> It is possible TGM was unable to save the Hibernated Groups etc correctly. 
> 
> TabGroups Manager exported the session data to the file. 
> 
> Even if data was saved incorrectly, it's possible TGM can restore the session when dropping the exported file into Firefox. 
> 
> TabGroups Manager will not export if "Cancel" is selected in the Save dialog window. 
> 
> If you select the session in the GroupBar session menu, the old session may be restorable.

At save time: 

```
NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS
[JavaScript Error: "browser is undefined" {file: "resource:///modules/sessionstore/TabState.jsm" line: 100}]'[JavaScript Error: "browser is undefined" {file: "resource:///modules/sessionstore/TabState.jsm" line: 100}]' when calling method: [nsISessionStore::getBrowserState]

File: undefined
Line: 775
Stack:
TabGroupsManagerJsm.SaveData.prototype.saveFileFromTgmData@resource://tabgroupsmanager/modules/TabGroupsManager.jsm:775:24
TabGroupsManager.Session.prototype.exportSession@chrome://tabgroupsmanager/content/TabGroupsManager.js:1315:7
TabGroupsManager.Session.prototype.exportDataEmergency@chrome://tabgroupsmanager/content/TabGroupsManager.js:1301:3
TabGroupsManagerJsm.SaveData.prototype.exportDataEmergency@resource://tabgroupsmanager/modules/TabGroupsManager.jsm:535:3
TabGroupsManagerJsm.SaveData.prototype.saveLatestData@resource://tabgroupsmanager/modules/TabGroupsManager.jsm:553:5
TabGroupsManagerJsm.QuitApplicationObserver.prototype.quitApplicationGranted@resource://tabgroupsmanager/modules/TabGroupsManager.jsm:1271:3
TabGroupsManagerJsm.QuitApplicationObserver.prototype.observe@resource://tabgroupsmanager/modules/TabGroupsManager.jsm:1243:36
goQuitApplication@chrome://global/content/globalOverlay.js:65:3
oncommand@chrome://browser/content/browser.xul:1:1
```

**Comment by grahamperrin** [comment]
At least one of the symptoms is also found with build `20191015002329`. 

https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads#201910-classic ▶ 

- https://github.com/MrAlex94/waterfox/compare/56.2.14...2019.10-classic

Re: apparent regression between tags `56.2.14` and `2019.10-classic`, can anyone identify the relevant commit(s)?

@miguelromero2000 might this benefit from an issue or pull request at <https://bitbucket.org/tabgroupsmanager/tabgroupsmanager/src/develop/>?

**Comment by hawkeye116477** [comment]
Possible replacement => https://addons.mozilla.org/pl/firefox/addon/tabby-manager/ or https://addons.mozilla.org/pl/firefox/addon/sync-tab-groups.

**Comment by orwel01** [comment]
Hi, sorry I am not a developer, but a long-year user of WF and TGM. TGM is one of the greatest addon in my opinion (you can search the web, you will see i am not the only one) and at this time THERE IS NO RELEVANT REPLACEMENT. I tested about 10 different addons from FF addons and no one brings the functionality of TGM or works properly in WF (last test 2019.12), maybe neither in FF (ratings of such addons are mostly low). It would be great if this problem could be fixed, if it is caused by the new version of WF. For me, I am stock on version 56.2 due my need of this addon for the work.

**Comment by forestmountain** [comment]
Privately I also jumped from FF to Waterfox for the same reason: to continue using TGM revived. Lately I have run into so many issues. At work I'm always using latest FF and have been testing the Tree Tabs add-on which I now have found to be the best replacement to TGM revived. Tree Tabs (https://addons.mozilla.org/da/firefox/addon/tree-tabs/) can do all what TGM can do and way more. It's pretty advanced. I have decided not to waste more time on the old add-on.

**Comment by grahamperrin** [comment]
Cross reference https://redd.it/fd4bjq

**Comment by L-VV** [comment]
Try this fix, it helped me:
https://bitbucket.org/tabgroupsmanager/tabgroupsmanager/pull-requests/1/add-objectprototypewatch-shim-for-pale/diff

**Comment by JulianRagan** [comment]
I have inserted the code from the snippet, and it broke it even further, tab bar did not display, must be PaleMoon specific fix. At least that is how it looks to someone, who can at best edit the JS file, i don't do JS.

**Comment by L-VV** [comment]
Sorry, I don't know (

But for PaleMoon it works fine.

Maybe someone can adapt this fix for Waterfox too.
