### ISSUE TITLE
Video Thumbnail in Google News – Mac OS X 10.7.5.

### ISSUE THREAD

**Issue by pjpreilly** [MrAlex94/Waterfox#1245]
The thumbnails with a video indicator do not display correctly in os x Lion on new.google.com.
There may be other instances but I'm not aware. I have included a good(chromium)/bad(waterfox/FF Legacy) instance. This display issue is apparent in current versions of Waterfox as well as FF Legacy on the os x Lion platform.
![Screenshot 2019-10-29 at 1 51 46 PM](https://user-images.githubusercontent.com/10430084/67795922-7692b100-fa55-11e9-8839-9d71dd34bd56.png)
![2019-10-29 01 53 29 pm](https://user-images.githubusercontent.com/10430084/67795937-7d212880-fa55-11e9-85ca-3671e85b1535.png)

**Comment by pjpreilly** [comment]
.. Notice the down caret does not display correctly. This seems to be related to **[THIS](https://www.reddit.com/r/waterfox/comments/alt6pm/google_calendar_rendering/)**

**Comment by grahamperrin** [comment]
Meta, tracking: #538 

Not reproducible with tag `2019.10-classic-1` Waterfox Classic 2019.10 (20191023220600) on Manjaro Linux: 

![image](https://user-images.githubusercontent.com/192271/67819934-247e7980-faaf-11e9-8c28-244f9c3aced6.png)

@pjpreilly please add a tail to the subject line:  

>  – Mac OS X 10.7.5

Thanks

**Comment by MrAlex94** [comment]
If this is still an issue, I doubt it will be looked into.
