### ISSUE TITLE
Waterfox Profile Manager should gain a distinctive title and content in both Waterfox Classic and Waterfox Current

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1247]
From #1246:

> there's nothing in the name of a profile to hint that it should be avoided when using either Waterfox Profile Manager or Waterfox Profile Manager.

If it's reasonably easy to have distinctive names/titles for the applications, let's do this: 

- Waterfox Classic Profile Manager
- Waterfox Current Profile Manager

Also, window content. Here's the generic phrase _Waterfox_: 

![image](https://user-images.githubusercontent.com/192271/67824145-7cbc7800-fabd-11e9-99ad-60c1cb0ada7c.png)

Meta, tracking: #538 

Suggested priority: fix before the next tag/distribution. 

Rationale: improve orientation; reduce the risk of misuse of a Waterfox Current profile by Waterfox Classic and vice versa.

A separate issue because I guess that this will be easier (quicker) to fix than #1246 …

**Comment by hawkeye116477** [comment]
For Current fix is on https://github.com/MrAlex94/Waterfox/commit/46ac9442f23453ccb53f75c49ed5a8d038799349
