### ISSUE TITLE
Opening url crashes WF

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1249]
https://tamogatas.index.hu/

WF 56.2.14

Edit:
Actually the first attachment had a lot of noise: I can also reproduce the crash in my clean profile:
[about:support](https://github.com/MrAlex94/Waterfox/files/3795602/Clipboarder.2019.10.31-002.txt)

**Comment by grahamperrin** [comment]
Thanks for the troubleshooting information, can you repeat it using the **Copy text to clipboard** button? (Easier to read, on screen, than raw data.)

Can you reproduce the issue with more recent (Windows) build 20191022125504 of Waterfox Classic 2019.10?

----

Here, no crash with heavily extended home-built Waterfox Classic 56.2.14 (20191007063316) on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/67994361-ca132380-fc3c-11e9-9eec-1d7cabdeff5a.png)

Screen recording: [2019-11-01 00:14.zip](https://github.com/MrAlex94/Waterfox/files/3796245/2019-11-01.00.14.zip)

**Comment by mzso** [comment]
> 
> 
> Thanks for the troubleshooting information, can you repeat it using the **Copy text to clipboard** button? (Easier to read, on screen, than raw data.)
> 
It's also not english.

> Can you reproduce the issue with more recent (Windows) build 20191022125504 of Waterfox Classic 2019.10?
> 

I don't use that version yet.

**Comment by grahamperrin** [comment]
Thanks, 

> not english.

Still, easier (for me) to interpret some of what I'd like to see …
