### ISSUE TITLE
Linux version (Classic) has memory leak issue

### ISSUE THREAD

**Issue by tcreek** [MrAlex94/Waterfox#1250]
This has been going on for a while.

With each version advancement, the issue only gets worse. I  use Waterfox daily on a laptop, and rather  than shut the laptop off, I put it to sleep daily. A few months ago, I would have to shut down Waterfox after a couple of weeks,

After this newest version of "Classic 2019.10," it has only gotten much worse. I am down to every other day, I am having to shut down Waterfox.

Previous version, it was about 5-6 days.

This laptop has 16GB of RAM and Waterfox ends up using 90% of that after a couple of days.

**Comment by grahamperrin** [comment]
Thanks. 

Reproducible with Waterfox Classic in safe mode? 

- about:support

Reproducible with a new profile? 

- about:profiles

Which operating system?

Which build of 2019.10?

**Comment by Kallinteris-Andreas** [comment]
can confirm same here 
```
[master-andreas@master-pc ~]$ uname -a
Linux master-pc 5.3.12-1-MANJARO #1 SMP PREEMPT Thu Nov 21 10:55:53 UTC 2019 x86_64 GNU/Linux
```
this is intepentant of profile and add-ons i have tested it

**Comment by grahamperrin** [comment]
@Kallinteris-Andreas above, the same questions to you.
