### ISSUE TITLE
New datepicker pop-up on Todoist doesn't work

### ISSUE THREAD

**Issue by Quintum** [MrAlex94/Waterfox#1251]
When [trying to click the reschedule button](https://i.imgur.com/PtGF7Xl.gif), on a specific task or on the multiple task selection drop-down, the task(s) gets marked but the action does not open the reschedule popup.

This feature does function properly on the latest versions of Firefox and Otter, so the rendering engine (version) that specifically Waterfox is using seems to be the issue.

Since this is however a core function in Todoist, this is quite annoying.

**Comment by grahamperrin** [comment]
https://todoist.com/app#

Waterfox **Classic** 56.2.14 (20191007063316) on FreeBSD-CURRENT: 

```text
ReferenceError: event is not defined Col_AppCollection-fde608.js:62:12748
	value https://d3ptyyxy2at9ui.cloudfront.net/Col_AppCollection-fde608.js:62:12748
	value https://d3ptyyxy2at9ui.cloudfront.net/Col_AppCollection-fde608.js:6:996
	$partial/< https://d3ptyyxy2at9ui.cloudfront.net/ist_libs_bundle-38a62a.js:1:3659
	_handleEvent https://d3ptyyxy2at9ui.cloudfront.net/ist_libs_bundle-38a62a.js:1:14616
```

- https://d3ptyyxy2at9ui.cloudfront.net/Col_AppCollection-fde608.js:62:12748
- https://d3ptyyxy2at9ui.cloudfront.net/Col_AppCollection-fde608.js:6:996
- https://d3ptyyxy2at9ui.cloudfront.net/ist_libs_bundle-38a62a.js:1:3659
- https://d3ptyyxy2at9ui.cloudfront.net/ist_libs_bundle-38a62a.js:1:14616

**Comment by grahamperrin** [comment]
Not reproducible with Waterfox Current 2019.10 (20191022131008).

**Comment by Sa-Ja-Di** [comment]
Same like in #1252:

Event missing - as IE has implemented this, pages like that work in IE but refuse to work in Waterfox classic or Pale Moon/Basilisk

This one has to be implemented to remove that issue=
https://bugzilla.mozilla.org/show_bug.cgi?id=218415

**Comment by endolith** [comment]
Selecting multiple tasks and clicking the Schedule button does nothing in Waterfox 2019.10 and Todoist Version 972. 

![image](https://user-images.githubusercontent.com/58611/71186879-f9f9a300-224b-11ea-9446-224160e1f0a8.png)


Spoofing User Agent as Firefox 71 offers to upgrade to version 983 but it doesn't actually upgrade.

![2019-12-19 10_33_28-Today_ Todoist - Waterfox Classic](https://user-images.githubusercontent.com/58611/71186810-d9314d80-224b-11ea-82f2-8264f963337f.png)

![image](https://user-images.githubusercontent.com/58611/71186826-e1898880-224b-11ea-8ac5-331a33a298e9.png)
