### ISSUE TITLE
Age verification unpassable on https://diablo.blizzard.com/ in waterfox classic

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox#1252]
Passes in Internet Explorer.

Page is supposed to continue after entering the last digit.

**Comment by grahamperrin** [comment]
Which version? 

https://diablo.blizzard.com/

With home-built Waterfox Classic 56.2.14 (20191007063316) on FreeBSD-CURRENT: 

```text
ReferenceError: event is not defined  _app.js:1:9269
	e/< https://d29z11wvk6phpt.cloudfront.net/assets/_next/static/JezBH993WidkE0EBpnu1i/pages/_app.js:1:9269
	e/< https://d29z11wvk6phpt.cloudfront.net/assets/_next/static/JezBH993WidkE0EBpnu1i/pages/_app.js:1:8330
	e/</< https://d29z11wvk6phpt.cloudfront.net/assets/_next/static/JezBH993WidkE0EBpnu1i/pages/_app.js:1:8649
	nrWrapper https://diablo.blizzard.com/en-gb/:1:14023
```

**Comment by Squall-Leonhart** [comment]
2019.10 Windows.

**Comment by Sa-Ja-Di** [comment]
Is most likely this one here. To make pages like that work, this complex issue has to be implemented!

https://bugzilla.mozilla.org/show_bug.cgi?id=218415

**Comment by grahamperrin** [comment]
> 2019.10 Windows.

Waterfox Classic 2019.10 or Waterfox Current 2019.10?

I _guess_ Waterfox Classic; certainty will be better. 

(I can't run Waterfox Current at the moment; can not compare.)

**Comment by grahamperrin** [comment]
Incidentally, how to re-trigger the age verification in a browser where verification has succeeded? (I tried deleting all cookies from the browser, that wasn't enough.)

**Comment by hawkeye116477** [comment]
Window.event is now deprecated. Anyway, looks like they are now using Custom Elements.
