### ISSUE TITLE
Legacy XUL extensions that use dialogs for settings do not work on Waterfox Currrent.

### ISSUE THREAD

**Issue by forkiesassds** [MrAlex94/Waterfox#1258]
Some legacy XUL extensions such as "Password Export" do not work at all, as they use a window dialog for settings. Will XUL support be as good as on Waterfox Classic? The version I tried on is Current 2019.10, I would like to use Current and not Classic as I use websockets.

**Comment by grahamperrin** [comment]
If I understand correctly: Waterfox Current is not designed to work with _non-modified_ legacy extensions.

**Comment by NebelNidas** [comment]
@grahamperrin Which is really unfortunate. @MrAlex94 himself said it's not much work to adjust the add ons, you just have to replace some XUL stuff with WebExt compatible HTML one... Considering most add ons are no longer maintained, it would be better if Alex could write a wrapper that basically tries to do that by itself. I unfortunately don't know enough C++ and Firefox structure to do it myself (would really love to help; but am quite busy as of now), but investing his time for this will almost eliminate the need of further maintaining WF Classic, which in return seems like a good compromise.

**Comment by grahamperrin** [comment]
I'd like to retry modifying a legacy extension. I tried, failed, a few months ago; could not put the documentation into practice for myself. 

> a wrapper 

If this were feasible, I _imagine_ that a larger project such as Thunderbird might have done so.

**Comment by hawkeye116477** [comment]
@forkiesassds Seems that there is alternative as app => https://github.com/kspearrin/ff-password-exporter.

**Comment by forkiesassds** [comment]
> @forkiesassds Seems that there is alternative as app => https://github.com/kspearrin/ff-password-exporter.

The addon I used doubled as a password importer
