### ISSUE TITLE
Waterfox Classic: reinstate UA string overrides for platforms other than Windows

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1260]
For example: 

https://github.com/MrAlex94/Waterfox/commit/3d735123dd028d1b306cfb0031a4099e3ed4f87f#diff-61cac4855c1bb1dd3e264ed799753d4fR47

- was one of three OS-specific overrides for Trello
- was, more generally, amongst the set of neat set of overrides that was implemented a few months ago, <https://github.com/MrAlex94/Waterfox/issues/985#issuecomment-499626903>.

Overrides such as these seem to be missing from Waterfox Classic 2019.10 (20191023220600) on Linux so, for example: 

![image](https://user-images.githubusercontent.com/192271/68524557-7352bd00-02c0-11ea-8fa7-6c340edc90b0.png)

- https://trello.com/b/KX3hV8XS/activity-stream-desktop
- 20191022125504 on Windows to the left
- 20191023220600 on Linux to the right with the uppermost yellow alert, 

> This version of Firefox is not supported. Please [upgrade to a supported version](https://www.firefox.com/).

I have not tested Waterfox Classic 2019.10 (20191022184353) on Mac OS X but if I understand correctly (from <https://github.com/MrAlex94/Waterfox/pull/1203/commits/02999ce8d80bd2d996e61faaec654a69820d6c65>): 

- Macs are similarly bugged. 

The need to restore overrides for Linux is explicit near the head of #1203 but the PR there is for _minor_ improvements. 

I reckon, the loss of overrides has the potential to be relatively _major_. Override discussions have been noisy in the past so let's nip this in the bud :-)

Meta, tracking: #538 

### Side note

Re https://www.reddit.com/comments/bup65x/-/epi08aa/ Trello is probably a fine example of a site that: 

- does **not** require an OS-specific string
- accepts **terse**, in this case:

`Firefox/60.0`

– and (as usual) given the 56.⋯ essence of Waterfox Classic, I favour `60.0` (as a former ESR) unless there's a known good reason to stretch the pretence higher to `68.0` for a site.

**Comment by hawkeye116477** [comment]
I already added that for Linux in https://github.com/MrAlex94/Waterfox/pull/1203

**Comment by hawkeye116477** [comment]
Just accept my PR, all should be good, I tested on Windows and Linux :smile:.

**Comment by grahamperrin** [comment]
Yesterday's merge https://github.com/MrAlex94/Waterfox/pull/1203#event-2785316106 noted with thanks. 

Is https://github.com/MrAlex94/Waterfox/commit/02999ce8d80bd2d996e61faaec654a69820d6c65#diff-96352d26103d2e2f5d0a8579538d4801R152 (no change) the Mac use case? 

I hesitate before closing this issue because reading between the lines of something in Reddit, a few days ago, I got the impression that Mac users, too, were without the usual overrides.

**Comment by grahamperrin** [comment]
Fix confirmed, thanks! 

![Waterfox Classic 2019 12, Manjaro Linux](https://user-images.githubusercontent.com/192271/70643562-1b99cf80-1c39-11ea-83cc-b34fe34757cb.png)
