### ISSUE TITLE
Waterfox Current compatibility with Wayback Machine captures of AMO pages

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1261]
Whilst CAA is not compatible, https://github.com/JustOff/ca-archive/issues/62

### Enhancement request

Please consider adding, to Waterfox, the workaround that's integral to CAA: 

- https://github.com/JustOff/ca-archive/commit/f92ef05d4ed3141272a69f2d62eb620d4e745e06

Subject to licensing, agreement with @JustOff etc.. 

### Without a workaround

Pages such as this become difficult or impossible to browse: 

- https://web.archive.org/web/20171101222339/https://addons.mozilla.org/en-US/firefox/addon/simple-add-on-manager/

Waterfox Current 2019.10 to the left, Waterfox Classic 2019.10 to the right: 

![image](https://user-images.githubusercontent.com/192271/68537589-83b97500-035e-11ea-8177-c82cda7fe33b.png)

Pages such as this (a later capture, the redesigned AMO) suffer from split-second redirection to **Page not found**: 

- https://web.archive.org/web/20171108151914/https://addons.mozilla.org/en-US/firefox/addon/simple-add-on-manager/

**Comment by laniakea64** [comment]
Why bundle this in Waterfox?

The following uBlock Origin filters, derived from the CAA commit you linked, seem to fix the issues for me -
```
||web.archive.org/web/*/addons.mozilla.org/*/more
||web.archive.org/web/*/addons.cdn.mozilla.net/*/loading-more.gif
||web.archive.org/web/*/addons-amo.cdn.mozilla.net/amo-*.js
```

**Comment by grahamperrin** [comment]
I don't use uBlock Origin, any other approach? 

> Why bundle this in Waterfox?

Expect a proportion of the user base to find themselves at affected pages, sooner or later.

**Comment by laniakea64** [comment]
> I don't use uBlock Origin, any other approach?

Do you use some other content blocking extension that can do custom filters?

> > Why bundle this in Waterfox?
> 
> Expect a proportion of the user base to find themselves at affected pages, sooner or later.

Sorry but IMO that is not sufficient reason to hard-code a non-configurable URL filter into Waterfox.  Unlike CAA, these Wayback Machine links are not a specific feature of Waterfox.

OTOH, I do realise the Wayback Machine is the **very first** recommendation at https://www.waterfox.net/addons/ .

So if this workaround does get integrated into Waterfox, please ensure the Waterfox version is configurable through `about:config`:

1) Boolean pref to completely enable/disable it.

2) String pref to customise the regex of Wayback Machine URL paths to block (default to same as CAA).

**Comment by MrAlex94** [comment]
Well in the re-design of the website, there will be a link to it but it won’t be the first or as prominent. 

Also I suppose there’s no expectation of the archived AMO website to work on Current.

**Comment by grahamperrin** [comment]
> Do you use some other content blocking extension that can do custom filters?

Solely for test purposes: rarely, I enable uBlock Origin 1.16.4.11 for Waterfox Classic or 1.23.0 for Waterfox Current. 

Everyday use – limited to Waterfox Classic: I use [Malwarebytes Browser Guard](https://addons.mozilla.org/addon/malwarebytes/) (for Firefox 57, acknowledging that it's not officially supported for use with Waterfox Classic). 

> So if this workaround does get integrated into Waterfox, please ensure the Waterfox version is configurable through `about:config`:

+1

> I suppose there’s no expectation of the archived AMO website to work on Current.

Flip-side: the surprise of things not working. Users, maybe newcomers, imagining a bug in the application. Or imagining bad advice when they follow a link (maybe from Reddit) to a page that disappears from, or becomes unusable in, the window of Waterfox Current. 

Enhancement is not necessary :-) but it could be a very nice touch. In the same way that CAA simplified things for end users.
