### ISSUE TITLE
clang-9: error: unable to execute command: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by eojjn** [MrAlex94/Waterfox#1263]
Encountered this error while building on Arch. 
I'm new to all this so not sure where to begin to be honest.
I can't attach the files mentioned in the below code because .c and .sh files are not supported for upload.

`clang-9: error: unable to execute command: Segmentation fault (core dumped)
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to  and include the crash backtrace, preprocessed source, and associated run script.
clang-9: error: unable to execute command: Segmentation fault (core dumped)
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to  and include the crash backtrace, preprocessed source, and associated run script.
clang-9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /tmp/test-ctors-24721b.c
clang-9: note: diagnostic msg: /tmp/test-ctors-24721b.sh
clang-9: note: diagnostic msg

: 

********************
make[5]: *** [/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/config/rules.mk:791: test-ctors.o] Error 254
make[5]: *** Waiting for unfinished jobs....
clang-9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /tmp/test-array-f8688e.c
clang-9: note: diagnostic msg: /tmp/test-array-f8688e.sh
clang-9: note: diagnostic msg: 

********************
make[5]: *** [/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/config/rules.mk:791: test-array.o] Error 254
make[5]: Leaving directory '/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/obj-x86_64-pc-linux-gnu/build/unix/elfhack'
make[4]: *** [/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/config/recurse.mk:100: build/unix/elfhack/libs] Error 2
make[4]: Leaving directory '/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/obj-x86_64-pc-linux-gnu'
make[3]: *** [/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/config/recurse.mk:33: libs] Error 2
make[3]: Leaving directory '/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/obj-x86_64-pc-linux-gnu'
make[2]: *** [/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/config/rules.mk:452: default] Error 2
make[2]: Leaving directory '/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/obj-x86_64-pc-linux-gnu'
make[1]: *** [/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/client.mk:419: realbuild] Error 2
make[1]: Leaving directory '/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox'
make: *** [client.mk:170: build] Error 2
==> ERROR: A failure occurred in build().
`

**Comment by hawkeye116477** [comment]
Seems related:
https://www.linuxquestions.org/questions/slackware-14/llvm-9-0-0-clang-segfault-firefox-build-4175661799/
https://bugs.llvm.org/show_bug.cgi?id=43659
But I also has clang 9 and doesn't have that problem, strange.

**Comment by eojjn** [comment]
That does indeed look like the same issue. Looks to me like the only workaround is to use gcc as a compiler instead of clang, right?
One of the commenters mentioned the neccesary code to do this but it isn't clear to me where that should be inserted. Is it into the mozconfig file?

**Comment by hawkeye116477** [comment]
@eojjn Yes, that's for mozconfig, but for Classic it should look little different.
That change should be enough:
```
ac_add_options CC=/usr/bin/gcc
ac_add_options CXX=/usr/bin/g++
```

**Comment by eojjn** [comment]
should I do anything about the lines where clang is referenced?

`export CC=clang

export CXX=clang++`

**Comment by hawkeye116477** [comment]
@eojjn Just replace this
```
export CC=clang

export CXX=clang++
```
with
```
export CC=gcc

export CXX=g++
```

**Comment by eojjn** [comment]
OK I changed to gcc in the mozconfig file but I'm now getting gcc related errors

`configure: error: These compiler flags for C are invalid: -O3 -march=native -mtune=native -fcolor-diagnostics -w -fstack-protector-strong -fcf-protection=full -Wp,-D_GLIBCXX_ASSERTIONS -fno-plt
DEBUG: <truncated - see config.log for full output>
DEBUG: configure:14984: /usr/bin/gcc -std=gnu99 -o conftest  -fstack-protector-strong -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread   -fstack-protector-strong -lpthread -Wl,-O3,--no-omagic,--sort-common,--as-needed,--relax,-z,norelro,-z,combreloc,-z,global,-z,noexecstack,-z,now -Wl,-z,noexecstack -Wl,-z,text -Wl,-z,relro -Wl,--build-id conftest.c -ldl  -lsqlite3  1>&5
DEBUG: configure:15007: checking for SQLITE_THREADSAFE support in system SQLite
DEBUG: configure:15030: /usr/bin/gcc -std=gnu99 -o conftest  -fstack-protector-strong -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread   -fstack-protector-strong -lpthread -Wl,-O3,--no-omagic,--sort-common,--as-needed,--relax,-z,norelro,-z,combreloc,-z,global,-z,noexecstack,-z,now -Wl,-z,noexecstack -Wl,-z,text -Wl,-z,relro -Wl,--build-id conftest.c -ldl  -lsqlite3  1>&5
DEBUG: configure:15053: checking for SQLITE_ENABLE_FTS3 support in system SQLite
DEBUG: configure:15076: /usr/bin/gcc -std=gnu99 -o conftest  -fstack-protector-strong -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread   -fstack-protector-strong -lpthread -Wl,-O3,--no-omagic,--sort-common,--as-needed,--relax,-z,norelro,-z,combreloc,-z,global,-z,noexecstack,-z,now -Wl,-z,noexecstack -Wl,-z,text -Wl,-z,relro -Wl,--build-id conftest.c -ldl  -lsqlite3  1>&5
DEBUG: configure:15099: checking for SQLITE_ENABLE_UNLOCK_NOTIFY support in system SQLite
DEBUG: configure:15122: /usr/bin/gcc -std=gnu99 -o conftest  -fstack-protector-strong -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread   -fstack-protector-strong -lpthread -Wl,-O3,--no-omagic,--sort-common,--as-needed,--relax,-z,norelro,-z,combreloc,-z,global,-z,noexecstack,-z,now -Wl,-z,noexecstack -Wl,-z,text -Wl,-z,relro -Wl,--build-id conftest.c -ldl  -lsqlite3  1>&5
DEBUG: configure:15145: checking for SQLITE_ENABLE_DBSTAT_VTAB support in system SQLite
DEBUG: configure:15168: /usr/bin/gcc -std=gnu99 -o conftest  -fstack-protector-strong -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread   -fstack-protector-strong -lpthread -Wl,-O3,--no-omagic,--sort-common,--as-needed,--relax,-z,norelro,-z,combreloc,-z,global,-z,noexecstack,-z,now -Wl,-z,noexecstack -Wl,-z,text -Wl,-z,relro -Wl,--build-id conftest.c -ldl  -lsqlite3  1>&5
DEBUG: configure:15338: checking for valid C compiler optimization flags
DEBUG: configure:15349: /usr/bin/gcc -std=gnu99 -c  -fstack-protector-strong -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -O3 -march=native -mtune=native -fcolor-diagnostics -w -fstack-protector-strong -fcf-protection=full -Wp,-D_GLIBCXX_ASSERTIONS -fno-plt  -fstack-protector-strong conftest.c 1>&5
DEBUG: gcc: error: unrecognized command line option '-fcolor-diagnostics'
DEBUG: configure: failed program was:
DEBUG: #line 15342 "configure"
DEBUG: #include "confdefs.h"
DEBUG: #include <stdio.h>
DEBUG: int main() {
DEBUG: printf("Hello World\n");
DEBUG: ; return 0; }
DEBUG: configure: error: These compiler flags for C are invalid: -O3 -march=native -mtune=native -fcolor-diagnostics -w -fstack-protector-strong -fcf-protection=full -Wp,-D_GLIBCXX_ASSERTIONS -fno-plt
ERROR: old-configure failed
*** Fix above errors and then restart with\
               "make -f client.mk build"
make[2]: *** [/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/client.mk:383: configure] Error 1
make[2]: Leaving directory '/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox'
make[1]: *** [/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/client.mk:396: /home/aj/.cache/yay/waterfox-classic-git/src/Waterfox/obj-x86_64-pc-linux-gnu/Makefile] Error 2
make[1]: Leaving directory '/home/aj/.cache/yay/waterfox-classic-git/src/Waterfox'
make: *** [client.mk:170: build] Error 2
==> ERROR: A failure occurred in build().
`

I'm starting to feel out of my depth to be honest, I'd loved to get Waterfox working but it seems very complicated compared to installing on other systems, or compared to plain Firefox on Arch.

**Comment by hawkeye116477** [comment]
@eojjn I forgot about optimize flags. So you'll need to change line 13 and 14 => https://aur.archlinux.org/cgit/aur.git/tree/mozconfig?h=waterfox-classic-git#n13). I didn't tried to compile with gcc and I don't know what equivalents of this flags for gcc are, so you'll need to look at some doc or maybe just try with lower version of clang.

`it seems very complicated compared to installing on other systems`
You have also binary version => https://aur.archlinux.org/packages/waterfox-classic-bin, no need to build it.

**Comment by eojjn** [comment]
I hadn't seen that there's a binary version. That's made life a lot simpler! 
Thanks for all your help!
