### ISSUE TITLE
Waterfox does not return its version when run with --version

### ISSUE THREAD

**Issue by adamryczkowski** [MrAlex94/Waterfox#1265]
I would appreciate if the version included when run with `--version` (in e.g. second line) be in the same format as the github releases, i.e. `2019.10-classic-1`.

I need the version for automated updates on Linux - my script reads the latest github release and compares it with the parsed output of `waterfox --version` to check if an update is needed.

**Comment by grahamperrin** [comment]
A tentative +1 from me – _without_ knowing the implications of such a change. 

https://github.com/MrAlex94/Waterfox/issues/1204#issuecomment-543193028 in particular.

**Comment by MrAlex94** [comment]
Found the [offending code](https://github.com/MrAlex94/Waterfox/blob/19fe621225c69b3a8df8f60cc5d68bd0422601e4/toolkit/xre/nsAppRunner.cpp#L1449).

Will try and squeeze this in for the next update.

**Comment by hawkeye116477** [comment]
From recently is little better, it shows `Waterfox Classic 2020.04`.

**Comment by MrAlex94** [comment]
Please re-open if needed.
