### ISSUE TITLE
VRAM leak??.... well... sort of. Windows 7, 2019.10 Classic

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox#1267]
If the user closes or unloads the tab they are currently viewing, the  content process does not release the vram contents for that tab

If that tab is restored and then the user clicks to another tab, the vram in the process correlating to previous tab is released and the user can close or unload that tab without it holding onto vram contents.

This requires that there be more tabs than content processes to pull off so that the content process isn't shutdown with the tab unloading.

**Comment by grahamperrin** [comment]
I'm curious, how is the per-process VRAM measured? 

Re: https://superuser.com/a/1360976 I tried (Sysinternals) Process Explorer (on Windows 10) …

**Comment by Squall-Leonhart** [comment]
Process Explorer, its almost like the lazification and close tab code isn't tied into the vram allocator like tab switching is.
