### ISSUE TITLE
[Bug] Possible Broken Addon Support

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1268]
Hello, so, i installed a addon to enhance my Experience on a Online Gaming Website and to my surprise, it looked like this. Notice how the Chat is broken with this addon. Here is the link to the addon : https://addons.mozilla.org/en-US/firefox/addon/btroblox/?src=search
This did not look like this in WaterFox Current.

![8GyteTeASx](https://user-images.githubusercontent.com/37266538/69248706-69309880-0bb5-11ea-962a-e7fe5b46924b.png)

**Comment by MrAlex94** [comment]
I suggest [messaging the author](https://twitter.com/AntiBoomz) of the addon as they say it's compatible with Firefox 42+.

**Comment by ghost** [comment]
Ahh ok then. What shall I include?

**Comment by MrAlex94** [comment]
Not sure, a link to this issue? Also maybe post your [console output](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) for any error messages related to the addon?

**Comment by ghost** [comment]
Of course
