### ISSUE TITLE
Waterfox Classic can not add legacy Icon Effects

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1269]
Spun off from #370

### Steps

1. Add or enable the Classic Add-ons Archive extension
2. caa:addon/icon-effects
3. **Install now**

### Expected

4. the option to **Add**

### Actual result

4. the Add button remains greyed out

![image](https://user-images.githubusercontent.com/192271/69298077-bd169e00-0c04-11ea-8c35-aacd6d6b161b.png)

The `.xpi` can be downloaded but the downloaded file can not be added: 

![image](https://user-images.githubusercontent.com/192271/69298257-3910e600-0c05-11ea-8b79-0d74df9901f3.png)

From <https://www.reddit.com/comments/dvyx22/-/f859pvg/?context=3>: 

> … its name gets reported as "null", and it breaks building the list of extensions, even if it's disabled. Workaround is to remove it from the extensions folder (look for `StyleThing@ya.ru.xpi`), restart, then put it back. Has to be done every time a new addon is installed. …

https://robwu.nl/crxviewer/?crx=https%3A%2F%2Fca-archive.biz.tm%2Fstorage%2F247%2F247570%2Ficon_effects-0.9-fx.xpi `install.rdf` line 8: 

```
	  <em:name>Icon Effects</em:name>
```

**Comment by grahamperrin** [comment]
If there's non-installation, it's normal for Waterfox to be explicit about the reason for non-installation. Sometimes we see the word *corrupt* but I don't know whether that's true in this case. 

@ElhemEnohpi please, on your Mac, can you reproduce the (non-explicit) failure to install with Firefox 56.0.2? 

https://ftp.mozilla.org/pub/firefox/releases/56.0.2/mac/

**Comment by ElhemEnohpi** [comment]
@grahamperrin - it's not possible to add Classic Add-ons Archive to that version of Firefox, because of addon signing requirements. Do you know where I can get the unbranded version of that, which allowed it? I don't have it anymore and I can't seem to find it online.

If I just download the icon_effects-0.9-fx.xpi and drag it onto a Firefox window, I get this error:
`TypeError: (new TypeError("this.addon._repositoryAddon is null", "resource://gre/modules/addons/XPIInstall.jsm", 1720)) is not iterable`
and it just fails without showing any install popup or message.

**Comment by grahamperrin** [comment]
With Firefox 56.0.2, visit this address: 

- about:config?filter=xpinstall.signatures.required

Make `xpinstall.signatures.required` `false` then retry addition of Classic Add-ons Archive …

**Comment by ElhemEnohpi** [comment]
It's not possible to add unsigned addons to Firefox release versions as of 48, regardless of the setting of `xpinstall.signatures.required`: https://wiki.mozilla.org/Add-ons/Extension_Signing

There was an en-US-only unbranded build of 56.0.2, but I can't find it anymore.

Version 52 ESR does allow it, and attempting to install Icon Effects from the CAA does result in the "Install" button (in later versions called "Add") being greyed out.

**Comment by grahamperrin** [comment]
> ……52 ESR … attempting to install Icon Effects from the CAA does result in the "Install" button … being greyed out.

OK, and Firefox 52.⋯ ESR spanned 2017–2018. 

Let's assume that this 2011 extension was simply not compatible with more recent Firefox 56.0.2 and so, not compatible with Waterfox Classic. Not an issue with Waterfox. 

I don't imagine a workaround without someone forking and fixing the extension so I'll close this issue and mark https://redd.it/dvyx22 _RESOLVED_ (explained). 

Thanks @ElhemEnohpi for working through this with me.
