### ISSUE TITLE
crash osx on tab open

### ISSUE THREAD

**Issue by andyzeo** [MrAlex94/Waterfox#1274]
using waterfox classic on 10.7.5 in a MacBook3,1 4GB ram and SSD waterfox crashes on opening new tab via keyboard shortcut or tab click. freezes whole computer.

also crashes on trying to play netflix via silverlight plugin

**Comment by grahamperrin** [comment]
> 10.7.5 … crashes on opening new tab 

Duplicate of #1217

**Comment by grahamperrin** [comment]
OT, 

> silverlight

From <https://www.reddit.com/comments/da0fg1/-/f31pj22/>:

>> Microsoft never released a 64-Bit Silverlight NPAPI plug-in for macOS, so it has never worked on that platform for Waterfox Classic.
