### ISSUE TITLE
Waterfox Classic: e10s: multiple processes (one content process) in single-process mode

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1276]
Observable with: 

- Waterfox Classic 2019.10 (20191103135811) on FreeBSD-CURRENT
- Waterfox Classic 2019.10 (20191023220600) on Manjaro Linux.

On Linux, the unexpected content process seems to be triggered by some types of new tab action: 

![2019-11-22 08:19:37 e10s, 2019 10 (20191023220600), Linux](https://user-images.githubusercontent.com/192271/69478332-222ae900-0de9-11ea-975d-18c02065b464.png)

– **and** soon afterwards there can be multiple tabs with loaded content, in the same session, without using a content process: 

![2019-11-22 08:20:43 e10s, 2019 10 (20191023220600), Linux](https://user-images.githubusercontent.com/192271/69478331-222ae900-0de9-11ea-9c67-4f0c6c406f44.png)

Screen recordings of FreeBSD-CURRENT: 

- `2019-11-22 07:59 e10s, 2019.10 (20191103135811), FreeBSD-CURRENT.mp4` https://put.re/player/q9jMcFV2.mp4
- [2019-11-22 07:59 e10s, 2019.10 (20191103135811), FreeBSD-CURRENT.zip](https://github.com/MrAlex94/Waterfox/files/3882419/2019-11-22.07.59.e10s.2019.10.20191103135811.FreeBSD-CURRENT.zip)
- `2019-11-22 08:05 e10s, 2019.10 (20191103135811), FreeBSD-CURRENT.mp4` https://put.re/player/McwzfvR9.mp4
- [2019-11-22 08:05 e10s, 2019.10 (20191103135811), FreeBSD-CURRENT.zip](https://github.com/MrAlex94/Waterfox/files/3882421/2019-11-22.08.05.e10s.2019.10.20191103135811.FreeBSD-CURRENT.zip)

Screen recording of Linux: 

- `2019-11-23 11:37.mp4` https://put.re/player/oySLodsp.mp4
- [2019-11-23 11:37.zip](https://github.com/MrAlex94/Waterfox/files/3882413/2019-11-23.11.37.zip)

### Impact

I'm not aware of problems arising, from the content process, in FreeBSD-CURRENT or Linux environments. However:

- on FreeBSD-CURRENT, I rarely notice the issue – at the time of writing I can **not** reproduce it with my very heavily-extended everyday profile
- on Linux, where the issue seems to be consistently reproducible, I have not actively tested with e.g. legacy extensions that are known to fail with Waterfox Classic in multi-process mode. 

I don't have easy access to a Mac. If an unexpected content process is a cause of instability in e.g. #1217 (vintage/obsolete environments) then this issue might be treated as a bug. 

Meta, tracking: #538 

### Observation

`browser.tabs.remote.force-disable` `true` **no longer prevents** 

**☑ Enable multi-process Waterfox**

– at about:preferences#general

### Distinction

A content process, not a plug-in process. 

Here's a separate process for a plug-in with Waterfox Classic in single-process mode (nothing unusual): 

![2019-11-22 08:11:41 e10s, 2019 10 (20191103135811), FreeBSD-CURRENT](https://user-images.githubusercontent.com/192271/69478334-222ae900-0de9-11ea-83f2-890f5770eeed.png)

**Comment by MrAlex94** [comment]
Even with e10s disabled, there are various other processes that are spun up :-). It may just be a bit more verbose on Linux in displaying that.
