### ISSUE TITLE
G/O Media sites - white text and invisible images

### ISSUE THREAD

**Issue by kazerniel** [MrAlex94/Waterfox#1282]
Hi,

In the last few weeks I've been getting two very strange bugs on G/O Media's sites (Lifehacker, Gizmodo, Kotaku, etc.)

First off, the large top image in the article pages often doesn't load. If I'm opening multiple tabs, the ones loading in the background pretty much never load these images. Even in the active tab I usually have to reload the page several times before it does.

A rarer bug I'm getting is when all text on the site turns white. The lines are still there, and the links underlined, but even if I select the text, it's not visible in inverse colours. (The text is there though, and can be copied to the clipboard.) This also needs several reloads to fix, but fortunately it happens rarer than the other bug.

Any idea how to fix these? It only started happening recently, and I don't think I got any addons or userstyles that could cause it.

OS: Win7 Pro Sp1 x64
Waterfox 2019.10 x64

**Comment by grahamperrin** [comment]
Meta, tracking: #538 

@kazerniel please tell us whether it's Waterfox Classic 2019.10 or Waterfox Current 2019.10

### Related

[Problem with kinja websites (Splinter, deadspin, gizmodo, etc.) : waterfox](https://www.reddit.com/r/waterfox/comments/c0kuxa/problem_with_kinja_websites_splinter_deadspin/) (2019-06-14)

[Pages Do Not Load Text : waterfox](https://www.reddit.com/r/waterfox/comments/c34fej/pages_do_not_load_text/) (2019-06-21) – some commentary from me. tl;dr a sense of randomness with no reliable workaround. 

Maybe not related, but worth noting (given the sense of randomness): 

 [Waterfox Classic, UK: one profile stuck with https://www.gizmodo.co.uk/ – can't get to https://gizmodo.com/ (and stay there)](https://www.reddit.com/r/waterfox/comments/c1rqg1/waterfox_classic_uk_one_profile_stuck_with/)

**Comment by kazerniel** [comment]
Thanks for the links!

I'm not sure how to tell which version I have, I can't see it in the About window. If that helps, I updated my Waterfox from the previous versioning system via the built-in updater, without downloading a new exe from the website.

**Comment by hawkeye116477** [comment]
I guess that's rather Waterfox Classic and I can confirm that happens randomly. I tried to test that with mozregression tool, but because that happens randomly, it's hard to catch it.

**Comment by grahamperrin** [comment]
> randomly

Re: https://github.com/MrAlex94/Waterfox/issues/1282#issuecomment-559846895 I used newly-installed Waterfox Classic `2020.02.1` on Windows 10 to visit the eleven sites that are linked from <https://kinja.com/>. Then followed a link from the home page of each site. 

So far, no problem; no sense of randomness. 

@kazerniel @hawkeye116477 please, can either of you reproduce this issue with `2020.02.1` and if so: which OS?

**Comment by kazerniel** [comment]
It seems fixed in 2020.02.1 Classic on Win7 👍

**Comment by grahamperrin** [comment]
Thanks. If you're happy to close this issue, I'll not stop you :-)

**Comment by kazerniel** [comment]
Whoops, forgot it was me who opened it 😅
