### ISSUE TITLE
Login failure.

### ISSUE THREAD

**Issue by Achaean** [MrAlex94/Waterfox#1283]
Same issue as https://github.com/MrAlex94/Waterfox/issues/932
Can't login at various websites. PS. here: https://zz0.grepolis.com/

I opened new issue, because this time is about Waterfox-Current.
Latest version from repository, at a Debian oldstable based distro.

**Comment by grahamperrin** [comment]
> https://zz0.grepolis.com/

Login success: 

![Screenshot_20191202_111125](https://user-images.githubusercontent.com/192271/69954994-986bd180-14f4-11ea-838c-2a346bfdb068.png)

> various

Addresses please.

**Comment by Achaean** [comment]
Strange! I even tried in safe mode, with all plugins disabled.
I'll look at it more thoroughly and I'll be back.
