### ISSUE TITLE
Waterfox Current container IDs: consider prefix waterfox- in lieu of firefox-

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1285]
Re: https://redd.it/e4itqr

From https://github.com/stoically/temporary-containers/issues/335#issuecomment-560130899

> … Waterfox returns `{ name: "Waterfox", vendor: "Mozilla", version: "68.0", .. }` on the [browser.runtime.getBrowserInfo()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getBrowserInfo) API, but the container ids are still prefix with `firefox-` instead of `waterfox-`. I'd say that _should be_ fixed in Waterfox, …

**Comment by grahamperrin** [comment]
Cross reference https://redd.it/fzn7rw

**Comment by kopach** [comment]
Hi. The issue is still there. Any updates on this?
