### ISSUE TITLE
how to change user agent (waterfox classic on linux)?

### ISSUE THREAD

**Issue by linuxgirl22** [MrAlex94/Waterfox#1287]
Hello, in a couple of days a software I've been able to use an alternative manual way of registering license is removing that option, to make use of the software depend on logging in via account ... I am not able to successfully login outside of Waterfox, so would lose access to being able to use the software. 

I am trying to find how to change the user agent to:
    Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko
in the hope that it will appear that I'm using ie11, which is the requirement for this software. 

I've read many many threads, tried creating general.useragent.overridepreference, but user agent still shows as Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3

If someone can point me on how to fix this, I'd be very grateful.

**Comment by MrAlex94** [comment]
Go to `about:config` > Right Click > New String > Name: `general.useragent.override.URL` > Value: `Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko` and  you're done! Either refresh the page or restart the browser.

**Comment by linuxgirl22** [comment]
Thank you very much for such a quick response; I'll go and do that now! :-)

**Comment by linuxgirl22** [comment]
Unfortunately that didn't change the user agent. If it's relevant, I'd cleaned cache/cookies/history, and am only using a few add-ons ... fixed zoom, adblock plus, decentraleyes, ublock origin, and the Classic Addons Archive. (Zen arch installer/Mate) On installing Waterfox, I copy over .waterfox folder that I have backed up on external drive, so am not sure if something in that may be causing a problem? or the software in question has already noted Linux instead of Windows? I don't know if VPN has anything to do with it. Sorry, just throwing out various things incase one of them is relevant.

**Comment by grahamperrin** [comment]
Suggested extensions: 

https://www.reddit.com/r/waterfox/comments/9drjqx/user_agent/e66gcir/

**Comment by linuxgirl22** [comment]
Thank you for the link. User Agent Overrider has worked perfectly! :-) 

Unfortunately I still can't login to the software outside of browser, so it must be a server error or something; already dialoguing, but will hope whatever the error is can be fixed.

**Comment by DrakeTDL** [comment]
In case you didn't want to use an extension to change your useragent, you could try this (as this has worked for me).
Add a new string named "general.useragent.override"

**Comment by grahamperrin** [comment]
> "general.useragent.override"

Please avoid that approach. It's too easy to cause the application to stop working with sites such as YouTube. 

----

https://github.com/MrAlex94/Waterfox/issues/1287#issuecomment-561190628 above offers a less risky approach, 

`general.useragent.override.URL`
