### ISSUE TITLE
Is it possible to get a better spellcheck dictionary?

### ISSUE THREAD

**Issue by endolith** [MrAlex94/Waterfox#1291]
The default dictionary in Firefox is [missing a lot of legitimate words](https://www.reddit.com/r/firefox/comments/6zgoza/how_is_it_that_firefoxs_spellcheck_still_sucks/?ref=share&ref_source=link) (duplicative, profiler, parallelization, reweighting, etc.)  Can Waterfox get a more comprehensive dictionary, so it works more like Chrome?

**Comment by grahamperrin** [comment]
Waterfox Classic or Waterfox Current?

> The default dictionary

Which language? 

> duplicative, profiler, parallelization, reweighting 

British English Dictionary (Marco Pinto) 2.67 with Waterfox Classic 2019.10 treats only one of those four words as mis-spelt.

**Comment by endolith** [comment]
I'm using Waterfox Classic 2019.10, American English

**Comment by grahamperrin** [comment]
OK. Over to [Spell-checker : waterfox](https://www.reddit.com/r/waterfox/comments/e1x21b/spellchecker/) for discussion – thanks.
