### ISSUE TITLE
clients.openWindow is not a function

### ISSUE THREAD

**Issue by luzrain** [MrAlex94/Waterfox#1295]
In service workers clients.openWindow is not working, because of this the opening new windows from service worker is not possible.
In modern Firefox or Chrome it works fine.

You can try this. Go to the link, search "Open a Window", click "OPEN WINDOW" button, click on received push message and show the console.
https://web-push-book.gauntface.com/demos/notification-examples/

![Без-имени-1](https://user-images.githubusercontent.com/25800964/70476922-cbabf300-1ae8-11ea-82d3-11dde9105a08.png)

**Comment by laniakea64** [comment]
In Waterfox Classic this was disabled by default - https://github.com/MrAlex94/Waterfox/commit/521afd50114f7814ad7f0c013fd7c3dfad15d4e5

Does setting `about:config` >  `dom.serviceWorkers.openWindow.enabled` to `true` get it working for you?

**Comment by luzrain** [comment]
Yes, its works. Thank you!
