### ISSUE TITLE
WordReference -- Waterfox Classic 2019.12

### ISSUE THREAD

**Issue by TheTechRobo** [MrAlex94/Waterfox#1296]
Wordreference looks very weird. I am using latest WATERFOX CLASSIC and it looks weird. 

Have tried reloading. It is installed with no admin privileges -- i love that feature of the install :)

Also right-click doesn't work

Using Windows 10

Thanks!

![WeirdWaterfox](https://user-images.githubusercontent.com/52163910/70554122-90421080-1b4a-11ea-9679-c7a84efdb235.PNG)

**EDIT:** Oh crap this **is** bad
![omg](https://user-images.githubusercontent.com/52163910/70554465-27a76380-1b4b-11ea-8fce-62bb026e4583.PNG)

**Comment by TheTechRobo** [comment]
![Capture](https://user-images.githubusercontent.com/52163910/70554326-ea42d600-1b4a-11ea-9694-5c8ac9818d39.PNG)

This is what it's supposed to look like

**Comment by TheTechRobo** [comment]
This is a fresh install.

**Comment by grahamperrin** [comment]
https://www.wordreference.com/

Home-built Waterfox Classic 2019.10 (20191103135811) on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/70554996-17f14480-1b76-11ea-95a3-6396ba0e1205.png)

I'll try to build 2019.12.
