### ISSUE TITLE
App Name Reverts to Just "Waterfox" in 2019.12

### ISSUE THREAD

**Issue by pjpreilly** [MrAlex94/Waterfox#1297]
In both Mac Os & Linux the app name reverted to "Waterfox" when in 2019.10 it was "Waterfox-Classic".

**Comment by hawkeye116477** [comment]
In case of me, in 2019.10 it was just Waterfox, now is Waterfox Classic :smile:

**Comment by pjpreilly** [comment]
Downloaded fresh from waterfox.net/releases

**Comment by grahamperrin** [comment]
@pjpreilly please, can you let us have screenshots? 

* Waterfox Classic 2019.12 on Linux including the **About Waterfox** window and the task manager
* Waterfox Classic 2019.12 on Mac OS X including the **About Waterfox** window and the dock. 

@pjpreilly @hawkeye116477 which distribution and version of Linux, which desktop environment?

Here: Manjaro Linux (kernel 5.4.2-1-MANJARO), KDE Plasma 5.17.4. 

Thanks

**Comment by hawkeye116477** [comment]
Kernel rather nothing change, more important is source of package and used langpack, cuz on langpack is written if it's Waterfox or Waterfox Classic. Anyway, I have Manjaro KDE and in case of me, on both official and my build it's Waterfox Classic.

**Comment by pjpreilly** [comment]
waterfox-classic-bin not the kde version
Manjaro Gnome/Dash to Dock ...
click new File->restart option in Waterfox Classic and
restart opens a new icon on DTD called "Waterfox"

![Uploading Screenshot from 2019-12-11 16-44-47.png…]()

![Screenshot from 2019-12-11 16-46-59](https://user-images.githubusercontent.com/10430084/70663241-ef308400-1c35-11ea-8cdf-15a86d1d348f.png)

**Comment by pjpreilly** [comment]
After restart ...
![Screenshot from 2019-12-11 16-44-47](https://user-images.githubusercontent.com/10430084/70663482-6f56e980-1c36-11ea-9a66-30efb8bb02bb.png)

**Comment by grahamperrin** [comment]
Thanks, 

> waterfox-classic-bin not the kde version
> Manjaro Gnome/Dash to Dock ...
> click new File->restart option in Waterfox Classic and
> restart opens a new icon on DTD called "Waterfox"

Can you share a screenshot? Or two.

**Comment by pjpreilly** [comment]
Can you share a screenshot? Or two.
.. of what exactly?

**Comment by grahamperrin** [comment]
Task manager (or its equivalent).

**Comment by pjpreilly** [comment]
Manjaro first launch ... Notice Manjaro Gnome Title Bar.
![Screenshot from 2019-12-13 14-32-46](https://user-images.githubusercontent.com/10430084/70826792-c931ed80-1db5-11ea-9073-7fe989e284d9.png)

**Comment by pjpreilly** [comment]
OS X downloaded from waterfox.net....
![2019-12-13 05 21 36 pm](https://user-images.githubusercontent.com/10430084/70836046-081f6d80-1dcd-11ea-8f65-54fbdeff9f28.png)
![2019-12-13 05 21 05 pm](https://user-images.githubusercontent.com/10430084/70836069-13729900-1dcd-11ea-9ab4-b3d34b235647.png)

**Comment by grahamperrin** [comment]
Sorry, I couldn't recall the name of the task manager in GNOME. It's the *Dock*, can you share a shot of the Dock (with the Waterfox icon)? 

Thanks

**Comment by pjpreilly** [comment]
> After restart ...
> ![Screenshot from 2019-12-11 16-44-47](https://user-images.githubusercontent.com/10430084/70663482-6f56e980-1c36-11ea-9a66-30efb8bb02bb.png)

The Dock is pictured here with the two icons (Waterfox Classic is a favorite & pinned in the middle & not active) Waterfox is on the right after restart & active. There aren't named just icons, names appear on pointer hover.

**Comment by pjpreilly** [comment]
![Screenshot from 2019-12-17 20-45-04](https://user-images.githubusercontent.com/10430084/71048884-bfd6b700-210e-11ea-9d28-770b00bc39dc.png)
![Screenshot from 2019-12-17 20-46-13](https://user-images.githubusercontent.com/10430084/71048885-bfd6b700-210e-11ea-95c8-93632158b304.png)

**Comment by pjpreilly** [comment]
The second pic is after a File->Restart
