### ISSUE TITLE
Waterfox Classic 2019.10 cannot sign into Sony ID related services (PSN/Playstation store)

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox#1299]
Attempts fail with

> A connection to the server could not be established.

![image](https://user-images.githubusercontent.com/1098176/70596312-b2668c00-1c39-11ea-8c8f-517b6228b3a5.png)

**Comment by Squall-Leonhart** [comment]
![image](https://user-images.githubusercontent.com/1098176/70596405-ecd02900-1c39-11ea-9d26-bc1d8570bb23.png)

**Comment by Squall-Leonhart** [comment]
Login successful with IE on host
Login successful with Edge insider in VM
Login failed on Waterfox Classic in VM and on Host.

**Comment by hawkeye116477** [comment]
Hmm, in case of me, it's fine on Linux.

**Comment by Squall-Leonhart** [comment]
still broken on 2019.12 Classic.

Windows only it seems.

**Comment by Squall-Leonhart** [comment]
Resolved in 20.01
