### ISSUE TITLE
Websites not loading in Classic (since 56.2.14)

### ISSUE THREAD

**Issue by uDEV2019** [MrAlex94/Waterfox#1301]
Some (german) websites are not loading. Not all the time, but mostly. If the Website is not loading, i'm getting only a white background.

Examples:
- www.motor-talk.net
- www.computerbase.de

I've updated severals times (gone always back to 56.2.12):
- 56.2.12 to 56.2.14
- 56.2.12 to 2019.10
- 56.2.12 to 2019.12 

Using Classic under Windows 7 x64 and tested it already with a fresh start (new profile, with some extensions like µBlock Origin, HTTPS Everywhere, NoScript, TabMix Plus, Stylus).
If i deactivate e.g. µBlock Origin the website normally loads up. 
Next time refreshing the website (with deactivated µBlock) its not loading.

**Comment by grahamperrin** [comment]
I tested with home-built Waterfox Classic 2019.12 (20191210201058) on FreeBSD-CURRENT, a very heavily extended profile. 

I couldn't easily get a white background. 

The first site might be more demanding than the second. 

Instead of a new profile with extensions, test in safe mode.

**Comment by uDEV2019** [comment]
safe mode is useless, because its simply a profile without extensions loaded.

**Comment by grahamperrin** [comment]
> safe mode is useless, 

Safe mode is **entirely** useful for troubleshooting purposes. To tell, for example, whether the issue is a Waterfox issue.

**Comment by hawkeye116477** [comment]
`If i deactivate e.g. µBlock Origin the website normally loads up.`
So it's rather problem related with uBO filterlists.

**Comment by uDEV2019** [comment]
tested it in safe mode and every website is loading normal, because its like a new profile without anything. also tested it with one extension activated (µblock origin) and it's not loading anymore. Screenshot with browser console (anything activated except css reflows)
![error](https://user-images.githubusercontent.com/51911097/70740923-8bcc5200-1d1a-11ea-80db-5fb8e4d4888c.png)

**Comment by grahamperrin** [comment]
Thanks. What advice have you received in uBlock Origin support areas?

**Comment by uDEV2019** [comment]
i didn't ask at the support area of µBlock Origin for now, because of:
- v56.2.12 with newest µBlock Origin works everything fine
- v56.2.14+ with the µBlock Origin (as above with same settings and same filterlists) don't work fine

What Do you think could someone tell me at µBlock Origin support area, except that something in Browser has been changed?!

**Comment by hawkeye116477** [comment]
56.2.14 had only security fixes, but if issue appears also on 56.2.13, then maybe that's because on that version support for  filtering streaming response data via webRequest API was added, so that's maybe issue with filterlist, cuz previously html filtering doesn't worked.

**Comment by hawkeye116477** [comment]
@uDEV2019 Can you make backup of uBO settings and show us content of that file?

**Comment by Squall-Leonhart** [comment]
Waterfox shouldn't be using the "newest" ublock origin.

**Comment by hawkeye116477** [comment]
@Squall-Leonhart Why? It's marked as compatible with 55, for me works great, legacy version lacks many new things :smile:

**Comment by uDEV2019** [comment]
will try on windows with next release of waterfox classic.
