### ISSUE TITLE
Firefox Connect is there (no priority)

### ISSUE THREAD

**Issue by TheTechRobo** [MrAlex94/Waterfox#1306]
![Capture](https://user-images.githubusercontent.com/52163910/70731318-80563800-1cd4-11ea-9911-f9aa27613df7.PNG)

As you can see, you can click the person and actually sign into  Mozillla Account. 

Just a heads-up

**Comment by MrAlex94** [comment]
That's meant to be there. So you can use Firefox Sync :-)
