### ISSUE TITLE
Issue with multiple PortableWaterfox intances

### ISSUE THREAD

**Issue by HyperCriSiS** [MrAlex94/Waterfox#1309]
Hi,

I am using three copies of Portable Waterfox with different configuration.
After enabling "AllowMultipleInstances" this works well.

Unfortunately this also activates the -no-remote. Waterfox won't take remote commands then which leads to an error when I open a link outside of Waterfox:
"Waterfox is already running, but not responding. The old process needs to be closed to open a new window". 

Can you please make the -no-remote parameter optional when enabling "AllowMultipleInstances"?

Thanks,
Hyper

**Comment by ghost** [comment]
@HyperCriSiS Here you have a good portable Waterfox >>http://portableappz.blogspot.com/search?q=Waterfox

**Comment by Huge** [comment]
> @HyperCriSiS Here you have a _good_ portable Waterfox >>http://portableappz.blogspot.com/search?q=Waterfox

! OS is telling me it is contains a virus. Who made the page and built the software you link to??
