### ISSUE TITLE
could not compile cssparser

### ISSUE THREAD

**Issue by 0xFF1E071F** [MrAlex94/Waterfox#1311]
```
 6:16.84 error[E0506]: cannot assign to `self.input.cached_token` because it is borrowed
 6:16.84    --> /waterfox-2019.12-1/work/Waterfox-2019.12-classic/third_party/rust/cssparser/src/parser.rs:388:17
 6:16.84     |
 6:16.85 364 |     pub fn next_including_whitespace_and_comments(&mut self) -> Result<&Token<'i>, BasicParseError<'i>> {
 6:16.85     |                                                   - let's call the lifetime of this reference `'1`
 6:16.86 ...
 6:16.86 377 |             Some(ref cached_token) if cached_token.start_position == token_start_position => {
 6:16.86     |                  ---------------- borrow of `self.input.cached_token` occurs here
 6:16.86 ...
 6:16.86 388 |                 self.input.cached_token = Some(CachedToken {
 6:16.86     |                 ^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.input.cached_token` occurs here
 6:16.87 ...
 6:16.87 400 |         Ok(token)
 6:16.87     |         --------- returning this value requires that `self.input.cached_token.0` is borrowed for `'1`
 6:16.87 
 6:17.06 error: aborting due to previous error
 6:17.06 
 6:17.06 For more information about this error, try `rustc --explain E0506`.
 6:17.09 error: could not compile `cssparser`.
```

i have tried both rust versions 1.38 and 1.39
i have search through the `rustc --explain E0506` but it doesnt help.

i have extracted the code 
install dependencies
then:
#export SHELL=/bin/sh
#./mach build
i have used these commands

**Comment by hawkeye116477** [comment]
Just disable stylo.

**Comment by 0xFF1E071F** [comment]
i have changed 
```ac_add_options --enable-stylo=build to ac_add_options --disable-stylo```
in .mozconfig file
and it is compiling now 
i will come back for other issues =)
close  #1311

**Comment by magiruuvelvet** [comment]
what if I want to compile stylo? are there any patches? I found a patch in a gentoo overlay for tor browser with the same issue with cssparser, but there are quite some merge conflicts and I have no idea how Rust works so I wasted hours trying to fix it :(

Btw, what is stylo supposed to do. I use the developer tools in Waterfox if that matters.

**Comment by hawkeye116477** [comment]
Currently stylo isn't reliable in Waterfox Classic, so it's rather not worth to fix building stylo.
For example this problem appears => https://github.com/MrAlex94/Waterfox/issues/498.

https://hacks.mozilla.org/2017/08/inside-a-super-fast-css-engine-quantum-css-aka-stylo/

**Comment by grahamperrin** [comment]
> Waterfox Classic, so it's rather not worth to fix building stylo.

+1

https://www.reddit.com/r/waterfox/comments/7bj77g/do_not_forget_to_enable_styloquantum_css/dx12nol/ shortlist of links to discussions of Stylo not working as expected. 

My bad. When I opened #332 I simply thought that it seemed like a good idea; I didn't test.
