### ISSUE TITLE
Upgraded Waterfox language pack stop working

### ISSUE THREAD

**Issue by iPublicis** [MrAlex94/Waterfox#1312]
Hi,

I upgraded to last 2019.12 in Ubuntu 19.10

1. Waterfox stop loading with error XML when changed locale to **Portuguese pt_PT**
2. Have to load it with `--safe-mode` and remove the Language pack installed
3. reload it but selected locale won't load. Still all in English
4. Tried to install `sudo apt install waterfox-locale-pt` but gave error of dependency for package **_waterfox-classic-i18n-pt-PT_**

**Comment by hawkeye116477** [comment]
Try install `waterfox-classic-i18n-pt-pt` package.

**Comment by iPublicis** [comment]
> Try install `waterfox-classic-i18n-pt-pt` package.

5. When tried to install `sudo apt install waterfox-classic-i18n-pt-pt` It is not available on the server

Forgot to mention that ;-)

**Comment by hawkeye116477** [comment]
@iPublicis  Try again, it's here https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-classic-i18n-pt-pt

**Comment by iPublicis** [comment]
> @iPublicis Try again, it's here https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-classic-i18n-pt-pt

I have `http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_Next/`on my repos. Shouldn't it be enough?

**Comment by iPublicis** [comment]
I followed the instructions for xUbuntu_Next and not the ones for xUbuntu_19.10 at

https://software.opensuse.org/download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-kde#manualUbuntu

**Comment by hawkeye116477** [comment]
That package is also available for Ubuntu Next (testing version).
However soon waterfox-classic-kpe package from Next repo might be incompatible with Ubuntu 19.10, so you should rather switch to Ubuntu 19.10 repo.

**Comment by iPublicis** [comment]
Nope. 

1. Removed Next repo
2. Removed locale files
3. Add 19.10 repo
4. Updated
5. Upgraded (upgrade 2019.12 probably from new repo)
6. Still no use of Locale PT
7. Still error if trying to install `sudo apt install waterfox-locale-pt` 

```
A ler as listas de pacotes... Pronto
A construir árvore de dependências       
A ler a informação de estado... Pronto
Alguns pacotes não puderam ser instalados. Isso pode significar que
você solicitou uma situação impossível ou se você está a usar a
distribuição unstable em que alguns pacotes pedidos ainda não foram 
criados ou foram movidos do Incoming.
A seguinte informação pode ajudar a resolver a situação:

Os pacotes a seguir têm dependências não satisfeitas:
 waterfox-locale-pt : Depende: waterfox-classic-i18n-pt-BR mas não é instalável
                      Depende: waterfox-classic-i18n-pt-PT mas não é instalável
E: Não foi possível corrigir problemas, você tem pacotes mantidos (hold) estragados.
```

**Comment by iPublicis** [comment]
Worked but had to install `waterfox-classic-i18n-pt-pt`by hand from deb package. Using APT wouldn't install.

**Comment by hawkeye116477** [comment]
If `sudo apt install waterfox-classic-i18n-pt-pt` without capital letters doesn't worked, then it's strange.
Anyway, I made small mistake in depends, should be without capital letters, sorry for that, fix should come in about 2 hours.

**Comment by iPublicis** [comment]
Retried and it's possible to install `sudo apt install waterfox-classic-i18n-pt-pt`
What still gives error is if trying to use the `sudo apt install waterfox-locale-pt`

So, since you already found the issue can close this one. And thanks for the speedy reply :-)

**Comment by hawkeye116477** [comment]
Even `waterfox-locale-pt` package should be fixed now.

**Comment by iPublicis** [comment]
Can close it then.
