### ISSUE TITLE
waterfox keeps crashing

### ISSUE THREAD

**Issue by shogunreaper** [MrAlex94/Waterfox#1314]
I switched to waterfox about a month ago and i keep getting random crashes with this error:

https://i.imgur.com/YHrChp7.png

How can i find out what is causing it? I am running the same setup i was on firefox 52 esr and never had that problem.

**Comment by Squall-Leonhart** [comment]
looks like faulty ram or software combination is bad.

**Comment by shogunreaper** [comment]
but it only happens with waterfox

**Comment by Squall-Leonhart** [comment]
and?

**Comment by shogunreaper** [comment]
if it was a ram problem it would be more than just waterfox crashing?

**Comment by Squall-Leonhart** [comment]
can be, often isn't.

**Comment by shogunreaper** [comment]
okay so how can i figure out what is causing it?

is there a log somewhere that can be looked at?
