### ISSUE TITLE
[Classic] Waterfox 2019.12: Greasemonkey stopped working in WF Mac, Linux & Windows 8.1

### ISSUE THREAD

**Issue by LeeBinder** [MrAlex94/Waterfox#1326]
**Affected extension**: Greasemonkey latest version 4.9 from https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/

**Affected OSes**: 
- macOS Mojave 10.14.6 (testified by me)
- Linux (as per hawkeye116477)
- Windows 8.1 (as per maxoku)

**Not affected OS**:
- Windows 10 64bit latest v.1909 (verified by me)

**Symptoms**:
After clicking onto the Greasemonkey icon in the bar:
- Empty list of scripts: all user scripts don't show up in the menu anymore
- not possible anymore to create a new script
- Importing a backup does not work anymore

**Reproducibility**:
- After reverting back to the previous Waterfox 2019.10 ¹, all is back to normal
- Same thing in brand new Waterfox profile w/o any add-ons
- Tried older versions of Greasemonkey all the way down to v.4.6 - same thing

GM latest v.4.9 also still works fine in Firefox 71 for macOS and Windows.
__________
¹ accidentally same version 56.3 in Finder as the new 2019.12

**Comment by hawkeye116477** [comment]
There is no Waterfox 56.3...
In case of me, Greasymonkey shows up as incompatible and is disabled, cuz it's compatible with FF 57, so some things might be missing. I can recommend Violentmonkey instead of :smile:

**Comment by grahamperrin** [comment]
> no Waterfox 56.3...

Waterfox Classic 2019.10 and Waterfox Classic 2019.12 are also known as 56.3. 

I should assume that a step back from 2019.12 = 2019.10.

**Comment by LeeBinder** [comment]
The previous version identifies itself in Finder as just that, v. 56.3. But so does this current version.. Obviously Alex simply forgot to bump the version # for Finder from 56.3 to >56.3, or simply the 2019.12 from "About".

Nobody ain't perfect, right ;)?

Anyway, thanks for the pointer - I'll edit my issue report next.

**Comment by grahamperrin** [comment]
> Alex simply forgot 

No, please see: 

`https://github.com/MrAlex94/Waterfox/issues/1204#issuecomment-543193028`

**Comment by LeeBinder** [comment]
Obviously 2019.10 having been versioned as 56.3 doesn't mean at all that 2019.12 couldn't/ shouldn't have been identified with a slightly higher version number like 56.4 (or at least 56.3.1 if Alex wants to stay in the 56.3 range for now)..

Anyway, that's enough about version #s - let's now keep space for on-topic comments in here ;). Thanks.

**Comment by maxoku** [comment]
I never thought that I would need to downgrade Waterfox. 😕
> 
> 
> I can recommend Violentmonkey instead of smile

Violentmonkey seems to be less functional than Greasymonkey.
Is there any other alternative that is not worse?

**Comment by hawkeye116477** [comment]
`Violentmonkey seems to be less functional than Greasymonkey`
@maxoku Can you expand the answer, what's not working?

**Comment by maxoku** [comment]
> Can you expand the answer, what's not working?

E.g. doesn't have an option to include/exclude sites on the fly.

**Comment by hawkeye116477** [comment]
@maxoku I'm not sure what you mean, but it has https://violentmonkey.github.io/api/matching/.

**Comment by maxoku** [comment]
@hawkeye116477 
It is not comfortable to manually write something. You should check how that works in Greasemonkey, it's easy to use without having to modify the script itself.

**Comment by hawkeye116477** [comment]
`it's easy to use without having to modify the script itself`
Violetmonkey has separate tab with settings for each script, in which you can write include and exclude rules, just like Greasymonkey. 
Ok, I see, you probably mean that Violentmonkey doesn't show what site to exclude, you must write rule by myself and seems that feature is only in Greasymonkey.

**Comment by LeeBinder** [comment]
@maxoku which OS are you running Waterfox in? I'm asking because I just booted Windows on the same computer, updated Waterfox to the latest 2019.12, and Greasemonkey is working just fine. So this might be just an issue of Waterfox' macOS fork?

@hawkeye116477 @grahamperrin  : can you help differentiate, too? Install Greasemonkey (if not installed yet), test by clicking onto the monkey icon in the toolabr, New Script -> possible to create a new script or not? and share the results here incl. your OS?

Please all of you let me know so I can edit the title accordingly if relevant - thanks.

**Comment by hawkeye116477** [comment]
@LeeBinder In case of me it stays as disabled and can't be enabled.
OS is Linux.

**Comment by LeeBinder** [comment]
@hawkeye116477 oh wow, you can't even enable it on the add-ons page? I think I experienced that before and solved at least that part - here's my notes (below does **_NOT_** solve for me that GM is a function-less zombie in Waterfox 2019.12 macOS):

**Issue workaround: Greasemonkey 4.9 does not fully work in Waterfox**

1) from https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions, install v.4.6 then 4.7 and test

2) If OK then install the latest update (tested OK with v.4.9)

Only if issues persist, install 4.1 then repeat above

**Comment by grahamperrin** [comment]
> down to v.4.6 

…

> … 4.1 …

Given the requirements expressed by the developer, 4.1 might be recommended. 

![image](https://user-images.githubusercontent.com/192271/71581631-ff81a380-2afd-11ea-8988-03cbbb572701.png)

Re: https://www.reddit.com/r/waterfox/comments/9gea50/alternative_or_correct_version_for_greasemonkey/e645cqn/ there's also 4.2b3. 

I don't use either version, sorry. 

If in doubt, ask at https://groups.google.com/forum/#!forum/greasemonkey-users

**Comment by grahamperrin** [comment]
PS if you do go with 4.1, check (before adding) that the URL is the right one for your platform. 

There was platform-specificity. Viewed with CRX Viewer: 

![image](https://user-images.githubusercontent.com/192271/71582017-12957300-2b00-11ea-87d7-1012e93155f9.png)

**Comment by LeeBinder** [comment]
overkill but thanks and (as could be expected..) no change neither with 4.1 mac nor with 4.2b3.

As I wrote GM 4.9 is still working mighty fine in Waterfox 2019.12 Windows and was working fine with 2019.10 Mac (and apparently Linux), so it is fixable for sure.

Let's wait and see if Alex gets to this, or not. Using Violentmonkey for now.

**Comment by maxoku** [comment]
@LeeBinder 
I have Windows 8.1 and it's not working in 2019.12. Empty list of scripts, can't create new one or import.
Which Windows do you use?

**Comment by LeeBinder** [comment]
@maxoku no kidding.. I'm having WIndows 10 latest (1909) 64bit installed as my 2ndary OS.

Have you tried these [tricks I mentioned earlier](https://github.com/MrAlex94/Waterfox/issues/1326#issuecomment-569645666)?

**Comment by maxoku** [comment]
@LeeBinder 
I already downgraded Waterfox, so I didn't have a chance. When I'll find some time I'll try it, but it won't be before new year.

**Comment by LeeBinder** [comment]
allright. So you are motivated, look here:

![GM 4 9 working in WF 2019 12 for Windows](https://user-images.githubusercontent.com/39203497/71600901-55cc0200-2b51-11ea-9d30-b657e606b5dc.png)
I was also able to create a new script.

Next I started WF 2019.12 Windows into a new fresh profile, added GM 4.9, and there also no issues at all.

I also have [Aero Glass](http://glass8.eu/) by BigMuscle installed + [AG4FFCR ver.0.0.0.11](https://www.mediafire.com/file/n9qa53qb503x385/AG4FFCR_ver.0.0.0.11.zip/file) (transparency for Chrome and Firerfox) - not sure if that makes a difference. Everything else is pretty much stock/ "vanilla".

**Comment by HKWinterhalter** [comment]
I've tried Greasemonkey 4.6,. 4.7, and 4.9 without success.  They all show "incompatible" and don't work.

Greasmonkey 4.1 works.
Violentmonkey didn't work due to not supporting CSP/CORS bypassing for trusted sites like GM does, therefore breaking my scripts.

**Comment by hawkeye116477** [comment]
@HKWinterhalter https://violentmonkey.github.io/posts/inject-into-context/

**Comment by LeeBinder** [comment]
@hawkeye116477 : valuable information, thanks

@HKWinterhalter re. "Greasmonkey 4.1 works": which OS and version of OS are you running?

**Comment by maxoku** [comment]
@LeeBinder 
I've installed Waterfox 2020.01 and tried greasmonkey versions 4.6 and 4.7 without success. I've tried 4.1 and it seems to work as to create new script, though there were no options to import scripts and the list was empty. Installing after that 4.6, 4.7 and 4.9 have the same results, nothing works.

Why it wasn't still fixed? 😒

**Comment by LeeBinder** [comment]
@maxoku : good you report in this detailed manner. We need to remain patient. Remember Alex does all of this voluntarily in his spare time, simply can't keep up with all the requests and has to set priorities. For now we have to stick to Violentmonkey.

Still I do hope that someone with coding skills finds the spot in the code which got corrupted so it can be pointed out to Alex for him to simply fix, rather than having to hunt for the regression. It's working fine in the latest Firefox so it's definitely something that needs to be fixed in Waterfox code.

We'll see..

**Comment by hawkeye116477** [comment]
`It's working fine in the latest Firefox so it's definitely something that needs to be fixed in Waterfox code.`
It's marked as compatible with Firefox 57. GreasyMonkey 4.1 works, cuz it's marked as compatible with Firefox 52, but I guess that could be mistake and should be Firefox 57. Anyway, Waterfox Classic might not have all required apis, top priority is compatibility with Classic XUL extensions, not webextensions. If you want to use it, then you should probably switch to Waterfox Current or try forked version from https://github.com/janekptacijarabaci/greasemonkey/releases.

**Comment by LeeBinder** [comment]
@hawkeye116477 have you tested Greasemonkey 4.1 for 100% functionality incl. importing scripts?

Also latest GM 4.9 **_webextension_** worked fine with Waterfox 2019.10 **_classic_**, so your argumentation does not fully hold, esp. for saying that this can't be fixed again in Waterfox classic code.

**Comment by hawkeye116477** [comment]
`importing scripts`
Greasymonkey 4.1 doesn't have option for importing scripts, it's only possible to turn it off and create new userscript, so better is forked version.

**Comment by MrAlex94** [comment]
I'm not sure what the last version of GM that worked with `Classic` was, but I tested [this](https://github.com/xiaoxiaoflood/firefox-scripts/tree/572ed613905e9be10312f0dcc221f523478e1297/extensions/greasemonkey) ported version of the old-style extension by @xiaoxiaoflood with `Current` and it works.

**Comment by hawkeye116477** [comment]
`Also latest GM 4.9 webextension worked fine with Waterfox 2019.12 classic`
I checked 4.9 on 2019.12 and icon was visible, but for example creating new userscript isn't possible, so I guess that probably something is missing.

**Comment by LeeBinder** [comment]
@hawkeye116477 I meant WF 2019.**10** classic.. which is what I had written before to begin with. I corrected in my comment above.

@MrAlex94 thanks for having a look at this. To summarize, GM 4.9 works 100% (at least for me) with WF classic 2019.10 Mac and with WF classic 2019.12/2020.01 in Windows 10. I'm actually writing from WF classic 2019.10 Mac right now.

Xiaoxiaoflood's ported mod you linked to is based on [GM 3.12 from 2017-10](https://www.greasespot.net/2017/09/greasemonkey-312-release.html) and therefore should not even be looked at as a work-around, let alone a solution. I would still suggest to fix this in the Mac and Linux version of WF classic. As I wrote above this is still fine in some archs of WF classic. Basically all that might be needed is to compare the correlating part of the code in the Windows (10) with the one in the Mac and/ or Linux version of WF classic and find the culprit code change from 2019.10 to 2019.12.

**Comment by LeeBinder** [comment]
I updated my posting above with some relevant information and corrections.

**Comment by MrAlex94** [comment]
Apologies - i didn't think GM 4.x would work at all as it was released for Firefox 57+. I'll have a look but no promises, ideally people would move to `Current` if most of their extensions are available there.

**Comment by LeeBinder** [comment]
yes, ideally .. ;)

If you don't manage to get 4.9 working in WF classic 2019.10 (any OS) or 2019.12 (Windows 10, Linux) working right away, use the trick of installing in the order of: 4,6 -> 4.7 -> 4.9 (see [this previous posting of mine](https://github.com/MrAlex94/Waterfox/issues/1326#issuecomment-569645666))
