### ISSUE TITLE
Classic Waterfox 2019.12: Browser doesn't start anymore after version update

### ISSUE THREAD

**Issue by kazerniel** [MrAlex94/Waterfox#1327]
Just opens a smaller window with this message:

> XML Parsing Error: undefined entity
> Location: chrome://browser/content/browser.xul
> Line Number 367, Column 7:      <menuitem id="context_duplicateTab" label="&duplicateTab.label;" accesskey="D"
> ------^

Edit: Tried reinstalling with exe downloaded from website, same issue.

Edit 2: Found a 56.2.14 version online, rolled back, that version works now. It would be nice if older versions were available on the website, so I could easily roll back to 2019.10 instead of having to hunt old exes on dodgy websites 😅

**Comment by Squall-Leonhart** [comment]
no repro.

Probably what happened is specific to your WF install and you've made an easily made mistake with the WF classic installer installing to program files\waterfox classic  rather than program files\waterfox which is where the prior installers installed to.

So most likely:
Shortcut points to program files\waterfox and the files here didn't update properly.

reinstall is in program files\waterfox classic but no shortcut points to it.

Uninstall pre-classic waterfox and install classic 2019.12

I manually applied the MAR file before the XML files were available, and as you can see, it works just fine

![image](https://user-images.githubusercontent.com/1098176/71456887-b248bd80-27ef-11ea-90cc-147378040be0.png)

**Comment by kazerniel** [comment]
> Probably what happened is specific to your WF install and you've made an easily made mistake with the WF classic installer installing to program files\waterfox classic rather than program files\waterfox which is where the prior installers installed to.

The updater didn't ask which folder to install the update to. My manual rollback was trying to fix an install already broken by the built-in updater.

> Uninstall pre-classic waterfox and install classic 2019.12

I now uninstalled 56.2.14, and installed 2019.12, but when tried to launch waterfox.exe from the new waterfox classic folder, it still gave the same error, so uninstalled 2019.12 and went back to 56.2.14 for now.

**Comment by Squall-Leonhart** [comment]
> The updater didn't ask which folder to install the update to. My manual rollback was trying to fix an install already broken by the built-in updater.

it isn't supposed to.

> I now uninstalled 56.2.14, and installed 2019.12, but when tried to launch waterfox.exe from the new waterfox classic folder, it still gave the same error, so uninstalled 2019.12 and went back to 56.2.14 for now.

possibly another extension in the profile is involved

I just installed it fresh with the Exe
![image](https://user-images.githubusercontent.com/1098176/71478145-2f9d1e00-2842-11ea-81b5-aac7c5d637c0.png)

**Comment by hawkeye116477** [comment]
It's related with langpacks, some new strings were added. Maybe you installed language pack manually some time ago and now problem appears or updater doesn't updated properly. What's your language?

**Comment by kazerniel** [comment]
> 
> 
> It's related with langpacks, some new strings were added. Maybe you installed language pack manually some time ago and now problem appears or updater doesn't updated properly. What's your language?

I'm using Waterfox in British English. (With British English and Hungarian dictionaries installed.)

**Comment by schnitzelbub** [comment]
I have the same problem after upgrading Waterfox Current from `2019.10` to `2020.01` via AUR.
The culprit indeed is the [language pack](https://addons.mozilla.org/en-US/firefox/addon/deutsch-de-language-pack/). After removing it `waterfox-current` starts again. A new installation of the addon does not fix this, thus I believe the language pack is outdated (5 months ago (Aug 13, 2019)).

Are mainline Firefox and Waterfox diverging in that regard as well?

**Comment by hawkeye116477** [comment]
@schnitzelbub Language pack from Firefox isn't compatible, cuz Waterfox Current has some additional things. But you can download fixed language pack from my repository following with instructions from https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-current-i18n-de.

But keep in mind that new strings are only translated in Polish, for other languages there is English text, however I created repository with unpacked language packages for easier collaboration => https://github.com/hawkeye116477/LanguagePacksForWaterfox, so you can submit PR.

**Comment by schnitzelbub** [comment]
@hawkeye116477 thanks for sharing!
I could install the extension manually, but unfortunately it did not work, at least against the version that is on AUR. Too bad, the browser will not fallback to default language in case of a missing translation element.

What is the best way to get started on a PR? Diff the English sources against the desired language?

**Comment by hawkeye116477** [comment]
`What is the best way to get started on a PR? Diff the English sources against the desired language?`
@schnitzelbub You can also look for previous commits, which contains added new strings, following with https://github.com/hawkeye116477/LanguagePacksForWaterfox/commit/ac143172a608887a97d99e9ec980bb48ca7bbdf2.

Unfortunately for now isn't on Crowdin, cuz I'm not Waterfox's lead, so can't attend for free plan (`https://crowdin.com/page/open-source-project-setup-request`).

**Comment by schnitzelbub** [comment]
@hawkeye116477 wow, that's quite a lot of changes. I will have a look at when I find some spare time, which might take a while.
