### ISSUE TITLE
[Classic][Feature] Add "Open URL's From Clipboard" Tab Option

### ISSUE THREAD

**Issue by Yay295** [MrAlex94/Waterfox#1328]
Commit https://github.com/MrAlex94/Waterfox/commit/a02e059a0ef2a9fa7066f54763fe664fcdfd6e5c added an option to copy the URL's of all tabs in the current window, but there's no easy way to do the reverse - open all of the copied URL's from your clipboard into new tabs in the current window. I've been using Copy Urls Expert (caa:addon/copy-urls-expert) to do this for years now and I don't have a problem with continuing to do that, but I think this would be a useful feature for everyone that doesn't have this addon.

**Comment by Squall-Leonhart** [comment]
The copy feature is not intended to be used to store/load tabs in this fashion.

**Comment by ChiaYen-Kan** [comment]
you can install "Multiple Paste and Go Button" from "Classic Add-ons Archive" or
install "Multiple Paste and Go Button" version 2.5.0 from addons.mozilla.org
