### ISSUE TITLE
Multi-row tabs - Feature Request

### ISSUE THREAD

**Issue by Ryushin** [MrAlex94/Waterfox#1339]
The multi-row javascript css workaround from here works well (using non-scrollable): https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions

I had to tweak the multirow css file a bit to make the tabs a bit thinner (https://support.mozilla.org/en-US/questions/1243994) and I enabled the border to visually separate the tabs.

The Tabs on Bottom also worked well with a couple of tweaks to have the menu bar display properly.

Overall, this solution works. I can drag tabs around between rows and there is an arrow that shows where the tab goes. I can also drag tabs between windows. Since this solution has finally allowed me to migrate to a modern version of Firefox, I think this should be implemented natively in Waterfox Current as a selectable option under General, Tabs.

**Comment by hawkeye116477** [comment]
`The Tabs on Bottom also worked well with a couple of tweaks to have the menu bar display properly.`
In case of that feature, in the next version of Waterfox Current will be possible to set Tab Bar position from preferences: top above address bar (default), top under address bar and bottom.

**Comment by Ryushin** [comment]
@MrAlex94 Why was this closed with no comment?  Has the feature been added?
