### ISSUE TITLE
Has It Been That Long?

### ISSUE THREAD

**Issue by pjpreilly** [MrAlex94/Waterfox#1340]
![Screenshot 2020-01-05 at 1 43 56 PM](https://user-images.githubusercontent.com/10430084/71784442-91d3ec80-2fc1-11ea-897d-3146b568cb47.png)

**Comment by hawkeye116477** [comment]
@pjpreilly Moz://a something messed...
https://bugzilla.mozilla.org/show_bug.cgi?id=1583471#c23
