### ISSUE TITLE
Ivacy VPN Addon No Longer Works

### ISSUE THREAD

**Issue by own3mall** [MrAlex94/Waterfox#1343]
I'm not sure if this is a problem caused by Ivacy, but their plugin used to work in Waterfox.  I don't think it's worked since the Waterfox release in October.  Their plugin connects to a VPN, but my IP address still shows up as my own.  Before, it would show up as their IP address. 

So, the plugin appears to install and work correctly, but the VPN connection doesn't seem to be taking place or simply isn't being used if a connection was established.  I will open a ticket with Ivacy as well since I don't know who broke it.  :(

**Comment by hawkeye116477** [comment]
Waterfox Current or Classic?

**Comment by own3mall** [comment]
Oh, I didn't even realize.  I'm running Classic.  Should I be running Current?

**Comment by hawkeye116477** [comment]
I see that it's marked as compatible with 56+, so theoretically should be working with Classic, if they marked correctly. Anyway that's webextension and Current has better compatibility with webextensions.

**Comment by own3mall** [comment]
Update:  It works fine in Waterfox Current.  Don't know why it doesn't work in Classic.
