### ISSUE TITLE
Could you plase uplift bug 1564330 to Waterfox Classic?

### ISSUE THREAD

**Issue by pintassilgo** [MrAlex94/Waterfox#1345]
https://hg.mozilla.org/releases/mozilla-esr68/rev/a72db9bbc92b

Brazil no longer has Summer Time, 2019/20 is the first year without it. Waterfox Classic is showing the wrong time by 1 hour and this is very annoying.

Thank you.

**Comment by Ibuprophen** [comment]
Did you try to turn the setting off regarding the DST (Daylight Savings Time)?

**Comment by pintassilgo** [comment]
Which setting?
