### ISSUE TITLE
[Classic] First party isolate breaks cookie cleaner extensions

### ISSUE THREAD

**Issue by Ph0rk0z** [MrAlex94/Waterfox#1346]
**Describe the bug**

First party isolation makes self destructing cookies or cookie autodelete unable to clear cookies.

**To Reproduce**
1. privacy.firstparty.isolate to true
2. try clearing cookies
3. cookies "cleared"
4. Check preferences, cookies remain

**Expected behavior**
Isolated cookies are all cleared.

**My configuration** 
 - Device: PC
 - OS: Win7/Linux
 - Version: Classic 2019.12/56

**Additional context**
I run current on some systems and I don't think the bug is present there but will now double check.

**Comment by hawkeye116477** [comment]
Related => https://bugzilla.mozilla.org/show_bug.cgi?id=1381197

**Comment by hawkeye116477** [comment]
@Ph0rk0z Can you confirm that's fixed now?
