### ISSUE TITLE
unable to install Waterfox in macOS Catalina 

### ISSUE THREAD

**Issue by saipraveen23** [MrAlex94/Waterfox#1348]
downloaded the  application from **https://www.waterfox.net**.
followed the instructions . when I am trying to open the application from **Finder**  getting the below error : 

“Waterfox” can’t be opened because Apple cannot check it for malicious software.
<img width="468" alt="Screenshot 2020-01-10 at 10 22 27 PM" src="https://user-images.githubusercontent.com/35190084/72171082-2b533200-33f8-11ea-9a89-08e17b6e41ea.png">

**Comment by ElhemEnohpi** [comment]
The application hasn't been "notarized", but I wouldn't call it a bug.

Apple now requires applications to be submitted to them for a virus check and approval ("notarized") by default, even from recognized developers. But if you trust the developer you can just right click the app and choose "open" and then "open anyway".

See the bottom of this page: https://support.apple.com/en-us/HT202491

**Comment by MrAlex94** [comment]
Which version?

**Comment by grahamperrin** [comment]
https://redd.it/fa773y mentions _Waterfox Classic_ but not a version. 

Key points: 

* Apple's workaround for users in this situation is linked from https://old.reddit.com/comments/fa773y/-/fiwg0p6/
* https://old.reddit.com/r/waterfox/comments/fa773y/-/fizfrrz/ 

> … Now that I’ve got some help I’ll dive in and see if I can get notarisation working for Classic too.

👍

**Comment by grahamperrin** [comment]
@MrAlex94 would you like to make sticky your comment in Reddit?

(Mine is unstuck; I can't stick yours.)
