### ISSUE TITLE
Waterfox not detecting any updates - again...

### ISSUE THREAD

**Issue by NebelNidas** [MrAlex94/Waterfox#1352]
It indeed detects the updates eventually, but only around one to two months later. IDK why, I had already opened issue #1323 for the 2019.12 release, but when it suddenly worked, I thought it maybe was just a temporary issue. However, since 56.2.14 → 2019.10 it happens on every release. Could it be related to the new versioning scheme? (It's not working on both Classic and Current)

**Comment by NebelNidas** [comment]
BTW, my Current 2019.10 still doesn't detect any updates. At least Classic did that after a few weeks...

**Comment by grahamperrin** [comment]
> every release. 

It's normal for full installers and updates to **not** become available at the same time. 

Normal for full installers to be made available first.

**Comment by NebelNidas** [comment]
Yeah, usually there's a few hours delay, if not a few days. But it shouldn't take weeks or months! No, there must be another issue going on.

**Comment by grahamperrin** [comment]
Two current update paths: 

* Waterfox Classic 2019.12 ▻ Waterfox Classic 2020.01
* Waterfox Current 2019.10 ▻ Waterfox Current 2020.01

Does any outdated path _not_ work for you, at this time? This, for example, should work: 

* Waterfox Classic 2019.10  ▻ Waterfox Classic 2019.12

**Comment by NebelNidas** [comment]
The outdated paths all work, at least for Classic. For testing, I downloaded [Classic 2019.10 Portable](https://storage-waterfox.netdna-ssl.com/releases/win64/portable/WaterfoxPortable_2019.10_English.paf.exe) and started it. Immediately it prompted me to update: 
![Waterfox 2019 10 detecting 2019 12](https://user-images.githubusercontent.com/48808497/72238396-e4269600-35dd-11ea-8612-f3e1e4c4ed8e.PNG)
Then, after installing 2019.12, it says it's up to date:
![Waterfox 2019 12 up to date](https://user-images.githubusercontent.com/48808497/72238441-fe607400-35dd-11ea-89cb-8387bf13b06a.PNG)
which is exactly the problem.

As said above, Current only updates to 2019.10, nothing above that.

**Comment by grahamperrin** [comment]
OK, thanks. 

Re: https://www.waterfox.net/blog/waterfox-2020.01-release/ the installers for Waterfox Classic 2020.01 and Waterfox Current 2020.01 were made available around four days ago so let's wait a little longer before treating updaters as weeks late.

**Comment by NebelNidas** [comment]
A bit late, but I wanted to inform you that the latest updates, for both Classic and Current, finally got detected 4 days ago. Now I have two final questions preventing me from closing the issue:
1. Why are the auto-updates delayed in the first place? Shouldn't it be possible to release the updates on the website and in the auto-updater simultaneously? Or is this purposely done for testing, should it contain critical bugs?
2. Why do some people get the auto-updates immediately and some not? Is it random? Or region-based? Because, as said above, it's only been happening to me since 2019.10. Others, on the other hand, get it right after the release, as it should be happening in my opinion and as it happened all the time before.

**Comment by hawkeye116477** [comment]
@Cicero-Interactive As I remember on reddit or some other place MrAlex told that's delayed, cuz he must test if security patches doesn't crash browser.

**Comment by GJRobert** [comment]
As of Jan 31 UTC+8 and also to date, my Waterfox Classic 2019.12 still cannot detect the update release:
![2020-01-31_10-08-15](https://user-images.githubusercontent.com/655584/74307095-7ec1f280-4d9f-11ea-9f75-91104036d5bc.png)

...or it can detect but is not able to perform the downloading and auto-updating?
![2020-02-01_12-24-44](https://user-images.githubusercontent.com/655584/74307131-9b5e2a80-4d9f-11ea-8b18-db3be0730f45.png)
(The zh-tw bubble dialog about not being able to update but can direct the user to the download page, which pops up every day to me here)

Making me wondering under what circumstances would Waterfox act like this.

**Comment by NebelNidas** [comment]
> As I remember on reddit or some other place MrAlex told that's delayed, cuz he must test if security patches doesn't crash browser.

@MrAlex94 Can you tell us if this really is intended behavior or not? So I can finally close this issue. 😉
