### ISSUE TITLE
Different comments on same subpage

### ISSUE THREAD

**Issue by hawkeye116477** [MrAlex94/Waterfox#1354]
**Describe the bug**
When you go to https://www.waterfox.net/blog/waterfox-2020.01-release, then you will see 2 comments, but if you add slash on end of line, then you will see more comments.

**Expected behavior**
Should be the same amount of comments on both pages.

**Comment by grahamperrin** [comment]
#582

**Comment by hawkeye116477** [comment]
Seems that problem is solved now, page without slash is now „not found", but release notes in about dialog leads to „not found" page, so there is another problem now. Page should rather redirect to that page with slash.

**Comment by laniakea64** [comment]
> release notes in about dialog leads to „not found" page, so there is another problem now. 

I'm not seeing this in Waterfox Current 2020.01 (self build from https://github.com/MrAlex94/Waterfox/commit/bd2f3dffe7ad66eb47bb5e1a870298223530726f ).  "What's new" link in about dialog goes to https://www.waterfox.net/blog/waterfox-2020.01-release/

**Comment by hawkeye116477** [comment]
Yeah, seems that problem isn't on Waterfox Current, but is on Classic.
