### ISSUE TITLE
Waterfox classic portable 2020.01 unavailable

### ISSUE THREAD

**Issue by TheQuickFox** [MrAlex94/Waterfox#1358]
I'm currently unable to update my Waterfox classic 2019.12 to version 2020.01 because the download is missing from the Waterfox web server:

https://storage-waterfox.netdna-ssl.com/releases/win64/portable/WaterfoxPortable_2020.01_English.paf.exe

"404 Not Found
nginx"

**Comment by TheQuickFox** [comment]
Is there any reason for the delay of the portable version and why this has not gotten resolved yet?

**Comment by TheQuickFox** [comment]
How do we actually get support on this?

**Comment by MrAlex94** [comment]
https://www.waterfox.net/download/

2020.02 portable is available

**Comment by melnation-com** [comment]
This is a false case solved, This specific issue is for the **CLASSIC** version proven with this link. as of 26Jan2021 is not working https://cdn.waterfox.net/releases/win64/portable/WaterfoxPortable_2021.01_English.paf.exe

The presumed working available is the non-classic or Third Generation version proven with this link. https://cdn.waterfox.net/releases/win64/installer/Waterfox%20G3.0.2%20Setup.exe
