### ISSUE TITLE
locale files

### ISSUE THREAD

**Issue by 0xFF1E071F** [MrAlex94/Waterfox#1369]
where can i download locale files as a whole tarball package?
Or
where can i download locale as a single file.

PS: i am talking about the files with the extension of 'xpi'

**Comment by hawkeye116477** [comment]
For Waterfox Classic or Current?

**Comment by 0xFF1E071F** [comment]
Sorry for not to mention: I asked for waterfox-classic.
But at the end i need both. =)

**Comment by hawkeye116477** [comment]
@0xFF1E071F Locales are inbuilt in packages, should be on `waterfox-classic/browser/features`. However if you're using Linux and my repository, then you can install them from repository, just look for `waterfox-classic-i18n-*` packages.

**Comment by 0xFF1E071F** [comment]
i am using linux and your repository (and the latest release 2019-12)
i can compile waterfox-classic from source everything is ok.
now i need waterfox-classic-i18n-* packages and i couldn't manage to find them :/
i have search through your repo but no results actually.
if the waterfox-classic-i18n-*.xpi packages are built during compilation should i add some kind of flag during compilation?

**Comment by hawkeye116477** [comment]
@0xFF1E071F Latest release is 2020.01. Are you sure that you typed correctly?
![i18n](https://user-images.githubusercontent.com/19818572/72726875-cc28b680-3b89-11ea-819b-4997d8c35719.png)

You can also type `waterfox-classic-i18n` in Synaptic.

Or directly download from https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_16.04/amd64/.

**Comment by 0xFF1E071F** [comment]
@hawkeye116477 
1. at this link: https://github.com/MrAlex94/Waterfox/releases there is no 2020.01 tarball package, am i missing something?

2. I am also making a waterfox package for [PisiLinux](https://pisilinux.org/) & [Pisilinux-Github](https://github.com/pisilinux) So i need sources. The link you send me are debian packages of language files. Isn't that possible for me to download xpi files directly or in a tarball package?

3. sorry for misunderstanding i searched the term "waterfox-classic-i18n" under your github repo.

**Comment by hawkeye116477** [comment]
@0xFF1E071F It's just not tagged yet, probably @MrAlex94 forgot about that. However commit [45130a237874aaa96bdf23ee107b0be0e0a2afab](https://github.com/MrAlex94/Waterfox/tree/45130a237874aaa96bdf23ee107b0be0e0a2afab) is for 2020.01.

`sorry for misunderstanding i searched the term "waterfox-classic-i18n" under your github repo.`
It's not mine repo, it's MrAlex's repo. I thought that you mean my apt repository. Anyway if you want locales, then you don't need to add any special flag, files are named `langpack-*@waterfox.xpi` and will be in `browser/features` directory after compilation, you didn't need to do anything special.
Before building, they are also here => https://github.com/MrAlex94/Waterfox/tree/45130a237874aaa96bdf23ee107b0be0e0a2afab/browser/extensions.

**Comment by 0xFF1E071F** [comment]
> Before building, they are also here => https://github.com/MrAlex94/Waterfox/tree/45130a237874aaa96bdf23ee107b0be0e0a2afab/browser/extensions.
1. I think that is what i need thank you very much
2. @MrAlex94 can you please tag the new version =)

Closing 1369

**Comment by grahamperrin** [comment]
Re: tags for this month's releases, https://redd.it/eqdm0r

**Comment by 0xFF1E071F** [comment]
> Re: tags for this month's releases, https://redd.it/eqdm0r

@grahamperrin  so we still can't download 2020.01 from @MrAlex94 's github repo :/

**Comment by Ibuprophen** [comment]
@0xFF1E071F, the very last part of the sentence within the Reddit link (from @grahamperrin) was that the 2020 versions will be available `after the libc issue is resolved.`.

I just wanted to point this out in case you may have accidentally overlooked that part. 


~Ibuprophen

**Comment by hawkeye116477** [comment]
`that the 2020 versions will be available after the libc issue is resolved`
It's rather not correct, cuz everything is fine on source, MrAlex only needs to compile on some older distro. Unfortunately some things can't be just statically linked, so probably the only way is to use older distro, just like I did with AppImage package, which is built on CentOS 7 (OBS VM).

**Comment by Ibuprophen** [comment]
My apologies @hawkeye116477... 

Since the Reddit post was only a few days old, it had appeared as if that was the reason for the delay. 

Thank you very much for clarifying this! :-) 


~Ibuprophen
