### ISSUE TITLE
sqlite 3.31.0 breaks Waterfox 

### ISSUE THREAD

**Issue by ilikenwf** [MrAlex94/Waterfox#1374]
I can't explain this better than the Mozilla devs, but 3.31.0 makes a hack Mozilla was using now unnecessary.

https://hg.mozilla.org/try/rev/8d7104bac33729b4da67954b07fb08371df39bd8

I maintain the waterfox-git package for Archlinux and will probably be adding this to the build until it gets merged here.

**Comment by hawkeye116477** [comment]
https://github.com/MrAlex94/Waterfox/commit/549c9fc74a9875f05d871b50012f0e7c8e6abb2d.
