### ISSUE TITLE
About Waterfox contains link to a broken page

### ISSUE THREAD

**Issue by strotee** [MrAlex94/Waterfox#1377]
About Waterfox ('Whats new') points to a non-functional hyperlink (page states "Not Found" with an all white background) but if one were to add a forward slash (/) at the end it then connects to a functional page. Top pic shows the non-functional while the bottom shows the functional with the slash. [Image](https://i.imgur.com/jZr9mDI.png)

**Comment by laniakea64** [comment]
https://github.com/MrAlex94/Waterfox/issues/1354#issuecomment-576876246
