### ISSUE TITLE
Wrong tag for 2020.01 Classic

### ISSUE THREAD

**Issue by hawkeye116477** [MrAlex94/Waterfox#1383]
Tag points to 2019.12, but should point to 2020.01.
See https://github.com/MrAlex94/Waterfox/blob/2020.01-classic/browser/config/version_display.txt.

Rather commit https://github.com/MrAlex94/Waterfox/commit/45130a237874aaa96bdf23ee107b0be0e0a2afab should be associated with tag 2020.01-classic.

**Comment by grahamperrin** [comment]
* `2020.01-classic`

Also, no tag for: 

* `2020.02.1-classic`

Meta, tracking: #538

Impact on (unofficial): 

* https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads#202001-classic
* https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads#202002-classic
* https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads#2020021-classic

**Comment by MrAlex94** [comment]
Fixed https://github.com/MrAlex94/Waterfox/releases/tag/2020.01-classic

**Comment by grahamperrin** [comment]
Thanks, https://github.com/MrAlex94/Waterfox/releases/tag/2020.02.1-classic is not found … doesn't bother me personally, if it's not easily tagged <strike>then I'll work</strike> (I worked around it in my wiki page).

**Comment by grahamperrin** [comment]
### … Current

Hmm, the upper (earlier) range of dates here are not fitting, at a glance: 

https://github.com/MrAlex94/waterfox/compare/2020.01-current...2020.02-current

It's peculiar (but not worrying) to see the date range that's covered by the first two-thirds of the comparison page. https://github.com/MrAlex94/Waterfox/releases/tag/2020.01-current was released 2020-01-24.

@hawkeye116477 @MrAlex94 please, is this another peculiarity of GitHub? Or maybe another tag pointer issue?
