### ISSUE TITLE
Waterfox 2020.01 current dead space where minimize/maximize/close buttons are even when titlebar is used

### ISSUE THREAD

**Issue by RaitaroH** [MrAlex94/Waterfox#1384]
**Describe the bug**

I noticed after the upgrade (manually downloaded the tarball) that now waterfox can have minimize/maximze/close buttons integrated in the tabbar. It seems though, the space they take is still there even after "Titlebar" is enabled in Customize. I don't have titlebars because I removed them, but now it seems waterfox just allocates that **small** space to nothing at all.

**To Reproduce**
1. Go to Customize
2. Enable titlebar. Drag Space is not active (nor can it be)
3. I also have some extra icons in between the New Tab Button and the new dead space. Not an issue before.

**Expected behavior**

I expected the icons to be flush, no dead space.

**Screenshots**
![image](https://user-images.githubusercontent.com/19552720/73559981-cc189880-445e-11ea-83d8-2ac9171601a2.png)
![image](https://user-images.githubusercontent.com/19552720/73559990-d2a71000-445e-11ea-833b-3e31b2db1764.png)

**My configuration** 
 - Device: Dell Inspiron 7567 gaming
 - OS: Manjaro, KDE 5.17.5
 - Version: 2020.01 (64-bit)

**Additional context**

**Comment by laniakea64** [comment]
This sounds like issue I noticed that was fixed by https://github.com/MrAlex94/Waterfox/pull/1353 .  Are you able to build Waterfox yourself from latest `current` branch?

**Comment by hawkeye116477** [comment]
Or download AppImage => https://appimage.github.io/Waterfox_Current/. You can even extract it if you want.

**Comment by RaitaroH** [comment]
@hawkeye116477 yes, the appimage does not have this problem. I extracted it, replaced the tarball with the `bin/` found in the appimage and now waterfox performs as it should. Thanks.
