### ISSUE TITLE
Classic - Website issues - GitHub and answers.unrealengine.com

### ISSUE THREAD

**Issue by victor-vexargames** [MrAlex94/Waterfox#1387]
GitHub is asking to install a new browser again. The following message appears:

Please note that GitHub no longer supports old versions of Firefox.

We recommend upgrading to the latest Safari, Google Chrome, or Firefox.

answers.unrealengine.com is give the following error only using Waterfox 

Forbidden

You don't have permission to access / on this server.

**Comment by grahamperrin** [comment]
GitHub: see #1360

**Comment by hawkeye116477** [comment]
In case of unreal, seems that changing useragent to `Mozilla/5.0 (Windows NT 7.0; rv:68.0) Gecko/20100101 Firefox/60.0` helps, but then page looks broken.

Update: Seems, that override for `unrealengine.com` isn't enough, if I do override for all sites, then it's all fine.

Ping @MrAlex94

**Comment by hawkeye116477** [comment]
@MrAlex94 Problem is still not solved (unrealengine).

**Comment by MrAlex94** [comment]
Interesting, there must be some other network request that’s happening to check the browser. So much for the open web 🙄

**Comment by hawkeye116477** [comment]
Because now user-agent overrides from release tagged as 2020.07.2.1-classic, work for all requests, then that problem should be solved :smile:
