### ISSUE TITLE
Provide a Flatpak as software package

### ISSUE THREAD

**Issue by x80486** [MrAlex94/Waterfox#1388]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

**Comment by hawkeye116477** [comment]
If you want official flatpak package, then that rather won't happen, there is one constant developer and he rather doesn't have time to do it. 
There was also discussion about AppImage => https://github.com/MrAlex94/Waterfox/issues/127.

**Comment by x80486** [comment]
OK, your call...

**Comment by ghost** [comment]
https://github.com/MrAlex94/Waterfox/issues/1752
