### ISSUE TITLE
[Feature request]Font weight settings

### ISSUE THREAD

**Issue by nobk** [MrAlex94/Waterfox#1392]
Font settings as firefox, I can choose which font and mono space font I use. But it always use 'Regular' font weight(font weight 300) do webpage render.
Even if the font I choose have may font weight like 100,200,300,400, 500, 600,700,800. I have no choice to select and use them.
Please add a font weight settings to options page, let user choose which font weight as default webpage render font weight.

**Comment by nobk** [comment]
I find Waterfox Classic 2020.02.1 can select font with font weight. Like 'Iosevka SS13 Medium' or 'Sarasa Term SC Semibold' at about:preferences#content. That is what I want.
Please port this feature to Waterfox Current, it really help.
![c](https://user-images.githubusercontent.com/4659870/76165470-44772580-6192-11ea-99b9-d9aef1a93305.PNG)

**Comment by grahamperrin** [comment]
@nobk [ReFont](https://addons.mozilla.org/addon/refont/) might be of interest. 

----

Side note, for reference only, my old Reddit view of the support area e.g. https://old.reddit.com/r/waterfox/ is bugged – but only if I allow the subreddit style (I do not): 

![image](https://user-images.githubusercontent.com/192271/76166972-e8dd7580-615a-11ea-8f36-b1c3f428276a.png)

Help not required by me; I probably posted to the support area years ago. Moreover, the poor rendering might be peculiar to FreeBSD (I'm not aware of any user of Linux reporting the problem).
