### ISSUE TITLE
Waterfox Android: Able to sign into Firefox Sync, but it dun't sync.

### ISSUE THREAD

**Issue by LafinJack** [MrAlex94/Waterfox#1397]
Hi there, I've been having a very weird problem with one of my Android devices while the other has no issues at all. Recently my Pixel 2 running Android 10 build QP1A.191005.007.A1 (holy crap Google can't you use normal version numbers like everybody else?) has been unable to sync, while my Huawei M5 running Huawei's own version of Android, Android 8.0.0.199(C567) keeps syncing just fine along with my Windows Waterfox.

When I'm "signed in" on the Pixel 2, the "Sync now" button below the username button says "Last synced: never", the checkboxes below are greyed out, the "Sync only over Wi-Fi" toggle is toggleable back and forth but does nothing else, and the only other things in the Sync settings page that work are "Disconnect...", "Terms of service", and "Privacy notice".

I am able to click "Sync now", but it immediately changes to what I assume is "Syncing" and then immediately reverts back to "Sync now", status "Last synced: never". I can  click Sync Now as many times as I do not like and it remains at sync status: never.

I am able to go through the normal sync login process, which gives me the happy "hey you're synced" page. Still won't sync, though.

I am able to use the Disconnect function to disconnect this device from my account, and then go through the process of resyncing it with Firefox again, but it then reverts to the above behavior. I have also gone into the "about:accounts?action=manage" page which shows my Huawei M5, Windows machine, and however many "Web Session, Firefox Mobile 68" sessions I've created and disconnected and haven't deleted yet.

I've deleted the cache and retried, deleted all user data and retried, and uninstalled and reinstalled and retried, and even installed Firefox and it worked but still nothing for Waterfox.

Is this just me? Or how did Android 9/10 break Waterfox syncing?

**Comment by mohibo** [comment]
for me when i tried to sync,waterfox just crashes
