### ISSUE TITLE
Waterfox Current 2020.02: libc++.so.1 error on startup

### ISSUE THREAD

**Issue by vcekron** [MrAlex94/Waterfox#1402]
**Describe the bug**
Upon startup of binary Waterfox Current 2020.02 release, it gives an error seemingly related to the shared library libc++.so.1.

**To Reproduce**
1. Download and install the Waterfox Current 2020.02 binary release (I used the following PKGBUILKD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=waterfox-current-bin with this patch: https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=waterfox-current-bin&id=ea015e616b82b9f4f3ad71e41172627882f747da).
2. Execute `/usr/bin/waterfox-current`.
3. Get error:
`/usr/bin/waterfox-current: error while loading shared libraries:`
` libc++.so.1: cannot open shared object file: No such file or directory`

**My configuration**
 - OS: Arch Linux x86_64
-  Kernel: 5.5.3-arch1-1
 - Version: Current 2020.02

**Additional context**
Everything on my system is up to date.

**Comment by MrAlex94** [comment]
Could you try installing the [libc++](https://aur.archlinux.org/packages/libc%2B%2B/) package?

**Comment by vcekron** [comment]
> Could you try installing the [libc++](https://aur.archlinux.org/packages/libc%2B%2B/) package?

Thanks Alex, that certainly helped. Am I to infer this is a new dependency then?

Cheers

**Comment by MrAlex94** [comment]
Ideally not, will try to get it statically linked

**Comment by vcekron** [comment]
> Ideally not, will try to get it statically linked

Excellent, I agree. That package is a whole thing.

Let me know if you need me to do some tests further on.

**Comment by MrAlex94** [comment]
Thanks, will let you know.

**Comment by vcekron** [comment]
Any news regarding this? I would like to update the AUR package, but would prefer to do so without the added `libc++` prerequisite.

**Comment by stuart909** [comment]
I am also having this issue in Fedora 29 5.3.11-100.fc29.x86_64.  Everything was working fine until I upgraded to the latest build.  I have installed libc++, still fails.

edit:
I had to specifically install another variant of libcxx:

libcxx-7.0.0-1.fc29.x86_64

This is the same dependency the older version of discord had.

**Comment by hawkeye116477** [comment]
@stuart909 Fedora 29 is EOL, you should upgrade.
