### ISSUE TITLE
Runaway Scripts in Classic Freezing Browser & OS

### ISSUE THREAD

**Issue by pjpreilly** [MrAlex94/Waterfox#1404]
I'm experiencing serious javascript issues with runaway scripts crashing the OS in Classic. On Linux and os x Lion these sites have runaway scripts. Tested in Safe mode. Seems to have arisen in 2020.1.1 and carried over to 2020.2

https://www.wunderground.com/dashboard/pws/KPACHELT4?cm_ven=localwx_pwsdash

https://www.cnn.com/2020/02/13/politics/jessie-liu-trump-administration/index.html

**Comment by hawkeye116477** [comment]
I can't reproduce.

**Comment by pjpreilly** [comment]
I can't reproduce.

... try the wunderground site & scroll in the page.. 
The loading spinner on the tab freezes..

**Comment by pjpreilly** [comment]
...sometimes I get the dropdown window about stopping a script that's not responding.

**Comment by pjpreilly** [comment]
on Mac OS I watched it tochewthrough a gigabyte of ram until it had none and then the system froze.

**Comment by pjpreilly** [comment]
On OS X Mojave with just those two tabs open waterfoxCP web content is consuming / 1 1/2 GB of memory causing memory to go down to less than 30 megabytes free.

**Comment by pjpreilly** [comment]
if it makes any difference those two tabs or pinned tabs.

**Comment by MrAlex94** [comment]
I can't reproduce either on macOS 10.15, in safe mode or without add-ons.

**Comment by pjpreilly** [comment]
.. It happened earlier but now it seems to have cleared up, I'll Monitor and give information as I get it. in OS Mojave it does seem to use a lot of memory for just two pined tabs.

**Comment by pjpreilly** [comment]
.. might have something to do with blocking autoplay media especially advertisements??

**Comment by pjpreilly** [comment]
Some insight **[here](https://www.reddit.com/r/waterfox/comments/f3dw3c/waterfox_202002_release_security_issues_fixed_and/fhm7lun?utm_source=share&utm_medium=web2x)**:

**Comment by pjpreilly** [comment]
This Wundermap widget as well as the wundermap sight itself is a processing/javascript nightmare for os x 10.7 and probably 10.8. It causes excessive memory as well as processor consumption & does not render correctly & needs to be blocked on this OS. Image is from a correct rendering on a chromebook.

![Screenshot 2020-02-15 at 1 44 36 PM](https://user-images.githubusercontent.com/10430084/74593503-cba10580-4ff9-11ea-84d6-2ac7e2c14f45.png)

**Comment by pjpreilly** [comment]
.. & on os x 10.7:

![2020-02-15 01 58 25 pm](https://user-images.githubusercontent.com/10430084/74593633-34d54880-4ffb-11ea-9bf8-cbc24cd5a8e7.png)

**Comment by grahamperrin** [comment]
> crashing the OS 

As the developers have been unable to reproduce a kernel panic in relation to this issue, it's possible/likely that a normal `.panic` file will be not immediately useful. So please follow this guide: 

[Troubleshooting: getting more from kernel panics with keepsyms (address to symbol translation) | MacRumors Forums](https://forums.macrumors.com/threads/troubleshooting-getting-more-from-kernel-panics-with-keepsyms-address-to-symbol-translation.1834117/)

Then after the next system crash, please provide the `.panic` file for the incident. You'll find `.panic` files at:

`/Library/Logs/DiagnosticReports`

### Additional reference material

This is old (2013) but does cover versions 10.7 and 10.8 of Mac OS X: 

* [Mac OS X and iOS Internals: To the Apple's Core](http://newosxbook.com/MOXiI.pdf) (Jonathan Levin)

**Comment by pjpreilly** [comment]
K.P. not reported here.

**Comment by grahamperrin** [comment]
Are these OS crashes (kernel panics), application crashes or tab crashes?

**Comment by pjpreilly** [comment]
In this instance they are system freezes. I/O ceases to work first for the browser & then the OS.
