### ISSUE TITLE
Classic 2020.02 (64-bit), DRM/Plex issue?

### ISSUE THREAD

**Issue by strotee** [MrAlex94/Waterfox#1405]
After installing Classic 2020.02 (64-bit), I noticed an unusual issue, which fortunately, I have found a work-around of sorts. Opening Plex web interface in Waterfox (default browser), it takes what feels like 30+ seconds, not the usual 1-2 seconds in previous editions of Waterfox. It will prompt with a message "Waterfox is installing components needed to play the audio or video on this page. Please try again later." with the Plex logo in the middle of the screen and then after seemingly 30+ seconds, it finally does log in successfully. 

However, disabling "Play DRM content" under Content in about:preferences, allows Waterfox to login promptly (similar to older versions of Waterfox), but now I have a "You must enable DRM to play some audio or video on this page." message at the top of my browser. While I rarely playback video files in my browser (regularly use my PS4 to watch), I wonder if I'll have issues leaving that aforementioned "Play DRM content" option unchecked. 

Just thought I would report the error to see if a recent code check-in broke DRM; thank you for your hard work and continued support for the Classic branch.

**Comment by MrAlex94** [comment]
You should be able to have it disabled, I think DRM playback is to do [with this](https://forums.plex.tv/t/why-does-plex-web-request-drm-support/490361). Also after the first prompt, you shouldn't receive one again :-) basically after accepting DRM, it downloads Widevine from Google - but should only do that once.

I'll close this, but feel free to open again if you need to.

**Comment by hawkeye116477** [comment]
@MrAlex94 It's because you missed MrAlex94

**Comment by warpfactor999** [comment]
This appears to have popped up again with the last update. Works if you turn off DRM. If you turn DRM back on, it takes a VERY long time to run.
