### ISSUE TITLE
[Current] Restore RSS live bookmarks functionality

### ISSUE THREAD

**Issue by maxoku** [MrAlex94/Waterfox#1408]
Please restore RSS live bookmarks that are still in classic version to current version.
Add-ons don't provide the same functionality and can't import live bookmarks from classic version.

**Comment by grahamperrin** [comment]
FYI https://redd.it/ccftqq

**Comment by maxoku** [comment]
Thanks for the lecture, any progress there?

**Comment by sjehuda** [comment]
What's the status of this?

Does Waterfox has RSS icon and reader by default?

Reference: https://openrss.org/blog/browsers-should-bring-back-the-rss-button
