### ISSUE TITLE
[Current] Release dictionary for English spellchecking from omni.ja file

### ISSUE THREAD

**Issue by maxoku** [MrAlex94/Waterfox#1410]
While Waterfox (like Firefox) doesn't allow to use multiple dictionaries at the same time I'm merging them manually with an app and replacing the main (en-us) dictionary files. Classic puts those freely in a folder while Current have it in omni.ja file. What means to do that I need to modify the file every time after update instead to only replace two files. Please put those files normally like the Classic version does for easy access.

**Comment by hawkeye116477** [comment]
Appears that was done for performance improvements.
https://bugzilla.mozilla.org/show_bug.cgi?id=1457321

**Comment by maxoku** [comment]
Waterfox doesn't have to be like Firefox. What is safer, replacing two files or modifying omni.ja file?
Besides they should allow to use multiple dictionaries and they haven't done this for so many years.
