### ISSUE TITLE
Publish language packages on localization management platform

### ISSUE THREAD

**Issue by hawkeye116477** [MrAlex94/Waterfox#1412]
There are more and more untranslated things. So I think that's time to publish language packs on Crowdin just like Moonchild did. You can even setup GitHub integration (https://support.crowdin.com/github-integration/) for this.  Thanks to this, translating would be easier for translators, they will easier find untranslated strings. Crowdin has some price, but Waterfox is open-source project, so you can attend for free account (https://crowdin.com/page/open-source-project-setup-request).
There is also alternative service called Transifex, but I don't know if anything changed, cuz previously there were some problems (`https://forum.palemoon.org/viewtopic.php?f=30&t=10711&p=74863&hilit=transifex#p74863`).

Example configuration file => `https://github.com/hawkeye116477/LanguagePacksForWaterfox/blob/master/crowdin.yml`.

Update: Checked Transifex and still that problem appears. I found also possible alternative => `https://github.com/mozilla/pontoon/`, but I'll need to be self-hosted.

**Comment by steelmandi** [comment]
Hi, so what do you think about this on crowdin or other translate help.
yrs. Mandi

**Comment by GJRobert** [comment]
My experience on Crowdin is good.

**Comment by comradekingu** [comment]
@hawkeye116477 
It isn't gratis for libre software projects with a source of income
> If you're building awesome non-profit projects that could use the power of Crowdin, we're happy to help.
https://crowdin.com/pricing#annual

You also missed the small-text part where what crowdin calls "free" isn't gratis, as it requires you to contribute to their translation memory. Crowdin is closed source, and has no libre software interests.

Please don't use Crowdin, it is a sub-par tool with tracking everywhere https://support.crowdin.com/cookies/. Having used both extensively, I recommend https://weblate.org/hosting/ which has always been gratis for all libre software projects to use, and allows you to run your own platform too.
