### ISSUE TITLE
[Classic] Waterfox greatly lagging after visiting Facebook

### ISSUE THREAD

**Issue by maxoku** [MrAlex94/Waterfox#1413]
Every time I visit Facebook and do some stuff there Waterfox starts to lag, stopping to respond for few seconds constantly. I need to restart Waterfox to be able to use it normally again. It started recently after I installed 2020.01, before I used 2019.10 and didn't have such problems.

**Comment by NebelNidas** [comment]
Does this also happen on a new profile? To create a new one, go to `about:profiles` and select it as the default one. When you restart Waterfox, it will use this fresh one, and if it works, it's just your old profile which has been corrupted/slowed down by extensions. To go back to your old one, just set your old profile as default one again and restart the browser.

**Comment by maxoku** [comment]
@NebelNidas 
It started to happen after the update. And why extensions would slow down the browser only after visiting one site? I think if it was fault of extensions then it would slow down the browser generally without visiting Facebook. E.g. I haven't visited fb today and after the whole day using the browser it's still working normally. When one day I visited fb just after starting the browser it started to slow down very quickly, after about an hour I couldn't use it anymore without restarting.
