### ISSUE TITLE
Waterfox blog doesn't work without a trailing slash.

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox#1417]
See https://www.waterfox.net/blog/waterfox-2020.02-release

See https://www.waterfox.net/blog/waterfox-2020.02-release/

The former doesn't work and the latter does, the About box points to the former.

**Comment by hawkeye116477** [comment]
Duplicate of https://github.com/MrAlex94/Waterfox/issues/1377

**Comment by Squall-Leonhart** [comment]
closed as duplicate
