### ISSUE TITLE
Use OpenH264 to decode profiles it supports that the platform decoder does not

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox#1418]
Doing so would enable Win 7 and 8 to decode profile 5.2 content that is otherwise incompatible with the WMF decoder.

https://bugzilla.mozilla.org/show_bug.cgi?id=1608252

**Comment by Squall-Leonhart** [comment]
Alternatively, let us use Directshow filters again like we used to be able to on XP.

**Comment by wtfiwinomgs** [comment]
could we get an update on this from the devs? switching between browser is a real pain.
