### ISSUE TITLE
Question - New Waterfox partnership - What does that mean for Watefox Classic development?

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MrAlex94/Waterfox#1419]
As you are now partnering with "System 1" - which was interested to keep "Classic Firefox" around - will this partnership will lead to

- a possible improvement in web-compatibility features in Waterfox Classic  - 

or

- is this partnership only benefiting the Current branch?

Thanks!

**Comment by grumpygeek** [comment]
I'd like to know if we, the users, remove Bing, and maybe all search plugins, would that eliminate any connection with the ad company, aka "Search Integrator" or is there something else to tweak?

**Comment by Squall-Leonhart** [comment]
maybe you didn't notice the commit history for classic?

**Comment by grumpygeek** [comment]
What kind of a response is that?  The commits here only show one branch (Current) which has 700,000 items.   No way to select Classic branch.  If you found something in commits, a link to it would be kind of helpful.  And there is no release history or anything similar on the WF download page.

**Comment by grahamperrin** [comment]
> No way to select Classic branch.

https://github.com/MrAlex94/Waterfox/tree/classic

**Comment by reallyuniquename** [comment]
@Squall-Leonhart 
>maybe you didn't notice the commit history for classic?

What are you referring to exactly?

**Comment by grahamperrin** [comment]
> Question

Folks, GitHub issues is not a discussion forum. 

Alex invited discussion in the support area – https://old.reddit.com/r/waterfox/comments/f3zm8o/waterfox_has_joined_system1_waterfox_now_has/ – you'll find answers to most things there. 

It's already stated that there'll be a blog post about engineering etc. next month so please be patient for statements about development. 

Thanks

**Comment by grahamperrin** [comment]
If I understand correctly: it's still planned to have another blog post before the end of this month :-)

#582
