### ISSUE TITLE
Pressing "f" for fullscreen doesn't work on youtube if the focus is not on the player. Works on chrome

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1422]
**Describe the bug**
Back/forward arrows, space, "c" on the other hand work. It's annoying because of the lot "f" for fullscreen is most likely the most frequent one I use.

**My configuration** 
 - Device: PC
 - OS: Win8.1
 - Version: Classic 2020.02

**Comment by wtfiwinomgs** [comment]
mine works just fine. in both chrome and latest waterfox current, even when unfocused.

I'd purposely click on comment sort by date/popular then press f and it'll go full screen just fine.

**Comment by mzso** [comment]
[**@wtfiwinomgs**](https://github.com/wtfiwinomgs) commented on [2020. febr. 23. 08:31 CET](https://github.com/MrAlex94/Waterfox/issues/1422#issuecomment-590035844 "2020-02-23T07:31:44Z - Replied by Github Reply Comments"):
> mine works just fine. in both chrome and latest waterfox current, even when unfocused.
> 
> I'd purposely click on comment sort by date/popular then press f and it'll go full screen just fine.

Are you also using the classic version?

**Comment by mzso** [comment]
[**@wtfiwinomgs**](https://github.com/wtfiwinomgs) commented on [2020. febr. 23. 08:31 CET](https://github.com/MrAlex94/Waterfox/issues/1422#issuecomment-590035844 "2020-02-23T07:31:44Z - Replied by Github Reply Comments"):
> mine works just fine. in both chrome and latest waterfox current, even when unfocused.
> 
> I'd purposely click on comment sort by date/popular then press f and it'll go full screen just fine.

What can I say? I create a new profile, open youtube click anywhere outside the player and "f" for fullscreen stops working.

**Comment by NebelNidas** [comment]
I can confirm this issue with Classic 2020.02.1 on the latest Windows 10.

**Comment by mzso** [comment]
Looks like it was fixed by someone somewhere, because right now it's working. Maybe by v2020.03

**Comment by NebelNidas** [comment]
Yeah, seems to have been fixed with 2020.03!
