### ISSUE TITLE
[Classic] Videos on pornhub don't play (possibly OpenH264 Video Codec update issue)

### ISSUE THREAD

**Issue by TheWhiteAvatar** [MrAlex94/Waterfox#1423]
Some people already tried to report it on the Waterfox's reddit, but I'm not sure it will be heard there.

**Describe the bug**
Videos on pornhub.com stopped playing after the recent update. It might have something to do with OpenH264 Video Codec being updated at the same time.

It's really possible, that some other sites got the same issue now.

**To Reproduce**
Open the pornhub.com and try to play any video, in Waterfox Classic 2020.02 (64-bit)

**My configuration** 
 - Device: PC
 - OS: Windows 7
 - Version: Classic 2020.02 (64-bit)

**Comment by Squall-Leonhart** [comment]
don't think it has anything to do with the video codec, as that would mean very pornhub video was suddenly reencoded overnight (they weren't.)

the issue seems to be rather that they dropped support for some legacy html5 code that 56 is reliant on but kept something compatible with chrome 66 and IE11

**Comment by tribes11** [comment]
I second that, doesn't work for me.

**Comment by nomosaic** [comment]
When I tried to play some videos, they crashed in Waterfox, no sound in Vivaldi. Only Chrome was playing well. (This kind of example is quite rare.)
e.g.  pornhub.com/view_video.php?viewkey=ph5d606a8650465
BTW, if I set the "shadow dom" parameter of “dom.webcomponents.enabled” to "false", PH player UI will become as a black blank backgound as there is no player on the place anymore.
