### ISSUE TITLE
[Classic] Notion.so as blank page

### ISSUE THREAD

**Issue by GJRobert** [MrAlex94/Waterfox#1424]
**Describe the bug**
All blank page for [Notion](https://www.notion.so/). Suddenly starting from early Feb 2020, on Waterfox Classic 2019.12 and 2020.02. macOS El Capitan. Not happening on Firefox 72, Vivaldi 2.9.

New profile does not help.

The error message in the Browser Console (view-source:https://www.notion.so/app-c6a505fe3c92dcae33d7.js):
```
SyntaxError: generator function or method can't be async
```
This message does not appear in Firefox 72 Browser Console.

**To Reproduce**
1. Go to any page of the site Notion.so
2. All blank page after the loading looks finished (or interrupted).

**Expected behavior**
Notion.so used to work correctly before this month on Waterfox Classic 2019.12.

**My configuration**
 - Device: MacBook Air 2013-Mid
 - OS: macOS 10.11.6 El Capitan
 - Version: Classic 2019.12, 2020.02/56.3

**Comment by grahamperrin** [comment]
> All blank page 

Reproducible with home-built Waterfox Classic 2019.12 (20200103060435) on FreeBSD-CURRENT. 

I tried a few UA overrides, including one for Firefox 68.0 and one for Firefox 73.0 … not really expecting any one to be effective. None was effective.

**Comment by hawkeye116477** [comment]
Seems that starts working fine from Firefox 57.
Tried with mozregression to find something, but seems that works on Firefox 56 Nightly, but not on stable version, so can't find. So probably something was enabled in Nightly, but disabled on stable.

**Comment by hawkeye116477** [comment]
@GJRobert Check on 2020.02.1.

**Comment by GJRobert** [comment]
> @GJRobert Check on 2020.02.1.

Hi @hawkeye116477 ,

Really glad that the fix works for you. While on my side, the thing is not yet over with me...
![2020-02-24_20-07-42](https://user-images.githubusercontent.com/655584/75151748-6314ff80-5742-11ea-9b8f-af6f05d05844.png)
I have tried to load Notion.so with 2020.02 again last week, and to my surprise the contents got rendered, not blank page, but this "IndexedDB error" or "Cannot save changes" message started to appear, even with whole new Waterfox profiles.

And today after I see your kind-hearted post, I have updated to 2020.02.1, but get the same result as I just mentioned.

**Comment by hawkeye116477** [comment]
Ok, so that requires having account. I didn't checked how it works after logging in, fix was only for blank page. 

Update:
Mozregression results:
Last bad: 2018-03-04
First good: 2018-03-05
Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=190b536928f8a8ca96e52101d2013c88a1a66384&tochange=bccdc684210431c233622650a91454c09f6af9eb

Probable solution => https://bugzilla.mozilla.org/show_bug.cgi?id=1193394

**Comment by GJRobert** [comment]
Fixed in 2020.03! Saving is normal now.
Thank you so much @hawkeye116477 !
