### ISSUE TITLE
[Classic] Netflix unsupported as of today on Classic Waterfox?

### ISSUE THREAD

**Issue by kikaragyozov** [MrAlex94/Waterfox#1425]
Nothing is being played. There is a small pop-up saying that Waterfox is installing needed components, but I feel it's not doing anything. This problem did not persist yesterday I think.

**Comment by grahamperrin** [comment]
[Netflix and Prime Video not working since update : waterfox](https://www.reddit.com/r/waterfox/comments/f4em15/netflix_and_prime_video_not_working_since_update/) ▶ https://github.com/MrAlex94/Waterfox/issues/316#issuecomment-586655772

**Comment by Squall-Leonhart** [comment]
bug unnecessary, the fix is already checked in.

Fixed by 6a456932239efc6f595d3cb35b87113e4677a845

**Comment by grahamperrin** [comment]
@jorg35 was your down-vote because I did not provide a link to the commit? 

I'm sorry that Alex's words (linked) "Has been fixed and will be in the next update" were not good enough for you.

**Comment by kikaragyozov** [comment]
The fix has been officially deployed to the latest waterfox releases, hence why I'll be closing this issue.
