### ISSUE TITLE
Some about:config settings need to be altered, but I can't seem to find them.

### ISSUE THREAD

**Issue by Peacock365** [MrAlex94/Waterfox#1427]
@MrAlex94 @laniakea64 @hawkeye116477 

Some settings in about:config should be altered to different values, but I can't seem to find them. I ask you to create pull requests to fix those, if possible. The settings in question are:

Disable the predictive service (Necko):
_network.predictor.enabled - false_
https://wiki.mozilla.org/Privacy/Reviews/Necko

**Comment by Squall-Leonhart** [comment]
these prefs  do not exist by default, so add them.

this isn't worth a bug.

**Comment by Peacock365** [comment]
Where do I add them? In _modules/libpref/init/all.js_ or in _browser/app/profile/firefox.js_ or somewhere else? This is why I need help.

> this isn't worth a bug.

Oh, come on. Bugs have been opened for less here. I need support and want to change some about:config values, i.e. implement a change, this is definitely worth a bug. And don't tell me what to do, I have contributed stuff already, contrary to you might I add. 

Thanks for the non-support @Squall-Leonhart...

**Comment by laniakea64** [comment]
Sorry @Peacock365 but I'm currently too hassled to do any pull requests in the foreseeable future :frowning_face: 

> Disable Microsoft Family Safety by default

https://github.com/MrAlex94/Waterfox/issues/538#issuecomment-568214398

If you use Windows to build and test your pull requests, you can try see if changing this does the job? -
https://github.com/MrAlex94/Waterfox/blob/6bce12d08d55de605a41c66ea540108ec25418a8/security/manager/ssl/security-prefs.js#L50-L56

**Comment by Peacock365** [comment]
Does the job. Thank you for pointing me to the location of the setting, @laniakea64! Took the opportunity and got rid of some SSL telemetry, as well (new PRs created.) Thumbs up!

**Comment by Peacock365** [comment]
@hawkeye116477 @laniakea64 @MrAlex94 

Any idea where the setting _network.predictor.enabled_ can be found in WF Current?

**Comment by hawkeye116477** [comment]
@Peacock365 You have searchbar on top, you can find :smile:
Here it's:
https://github.com/MrAlex94/Waterfox/blob/d8326e125b8fde7e73d44891df935504b12362b3/modules/libpref/init/StaticPrefList.h

**Comment by reallyuniquename** [comment]
@Peacock365 
You really shouldn't patch browser internals just to change `about:config` options. Use  `about:config` context menu and choose `New` or try [autoconfig](https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig).
