### ISSUE TITLE
Feature request: Introduce setting to disable the reader mode in the preferences.

### ISSUE THREAD

**Issue by Peacock365** [MrAlex94/Waterfox#1431]
@hawkeye116477 

I think it would be a great idea to have two new settings in the preferences panel: One for the internal PDF reader and one for the reader mode:

_reader.parse-on-load.enabled
pdfjs.disabled_

Of course, both features should be enabled by default, but having actual settings to easily disable them would be neat to have. CTR used to have these settings, but alas it doesn't work in WF Current.

**Comment by hawkeye116477** [comment]
Disabling internal PDF reader is already possible, general (or Web Pages in new layout) => applications and just choose app in which you want open PDF.

**Comment by Peacock365** [comment]
@hawkeye116477 

The file type manager is one of the shittiest interfaces found in all of FF / WF, but I agree, it is possible. So maybe we shouldn't duplicate it. A setting for the reader mode would still be neat, though. That's definitely a feature some people would use.

**Comment by Peacock365** [comment]
@hawkeye116477 

A setting in the Tabs section of the preferences which controls the setting _browser.tabs.showAudioPlayingIcon_ would also be very cool. :-)

**Comment by Peacock365** [comment]
@hawkeye116477 

We should at least consider making those more accessible to users.
