### ISSUE TITLE
Old firefox "extensions.databaseSchema" bug in waterfox.

### ISSUE THREAD

**Issue by MichaelViV** [MrAlex94/Waterfox#1434]
When Mozilla was a transition period from addons to webextensions they create bug in extensions.databaseSchema. Only versions FF 55-56.X are affected. Waterfox inherited this bug. Has an effect on some legacy addons.

**Step to reproduce:**
1: Download clean version "Cookie Controller" addon ({ac2cfa60-bc96-11e0-962b-0800200c9a66}.xpi)
2: Install Waterfox browser, or just remove folder with user profile if alredy installed.
3: Open browser first time to create a folder with a user profile.
4: Close browser.
5: Create in C:\Users\XXXXX\AppData\Roaming\Waterfox\Profiles\XXXXX.default\ folder with name "extensions" and copy there {ac2cfa60-bc96-11e0-962b-0800200c9a66}.xpi.
6: Open browser and enable this addon, then restart.

**Expected behavior**
Addon should already work, but it’s not. Just open Menu --> Customize and you must see that several addon icons have no pictures. It seems that he is in some kind of inactive state.

**Screenshots**
Bug
![bug](https://user-images.githubusercontent.com/61154304/74668794-9f7ab580-51ae-11ea-8439-5a7676514fb6.png)
Normal work
![normal](https://user-images.githubusercontent.com/61154304/74668828-b0c3c200-51ae-11ea-8eee-9c37a3238686.png)

**My configuration**
 - Device: PC
 - OS: Windows 10, Ubuntu
 - Version:Classic 2020.02

**Additional context**
I think the same problem was described to you by one user https://github.com/MrAlex94/Waterfox/issues/295.
 To work around this problem, simply remove in C:\Users\XXXXX\AppData\Roaming\Waterfox\Profiles\XXXXX.default\prefs.js **user_pref("extensions.databaseSchema", XX);** This is not a panacea, but ... I have been doing this way for several years. But I would like you to pay attention to this bug and fix it.

**Comment by Squall-Leonhart** [comment]
this extension probably has the same cpow bug that popup blocker ultimate has and th existance of the buttons is a fault that causes the browser parent to leak memory.

**Comment by MichaelViV** [comment]
Firefox 54 and much lower not affected. As I said, this problem created Mozilla in version 55 and did not fix it because in version 57 support for legacy addons was removed. They didn't make sense to repair something. I have tried all versions of this addon. Always the same.
