### ISSUE TITLE
Feature request: Remove warning "Addon" is incompatible with Waterfox 56.3

### ISSUE THREAD

**Issue by MichaelViV** [MrAlex94/Waterfox#1435]
You guys did a great job so that addons and web extensions worked on Waterfox. The entire picture is spoiled only by these yellow warnings:
![incompatible](https://user-images.githubusercontent.com/61154304/74670742-778d5100-51b2-11ea-850d-c74c3c95a8c5.png)
Can you create some prefs to disable this?

**Comment by Ibuprophen** [comment]
The following link should be helpful for what your looking for. 

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

Good Luck! 


~Ibuprophen

**Comment by MichaelViV** [comment]
No. It's different. All my addons and web extension fully working. I just need to remove these annoying warnings without editing install.rdf and manifest.json inside them.

**Comment by Ibuprophen** [comment]
To my knowledge, there's only 2 ways to remove the warning message. 

1) By re-enabling add-ons that are disabled. 

2) Remove/Uninstall the add-ons that are reflecting the warning message. 

There may be other ways that I'm not, personally, aware of. 


~Ibuprophen

**Comment by MichaelViV** [comment]
Nope. Best way remove it`s globaly from waterfox code. I don’t understand why they didn’t do it a long time ago. Only confuses users. Because everything works fine.

**Comment by Squall-Leonhart** [comment]
Don't bother, this warning can still bring attention to extensions capable of breaking the browser.

**Comment by MichaelViV** [comment]
But optionally, you can create a pref in order to disable these annoying warnings. For experienced users of course. By default, it will be "false". To whom the warnings disturb will switch to "true".

**Comment by hawkeye116477** [comment]
I installed that extension and haven't that warning.

**Comment by MichaelViV** [comment]
Of course. Because you installed ANOTHER extension. This is my personal fork. Fully signed and with disabled update check. Do not pay attention to the extension. I just brought it as an example of a problem with annoying warnings.

If you need real-world test, then fresh install "CanvasBlocker". Then disable internet and install again only from xpi file and you see.
