### ISSUE TITLE
Spell checker underline

### ISSUE THREAD

**Issue by kroncke-w** [MrAlex94/Waterfox#1436]
**Describe the bug**

https://www.reddit.com/user/kronckew/draft/83760df2-51b4-11ea-92df-82a2e0f9340d

The spell checker underline style is a faint red wavy line, in firefox 73.0 you can set this to a more visible double straight line with an about:config integer parameter ui.SpellCheckerUnderlineStyle set to 4, and thickness of the lines can be adjusted with another integer ui.SpellCheckerRelativeSize set to 10 thru 100. The color can be changed with a string value ui.spellcheckerunderline with the hex color number, default red is #FF0000

this does not seem to work in Waterfox current 2020.02. It would be nice if you could as the default is rather hard to see on a high resoultion monitor.

**Comment by NebelNidas** [comment]
That's because Waterfox Current is currently still based on Firefox ESR editions, hopefully this will change now with the help of the additional System1 developers.
