### ISSUE TITLE
Waterfox crashes on multiple pages using Java Applet in Classic 2020.02

### ISSUE THREAD

**Issue by hurumori** [MrAlex94/Waterfox#1444]
Waterfox crashes on multiple pages using Java Applet in Classic 2020.02.

ex. https: //www.w3.org/People/mimasa/test/object/java/clock
ex. https: //oekakiart.net/oeb10/
(After selecting ShiPainter (other than neo) in the drop down box, press the blue button on the right)

**Comment by MrAlex94** [comment]
Which OS?

**Comment by hurumori** [comment]
Mr Alex, thank you for reading.
My environment is Windows7 64bit + Java Update 241.

**Comment by hawkeye116477** [comment]
I can reproduce crash on first link on Linux. This doesn't happens on Firefox 56, so it's rather specific to Waterfox Classic and that was broken on this version.

**Comment by hurumori** [comment]
Browser crash has been resolved with the Classic 2020.02.1.
Thanks for fixing!
