### ISSUE TITLE
Can't see the videos (anymore) on a site...

### ISSUE THREAD

**Issue by PiliJ** [MrAlex94/Waterfox#1451]
Hello, 
I can't see all the videos on https://www.vkmag.com/ with Waterfox Classic since version 2020.02, only images like this : 

![Image 001](https://user-images.githubusercontent.com/33757855/75062104-6dd15980-54e2-11ea-856c-f14b6069fb6f.jpg)

These are clearly visible in Firefox (with the same settings) or IE.
A restart in safe mode give this result :

![Image 002](https://user-images.githubusercontent.com/33757855/75062118-775ac180-54e2-11ea-92ff-a90675c0d628.jpg)

However, cookies are accepted and have always been.
Thank you !

**Comment by hawkeye116477** [comment]
Try update to 2020.02.1.

**Comment by PiliJ** [comment]
It was already update.
![Image 003](https://user-images.githubusercontent.com/33757855/75094051-aecf7980-5587-11ea-8ec6-6a391f90f3f0.jpg)
The problem occured first with version 2020.02.

**Comment by hawkeye116477** [comment]
@PiliJ Can you give some direct link to that not visible videos?

**Comment by PiliJ** [comment]
Here are some links captured via Firefox...
https://dailybuzz.nl/media/2020/2/21/9a019160-54b5-11ea-b951-10ddb1b30d21/pis-dog_web_wm.mp4
https://dailybuzz.nl/media/2020/2/21/e1a4dc00-54a6-11ea-8b58-10ddb1b30d21/de-zucht-boor_web_wm.mp4

**Comment by hawkeye116477** [comment]
@PiliJ That videos are playing fine. I assume they didn't work when they are embedded on site, right? So can you give direct link to that site with embedded videos?

**Comment by Squall-Leonhart** [comment]
are those using h264 profile 5.2?

**Comment by hawkeye116477** [comment]
I see the problem on `https://www.vkmag.com/magazine/hoe_niet_een_belgische_vw_showroom_te_betreden`, but in my case that problem causes uBlock Origin, it blocks something, so video isn't visible.

**Comment by PiliJ** [comment]
I don't have uBlock Origin, only Privacy Badger, but even the latter deactivated, the result is the same.
Without having made the slightest change in the browser, I no longer see these videos when before I had no problem.
@ Squall-Leonhart 
I have no idea !

**Comment by PiliJ** [comment]
Problem seems to be solved now and its origin was likely due to the site itself.
Thank you to all !
