### ISSUE TITLE
Waterfox with hardware acceleration or media foundation option on will makes some pages playing H5 videos crashing everytime.

### ISSUE THREAD

**Issue by nomosaic** [MrAlex94/Waterfox#1454]
Win7 SP1 x64, the latest x64 Waterfox Classic 2020.02.1, AMD R7 250 Graphics card with Radeon Software Adrenalin 2020 Edition 20.1.3 driver

I disabled all my Add-ons, JSs, and plugins, restarted and it crash again and again.
Starting the browse‘s safe mode can finally help the pages playing videos well, or disable HA, or set media founation parameter "media.wmf.enabled" to fasle.[Maybe (or not) a prompt about an unsupported Minetype will display.]

e.g.
https://www.realme.com/in/realme-x2
https://www.sonystyle.com.cn/products/xperia/10plus/10plus_silver.html
![Waterfox crashing](https://user-images.githubusercontent.com/14254798/75088526-6c0ea100-5589-11ea-9416-0746df7e7aa1.jpg)

**about:support**
![waterfox about：support - Graphics](https://user-images.githubusercontent.com/14254798/75088744-5f3f7c80-558c-11ea-89ed-887e7d089817.jpg)

![waterfox about：support - Important Modified Preferences](https://user-images.githubusercontent.com/14254798/75088773-b0e80700-558c-11ea-9de7-977ffcf9f984.jpg)

**Comment by Squall-Leonhart** [comment]
your video driver is the problem.

**Comment by nomosaic** [comment]
> 
> 
> your video driver is the problem.

Emm… AMD
But the last driver v19.5.2 where I updated from was crashing too.
These days I also found if Youtube new UI (https://www.youtube.com/new) was enabled the Waterfox had a certain possiblity of crash.

**Comment by hawkeye116477** [comment]
I also have same driver, but RX 570 and doesn't have problems mentioned in https://github.com/MrAlex94/Waterfox/issues/1454#issue-569300033.

In case of YouTube's new UI to stop crashing it, you'll need to set `dom.webcomponents.customelements.enabled` to true and user-agent as Firefox 63, but keep in mind that may break some other sites, cuz most code was implemented for Custom Elements, but not all.

**Comment by Squall-Leonhart** [comment]
> I also have same driver, but RX 570 and doesn't have problems mentioned in #1454 (comment).

AMD Habitually breaks older graphics card video accelleration capabilities as their drivers progress.

**Comment by hawkeye116477** [comment]
@nomosaic There is no R7 7750, maybe you mean HD 7750 or R7 250.

**Comment by nomosaic** [comment]
> 
> 
> There is no R7 7750, maybe you mean HD 7750 or R7 250.

Yes you are right, I mean R7 250.
