### ISSUE TITLE
(Classic) OpenWrt router webgui (Luci) displayed with errors.

### ISSUE THREAD

**Issue by MichaelViV** [MrAlex94/Waterfox#1455]
**Describe the bug**
Yesterday I noticed that some tabs in webgui openwrt (Luci) displayed with errors at the bottom of the page.

**To Reproduce**
1. Open Luci (192.168.X.X)
2. Sign in
3. Go to "Status" - "Realtime Graphs"
4. See error at the bottom of the page.

**Expected behavior**

It should not be there.

**Screenshots**
![screen](https://user-images.githubusercontent.com/61154304/75092705-1d5e0880-5583-11ea-8e9a-aba310f4f534.jpg)

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: Classic 2020.02.1

**Additional context**

I think the some old code is to blame. Firefox 73 not have this bug.

**Comment by hawkeye116477** [comment]
What error messages are on console (right click and inspect element => console)?

I installed OpenWRT 19.07 on VMWare and seems all is fine.

**Comment by MichaelViV** [comment]
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively. (unknown)
TypeError: data[(data.length - 1)] is undefined

**Comment by MichaelViV** [comment]
I did some more research. This bug causes an extension "Font Fingerprint Defender". So invalid. My bad.
