### ISSUE TITLE
Hard locked browser.safebrowsing.phishing.enabled perference?

### ISSUE THREAD

**Issue by gh-ix** [MrAlex94/Waterfox#1469]
Hello,
I'm switching from Firefox to Waterfox current for enterprise packaging a cusomized browser (addons, bookmarks).

What I've done in Firefox (ESR) so far is to extend the user selectable phishing/malware protection via autoadmin, to influence all the rest of the safebrowsing features.
Delivered default is "disabled", which also disables safebrowsing (and replacing numerous URLs, cause I'll never have time to lokk into the code what is really happening - just to be sure).

Now Waterfox current seems to have hard locked "browser.safebrowsing.phishing.enabled".
But like in Firefox, UI _ignores_!?!?! the preference completely and user can always enable sb.phishing, which results in a user_pref setting.
I'm simply deleting any user preference of sb.phishing and sb.malware in my autoadmin in case it's waterfox.  But that does also mean that complete safebrowsing is always disabled.
I'd prefer to leave it up to the user's choice, since the rest of the safebrowsing stuff isn't as "harmful" as the phishing and there might be reasons to turn it on.

What was the reason to hard lock sb.phishing?

Thanks
-harry

**Comment by hawkeye116477** [comment]
It's not locked. From where you have Waterfox Current?

**Comment by gh-ix** [comment]
https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%20Current%202020.02%20Setup.exe
sha256: 72CDB93AF5D1722325D0CC6BC6E69B224FD312D35A8AAA424591C62BC04416F8

Will re-install without any autoadmin and double-check....

**Comment by gh-ix** [comment]
Doh, sorry. please excuse the noise.
Forgot about policies.json... nuot used to it yet.
Plain waterfox does _not_ have "browser.safebrowsing.phishing.enabled" locked!
Sorry,
-harry

P.S.: Oddity that policy leads to locked preference, but user is still possible to tick/change the setting in UI remains true...
