### ISSUE TITLE
Backport Dav1d to WF classic for more efficient AV1 playback.

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1470]
**Describe the bug**

The Dav1d decoder is much faster than the libaom decoder. So it would make sense to include it. Youtube already has several videos with AV1 streams and the user can set youtube to prefer using these streams.

**Comment by Squall-Leonhart** [comment]
I'd rather not have av1 support in classic at all.

**Comment by mzso** [comment]
[**@Squall-Leonhart**](https://github.com/Squall-Leonhart) commented on [2020. márc. 1. 21:23 CET](https://github.com/MrAlex94/Waterfox/issues/1470#issuecomment-593140797 "2020-03-01T20:23:30Z - Replied by Github Reply Comments"):
> I'd rather not have av1 support in classic at all.

And what does that gain you? You can just disable the codec if you don't want it.

**Comment by Squall-Leonhart** [comment]
> And what does that gain you?

A stable code base with no more screwing around with it than necessary to keep things working.

2020.02 has only just rectified memory leaks in various video players that existed since late 2018.

**Comment by hawkeye116477** [comment]
@mzso https://github.com/MrAlex94/Waterfox/pull/1979
