### ISSUE TITLE
ipon.hu website completely broken under Waterfox Classic

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1471]
**Describe the bug**
Blank tab is shown.

**To Reproduce**
1. Go to 'https://ipon.hu/magazin/cikk/a-koffein-sok-elete'

**Expected behavior**
Functioning website

**My configuration** 
 - Device: PC
 - OS: Windows 8.1
 - Version: Classic 2020.02

**Additional context**
Adding a bogus user agent helps somewhat, though the website will lack some content.
Additionally in my main profile the website keeps refreshing constantly. I couldn't figure out why.

**Comment by grahamperrin** [comment]
Please try `2020.02.1`

**Comment by hawkeye116477** [comment]
@grahamperrin So you haven't that problem?

**Comment by grahamperrin** [comment]
Installing now. In the meantime it seems reasonable to not continue with an outdated installation.

**Comment by mzso** [comment]
[**@grahamperrin**](https://github.com/grahamperrin) commented on [2020. márc. 1. 17:42 CET](https://github.com/MrAlex94/Waterfox/issues/1471#issuecomment-593117333 "2020-03-01T16:42:06Z - Replied by Github Reply Comments"):
> Please try `2020.02.1`

No difference.

**Comment by grahamperrin** [comment]
My virtual machine just froze, before the freeze I got the site working with a Linux-specific UA override for Firefox 60. 

Whilst I restart the VM here, please try this terse string for the site: 

`Firefox/60.0`

**Comment by hawkeye116477** [comment]
Seems that works only if you make override for all sites, doesn't work only for `ipon.hu`.

**Comment by grahamperrin** [comment]
I have this at (for example) https://ipon.hu/shop/csoport/notebook-szamitogep/notebook with the terse string for `https://ipon.hu/`: 

![image](https://user-images.githubusercontent.com/192271/75630281-37ca5e80-5be1-11ea-8480-a87fb8df6f24.png)

* Firefox on the screen to the right
* `2020.02.1` on <strike>Kubuntu </strike>Manjaro Linux.

At a glance, window content appears the same on both screens. (Please, am I missing something?)

**Comment by mzso** [comment]
[**@grahamperrin**](https://github.com/grahamperrin) commented on [2020. márc. 1. 18:09 CET](https://github.com/MrAlex94/Waterfox/issues/1471#issuecomment-593119984 "2020-03-01T17:09:11Z - Replied by Github Reply Comments"):
> My virtual machine just froze, before the freeze I got the site working with a Linux-specific UA override for Firefox 60.
> 
> Whilst I restart the VM here, please try this terse string for the site:
> 
> `Firefox/60.0`

Same result as with a random string for ipon.



[**@grahamperrin**](https://github.com/grahamperrin) commented on [2020. márc. 1. 18:24 CET](https://github.com/MrAlex94/Waterfox/issues/1471#issuecomment-593121451 "2020-03-01T17:24:26Z - Replied by Github Reply Comments"):
> 
> *   Firefox on the screen to the right
> *   `2020.02.1` on Kubuntu.
> 
> At a glance, window content appears the same on both screens. (Please, am I missing something?)

Try the URL I shared. It has a blank recommened section and missing comments:
![kép](https://user-images.githubusercontent.com/4479090/75630529-c0e69300-5beb-11ea-8ca9-fd53fbdbaa2f.png) (Actually there are two comments)

**Comment by grahamperrin** [comment]
Thanks, 

> Try the URL I shared.

– that's where I began. 

Seeing no difference there (at a glance), I clicked through to a different area of the site.

**Comment by hawkeye116477** [comment]
`I have this at (for example) https://ipon.hu/shop/csoport/notebook-szamitogep/notebook with the terse string for https://ipon.hu/:`

For me `general.useragent.override.ipon.hu` doesn't works, page looks broken, this only works if I use `general.useragent.override` .

**Comment by grahamperrin** [comment]
> (Actually there are two comments)

![image](https://user-images.githubusercontent.com/192271/75630612-41a19100-5be4-11ea-9950-8f990026f9de.png)

Please visit: 

* about:config?filter=privacy.resistFingerprinting

Is the value `false`?

**Comment by grahamperrin** [comment]
@hawkeye116477 a long shot (maybe irrelevant) … do you (also) have a CAPTCHA before the site can be visited?

**Comment by hawkeye116477** [comment]
@grahamperrin Yes, I have captcha.

**Comment by mzso** [comment]
[**@grahamperrin**](https://github.com/grahamperrin) commented on [2020. márc. 1. 18:46 CET](https://github.com/MrAlex94/Waterfox/issues/1471#issuecomment-593124176 "2020-03-01T17:46:18Z - Replied by Github Reply Comments"):
> > (Actually there are two comments)
> 
> https://user-images.githubusercontent.com/192271/75630612-41a19100-5be4-11ea-9950-8f990026f9de.png
> 
> Please visit:
> 
> *   about:config?filter=privacy.resistFingerprinting
> 
> Is the value `false`?

Yes. Should I change it to true? It seems to work on my test profile but I can hardly check with the main because the website still keeps reloading like crazy, and I can't figure out why.

(I get no captcha, maybe that's done for foreign IP-s.)

**Comment by grahamperrin** [comment]
Thanks, 

> Should I change it to true?

No, `false` is the default – is what I have here with the working views of the pages. 

----

At this point I might normally suggest testing with a new profile (with the given UA override), however it's remarkable that _neither_ of you has a working view of the site.

**Comment by mzso** [comment]
> 
> 
> Thanks,
> 
> > Should I change it to true?
> 
> No, `false` is the default – is what I have here with the working views of the pages.
> 
> At this point I might normally suggest testing with a new profile (with the given UA override), however it's remarkable that _neither_ of you has a working view of the site.

I was testing with a new profile. And setting it to true amusingly fixed the page. (Even for the main profile considering appearance. It just keeps crazily reloading, which I'm starting to suspect is a separate issue.)

**Comment by grahamperrin** [comment]
OK, maybe the site requires a different (more specific) override on Windows 8.1. 

I just installed on Windows 10 …

**Comment by grahamperrin** [comment]
`Firefox/60.0` appears to work for me with Windows 10: 

![image](https://user-images.githubusercontent.com/192271/75631817-060bc480-5bee-11ea-9d39-a88f6474c653.png)

----

I'm vaguely reminded of an issue from a few months ago, I'll do some digging …

**Comment by grahamperrin** [comment]
Towards an explanation for the _sense_ of randomness (inconsistent test results) …

### Networking

IPv4 here at home. 

Do either of you have IPv6 enabled? 

(Waterfox aside: from maybe three or four years ago I have a vague memory of an issue that involved IPv6 and a content delivery network …)

**Comment by mzso** [comment]
[**@grahamperrin**](https://github.com/grahamperrin) commented on [2020. márc. 1. 20:30 CET](https://github.com/MrAlex94/Waterfox/issues/1471#issuecomment-593135424 "2020-03-01T19:30:16Z - Replied by Github Reply Comments"):
> Towards an explanation for the _sense_ of randomness (inconsistent test results) …
> 
> ### Networking
> 
> IPv4 here at home.
> 
> Do either of you have IPv6 enabled?
> 
> (Waterfox aside: from maybe three or four years ago I have a vague memory of an issue that involved IPv6 and a content delivery network …)

I don't know. I don't think so. I don't think my ONT even supports ipv6

**Comment by hawkeye116477** [comment]
I have IPv4.

`Firefox/60.0 appears to work for me with Windows 10:`
Seems that you used some extension, in case of browser's built-in settings, override for specific site doesn't works (https://github.com/MrAlex94/Waterfox/issues/1471#issuecomment-593124163).

Update: Now I get message that website owner banned me based on browser's signature....
