### ISSUE TITLE
Youtube video seems to crash Waterfox content process

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1473]
**Describe the bug**
Crashes with specific quality option.

**To Reproduce**

1. Go to 'https://www.youtube.com/watch?v=Fb1HIhepydU'
2. start playback
3. select the 1080p stream. 
4. content process crashes.

**Expected behavior**

**Screenshots**

**My configuration** 
 - Device: pc
 - OS: win 8.1
 - Version: Classic 2020.02.1

**Comment by grahamperrin** [comment]
Not reproducible on Windows 10.

**Comment by Squall-Leonhart** [comment]
just you.

Windows 7
![image](https://user-images.githubusercontent.com/1098176/75635768-bcae8a00-5c6c-11ea-825e-59f30b075110.png)

Windows 8
![image](https://user-images.githubusercontent.com/1098176/75635957-91c53580-5c6e-11ea-92ed-71f75a15d181.png)

**Comment by mzso** [comment]
It seems like several similar videos crash Waterfox.
https://www.youtube.com/watch?v=VVTiYpAelME
https://www.youtube.com/watch?v=e9TNkCQ7yQA
https://www.youtube.com/watch?v=nh-pelxVUxo
https://www.youtube.com/watch?v=IUieXmKp1Ic
https://www.youtube.com/watch?v=JI2NpcBdgss
And with a vanilla profile as well. 
[Clipboarder.2020.03.02.txt](https://github.com/MrAlex94/Waterfox/files/4276372/Clipboarder.2020.03.02.txt)

**Comment by Squall-Leonhart** [comment]
what codec are they  trying to load?

Sure it isn't your video driver?

**Comment by MrAlex94** [comment]
Does this happen in Safe Mode as well? If it doesn't, could be a driver issue.

**Comment by Squall-Leonhart** [comment]
something im noticing is that although my system is fast enough for vp9 decoding, all of these are avc1 instead.

i get vp9 in other videos though

Windows 10 is the only OS that has MFE vp9 support
7 and 8 can accelerate avc1/h264

i can play both ok with acceleration.

**Comment by mzso** [comment]
> something im noticing is that although my system is fast enough for vp9 decoding, all of these are avc1 instead.
> 
> i get vp9 in other videos though
> 
> Windows 10 is the only OS that has MFE vp9 support
> 7 and 8 can accelerate avc1/h264
> 
> i can play both ok with acceleration.

Probably they're not popular enough to even have VP9 streams. I can't tell the codec of course, because the crashing.

**Comment by mzso** [comment]
> Does this happen in Safe Mode as well? If it doesn't, could be a driver issue.

I'll check when I can, bit I don't think a cause outsideWF is likely. The driver didn't change for a long time.

**Comment by Squall-Leonhart** [comment]
> I'll check when I can, bit I don't think a cause outsideWF is likely. The driver didn't change for a long time.

The browser has changed though,  quite a bit of video playback stuff has changed in 20.2.x which is likely why im not getting leaks in mp4upload, youtube or similar html5 players anymore, but in changing that it can trip over bugs in the driver, or even have removed a workaround for that particular device.

**Comment by mzso** [comment]
> > I'll check when I can, bit I don't think a cause outsideWF is likely. The driver didn't change for a long time.
> 
> The browser has changed though, quite a bit of video playback stuff has changed in 20.2.x which is likely why im not getting leaks in mp4upload, youtube or similar html5 players anymore, but in changing that it can trip over bugs in the driver, or even have removed a workaround for that particular device.

Well, with Waterfox lacking a crash reporter, I'm not sure what else I could add.

**Comment by reallyuniquename** [comment]
You should download and post the exact video stream that crashes Waterfox for you.

**Comment by mzso** [comment]
[**@reallyuniquename**](https://github.com/reallyuniquename) commented on [2020. márc. 3. 16:39 CET](https://github.com/MrAlex94/Waterfox/issues/1473#issuecomment-594014849 "2020-03-03T15:39:01Z - Replied by Github Reply Comments"):
> You should download and post the exact video stream that crashes Waterfox for you.

How should I know? It crashes so I can't say anything for sure.
I'd say it's most likely the 1920*1200 stream.

**Comment by mzso** [comment]
[**@reallyuniquename**](https://github.com/reallyuniquename) commented on [2020. márc. 3. 16:39 CET](https://github.com/MrAlex94/Waterfox/issues/1473#issuecomment-594014849 "2020-03-03T15:39:01Z - Replied by Github Reply Comments"):
> You should download and post the exact video stream that crashes Waterfox for you.

Not that anyone interested couldn't download the Full HD streams, but here it is:
https://drive.google.com/open?id=1GN7_T805Cd1SFm57ja8mHEHLAU3pg78B

**Comment by mzso** [comment]
[**@reallyuniquename**](https://github.com/reallyuniquename) commented on [2020. márc. 3. 16:39 CET](https://github.com/MrAlex94/Waterfox/issues/1473#issuecomment-594014849 "2020-03-03T15:39:01Z - Replied by Github Reply Comments"):
> You should download and post the exact video stream that crashes Waterfox for you.

Not that anyone interested couldn't download the Full HD streams, but here it is:
https://drive.google.com/open?id=1GN7_T805Cd1SFm57ja8mHEHLAU3pg78B

It also crashes WF, on its own.

**Comment by Squall-Leonhart** [comment]
avc1.42001E, it doesn't crash for me :(

**Comment by reallyuniquename** [comment]
Works fine for me too, it's just H.264. 

@mzso 
Does it crash Waterfox if you open it directly from your local file system? Have you tried basic things like disabling hardware acceleration and updating video drivers?
>Not that anyone interested couldn't download the Full HD streams

Depending on your location, cookies and YouTube itself you might get different streams.

**Comment by mzso** [comment]
> Works fine for me too, it's just H.264.
> 
> @mzso
> Does it crash Waterfox if you open it directly from your local file system?

Yes, I mentioned it above.

>Have you tried basic things like disabling hardware acceleration and updating video drivers?
> 

Not yet. I wouldn't call it basic. It's trying stuff blindly without information.

> > Not that anyone interested couldn't download the Full HD streams
> 
> Depending on your location, cookies and YouTube itself you might get different streams.


The streams are finite and not numerous. Anyway, I myself had to use youtube-dl to find and download the stream.

**Comment by reallyuniquename** [comment]
>It's trying stuff blindly without information.

No, it's the most basic thing to do when you get playback issues.

>The streams are finite and not numerous

Yeah and we are not going to try every one of them. And there is no guarantee we would get the same files from YouTube CDN.

**Comment by Squall-Leonhart** [comment]
h264ify will force any youtube video to stream via h264, if all of them crash then this issue is specific to this computer.

**Comment by mzso** [comment]
[**@Squall-Leonhart**](https://github.com/Squall-Leonhart) commented on [2020. márc. 4. 20:18 CET](https://github.com/MrAlex94/Waterfox/issues/1473#issuecomment-594768421 "2020-03-04T19:18:29Z - Replied by Github Reply Comments"):
> h264ify will force any youtube video to stream via h264, if all of them crash then this issue is specific to this computer.

All of them definitely don't crash WF, only 1920*1200 streams appear to do so.

**Comment by mzso** [comment]
[**@Squall-Leonhart**](https://github.com/Squall-Leonhart) commented on [2020. márc. 4. 20:18 CET](https://github.com/MrAlex94/Waterfox/issues/1473#issuecomment-594768421 "2020-03-04T19:18:29Z - Replied by Github Reply Comments"):
> h264ify will force any youtube video to stream via h264, if all of them crash then this issue is specific to this computer.

All of them definitely don't crash WF, only 1920*1200 streams appear to do so.
[**@reallyuniquename**](https://github.com/reallyuniquename) commented on [2020. márc. 4. 08:19 CET](https://github.com/MrAlex94/Waterfox/issues/1473#issuecomment-594365167 "2020-03-04T07:19:34Z - Replied by Github Reply Comments"):
> Works fine for me too, it's just H.264.
> 
> [@mzso](https://github.com/mzso)  
> Does it crash Waterfox if you open it directly from your local file system? Have you tried basic things like disabling hardware acceleration and updating video drivers?

Setting layers.acceleration.disabled to true does seem to alleviate the problem.

**Comment by reallyuniquename** [comment]
>Setting layers.acceleration.disabled to true does seem to alleviate the problem

As in no more crashes?

**Comment by mzso** [comment]
> > Setting layers.acceleration.disabled to true does seem to alleviate the problem
> 
> As in no more crashes?

With the ones I tried with.

**Comment by reallyuniquename** [comment]
Who could have thought that _trying stuff blindly without information_ would do the trick.

You should check if latest Firefox can handle these videos on your machine.

**Comment by mzso** [comment]
> Who could have thought that _trying stuff blindly without information_ would do the trick.
> 
> You should check if latest Firefox can handle these videos on your machine.

It didn't. Because I don't intend to disable HW acceleration. By this logic not using the browser also solves the issue.

**Comment by reallyuniquename** [comment]
I never said anything about _solving_ the issue. You need to pinpoint what's causing it first. 

Check the Firefox and report back.

> I don't intend to disable HW acceleration. By this logic not using the browser also solves the issue.

No, by that logic you would be able to normally use Waterfox for a small price of your CPU time. Otherwise you are going to keep crashing, at least for now. Suite yourself.

**Comment by mzso** [comment]
[**@reallyuniquename**](https://github.com/reallyuniquename) commented on [2020. márc. 5. 15:58 CET](https://github.com/MrAlex94/Waterfox/issues/1473#issuecomment-595272607 "2020-03-05T14:58:31Z - Replied by Github Reply Comments"):
> I never said anything about _solving_ the issue. You need to pinpoint what's causing it first.
> 
> Check the Firefox and report back.
> 

Firefox is fine in this regard, it always was. Even Firefox 56 works fine.
Waterfox however invariably crashes. Tried versions all the way back to 56.2.7.1.

> > I don't intend to disable HW acceleration. By this logic not using the browser also solves the issue.
> 
> No, by that logic you would be able to normally use Waterfox for a small price of your CPU time. Otherwise you are going to keep crashing, at least for now. Suite yourself.

No, not normally.

**Comment by reallyuniquename** [comment]
There is no point in trying version 56 and lower. You need to test latest Firefox.

>No, not normally.

How's that?

**Comment by mzso** [comment]
It looks like I have been using the latest driver after all.
Because Nvidia stopped updating it in 2018...

**Comment by Squall-Leonhart** [comment]
391.35?

**Comment by mzso** [comment]
[**@Squall-Leonhart**](https://github.com/Squall-Leonhart) commented on [2020. márc. 14. 17:10 CET](https://github.com/MrAlex94/Waterfox/issues/1473#issuecomment-599087818 "2020-03-14T16:10:26Z - Replied by Github Reply Comments"):
> 391.35?

Yes.

**Comment by SylwesterZarebski** [comment]
Newest Waterfox Classic 2021.02 tab crashes on 360' video:
https://www.youtube.com/watch?v=I-Y14gm8C6o

**Comment by decembre** [comment]
I confirm:
For me too, Newest Waterfox Classic 2021.02 tab crashes on 360' video

**Comment by Squall-Leonhart** [comment]
Install enhanced h264ify, Set media.windows-media-foundation.allow-d3d11-dxva:false and reset media.hardware-video-decoding.failed

Though the issue mzso had is unrelated to the 360 degree video issue, which already has an existing issue #1588

**Comment by decembre** [comment]
Thanks for the workaround!

Some related question:
What i need to check to the options to just solve this problem (to not lost functionality or resolution on YouTube):
Actually "<a href="https://addons.mozilla.org/en-US/firefox/addon/enhanced-h264ify/">enhanced-h264ify by Alex</a>" as these options checked:

Block 60fps video
Block h264
X Block VP8
X Block VP9
X Block AV1
Disable Loudness Normalization

The about:config tweaks work fine for this problem and YouTube / Nivida.
But what can be the effect for others sites than Youtube ?

**Comment by Squall-Leonhart** [comment]
i don't know of any other sites that use vp9 apart from youtube, most of the net is still using the widely supported h264 codec.

**Comment by SylwesterZarebski** [comment]
Vimeo could still have many videos using VP9.

**Comment by decembre** [comment]
In an other hand, if the problem occur only with Waterfox Classic, it is possible to fix it without installing addon and about:config tweaks ?

Ps: 
<s>Can't edit this post with Waterfox Classic...</s>
Solved with:
<a href="https://github.com/JustOff/github-wc-polyfill/releases">github-wc-polyfill</a>
:-)

**Comment by decembre** [comment]
tab crashes on 360' video:
Seems solved with the last Update of Waterfox Classic!
Not need to use any tweaks.
;-)
