### ISSUE TITLE
Page Fails To Load On Classic In Safe Mode

### ISSUE THREAD

**Issue by pjpreilly** [MrAlex94/Waterfox#1481]
This **[PAGE](https://www.wunderground.com/forecast/us/pa/cheltenham/KPACHELT4)** fails to load in safe mode on linux Classic 20.2.1. I continously get the "A web page is slowing down your browser.....". When not in safe mode the page loads with Ublock Origin but then consumes the CPU while the page is fully loaded & idle. Seems to be javascript issues since disabling scripts alleviates the load issue but the page does not render near correctly. Should be easily reproducible.

**Comment by grahamperrin** [comment]
### Weather Underground

> PAGE 

https://www.wunderground.com/forecast/us/pa/cheltenham/KPACHELT4

The page loads in normal mode here. 

Note that for some types of page, safe mode can _cause_ the slowness that you describe. 

Related discussions: 

* https://old.reddit.com/r/waterfox/comments/f2fvqj/how_can_i_pinpoint_precisely_whats_slowing/fhgs125/
* 
https://old.reddit.com/r/waterfox/comments/f2fvqj/how_can_i_pinpoint_precisely_whats_slowing/fhw5nzu/
* https://old.reddit.com/r/waterfox/comments/f3dw3c/waterfox_202002_release_security_issues_fixed_and/fhieg6z/

**Comment by grahamperrin** [comment]
Try the page in a new profile, in a private window with basic tracking protection and [Malwarebytes Browser Guard](https://addons.mozilla.org/addon/malwarebytes/) alone enabled. Load times here vary between seven and twelve seconds, YMMV depending on hardware etc.

**Comment by pjpreilly** [comment]
It looks like tons of ads that are maybe geographically dependent which overload the javascript engine. Probably with embedded video/audio too. Ublock origin seems to work better than nanoblock but that's just shooting from the hip. I also use Privacy Badger. I give MWB a test...

**Comment by pjpreilly** [comment]
FWIW current Firefox as well as Chromium have less an issue on the different hardware I've run WFC on. There does seem to be some extra javascript overhead on the browser.

**Comment by pjpreilly** [comment]
**[Malwarebytes](https://addons.mozilla.org/en-US/firefox/addon/malwarebytes/)** and/or **[Privacy Badger](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/)**? Discuss.

**Comment by grahamperrin** [comment]
> Malwarebytes and/or Privacy Badger? Discuss.

▶ to https://www.reddit.com/r/waterfox/ please. GitHub is not a discussion forum. 

----

Above, the suggestion to test with Malwarebytes Browser Guard was primarily for you to share a comparative test result. 

Thanks

**Comment by pjpreilly** [comment]
> GitHub is not a discussion forum.

Advise then ....

**Comment by grahamperrin** [comment]
I mean, please raise the question in Reddit.

**Comment by pjpreilly** [comment]
> Above, the suggestion to test with Malwarebytes Browser Guard was primarily for you to share a comparative test result.

Seems to be better but why would Privacy Badger NOT seem to have the same benefits IYHO?

**Comment by grahamperrin** [comment]
I don't know; I don't use Privacy Badger. 

If the page successfully loads in a test environment, is it reasonable to assume that extensions (in your production environment) are contributory to – maybe the primary cause of – the issue? 

Always hard to guess without troubleshooting information.

**Comment by NebelNidas** [comment]
It's even worse with the German dictionary site Duden.de. As soon as you visit a subpage (like this one: [https://www.duden.de/rechtschreibung/Test](https://www.duden.de/rechtschreibung/Test)), it completely freezes all other tabs, not allowing them to render any further than what was on your screen already when you opened Duden. Here it's not even related to ads, it's just bad programming in the underlying page I think. Even after closing the tab, WFC won't recover, you have to click in the "Stop website" button in the yellow warning box.

**Comment by pjpreilly** [comment]
https://www.duden.de/rechtschreibung/Test
"You sunk my battleship!"
... spinning wheel of death for me on Lion.
also fails to load on os x Mojave as well as on Manjaro Linux.

**Comment by pjpreilly** [comment]
@NebelNidas On what OS have you tested?

**Comment by NebelNidas** [comment]
Windows 10 1909 Build 18363.752 x64

**Comment by pjpreilly** [comment]
Sounds like a javascript processing bug able to be reproduced on all OS platforms. Seems as though high priority should be given to its rectification.
