### ISSUE TITLE
Gah. Your tab just crashed. 2020.02.1 Classic

### ISSUE THREAD

**Issue by Keyzmo** [MrAlex94/Waterfox#1486]
**Describe the bug**
The page keeps crashing for me even with clean install and empty profile. No addons, the only plugins are Flash 32 and OpenH264 1.8.1.1.
Doesn't happen on every page load though, maybe every other refresh.
In safe mode the page loads ok-ish (at least doesn't crash).

**To Reproduce**
1. Go to https://petrolspy.com.au/map/latlng/-33.8657305/151.20733
2. Refresh a few times if it doesn't crash on first load

**My configuration**
 - OS: Win7 x64
 - Version: 2020.02.1 Classic portable

**Comment by strotee** [comment]
FWIW, I use Classic 2020.02.1 (64-bit) on 10 LTSC (17763.1075) and refreshed at least 10 times with zero crashes. I have a few add-ons too.

**Comment by grahamperrin** [comment]
Not reproducible on Windows 10 (1909) in a VirtualBox guest. 

First: if hardware acceleration is enabled, try disabling. 

about:preferences#general

▶ Performance

**Comment by Keyzmo** [comment]
With acceleration disabled behavior is a bit different: it now takes a few refreshes (~5) to get a crash  and a crash also always shows a popup like this
![image](https://user-images.githubusercontent.com/35167899/76395663-f5b4d000-63cb-11ea-8825-4603307f21a2.png)

**Comment by Keyzmo** [comment]
Tried in a Win7 VMWare VM and was unable to reproduce.
So looks like the issue is specific to my system.
Closing.

**Comment by grahamperrin** [comment]
Thanks.

It's sometimes found that a supposedly up-to-date driver, for graphics hardware, is outdated. I suggest checking the web site for the graphics hardware. 

More exotically: if your use of Microsoft Update is in a managed environment that limits things to an organisation-specific WSUS, maybe ask your systems administrator whether a one-off check can be performed against Microsoft's software update service. Sometimes a generic driver (from Microsoft's service) will be better than what's recommended by the hardware vendor.
