### ISSUE TITLE
Some wrong comparisons for tag-based changelogs at /tags

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1488]
https://github.com/MrAlex94/Waterfox/tags

At a glance, this one appears to be OK: 

![image](https://user-images.githubusercontent.com/192271/76493940-bf0ea200-642b-11ea-82b3-18bf2e006368.png)

This does not: 

![image](https://user-images.githubusercontent.com/192271/76494317-7a373b00-642c-11ea-8831-99b56a408dfd.png)

- `⋯-classic` need not (should not) be compared with `⋯-current`
- `⋯-current` need not (should not) be compared with `⋯-classic`

For the two most recent pairs of tags, the links offered at https://www.reddit.com/r/waterfox/comments/fhb17u/waterfox_202003_is_now_available_autoupdate/fka74hv/?context=1 should be OK. 

It might make sense to address #1383 before this issue.

**Comment by MrAlex94** [comment]
Nothing I can do in regards to that change log button, it's auto-generate by GitHub.

**Comment by grahamperrin** [comment]
Peculiar! Thanks for looking.
