### ISSUE TITLE
Classic202003, new logo and about:logo

### ISSUE THREAD

**Issue by dapgo** [MrAlex94/Waterfox#1489]
It is  cosmetic and really minor issue.
about:logo is still displaying the previous logo whereas in help:about Waterfox is showing the new one.

**To Reproduce**

1. Go to 'about:logo'
4. See the image

**Expected behavior**
the new Classic logo

 - Version: Classic 2020.0310

**Comment by Squall-Leonhart** [comment]
why would it show 2020.0310?

**Comment by dapgo** [comment]
It was a mistake, the version was mean to appear as:

**My configuration** 
OS: Windows
Version: Classic 2020.0310

**Comment by MrAlex94** [comment]
That's okay, the CLASSIC tag is just to differentiate between desktop icons :-)
