### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by psonnosp** [MrAlex94/Waterfox#1490]
**Describe the bug**

None of the product images show on [this site](https://www.kronansapotek.se/Djur/Hund/c/hund) but they work perfectly well in Chrome. So is the site using some non standard html or is it Waterfox that's messing things up? Tried to disable all add-ons but no change.

**To Reproduce**

That the images shows in Waterfox as they do in Chrome.

**Screenshots**

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: 2020.02-01 Classic

**Additional context**
Had to use Chrome to be able to post this so maybe it's a sign to abandon the classic version and move on to current and say good bye to my add-ons.

**Comment by hawkeye116477** [comment]
`So is the site using some non standard html`

It's rather problem with Javascript. I'll see later what I can find with mozregression.

Update:
Mozregression results:
Last bad: 2019-01-27
First good: 2019-01-28
Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=06e3993985b77e62c9b6ee1f9dba87da407eb6d1&tochange=d305772af471766618393c01065556e739738e84

Solution probably is in `https://bugzilla.mozilla.org/show_bug.cgi?id=1522491`, so dynamic importing modules must be implemented to fix that problem.

**Comment by psonnosp** [comment]
That's all like Greek to me but l guess you figured it out? ;)
The site is in no way vital to me and if this is an unusual thing, since the links are over a year old and no one pointed it out until now, you can forget about the whole thing and use your time on something of real value.
Thanks for the response!

**Comment by phylophyl** [comment]
Same problem of (some) images not showing on a shopify [website](https://drapeau-noir.fr/collections/pulls-mailles). It works well in Chromium and Firefox ESR.


    Device: Laptop Thinkpad P14s Amd Gen2
    OS: Debian Sid - Gnome Wayland
    Version: G5.1 (64-bit) KDE edition
