### ISSUE TITLE
Waterfox classic 2020.03 incompatible with NoScript classic

### ISSUE THREAD

**Issue by KritonK** [MrAlex94/Waterfox#1491]
**Describe the bug**
With Waterfox classic 2020.03, tabs crash on certain sites, such as Wikipedia, if the classic version of NoScript is installed.

**To Reproduce**
1. Start Waterfox classic with a new profile.
2. Install the classic version of NoScript from https://secure.informaction.com/download/releases/noscript-5.1.9.xpi
3. Visit https://en.wikipedia.org/
4. The current tab crashes

**Expected behavior**
The visited page should open without a crash.

**My configuration**
 - Device: Desktop PC, x86_64
 - OS: Linux (OpenSUSE Tumbleweed)
 - Version: Classic 2020.03

**Comment by MrAlex94** [comment]
Hmm, I can reproduce. Did this happen with older versions of Waterfox as well?

**Comment by KritonK** [comment]
No. In fact I reverted to 2020.02.1 because of this problem.

**Comment by MrAlex94** [comment]
Damn okay, will do a `git bisect` and try and see what's caused the issues.

**Comment by hawkeye116477** [comment]
Apparently that was caused by https://github.com/MrAlex94/Waterfox/pull/1476. There were a lot of related things and seems that I skipped one fix for crash and I'm not using NoScript (uBO is better, it only blocks what is bad), so I didn't experienced crash. Anyway, sorry for problems and I send a fix.

**Comment by MrAlex94** [comment]
> Apparently that was caused by https://github.com/MrAlex94/Waterfox/pull/1476. There were a lot of related things and seems that I skipped one fix for crash and I'm not using NoScript (uBO is better, it only blocks what is bad), so I didn't experienced crash. Anyway, sorry for problems and I send a fix.

Thanks for the fix!
