### ISSUE TITLE
Red banner on icon appears to be a Notification badge on macOS

### ISSUE THREAD

**Issue by ElhemEnohpi** [MrAlex94/Waterfox#1493]
On macOS, applications can signal that they need attention by sending notifications, including alerts, or badges on the application's icon in the Dock.

The new Waterfox Classic icon has a red badge saying "classic" that is difficult to distinguish from a Notifications badge. It is especially so if there are many icons in the dock and they have a small size. This interferes with the normal operation of the user interface by giving a false signal that the application requires attention, causing distraction to the user.

Could you please use a different method than a red badge to distinguish the Waterfox Classic icon? Thanks.

**Screenshots**

![Screen Shot](https://user-images.githubusercontent.com/23618559/76569856-68997600-64b4-11ea-963f-99f41e09f1ad.png)
Thunderbird showing a Notifications badge needing attention; Waterfox also appears to need attention.

Note: on the Mac, an application's icon can be replaced by copy/paste in the "Get Info" box. This could be a work-around, except that with Waterfox/Firefox, whenever you download a file the custom icon gets removed due to the download progress animation until you restart the application.

**My configuration** 
 - Device: MacBook
 - OS: macOS 10.14
 - Version: Classic 2020.03

**Comment by hawkeye116477** [comment]
Maybe old icons were better, blue for Classic, white for Current, was easier to distinguish.

**Comment by grahamperrin** [comment]
FWIW: [Colours of branding/icons/logos for Waterfox Classic and Waterfox Current](https://new.reddit.com/r/waterfox/comments/fihtdz/colours_of_brandingiconslogos_for_waterfox/) – an invitation to discuss … hopefully not ad nauseam `;-)`

**Comment by maxoku** [comment]
In taskbar in Windows, on tab and on titlebar it has the same effect. It constantly takes my attention and make me think there's a notification or something wrong with Waterfox. Very annoying, my eyes are uncomfortable.

**Comment by jabcreations** [comment]
Please get rid of the "Classic" red bar on the icon altogether. If anything stick it on the newer/less capable builds of Waterfox so people know extensions (and therefore the browser) won't work. I seriously thought I was having some sort of video or Explorer corruption at the end of my day. I really like the latest icon for Waterfox in general and it works well with Notepad++, Advanced Find and Replace, Hoo WinTail, HeidiSQL and FileZilla icons. Just get rid of that red bar please. It feels like we're being "warned" like when nubs say, "O-M-G don't disable the page file!" Thank you in advance.

**Comment by RaviOnline** [comment]
Yes, please remove the badge, it looks very odd among other taskbar icons. IMHO, just a different color scheme would look more professional. I'm a Windows user, BTW.

**Comment by grahamperrin** [comment]
With respect, 

> … If anything stick it on the newer …

– please, let's not. As the icon for Waterfox Classic should be free from visual annoyance, so the icon for Waterfox Current should be pleasing. 

I should encourage use of https://redd.it/fihtdz for discussion

**Comment by nuenuewei** [comment]
Something red hovering over an icon is paradigmatic for a pending notification on every platform. It's not particular to apple.

**Comment by grahamperrin** [comment]
> … every platform. …

https://www.reddit.com/r/waterfox/comments/fihtdz/colours_of_brandingiconslogos_for_waterfox/fklpaa1/

**Comment by nuenuewei** [comment]
I said every platform, not every program on every platform.

**Comment by GJRobert** [comment]
I suggest it's better to use colors as flavors.

There **WAS** such a addon called [Firefox-on-OS-X Label](http://web.archive.org/web/20181121092927/https://addons.mozilla.org/en-US/firefox/addon/fosx-label/) which is really really useful (though discontinued on MAO it's still usable in Waterfox Classic and is still available in various places or I can also send you an .xpi). I prefer to leave the Notification Badge of macOS to such addons, and we can use different colors for Waterfox flavors with cross-platform unity and formality.

**Comment by grahamperrin** [comment]
@GJRobert thanks, and (for browser compatibility) here's an earlier capture of the page, from before the redesign of AMO: https://web.archive.org/web/20171101022334/https://addons.mozilla.org/en-US/firefox/addon/fosx-label/

**Comment by MrAlex94** [comment]
> I suggest it's better to use colors as flavors.
> 
> 
> 
> There **WAS** such a addon called [Firefox-on-OS-X Label](http://web.archive.org/web/20181121092927/https://addons.mozilla.org/en-US/firefox/addon/fosx-label/) which is really really useful (though discontinued on MAO it's still usable in Waterfox Classic and is still available in various places or I can also send you an .xpi). I prefer to leave the Notification Badge of macOS to such addons, and we can use different colors for Waterfox flavors with cross-platform unity and formality.

Thanks for that link! This is actually a good idea - will investigate if it can be done cross-platform, and only have the badge show up if both browsers are installed.

**Comment by hawkeye116477** [comment]
`only have the badge show up if both browsers are installed`

Maybe slightly better will be than currently is. Anyway wouldn't even be better to change color of icon, just like Pale Moon did for unstable version?

**Comment by maxoku** [comment]
@MrAlex94 
Don't use red color, it's bad for eyes. And if you can make it show up in certain situations like both versions installed than you can make it also optional to be turned off. I have Current installed too, but only for testing and I never would mistake one for another even if they'd have the same icon.

**Comment by hawkeye116477** [comment]
I think that changing color of icon like Pale Moon did for unstable would be even better.

**Comment by MrAlex94** [comment]
True, but Current isn't unstable anymore.

**Comment by jabcreations** [comment]
> maxoku
> Don't use red color, it's bad for eyes.

No, blue has shorter wave-lengths, it is _scientifically_ worse for people's eyes.

Just use the more Firefox-like older Waterfox icon for the Waterfox Current for blatantly obvious reasons. Gets rid of badges and anyone who actually uses both will be able to easily tell which is which.

**Comment by ElhemEnohpi** [comment]
<s>I've found a better work-around for the current issue in macOS, which overcomes the problem of the custom icon being lost after downloading a file:

1. In the Finder, select the Waterfox Classic application and choose Make Alias from the File menu.
2. Select the alias and Choose Get Info from the File menu.
3. Select an older version of Waterfox and Choose Get Info from the File menu.
4. In the "Get Info" windows, select, copy, and paste the icon to the alias.
5. Remove the Waterfox application from the Dock, and drag the alias there instead.

There is a small black arrow indicating that it's an alias, but it's much better than the distracting red badge.</s> [Edit: I spoke too soon, it doesn't actually work. When downloading, it changes the icon in the dock to show the progress bar even for the alias, and doesn't change it back. Nevermind. I'm back to restarting Waterfox after every download.]

See also [this StackExchange question](https://apple.stackexchange.com/questions/344278/how-can-i-disable-the-red-software-update-notification-bubble-on-the-system-pref), and [this blog](https://robservatory.com/remove-the-macos-catalina-guilt-trip-from-macos-mojave/), for examples of how annoying a permanent red badge is to users, and the lengths that people will go to in order to get rid of it.

[**@MrAlex94**](https://github.com/MrAlex94) commented on [Mar 24, 2020, 4:17 PM GMT+1](https://github.com/MrAlex94/Waterfox/issues/1493#issuecomment-603299886 "2020-03-24T15:17:41Z - Replied by Github Reply Comments"):
> [**@GJRobert**](https://github.com/GJRobert) commented:
> > I suggest it's better to use colors as flavors.
> > 
> > There **WAS** such a addon called [Firefox-on-OS-X Label](http://web.archive.org/web/20181121092927/https://addons.mozilla.org/en-US/firefox/addon/fosx-label/) which is really really useful (though discontinued on MAO it's still usable in Waterfox Classic and is still available in various places or I can also send you an .xpi). I prefer to leave the Notification Badge of macOS to such addons, and we can use different colors for Waterfox flavors with cross-platform unity and formality.
> 
> Thanks for that link! This is actually a good idea - will investigate if it can be done cross-platform, and only have the badge show up if both browsers are installed.

Please don't do that. It's a misuse of the OS's notifications system. Badges are to inform the user of a transitory state that requires their attention. Please find some method other than a red badge to differentiate the versions.

It really is distracting, because people have been conditioned to respond to it as an alert, through years of use. Literally everyone who has commented has said that a red badge is not a good idea. GJRobert's comment was *not* suggesting a badge, but using different coloured icons, and leaving badges up to any users who like the idea, through an addon.

**Comment by jabcreations** [comment]
@ElhemEnohpi I have searched for a way to customize shortcuts on Mac OS X though never found the directory. Could you please post a link to whatever tutorial you've used to create the alias? I would like to be able to create custom shortcuts to launch Waterfox/Firefox with specific profiles. Also that was a fantastic post, thank you for sharing.

**Comment by ElhemEnohpi** [comment]
@jabcreations , I updated the instructions to be more specific. It's not possible to customize an alias as you describe. You need some sort of scripting, like an Applescript application with "do shell script". That's out of the scope of this issue, try looking on Reddit, Stack Exhange, etc.

PS, I don't believe it's possible for Waterfox to use the more Firefox-like older Waterfox icon due to trademark issues.

**Comment by grahamperrin** [comment]
> I don't believe it's possible for Waterfox to use the more Firefox-like older Waterfox icon

True, to the best of my knowledge. From the opening post at <https://redd.it/fihtdz>: 

>> … understand that it can not be reused. Need to accept this and move on. 

– there's further discussion.

**Comment by grahamperrin** [comment]
> … only have the badge show up if …

Whilst I like the theory of conditionally altering icons, I strongly suspect that **real-life** reactions to variation will be less pleasing. Here I draw upon my (limited) experience with AppleSeed, before the flood gates were opened by Apple :-)

**Comment by MrAlex94** [comment]
> Please don't do that. It's a misuse of the OS's notifications system. Badges are to inform the user of a transitory state that requires their attention. Please find some method other than a red badge to differentiate the versions.

I should have clarified - I meant it is a good idea to differentiate the icons only if both are installed,  not necessarily having a notification icon.

**Comment by grahamperrin** [comment]
Incidentally: 

* no archived version of any Waterfox logo at https://github.com/alrra/browser-logos/tree/master/src/archive
* files at https://github.com/alrra/browser-logos/tree/8b2a49d6a8f4feb60f323c0d4f1de9b7d67c5801/waterfox are from 2015

– eventually, it'll be neat to have logos for Waterfox Classic and Waterfox Current at https://github.com/alrra/browser-logos/blob/master/src/README.md#readme

### Context

Extensions such as [Open With](https://addons.mozilla.org/addon/open-with/) –

![image](https://user-images.githubusercontent.com/192271/77856402-c1744880-71ee-11ea-9ad9-385d45ddc213.png)
