### ISSUE TITLE
[BUG] Waterfox Classic: Github partially not working anymore

### ISSUE THREAD

**Issue by LeeBinder** [MrAlex94/Waterfox#1494]
Not working anymore: PREVIEW, EDIT, HIDE; short code like : and @

WF classic in macOS Mojave 10.14.6

I suddenly encountered this new bug with WF classic 2020.02-1, but it remains with latest WF classic 2020.03. It also occurs in safe mode with all extensions disabled. It does NOT occur in the latest Firefox. I don't use WF current so can't test in there.

After making sure via about:config that no user agent override is active for github.com, I tried first Firefox then several other user agent overrides to no avail, so this is not a user agent issue.

Since many of us are using github, I'm positive this bug is reproducible and fixable, hopefully w/o too much effort.

Thanks again for this wonderful browser

**Comment by MrAlex94** [comment]
Please see discussion here: https://github.com/MrAlex94/Waterfox/issues/1360

:-)

**Comment by LeeBinder** [comment]
wow yes, dom.webcomponents.customelements.enabled -> true did it. Thank you Alex!

**Comment by LeeBinder** [comment]
@MrAlex94 , why is dom.webcomponents.customelements.enabled not set to true by default in Waterfox, considering how many Waterfoxers use github? Is there a significant downside of having it set to true?

**Comment by grahamperrin** [comment]
> why is dom.webcomponents.customelements.enabled not set to true by default

Maybe https://github.com/MrAlex94/Waterfox/issues/1360#issuecomment-598611172

**Comment by LeeBinder** [comment]
no, I can't replicate any of the issues described by @hawkeye116477 here, neither in Windows nor macOS with the latest WF Classic 2020.03.1 - no issues at all in YouTube with `dom.webcomponents.customelements.enabled` set to `true` despite of `dom.webcomponents.enabled` left default = `false`
