### ISSUE TITLE
NHL.com wont display in Waterfox.

### ISSUE THREAD

**Issue by psonnosp** [MrAlex94/Waterfox#1496]
**Describe the bug**

NHL.com is just a complete mess, simple as that.

**To Reproduce**

1. Go to https://www.nhl.com/ using Waterfox
2. Go to https://www.nhl.com/ using Chrome.
3. Notice the difference.

**Expected behavior**
That Waterfox shows the page the same way Chrome does.

**My configuration** 
 - Device: PC
 - OS: Windows 10/
 - Version: Classic 2020.03.01

**Additional context**
Second page in two days that forces me to use another browser. What's going on?

**Comment by grahamperrin** [comment]
From [NHL.com is broken is latest Waterfox](https://old.reddit.com/r/waterfox/comments/e2449i/nhlcom_is_broken_is_latest_waterfox/) (2019-11-26)

> … on the checklist.

Meta, tracking: #538

**Comment by psonnosp** [comment]
OK?

**Comment by grahamperrin** [comment]
> OK?

Yes, thanks 👍
