### ISSUE TITLE
Error accessing https://www.icloud.com

### ISSUE THREAD

**Issue by Klaus1946** [MrAlex94/Waterfox#1499]
**Describe the bug**

Trying to open https://www.icloud.com leads to a partial buildup of that site, eventually resulting in an unspecific Error message "Verbindungsfehler".

**To Reproduce**
Verbindungsfehler. Beim Versuch, eine Verbindung zum Server aufzubauen, ist Icloud auf einen Fehler gestoßen.

**Expected behavior**

To get to the login page 

**Screenshots**

**My configuration** 
 - Device: 
 - OS: 
 - Version: 

**Additional context**

**Comment by MrAlex94** [comment]
I can load and use various iCloud.com features without issue with Classic 2020.03.1 on macOS.

As a test, could you enable `dom.webcomponents.customelements.enabled` and see if it makes a difference?

**Comment by colvacdir** [comment]
I was having the same issue with Classic 2020.03.1 and setting these preferences to 0 fixed it.

`network.http.referer.XOriginTrimmingPolicy`
`network.http.referer.XOriginPolicy`

**Comment by hawkeye116477** [comment]
@colvacdir These prefs are set to `0` by default.

**Comment by Klaus1946** [comment]
Sorry, I had some problems with the original form. 
My device is a PC, 
OS is Windows 10 1909

I have enabled dom.webcomponents.customelements.enabled and restarted Waterfox. No change in behaviour on the Icloud login page.

network.http.referer.XOriginTrimmingPolicy
network.http.referer.XOriginPolicy

are both set to 0, I havent't changed the default.

Customer support at Apple mumbled something vague about certificate problems. ???

Any other ideas?

Best regards, 
Klaus

**Comment by MrAlex94** [comment]
Would it be possible to get a screenshot of the error? Curious as to why it won't work on your PC.

**Comment by Klaus1946** [comment]
Screenshot attached:

![2](https://user-images.githubusercontent.com/62249468/77061714-fe646200-69da-11ea-9821-ad3f6a6ee40f.PNG)

**Comment by Klaus1946** [comment]
... and, btw, Waterfox was in safe mode, with no addons running.

**Comment by grahamperrin** [comment]
I can't run a virtual machine (to compare) at the time of writing … @Klaus1946 have you enabled fingerprint resistance?

about:config?filter=fingerprint

**Comment by Klaus1946** [comment]
Yes, and now I have disabled it, restarted, no change. 

Thanks to all for the effort to help me.

**Comment by LeeBinder** [comment]
Login fine here with latest WF classic Mac, also in Germany. Might be a Windows issue? @Klaus1946 , can you boot a Linux live distro, install Waterfox and try with that?

**Comment by Klaus1946** [comment]
Changing _resist.fingerprinting_ to false did the trick. Somehow I missed the message from grahamperrin or made some error. So many thanks, belatedly.

And thanks to all the others who tried to help.

**Comment by LeeBinder** [comment]
Very good. But I don't have that entry in about:config. Do you mean `privacy.resistFingerprinting`? That's what I have (and it is set to false to begin with).
