### ISSUE TITLE
Classic Linux: "WhatsApp Works with Firefox 52+"

### ISSUE THREAD

**Issue by tcreek** [MrAlex94/Waterfox#1500]
**Describe the bug**

WhatsApp web reporting version of Browser is not supported

**To Reproduce**
 
Visit https://web.whatsapp.com/

![Screenshot from 2020-03-16 16-57-48](https://user-images.githubusercontent.com/4149717/76803378-ad205c80-67a7-11ea-886e-b23a77dc0ddd.png)

**Expected behavior**
Open the chat window via Web

**My configuration** 
 - Device: 
 - OS:  Linux
 - Version:  Classic 2020.03.01

**Additional context**
 Windows client does not have this issue

**Comment by grahamperrin** [comment]
If I recall correctly, a user agent override is integral to Waterfox Classic. 

Is fingerprint resistance enabled?

**Comment by NebelNidas** [comment]
Yeah, I also get this error sometimes (despite WF having the override). No fingerprinting setting changed. You have to delete the "offline website data" from the "clear recent history" dialogue, then it works again!

**Comment by tcreek** [comment]
I got a little busy and forgot to reply.  I cleared the cache and now it is functioning again. 

This is very odd.

**Comment by tcreek** [comment]
For others:

While on the error page:

press key combination LEFT CTRL + F5 and the page will reload with you logged in.
