### ISSUE TITLE
[Classic] SyntaxError on IBM Carbon Desing System website

### ISSUE THREAD

**Issue by notpushkin** [MrAlex94/Waterfox#1501]
**Describe the bug**
```
SyntaxError: missing ( before catch
in app-ab5079a3a23c59cd6ed6.js:1:2894791
```
(I'm not yet sure where to find the unminified source code, but there's a good chance it's somewhere in https://github.com/carbon-design-system/carbon)

This makes some of the components unresponsive, e. g. you can't open submenus in the sidebar.

This doesn't reporoduce in Firefox 73.0.1 nor Chromium 80.0.3987.132.

**To Reproduce**
Go to https://www.carbondesignsystem.com/ and open Developer Tools.

**Expected behavior**
The error doesn't occur, script runs normally and the page is fully functional.

**My configuration** 
 - Device: ThinkPad T420
 - OS: Ubuntu 19.10
 - Version: Classic 2020.01 (from [hawkeye116477's repo](https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage))

**Comment by hawkeye116477** [comment]
@notpushkin Can you update to latest version (2020.03.1)?

**Comment by hawkeye116477** [comment]
@notpushkin Can you update to latest version (2020.03.1)?

**Comment by notpushkin** [comment]
OMG I feel so dumb now. 2020.03.1 works as intended, thank you so much.
