### ISSUE TITLE
WARNING: pipe error: Broken pipe: file /home/akontos/Waterfox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 709 (/home/akontos doesn't exist on my pc)

### ISSUE THREAD

**Issue by jasonkhanlar** [MrAlex94/Waterfox#1503]
**Describe the bug**

Tabs crash. I've experienced crashing tabs for a year or so, maybe 50-100+ times. Previous versions of Waterfox, when one tab crashed, every tab crashed, but it seems now only one tab crashes, which is a lot better, but still annoying. In any case, this time I noticed a crash and I kept the xterm window that I used to open Waterfox from the command line, and when 1 tab crashed, I posted the console output that appeared. I was prepared for the crash and nothing appeared in console until the tab crashed, and then this was dumped: https://www.ruqqus.com/post/354 There is no path /home/akondos on my computer, so I have no idea why Waterfox would mention this. Also just now I found this from someone else too: https://www.reddit.com/r/waterfox/comments/epb3fr/strange_warnings_from_waterfox/

Note: I see Waterfox 2020.02 is available to compile/install, and I'm doing that now. It might fix this issue maybe. I'm not sure. In any case, I didn't see this reported here, so I thought I would report it anyway, even though it affects Waterfox Classic 2020.01

**To Reproduce**

1. Check Linux terminal/console output before and after a tab crashes, whenever it does. I have no idea how to reproduce a tab crash, but be prepared that when it happens, see the console output that appears

**Expected behavior**

No tab crash

**Screenshots**

**My configuration** 
 - Device: Desktop computer
 - OS: Archlinux
 - Version: Waterfox Classic 2020.01

**Additional context**

**Comment by hawkeye116477** [comment]
@jasonkhanlar Maybe try to update to 2020.03.1?

`/home/akontos doesn't exist on my pc`

It was compiled by @MrAlex94, so that's why shows `akontos`, it just shows place on code on which it stops.
