### ISSUE TITLE
Site doesn't load in Waterfox due to badly configured SSL

### ISSUE THREAD

**Issue by kazerniel** [MrAlex94/Waterfox#1504]
**Describe the bug**
I got a Connection is not Secure warning when trying to load https://gha.org.uk/ . I added the security exception, which tends to solve this problem for other sites, but in this case it doesn't. The site now doesn't spend any time loading, just immediately throws a blank page.

I disabled uBlock and any other relevant addons, with no result. Tried refreshing the page with `Ctrl+F5`, still the same.

The same site loads without issues in Brave 1.5.113.

**My configuration** 
 - Device: PC
 - OS: Win7 Pro SP1 x64
 - Version: Classic 2020.03.1 x64

**Comment by Squall-Leonhart** [comment]
The site is the issue.

**Comment by SWAN-UA** [comment]
Error is correct, certificate contains set of domains for use and there is no "gha.org.uk" among them, but if you add www... then you can close this "issue"...

**Comment by kazerniel** [comment]
> 
> 
> Error is correct, certificate contains set of domains for use and there is no "gha.org.uk" among them, but if you add [www](http://www)... then you can close this "issue"...

Thanks, it worked this way :D
