### ISSUE TITLE
Waterfox refuses to connect to https server on port 6697

### ISSUE THREAD

**Issue by bkidwell** [MrAlex94/Waterfox#1507]
**Describe the bug**

Waterfox does not allow the user to connect to an https server on port 6697. It says

> This address is restricted
> 
> This address uses a network port which is normally used for purposes other than Web browsing. Waterfox has canceled the request for your protection.

It does not offer any way to resolve the problem locally, such as changing configuration to override the port blocking rule.

**To Reproduce**

1. Any fresh Waterfox profile with no add-ons installed.
2. Navigate to my ZNC control panel at https://vicky.glump.net:6697/ .
3. Waterfox displays the error message.

**Expected behavior**

I expect that Waterfox does not block any arbitrary port numbers that an https server might be running on. If Waterfox _does_ need to block port 6697, I expect it to allow the user in control of the Waterfox profile to override this with a configuration edit. The error message should state explicitly how this can be done.

**Screenshots**

![image](https://user-images.githubusercontent.com/723919/77671767-704e2580-6f5e-11ea-9aaa-8c3a6f53cd6b.png)

**My configuration**
 - Device: PC laptop
 - OS: Windows 10 Enterprise 64-bit
 - Version: Waterfox Current 2020.03 64-bit

**Additional Context**

If I recall correctly, my ZNC is running in its default configuration, and I see nothing wrong with its setup. It is listening on TCP port 6697 for IRC+TLS connections and for HTTPS connections; it determines which protocol to use based on the client's first messages. Normally the HTTPS/HTML dashboard is seldom used after the system is setup and fully configured; the dashboard doesn't need a dedicated port.

**Comment by TPXP** [comment]
Port 6697 is [known as a port for IRC over TLS](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers). You shouldn't use it for a web server and most browsers will refuse to connect to it (including Firefox, which Waterfox is forked from, and Chrome).

If you _really_ can't change the port your web server is listening on, the procedure on how to allow connection is just [a search away](https://lmgtfy.com/?q=firefox+allow+unsafe+port&s=d). Just in case: https://support.mozilla.org/en-US/questions/1083282
It's better not to explain it on the error message since it's usually a bad idea to try to circumvent this.

**Comment by bkidwell** [comment]
Waterfox can decide what the project wants. I'm not surprised "most browsers" refuse to work on port 6697 because other systems only use it for IRC, but I still consider it a bug if you can't connect on an arbitrary port and the browser doesn't tell you how to override this policy.

**Comment by grahamperrin** [comment]
> arbitrary

It's not arbitrary. You'll find the same restriction for port 548, and so on. 

[Service Name and Transport Protocol Port Number Registry](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml)

**Comment by bkidwell** [comment]
I agree I misused "arbitrary". Let's not quibble about that.

The browser said "I know better than you -- access denied" and the error message didn't name the hidden setting that resolves the conflict.

I hope that we can 1) remove the restriction because personally I don't see the harm in letting the browser try an https connection; or 2) TELL the user in the error message that the conflict can be resolved by editing a hidden config variable; or 3) the project documents here in the ticket that '1' or '2' are inappropriate.

**Comment by Squall-Leonhart** [comment]
the browser does know better than you

/thread

**Comment by wagle** [comment]
How do you fix this firefox-like "screw the users, we know best" attitude that seemed, until now, to get us waterfox as a replacement.

To wit, I can no long access my personal wiki, which uses URL's of the form "http://localhost:5001/...".

How do I repel this latest DoS attack? What do I set?

**Comment by usdanskys** [comment]
I'm running into the same problem with port 8888 when using waterfox-classic-2021.04.1. Adding network.security.ports.banned.override in about:config does not remedy the problem; access is still denied. However, version 2021.03 (and all previous version I've used) let me connect without difficulty.

**Comment by reallyuniquename** [comment]
@usdanskys https://github.com/MrAlex94/Waterfox/issues/2061
