### ISSUE TITLE
[Classic] Backport CSD

### ISSUE THREAD

**Issue by hockeymikey** [MrAlex94/Waterfox#1508]
I recently switched to linux and the experience with classic is crappy. I'm used to the wonderful experience in Windows with the removal the title bar, but in linux (kde neon) we don't have that until current and newer firefox bases. Backporting this would be huge and can't be super difficult. I don't even care if it styles right to the theme, something would be better than nothing. I'd use current, but no xul leaves me high and dry with a crappy user experience because of it.

**Comment by hawkeye116477** [comment]
Seems that you didn't saw latest commit (https://github.com/MrAlex94/Waterfox/commit/25eeb6938c675d657b3d48b285cc4921ffe73213), it's already backported, but without drag space and left position of buttons.

**Comment by hockeymikey** [comment]
@hawkeye116477 That's amazing! Really made my day. Wonder when it will get released.
