### ISSUE TITLE
Sound looping problem

### ISSUE THREAD

**Issue by KOTOEB** [MrAlex94/Waterfox#1510]
**Describe the bug**
After stopping the video (for example on sites like YouTube or Coub) looped sound remains (like bzzzzzzzzzzzz). It looks like the last sample repeats eternally. In order for this sound to stop, you need to start something else related to the sound (another video, winamp, video player, game).

**To Reproduce**
1. Go to 'coub.com'
2. Scroll coubs
3. Between changing of played coubs listen to a buggy sound.

**Expected behavior**
if you use bass.dll maybe you missed to use Bass_STOP(); in some place.

**My configuration** 
 - Device: i5 3570k, GTX 1660TI, GA-Z77X-UD3H, 16GB RAM
 - OS: Win 7 x64

**Comment by KOTOEB** [comment]
Im sorry, now i know that this happens not only in Waterfox, but i'm waterfox more often.

**Comment by grahamperrin** [comment]
Waterfox Classic or Waterfox Current? 

Which version?

**Comment by KOTOEB** [comment]
Classic 2020.03.1 (64-bit)
