### ISSUE TITLE
On SOME Sites, images adds red channel.

### ISSUE THREAD

**Issue by Artanejp** [MrAlex94/Waterfox#1511]
**WHAT:**
When visiting some sites (i.e: http://www.enkyouhyakka.com/china/fuzoku/fuzoku.htm ),pictures makes shifting red.See attached screen shot.

**TO REPRODUCE:**
This issue is reproduced  with some other sites.
Only visit them.

**Expected behavior:**
All of pictures are not making shift RED.

**Screenshots:**
![Screenshot at 2020-03-29 15-08-21](https://user-images.githubusercontent.com/363735/77842711-89f6a380-71d0-11ea-8e3d-30c7e9994f62.png)

**MY CONFIGURATION:**
- Device: PC, Ryzen 2600.
- OS: On Debian GNU/Linux sid, AMD64. OpenGL/Vulkan are MESA's them, version 20.0.2.
- Version: Current 2020.03

**ADDITIONAL:**
- This issue was happened sometimes, but, resolved.
- Some parts of UIs are shifting RED.See same attached screenshot.These are not on firefox mostly. 

Regards,
Ohta.

**Comment by grahamperrin** [comment]
Not reproducible on Manjaro Linux in a VirtualBox guest: 

![29-03-2020 14:19](https://user-images.githubusercontent.com/192271/77850170-9676fe00-71c8-11ea-9b70-e610a34913b3.png)

In performance preferences, please try disabling hardware acceleration.

**Comment by Artanejp** [comment]
Thanks for advising.With disabling "hardware acceleration", this issue don't appeared.
So, I checked configurations via about:config, some values had changed.
To change gfx.webrender.highlight-painted-layers to false, this issue has resolved.
I didn't change this value...if memory serves .
Sorry...
Ohta.

**Comment by grahamperrin** [comment]
> … `gfx.webrender.highlight-painted-layers` …

Thank you. If you like, close the issue.
