### ISSUE TITLE
Waterfox Classic: Windows 10: microphone input: process crash or system crash

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1513]
Spun off from https://redd.it/fmt0jq

With Windows 10 in a VirtualBox guest, visit https://www.podcastinsights.com/online-mic-test/ in three browsers: 

1. Firefox `74.0`
2. Waterfox Current `2020.03`
3. Waterfox Classic `2020.03.1`

### Expected

* in Waterfox Classic, a prompt to allow use of a microphone

### Actual result

* process crash (reported in Reddit) or system crash (reproducible here). 

Screen recording: 

* [2020-03-29 15:07.zip](https://github.com/MrAlex94/Waterfox/files/4399050/2020-03-29.15.07.zip)

Two frames from the recording: 

![image](https://user-images.githubusercontent.com/192271/77851402-ef4a9480-71d0-11ea-9d04-3b68ccc587cb.png)

– a split-second later, the guest machine crashing: 

![image](https://user-images.githubusercontent.com/192271/77851423-0ab59f80-71d1-11ea-8872-6ba45136a2eb.png)

### Environment here

```text
grahamperrin@momh167-gjp4-8570p:~ % date ; uname -v
Sun 29 Mar 2020 15:13:32 BST
FreeBSD 13.0-CURRENT #51 r357746: Tue Feb 11 03:54:19 GMT 2020     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' virtualbox-ose virtualbox-ose-kmod
emulators/virtualbox-ose 5.2.34_1 FreeBSD
emulators/virtualbox-ose-kmod 5.2.34 poudriere
grahamperrin@momh167-gjp4-8570p:~ % 
```

Meta, tracking: #538

**Comment by hawkeye116477** [comment]
I can't reproduce that, but I didn't checked on latest Windows 10 build.

**Comment by grahamperrin** [comment]
Thank you, also I should prefer to check with a _physical_ machine running Windows 10. (Not easy for me to do so, given the restrictions that are associated with COVID-19). 

It's vaguely possible that the system crash behaviour occurs only in VirtualBox (5.2.34 r133883) on a FreeBSD or FreeBSD-CURRENT host, however in my experience it's extraordinarily rare for a guest machine to crash in this way. Something smells not quite right. 

**PS** I do have remote access to a physical machine running Windows 10 but there's no microphone; I'm unable to test.

**Comment by grahamperrin** [comment]
> …  physical machine running Windows 10 but there's no microphone; I'm unable to test.

Also: 

* FreeBSD bug [245641 – emulators/virtualbox-ose guest crashes whilst running some types of application with webcam or audio input on USB](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245641)

All things considered, I'll close this incident. It can be reopened if necessary.
