### ISSUE TITLE
Please make a 'Waterfox Current' portable.. I need it..

### ISSUE THREAD

**Issue by hosadokha** [MrAlex94/Waterfox#1518]
Waterfox Current would be my main browser if it was portable.. I only use portable browsers because of my life.. That the only thing I wanted to say.. 
oh, and it has to be **TRULY** portable

**Comment by grahamperrin** [comment]
Duplicate of #1270

Please close this and subscribe to the earlier issue. Thank you.

**Comment by jrappen** [comment]
duplicate of #943
