### ISSUE TITLE
Language change crashes WF when applied

### ISSUE THREAD

**Issue by kroncke-w** [MrAlex94/Waterfox#1522]
Tried making english-UK the default language thru options, moved it to the upper slot above english-US then are offered to either restart & apply to firefox or waterfox, selecting either crashes waterfox, does not restart and if I try to run WF an error window flashes on screen for a fraction of a second and wf doesn't start. had to restore profile folders from backup to get it to work again.
WF-Current, march 2020. Win 10 x64 insider fast lane  19592.1001. also unable to remove English-United States.

**Comment by hawkeye116477** [comment]
@kroncke-w Language packs from AMO aren't compatible with Waterfox Current.

**Comment by kroncke-w** [comment]
I know, but there should be a way to use the ubiquitous en-??.dic files. In any case the language 'option' settings if non-functional or even producing a non-functional state should either be disabled or removed completely. I am an American living in the UK, so occasionally like to switch to confuse the indigenous natives here. Oddly, it will let me set en-gb for spell checking. Some websites think i am using Bosnian for some reason... 

Srdačan pozdrav,
Wayne Kröncke

**Comment by atheist1917** [comment]
Can I install russian language pack instead of default english?

**Comment by hawkeye116477** [comment]
@soviet-man Depends on source, you can do that only from my repositories or directly downloading tar.xz package from https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/Arch/x86_64/, but keep in mind that if you download directly through browser, then won't be any updates.

**Comment by atheist1917** [comment]
I installed waterfox by installing [binary from AUR](https://aur.archlinux.org/packages/waterfox-current-bin).

**Comment by hawkeye116477** [comment]
@soviet-man I mean source of language package, anyway just like I said, working language package is on https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-current-i18n-ru :smile:.
