### ISSUE TITLE
Waterfox 2020.4 classic doesn't work in Ubuntu 16.04

### ISSUE THREAD

**Issue by jcea** [MrAlex94/Waterfox#1525]
Waterfox 2020.1 classic doesn't work in Ubuntu 16.04. It is the very same problem that issue #1356. This time, it requires GLIB-2.27.

Ubuntu 16.04 is maintained until april 2021. It will be alive for another year, yet.

Waterfox 2020.03.1 worked fine.

Thanks.

**Comment by broadstairs** [comment]
This also fails on openSUSE 15.1 which is a long term support release. Works fine on Tumbleweed.
