### ISSUE TITLE
Youtube is obscenely slow on Waterfox Classic

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1526]
**Describe the bug**
It wasn't this bad was it with the new layout? Enterin/leaving takes a solid 4-5 seconds. It's borderline unusable. I've been using the new layout for a while but only in the past week or two it seems this excruciating.
Other stuff is slow as well. But the fullscreen thing is by far the worse
I tryied it with current on passing it seemed lots better. It was even better with Firefox nightly and chrome dev. But current Slimjet (Chromium browser) also sucked.

**To Reproduce**

 - Device: pc
 - OS: w8.1
 - Version: Classic 2019.04 and older as well.

**Comment by goodusername123** [comment]
Could you go to about:support and press "Copy text to clipboard" and paste the results here?

**Comment by HumanG33k** [comment]
Can you install some agent switcher addon try again and tell us. 
I think it can just be google tryng to kill not chrome product again.

**Comment by mzso** [comment]
[**@goodusername123**](https://github.com/goodusername123) commented on [2020. ápr. 10. 11:11 CEST](https://github.com/MrAlex94/Waterfox/issues/1526#issuecomment-611951722 "2020-04-10T09:11:49Z - Replied by Github Reply Comments"):
> Could you go to about:support and press "Copy text to clipboard" and paste the results here?

Sure but I doubt it's of much relevance. I think youtube just sucks and newer versions of FF and Chrome just have more speed optimizations that make it less painful.
[Clipboarder.2020.04.10.txt](https://github.com/MrAlex94/Waterfox/files/4460924/Clipboarder.2020.04.10.txt)


[**@HumanG33k**](https://github.com/HumanG33k) commented on [2020. ápr. 10. 11:15 CEST](https://github.com/MrAlex94/Waterfox/issues/1526#issuecomment-611953002 "2020-04-10T09:15:27Z - Replied by Github Reply Comments"):
> Can you install some agent switcher addon try again and tell us.  
> I think it can just be google tryng to kill not chrome product again.

Well, it sucked in a chromium browser as well.

**Comment by mzso** [comment]
Closing issues without a word is a jerk move. At least copy/paste the reason you're mass closing issues.
