### ISSUE TITLE
Some settings are reset upon manual update - is this normal ?

### ISSUE THREAD

**Issue by GitCurious** [MrAlex94/Waterfox#1527]
Every time I manually update waterfox I have to go through all the settings and put them back to as I last left them.

Some, not all,  are being reset when I update.

I just wanted to ask if this is normal or whether the issue lies only with me ?

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Example of some settings that are being reset on the latest update:

automatically update search engines
new Tabs home page changed to default
provide search suggestions
show search suggestions in address bar
Content Blocking....all changed
address bar suggestions...all checked
remember browsing & download history
remember search & form history

**Comment by Squall-Leonhart** [comment]
none of these are reset by a waterfox update done in any manner.

**Comment by GitCurious** [comment]
Thankyou for the info.

I can't imagine why it's happening to me in that case !
