### ISSUE TITLE
Any plans for patch the unabillity to choose between the new Mozilla Megabar vs the old one ?

### ISSUE THREAD

**Issue by Eragonfr** [MrAlex94/Waterfox#1529]
Mozilla has ignored all requests from many users to add an option to disable the new "Megabar" design. Actually only firefox nightly is affected by this, because there is an option in others branches of firefox to disable it.

So this is a question, and a request. What's your plans about this new ugly bar ?
Are you going to add a visible(in about:preferences) option to disable it and revert back to the old design ?

**Comment by grahamperrin** [comment]
GitHub is not a discussion forum and this is not a bug. 

Please join the discussion: https://redd.it/fxvnyr

**Comment by Eragonfr** [comment]
I know it's not un bug, but apparently the default label setting for creating an issue is `bug`.

Oh ! I didn't know about this subreddit

**Comment by hawkeye116477** [comment]
`the default label setting for creating an issue is bug`

You have written `Don’t see your issue here? Open a blank issue. `.

**Comment by 89z** [comment]
It seems the crapbar is live now with new Waterfox version

can it be disabled?

**Comment by 89z** [comment]
Now that I think about it, this was the one reason I was using Waterfox. I am uninstalling and going back to regular Firefox.
