### ISSUE TITLE
Missing WebP inside Request Header

### ISSUE THREAD

**Issue by FaySmash** [MrAlex94/Waterfox#1530]
**Describe the bug**
Waterfox Classic don't sent `Accept: image/webp` inside request Headers.

**To Reproduce**
Load a website and inspect the first request Header.

**Expected behavior**
Waterfox should send a Request containing
`Accept: image/webp,*/*`

**Screenshots**
![header](https://user-images.githubusercontent.com/30392780/79042040-93323800-7bf4-11ea-8ba0-5e21ae9f7849.JPG)

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: Classic 2020.04

**Additional context**
Because `Accept: image/webp,*/*` is missing in the request Header of Images, Websites won't deliver WebP images although Waterfox supports WebP.

**Comment by hawkeye116477** [comment]
`although Waterfox supports WebP.`

Waterfox Classic doesn't support WebP images.
