### ISSUE TITLE
Can't open <https://www.ebay-kleinanzeigen.de/m-einloggen.html?targetUrl=/>

### ISSUE THREAD

**Issue by Klaus1946** [MrAlex94/Waterfox#1531]
After my unresolved report #1499 re iCloud.com i find I can't login at

<https://www.ebay-kleinanzeigen.de>

After klicking on Login Waterfox tries to open the page

<https://www.ebay-kleinanzeigen.de/m-einloggen.html?targetUrl=/>

in a never-ending loop. Waterfox Current does it okay.

**Comment by Squall-Leonhart** [comment]
thats not even a legitimate ebay page.

**Comment by Klaus1946** [comment]
Sorry, Sir, in Germany it is. It is the local ads page of ebay. Like <https://www.ebay.co.uk/local/> in the UK.

**Comment by joberreiter** [comment]
Same problem here, but unfortunately doesn't work in Waterfox Current.

**Comment by LeeBinder** [comment]
Moin Klaus. https://www.ebay-kleinanzeigen.de/m-einloggen.html?targeturl=/ working fine here in WF 2020-04 Classic. I just logged into my account.

**Comment by joberreiter** [comment]
This is my network log showing the situation (in Current 2020.04): seems a 403 on the XHR request:

![network-log](https://user-images.githubusercontent.com/13220647/79563712-996d5c00-80ad-11ea-910f-bb8df93b7430.png)

A restart with addons deactivated (about:support / restart) does not change the situation.

**Comment by joberreiter** [comment]
@Klaus1946 
I think I tracked it down: Try to set the "HTTP Referrer Header" preference onto its default: "send the referrer header on all requests"

**Comment by Klaus1946** [comment]
Thanks very much. That worked for the Ebay Kleinanzeigen site. 

Sadly not working for Icloud login site (report #1499)

**Comment by LeeBinder** [comment]
> @Klaus1946
> I think I tracked it down: Try to set the "HTTP Referrer Header" preference onto its default: "send the referrer header on all requests"

For those affected, that's in Preferences/Privacy under "Suppress HTTP Referrer Header"
