### ISSUE TITLE
new Waterfox user inquiry: how to import history data from Firefox 57 to Waterfox 2020.04?

### ISSUE THREAD

**Issue by DomD84** [MrAlex94/Waterfox#1534]
Greetings from a new Waterfox user.

How to import history data from Firefox 57 to Waterfox 2020.04?

**Comment by grahamperrin** [comment]
Instead: for discussion, please use the support area. 

[Inquiry: how to import history data from Firefox 57 to Waterfox 2020.04?](https://old.reddit.com/r/waterfox/comments/g1dkuj/inquiry_how_to_import_history_data_from_firefox/) – *RESOLVED*
