### ISSUE TITLE
Latest waterfox update forced uninstalled ublock origin (no info)

### ISSUE THREAD

**Issue by ExecutorQ3** [MrAlex94/Waterfox#1536]
**Describe the bug**
Hi

The latest waterfox update uninstalled the uBlock Origin adblocker (which for some reason works better than classic AdBlock, at least with that "target" feature). The problem is 1) the waterfox did not tell me he would get rid of it 2) all my rules (rules i created and polished during last 6 months) are mercilessly gone... 

**To Reproduce**
(really?... ok)
1. Install previous version of Waterfox, install uBlock origin.
2. Update Waterfox to latest (public) version.
3. Check addons
4. Cry over lost rules

**Expected behavior**
Well... To not auto-uninstall things just by updating the program (we have enough BS like this with win10 already)

**Screenshots**
Don't really have one (and actually cannot be made to support this)

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: Won't show more than Classic 2020.04

**Comment by grahamperrin** [comment]
Updates to Waterfox Classic do not remove extensions. 

Did you use the integral update feature? 

Or did you download a full installer?
