### ISSUE TITLE
Disable/Hide all Firefox Sync

### ISSUE THREAD

**Issue by Neustradamus** [MrAlex94/Waterfox#1539]
Can you see to disable all Firefox Sync?

Tools: "Sign Into Sync..."
Open Menu: "Sign in to Sync"
Open Menu: "Synced Tabs"
Tools: Options -> "Sync"

Context Menu:
- "Send Page to Device"
- "Send Link to Device"
- "Send Tab to Device"

Page:
- about:accounts

Thanks in advance.

**Comment by grahamperrin** [comment]
Not a bug. Firefox Sync is a widely used feature.

**Comment by Neustradamus** [comment]
Can you add option to disable it?

**Comment by Perosteck** [comment]
In newer versions of Firefox Synch can be disabled in about:config.

Set identity.fxaccounts.enabled to false
