### ISSUE TITLE
[Current] Free Download Manager extension doesn't work

### ISSUE THREAD

**Issue by maxoku** [MrAlex94/Waterfox#1543]
Free Download Manager extension stopped working in Current. It worked before in alpha and it works in Classic. I reported it to the author, but if it works in Firefox then I don't know if they'd fix it. Besides it looks like something's wrong on Waterfox Current side.
Link to add-on:
https://addons.mozilla.org/pl/firefox/addon/free-download-manager-addon/

**Comment by darkling3100** [comment]
In the FDM <Browser Integration> settings tab if you click Firefox with only Waterfox installed it says "Firefox isn't installed. Download it <here>." FDM seems to have problems recognizing Waterfox.
