### ISSUE TITLE
slideUp animation bug in Waterfox - ver. 2020.04 (64-bit)

### ISSUE THREAD

**Issue by vegman** [MrAlex94/Waterfox#1544]
I'm using a slideUp js function on my site and the content animation is as smooth as silk on all browsers except Waterfox - ver. 2020.04 (64-bit).

Please correct in your next update.

Thanks !!!

[Click here for website](http://www.boulderdrumstudio.com/)

<script type="text/javascript">
    $(document).ready(function() {
    $(document).on('click','.closebtn', function(e) {
        e.preventDefault();
        $(this).parent().slideUp(500);
    });
});
</script>

**Comment by hawkeye116477** [comment]
@vegman Waterfox Classic or Current?

**Comment by vegman** [comment]
I'm using Waterfox "Classic".

Thanks!
