### ISSUE TITLE
www.duden.de is slowing down Waterfox Classic 2020.04

### ISSUE THREAD

**Issue by johastl** [MrAlex94/Waterfox#1545]
reproduction:
1. go to www.duden.de
2. search for some word like 'test' for example
3. Results page is slow and message "A web page is slowing down your browser" is shown
   -> results in rising CPU load and memory consumption for waterfox.exe process

problem **exists** with:
- Waterfox Classic 2020.04 (clean installation / no addons)

problem does **NOT exist** with:
- Waterfox Current 2020.04 (clean installation / no addons)

tested OS:
- Windows 7 64bit (patch level 2020-04)
- Windows 10 1909 64bit (patch level 2020-04)

HW:
tested on different HW

**Comment by hawkeye116477** [comment]
Mozregression results:
Last bad: 2018-07-18
Firs good: 2018-07-19

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=5a8107262015714d2907a85abc24c847ad9b32d2&tochange=690cb3015db6645b335ac4835a50073cb6a3e23c

Now someone only need to find fix hidden in pushlog :smile:

**Comment by LeeBinder** [comment]
confirmed in WF classic 2020.04 macOS.

Verified work-around: install [NoScript "Classic" 5.1.9](https://noscript.net/getit/#classic), do NOT allow scripts for duden.de. Luckily their search works w/o JS

**Comment by NebelNidas** [comment]
Related: https://github.com/MrAlex94/Waterfox/issues/1481

**Comment by NebelNidas** [comment]
Why was this closed, @MrAlex94? The issue is still not fixed.
