### ISSUE TITLE
[CLASSIC] 2020.04 Notification to update despite running latest version

### ISSUE THREAD

**Issue by LeeBinder** [MrAlex94/Waterfox#1546]
In reference to [reddit: Notification to update after doing so manually](https://reddit.com/r/waterfox/comments/fyggz9/):

I have been experiencing the exact same thing sporadically with WF Classic 2020.04 macOS, maybe every 3rd or 4th time I start WF Classic 2020.04. I can click it away but it will reappear again after some restarts. Yes, I already downloaded a fresh copy and overwrote the app.

I open this issue here because a) not everyone uses reddit and b) I experience this in Classic (not using Current).

Thanks.

![bzxm2n1c00s41](https://user-images.githubusercontent.com/39203497/80141130-634a4380-85a9-11ea-822b-9fda2c96406e.png)

**Comment by LeeBinder** [comment]
Can someone please add the BUG label - I can't afterwards.

**Comment by MrAlex94** [comment]
Could you do me a favour? In `about:config`, change `app.update.log` to `true`. Then open up the browser console by selecting on the menu bar `Tools > Web Developer > Browser Console (⇧⌘J)`.  When it launches, where it says "Filter Output", put `AUS:SVC`. Then, select on the menu bar `Waterfox Current > About Waterfox` and copy and paste the output here.

Thanks!

**Comment by LeeBinder** [comment]
Sure, @MrAlex94 , here you go:

```
AUS:SVC UpdateManager:_loadXMLFileIntoArray: XML file does not exist
AUS:SVC Creating UpdateService
AUS:SVC Checker: checkForUpdates, force: true
AUS:SVC gCanCheckForUpdates - able to check for updates
AUS:SVC Checker:getUpdateURL - update URL: https://www.waterfox.net/update/osx64/2020.04/en-US/release/update.xml?force=1
AUS:SVC Checker:checkForUpdates - sending request to: https://www.waterfox.net/update/osx64/2020.04/en-US/release/update.xml?force=1
AUS:SVC Checker:onLoad - request completed downloading document
AUS:SVC Checker:_updates get - unexpected node name!
AUS:SVC Checker:onLoad - there was a problem checking for updates. Exception: Error: Unexpected node name, expected: updates, got: parsererror
AUS:SVC Checker:onLoad - request.status: 404
AUS:SVC getStatusTextFromCode - transfer error: Update XML file not found (404), code: 404
```

**Comment by LeeBinder** [comment]
When I manually click onto

https://www.waterfox.net/update/osx64/2020.04/en-US/release/update.xml?force=1

from above output, I get `Not Found` in the browser window.

However, when I change the URL to the 2020.03 update

https://www.waterfox.net/update/osx64/2020.03/en-US/release/update.xml?force=1

I do get an output:

<details>
  <summary>click to expand</summary> 

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<updates>
<update type="major" appVersion="56.3" buildID="20200312164639" detailsURL="https://www.waterfox.net/blog/waterfox-2020.03.1-release" displayVersion="2020.03.1" extensionVersion="56.3" platformVersion="56.3" version="56.3">
<patch type="complete" URL="https://storage-waterfox.netdna-ssl.com/releases/osx64/update/waterfox-classic-2020.03.1.en-US.osx64.complete.xz.mar" hashFunction="SHA512" hashValue="5daa31cf1bb57983a1b03b8163fde1ea9bc339fb41dd9675b01476edfbb2856141dcd79c81bf366c566386f267fa28520e45d4ba7a9711d3ce5dcafaf05c8a02" size="83494711"/>
</update>
</updates>
```
</details> 

So obviously this error is not local but server side - the `osx64/2020.04/en-US/release/update.xml` file is still missing on the server at waterfox.net/update/

**Comment by MrAlex94** [comment]
Sorry, thought I commented! Do you still get the issue? I pushed a change to the website which should’ve fixed it.

**Comment by LeeBinder** [comment]
Thank you @MrAlex94 - I do see the change you pushed: when I manually follow that link, there indeed is output now
`<?xml version="1.0"?><updates></updates>`
even though it's much less than for the 2020.03 update, but as long as it servers its purpose... 

I'll keep on observing. If you don't hear back from me = 👍 :)
