### ISSUE TITLE
https://broadcast.nvidia.com/feedback?sdk=voice white page

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox#1549]
White screen in WF Classic 2020.04

also affects
https://broadcast.nvidia.com/feedback?sdk=greenscreen

Reproduced in new profile, not addin related

**Comment by hawkeye116477** [comment]
Just set `webgl.enable-debug-renderer-info` to `true` and it will work.

@Peacock365 Broke it in https://github.com/MrAlex94/Waterfox/pull/1461

**Comment by Squall-Leonhart** [comment]
Thanks, another strike against the collective stupidity of the pro-privacy crowd.

**Comment by Squall-Leonhart** [comment]
fixed
