### ISSUE TITLE
implement globalThis in Waterfox Classic

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1551]
ECMA-262/ECMAscript 2021 introduced globalThis; WF Classic does not implement it. (It appeared in Firefox in FF65, and https://bugzilla.mozilla.org/show_bug.cgi?id=1317422 enumerates the changes made to Firefox to support it.)

**Comment by FaySmash** [comment]
@MrAlex94 spotify now stopped working because of this, any updated on this matter?

**Comment by MrAlex94** [comment]
Have added this to the checklist, will see how feasible it is to implement.

**Comment by hawkeye116477** [comment]
New reddit now requires it also.

**Comment by MrAlex94** [comment]
2020.06 is out, please re-open if still have the issue.

**Comment by izogfif** [comment]
Still got the issue in Firefox Developer Edition 56.0b12 (64-bit) on Windows 10. Confirmed by opening https://www.reddit.com in new Private window.

**Comment by hawkeye116477** [comment]
> Still got the issue in Firefox Developer Edition 56.0b12 (64-bit) on Windows 10. 

It's issues tracker for Waterfox Classic, not Firefox... Yes, it's based on that version, but also includes improvements and features from much newer versions.
