### ISSUE TITLE
(Classic) Kernel panic in OS X 10.7.5

### ISSUE THREAD

**Issue by TheTechRobo** [MrAlex94/Waterfox#1555]
**Describe the bug**

A kernel panic, randomly, when Waterfox was about to crash (because I accidentally downloaded a file even though Waterfox Classic always crashes with it)

Message: https://pastebin.com/b3RMWxU5

**To Reproduce**
Steps to reproduce:
- Cannot reproduce. But maybe it is with a certain condition? (Can't remember what tabs what OS environment etc)

**Expected behavior**

It not to crash

**My configuration** 
 - Device: MacBook Air (2010)
 - OS: OS X 10.7.5
 - Version: Waterfox Classic 2020.03

**Comment by TheTechRobo** [comment]
And I have an account on here for a friend, but Waterfox just kernel-panics randomly all the time on that account. (Sadly I didn't pastebin the error) That is the "9 panics since last report" line.

**Comment by LeeBinder** [comment]
duplicate of https://github.com/MrAlex94/Waterfox/issues/1523

Work-around: you can use [CL-Jeremy's test-build for Mac OS X 10.7+](https://github.com/CL-Jeremy/Waterfox/releases/tag/upre-2020.05-classic)

**Comment by TheTechRobo** [comment]
thanks :)
