### ISSUE TITLE
Givero search engine addition

### ISSUE THREAD

**Issue by TheTechRobo** [MrAlex94/Waterfox#1556]
The search engine I use is called "Givero". Could you maybe add it as a builtin? Thanks :)

**Comment by colorworm** [comment]
Givero is a search engine that gives money to various charities. The amount of money Givero gives to a charity is determined on the individual level by the amount of searches a user makes and that user's choice of charity. Additionally, it is approximately as private and secure as Ecosia and it supports DDG-style bangs. Having it as a built-in option would be great.
