### ISSUE TITLE
Add a "Restore previous session" option under Options / General

### ISSUE THREAD

**Issue by oglumbakgit** [MrAlex94/Waterfox#1560]
At the moment no interface exists for configuring the following options:
browser.sessionstore.restore_hidden_tabs / false
browser.sessionstore.restore_on_demand / true
browser.sessionstore.restore_pinned_tabs_on_demand / false
browser.sessionstore.restore_tabs_lazily / true

"Restore previous session" feature would be very helpful:
![Screenshot](https://user-images.githubusercontent.com/7149961/81198319-03509580-8fca-11ea-9fe8-c286d3590e1a.png)

**Comment by Squall-Leonhart** [comment]
nor should there be.

**Comment by LeeBinder** [comment]
@Squall-Leonhart : why not? Please explain.
