### ISSUE TITLE
Waterfox verisions after 2020.03.1 fail to start on OSX 10.9.5

### ISSUE THREAD

**Issue by mr-a500** [MrAlex94/Waterfox#1562]
Waterfox Classic version 2020.04 and 2020.05 fail to start. Previous versions were fine. Console says "Exited with code: 255."

The last working version was 2020.03.1. (using it now)

**Comment by LeeBinder** [comment]
duplicate of https://github.com/MrAlex94/Waterfox/issues/1523

Work-around: you can use [CL-Jeremy's test-build for Mac OS X 10.7+](https://github.com/CL-Jeremy/Waterfox/releases/tag/upre-2020.05-classic)

Also there is neither a 2020.04.1 nor a  2020.05.1. Why do you write stuff like that? Please correct in your issue text - thank you.

**Comment by mr-a500** [comment]
OK, I never saw #1523. Thanks. I'll look at it.

Why do I write 2020.04.1 and 2020.05.1? Well, because I couldn't start it so I couldn't see the version numbers. (and OSX version only shows "Waterfox Classic 56.3" for all 3!) The new naming format screwed me up and I suppose I shouldn't have added the .1.
