### ISSUE TITLE
Enter does not confirm in address bar

### ISSUE THREAD

**Issue by lyiriyah** [MrAlex94/Waterfox#1563]
**Describe the bug**

I type an address in the search bar, press Enter and nothing happens.

**To Reproduce**

1. Put an address in the search bar.
2. Press Enter.

**Expected behavior**

It came up with the website the address led to.

**My configuration** 
 - Device: Lenovo Thinkpad T430
 - OS: Manjaro 20 Lysia
 - Version: Classic 57.3

**Comment by hawkeye116477** [comment]
`Classic 57.3`

There is no such a version. Type `waterfox-classic -v` in console to know what is version.

**Comment by grahamperrin** [comment]
Maybe a duplicate of #1175

**Comment by lyiriyah** [comment]
Just needed to remove the search bar, works now.
