### ISSUE TITLE
Google search engine does not show search suggestions

### ISSUE THREAD

**Issue by azat11** [MrAlex94/Waterfox#1564]
**Describe the bug**
Google search engine does not show search suggestions (when chosen as default). DuckDuckGo shows search suggestions (for example).

**To Reproduce**
Choose Google as default search engine and start typing in the search bar.

**Expected behavior**
Search suggestions must appear. They do not.

**Screenshots**
![wfbug1](https://user-images.githubusercontent.com/20098838/81478896-d3eb9400-9228-11ea-8476-8f1d105fea2b.jpg)
![wfbug2](https://user-images.githubusercontent.com/20098838/81478897-d51cc100-9228-11ea-8ca0-e99a017d53c8.jpg)

**My configuration**
 - Device: PC
 - OS: Windows 7
 - Version: Current 2020.04

**Additional context**
I recently switched from Firefox to Waterfox, this is a relatively clean installation.
List of extensions:
AdblockPlus 3.8.4
Auto Reload Tab 0.5
Better Twitter 1.4.2
Browsec VPN 3.27.5
Clippings 6.2.1
Dark Mode 0.3.5
Privacy Badger 2020.2.19
Search by Image on Google 1.6
Tampermonkey 4.10.6112
uBlock Origin 1.26.2
Dark Theme for VK 3.1.1
Download Master 3.10.0 (disabled) [no option to remove it]

**Comment by azat11** [comment]
Restarting with add-ons disabled does not remove the issue.

**Comment by hawkeye116477** [comment]
I can confirm that.

**Comment by Squall-Leonhart** [comment]
working for me

**Comment by azat11** [comment]
Is this going to be fixed soon? How often do updates for WF Current come out?
Edit: Well, it turns out it's 2020.05 already, and the bug is still here...

**Comment by azat11** [comment]
2020.06 – still not showing search suggestions for Google.

**Comment by azat11** [comment]
I just did a clean install of WF Current, and search suggestions for Google are just not working at all. I do not know enough to understand why they just stopped working at some point after installation, and still are not working.

**Comment by Revdep** [comment]
i have this same problem. How can i fix it?
version 6.6.2, OS: archlinux
