### ISSUE TITLE
waterfox-classic fail audio on linux alsa or apulse

### ISSUE THREAD

**Issue by Milch1** [MrAlex94/Waterfox#1566]
All Waterfox-Classic version can't play audio with alsa, or apulse from flash plugin, or mp4 files.

If I start waterfox-classic with the command " apulse waterfox " show the output from terminal this error,

All Waterfox-Classic version can't play audio with alsa, or apulse from flash plugin, or mp4 files.

If I start waterfox-classic with the command " apulse waterfox " show the output from terminal this error,

[apulse] [error] do_connect_pcm: can't open playback device "default". Error code -38 (Die angeforderte Funktion ist nicht implementiert)
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.

If I start waterfox-classic without apulse the don't show any error, but the audio fail to play.

If I start waterfox-classic without apulse the don't show any error, but the audio fail to play.

thanks michi01

**Comment by Squall-Leonhart** [comment]
Probably same as issue #1446

**Comment by Milch1** [comment]
Maybe, also I use pclinuxos LxQt. Other browser works correctly, apart the firefox fmiliarys like seamonkey etc that i must start it with the command apulse <browser> the works all.

Here a terminal output without the apulse command before the ~/./waterfox name

Sandbox: seccomp sandbox violation: pid 26818, tid 26930, syscall 220, args 1048576 140202120642404 2 0 6 140201859998432.
Sandbox: seccomp sandbox violation: pid 26818, tid 26930, syscall 220, args 1081344 140202120642404 2 0 6 140201859998432.
Sandbox: seccomp sandbox violation: pid 26818, tid 26930, syscall 220, args 1114112 140202120642404 2 0 6 140201859998432.

**Comment by Milch1** [comment]
More tests, I have no pulse audio, only ALSA with Jack.

Well, unfortunately waterfox-classic can't play sound even with Jack and the corresponding ~/.asoundrc.

The newest, current waterfox ( don't mix it up with waterfox-classic or misunderstand it ) can play the audio, either with ALSA only or with ALSA and active Jack server.

Could it be that there is a problem with the ALSA api of waterfox-classic to can connect it?
