### ISSUE TITLE
Waterfox Classic-Google spreadsheets

### ISSUE THREAD

**Issue by sutex** [MrAlex94/Waterfox#1568]
Waterfox Classic 2020.04 (64-bit) Google spreadsheets not loading 
![Spreedsheets](https://user-images.githubusercontent.com/10361359/81633384-c82be780-944b-11ea-9fe3-c78dc82859f1.png)

**Comment by Squall-Leonhart** [comment]
set any flashblock/html5 block extensions to allow docs.google.com

**Comment by sutex** [comment]
Where would I find  flashblock/html5 block extensions ?
