### ISSUE TITLE
<CLASSIC> Adobe Flash crashes Waterfox 2020.04

### ISSUE THREAD

**Issue by TheTechRobo** [MrAlex94/Waterfox#1570]
**Describe the bug**
When I try to use Adobe Flash to run *The Hitchhiker's Guide to the Galaxy* on BBC, it kernel panics.

**To Reproduce**
1. Go to the game Hitchhiker's Guide to the Galaxy
2. Enable Adobe Flash
3. Kernel panic

**Expected behavior**
adobe flash to run properly

**My configuration** 
 - Device: MacBook Air (Late 2010)
 - OS: OS X Lion 10.7.5
 - Version: Classic 2020.04

**Additional context**
[Pastebin](https://pastebin.com/LWCer2KD)

**Comment by TheTechRobo** [comment]
UPDATE: It happens *anytime* I want to use Flash. not just that game.

**Comment by DraconicNEO** [comment]
I [posted on Reddit](https://www.reddit.com/r/waterfox/comments/ks2bh9/waterfox_crashes_when_trying_to_play_any_flash/), it seems no one is aware of this glaring issue.

**Comment by DraconicNEO** [comment]
Don't Close this because of the Time bomb in Adobe Flash, It can be [circumvented](https://demo.hedgedoc.org/s/ag_rLN_3L#)

**Comment by TheTechRobo** [comment]
I don't really use Waterfox anymore, so I can't provide much info.
