### ISSUE TITLE
Memory handling broken badly

### ISSUE THREAD

**Issue by EdTomchin** [MrAlex94/Waterfox#1574]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

 - Device: 
 - OS: 
 - Version: 

![image](https://user-images.githubusercontent.com/65460624/82125551-8953a580-975b-11ea-9702-86170745b3b1.png)

**Additional context**

**Comment by hawkeye116477** [comment]
@EdTomchin Fill in form, write what OS and Waterfox's version you have. Write also more information how to reproduce that, cuz the screenshot itself says little.

**Comment by Squall-Leonhart** [comment]
working as expected for single process operation.
