### ISSUE TITLE
Google Meet won't run on Waterfox

### ISSUE THREAD

**Issue by troppo19** [MrAlex94/Waterfox#1577]
Google Meet used to be Google Hangout? I would like to try it but GMail doesn't recognise that Waterfox is a clone of Firefox.

**Comment by LeeBinder** [comment]
@troppo19 man, you don't mange to post:
- your OS
- which edition of WF - Classic or Current
- which version

and really expect to get help? Duuuh.. Feel humbled that posts like yours don't get deleted right away.

Apart from that:
**WF Classic 2020.05 in macOS Mojave:**

![meet1](https://user-images.githubusercontent.com/39203497/82261284-0a2ebf00-995f-11ea-9b8f-941ea8323057.jpg)

![meet2](https://user-images.githubusercontent.com/39203497/82261312-1450bd80-995f-11ea-8e8d-80bfbc1341c8.jpg)

Now do better and submit all required data for your own sake - thanks mate.

**Comment by troppo19** [comment]
Oops. Humbled. Win 10 1909 build 18363.836, Waterfox Classic 2020.05
User-agent overrides are a bit cryptic for me (I go back to PLAN1900 on an ICL mainframe) but User-Agent Switcher addin solved the problem.  Many thanks.

**Comment by hawkeye116477** [comment]
It was fixed in https://github.com/MrAlex94/Waterfox/pull/1573, so will be in next version.

**Comment by LeeBinder** [comment]
All great news. @troppo19 , you can now edit your issue title into

**[SOLVED] Google Meet won't run on Waterfox**

and/ or close the issue. Thank you.
