### ISSUE TITLE
Google Drive Doc, Sheets not working at all with user agent spoofing

### ISSUE THREAD

**Issue by Yoposoc** [MrAlex94/Waterfox#1578]
**Describe the bug**

https://old.reddit.com/r/waterfox/comments/gh76pa/cannot_copy_any_text_from_google_docs/
As described here, if I use user agent spoofing in order to remove a incompatibility notice from Google, I become unable to type or edit anything, or copy anything, from Google doc and sheet files. 
Perhaps I need to use a different User Agent?

**To Reproduce**
1. User Custom UserAgent Strong extension to spoof to latest chrome version (at time of this writing, it is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`).
2. Open any google doc or sheet file.
3. Attempt writing or copying. 

**Expected behavior**

I should be able to type and copy.

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: Classic 2020.05 (64-bit)

**Comment by Yoposoc** [comment]
I've found out that even without the agent spoofing, I cannot copy/paste.
One strange but consistent way I have found out how to get around this is to use the "Explore" or "Define" feature on a text that I want to copy. It loads that text into the Explore/Define side panel that opens. I can copy the text in the search box there properly. This is clearly suboptimal... but it works for now.

Commenting, in either case, works fine.

**Comment by hawkeye116477** [comment]
`I've found out that even without the agent spoofing, I cannot copy/paste.`

I can't reproduce that.

**Comment by Yoposoc** [comment]
Someone on reddit said the same thing. I really have no idea what's happening. I've turn off all extensions, ublock origin is off, Noscript is not blocking anything. I can only think it's possibly another add-on. I'll try one at a time to disable them and see if I get any results.

**Comment by Yoposoc** [comment]
Someone on reddit said the same thing. I really have no idea what's happening. I've turn off all extensions, ublock origin is off, Noscript is not blocking anything. I can only think it's possibly another add-on. Is it possible one of these may be causing this?

https://z.zz.ht/7Lfqv.jpg
https://z.zz.ht/pSpa5.jpg

**Comment by Yoposoc** [comment]
Wow, this was the problem for me: https://support.mozilla.org/en-US/questions/1196485
After following advice here to change this config setting, I can now copy/paste with ctrl+c,v properly **when I am not spoofing the user agent**. When spoofing, I still have the issues as described. I guess for now I'll have to deal with the dialog that tells me I'm using an outdated browser.

**Comment by hawkeye116477** [comment]
@Yoposoc I guess that spoofing causes that webcomponents are needed for proper working. Currently webcomponents are disabled in Waterfox Classic, cuz they are only partially implemented.

`After following advice here to change this config setting, I can now copy/paste with ctrl+c,v properly when I am not spoofing the user agent. `

That setting is enabled by default, so I guess that you probably changed it sometime accidentally.

**Comment by Yoposoc** [comment]
>I guess that spoofing causes that webcomponents are needed for proper working. Currently webcomponents are disabled in Waterfox Classic, cuz they are only partially implemented.

So does that mean that Google drive "files" spoofed with a custom user agent will never work with Waterfox Classic? That's a huge bummer. I feel like Google docs is used pretty ubiquitously, and that having "support" for it in Classic is not a strange request.

>That setting is enabled by default, so I guess that you probably changed it sometime accidentally.

Not sure when I did this, but yes I guess I must have.
