### ISSUE TITLE
Waterfox classic has issue with www.homedepot.com

### ISSUE THREAD

**Issue by Double00user** [MrAlex94/Waterfox#1579]
**Describe the bug**
Waterfox classic will not open images in homedepot.com at all some kind bug preventing it.

**To Reproduce**
Go to 'www.homedepot.com.'
Click on 'any item that has pictures, for example gas grill'
 'when clicking on the pictures it should open picture with on the side multiple
pictures that can be clicked on but classic will not open it, which is an issue'

**Expected behavior**
when clicking on the pictures it should open picture with on the side multiple
pictures that can be clicked on. 

**Screenshots**
![image](https://user-images.githubusercontent.com/65638794/82398915-f009e500-9a21-11ea-82ed-ff3beddcdb83.png)

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: Waterfox Classic 2020.05 Setup

**Comment by LeeBinder** [comment]
> Access Denied
You don't have permission to access "http://www.homedepot.com/" on this server.
Reference #18.c82bf648.1590010129.3864d9 

same in FIrefox and Google Chrome. I guess their server has an issue right now.

**Comment by hawkeye116477** [comment]
Same problem as https://github.com/MrAlex94/Waterfox/issues/1252#issuecomment-549055230

**Comment by hawkeye116477** [comment]
Looks like that webmasters fixed site.

**Comment by LeeBinder** [comment]
can they fix other websites, too, so they work with WF Classic, please .. 🤣
