### ISSUE TITLE
Updates not working - Classic 2020.03.1 says it's up to date but it's not

### ISSUE THREAD

**Issue by ElhemEnohpi** [MrAlex94/Waterfox#1580]
**Describe the bug**

Classic 2020.03.1 [edit: also affects 2020-04 through 2020-06] has not automatically updated itself to the latest 2020.05, and is now months out of date. The "about Waterfox" window says "Waterfox is up to date".

**To Reproduce**
1. Go to 'About Waterfox'
![screenshot_350](https://user-images.githubusercontent.com/23618559/82560081-06728680-9b71-11ea-99e1-bc551d4c007e.png)

**Expected behavior**
It should update to and/or show availability of the latest version, 2020.05

**My configuration** 
 - Device: Mac
 - OS: macOS Mojave 10.14.6
 - Version: 2020.03.1

**Comment by Squall-Leonhart** [comment]
theres also been issues since that month where the update.mar fails to update the installation on the next start leading to waterfox not loading at all.

**Comment by ElhemEnohpi** [comment]
I manually updated to 2020.05. I just saw that 2020.06 came out more than a week ago, but it's still saying it's "up to date". This is worrisome, there are going to be a lot of people with outdated and potentially insecure installations of Waterfox.

**Comment by ElhemEnohpi** [comment]
Seems that it's still not working, 2020.06 says "up to date", but 2020.07 was released almost a week ago.

**Comment by MrAlex94** [comment]
This has been fixed. 2020.07.2 is now available, auto-updates being pushed out tomorrow :-)
