### ISSUE TITLE
Classic 2020.05 on Win10 - New Facebook - Shortcuts Edit Button Crash

### ISSUE THREAD

**Issue by Yay295** [MrAlex94/Waterfox#1581]
Facebook has a new interface. In the frame on the left are your Shortcuts, and when you hover over the title an Edit button appears. Clicking this button causes Waterfox to crash. Before crashing one error message appeared in the console: "Content Security Policy: Ignoring 'x-frame-options' because of 'frame-ancestors' directive."

**Comment by Squall-Leonhart** [comment]
the new interface is garbage.
