### ISSUE TITLE
Worker undefined/waterfox hangs

### ISSUE THREAD

**Issue by DrIT2016** [MrAlex94/Waterfox#1586]
I have now issues with hanging Waterfox classic. Noticed it when opening youtube video in new window. Then it will play shortly, then stop and then Waterfox completely hangs (and crashes on closing). Also sometimes a lot of new blank windows are opened, etc.
Did manage to analyze it back to extension "Enhancer for YouTube" and then probably the css style option in it. I am using this for many years, it wasn't a problem in the past. Also it does work fine in latest Firefox.
I suspect this because when importing that style sheet (https://gitlab.com/RaitaroH/YouTube-DeepDark) directly in Stylish it gives error about "Worker undefined". And when forcing to import it, also slow browser and crashes, etc (easily tested by enable/disable stylesheet).

**Comment by Squall-Leonhart** [comment]
enhancer for youtube is unsafe and introduces extreme memory leaks that persist across sessions.

**Comment by DrIT2016** [comment]
Already testing some userscripts to accomplish the same. But that doesn't solve the issue of Waterfox. F.e. yesterday i had to insert new css style sheet in stylish when i discovered when you do something in manage interface of stylish exactly same issues occurs (hangs, more than 200 about"blank tabs, etc.).
