### ISSUE TITLE
[Classic] 2020.05 changelog is missing details about security fixes

### ISSUE THREAD

**Issue by reallyuniquename** [MrAlex94/Waterfox#1587]
Waterfox Classic 2020.05 [changelog](https://www.waterfox.net/blog/waterfox-2020.05-release/) says `Latest security advisories patched (best effort)*` but there is no footnote explaining what the issue was or what is meant by `best effort`.

Can you provide any details?

**Comment by reallyuniquename** [comment]
Classic 2020.06 [changelog](https://www.waterfox.net/blog/waterfox-2020.06-release/), same thing.

@MrAlex94 
Could you give us a comment on this matter? Does it mean security fixes are no longer ported to the full extent from upstream?

**Comment by MrAlex94** [comment]
Sorry, I used an asterisk and so it got added as a bullet point, fixed so it's now using †. It says:

> As the differences between Classic and later Firefox versions grow, we are doing our best to patch the security advisories as we think apply to Classic.

**Comment by reallyuniquename** [comment]
@MrAlex94 
How critical is this? Does Waterfox Classic remain vulnerable to some of the recent CVEs if enough effort is applied?

**Comment by MrAlex94** [comment]
Not that I’ve seen. A lot of vulnerabilities target features that Waterfox doesn’t even support at all. And I’ve kept the biggest attack surfaces (such as Skia and ANGLE up to date and patched). This was more a precautionary measure. Will have to do a big review once ESR68 is EOL.

**Comment by reallyuniquename** [comment]
@MrAlex94
I know you probably would not want to disclose too much details here but can you elaborate?

Is there something with low severity that remains unnpatched then? Or recent fixes can't cover some edge cases?

**Comment by MrAlex94** [comment]
So far, everything that I’ve seen that could be possibly related to Waterfox Classic, I will apply. Of course I’m not perfect, so I just put it there as a disclaimer. I do also check other forks (such as TenFourFox) to see what patches they use as well, to make sure I’m on the right track and haven’t missed anything. (Just a note TFF is for PowerPC Macintosh so not all patches apply for them either.)

I’m sure a lot of the security patches will be applicable for time to come, but it’s more preparing for a time where that _may_ not be possible. But looking at some forks they’ve been keeping up to date with security advisories for years. 

Hope that helps clarify things a bit :-)
