### ISSUE TITLE
Classic: Youtube 360 videos cause an instant tab crash.

### ISSUE THREAD

**Issue by JohnEdwa** [MrAlex94/Waterfox#1588]
**Describe the bug**
Opening a 360 degree Youtube video causes the browser tab to crash.

**To Reproduce**
Open any one of these links: 
https://www.youtube.com/watch?v=-xNN-bJQ4vI
https://www.youtube.com/watch?v=pCve1w1GFOs
https://www.youtube.com/watch?v=QKm-SOOMC4c
And the result is a "Gah. Your tab just crashed"

**Expected behavior**
For the tab not to crash. Duh.

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: Classic 2020-05

**Additional context**
Tested with a clean profile, same thing happens. Works fine on Current.

**Comment by Squall-Leonhart** [comment]
No repro.

WF Classic, Win7 - with multiprocess enabled and disabled

**Comment by Squall-Leonhart** [comment]
Crash is due to no support for NPOT NV12 in the D3D11 DXVA support

**Comment by MrAlex94** [comment]
I've tried to repro this, but after upgrading ANGLE can't seem to.

**Comment by hawkeye116477** [comment]
@MrAlex94 I updated and can reproduce crashes after playing advert.

[support_info.txt](https://github.com/MrAlex94/Waterfox/files/5989348/support_info.txt)

**Comment by Squall-Leonhart** [comment]
its specific to windows 10 with nvidia hardware and requires a VP9 capable device, last i checked AMD doesn't have nv12 support at all and their hardware vp9 is spotty.

**Comment by Squall-Leonhart** [comment]
Please reopen this, based on comments https://github.com/MrAlex94/Waterfox/issues/1473#issuecomment-787504414 and https://github.com/MrAlex94/Waterfox/issues/1473#issuecomment-787489100

Disabling media.windows-media-foundation.allow-d3d11-dxva + h264ify is still a workaround.

**Comment by SylwesterZarebski** [comment]
Thanks, workaround works.

**Comment by decembre** [comment]
Thanks for the Update about tab crashes on 360' video!
Work fine now without any tweaks...
