### ISSUE TITLE
Homepage off layout in mobile view

### ISSUE THREAD

**Issue by Huge** [MrAlex94/Waterfox#1590]
**Describe the bug**

Mobile view of the waterfox website has the menu showing wrong.

**To Reproduce**

Load in Chrome on Android and see
![Screenshot_20200530_081157_com android chrome](https://user-images.githubusercontent.com/111648/83321084-95586080-a24d-11ea-85ff-52e518d7cdee.jpg)

**Comment by MrAlex94** [comment]
Am aware, will be fixed soon. Thanks for the report.
