### ISSUE TITLE
html file created with google web designer works in firefox and chromium but not within waterfox

### ISSUE THREAD

**Issue by warichnict** [MrAlex94/Waterfox#1591]
hi,

i wanted to test out google web designer and was wondering why my animation wasnt working anymore after exporting it. Then i found out that it only was not working in my default browser waterfox for some reason. With firefox (barly old and latest version) and chrome it worked without problems. Can you tell me why and may fix that? im appending the html-file here.

thanks a lot in advance and keep up the good work.

tested on up do date waterfox 2020.05 (64-bit) and waterfox classic on linux. both did not work.

[test.zip](https://github.com/MrAlex94/Waterfox/files/4705172/test.zip)

**Comment by hawkeye116477** [comment]
It's because webcomponents are required to display this. You can enable them on about:config, but currently not all things may work properly when you do that. In next version more things should start working, but probably still not all things. Works are in progress...

**Comment by warichnict** [comment]
thanks for that hint. Could you add some hint like "enable javascript" when there is a site that requiereds this feature. the thing is i see just nothing at all and dont know what to look for... Or do i have to use some alternative content tag stuff that googles designer is not using by default as web develper?

thanks for any further advice...

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
