### ISSUE TITLE
Waterfox on OpenSuse Leap 15.1 or 15.2 (as well as Suse commercial versions)

### ISSUE THREAD

**Issue by FranzGotsis** [MrAlex94/Waterfox#1595]
Sadly the glibc issue prevents running waterfox on opensuse stable versions 15.1 and 15.2 which means that the last running release of waterfox was 2019.12.

As OpenSuse 15.2 (to be released in August 2020) stays on GLIBC 2.26 the issue will persist. There are some packages for waterfox around, but sadly they cannot be installed anymore:
https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-classic-kpe

Is there any way to get waterfox in its current versions running on OpenSuse 15.1 oder 15.2 meaning using GLIBC 2.26?

we are running a large amount of Suse Server machines, so we won't be able to migrate any time soon. The rolling release Tumbleweed works just fine with waterfox (GLIBC 2.31), but cannot be used due to lack of support garanties.

Just giving it a try before we have to deinstall waterfox
kind regards from Munich, Germany

**Comment by hawkeye116477** [comment]
`There are some packages for waterfox around, but sadly they cannot be installed anymore`

I checked and everything is fine. What error you had?

**Comment by FranzGotsis** [comment]
These ar ethe errors I get:

Problem retrieving files from 'home:hawkeye116477:waterfox'.
Download (curl) error for 'https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/openSUSE_Leap_15.1/repodata/repomd.xml':
Error code: Curl error 51
Error message: SSL: no alternative certificate subject name matches target host name 'download.opensuse.org'

Please see the above error message for a hint.
Warning: Skipping repository 'home:hawkeye116477:waterfox' because of the above error.
Problem retrieving files from 'devel:languages:rust'.
Download (curl) error for 'https://download.opensuse.org/repositories/devel:/languages:/rust/openSUSE_Leap_15.1/repodata/repomd.xml':
Error code: Curl error 51
Error message: SSL: no alternative certificate subject name matches target host name 'download.opensuse.org'

Please see the above error message for a hint.

It seems to be a certificate problem, it does not get to the point of actually trying to install the package.

One question: 
How did you make it work? If waterfox needs GLIBC 2.27 and OpenSuse provides release 2.26 there should some library calls that cannot be matched.
I have not checked that.
On the other hand firefox is running in its current version on OpenSuse Leap (as well as Suse Desktops - the commercial version), so there must be be a way to cope with the older library. I just want to understand the reason behind the GLIBC 2.27 requeirement and what kind of effort is necessary to overcome that requirement.

kind regards from Munich, Germany

**Comment by hawkeye116477** [comment]
@FranzGotsis https://forums.opensuse.org/showthread.php/540335-UPDATE-ERROR-what-does-this-mean, but 3 days ago was everything fine, so if you had same error before, then it maybe something bad is on your side. Anyway, for now you should observe https://status.opensuse.org/.

`How did you make it work? If waterfox needs GLIBC 2.27 and OpenSuse provides release 2.26 there should some library calls that cannot be matched.`

Waterfox hasn't specific Glibc version as build depend, but unfortunately Glibc isn't backward compatible, so if you want to make it working for example on distro with Glibc 2.10, then you can't compile program on distro with Glibc 2.11, it must be same version on lower.

Update: Check now, problem should be solved.

**Comment by hawkeye116477** [comment]
@FranzGotsis Check now, problem should be solved.

**Comment by manuelsongokuh** [comment]
same problem my opensuse 15.2 beta...i need this.. please fix it..

**Comment by manuelsongokuh** [comment]
for now i will back old version..

**Comment by hawkeye116477** [comment]
> same problem my opensuse 15.2 beta

@manuelsongokuh You mean that you can't download my package? 

@FranzGotsis Is that problem solved now or same error appears?

**Comment by manuelsongokuh** [comment]
i can download OLD versione 2019.12 and i cant download 2020.5 because problem missing version of glibc 2.27 opensuse 15.2 beta , have 2.26 glibc..maybe you can fix it for waterfox on opensuse glibc 2.26 or other solution..

**Comment by hawkeye116477** [comment]
@manuelsongokuh Just try this package => https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-classic-kpe or [AppImage](https://appimage.github.io/Waterfox_Classic/), as you wish, but I would rather recommend first package, cuz you'll get updates with system updates and AppImage requires downloading newer versions manually. Source files and other info on https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage#other-source-files.

**Comment by manuelsongokuh** [comment]
hi, few minutes ago i did installare from you repository link result perfect! but in search repository dont find wtaerfox for opensuse.. why?

**Comment by manuelsongokuh** [comment]
![image](https://user-images.githubusercontent.com/12126929/84141102-ec7ee200-aa52-11ea-835c-10bd35e030c7.png)

**Comment by hawkeye116477** [comment]
@manuelsongokuh That's because packages are named `watefox-classic-kpe` and `waterfox-current-kpe`, not `waterfox`. Package named `waterfox` is only transitional package made for Debian and Ubuntu, because previously name was different, but distros which uses rpm packages doesn't need it, I can just write `Obsoletes` and new package is automatically installed for them.

**Comment by FranzGotsis** [comment]
Thank to the latest change from  hawkeye116477 I could get Waterfox 2020.06 (64-bit) running. The one-click install was not working and resulted in error message regarding missing metadata of the archive.
But downloading the rpm-Package and then installing it via zypper worked without a glitch.

This means I am back in business ;-) Thank you a lot, also for the added source code package which allows me to compile just fine and if necessary adjust to new libraries.

Keep up the good work. Up to now I have never regretted using waterfox as my main browser. The ongoing support for old add-ons the easier API for extensions (e.g. password import and export is not possible with firefox anymore) and a few very nice features like copying the URLS of all Windows to the clipboard are cute features as well as added privacy none of the other big players offers for the multiplaform browsers (chrome, firefox, opera).
