### ISSUE TITLE
Replies not working with spot.im comments.

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1596]
**Describe the bug**
Clicking the reply button has no effect.

**To Reproduce**

1. Go to a motorsport.com article eg: https://www.motorsport.com/f1/news/williams-considering-selling-team/4798066/
3. Scroll down to the comments and wait for them to get loaded
4. Click any reply button.

**Expected behavior**
A textfield should appear to reply to a comments

**My configuration** 
 - Device: PC
 - OS: Win8.1
 - Version: Classic

**Comment by mzso** [comment]
It seems like its high time to move on from WF. Ever more websites are broken, the performance is poor on websites like youtube.. And Current doesn't have anything significant to offer over Firefox proper.

**Comment by hawkeye116477** [comment]
Do you have some example link?

------------------------------------------
`Current doesn't have anything significant to offer over Firefox proper`

It's your choice, although I can't agree with you. It supports old overlay and bootstraped extensions, but some must be modfied to work properly. It also has ability to show status bar, change tab bar position, bookmarks toolbar position, windows control position, show restart button, additional options for tab context menu and toggling it, new settings layout inspired by Vivaldi. I'm also preparing one great overlay extension for Waterfox Current :smile:

**Comment by mzso** [comment]
[**@hawkeye116477**](https://github.com/hawkeye116477) commented on [2020. jún. 1. 14:41 CEST](https://github.com/MrAlex94/Waterfox/issues/1596#issuecomment-636838422 "2020-06-01T12:41:23Z - Replied by Github Reply Comments"):
> Do you have some example link?
> 

I did. Although it accidentally got hidden by a comment remnant.

> 
> `Current doesn't have anything significant to offer over Firefox proper`
> 
> It's your choice, although I can't agree with you. It supports old overlay and bootstraped extensions, but some must be modfied to work properly. It also has ability to show status bar, change tab bar position, bookmarks toolbar position, windows control position, show restart button, additional options for tab context menu and toggling it, new settings layout inspired by Vivaldi. I'm also preparing one great overlay extension for Waterfox Current ![smile](https://github.githubassets.com/images/icons/emoji/unicode/1f604.png)

Well, the one big thing that isnterests me is old XUL addons. But virtually all of them are broken, even if they do get loaded. 

What sort of an overlay extension are you making?

**Comment by hawkeye116477** [comment]
@mzso Looks like that's same problem as https://github.com/MrAlex94/Waterfox/issues/1252#issuecomment-549055230. So now 4 pages needs feature known from Internet Explorer and there will be probably more. 

@MrAlex94 Can you backport it?

---------------------------------------

> What sort of an overlay extension are you making?

Classic (formerly All-in-One) Sidebar.

**Comment by MrAlex94** [comment]
Looks like it’s implementing [Bug 218415](https://bugzilla.mozilla.org/show_bug.cgi?id=218415)? Looks okay to me. Have added it to checklist.

**Comment by hawkeye116477** [comment]
Yes, that's it.

**Comment by MrAlex94** [comment]
Okay. Have got a list of the bugs I'll import. Exciting 😬

**Comment by apm** [comment]
@MrAlex94 can you add the list of Mozilla patches you will import to this ticket?  Is this something that is going to be worked on soon?  Thanks.
