### ISSUE TITLE
Waterfox crashes on this website. All tabs get unloaded

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1598]
**Describe the bug**
Crashes here: https://www.silentiumpc.com/en/product/signum-sg1-tg/

**My configuration** 
 - Device: pc
 - OS: win8.1
 - Version: Classic

**Comment by ghost** [comment]
The site opens correctly, no problem - Waterfox Classic

**Comment by hawkeye116477** [comment]
Maybe it's only problem with combination with some extension.

@mzso Can you give us all information from `about:support`?

**Comment by Squall-Leonhart** [comment]
more than likely another 391.35 related issue.

**Comment by mzso** [comment]
> more than likely another 391.35 related issue.

Possible. WF crashes with a brand new profile as well.
Didn't get to posting support data while I was at home. But I doubt it would have showed anything new from last time.

**Comment by mzso** [comment]
T

**Comment by nomosaic** [comment]
Me too, and also this one: https://www.realme.com/in/realme-x2

**Comment by Squall-Leonhart** [comment]
> 
> 
> Me too, and also this one: https://www.realme.com/in/realme-x2

and your graphics hardware + driver is?

This page is embedding a 2560x1000 Main@5 mp4

**Comment by nomosaic** [comment]
> 
> and your graphics hardware + driver is?
> 
> This page is embedding a 2560x1000 Main@5 mp4

Win7, Waterfox Classic x64, AMD R7 250 1G, with latest stable ver. driver
IE11 or Vivaldi is running no problem.

**Comment by Squall-Leonhart** [comment]
the latest stable AMD driver is from sometime november last year, nothing from this year passes my criteria for stable.

i had no issue loading the page on Win7, GTX 1080

**Comment by nomosaic** [comment]
> 
> 
> the latest stable AMD driver is from sometime november last year, nothing from this year passes my criteria for stable.
> 
> i had no issue loading the page on Win7, GTX 1080

Nvidia Yes! :rofl:   Someone told me that maybe it made a mistake in using a minority browser with a minority card.

**Comment by hawkeye116477** [comment]
I have Sapphire Radeon RX 570 and no problems also :smile:

**Comment by mzso** [comment]
By the way here is the about:support data:
[Waterfox-Clipboarder.2020.06.05.txt](https://github.com/MrAlex94/Waterfox/files/4735334/Waterfox-Clipboarder.2020.06.05.txt)

**Comment by hawkeye116477** [comment]
@mzso So no extensions, so it may be problem with your GPU/driver.

**Comment by mzso** [comment]
[**@hawkeye116477**](https://github.com/hawkeye116477) commented on [2020. jún. 5. 12:19 CEST](https://github.com/MrAlex94/Waterfox/issues/1598#issuecomment-639390153 "2020-06-05T10:19:09Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) So no extensions, so it may be problem with your GPU/driver.

Or Waterfox's handling of them.

**Comment by Squall-Leonhart** [comment]
there was hardware acceleration issues between 385.69 and 398.xx that occured on mostly pascal but also some fermi gpu's.

**Comment by rado84-github** [comment]
Waterfox-current (aurora), 21 extensions, 4 color themes, 440.82 nvidia proprietary driver - no problems whatsoever with the website mentioned above.

**Comment by LeeBinder** [comment]
Neither https://www.silentiumpc.com/en/product/signum-sg1-tg/ nor https://www.realme.com/in/realme-x2 crashing my WF Classic 2020.06 in macOS Mojave 10.14.6 - both web pages loading just fine.
