### ISSUE TITLE
Can't click into any "view entire discussion" button on reddit for looking more comments.

### ISSUE THREAD

**Issue by nomosaic** [MrAlex94/Waterfox#1601]
**Win7 Waterfox Classic 2020.5 x64**
e.g. by any post in reddit
https://www.reddit.com/r/waterfox/comments/brkiij/waterfox_crash/

And What is this in the Waterfox Community？
![Waterfox Community](https://user-images.githubusercontent.com/14254798/83752477-322a5c00-a69b-11ea-80b4-549da32460ce.jpg)

**Comment by hawkeye116477** [comment]
In that situations, you should go to website and see if newer Waterfox's version is available and then submit issue if that doesn't help. That was already discussed, just update to newest version.

**Comment by nomosaic** [comment]
Oh, just yesterday released. Nice
