### ISSUE TITLE
WF-current OS X 10.9 support?

### ISSUE THREAD

**Issue by NapalmSauce** [MrAlex94/Waterfox#1606]
Does -current really support OS X 10.9? It's advertised as requiring 10.9+ minimum, but right now it looks like there's dependencies on 10.10+ calls that aren't on 10.9.5. from a term:

```
XPCOMGlueLoad error for file /Volumes/Waterfox Current/Waterfox Current.app/Contents/MacOS/XUL:
dlopen(/Volumes/Waterfox Current/Waterfox Current.app/Contents/MacOS/XUL, 265): _Library not loaded: /System/Library/Frameworks/LocalAuthentication.framework/Versions/A/LocalAuthentication_
 Referenced from: /Volumes/Waterfox Current/Waterfox Current.app/Contents/MacOS/XUL
  Reason: image not found
Couldn't load XPCOM.
```
( https://developer.apple.com/documentation/localauthentication/ )

Also, see https://old.reddit.com/r/waterfox/comments/fi5k43/cant_open_waterfox_current_on_os_x_1095_mavericks/
( https://developer.apple.com/documentation/foundation/nsuseractivitytypebrowsingweb )

This is confusing. Unless there's something else I'm missing, should I assume anything?

**Comment by rorya** [comment]
Seems like the a very similar error that is plaguing WF Classic on 10.7 & 10.8. Seems like it may have something to do with the author building on a foreign system (read: not OSX). Here's that bug report, if it helps: #1523

**Comment by mr-a500** [comment]
Is anybody working on this - or is 2020.3.1 the end of the line for us?

**Comment by NapalmSauce** [comment]
Mozilla dropping support for even 10.11 after firefox 78.x ESR doesn't look too good either. Sounds like a warning to move away from Mac OS X before every single project wontfixes the last (barely) usable release. Mavericks is my upper limit.

**Comment by MrAlex94** [comment]
Waterfox Current needs 10.10 or later. Classic now works on 10.7 or later.
