### ISSUE TITLE
Classic (.06): DD-WRT r307xx (and more) Web Interface UNUSABLE.

### ISSUE THREAD

**Issue by SPWGitHub** [MrAlex94/Waterfox#1611]
** Attempting any change ANY change in the http control panel causes "Connection Reset" **

**To Reproduce**

1. Go to http://(router ip) - login
2. Click on ANY CHANGE AT ALL
3. Apply
4. See error --> "Connection Reset"
5. Change FAILED.

**Expected behavior**
NO ERROR

**Screenshots**
If you don't know what the "Connection Reset" page looks like, I give up!

**My configuration**
 - Device: Intel PC 
 - OS: Windows 10
 - Version: 2020.06 (64-bit)

**Comment by hawkeye116477** [comment]
What is on console (ctrl+shift+i)? Have you some demo of site?

**Comment by SPWGitHub** [comment]
![image](https://user-images.githubusercontent.com/22408621/84191969-51dcce00-aa67-11ea-8670-3dc9abd2ab73.png)
DD-WRT is open source router firmware. Google it if you're unfamiliar with this 40-year ongoing masterpiece project.

**Comment by SPWGitHub** [comment]
I don't have a router I'd be willing to open to wan access, but you could get a Linksys e-3000 on eBay for about $15. Makes a terrific wireless Ethernet bridge. (With DD-WRT)

**Comment by SPWGitHub** [comment]
![E3000_UPTime](https://user-images.githubusercontent.com/22408621/84193299-383c8600-aa69-11ea-9e07-7ba3746efc4a.PNG)
