### ISSUE TITLE
One process of WF eats up a lot of memory (after the latest update it seems)

### ISSUE THREAD

**Issue by azat11** [MrAlex94/Waterfox#1613]
**Describe the bug**
One process of WF eats up huge amounts of memory (I have 4GB on my laptop, that one process eats up over 2GB at times). This hasn't happened before. 

**To Reproduce**
As far as I see it happens when I open up a lot of tabs. But this hasn't happened before the latest update, and my browsing behaviour hasn't changed. Doesn't free up memory after tabs are closed, have to free it up through about:memory, that works sometimes, at other times I have to close WF to clear up memory.

**Expected behavior**
Not use that much memory, free the memory after tabs are closed.

**My configuration** 
 - Device: PC
 - OS: Windows 7
 - Version: Current 2020.06 (64-bit)

**Additional context**
I swithced to WF from FF because of RAM problems FF has. WF actually does free RAM much better for me. Hope this is a fluke and it all will return to normal.

List of extensions:
AdblockPlus 3.8.4
Auto Reload Tab 0.5
Better Twitter 1.4.2
Clippings 6.2.1
Dark Mode 0.3.5
Privacy Badger 2020.2.19
Search by Image on Google 1.6
Tampermonkey 4.10.6112
Touch VPN 3.1.5
uBlock Origin 1.26.2
Dark Theme for VK 3.1.1
Yandex Search Image 1.2
Download Master 3.10.0 (disabled) [no option to remove it]
Save Page WE 17.3 (disabled)

**A small update:** After observing for a bit I see that this process's RAM consumption is jumping up and down like crazy, and can stay above 1GB (just that process) even with 10 open tabs for a long time. I don't know enough to explain this strange behaviour.

**Comment by hawkeye116477** [comment]
> AdblockPlus 3.8.4
> uBlock Origin 1.26.2

You should use one adblocker, cuz they can conflict with each other just like AV and also uBO does the same job as ABP, but better, so I recommend disabling ABP and selecting more filterlists for uBO if needed.

**Comment by azat11** [comment]
> 
> 
> > AdblockPlus 3.8.4
> > uBlock Origin 1.26.2
> 
> You should use one adblocker, cuz they can conflict with each other just like AV and also uBO does the same job as ABP, but better, so I recommend disabling ABP and selecting more filterlists for uBO if needed.

Yeah, I actually did that just now. Will see if that helps.
It's just ABP sometimes does better job in creating filters, than uBO.

**Comment by azat11** [comment]
For now the issue appears to have been solved by the removal of the second adblocker.

**Comment by azat11** [comment]
Celebrated too soon. Right now it's happening again. This crazy process RAM usage keeps jumping from 150Mb to 1,5Gb for no apparent reason. And it's not just that, it also starts using CPU too much, as if something resource intensive was happening.
Anyone got any ideas why?

**Comment by rado84-github** [comment]
AdBlock Plus has been a resources greedy crap for a long time! I stopped using it years ago because it used too much RAM and CPU. Use only uBlock Origin and you won't have problems. Right now with 5 open tabs and uBlock Origin the highest amount of RAM used is just 220 MB by Waterfox-current.

**Comment by MrAlex94** [comment]
> Celebrated too soon. Right now it's happening again. This crazy process RAM usage keeps jumping from 150Mb to 1,5Gb for no apparent reason. And it's not just that, it also starts using CPU too much, as if something resource intensive was happening.
> 
> Anyone got any ideas why?

The easiest way to debug is by using [safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-safe-mode). If you browse for a while and find that you are okay, I would go through your extensions one by one. It’s a hassle but probably the only way to find out. Of course, if it still happens in safe mode then it’s most likely not extension related and we can go from there.

**Comment by azat11** [comment]
> 
> 
> AdBlock Plus has been a resources greedy crap for a long time! I stopped using it years ago because it used too much RAM and CPU. Use only uBlock Origin and you won't have problems. Right now with 5 open tabs and uBlock Origin the highest amount of RAM used is just 220 MB by Waterfox-current.

Well, I rutinely see 1Gb (and more) of RAM being used by FF or WF. IDK what is the reason, this was always true for me. But I usually have 10-20 tabs open, so maybe that is the reason.

**Comment by azat11** [comment]
> 
> 
> > Celebrated too soon. Right now it's happening again. This crazy process RAM usage keeps jumping from 150Mb to 1,5Gb for no apparent reason. And it's not just that, it also starts using CPU too much, as if something resource intensive was happening.
> > Anyone got any ideas why?
> 
> The easiest way to debug is by using [safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-safe-mode). If you browse for a while and find that you are okay, I would go through your extensions one by one. It’s a hassle but probably the only way to find out. Of course, if it still happens in safe mode then it’s most likely not extension related and we can go from there.

For now I removed Touch VPN extension, I suspected it to be the culprit - this RAM issue happened again and again when I opened multiple tabs while Touch VPN being turned on. I can't remeber if this issue appeared at other times. Issue didn't appear again since then.
