### ISSUE TITLE
https://techcommunity.microsoft.com/ style CSS not applied

### ISSUE THREAD

**Issue by rsoakford** [MrAlex94/Waterfox#1614]
**Describe the bug**
On visiting https://techcommunity.microsoft.com/ the style CSS does not appear to be applying correctly in Waterfox Current 2020.06 (64-bit).  When I visit the same site in Firefox Developer 78.0b4 (64-bit), the page style does apply correctly.  I have tried clearing all Waterfox cookies, cache, offline site data and site preferences (for time range: everything) but this has not resolved the issue on reloading the page.

**To Reproduce**
1. Go to https://techcommunity.microsoft.com/ 

**Expected behavior**
Page style CSS to apply.

**Screenshots**
Waterfox Current 2020.06 (64-bit)
![Screenshot_2020-06-10 Microsoft Tech Community Waterfox Current 2020 06](https://user-images.githubusercontent.com/59645846/84261180-3c24e280-ab13-11ea-9e1f-6afb925e07e2.png)
Waterfox Current console
![Screenshot_2020-06-10 Microsoft Tech Community Waterfox Current 2020 06 console](https://user-images.githubusercontent.com/59645846/84263267-1c8fb900-ab17-11ea-8b95-c4f75475dfdb.png)

Firefox Developer 78.0b4 (64-bit)
![Screenshot_2020-06-10 Microsoft Tech Community Firefox Developer 78 0b4](https://user-images.githubusercontent.com/59645846/84261188-3fb86980-ab13-11ea-9e73-0bf1f6057595.png)
Firefox Developer console
![Screenshot_2020-06-10 Microsoft Tech Community Firefox Developer 78 0b4 console](https://user-images.githubusercontent.com/59645846/84263294-287b7b00-ab17-11ea-90bb-902f0adb1532.png)

**My configuration** 
 - Device: Laptop
 - OS: Windows 10 Pro 1909 (build 18363.836)
 - Version: Current 2020.06 (64-bit)

**Comment by hawkeye116477** [comment]
I can't reproduce, everything is fine.

**Comment by rsoakford** [comment]
Thank you for checking, @hawkeye116477 

I reproduced the issue using the same Waterfox Current build on another Windows 10 Pro 1909 machine (and reproduced in the latest version of Brave) - I narrowed the issue in Waterfox down to the https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/ browser plug-in 🤭
