### ISSUE TITLE
cannot access econsult (gp surgery system)

### ISSUE THREAD

**Issue by linuxgirl22** [MrAlex94/Waterfox#1615]
Hello :-)

A new econsult system is now being used at gp surgery, **through which everything must be routed eg making appointments, arranging prescriptions, referrals, etc**. I have tried everything possible to access their portal for econsult ... javascript on, whitelistings then turning off all ad-blockers, allow pop-ups, cleaned cookies/history etc, restarted waterfox (classic appimage 2020.04-29.1.Build34.2.glibc2.17-x86_64). Not able to access where I can write information, and, on econsult's actual site, the same issues, but worse ... not even able to search the gp surgery and get a result. 

I can provide econsult's url, but not my local gp surgery url, as I'm sure you understand.
[https://patients.econsult.health/](url) I right-clicked and chose I think 'inspect source' ... no idea how to work with all the info that comes up, but clicking on the Console tab of my local gp surgery's econsult access page showed the following text: 
**_Content Security Policy: Directive ‘%’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.  (unknown)
Loading failed for the <script> with source “https://analytics.webgp.com/piwik.js”.  react-consult-back-pain:1
Loading failed for the <script> with source “https://static.hotjar.com/c/hotjar-28299.js?sv=4”._**

Add-ons are all turned off, bar the CA and the overrider, and Matrix is set to allow everything ... 
![right-side of top bar](https://user-images.githubusercontent.com/35760727/84426728-37475800-ac13-11ea-88bc-02087c2258b6.png)

Linux Anarchy arch install, using Mate. 
Ryzen 7 3800X, Radeon rx5700xt, 32 ram, using latest zen kernel.

Thanks.

**Comment by hawkeye116477** [comment]
For first, maybe try checking with latest version.

**Comment by linuxgirl22** [comment]
Hi hawkeye :-) and thanks for response ... I'll look that up right now.

**Comment by linuxgirl22** [comment]
I've tried it, and there's the same issues, but a shorter message when I right-click and see the Console information: _Content Security Policy: Directive ‘%’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively._ Yet I can see that this github page has the same error, so it can't be that. Maybe concerning that the econsult page doesn't even try to load scripts the earlier Waterfox is reporting issue about?

**Comment by hawkeye116477** [comment]
@linuxgirl22 Ok, unfortunately that message doesn't tell anything about that problem. If there are only that messages, then it could be some problem with css handling of browser.  You can also click on console and on CSS and choose errors and see if something another appeared, if not then less chance that someone will be able to help you with it. To be able to help at least page must be saved for offline viewing, but if you can't then probably you'll rather need to access this site on Waterfox Current or some another browser.

**Comment by linuxgirl22** [comment]
@hawkeye116477 I've clicked on Console, then CSS, and there are a lot of issues:

`Content Security Policy: Directive ‘%’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.  (unknown)
Expected declaration but found '*'.  Skipped to next declaration.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:63
Unknown property 'speak'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:4564
Unknown property 'text-underline-position'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:18934
Unknown property 'test-underline-position'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:19360
Unknown property 'text-underline-position'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:20203
Unknown property 'text-underline-position'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:20624
Unknown property 'text-underline-position'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:21035
Expected media feature name but found '-webkit-min-device-pixel-ratio'.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:50165
Expected colour but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:50383
Unknown property 'column-break-inside'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:57946
Unknown property 'break-inside'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:57966
Unknown property '-moz-box-shadow'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:69078
Unknown property '-moz-box-shadow'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:74887
Error in parsing value for 'cursor'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:76202
Unknown property '-moz-box-shadow'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:86332
Error in parsing value for 'display'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:88227
Error in parsing value for 'background-image'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:95441
Error in parsing value for 'background-image'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:107971
Error in parsing value for 'display'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:108290
Error in parsing value for 'display'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:108584
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:129452
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:129511
Error in parsing value for 'background-image'.  Declaration dropped.  styles-bbb878a41e371dd163a50c5304da6b7e.css:1:134208
Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector.  2.3932ead9.chunk.css:1:7359
Unknown property 'user-select'.  Declaration dropped.  2.3932ead9.chunk.css:1:17322
Error in parsing value for 'display'.  Declaration dropped.  react-consult-back-pain
Error in parsing value for 'display'.  Declaration dropped.  react-consult-back-pain
Error in parsing value for 'display'.  Declaration dropped.  react-consult-back-pain
Error in parsing value for 'display'.  Declaration dropped. react-consult-back-pain
Loading failed for the <script> with source “https://analytics.webgp.com/piwik.js”.  react-consult-back-pain:1
Loading failed for the <script> with source “https://static.hotjar.com/c/hotjar-28299.js?sv=4”.  react-consult-back-pain:1
Error in parsing value for 'display'.  Declaration dropped.  react-consult-back-pain
Unknown property '-moz-scrollbar-width'.  Declaration dropped.  react-consult-back-pain
Unknown property 'scrollbar-width'.  Declaration dropped.  react-consult-back-pain
Unknown pseudo-class or pseudo-element '-webkit-scrollbar'.  Ruleset ignored due to bad selector.  react-consult-back-pain
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector.  react-consult-back-pain
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-track'.  Ruleset ignored due to bad selector.  react-consult-back-pain
Error in parsing value for 'display'.  Declaration dropped.  react-consult-back-pain
Error in parsing value for '-webkit-box-align'.  Declaration dropped.  react-consult-back-pain
Unknown property 'text-underline-position'.  Declaration dropped.  react-consult-back-pain

Fingers crossed that points to something solvable. I've been able to save the page for offline viewing and can pick some parts out, incase they're useful:

    
    
    <script>
    if (navigator.userAgent.indexOf('MSIE') !== -1 || navigator.appVersion.indexOf('Trident/') > 0) {
        if (navigator.userAgent.match('MSIE 10.0;')) {
            $('html').addClass('ie10');
        }
        if (navigator.userAgent.match('MSIE 9.0;')) {
            $('html').addClass('ie9');
        }
        if (navigator.userAgent.match('MSIE 8.0;')) {
            var root = document.getElementsByTagName( 'html' )[0];
            root.setAttribute( 'class', 'ie8' );



<header class="header" aria-label="main-header" role="banner">
    
    <a href="#content" class="skiplink sr-only">Skip to main content</a>
    <div class="notice-banner-info notice-banner-ie">
        <div class="wrapper">
            We offer limited support for your version of the Internet 
Explorer browser. You can still use the site and complete a GP 
consultation, but
            not everything will work and look great. If you can, try to <a href="http://www.browsehappy.com/" target="_blank" rel="noopener noreferrer">upgrade to a modern browser</a>
        </div>
    </div>
_**[the browsehappy page lists Firefox as 1 of the 5 browsers that can be used]**_

            
            <script type="text/javascript">
                setTimeout(function(){window.location.hash = "#EC"}, 1000);
                // IE9 Fix for missing console definition
                if(!window.console) {
                    var console = {
                        log : function(){},
                        warn : function(){},
                        error : function(){},
                        time : function(){},
                        timeEnd : function(){}
                    }
                }
                // IE9 Fix for missing window.location.origin
                if (!window.location.origin) {
                    window.location.origin = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port: '');
                }
            </script>

    
    
        
        <script type="text/javascript">
            var _paq = _paq || [];
            _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
            _paq.push(["setCookieDomain", "*.webgp.com"]);
            _paq.push(['trackPageView']);
            _paq.push(['enableLinkTracking']);
            (function () {
                var u = "//analytics.webgp.com/";
                _paq.push(['setTrackerUrl', u + 'piwik.php']);
                _paq.push(['setSiteId', 1]);
                var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
                g.type = 'text/javascript';
                g.async = true;
                g.defer = true;
                g.src = u + 'piwik.js';
                s.parentNode.insertBefore(g, s);
            })();
        </script>
        

    </script><script>
    // Track outbound link exits
    $(document).ready(function() {
        $("a[target='_blank']").click(function(){
            var href = $(this).attr('href');
            trackOutboundLink(href);
        });
    });
    </script>`

**Comment by linuxgirl22** [comment]
Hi again. Just an update ... waterfox current, without any profile/add-ons etc, runs the site properly (I didn't go through a full enquiry, but could see that all the parts needed for that were active), so I can use current just for that, and keep waterfox classic as main. 

Not sure if it's an add-on issue, or if the code above shows any clues about if it's a waterfox classic bug. No time just now to test all add-ons, but had tested with them all off previously, so am not sure it's that. If it is a different bug in waterfox classic it'd be awesome to not need to use both waterfox versions (appimages), but relieved to be able to access site in some form at this point.
