### ISSUE TITLE
Statusbar overlapping tabbar at the bottom

### ISSUE THREAD

**Issue by rado84-github** [MrAlex94/Waterfox#1617]
**Describe the bug**
When I set Waterfox to show statusbar (whether it's just statusbar or the one with info overlay) and then I set tabbar to be at the bottom, the statusbar is overlapping the tabbar. For instance, when I hover over a link to see its URL address, the address is displayed over the tabbar, completely hiding the tabs (image01).

**To Reproduce**
1. Go to browser preferences.
2. Set statusbar to be displayed. It doesn't matter if it's just statusbar or the one with info overlay).
3. Set tabbar to be displayed at the bottom.
4. Open any website and hover over any link to view its full URL.
5. You will see how the URL is completely covering all the tabs in the tabbar.

**Expected behavior**
When tabbar is set to bottom, it should appear right above the statusbar.

**Screenshots**
![image01](https://user-images.githubusercontent.com/41172201/84599784-4df0e780-ae7d-11ea-9c17-92360ee5763d.png)

**My configuration**
[rado@arch]: ~>$ sysinfo
 rado@arch
 OS: Arch Linux 
 Kernel: x86_64 Linux 5.7.2-arch1-1
 Uptime: 27m
 Packages: 1127
 Shell: bash
 Resolution: 1920x1080
 DE: Cinnamon 4.6.3
 WM: Muffin
 WM Theme: Mint-Y-Brownish-v4.3_for-Cinnamon_by-Valso (Cinnamox-Rhino)
 GTK Theme: Mint-Y-Brownish-v4.3_for-Cinnamon_by-Valso [GTK2/3]
 Icon Theme: Humanity-Dark
 Font: Noto Sans Bold 10
 Disk: 980G / 1,5T (65%)
 CPU: Intel Core i7-4770 @ 8x 3.9GHz [32.0°C]
 GPU: GeForce GTX 1050 Ti
 RAM: 1645MiB / 32034MiB

**Comment by hawkeye116477** [comment]
I can't reproduce that.

**Comment by rado84-github** [comment]
> I can't reproduce that.

I can make a video, if my text explanation is not clear.

**Comment by rado84-github** [comment]
I'm closing this and the other issue. I found what the problem was - a literally ancient version of userChrome.css that contained some CSS code to forcibly return the statusbar in Firefox 57+. I removed that part of the code and now everything works the way I wanted it.
