### ISSUE TITLE
[Feature request] Persistent extension debugging

### ISSUE THREAD

**Issue by narcolepticinsomniac** [MrAlex94/Waterfox#1619]
It's great that Waterfox allows installations outside AMO, but when you're developing extensions, installing from a file is so much more of a PITA than having the ability to keep unpacked extensions side-loaded, like you can in most Chromium forks.

**Comment by narcolepticinsomniac** [comment]
My bad, on the classifying this as a bug, obviously. Only noticed the one button, so I clicked it without thinking much about it. Now I see there's a link underneath.

**Comment by hawkeye116477** [comment]
@narcolepticinsomniac `about:debugging#addons`

**Comment by narcolepticinsomniac** [comment]
AFAIK, loading unpacked extensions that way is temporary, meaning as soon as you restart the browser it disappears. The request here is for these types of installs to remain persistent, like they are in Chromium.

**Comment by narcolepticinsomniac** [comment]
@hawkeye116477 What's the point of deleting your comment? To make sure there's absolutely zero context to the response?

**Comment by hawkeye116477** [comment]
Sorry, I removed it fast, I didn't thought that you will see it at that moment and reply and I did that because I read whole topic again.

**Comment by narcolepticinsomniac** [comment]
Fair enough. NBD, I just don't need any help making myself look crazy. =)
