### ISSUE TITLE
Classic - unable to install apps or change payment settings on play.google.com

### ISSUE THREAD

**Issue by Avrution** [MrAlex94/Waterfox#1620]
Try to install any app (https://play.google.com/store/apps/details?id=com.instagram.android) and nothing will happen.  On the first page load, there may be a quick blue swirl when hitting install.

https://play.google.com/store/paymentmethods - continuous colored circle

This happens in safe mode as well with all addons disabled.

Previously, changing the useragent worked fine.  That seems to no longer be the case, unless it needs a specific override.

![screenshot](https://user-images.githubusercontent.com/38819283/84604428-a616f200-ae5b-11ea-8322-f3c021bb44de.png)

**Comment by rado84-github** [comment]
Both things you're trying to do are done through the Google Play app that comes by default with any Android. It's also possible that Google have limited the Google Play store to work only with Google Chrome.

**Comment by Avrution** [comment]
Doesn't change the fact that this no longer works in classic.  Current works fine, so either something isn't supported in classic anymore and can be changed (setting or another useragent) or classic will just no longer be supported on play.google.com anymore.

**Comment by rado84-github** [comment]
I know this may be the wrong place to ask but... where did you find Waterfox for Android, anyway? There isn't such a browser in Google Play and on the WF homepage there are links to download only for PC operating systems.

**Comment by Avrution** [comment]
This is Waterfox Classic for the PC, not Android

**Comment by hawkeye116477** [comment]
@Avrution Strange, I checked and it's working fine for me.

**Comment by rado84-github** [comment]
> This is Waterfox Classic for the PC, not Android

Sorry, I thought you were using an Android version because the "install app" part of the website works only for android devices.
As for the payment methods - that part opens without any problems in waterfox-current.

**Comment by Avrution** [comment]
On the website install let's you send it to one of your devices remotely

**Comment by Avrution** [comment]
> 
> 
> @Avrution Strange, I checked and it's working fine for me.

On classic?  Any modifications?  Someone else tried on reddit and had the same issue.

**Comment by hawkeye116477** [comment]
@Avrution Yes, on classic, no modifications.

**Comment by Avrution** [comment]
Very odd.  I just tried on a fresh install and it still doesn't work.  Been sitting here on the swirling circle at payment methods for a few minutes now.

**Comment by Avrution** [comment]
I should add the same thing seems to happen on pay.google.com - most menu options never load

**Comment by Avrution** [comment]
Wanted to update this with some more info that was figured out on reddit

https://www.reddit.com/r/waterfox/comments/jfjans/paygooglecom_never_fully_loads_in_classic/

Google pay is the cause for google play having issues. Ntrf stated:

In my case pay.google.com sends Content-security-policy header in one of its responses. Compatibility table shows that it should be implemented in FX 33, but maybe there was some kind of regression.
