### ISSUE TITLE
Waterfox classic is broken on edx.org now.

### ISSUE THREAD

**Issue by 133794m3r** [MrAlex94/Waterfox#1625]
**Describe the bug**

EdX.org is broken for some reason now with waterfox classic.

**To Reproduce**
1. go to edx.org
2. see tha it doesn't look right.
3. Try to set a general.useragent.override.github.com to be the same useragent as github to see if that fixes it.
4. It doesn't the home-page is still broken for some reason.

**Expected behavior**
The site looking correct.

**Screenshots**

![Screenshot at 2020-06-19 22-13-29](https://user-images.githubusercontent.com/599849/85189161-aff58680-b29b-11ea-8fd2-f596b0fa6c20.png)

**My configuration** 
 - Device: PC/
 - OS: GNU/Linux Debian
 - Version: Classic 2020.05 (64-bit)(latest in the apt repo from spiderman avatar guy.

**Additional context**
The rest of the pages work just fine. I can see my dashboard, I can see my progress. It's only the main page, and the pages when you try to view a course you're not currently enrolled in that this issue occurs.

**Comment by hawkeye116477** [comment]
Webmasters should fix their code, someone already reported that => https://openedx.atlassian.net/browse/CRI-218.

**Comment by 133794m3r** [comment]
I'll have to +1 on it then. B/c it's annoying that it all-of-a-sudden did that to me.
