### ISSUE TITLE
British English Dictionary Can't install Version issue

### ISSUE THREAD

**Issue by Wonk0TheSane** [MrAlex94/Waterfox#1627]
**Describe the bug**

**To Reproduce**
 This add-on requires a newer version of Firefox (at least version 78.0). You are using Firefox 57.0.

**Expected behavior**

**Screenshots**

**My configuration** 
 - Device: 
 - OS: 
 - Version: 

**Additional context**

**Comment by hawkeye116477** [comment]
You should read carefully, it's not dictionary, it's language package :stuck_out_tongue: 
This is dictionary => https://addons.mozilla.org/pl/firefox/addon/british-english-dictionary-2/ and version for Waterfox Classic is on developer's GitHub as written in description.

**Comment by Wonk0TheSane** [comment]
Hi,
Thanks for the feedback, I do have that "add-on" installed but whenever doing a spell check I am always presented with the us-english spelling as I cannot install the current "language pack" due to version. Even going through the install I don't have english-uk as the dictionary.. 
My apologies too, as this is my first report... Forgive me..

**Comment by hawkeye116477** [comment]
> Even going through the install I don't have english-uk as the dictionary

Are you sure that you installed this => https://github.com/marcoagpinto/aoo-mozilla-en-dict/blob/master/Extension%20-%20Firefox%20%2B%20Thunderbird%20%2B%20SeaMonkey%20(GB)%20(Legacy)/british_english_dictionary_marco_pinto-2.85-legacy.xpi ? 
After installing it I can choose British for spell checking.
