### ISSUE TITLE
Unable to remove the home button from the interface

### ISSUE THREAD

**Issue by rado84-github** [MrAlex94/Waterfox#1634]
I wanted to remove the home button (house-like icon) from the interface thus leaving only back, forward and refresh buttons.

![Снимка от 2020-06-30 03-37-31](https://user-images.githubusercontent.com/41172201/86069722-6c610080-ba83-11ea-8f73-c2a893bbbb02.png)

But no matter what I do, it won't get out of there. I tried dragging it out in "Customize" mode but it won't move at all. I tried moving it to the additional menu but it only disappears for about half a second and then returns to its position. That button is really annoying because sometimes I click it by mistake, instead of clicking "back". That's why I need to remove it permanently.

Waterfox Current 2020.06 (64-bit)

[rado@arch]: ~>$ sysinfo
 OS: Arch Linux 
 Kernel: x86_64 Linux 5.7.6-arch1-1
 Uptime: 6h 38m
 Packages: 1142
 Shell: bash
 Resolution: 1920x1080
 DE: Cinnamon 4.6.6
 WM: Muffin
 WM Theme: Mint-Y-Brownish-v4.3_for-Cinnamon_by-Valso (Cinnamox-Rhino)
 GTK Theme: Mint-Y-Brownish-v4.3_for-Cinnamon_by-Valso [GTK2/3]
 Icon Theme: Humanity-Dark
 Font: Noto Sans Bold 10
 Disk: 1,1T / 1,5T (68%)
 CPU: Intel Core i7-4770 @ 8x 3.9GHz [33.0°C]
 GPU: GeForce GTX 1050 Ti
 RAM: 1867MiB / 32034MiB

**Comment by hawkeye116477** [comment]
Hmm, I can move it to customize and it never returns.

**Comment by rado84-github** [comment]
> Hmm, I can move it to customize and it never returns.

https://drive.google.com/file/d/1wIkYbY-5Jb3_VR7Lllkwv3lN7eo8b9AR/view?usp=sharing

In Firefox I have always been able to remove it, but not in WF.

**Comment by hawkeye116477** [comment]
So that looks like problem on your side, maybe some extension or another thing prevents that, maybe check on safe mode.
