### ISSUE TITLE
Discord is shown incorrectly

### ISSUE THREAD

**Issue by MarkoH01** [MrAlex94/Waterfox#1636]
My discord is looking like shown in attachment. As you can see the scrollbars are overlapping (Windows Waterfox 2020.06) - this is not 
the case with the actual Firefox release.

![discord](https://user-images.githubusercontent.com/22550982/86237070-66f6d980-bb9b-11ea-9d9c-a15cefdcdc04.jpg)

**Comment by hawkeye116477** [comment]
Seems that problem is that Waterfox Classic doesn't support `scrollbar-color` and `scrollbar-width` CSS properties.

**Comment by MarkoH01** [comment]
> 
> 
> Seems that problem is that Waterfox Classic doesn't support `scrollbar-color` and `scrollbar-width` CSS properties.

Is there any way to fix this?

**Comment by hawkeye116477** [comment]
@MarkoH01 Yes, you only need to send Pull Request with implementation of it or convince someone to do it :smile:

**Comment by docrR** [comment]
While this isn't necessarily a fix to lack of scrollbar-color / scrollbar-width properties, Overlay scrollbars can clean that mess up. If you have Classic Add-ons Archive, just search for the Overlay Scrollbars 0.4.3 extension from by def00111 and configure it to your liking. Or HideScrollbars from Aris.
Still would be great to see native implementation of these properties in Classic though =)

**Comment by ghost** [comment]
I can say that I am also experiencing this on Waterfox Current on the StreamElements dashboard. Heres what it looks like
![waterfox_y4ISHD1nSE](https://user-images.githubusercontent.com/37266538/89817534-97417880-db48-11ea-8e90-8ecd812e968c.png)

**Comment by hawkeye116477** [comment]
Well, I've good news. I started working on implementing these 2 things for Classic. It's almost ready, but I'll do that only for Windows and Linux. I'll leave Mac OS for those willing.
