### ISSUE TITLE
Text is missing on https://nvidia.custhelp.com/ text entry boxes

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox#1637]
**Describe the bug**
Text is missing on https://nvidia.custhelp.com/ text entry boxes

**To Reproduce**

1. Open page
2. navigate to login

**Expected behavior**
text is visible in the text entry boxes for username and asterisks for password

**My configuration** 
 - Device: PC
 - OS: Windows 7
 - Version: Classic 2020.6

**Comment by hawkeye116477** [comment]
Looks like that's problem with parsing CSS by browser. Temporary fix for uBO => `nvidia.custhelp.com##input:style(padding: 0 !important;)`

**Comment by hawkeye116477** [comment]
@Squall-Leonhart That should be fixed by latest update.

**Comment by Squall-Leonhart** [comment]
confirmed fixed
