### ISSUE TITLE
fullscreen youtube -> open link in new tab can freeze a waterfox window

### ISSUE THREAD

**Issue by toddfraser88** [MrAlex94/Waterfox#1651]
**Describe the bug**

When in fullscreen youtube at the end of a video when you get a grid of videos to watch next, if you right click on a video and click open link in new tab waterfox will open a new tab for that video, but you will be unable to switch to it, and that waterfox window will freeze, being unable to switch tabs or anything until you kill the waterfox process.

**To Reproduce**
1. Go to '...' the end of a youtube video in fullscreen
2. Click on '....' another video, right click and select open link in new tab

At the end of a fullscreen youtube video right click on any video in the grid and select open link in a new tab. Exit fullscreen youtube, try to switch to new tab.

**Expected behavior**

when open link in new tab is selected Exit fullscreen youtube and open a new tab for the selected video without freezing the window.

**Screenshots**

**My configuration** 
 - Device:  custom PC
 - OS:  Windows 10 1903
 - Version:  Current 2020.06

**Additional context**

**Comment by OnSive** [comment]
Possible duplicate to https://github.com/MrAlex94/Waterfox/issues/1540

**Comment by Squall-Leonhart** [comment]
it is a duplicate

**Comment by kriskog** [comment]
Fixed in latest current release. 🚀
