### ISSUE TITLE
More Web sites not working

### ISSUE THREAD

**Issue by sutex** [MrAlex94/Waterfox#1656]
Cant log in to 
https://www.originenergy.com.au/
https://robertsspaceindustries.com/spectrum/community/SC
Twitter

All this sites above work in Opera , but NOT in Waterfox classic  even if restarted with all addon disabled

I have found many more that just refuse to load

**Comment by apm** [comment]
Yes, this is quickly becoming a problem for accessing many sites.  I assume there is a library that is expecting the latest browsers' behavior.  See https://github.com/MrAlex94/Waterfox/issues/1596

**Comment by condoghost** [comment]
https://www.bbc.co.uk and https://www.bbc.com all video clips - EVERY SINGLE ONE - return the message 'This content doesn't seem to be working'. All working okay Google Chrome, Safari, SeaMonkey.

**Comment by BrettDikeman** [comment]
> https://www.bbc.co.uk and https://www.bbc.com all video clips - EVERY SINGLE ONE - return the message 'This content doesn't seem to be working'. All working okay Google Chrome, Safari, SeaMonkey.

I believe you that it's not working, but I don't think this is a Waterfox-specific issue. In the June Waterfox release on OS X, BBC's videos play just fine, and this is with a fairly aggressive suite of privacy and adblocking plugins.

![waterfox bbc](https://user-images.githubusercontent.com/4131229/86946346-3b826a80-c118-11ea-9653-59d3c9c62c72.png)

It would be highly surprising if a major internet presence like the BBC stopped supporting specific versions of Firefox-based browsers.

**Comment by sutex** [comment]
Update, when signing into Star Citizen Website , there is a another page which comes up for authentication. Just in Waterfox this page never appears. So can never sign in. In the newer firefox that page appears so can sign in with no problems. Had to install the newer firefox to allow me access sites, simply because Waterfox is failing on so many, yet is still my default browser with all my favorite addons

**Comment by hawkeye116477** [comment]
@condoghost For me that videos works fine. Maybe that depends on what OS you're using.

**Comment by hawkeye116477** [comment]
@sutex Have you some test account?

**Comment by Squall-Leonhart** [comment]
i have logged into twitter and rsi just fine, seems to be a user profile problem.

**Comment by condoghost** [comment]
> 
> 
> > https://www.bbc.co.uk and https://www.bbc.com all video clips - EVERY SINGLE ONE - return the message 'This content doesn't seem to be working'. All working okay Google Chrome, Safari, SeaMonkey.
> 
> I believe you that it's not working, but I don't think this is a Waterfox-specific issue. In the June Waterfox release on OS X, BBC's videos play just fine, and this is with a fairly aggressive suite of privacy and adblocking plugins.
> 
> ![waterfox bbc](https://user-images.githubusercontent.com/4131229/86946346-3b826a80-c118-11ea-9653-59d3c9c62c72.png)
> 
> It would be highly surprising if a major internet presence like the BBC stopped supporting specific versions of Firefox-based browsers.

"I believe you that it's not working, but I don't think this is a Waterfox-specific issue" and "It would be highly surprising if a major internet presence like the BBC stopped supporting specific versions of Firefox-based browsers."?

Right, so it is 'not Waterfox' and it is 'not a major internet presence like the BBC". Very helpful that - not!

Some days no BBC News video clips play, other days all BBC News video clips play. It most definitely is an 'issue' and more likely to do with Waterfox 'Connection Settings Configure Proxies to Access Internet Manual proxy configuration No proxy for' where sometimes the 'No proxies for' 'works' and other times it does not. But hey, who am I but someone reporting an 'issue' and you telling me what it isn't. Thank-you for your very helpful comment.

**Comment by condoghost** [comment]
> 
> 
> @condoghost For me that videos works fine. Maybe that depends on what OS you're using.

I haven't changed my OS, Windows 7 Pro since it was first released. Some days no BBC News video clips play in Waterfox and other days all BBC News video clips play in Waterfox.

It may likely to do with Waterfox 'Connection Settings Configure Proxies to Access Internet Manual proxy configuration No proxy for' where sometimes the 'No proxies for' 'works' and other times it appears the 'No proxy for' does not 'work'.
I have come across this before with some earlier versions of Waterfox but all had settled down and was working with no 'issues' like this until this version was loaded. Immediately before updating, these BBCNews video clips were playing, immediately afterwards they were not. The next day they were, a day or so later they were not. Yesterday they were. Today they are. Who knows, 'it's a 'mystery''.

**Comment by condoghost** [comment]
> 
> 
> i have logged into twitter and rsi just fine, seems to be a user profile problem.

What 'seems to be a user profile problem'?
The issue I get with some days all BBC News video clips playing in Waterfox, other days 'not' cannot be a 'user profile problem' otherwise BBC News video clips would always be playing in Waterfox or would always not be playing in Waterfox.

**Comment by sutex** [comment]
Still cant login into robertsspaceindustries.com , I put in my ID password and the page refreshes to 'not signed in'

**Comment by Squall-Leonhart** [comment]
try a new profile, or white listing the site with your adblocker.

**Comment by sutex** [comment]
A New Profile reset Waterfox, which is not going to happen I have add-ons used for many years and tweets to those add-ons it's like saying I have a problem with the human race, lets remove them and start again. I see this as a fix many others do not :)

**Comment by Squall-Leonhart** [comment]
you're wasting everyones time then.

**Comment by hawkeye116477** [comment]
> A New Profile reset Waterfox, which is not going to happen I have add-ons used for many years

But you know that you could always return to old profile.

**Comment by sutex** [comment]
Must be me, with the same addons used for years with no issues Old Firefox to Cyberfox to Waterfox. Then one day in Waterfox pages just don't load .. 

@hawkeye116477 Yep , but don't worry about it. Ive lost functionality and not destroying a profile to fix it.

Lost functionality for Google sheets , was working not anymore, and Imugr link the other day refused to load as well. Copied that into modern Firefox and it loaded up fine.
