### ISSUE TITLE
Current cannot save a selection as HTM page

### ISSUE THREAD

**Issue by rebop** [MrAlex94/Waterfox#1657]
**Describe the bug**
Current 2020 cannot save a selection source as an htm page. This works in Classic as expected.

**To Reproduce**
1. Select part of a page
2 Right click and choose View Selection Source
3.File / Save Page As, choose Web Page HTML Only
4. No page is created or saved

**Expected behavior**
As in Classic, a page xxx.htm is created and saved in your directory of choice.

**My configuration** 
 PC
Windows 7 or 10
Fails in 2020.06 Testing 2020.07 now and expect the same failure.

Confirmed it fails in Current 2020.07 as well.

**Comment by rebop** [comment]
No reply at all here, Zulip or Reddit. :(

**Comment by MrAlex94** [comment]
Does this work on Firefox 68 ESR as well?

**Comment by rebop** [comment]
Hi Alex. I don't have Firefox 68ESR. It works on Classic. Used to work on
Current until I reported it.
 
Checking portable 2020.07.2 now.....works perfectly there as well.
 
Checking Current one more time.... It fails. But just noticed I am getting a
filed message under downloads. I do not recall seeing that before.
 
 

  _____

**Comment by rebop** [comment]
Still does not work in 2020.08 Current. Does still in Classic
