### ISSUE TITLE
Addon CoolPreviews not working properly

### ISSUE THREAD

**Issue by w64fox** [MrAlex94/Waterfox#1658]
CoolPreviews (which b.t.w. along with SessionManager is my main reason for preferring Waterfox over Firefox) since last update doesn't work properly anymore.
On starting Waterfox at first, though, it seems to be still functioning as usual but then after a while the CoolPreviews window keeps constantly freezing so as to force me to restart the browser.
Please fix this VERY annoying bug!

My configuration
 - Device:  PC
 - OS:  Windows 7 x64

**Comment by Squall-Leonhart** [comment]
this is an issue in the dll that coolpreviews uses, and nothing has changed since it was used in cooliris.
