### ISSUE TITLE
This domain is not registered with Commento.

### ISSUE THREAD

**Issue by Jamesstevens-3rd** [MrAlex94/Waterfox#1659]
Hi Alex

apologies for reporting it here but there are no blog comments (waterfox.net/blog/), only an error message 'This domain is not registered with Commento.'

would be nice if you could fix this as I dislike using reddit.

thanks
James

**Comment by hawkeye116477** [comment]
That problem was already some time ago, so seems that now it returned again.

**Comment by Jamesstevens-3rd** [comment]
I  assumed Commento was a paid for service and someone has not paid the bill, but depends on whether he is using Self-hosting (free) or Cloud Service (not free)

**Comment by hawkeye116477** [comment]
@Jamesstevens-3rd MrAlex wrote on February on chat that he migrated to self-hosted.

**Comment by MrAlex94** [comment]
Fixed, looks like the db connection died in docker
