### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by wkuzma** [MrAlex94/Waterfox#1677]
Your connection is not secure

The owner of cod4x.me has configured their website improperly. To protect your information from being stolen, Waterfox has not connected to this website.

This site uses HTTP Strict Transport Security (HSTS) to specify that Waterfox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

**Comment by hawkeye116477** [comment]
@wkuzma For me this site works fine. Did you know that also there are 2 Waterfoxes and multiple versions? You should fill in bug report form, provide what is your configuration.

**Comment by wkuzma** [comment]
the site corrected their problem and I am able to see it again 
- the reason I posted the message above is because in firefox I was able to add an exception but not in waterfox
