### ISSUE TITLE
Videos are are not visible ...

### ISSUE THREAD

**Issue by PiliJ** [MrAlex94/Waterfox#1679]
... on this site (well in Firefox):
https://www.hln.be/video/veel-goodwill-rond-mondmaskers-maar-ook-hardleerse-mensen~p158536
When clicked, the image of the video turns white.
PC - Win 8.1x64
Version Waterfox Classic : 07/2020

**Comment by hawkeye116477** [comment]
I can't reproduce that on Linux and W10.

**Comment by PiliJ** [comment]
Ter info, i tried also in IE where only the first video-image appears (see attach)
![Image 001](https://user-images.githubusercontent.com/33757855/88486255-c7035480-cf7c-11ea-9396-942a31879184.jpg)
When i click on it, nothing happens. Same with all the videos on the right of the screen.
I can only see all the videos in Firefox.
