### ISSUE TITLE
Waterfox Classic Addon Support

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [MrAlex94/Waterfox#1681]
This is more of a question really.
I've been using Waterfox Classic primarily because it allowed me to update from a really old Firefox version but retain usage of my plugins.
I just updated to Waterfox Current (2020.07) and see that none of the plugins were carried across.  This is a show-stopper issue for me.
Is this normal behaviour or did something go wrong in porting my plugins?

**Comment by hawkeye116477** [comment]
> did something go wrong in porting my plugins

Plugins or maybe extensions? Plugins should work, but extensions needs changes to work properly, see https://github.com/MrAlex94/Waterfox/wiki.

**Comment by Napoleon-BlownApart** [comment]
Ok, my mistake.  The question is about Extensions.  None were migrated across.
@hawkeye116477 :  Thanks for the link.  I read what's there and it appears the answer to my question is that my legacy extensions won't work.  That being the case, I'm staying with Waterfox Classic.

Thanks for your time.
