### ISSUE TITLE
[Current] Broken after 2020.07.1 update

### ISSUE THREAD

**Issue by maxoku** [MrAlex94/Waterfox#1683]
**Describe the bug**

After today's update some of my add-ons stopped working properly. Custom buttons and Download Grab. Search bar doesn't work either. When I've downgraded Waterfox it didn't want to open the profile, only creating new one.

**My configuration** 
 - Device: PC
 - OS: Windows 8.1
 - Version: Current 2020.07.1

**Comment by hawkeye116477** [comment]
> Custom buttons and Download Grab

Hmm, I don't see them in AMO. Where you get them?

> When I've downgraded Waterfox it didn't want to open the profile, only creating new one.

Just remove `compatibility.ini` file from profile and it will work :smile:.

**Comment by maxoku** [comment]
https://github.com/pouriap/Firefox-DownloadGrab/releases
https://forum.mozilla-russia.org/search.php?search_id=410379131

**Comment by hawkeye116477** [comment]
I checked DownloadGrab and appears that it works fine.

In case of Custom Buttons, link is wrong, I translated to English and got `No results were found for your search`.

**Comment by maxoku** [comment]
Right, Download Grab started to work again, weird 🤔 
I downloaded Custom Buttons today, let's see if I can put a direct link: 
[The newest](https://anonfiles.com/t6I5z2Ibo6/custom_buttons-0.0.7.0.0.16-fx-bootstrap_xpi) and [version I was using](https://anonfile.com/Q0dfc3s3nf/custom_buttons-0.0.7.0.0.4-fx-bootstrap_xpi).
And don't forget about search bar that stopped working completely.

If I remove Custom Buttons, restart and install again then it works, but after another restart buttons are gone again.
If I disable and enable search bar it works, but after restart it's broken again.
Maybe that has something in common with `Restore customizable toolbar for overlay extensions` that is in the change log?

**Comment by maxoku** [comment]
Do those links work? Have you found out anything?

**Comment by InvisibleManX** [comment]
I can confirm the broken search bar problem. 

It actually behaves in a very weird way. I reported it with details in the new opened bug issue thread: [https://github.com/MrAlex94/Waterfox/issues/1686](https://github.com/MrAlex94/Waterfox/issues/1686)

> Maybe that has something in common with `Restore customizable toolbar for overlay extensions` that is in the change log?

It really might be the case.

**Comment by maxoku** [comment]
@hawkeye116477 ?

**Comment by hawkeye116477** [comment]
Links works, submitted PR with workaround.

**Comment by maxoku** [comment]
Thanks for the answer and making the patch. Can I somehow manually put it somewhere to test if it works?

**Comment by maxoku** [comment]
Oh I find the proper file: \browser\omni.ja -> chrome\browser\content\browser\customizableui\toolbar.xml
After replacing it with the patched one I repeated the procedure with removing extension, restart and installing it again.
Seems to work. Custom buttons stays on toolbar after restarting. Thanks again for fixing.
