### ISSUE TITLE
Current 2020.07.1 gets a broken search bar if you remove the Waterfox Home Page button from the toolbar

### ISSUE THREAD

**Issue by InvisibleManX** [MrAlex94/Waterfox#1686]
**UPDATE!**

I found what is the cuase of the bug I'm describing below in this post!

Go to "Customize", and hit "Restore Defaults" button there. The bug will be gone.

Then go and simply remove from the toolbar the **"Waterfox Home Page" button**, and everything is broken again, once you restart your browser, or try opening a new window and try to use the search bar in it.

==========

**Describe the bug**

Search bar doesn't work. If you type something there and hit enter, it doesn't work, and it also doesn't show options for additional search engines when the "magnifying glass" button is clicked.

I mean using the browser with search settings set to "Add search bar in toolbar".

It doesn't even work without addons and in a safe mode. But it worked before the recent update on all pervious versions.

**Important**

If you switch between options "Use the address bar for search and navigation" and "Add search bar in toolbar", the problem **temporarily** fixes itself, but if you open a new private (or even a regular) window, then in that window it stops working again!

If you restart a browser it's broken again. If you create new windows (especially private ones) it's broken again.

**To Reproduce**

Go to "Customize", and hit "Restore Defaults" button there. Then go and simply remove from the toolbar the **"Waterfox Home Page" button**.

Restart the browser, try to search in the search bar, by typing something there and hitting Enter. 

If the search bar isn't present, first change the search setting to ""Add search bar in toolbar". It's also probably better to restore search engines settings to default. 

Then restart a browser fully (if you don't, the search bar will temporarily work). 

Try it in the current window, or try to create a private window.

Type something in the search bar, and it if you press Enter button on your keyboard it won't search anything. It also won't show any other search engines there as options to search with them.

**My configuration** 
 - Device: PC
 - OS: Windows 7
 - Version: Current 2020.07.1

**Comment by InvisibleManX** [comment]
By the way, I see the `Restore customizable toolbar for overlay extensions` in the change log.

I suspect that it might be the cause of this new bug. It probably wasn't tested before this update simply because not many people use the separate search bar option.

**Comment by RPYoshi** [comment]
I use the seperate search bar myself, I can confirm @InvisibleManX is correct in his assessment of the bug report. Everything is reproducible on my end.

P.S. On the waterfox.net homepage it shows the browser with a search bar!

My configuration:
- Device: PC
- OS: Windows 10
- Version: Current 2020.07.1 (64-bit)

**Comment by maxoku** [comment]
I wonder what `Restore customizable toolbar for overlay extensions` really means and how it affects the browser?
Interesting that the search bar appears to be a build in overlay extension.
And how it's possible that they didn't notice that it broke the search bar? Is it disabled by default that they don't check it? I always had it enabled by default from when it started to exist in Firefox.
An extension not working is one thing but if something native stops to work without devs noticing it's very disturbing.

**Comment by hawkeye116477** [comment]
Search bar is working fine for me.

**Comment by maxoku** [comment]
That's even more disturbing.

**Comment by InvisibleManX** [comment]
> 
> 
> Search bar is working fine for me.

Are you sure you're reproducing it properly? Read my explanation of the bug in detail in the main post. I'm talking about a separate search bar, not the way you can search by typing into the address bar. 
And if you change that setting to enable the separate search bar, it might look working, but only until you either open a new window and try to search in it, or restart your browser.

Did you try it with all extensions addons disabled, in a safe mode?

**Comment by InvisibleManX** [comment]
**I found what the cuase of the bug!** 

Go to "Customize", and hit "Restore Defaults" button there. 

The bug will be gone. 

Then go and simply remove from the toolbar the "Waterfox Home Page" button, and everything is broken again, once you restart your browser, or try opening a new window and try to use the search bar in it.

**Comment by hawkeye116477** [comment]
@InvisibleManX Yes, I also mean separate search bar.

Update: Ok, so removing buttons from toolbar causes that problem.

**Comment by InvisibleManX** [comment]
@hawkeye116477 yes, read my previous comment I just left. I found out what's causing the bug.

**Comment by maxoku** [comment]
Facepalm, I removed "Waterfox Home Page" button from toolbar, I use a better custom buttom for that.
It's absurd, what was changed so much to case that?

Edit: It fixed the search bar, but Custom Buttons still doesn't work.

**Comment by InvisibleManX** [comment]
@maxoku I'm really confused myself! How is that even related to that... 

So apparently your other problems you described in your opened issue thread are related to the same issues.

You probably should edit your main post, adding this extra info we discovered here, linking to my thread.

This is very frustrating, because I don't like to clutter my toolbars with unnecessary buttons like that Home button, and this bug is forcing me to keep it there. 

I hope it will be fixed soon. :)

**Comment by maxoku** [comment]
Well, button itself isn't a big problem to me while I can just hide with a css. Problem is that it didn't help with Custom Buttons, so I don't know if it's related. There might be more bugs lurking in that new update.

**Comment by InvisibleManX** [comment]
@maxoku Oh, that doesn't sound good. So the update is really bugged... :(

**Comment by InvisibleManX** [comment]
Wow, the search bar stops working after a browser restart, even if you simply move that Home button into some other place on the tool bar, like to the right of the search bar! 

How does its position affect it?!

**Comment by RPYoshi** [comment]
I did some testing and found the following. I currently have these in my toolbar "Waterfox Home Page | Downloads | Bookmarks | Library | extensions"

Steps to get working:
1. Open new browser session (browser restart)
2. Search doesn't work!
3. Customize... toolbar (Don't need to change anything)
4. Click Done at bottom right
5. Search bar works again!

**Comment by maxoku** [comment]
As I tested seems that hawkeye's patch fixed the problem for both search bar and Custom Buttons.

**Comment by InvisibleManX** [comment]
@maxoku How do I use that patch, before the official next Waterfox update?
