### ISSUE TITLE
User Agent Switcher causes pdf's to take sometimes minutes to open

### ISSUE THREAD

**Issue by rebop** [MrAlex94/Waterfox#1687]
**Describe the bug**
User Agent Switcher causes Classic 2020.07 and 2020.07.1 to take minutes to open a pdf.

**To Reproduce**
Install UAS https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/
Close and reopen Classic
Open a group of tabs - 20-25 not uncommon for me at all.
Try to open a pdf. A good example is: https://cam.start.canon/en/C004/manual/c004.pdf

**Expected behavior**
pdf opens as any tab in a timely manner. With UAS disabled, or better yet removed, it does.

**My configuration** 
2 laptops
Win 10 and Win 7
Classic 2020.07.1

**Additional context**
Been using User Agent Switcher for quite some time. 2020.07 with UAS running in CLassic causes pdf files to sometimes take minutes to open. With UAS disabled, or better yet removed, it functions as expected. Current does not have the issue.

**Comment by rebop** [comment]
I have tried other User Agent Switchers with similar results. I now believe that there is something new in Waterfox Classic that is conflicting with agent switchers in general .Would appreciate someone looking into it.

Just noticed your entry hawkeye. Will take a look at it. Thanks.

**Comment by rebop** [comment]
Actually, this is Classic only, so I do not think that would apply.

**Comment by hawkeye116477** [comment]
@rebop I referenced that by mistake.
