### ISSUE TITLE
Waterfox no option to accept risk if security certificate expired

### ISSUE THREAD

**Issue by Telmesomething** [MrAlex94/Waterfox#1690]
Waterfox refuses connection if security certificate expired. Other browsers such as Firefox or (God forbid) Internet Explorer include the option to accept the risk and continue to the site. There is no such option on Waterfox Classic. 

**To Reproduce**
1. Go to https://forum.videolan.org/
2. Click on Advanced when the warning appears

There is no option to accept the risk of connecting to the site.

**Expected behavior**

There should be an option to accept the risk as per the screenshot taken on Firefox. 

**Screenshots**

![Image00002](https://user-images.githubusercontent.com/33827636/89098160-4eb9ea80-d3e5-11ea-927a-c8c23f900e41.jpg)

![Image00001](https://user-images.githubusercontent.com/33827636/89098167-59747f80-d3e5-11ea-8878-72ad497c5e68.jpg)

**My configuration** 
 - Device: Windows PC
 - OS: Windows 8.1
 - Version: Waterfox Classic 2020.07.01

**Additional context**

**Comment by hawkeye116477** [comment]
Really weird, I have option to add exception.

**Comment by reallyuniquename** [comment]
That's actually [expected](https://tools.ietf.org/html/rfc6797#section-12.1) behaviour.

But if you want to bypass that you need to close Waterfox and rename `SiteSecurityServiceState.txt` in your profile folder.

**Comment by Telmesomething** [comment]
>Really weird, I have option to add exception.

That sounds odd. But fortunately the site has updated their security certicate today so it's no longer an issue.

**Comment by Telmesomething** [comment]
>That's actually expected behaviour.

>But if you want to bypass that you need to close Waterfox and rename SiteSecurityServiceState.txt in your profile folder.

That's a bit drastic isn't it? It's 55KB's worth of sites I've visited in the past and I wouldn't want to disable security for them which I assume is what would happen. 

But hawkeye116477 mentioned that he/she has the option to add an exception so I guess I'll have to ditch this profile and create a new one.

**Comment by reallyuniquename** [comment]
You can edit that file manually and reset security state for specific sites.

Like I said it's intended behaviour, you are not supposed to bypass that kind of security warning. Your issue is with owners of `forum.videolan.org` and the way they configured their HSTS/SSL. It has nothing to do with Waterfox.

>hawkeye116477 mentioned that he/she has the option to add an exception

Because he either never visited that site or its security state has expired.
