### ISSUE TITLE
Classic 2020.07.1 (64-bit) Web pages still broken

### ISSUE THREAD

**Issue by sutex** [MrAlex94/Waterfox#1691]
Still unable to have the page load my saved login and see the page as been logged in
in https://robertsspaceindustries.com/spectrum/community/SC

**Comment by hawkeye116477** [comment]
So it's duplicate of #1656. Opening same issue over and over again rather won't help...

**Comment by Squall-Leonhart** [comment]
seems to be a user profile issue, can login just fine to RSI.

**Comment by sutex** [comment]
> 
> 
> seems to be a user profile issue, can login just fine to RSI.

Ok, But Ive tried with all addon disabled and still the same issue , where another browser I have no problems, so a user profile issue?

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/issues/1656
