### ISSUE TITLE
hcaptcha fails to load/complete on Waterfox classic, possibly CSP related

### ISSUE THREAD

**Issue by dorkulon** [MrAlex94/Waterfox#1694]
hCaptcha, as used on e.g. [Nexus Mods](https://users.nexusmods.com/auth/sign_in), shows "Rate limited or network error. Please retry." upon load on Waterfox 2020.07.01. Clicking the "I'm a human" button causes animation to start, but the captcha never succeeds or fails.

The console shows several suspicious things, possibly related to the seemingly never-ending CSP saga (e.g. [this](https://bugzilla.mozilla.org/show_bug.cgi?id=866522))

Content Security Policy: Ignoring “https://assets.hcaptcha.com” within script-src: ‘strict-dynamic’ specified (unknown)
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified (unknown)
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified (unknown)
[...]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hcaptcha.com/checksiteconfig?host=users.nexusmods.com&sitekey=75161fda-5ac6-43fc-8c59-f02058a4b13b&sc=1&swa=1. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://hcaptcha.com’).  (unknown)

hCaptcha has a [demo page](https://accounts.hcaptcha.com/demo) which exhibits the same behavior, with a much more minimal set of JS.

**Comment by hawkeye116477** [comment]
Waterfox Current or Classic?

Anyway, Nexus Mods and demo page works fine on Classic and Current.

**Comment by dorkulon** [comment]
Ugh, this bug is invalid; their captcha checks the referrer for some reason. Not waterfox's fault.
