### ISSUE TITLE
Waterfox Search Bar No Longer Working With StartPage

### ISSUE THREAD

**Issue by Petros606** [MrAlex94/Waterfox#1695]
Waterfox July 2020 version for Windows. Waterfox search bar set in options for the search engine StartPage, but entering a search there will only take you to the StartPage homepage, where you will have to again type in what you are searching for.

To reproduce: Set Waterfox option for search bar to StartPage, Type in a search topic. Press enter or click the search arrow, and you will only be brought to the StartPage homepage, not the search results.

You should be getting the search results without needing to again type in what you are searching for at the StartPage homepage.

If I'm not mistaken, this began on August 1, 2020. 

I have of course tried clearing cookies and cache, but still not working correctly.

**Comment by Petros606** [comment]
Disabling add-ons and creating new profile did not fix the issue.

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/86777ac0019adedbd5ed51c9c329cf6ce3f136e8

I will re-open if not, but this should fix the issue.

**Comment by Petros606** [comment]
Problem appears to be fixed. No longer going to StartPage Homepage and now getting search results as expected.

**Comment by Petros606** [comment]
Actually I take that back, but it may be StartPage that has the problem:

<img src="https://i1.lensdump.com/i/jbexpD.png" alt="jbexpD.png" border="0" />


I have no clue what's going on here. Looks to me like they're trying to force me to use their homepage but they're saying it's an error.

**Comment by MrAlex94** [comment]
On macOS, searching with StartPage as default works perfectly. Very strange 🤔

**Comment by Petros606** [comment]
Working okay today. May have been a glitch on their end?

Look at that error page again:

"Many thanks for your patience and understanding."
