### ISSUE TITLE
Waterfox Classic self-destructs by automatic update on Debian Stretch

### ISSUE THREAD

**Issue by he29-net** [MrAlex94/Waterfox#1705]
**Describe the bug**
Today I got a prompt to "restart and restore" Waterfox to finish an update to new version. After Waterfox closed, however, it did not start again. When running it from command line, I found out that it is a glibc version issue:
```
XPCOMGlueLoad error for file /home/martin/programy/waterfox/liblgpllibs.so:
/lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.27' not found (required by /home/martin/programy/waterfox/liblgpllibs.so)
Couldn't load XPCOM.
```

**To Reproduce**
Use Waterfox Classic on Debian Stretch and have automatic Waterfox updates enabled.

**Expected behavior**
Automatic update should either finish successfully or fail safely. It should not result in a broken state that ordinary users cannot fix.

**My configuration**
 - Device: PC
 - OS: Debian Stretch
 - Version: Classic 2020.07.1

**Comment by hawkeye116477** [comment]
That's already known problem. As alternative you could use one of my packages => https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage, portable AppImage or deb.

https://github.com/MrAlex94/Waterfox/issues/1525, https://github.com/MrAlex94/Waterfox/issues/1631

**Comment by he29-net** [comment]
I know the glibc problem is a known issue, I solved it simply by downgrading to an older version for now.

What I'm getting at in this bug report is the upgrade process itself. System requirements will change eventually, Waterfox clearly can't support the old glibc versions forever. But some of the LTS distros can last a long time, so this issue could occur again in the future, even when glibc requirements are rised intentionally.

Ideally Waterfox should check the glibc version requirements _before_ the upgrade takes place, and if the system glibc is too old, abort the upgrade and notify the user, rather than leaving the Waterfox install broken.

**Comment by MrAlex94** [comment]
> Ideally Waterfox should check the glibc version requirements before the upgrade takes place, and if the system glibc is too old, abort the upgrade and notify the user, rather than leaving the Waterfox install broken.

I agree. Unfortunately the update system is rather rudimentary. Mozilla have improved it, but that is in newer versions unfortunately. I'm trying not to change the build system for `Classic` much - so hopefully won't break things. I'll close this for now, but I am aware of the strange requirements.
