### ISSUE TITLE
Cannot copy Discord message links or IDs to clipboard

### ISSUE THREAD

**Issue by sonofevil** [MrAlex94/Waterfox#1706]
So, Discord in browser has its own scripted menues for copying message links and IDs. When I click the respective button however, nothing happens. The link or ID isn't copied to clipboard. Pasting from clipboard just yields its old contents. 

This only happens in Waterfox (waterfox-current-kpe 2020.07.2.1-0 for Arch Linux), not in Firefox or in Chrome. The problem persists in safe mode.

Console reveals the following error:

`document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.`

**Comment by hawkeye116477** [comment]
Same problem is on Classic also.
