### ISSUE TITLE
Create an official AppImage for Waterfox

### ISSUE THREAD

**Issue by SmootheSmooth** [MrAlex94/Waterfox#1707]
Hello developer,

can you create an AppImage for Waterfox? Then it runs on almost all Linux distributions.

Here is more information about AppImage.
https://appimage.org/

Here's why I like it.

Very easy as a user to run the software. It feels very similar to running it on an Android device with apk file. But without installation process, find even better than the Android method.

Use the latest version of the software or if there were problems with the new version, e.g. bugs. I can use the old version, just use the older AppImage version.

**Comment by hawkeye116477** [comment]
There was already that discussion (https://github.com/MrAlex94/Waterfox/issues/127) and that will rather never happen. MrAlex94 haven't time to do that.

However unofficial packages blessed by AppImage format creator are available => https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage#downloading-and-installing-appimage-packages and they have even better compatibility than official tarball (built on CentOS 7, glibc 2.17). Problem is only with updates, cuz they must be manually downloaded from website, there is a way to also use special AppImageUpdater, but on OBS there is some problem that causes „Signature validation problem, not signed" errors. Also update window isn't patched, so it's checks only for official updates.

Small update: Now I'm using own xml hosted on GitHub Pages, so it points to updates of AppImages, but it's still not ideal, cuz I must manually bump it and AppImages are usually automatically rebuild when there are new versions of depends and updates currently are only manual.
