### ISSUE TITLE
Make complete privacy for Waterfox (no automatic external server connection without asking the user)

### ISSUE THREAD

**Issue by SmootheSmooth** [MrAlex94/Waterfox#1708]
Hello developers,

I use Waterfox (version: 202020.07.1) on my Windows 7 and Linux PC.

But the problem is, when I start Waterfox for the first time it automatically connects to http://detectportal.firefox.com/success.txt

and when I go to settings it automatically connects to other external servers. It connects to your Waterfox website and also downloads the blocker list because of this content blocking feature of Mozilla. In general I can't just remove this content blocking feature from Mozilla.

With Wireshark you can check.
https://www.wireshark.org/

Unfortunately Waterfox is not lightweight and not clean. It is not complete for privacy and connects automatically to external servers without asking the user.

There is no easy way for the user to disable it immediately. There is also a general lack of a "setup" process when users start Waterfox for the first time.

The normal user usually thinks that browsers usually only connect to external servers when the user enters something in the search bar or has enabled the automatic update function in the settings.

**Comment by hawkeye116477** [comment]
> It is not complete for privacy

As I know it wasn't mean to be replacement for Tor Browser.


> detectportal.firefox.com is used to detect captive portals on public wifi networks to be able to redirect you to their logon screen, so you don't just get page loading errors in firefox (set network.captive-portal-service.enabled to false in about:config in order to disable that feature).

**Comment by MrAlex94** [comment]
GitHub Issues isn't really the place for discussions.

If you want absolute privacy, use Tor. I have always said this. Waterfox is privacy conscious, but it won't come at the cost of an unusable user experience. I've disabled or removed everything that's unnecessary, but there comes a point where users will just stop using the browser if it doesn't work the way they are used to.

**Comment by SmootheSmooth** [comment]
Please reopen my github report.

I didn't say makes Waterfox completely anonymous using Tor Browser method/techniques.

Instead, create a Waterfox that does not automatically connect to external servers in the background, such as your Waterfox website, blocklist loading due to content blocking features of Mozilla and other Mozilla services, etc. 

A browser that is lightweight and clean, nothing more.

It should generally respect the privacy of its users. I think you have misunderstood my report.

On Linux and Windows there are browsers that do not automatically connect to external servers.

It only connects to external servers if enter something in the search bar and the automatic update search is activated.

**Comment by THEtomaso** [comment]
Thought I'd give Waterfox a try just now..
After installing, before I even got to launcing the browser itself, setup.exe immediately tried to connect to Google Cloud @ 34.120.208.123 !
For this reason, I uninstalled it.
Might give it another try, if these connection/privacy issues gets resolved.
