### ISSUE TITLE
Spot.im comments don't load anymore.

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1712]
**Describe the bug**
Little to add. At most I only get some blank throbbing nonsense.

**To Reproduce**
Visit any article on motorsport.com or nextbigfuture.com

**My configuration** 
Classic, Win 10

**Comment by hawkeye116477** [comment]
They require Shadow Root, which is for now only partially implemented, so you'll need to wait maybe even few months to have that fixed. If you don't want to wait, then use WF Current.

**Comment by mzso** [comment]
> 
> 
> They require Shadow Root, which is for now only partially implemented, so you'll need to wait maybe even few months to have that fixed. If you don't want to wait, then use WF Current.

It feels like a losing battle. Ever more websites seems to be misbehaving or utterly broken with WF classic. Current is not compatible with XUL addons, since pretty much everything they rely on was removed.
I wish there was a way of keeping my addons and browsing normally...

**Comment by hawkeye116477** [comment]
> Current is not compatible with XUL addons, since pretty much everything they rely on was removed.

So how my Classic Sidebar (formerly All-in One Sidebar) works on Current? It's compatible with XUL addons, but unfortunately some changes are required and seems that most authors of that extensions doesn't want to deal with them anymore.
I suspect that many extensions could be ported, the only problem is the lack of volunteers...

> It feels like a losing battle. Ever more websites seems to be misbehaving or utterly broken with WF classic

Well, there's always something that can be done. I recently added one thing, which fixed problem with one site from reddit report and probably some others which uses that. More fixes will be probably for next update. 

There is one positive, in case of domains from my country, all works well, they don't need to use any new things.

**Comment by InvisibleManX** [comment]
Yes, a lot of sites just don't work or work really slowly in Classic. 
I was forced to switch to Current, and overall it was a good experience. 

I was lucky to restore the majority of most important for me functionality from addons that I always used in Classsic. 
I found some addon alternatives, edited a few things in `about:config` and adjusted a few things with `userChrome.css`

**Comment by mzso** [comment]
[**@hawkeye116477**](https://github.com/hawkeye116477) commented on [2020. aug. 14. 10:43 CEST](https://github.com/MrAlex94/Waterfox/issues/1712#issuecomment-673963710 "2020-08-14T08:43:16Z - Replied by Github Reply Comments"):
> They require Shadow Root, which is for now only partially implemented, so you'll need to wait maybe even few months to have that fixed. If you don't want to wait, then use WF Current.

It has been months. Is it even still planned?

**Comment by mzso** [comment]
[**@InvisibleManX**](https://github.com/InvisibleManX) commented on [2020. aug. 18. 19:56 CEST](https://github.com/MrAlex94/Waterfox/issues/1712#issuecomment-675626433 "2020-08-18T17:56:37Z - Replied by Github Reply Comments"):
> Yes, a lot of sites just don't work or work really slowly in Classic.  
> I was forced to switch to Current, and overall it was a good experience.
> 
> I was lucky to restore the majority of most important for me functionality from addons that I always used in Classsic.  
> I found some addon alternatives, edited a few things in `about:config` and adjusted a few things with `userChrome.css`

Out of curiosity, what did you manage to replace (with what?), and what did you need to let go?

**Comment by hawkeye116477** [comment]
> It has been months. Is it even still planned?

Yes. https://github.com/MrAlex94/Waterfox/issues/1790#issuecomment-717192447

**Comment by InvisibleManX** [comment]
> Out of curiosity, what did you manage to replace (with what?), and what did you need to let go?

@mzso 
I didn't really use many essenstial addons, but I had to let go of "Tab Mix Plus", but I managed to get back 90% of the functionality I was using. And all other addons, including adblocking ones do have good versions that work just fine on Current.

Instead of "Tab Mix Plus" I installed these two addons: 
"Select After Closing Current" by jingyu9575
"Undo Close Tab" by Manuel Reimer
So, now I have an easy way to undo closed tabs (and see a list of most recently closed ones) and also after closing a tab, the last selected one is getting automatically selected. 

Everything else is cosmetic, can be found by google, and adjusted via editing the `userChrome.css` file.

**Comment by mzso** [comment]
@InvisibleManX 
I'll check them out, thanks.

**Comment by mzso** [comment]
[**@InvisibleManX**](https://github.com/InvisibleManX) commented on [2020. nov. 12. 03:41 CET](https://github.com/MrAlex94/Waterfox/issues/1712#issuecomment-725791751 "2020-11-12T02:41:11Z - Replied by Github Reply Comments"):
> > Out of curiosity, what did you manage to replace (with what?), and what did you need to let go?
> 
> [@mzso](https://github.com/mzso)  
> I didn't really use many essenstial addons, but I had to let go of "Tab Mix Plus", but I managed to get back 90% of the functionality I was using. And all other addons, including adblocking ones do have good versions that work just fine on Current.
> 
> Instead of "Tab Mix Plus" I installed these two addons:  
> "Select After Closing Current" by jingyu9575  
> "Undo Close Tab" by Manuel Reimer  
> So, now I have an easy way to undo closed tabs (and see a list of most recently closed ones) and also after closing a tab, the last selected one is getting automatically selected.
> 
> Everything else is cosmetic, can be found by google, and adjusted via editing the `userChrome.css` file.

I also decided to take the leap. I had horrible performance and daily out of memory events for a good while now, apart from the non-functioning websites. Not sure how much of it was related to the dated codebase and how much were (in part also dated) addons.

It's remarkably smoother now 83b10. And I could retain a [number of the most useful old addons](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions/), because someone updated them. Also, Custom Buttons [from elsewhere](https://forum.mozilla-russia.org/viewtopic.php?pid=783406#p783406).
The biggest loss is multi-rows tabs and other Tab mix plus features, searching bookmarks and jumping to its location in the bookmarks folder tree.
And probably the most annoying so far: drag and drop and sending text to the urlbar. Starting with FF58 the urlbar stupidly started to load everything as soon as you drop it. So you can't drop and edit, add a keyword, etc. And the addon that made urlbar usage even more effective by allowing me to send text to it ([Simplify Awesomebar](https://web.archive.org/web/20171115135855/https://addons.mozilla.org/en-US/firefox/addon/simplify-awesome-bar/)) broke.

**Comment by InvisibleManX** [comment]
> And probably the most annoying so far: drag and drop and sending text to the urlbar. Starting with FF58 the urlbar stupidly started to load everything as soon as you drop it

@mzso 
Whatever do you mean by that? Could you elaborate?

Because, I never experienced any pages actually auto-loading past FF58. 

But maybe you mean auto-filling / auto-completing of url based on suggestions from a dropdown list? 

If yes, then it can be solved: 

Go to `about:config` then search for and change `browser.urlbar.autoFill` to false. 

This will remove the autocomplete but keep the suggestions.

> 83b10

Wait. I thought we were talking about switching to Waterfox Current. And you seem to talk about Firefox now.

**Comment by mzso** [comment]
@InvisibleManX drag any highlighted text from a webpage to the urlbar. FF will auto load it.

FF current, I see little point in WF current. But it also should be affected. Not sure if the setting to disable this is retained. (It's not auto fill)

**Comment by InvisibleManX** [comment]
@mzso 

There are other things like: 

[https://chirale.org/2019/05/19/disable-search-and-autocomplete-on-url-bar-of-firefox/](https://chirale.org/2019/05/19/disable-search-and-autocomplete-on-url-bar-of-firefox/)

In any case, I'm still not sure I understand your problem. 

I never drag any text from a webpage to the urlbar, I simply select, copy it (usually with Ctrl+C) and then I paste it where I need it.

As for the point of WF current... It's based on Firefox ESR 78 currently, and those are more stable releases of Firefox. And this way I don't have to see those questionable innovations of most recent Firefox for a longer time.

**Comment by mzso** [comment]
@InvisibleManX 
Thanks for the suggestions. Though these don't really help. Keyword.enabled is somewhat relevant, but it only disables the default search engine. So I get random nasty websites resolved instead.

> I never drag any text from a webpage to the urlbar, I simply select, copy it (usually with Ctrl+C) and then I paste it where I need it.

That's inefficient. D&D is a little better. (Even if it weren't I would never want every friggin thing to be resolved that's dopped in the urlbar. I have the tab-bar for that.)
In truth the combination of simplify awesomebar and stay-open menu was I used for several years, because it was a lot superior.
Select text press hotkey, then. And now the text is in the urlbar with the caret in front and a space between so I only need to type the keyword for a search. Or alternatively, middle click multiple items in the urlbar results (the dropdown stays open), which open in the background.

Nowadays this is disrupted in many places. I find myself copy pasting all the time and ctlr+tabbing between tabs, and opening new tabs. (Often the urlbar doesn't get focus on a new tab which is very annoying) All superfluously compared to before. 

You can try them in WF classic if you're curious. (Via classic addons archive)
