### ISSUE TITLE
Please keep Waterfox at Mac OSX 10.11 or less

### ISSUE THREAD

**Issue by pixturesk** [MrAlex94/Waterfox#1714]
I notice with the new update to 2020.07.2, the minimum system requirements for Waterfox Current have been raised to Mac OSX 10.10, Now that Firefox version 79, only supports Mac OSX 10.12+, I urge Mr. Alex to continue to support, as a maximum Mac OSX 10.11. Waterfox is the perfect replacement for FF, faster, more reliable, can continue to use all my FF extensions. Without Waterfox, this Mac user up to version 10.11 will have a serious problem finding another browser, I find the version of Safari that comes with 10.11 quite inferior to Waterfox. Thanks, Ken.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
According to [future branch](https://github.com/MrAlex94/Waterfox/tree/future) the next version will be based on Firefox 78 ESR engine.

**Comment by pixturesk** [comment]
Yes but that is only for another year as I see it.

**Comment by MrAlex94** [comment]
Issues isn't the place for discussions.

We'll see what will happen when we need to cross that bridge and why the OS version was increased? Simple change? Sure, we'll revert. Anything more complex and probably not.
