### ISSUE TITLE
Immediate crashing on Windows 10 Enterprise 2004, within .14 seconds

### ISSUE THREAD

**Issue by 514guy** [MrAlex94/Waterfox#1718]
Waterfox Classic 56.3.0.7528 is exiting on startup, with exit status 322122547. Event viewer shows:

Problem signature:
P1: waterfox.exe
P2: 56.3.0.7528
P3: 5f32945d
P4: StackHash_ec17
P5: 0.0.0.0
P6: 00000000
P7: c0000005
P8: PCH_22_FROM_unknown+0x0000000000000000

This crash is happening on all recent versions, and portable. All other browsers are unaffected.
I attached waterfox.exe to a debugger, and the result was [https://imgur.com/a/uG8qKQe](url)

System info is:

	<OSVersionInformation>
		<WindowsNTVersion>10.0</WindowsNTVersion>
		<Build>19041</Build>
		<Product>(0x4): Windows 10 Enterprise</Product>
		<Edition>Enterprise</Edition>
		<BuildString>19041.450.amd64fre.vb_release.191206-1406</BuildString>
		<Revision>450</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X64</Architecture>
		<LCID>1033</LCID>

I realize there's not much to go on, here, but any help would be appreciated.

**Comment by hawkeye116477** [comment]
In case of Windows 10 1909, no crash, maybe it's hardware related or that problem only appears on 2004.

**Comment by 514guy** [comment]
In my case, it was a Comodo HIPS issue. Closing this, now.
