### ISSUE TITLE
Imgur

### ISSUE THREAD

**Issue by nu8** [MrAlex94/Waterfox#1722]
Imgur seems to be broken with Waterfox - example link:

https://imgur.com/gallery/XNKh9kH

I figured it was a user agent bug - but even with Firefox 79 useragent it is still broken

**Comment by nu8** [comment]
Workaround:

https://imgur.com/beta/disable

**Comment by hawkeye116477** [comment]
In case of Waterfox Current it should be solved after merging #1719 (probably next update).

**Comment by kazerniel** [comment]
Imgur galleries are broken for me too on Waterfox Classic 2020.07.2. For a moment the header loads, then it all switches to an empty grey page. The preview images and videos look fine on the front page, just the galleries are broken.

**Comment by highnrgappalachian** [comment]
Still not fixed on latest Classic.
