### ISSUE TITLE
Screen flashes white when refreshing about:home

### ISSUE THREAD

**Issue by vachan-maker** [MrAlex94/Waterfox#1723]
**Describe the bug**
White flash occurs when refreshing about:home

**To Reproduce**
1. Use a dark theme
2. Go to about:home
3. Press Ctrl+R or refresh button or home button
4. See a white flash

**Expected behavior**
The white flash should not occur.

**My configuration** 
 - Device: Dell Inspiron Laptop
 - OS: Windows 10
 - Version: Waterfox current 2020.07.2.1 (64-bit)

**Comment by hawkeye116477** [comment]
It's probably https://bugzilla.mozilla.org/show_bug.cgi?id=1408122.

**Comment by vachan-maker** [comment]
> 
> 
> It's probably https://bugzilla.mozilla.org/show_bug.cgi?id=1408122.

This issue is still in Firefox 79.0 and I did file a bug report in bugzilla
Link:

https://bugzilla.mozilla.org/show_bug.cgi?id=1653505
https://bugzilla.mozilla.org/show_bug.cgi?id=1603918
