### ISSUE TITLE
Gitlab.com - main content blank

### ISSUE THREAD

**Issue by c33s** [MrAlex94/Waterfox#1724]
**Describe the bug**

since today (it worked for me yesterday) most of the content of gitlab.com is blank. you see the base menu but no submenu and the main content is just a big white page.

- https://gitlab.com/explore
- https://gitlab.com/gitlab-org/gitlab-foss

tried:
- changing useragent has not helped
- switching to chromium made the site work again
- starting waterfox with a complete new profile (no addons) has the same result

**To Reproduce**

**Expected behavior**
normal webpage displayed

**Screenshots**
![2020-08-22 13_30_37- #  Projects · Explore · GitLab - Waterfox Classic  #](https://user-images.githubusercontent.com/649209/90955191-bb238900-e47b-11ea-946c-4003673f9d61.png)

**My configuration** 
 - Device: PC
 - OS: Win
 - Version: Classic 2020.07.2

**Comment by c33s** [comment]
issue on gitlab https://gitlab.com/gitlab-org/gitlab/-/issues/239357 with greasemonkey fix

**Comment by hawkeye116477** [comment]
Mozregression results:
Last bad: 2018-04-25 (e33e5049d9f35e16893f5ba4ec823f69f04972dd)
First good: 2018-04-26 (63a0e2f626febb98d87d2543955ab99a653654ff)

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=e33e5049d9f35e16893f5ba4ec823f69f04972dd&tochange=63a0e2f626febb98d87d2543955ab99a653654ff

**Comment by hawkeye116477** [comment]
@c33s GitLab now works great again.

**Comment by IanN-GH** [comment]
The particular bug is bug 1386840 along with pre-req of bug 1456435

**Comment by IanN-GH** [comment]
The particular bug is bug 1386840 along with pre-req of bug 1456435

**Comment by IanN-GH** [comment]
The particular bug is bug 1386840 along with pre-req of bug 1456435

**Comment by IanN-GH** [comment]
The particular bug is bug 1386840 along with pre-req of bug 1456435
