### ISSUE TITLE
Weather radar video fails to refresh even if use ctrl+F5

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1726]
**Describe the bug**
On this weather website the radar video is not refreshed at all. On chromium I can refresh it continuously.

**To Reproduce**

1. Go to https://www.idokep.hu/radar
2. Click on play button
3. refresh arbitrary long time later
4. observe the video staying the same. (Particularly timestamp in the corner)

(Time is in CET)

**Expected behavior**
Browser should load the latest updated video.

**Screenshots**
![kép](https://user-images.githubusercontent.com/4479090/90976093-81658780-e53a-11ea-9852-385096c28e3f.png)

It looks like this and it only appears if there's any sort of rain in the country

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: Classic 2020.07.02

**Additional context**
Video directlink: https://www.idokep.hu/idokepradar/public_radar_terkep.mp4
I doubt it works when it doesn't appear on the website.

**Comment by hawkeye116477** [comment]
Hmm, on Linux works fine, when I press ctrl+f5, video refreshes.

**Comment by mzso** [comment]
> 
> 
> Hmm, on Linux works fine, when I press ctrl+f5, video refreshes.

Here not even a browser restart is always successful for some reason. (Even though I have disk cache disabled and always had.)
