### ISSUE TITLE
Os x Lion Videos Do Not Play WF Classic 2020.07.02 & 2020.08

### ISSUE THREAD

**Issue by pjpreilly** [MrAlex94/Waterfox#1729]
The newest **Waterfox Classic** 2020.08 & 2020.07.2 on **os x Lion 10.7.5** does not play videos, as can be seen on youtube as well as 6abc.com. DRM widevine plugin crashes but no KP or browser crash.

NOTE: Testing in a VM will not reproduce the problem since the native OS seems to compensate......

**Comment by pjpreilly** [comment]
Who's looking into this @**[issue-label-bot](https://github.com/marketplace/issue-label-bot)**?

**Comment by efficientbaxter** [comment]
Still not working in 2020.10

Neither in current Youtube version nor in the old via one of the AddOns like [Good Old Youtube](https://addons.mozilla.org/en-US/firefox/addon/good-old-youtube/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search).

**Comment by pjpreilly** [comment]
Get it from **[here](https://github.com/aeiouaeiouaeiouaeiouaeiouaeiou/waterfox-osx/releases/tag/2020.10-osxfix-classic)**...

**Comment by efficientbaxter** [comment]
This is the error message in the debugger (no old YT AddOn) for this [Video](https://www.youtube.com/watch?v=1s587_qG8eg) as an example:

`Media resource https://r4---sn-h0jeenek.googlevideo.com/videoplayback?expire=1604287659&ei=SyifX6bSEpeRgQfLsojACg&ip=2003%3Ad3%3A8f39%3A3a00%3A9d30%3Abc68%3Ad8d2%3A5c82&id=o-AE7OLm404KVwWYDnXa3N0zD__m1JnRXs_8QD8-jb5ytL&itag=18&source=youtube&requiressl=yes&mh=rS&mm=31%2C26&mn=sn-h0jeenek%2Csn-4g5ednss&ms=au%2Conr&mv=m&mvi=4&pl=32&initcwndbps=1103750&vprv=1&mime=video%2Fmp4&gir=yes&clen=15779502&ratebypass=yes&dur=213.832&lmt=1542278408381420&mt=1604265997&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANGjkzuw-S1j1d3NG_KEMaFUXUMUPG_q2c-CKooloFFzAiApmXrkV7K_q0Ao5hPUSzOi9J6eiMTDIqpyPlrCFyrmTw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKk_EbUWygPaiiWisrYZUsiLjSTEg5jXnw44JE8yLJxrAiAjL3eH_fGqEq-16DM4ePZA9ENDKvD19e1P2Lv_VEFF_g%3D%3D&cpn=cZrSO-9tfmCnuIvn&cver=2.20201030.01.00&ptk=youtube_single&oid=9OOfqQJk9jMRqO7P3pjGWA&ptchn=U0rIMU3k_AsVA8d6N1B03w&pltype=content could not be decoded.  watch
Media resource https://r4---sn-h0jeenek.googlevideo.com/videoplayback?expire=1604287659&ei=SyifX6bSEpeRgQfLsojACg&ip=2003%3Ad3%3A8f39%3A3a00%3A9d30%3Abc68%3Ad8d2%3A5c82&id=o-AE7OLm404KVwWYDnXa3N0zD__m1JnRXs_8QD8-jb5ytL&itag=18&source=youtube&requiressl=yes&mh=rS&mm=31%2C26&mn=sn-h0jeenek%2Csn-4g5ednss&ms=au%2Conr&mv=m&mvi=4&pl=32&initcwndbps=1103750&vprv=1&mime=video%2Fmp4&gir=yes&clen=15779502&ratebypass=yes&dur=213.832&lmt=1542278408381420&mt=1604265997&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANGjkzuw-S1j1d3NG_KEMaFUXUMUPG_q2c-CKooloFFzAiApmXrkV7K_q0Ao5hPUSzOi9J6eiMTDIqpyPlrCFyrmTw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKk_EbUWygPaiiWisrYZUsiLjSTEg5jXnw44JE8yLJxrAiAjL3eH_fGqEq-16DM4ePZA9ENDKvD19e1P2Lv_VEFF_g%3D%3D&cpn=cZrSO-9tfmCnuIvn&cver=2.20201030.01.00&ptk=youtube_single&oid=9OOfqQJk9jMRqO7P3pjGWA&ptchn=U0rIMU3k_AsVA8d6N1B03w&pltype=content could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)  watch`

`Media resource https://r4---sn-4g5ednss.googlevideo.com/videoplayback?expire=1604287659&ei=SyifX6bSEpeRgQfLsojACg&ip=2003%3Ad3%3A8f39%3A3a00%3A9d30%3Abc68%3Ad8d2%3A5c82&id=o-AE7OLm404KVwWYDnXa3N0zD__m1JnRXs_8QD8-jb5ytL&itag=18&source=youtube&requiressl=yes&mh=rS&mm=31%2C26&mn=sn-h0jeenek%2Csn-4g5ednss&ms=au%2Conr&mv=m&mvi=4&pl=32&initcwndbps=1103750&vprv=1&mime=video%2Fmp4&gir=yes&clen=15779502&ratebypass=yes&dur=213.832&lmt=1542278408381420&mt=1604265997&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANGjkzuw-S1j1d3NG_KEMaFUXUMUPG_q2c-CKooloFFzAiApmXrkV7K_q0Ao5hPUSzOi9J6eiMTDIqpyPlrCFyrmTw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKk_EbUWygPaiiWisrYZUsiLjSTEg5jXnw44JE8yLJxrAiAjL3eH_fGqEq-16DM4ePZA9ENDKvD19e1P2Lv_VEFF_g%3D%3D&cpn=cZrSO-9tfmCnuIvn&cver=2.20201030.01.00&ptk=youtube_single&oid=9OOfqQJk9jMRqO7P3pjGWA&ptchn=U0rIMU3k_AsVA8d6N1B03w&pltype=content&fallback_count=1 could not be decoded.`

`Media resource https://r4---sn-4g5ednss.googlevideo.com/videoplayback?expire=1604287659&ei=SyifX6bSEpeRgQfLsojACg&ip=2003%3Ad3%3A8f39%3A3a00%3A9d30%3Abc68%3Ad8d2%3A5c82&id=o-AE7OLm404KVwWYDnXa3N0zD__m1JnRXs_8QD8-jb5ytL&itag=18&source=youtube&requiressl=yes&mh=rS&mm=31%2C26&mn=sn-h0jeenek%2Csn-4g5ednss&ms=au%2Conr&mv=m&mvi=4&pl=32&initcwndbps=1103750&vprv=1&mime=video%2Fmp4&gir=yes&clen=15779502&ratebypass=yes&dur=213.832&lmt=1542278408381420&mt=1604265997&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANGjkzuw-S1j1d3NG_KEMaFUXUMUPG_q2c-CKooloFFzAiApmXrkV7K_q0Ao5hPUSzOi9J6eiMTDIqpyPlrCFyrmTw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKk_EbUWygPaiiWisrYZUsiLjSTEg5jXnw44JE8yLJxrAiAjL3eH_fGqEq-16DM4ePZA9ENDKvD19e1P2Lv_VEFF_g%3D%3D&cpn=cZrSO-9tfmCnuIvn&cver=2.20201030.01.00&ptk=youtube_single&oid=9OOfqQJk9jMRqO7P3pjGWA&ptchn=U0rIMU3k_AsVA8d6N1B03w&pltype=content&fallback_count=1 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)  watch
Media resource https://r4---sn-4g5ednss.googlevideo.com/videoplayback?expire=1604287659&ei=SyifX6bSEpeRgQfLsojACg&ip=2003%3Ad3%3A8f39%3A3a00%3A9d30%3Abc68%3Ad8d2%3A5c82&id=o-AE7OLm404KVwWYDnXa3N0zD__m1JnRXs_8QD8-jb5ytL&itag=18&source=youtube&requiressl=yes&mh=rS&mm=31%2C26&mn=sn-h0jeenek%2Csn-4g5ednss&ms=au%2Conr&mv=m&mvi=4&pl=32&initcwndbps=1103750&vprv=1&mime=video%2Fmp4&gir=yes&clen=15779502&ratebypass=yes&dur=213.832&lmt=1542278408381420&mt=1604265997&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANGjkzuw-S1j1d3NG_KEMaFUXUMUPG_q2c-CKooloFFzAiApmXrkV7K_q0Ao5hPUSzOi9J6eiMTDIqpyPlrCFyrmTw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKk_EbUWygPaiiWisrYZUsiLjSTEg5jXnw44JE8yLJxrAiAjL3eH_fGqEq-16DM4ePZA9ENDKvD19e1P2Lv_VEFF_g%3D%3D&cpn=cZrSO-9tfmCnuIvn&cver=2.20201030.01.00&ptk=youtube_single&oid=9OOfqQJk9jMRqO7P3pjGWA&ptchn=U0rIMU3k_AsVA8d6N1B03w&pltype=content&fallback_count=1 could not be decoded.`

`Media resource https://r4---sn-4g5ednss.googlevideo.com/videoplayback?expire=1604287659&ei=SyifX6bSEpeRgQfLsojACg&ip=2003%3Ad3%3A8f39%3A3a00%3A9d30%3Abc68%3Ad8d2%3A5c82&id=o-AE7OLm404KVwWYDnXa3N0zD__m1JnRXs_8QD8-jb5ytL&itag=18&source=youtube&requiressl=yes&mh=rS&mm=31%2C26&mn=sn-h0jeenek%2Csn-4g5ednss&ms=au%2Conr&mv=m&mvi=4&pl=32&initcwndbps=1103750&vprv=1&mime=video%2Fmp4&gir=yes&clen=15779502&ratebypass=yes&dur=213.832&lmt=1542278408381420&mt=1604265997&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANGjkzuw-S1j1d3NG_KEMaFUXUMUPG_q2c-CKooloFFzAiApmXrkV7K_q0Ao5hPUSzOi9J6eiMTDIqpyPlrCFyrmTw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKk_EbUWygPaiiWisrYZUsiLjSTEg5jXnw44JE8yLJxrAiAjL3eH_fGqEq-16DM4ePZA9ENDKvD19e1P2Lv_VEFF_g%3D%3D&cpn=cZrSO-9tfmCnuIvn&cver=2.20201030.01.00&ptk=youtube_single&oid=9OOfqQJk9jMRqO7P3pjGWA&ptchn=U0rIMU3k_AsVA8d6N1B03w&pltype=content&fallback_count=1 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)  watch`

**Comment by efficientbaxter** [comment]
Reverted back to WF 2020.03.1 and above video plays fine.

**Comment by efficientbaxter** [comment]
> Get it from **[here](https://github.com/aeiouaeiouaeiouaeiouaeiouaeiou/waterfox-osx/releases/tag/2020.10-osxfix-classic)**...

@pjpreilly Hey, thank you, Phil, works like a charm!

**Comment by pjpreilly** [comment]
@efficientbaxter I've moved on to **[FF Legacy](https://parrotgeek.com/fxlegacy.html)**. Much faster & better supported.

**Comment by efficientbaxter** [comment]
@pjpreilly Well, thanks a million! Wasn't aware of that one.
