### ISSUE TITLE
[Classic] on signal.org/download, none of the clicks onto any of the buttons work

### ISSUE THREAD

**Issue by LeeBinder** [MrAlex94/Waterfox#1730]
**Describe the bug**
on [https://signal.org/download](https://signal.org/download/), none of the clicks onto any of the blue buttons work

**Expected behavior**
clicks should open corresponding new pages

**My configuration** 
 - Devices: Mac & PC
 - OS: Windows 10 1909/ macOS Mojave & Catalina, both latest
 - Version: Classic all latest versions up to 2020.08 in a clean new stock profile

**Additional context**
working fine in Current

**Comment by hawkeye116477** [comment]
From console: `window.customElements is undefined`, so that means that they are using webcomponents, which aren't fully supported in Classic yet and disabled by default, but seems that even enabling them doesn't help in that case.

**Comment by LeeBinder** [comment]
thanks hawkeye116477 for looking at this and laying out the context.

**Comment by hawkeye116477** [comment]
Mozregression results:

Last bad: 2018-12-11 (ac7f3beb633340c6b3fea25059e8b8aa52b5fc8a)
First good: 2018-12-12 (6f21533f643edc0729216fcc1a2fd6c1b638e536)

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=ac7f3beb633340c6b3fea25059e8b8aa52b5fc8a&tochange=6f21533f643edc0729216fcc1a2fd6c1b638e536

**Comment by LeeBinder** [comment]
Is there any chance webcomponents get fully supported in Classic any time soon, like with the .10 or .11 release?

**Comment by hawkeye116477** [comment]
@LeeBinder I don't think that will be that fast, cuz especially looks like I'm the only one who wants to do that and some of the parts Mozilla done for Servo only. Currently I'm waiting for UXP next turn, I'll see what they do and try to port that.

**Comment by LeeBinder** [comment]
OK, gotcha, and again thank you for sharing the context - so much easier to apprehend and relate in that manner 👍

**Comment by LeeBinder** [comment]
@hawkeye116477 is the following a webcomponents issue, too, or should I open a new issue?

On https://www.mediamarkt.de/de/search.html?query=usb, the content which should be to the right of the sidebar is displayed below it. It is displayed correctly in WF current.

**Comment by hawkeye116477** [comment]
@LeeBinder No, it's different problem. You should open a new issue.

**Comment by LeeBinder** [comment]
Ok thanks, will do. BTW, same issue with Firefox 56.0.2.

**Comment by LeeBinder** [comment]
or in other words, you gave up on it/ not getting fixed :(

**Comment by MrAlex94** [comment]
hawkeye116477 has been kindly providing compatibility updated for webcomponents. Unless they or someone else continues to do so, this won't be getting fixed "officially".

**Comment by LeeBinder** [comment]
OK, gotcha Alex.
