### ISSUE TITLE
[Waterfox current] [Feature Request] Vaapi Hardware acceleration

### ISSUE THREAD

**Issue by aquaspy** [MrAlex94/Waterfox#1731]
Well, not sure if Waterfox accepts feature suggestions, if this is something not cool or weird to post here, feel free to close the issue.

Recently, Firefox release the Firefox 80, which brings support to vaapi hardware acceleration on linux. This is one of the most waited feature on firefox, so it would be great to have that in waterfox current too!

I am not sure about how difficult is to add it, so if it is that much difficult, feel free to don't merge it.

The only thing I can do to help at this moment is posting the steps to activate the hardware acceleration, so here we go:

----------------------------------------------------------------------------------------------------------------------------------------------------------------
To use VA-API in xorg, set the environment variable MOZ_X11_EGL=1, enable these about:config presets: media.ffmpeg.dmabuf-textures.enabled, media.ffmpeg.vaapi.enabled, and set this about:config preset media.ffvpx.enabled to false.

To use VA-API in Wayland, set the environment variable MOZ_ENABLE_WAYLAND=1, enable these about:config presets: media.ffmpeg.dmabuf-textures.enabled, media.ffmpeg.vaapi.enabled, and set this about:config preset media.ffvpx.enabled to false.

Add to /etc/environment:

 MOZ_X11_EGL=1 or MOZ_ENABLE_WAYLAND=1

----------------------------------------------------------------------------------------------------------------------------------------------------------------

Thank you for making this great browser and don't feel pressure to do anything here, take this issue just as a suggestion.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1619523

Maybe developers can implement this in the next version of Current.

**Comment by aquaspy** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1619523
> 
> Maybe developers can implement this in the next version of Current.

It would be a very very great addition to Waterfox I think

But maybe it's better to wait for Firefox 81, which will come with hardware acceleration enabled by default in linux :)
