### ISSUE TITLE
Waterfox current 2020.08 web content follows GTK3 theme

### ISSUE THREAD

**Issue by DasHammett** [MrAlex94/Waterfox#1732]
**Describe the bug**
Current version of waterfox will render some websites according to current GTK3 theme. If theme is dark, website will adjust colors, ie, dark background with light font. I haven't found any option to not allow this behaviour.

I have seen this behaviour in 2 websites: web.whatsapp.com and www.twitter.com

**To Reproduce**
1. Go to www,twitter.com
2. Log in
4. See error --> Background is black with white font color

**Expected behavior**
Option to disallow this behaviour. I see the benefit during the night, but an option would be perfect for thos who do not want it.

**Screenshots**
![image](https://user-images.githubusercontent.com/13760961/91531074-7af55800-e90c-11ea-81f8-9eae44b25ea8.png)

**My configuration** 
 - Device: PC
 - OS: Linux
 - Version: Current 2020.08

**Comment by hawkeye116477** [comment]
It's not a bug, it's css feature, which some websites uses. 

> I haven't found any option to not allow this behaviour.

There is hidden option:

> If you have set privacy.resistFingerprinting to true, prefers-color-scheme preference is overridden to light.
> Alternately, users can create the numeric preference ui.systemUsesDarkTheme to override the default behavior and return light (value: 0), dark (value: 1), or no-preference (value: 2). (Any other value causes Firefox to return light.)

Source: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
