### ISSUE TITLE
Can't see anything on this page (help.ea.com/…) after loaded

### ISSUE THREAD

**Issue by nomosaic** [MrAlex94/Waterfox#1733]
environment: win7SP1 Waterfox Classic 2020.08.1 x64
I mean
https://help.ea.com/zh-tw/help/account/ordering-payment-information
Be blank webpage with Waterfox Classic browsing.

**Comment by hawkeye116477** [comment]
I can't reproduce that. Is that after signing?

**Comment by nomosaic** [comment]
> 
> 
> I can't reproduce that. Is that after signing?

No, needn't, just visit it. You can see it always blank.

**Comment by hawkeye116477** [comment]
@nomosaic Have you some addons installed? Could you copy all unprocessed information from `about:support`?

**Comment by nomosaic** [comment]
In about:config, set "dom.webcomponents.enabled" of the value to "false" should be able to handle the case.
This feature had also caused some other conditions before.

**Comment by hawkeye116477** [comment]
Ok, if enabling webcomponents broke that website, then it's not case for now. Webcomponents maybe some day will be fully implemented, but there is long way to do that.
