### ISSUE TITLE
Don't work site rozetka.ua

### ISSUE THREAD

**Issue by Viator76** [MrAlex94/Waterfox#1738]
Gentlemen, scripts do not work on this site, which is why the site is not fully loaded.
BUT, scripts work on the 78th chrome engine, as well as on 78esr firefox, please, if possible, add the following changes to the javascript engine.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll

**To Reproduce**
Go to site rozetka.ua
Scroll down...
See error (images add)

**Expected behavior**
SyntaxError: invalid regular expression flag s main.b2d1721db91b9373b2f7.js:1:36987
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll

**Screenshots**

ERROR
http://imglink.ru/show-image.php?id=e504d48688881ed25a2170f23d38ce4f
NORMAL
http://imglink.ru/show-image.php?id=dec47197db074044bccd6a6f2c3b1b35

**My configuration** 
 - Device: Notebook Asus K55V
 - OS: Windows 10 Pro 1909
 - Version: Classic 2020.08.1/Current 2020.08.1

![error](https://user-images.githubusercontent.com/70686252/92082384-2569f100-edcd-11ea-8a16-1d9adca0287a.png)
![norm](https://user-images.githubusercontent.com/70686252/92082386-26028780-edcd-11ea-8d44-8fc68a736f95.jpg)

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Works only on a clean profile if you refresh the page manually (Classic Portable).

![image](https://user-images.githubusercontent.com/69355938/92140840-4d337600-ee1a-11ea-9bad-9720192afd4e.png)

**Comment by Viator76** [comment]
The Rozetka website removed an unsupported option in its engine yesterday.
BUT they removed it, and how much will they use such an innovation?
Therefore, please add support for the new one from this link:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll
