### ISSUE TITLE
saved passwords and master password disappear

### ISSUE THREAD

**Issue by Waltraute** [MrAlex94/Waterfox#1739]
I am finding that all my old saved passwords--and the master password--disappear if I save a new login. I believe key3.db is the problem since I can recover my passwords (including the new one that triggered the issue) by restoring a backup of it. I have noticed this in the last two or three days.

**To Reproduce**
Create a login for a site and ask Waterfox to remember the login.

**Expected behavior**
The username and password should be added to the 'saved logins' list.

**My configuration** 
 - Device: HP Pavilion laptop
 - OS: Lubuntu 18.04 LTS
 - Version: Classic 2020.08.1

**Comment by hawkeye116477** [comment]
Are you sure that disappeared after saving new one password and not before? If you go to `about:config` and toggle `security.use_sqldb` to `true`, does that help?

**Comment by MrAlex94** [comment]
Since there has been no reply in a while - please re-open if necessary.
