### ISSUE TITLE
dom.webcomponents.enabled causes distorted layout on Wayback Machine

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [MrAlex94/Waterfox#1740]
- Set **dom.webcomponents.enabled** to **true** on **about:config**.
- Open the [archived page](https://web.archive.org/web/20071001024905/http://youtube.com/).

As a result the top panel becomes corrupted and unusable, the timeline goes into background layer of the page. Same thing happens on the latest version of Classic for Windows. Probably this caused by effect of an unfinished Shadow DOM implementation.

![2020-08-21_22-35-12](https://user-images.githubusercontent.com/69355938/92143006-57a33f00-ee1d-11ea-9141-a10aa24e7d1b.png)

**Comment by hawkeye116477** [comment]
So it's same problem as #1733. Maybe some day that will be fixed, but I think that can take few months.

**Comment by AM4Ryzen** [comment]
I think it'd be possible to introduce a list of sites for the browser to disable webcomponents on

**Comment by reallyuniquename** [comment]
Which sites require webcomponents to be enabled in the first place?
