### ISSUE TITLE
[Classic]stream player on live.bilibili.com not working

### ISSUE THREAD

**Issue by 117649** [MrAlex94/Waterfox#1741]
The player not loading the stream which version is 1.17.0 . I have to use re-director to trick the site to load an old player-1.11.0.js for it to work.

**Comment by hawkeye116477** [comment]
Check if toggling `javascript.options.streams` and `dom.streams.enabled` in `about:config` to `true` helps.

**Comment by 117649** [comment]
Great it works. But it some how force the player muted at load and I have to manually turn the audio on.
I do have the autoplay disabled maybe is because that.

**Comment by 117649** [comment]
@hawkeye116477 Sadly Its stop working just this fast. In some of the channel the player has been upgrade to version 2.0.3 and it says it can not fetch the video because network issue, And I found that the request has been forbidden by the some same origin policy. I'd like to know how to disable such policy.

**Comment by hawkeye116477** [comment]
`In some of the channel the player has been upgrade to version 2.0.3`

Can you give URL to that channels?

**Comment by 117649** [comment]
> 
> 
> `In some of the channel the player has been upgrade to version 2.0.3`
> 
> Can you give URL to that channels?

[https://live.bilibili.com/22349508](url) For example this one and maybe all of them when you see this. 
It seems they're rolling out the upgrade for different channel at different time, I do saw some even still stay at v1.17.0 this maybe due some reason on the site's side.

And after this much time almost al the same origin errors are gone by it self, It may also be on the bilibili's end but I do confirm that while Waterfox has the CORS problem other browser don't (FF dev 81b1 & Edge chrome ver) so it still has something not right for WF.

**Comment by 117649** [comment]
@hawkeye116477 Now is the CORS break things. It keep saying something like "Reason: CORS header 'Access-Control-Allow-Origin' does not match 'https://live.bilibili.com'"
