### ISSUE TITLE
Request: Support the Vista extended kernel (Only two simple fixes needed)

### ISSUE THREAD

**Issue by AM4Ryzen** [MrAlex94/Waterfox#1743]
All you need to do to get Waterfox Classic and Current to run on the Vista extended kernel [linked here](https://msfn.org/board/topic/181612-wip-windows-vista-extended-kernel/), is to set the OSVersion and SubSysVersion to 6.0 on all the .exe files.

Both browsers run perfectly fine, until you try to play a video. The video won't play, because the code to detect Vista's codecs was considered a "defect", and was removed. Undoing [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1324183) should allow videos to play on Vista systems.

If/When Waterfox Current is rebased off of ESR 78, another change will need to be made. Waterfox Current 78 would require the RtlQueryPerformanceCounter function in ntdll. This can be changed to use the NtQueryInformationProcess function for the same purpose without any noticeable or measurable repercussion.

Making these changes should produce builds that work on the Vista extended kernel without the user needing to mod any of the .exes.

**Comment by AM4Ryzen** [comment]
One more thing I forgot, the fonts need to be reverted back to the Firefox 52 and earlier releases to look decent on Vista

In about:config
gfx.canvas.azure.backends = direct2d1.1,cairo,skia
gfx.content.azure.backends = direct2d1.1,cairo,skia
![Untitled](https://user-images.githubusercontent.com/39643236/92415286-d3eb9a00-f11d-11ea-93c7-3ba8f4f7a07f.png)

**Comment by Squall-Leonhart** [comment]
Vista has no capability for TLS 1.2+, so no.

**Comment by AM4Ryzen** [comment]
> Vista has no capability for TLS 1.2+, so no.

1: You're wrong
2: What cypher the system is set to use does not matter to Waterfox

![ScreenShot_20200926070003](https://user-images.githubusercontent.com/39643236/94340268-176f5080-ffc6-11ea-80ed-f3d35c6ef175.png)
![ScreenShot_20200926070055](https://user-images.githubusercontent.com/39643236/94340283-281fc680-ffc6-11ea-848c-6b7be36b062c.png)
