### ISSUE TITLE
Create a Fork of Waterfox Current Based on ESR 60.9

### ISSUE THREAD

**Issue by JodyThornton** [MrAlex94/Waterfox#1744]
Firefox ESR 60 worked exceptionally well, performance-wise and was highly configurable.  Could not a long-term support Waterfox Current release be forked off using this version as a base?  Even better, could Waterfox Classic be eventually moved to this version?

**Comment by 117649** [comment]
If all legacy addon are working on that version that will be good.
TMP has some code for 60 as well.

**Comment by JodyThornton** [comment]
@117649:

I'm not sure that any legacy add-ons were still working by then.  I think Quantum was in full kick by then.

**Comment by AM4Ryzen** [comment]
> @117649:
> 
> I'm not sure that any legacy add-ons were still working by then. I think Quantum was in full kick by then.

I have a old school XUL theme that works with Firefox 58 Nightly, so there'd probably be less work needed to port XUL extensons to 60.

Edit: I don't think they'd ever replace Waterfox Classic with this though.

**Comment by 117649** [comment]
> > @117649:
> > I'm not sure that any legacy add-ons were still working by then. I think Quantum was in full kick by then.
> 
> I have a old school XUL theme that works with Firefox 58 Nightly, so there'd probably be less work needed to port XUL extensons to 60.
> 
> Edit: I don't think they'd ever replace Waterfox Classic with this though.

FF 56 is just about to be too old. I really want to see this happen soon. And I think they should also push current beyond 73. I'm just ported Tab-Groups to FF dev 81, the change mozilla had made at 73 is just so big it effectively render any version that is lower not worthy consider at all. Waterfox current which base on 68 is of course included and I don't see there is any reason for its existence any more.

**Comment by JodyThornton** [comment]
But 73+ disallows some things, like the old address bar, disabling e10s, and there will be further crippling of prefs and about:config.  I'd rather have two more years of being able to update an ESR 60x based browser, than jettison Gecko altogether.

68 works with enough sites still.  I don't experience any issues.  But I'd love 60 better.

**Comment by AM4Ryzen** [comment]
> 
> 
> > > @117649:
> > > I'm not sure that any legacy add-ons were still working by then. I think Quantum was in full kick by then.
> > 
> > 
> > I have a old school XUL theme that works with Firefox 58 Nightly, so there'd probably be less work needed to port XUL extensons to 60.
> > Edit: I don't think they'd ever replace Waterfox Classic with this though.
> 
> FF 56 is just about to be too old. I really want to see this happen soon. And I think they should also push current beyond 73. I'm just ported Tab-Groups to FF dev 81, the change mozilla had made at 73 is just so big it effectively render any version that is lower not worthy consider at all. Waterfox current which base on 68 is of course included and I don't see there is any reason for its existence any more.

What did Firefox 73 change, and why have I not heard about it before?

**Comment by 117649** [comment]
> > > > @117649:
> > > > I'm not sure that any legacy add-ons were still working by then. I think Quantum was in full kick by then.
> > > 
> > > 
> > > I have a old school XUL theme that works with Firefox 58 Nightly, so there'd probably be less work needed to port XUL extensons to 60.
> > > Edit: I don't think they'd ever replace Waterfox Classic with this though.
> > 
> > 
> > FF 56 is just about to be too old. I really want to see this happen soon. And I think they should also push current beyond 73. I'm just ported Tab-Groups to FF dev 81, the change mozilla had made at 73 is just so big it effectively render any version that is lower not worthy consider at all. Waterfox current which base on 68 is of course included and I don't see there is any reason for its existence any more.
> 
> What did Firefox 73 change, and why have I not heard about it before?

In short .xul is RIP all previous .xul have been change to .xhtml and so the contents and layout of them.

But some of the XUL element still be reserved as html custom element thus making port legacy addon not that difficult.

I believe 73 is the number all this happened but may be mistaking.

**Comment by AM4Ryzen** [comment]
> > > > > @117649:
> > > > > I'm not sure that any legacy add-ons were still working by then. I think Quantum was in full kick by then.
> > > > 
> > > > 
> > > > I have a old school XUL theme that works with Firefox 58 Nightly, so there'd probably be less work needed to port XUL extensons to 60.
> > > > Edit: I don't think they'd ever replace Waterfox Classic with this though.
> > > 
> > > 
> > > FF 56 is just about to be too old. I really want to see this happen soon. And I think they should also push current beyond 73. I'm just ported Tab-Groups to FF dev 81, the change mozilla had made at 73 is just so big it effectively render any version that is lower not worthy consider at all. Waterfox current which base on 68 is of course included and I don't see there is any reason for its existence any more.
> > 
> > 
> > What did Firefox 73 change, and why have I not heard about it before?
> 
> In short .xul is RIP all previous .xul have been change to .xhtml and so the contents and layout of them.
> 
> But some of the XUL element still be reserved as html custom element thus making port legacy addon not that difficult.

More of a reason to avoid that, but ok

**Comment by hawkeye116477** [comment]
> But 73+ disallows some things, like the old address bar, disabling e10s, and there will be further crippling of prefs and about:config. I'd rather have two more years of being able to update an ESR 60x based browser, than jettison Gecko altogether.

This is not product made by Mozilla. That changes probably will be reverted.

**Comment by 117649** [comment]
> > But 73+ disallows some things, like the old address bar, disabling e10s, and there will be further crippling of prefs and about:config. I'd rather have two more years of being able to update an ESR 60x based browser, than jettison Gecko altogether.
> 
> This is not product made by Mozilla. That changes probably will be reverted.

How about integrate all functions of TMP in to the WF at same time? Those are very wanted but also basic.
