### ISSUE TITLE
32-bit support (hear me out)

### ISSUE THREAD

**Issue by Fierelier** [MrAlex94/Waterfox#1746]
I read up on the roots of this browser, I know this is supposed to be a pure 64-bit kind of deal, but...

I really think this browser could have an important role for older devices with low memory and weak CPUs. Waterfox Current is quite a modern fork of Firefox, though it still lets you disable e10s (a feature I much appreciate), which saves a butt-load of memory and makes CPU prioritization much simpler. And because the browser is based on modern pinnings, it runs quite fast. There's nothing quite like it out there, and I was crushed to find out about this caveat.

**Comment by Ibuprophen** [comment]
I feel the pain my friend as I currently have an open issue https://github.com/MrAlex94/Waterfox/issues/730 regarding this specific topic for around 2 years... 


~Ibuprophen

**Comment by Ibuprophen** [comment]
I feel the pain my friend as I currently have an open issue https://github.com/MrAlex94/Waterfox/issues/730 regarding this specific topic for around 2 years... 


~Ibuprophen

**Comment by AM4Ryzen** [comment]
> 
> 
> I read up on the roots of this browser, I know this is supposed to be a pure 64-bit kind of deal, but...
> 
> I really think this browser could have an important role for older devices with low memory and weak CPUs. Waterfox Current is quite a modern fork of Firefox, though it still lets you disable e10s (a feature I much appreciate), which saves a butt-load of memory and makes CPU prioritization much simpler. And because the browser is based on modern pinnings, it runs quite fast. There's nothing quite like it out there, and I was crushed to find out about this caveat.

If you have a system that can't run a x64 OS, you really should upgrade. Even the Pentium 4 can do 64-bit.

**Comment by Fierelier** [comment]
@Ibuprophen :+1:

@asdf2345 That is not correct. Pentium 4s are 32bit, in fact, I think all Intel CPUs were, until the Intel Core 2 Duo changed that, with the original Intel Core Duo line still being 32bit, even. Also, I'm personally really against the "just upgrade" advice, these systems are more viable than you might realize, and this browser would make them even more viable thanks to the great render speed, even on software.

**Comment by hawkeye116477** [comment]
> The first Pentium 4-branded processor to implement 64-bit was the Prescott (90 nm) (February 2004), but this feature was not enabled. Intel subsequently began selling 64-bit Pentium 4s using the "E0" revision of the Prescotts, being sold on the OEM market as the Pentium 4, model F. 

`http://www.cpu-world.com/sspec/SL/SL8J6.html`

**Comment by Fierelier** [comment]
Good to know, the Pentium 4 line sure is confusing.

**Comment by AM4Ryzen** [comment]
> 
> 
> @Ibuprophen +1
> 
> @asdf2345 That is not correct. Pentium 4s are 32bit, in fact, I think all Intel CPUs were, until the Intel Core 2 Duo changed that, with the original Intel Core Duo line still being 32bit, even. Also, I'm personally really against the "just upgrade" advice, these systems are more viable than you might realize, and this browser would make them even more viable thanks to the great render speed, even on software.

90% Certain I was able to install Vista x64 on a Pentium 4.

> I really think this browser could have an important role for older devices with low memory and weak CPUs. Waterfox Current is quite a modern fork of Firefox, though it still lets you disable e10s (a feature I much appreciate), which saves a butt-load of memory and makes CPU prioritization much simpler. And because the browser is based on modern pinnings, it runs quite fast. There's nothing quite like it out there, and I was crushed to find out about this caveat.

I think what you want would be something like [basilisk55/serpent55](http://rtfreesoft.blogspot.com/2020/08/weekly-browser-binaries-20200829.html). Just Ctrl + F for basilisk55, and you'll find it.

**Comment by Ibuprophen** [comment]
My deepest apologies as I was under the impression that this was referring to the 32-bit Android OS. 

:-((


~Ibuprophen

**Comment by Fierelier** [comment]
> 90% Certain I was able to install Vista x64 on a Pentium 4.

I have already acknowledged that some Pentium 4s are indeed 64-bit.

> I think what you want would be something like [basilisk55/serpent55](http://rtfreesoft.blogspot.com/2020/08/weekly-browser-binaries-20200829.html). Just Ctrl + F for basilisk55, and you'll find it.

Thank you, that's cool. I'll check it out.

**Comment by MrAlex94** [comment]
I can appreciate your points, unfortunately it's not likely to happen. It would require pushing out even more builds and introduces a set of it's own problems. The ask is too much for how many people would actually use it.

**Comment by LOuroboros** [comment]
It's been more than a year, so I feel the need to ask; is this still completely out of question, @MrAlex94?

Sadly, the last time I tried the 64bit build of Waterfox it was considerably sluggish compared to the builds of Firefox *(be it the 32bits or the 64bits ones)*, and being a fork of Firefox, I fear that they may also have the same problem with the RAM on certain hardware combos that 64bit builds of Firefox do where it just keeps chewing at your RAM until they slow your PC down to a crawl and thus need to be restarted *(the browser, not the PC)*.
