### ISSUE TITLE
CLASSIC Another page wont load

### ISSUE THREAD

**Issue by sutex** [MrAlex94/Waterfox#1747]
Wont work with addon disabled, Safe mode , worked a few days ago
https://www.escapefromtarkov.com/support
Works in Firefox

**Comment by hawkeye116477** [comment]
You forgot to write what version you have. Anyway, I say that issue is on both Classic and Current and looks like that new regex feature must be implemented to fix that or you can wait for new WF based on 78.

**Comment by sutex** [comment]
Another site , loosing count https://www.nvidia.com/en-us/geforce/forums/discover/

**Comment by hawkeye116477** [comment]
@sutex That site works fine for me.

**Comment by sutex** [comment]
No idea what's going on with my Waterfox , sites just stop working
