### ISSUE TITLE
Game Jolt website won't load

### ISSUE THREAD

**Issue by EternityEngine** [MrAlex94/Waterfox#1750]
**Describe the bug**
When I go to the Game Jolt website (https://gamejolt.com/) using Waterfox Classic, the page is blank. When the page is loaded in the current Firefox, it loads correctly.

**To Reproduce**
1. Go to https://gamejolt.com/.
2. The page does not load - it is blank.

**Expected behavior**
The Game Jolt homepage is loaded and displayed.

**My configuration** 
 - Device: PC
 - OS: Windows 7 64-bit
 - Version: Classic 2020.08.1

**Additional context**
The Console output:
```
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.  gamejolt.com:69
SyntaxError: invalid regexp group  app.app.a658a357.js:1:247767
```

The Console output in Firefox (technically from loading the URL https://gamejolt.com/games/Sonic-GT/533291, but the Waterfox output is the same there):
![unknown](https://user-images.githubusercontent.com/20052973/92988747-2cef6100-f483-11ea-8d52-91fb0429c31a.png)

**Comment by hawkeye116477** [comment]
It's similar problem as #1747.

**Comment by EternityEngine** [comment]
Clarification: The Waterfox console output is the same on both pages, rather than the Waterfox output matching the Firefox output on the specific page I mentioned.

**Comment by EternityEngine** [comment]
Update: The Game Jolt website loads in Classic now (with no updates to the browser), so I assume they added a fallback or something for older browsers.

The Console output on the website now:
```
[vuex-class] passing the 2nd argument to `namespace` function is deprecated. pass only namespace string instead. app.vendors~app.eaaeca19.js:23:159323
Timing (shell) vue-init = 693  app.app.c5d12c2b.js:1:390490
Timing (shell) vue-mounted = 922
```
