### ISSUE TITLE
about:config

### ISSUE THREAD

**Issue by sutex** [MrAlex94/Waterfox#1751]
Can we have a list of all the **about:config** to either enable or disable **_For those that can't get Web sites to load_**

I have quite a few sites that want load at all or allow me to sign in then after the page is refreshed, have me signed out Star Citizen case in point.

**Comment by hawkeye116477** [comment]
Not for all sites helps switching that prefs and usually toggling them fixes one site, but breaks another. Maybe better would be to wait when them becomes enabled by default.
