### ISSUE TITLE
Waterfox in snap store and flathub

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1752]
We're really tired with portable style waterfox that available for linux. Release to snap store or flathub quite easy task.

**Comment by ghost** [comment]
I noticed https://github.com/MrAlex94/Waterfox/issues/1388 issue comment. Anyway this's not something to say no time however snap store packages support for all linux distributions (something like one package and all distro) and may eventually work with windows etc.

**Comment by hawkeye116477** [comment]
@azrea https://github.com/YamiYukiSenpai/waterfox-snap

**Comment by ghost** [comment]
@hawkeye116477 Add this details to this repo readme as thirdpary/volunteer contribution. it'll helpful for someone else looking for snap package. basically there's is no risk due it available in public repo and he follow the snapcraft build template and publishing procedure.

**Comment by ghost** [comment]
Above classic version and current version https://github.com/YamiYukiSenpai/waterfox-current-snap

**Comment by chaserene** [comment]
Waterfox should really be in the Snap Store.
