### ISSUE TITLE
Waterfox doesn't support for add custom search engines as firefox

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1753]
**Describe the bug**
See the title.

**To Reproduce**
Check search engines area. no option to add custom search engines.

**Expected behavior**
See the firefox.

**My configuration** 
 - Device: Ubuntu 20.04.01

**Comment by hawkeye116477** [comment]
Why you didn't fill in version field? Anyway, there are 2 Waterfoxes - Classic and Current and both allow to add additional search engine.

**Comment by ghost** [comment]
> Why you didn't fill in version field? Anyway, there are 2 Waterfoxes - Classic and Current and both allow to add additional search engine.

Sorry, these months i'm not using waterfox but i believe this is not implemented yet. In this cause, i have used waterfox current and that's the only the reason for stopped use.

**Comment by ghost** [comment]
Hey, tested latest version. no option to add custom search engine.

**Comment by hawkeye116477** [comment]
@azrea Then maybe you mean something another than I think, but, you should see „+" icon in search bar when you go to GitHub for example.

**Comment by ghost** [comment]
My bad :rofl: you need write documentation for that but it's very easy method for add custom search engines compared to other browsers.

**Comment by ghost** [comment]
Ah, not necessary. its seems that's the new method in firefox.
