### ISSUE TITLE
Replace Waterfox Homepage with fan-art

### ISSUE THREAD

**Issue by N8BWert** [MrAlex94/Waterfox#1759]
### Bringing the community together
**In an effort to engage with our community better we should replace the current Waterfox homepage with this month's highest rated fan-art picture.  This addition would greatly enhance our user retention by creating a Waterfox community where dedicated users can express their creativity.**

**Comment by clay53** [comment]
I really love this idea. I hope it can be implemented soon! :heart:

**Comment by ghost** [comment]
This could be the greatest thing to happen to Waterfox, I would cry in joy for 7 days and 7 nights if my beautiful brothers in the Waterfox community linked arms and made the impossible possible. 

May god shine his grace on thee, 
-H. Shuker of the Waterfox fandom

**Comment by aquaspy** [comment]
I agree with  this idea too

**Comment by clay53** [comment]
> I agree with this idea too

I agree with this. :heart:

**Comment by clay53** [comment]
This is blasphemy.

**Comment by MrAlex94** [comment]
I really appreciate the thought everyone - it is very sweet.

Unfortunately I have seen some of the Waterfox fan art before - it's not very PG. I do not think that would tide over well with any poor soul not expecting it 😅
