### ISSUE TITLE
This podcast doesn't play in latest version of Waterfox, but plays fine in Chrome or Opera

### ISSUE THREAD

**Issue by ArizonaCowboy** [MrAlex94/Waterfox#1763]
This podcast doesn't play in latest version of Waterfox, but plays fine in Chrome or Opera

**To Reproduce**

Go to https://fivethirtyeight.com/features/politics-podcast-how-a-scotus-vacancy-will-shape-the-election/

push play button

**Expected behavior**

podcast should play, as it does on Chrome or Opera

**My configuration** 
 - Device: PC
 - OS:  Windows 7
 - Version: 2020.08 (64-bit)

HINT:

doesn't play on Firefox versions numbered in the 60's either

**Comment by hawkeye116477** [comment]
> OS: <Windows 7

Version lower than Windows 7, so you have Vista?

Did you have uBO or some another adblocker installed? Appears that it could block playing that podcast.

**Comment by ArizonaCowboy** [comment]
You are correct, the issue was uBO - sorry for the incorrect bug report
