### ISSUE TITLE
Help compiling for Android on Debian 9, or bug?

### ISSUE THREAD

**Issue by tcreek** [MrAlex94/Waterfox#1764]
I am trying to compile 2020.09-current for Android, and using the online Firefox guide (a bit outdated).

https://firefox-source-docs.mozilla.org/mobile/android/geckoview/contributor/geckoview-quick-start.html

I am trying from both the command line, and Android Studio.

First from command line:

I am getting the following:

> 
> Warning: File /home/trent/.android/repositories.cfg could not be loaded.        
> Warning: Failed to find package docs                                            
> Error running mach:                     ] 10% Computing updates...              
> 
>     ['bootstrap']
> 
> The error occurred in code that was called by the mach command. This is either
> a bug in the called code itself or in the way that mach is calling it.
> You can invoke |./mach busted| to check if this issue is already on file. If it
> isn't, please use |./mach busted file| to report it. If |./mach busted| is
> misbehaving, you can also inspect the dependencies of bug 1543241.
> 
> If filing a bug, please include the full output of mach, including this error
> message.
> 
> The details of the failure are as follows:
> 
> CalledProcessError: Command '['/home/trent/.mozbuild/android-sdk-linux/tools/bin/sdkmanager', 'platform-tools', 'build-tools;27.0.3', 'platforms;android-28', 'emulator', 'docs']' returned non-zero exit status 1
> 
>   File "/home/trent/dev/Waterfox-2020.08-current/python/mozboot/mozboot/mach_commands.py", line 43, in bootstrap
>     bootstrapper.bootstrap()
>   File "/home/trent/dev/Waterfox-2020.08-current/python/mozboot/mozboot/bootstrap.py", line 430, in bootstrap
>     getattr(self.instance, 'install_%s_packages' % application)()
>   File "/home/trent/dev/Waterfox-2020.08-current/python/mozboot/mozboot/debian.py", line 129, in install_mobile_android_packages
>     self.ensure_mobile_android_packages()
>   File "/home/trent/dev/Waterfox-2020.08-current/python/mozboot/mozboot/debian.py", line 151, in ensure_mobile_android_packages
>     no_interactive=self.no_interactive)
>   File "/home/trent/dev/Waterfox-2020.08-current/python/mozboot/mozboot/android.py", line 201, in ensure_android
>     ensure_android_packages(sdkmanager_tool=sdkmanager_tool, no_interactive=no_interactive)
>   File "/home/trent/dev/Waterfox-2020.08-current/python/mozboot/mozboot/android.py", line 279, in ensure_android_packages
>     subprocess.check_call(args)
>   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
>     raise CalledProcessError(retcode, cmd)

It is clear it is looking for 

> repositories.cfg

For Android Studio

I just put Android Studio on the computer just to build this.

It is failing to sync with Gradle.

> Gradle sync failed: Process '[/home/trent/dev/Waterfox-2020.08-current/mach, environment, --format, json, --verbose]' finished with non-zero exit value 1: Error running mach: ['environment', '--format', 'json', '--verbose'] The error occurred in code that was called by the mach command. This is either a bug in the called code itself or in the way that mach is calling it. You can invoke |./mach busted| to check if this issue is already on file. If it isn't, please use |./mach busted file| to report it. If |./mach busted| is misbehaving, you can also inspect the dependencies of bug 1543241. If filing a bug, please include the full output of mach, including this error message.
> The details of the failure are as follows:
> BuildEnvironmentNotFoundException: config.status not available. Run configure. 
> File "/home/trent/dev/Waterfox-2020.08-current/python/mozbuild/mozbuild/mach_commands.py", line 1188, in environment return func(sys.stdout, verbose)
> File "/home/trent/dev/Waterfox-2020.08-current/python/mozbuild/mozbuild/mach_commands.py", line 1258, in _environment_json json.dump(self, cls=EnvironmentEncoder, sort_keys=True, fp=out)
> File "/usr/lib/python2.7/json/__init__.py", line 189, in dump for chunk in iterable:
> File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode o = _default(o)
> File "/home/trent/dev/Waterfox-2020.08-current/python/mozbuild/mozbuild/mach_commands.py", line 1252, in default result['substs'] = obj.substs
> File "/home/trent/dev/Waterfox-2020.08-current/python/mozbuild/mozbuild/base.py", line 350, in substs return self.config_environment.substs
> File "/home/trent/dev/Waterfox-2020.08-current/python/mozbuild/mozbuild/base.py", line 333, in config_environment raise BuildEnvironmentNotFoundException('config.status not available. Run configure.') Consult IDE log for more details (Help | Show Log) (1 m 35 s 313 ms)

I doubt this is a bug since the project is in the Google Play store.

Any ideas on what I may be doing wrong, or could it be a bug?

**Comment by shalva97** [comment]
I have same error with Gradle, but I am on Mac. any way to fix?
