### ISSUE TITLE
No updates visible on Waterfox Current 2020.07.2.1 (64-bit)

### ISSUE THREAD

**Issue by InvisibleManX** [MrAlex94/Waterfox#1767]
Waterfox Current 2020.07.2.1 (64-bit)
PC, Windows 7 64-bit

Already two new version got released by now, according to the blog, but still if I open Help>About Waterfox it says that it's up to date. 
So now I'll have to only update manually?

**Comment by MrAlex94** [comment]
Hmm very strange, the [update URL](https://www.waterfox.net/update/Waterfox/2020.07.1/aurora/WINNT/update.xml) points to the newest release.

Could you do me a favour? Before going to `Help > About Waterfox`, launch the browser console `(Ctrl+Shift+J)`. Then open `Help > About Waterfox`. After, in the search bar of the console type `AUS`. Then right click > select all and paste the output here. Should look similar to this:

<img width="992" alt="Screenshot 2020-09-23 at 17 34 01" src="https://user-images.githubusercontent.com/4728920/94042278-44074a80-fdc3-11ea-870f-4c02692442b4.png">

**Comment by InvisibleManX** [comment]
> 
> 
> Hmm very strange, the [update URL](https://www.waterfox.net/update/Waterfox/2020.07.1/aurora/WINNT/update.xml) points to the newest release.
> 
> Could you do me a favour? Before going to `Help > About Waterfox`, launch the browser console `(Ctrl+Shift+J)`. Then open `Help > About Waterfox`. After, in the search bar of the console type `AUS`. Then right click > select all and paste the output here. 

I did better. I just cleared the console before doing these tests. 

And I found out some weird errors appearing there the moment I opened this github page we're currently on. 

So you might wanna look into that as well. 

And here is the screenshot with all those erros, including AUS ones: 

![info](https://user-images.githubusercontent.com/66888405/94052957-5b096500-fde2-11ea-8da4-aa31252d9310.png)

**Comment by InvisibleManX** [comment]
Oh, and this is also my update settings: 

![info2](https://user-images.githubusercontent.com/66888405/94053415-fc90b680-fde2-11ea-9c52-303d8b0d7b04.png)

**Comment by InvisibleManX** [comment]
@MrAlex94 
Ah, I just noticed, in my screenshot above, my update variables are pointing to the same version I have currently, instead of pointing to the newest ones.

Maybe that's because I had to manually install version 2020.07.2.1 after having issues with 2020.07.2 ?

**Comment by MrAlex94** [comment]
Ah that was the problem - I misread the version number. Have added the update XML to that version now :-)

**Comment by InvisibleManX** [comment]
> 
> 
> Ah that was the problem - I misread the version number. Have added the update XML to that version now :-)

Alright :) 

Here's that link: [https://www.waterfox.net/update/Waterfox/2020.07.2.1/aurora/WINNT/update.xml](https://www.waterfox.net/update/Waterfox/2020.07.2.1/aurora/WINNT/update.xml)

For now it has no proper code though.

**Comment by InvisibleManX** [comment]
@MrAlex94 

So... I'm not sure what you meant by saying that you "added the update XML to that version now". 

Because it still says for me that my browser is up to date, and the link for my version 2020.07.2.1 has no content. 

Is it planned to be fixed, or my only chance to update is to go for manual downloading and installing of the new version?

**Comment by MrAlex94** [comment]
It'll be there with the new update today :-)

**Comment by MrAlex94** [comment]
Should be available now

**Comment by Callmebyourname** [comment]
Hi, how come every update needs download manually?
after click help and shows Restart to update Waterfox.
BUT actually can not update automatically. it happens more than one time when need an update.
![image](https://user-images.githubusercontent.com/44966528/94618684-86c09b00-0279-11eb-9dc0-2b1a4c319a65.png)
![image](https://user-images.githubusercontent.com/44966528/94618693-8aecb880-0279-11eb-89e1-20cce4bc05ab.png)
