### ISSUE TITLE
Images are not displayed on RTL.BE

### ISSUE THREAD

**Issue by Ropliplo951** [MrAlex94/Waterfox#1769]
**Describe the bug**
Images are not displayed on RTL.BE.

**To Reproduce**
Go to https://www.rtl.be/

**Expected behavior**
Images must display on RTL.BE.

**Screenshots**
![RTL](https://user-images.githubusercontent.com/62814587/94339654-bcf0e700-fffb-11ea-9d53-3c76b7851077.jpg)

**My configuration**
 - Device: PC
 - OS: Windows 10
 - Version: Classic 2020.09

**Comment by hawkeye116477** [comment]
That problem appears also on Current.

Update: Seems that's the thing => https://bugzilla.mozilla.org/show_bug.cgi?id=1566143 which needs to be implemented to fix that.

**Comment by LeeBinder** [comment]
Hawks appear to have even better eyes than eagles. At least you prove that to be true .. ;)
