### ISSUE TITLE
Waterfox Classic unusable after OS-level zoom (W10)

### ISSUE THREAD

**Issue by mkruselj** [MrAlex94/Waterfox#1771]
**To Reproduce**
1. Have Waterfox Classic open
2. Use Win++ or Win+- to magnify the whole screen
3. Zoom out back to 100%
4. Try browsing anywhere
5. "Gah! This tab has crashed" happens no matter which URI you try to open

**Expected behavior**
Would not expect that to happen at all.

**My configuration**
 - Device: Desktop i7-6700K, 64 GB RAM, 2x 1920x1200 monitors
 - OS: W10 1909
 - Version: Classic 2020.09 64-bit

**Comment by mkruselj** [comment]
Anyone? 🙁

**Comment by mkruselj** [comment]
@MrAlex94 Does closing this issue mean it was fixed? 🙂

**Comment by jrappen** [comment]
I assume not as 550 issues were closed right now without any comments at all.

**Comment by mkruselj** [comment]
I guess that means Waterfox development is being abandoned properly. Sad...
