### ISSUE TITLE
Very poor performance for Youtube streaming

### ISSUE THREAD

**Issue by 117649** [MrAlex94/Waterfox#1772]
![Screenshot 2020-09-27 221215](https://user-images.githubusercontent.com/8281345/94367173-7db3ba80-010f-11eb-8379-6196b3bf1b67.png)
Upper is WF classic and lower is MS Edge.
WF is hardly buffer any data and extremely stuttering.

**Comment by Squall-Leonhart** [comment]
Just you. ¯\\_(ツ)_/¯

**Comment by XenHat** [comment]
I also noticed severe performance issues playing Youtube on my laptop.

May be related to #1731, difficult to know without any info about the OP's hardware.
