### ISSUE TITLE
[Classic] search result page on mediamarkt.de not rendered correctly

### ISSUE THREAD

**Issue by LeeBinder** [MrAlex94/Waterfox#1773]
**Describe the bug** 
On https://www.mediamarkt.de/de/search.html?query=usb, the content which should be to the right of the sidebar appears for a second but then vanishes and gets erroneously displayed below it (scroll down to see). It is displayed correctly in WF current.

That's **_not_** dependent on the search query, it applies to any search.

**My configuration**
 - Device & OS: Laptop with macOS Mojave 10.14.6
 - Version of Waterfox: Classic 2020.09/56.3, but also not displaying correctly in Firefox macOS 56.0.2

**Additional context**
hawkeye already told me that this is not a webcomponents issue but something else

**Comment by hawkeye116477** [comment]
Problem is with flexbox (https://bugzilla.mozilla.org/show_bug.cgi?id=1409083).

**Comment by hawkeye116477** [comment]
Looks like that works correctly only with Servo.

**Comment by LeeBinder** [comment]
Thanks hawkeye for checking into this. As per Wikipedia, "in 2017 with the release of Firefox 54, the Servo CSS style engine (a part of the project) was incorporated by Mozilla into their open-source web browser." Since huge parts of Waterfox Classic are based on the 56.0.2 code, at least the CSS part of the engine should be present, shouldn't it?

The content IS displayed but "jumps" into the wrong place, which does seem like a CSS issue.

**Comment by LeeBinder** [comment]
Classic has bitten the dust, apparently :(

**Comment by MrAlex94** [comment]
Classic has been in security fix only ("maintenance") mode only for a year or two now. Unless someone provides compatibility patches. Nothing has changed in that regard. We just spent a non-significant amount of time getting CI/CD up and running for it too.

**Comment by LeeBinder** [comment]
I guess I needed a reminder. Glad to hear you folks only had to spend a NON-significant amount of time on CI/CD for Classic - that should be helpful.
