### ISSUE TITLE
Cannot browse any kb.vmware.com article, Waterfox show a black page.

### ISSUE THREAD

**Issue by sebma** [MrAlex94/Waterfox#1774]
**Describe the bug**

Hi,
Cannot browse any kb.vmware.com article, Waterfox show a black page.
Example : https://kb.vmware.com/s/article/2005129

**To Reproduce**

1. Go to https://duckduckgo.com/?q=site%3Ahttps%3A%2F%2Fkb.vmware.com&ia=web
2. Click on any result

**Expected behavior**

Waterfox shows the content of the page

**Screenshots**

![kb vmware com_Waterfox_Issue_#1774](https://user-images.githubusercontent.com/4569306/94448353-15b2b200-01ab-11eb-8371-3b5c657e20b9.png)

**My configuration** 
 - Device:  PC
 - OS:  Windows 7 64bits
 - Version: Classic 2020.09 64bits

**Additional context**

**Comment by hawkeye116477** [comment]
Mozregression results:
Last bad: 2018-07-04
First good: 2018-07-05
Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=6c0fa9a675c91390ca27664ffb626c56e8afea4d&tochange=afdeb0288690f0acde2ba6bd008f860e1acdd026

I guess that's probably same problem as #1252 and few others.
