### ISSUE TITLE
Classic Addon Archive URLs are not understood in a new tab of the first Waterfox window

### ISSUE THREAD

**Issue by sebma** [MrAlex94/Waterfox#1775]
**Describe the bug**

Classic Addon Archive URLs (example caa:list) are not understood in a new tab of the first Waterfox window.

**To Reproduce**

1. Install [Classic Addon Archive addon](https://github.com/JustOff/ca-archive/releases/download/2.0.3/ca-archive-2.0.3.xpi)
2. Restart Waterfox
3. Click on the Classic Addon Archive icon, it opens a new window
4. Close the new window when the Classic Addon Archive db re-indexing is finished
5. Open a new tab in the first Waterfox window
6. Type `caa:list` in the url

**Expected behavior**

Interpret `caa:` urls instead of triggering a "caa:" search with the default search engine (in my case `duckduckgo` is the default search engine).

**Screenshots**

![image](https://user-images.githubusercontent.com/4569306/94451108-4d6f2900-01ae-11eb-80a8-aa3224d61708.png)

**My configuration** 
 - Device:  PC
 - OS:  Windows 7 64bits
 - Version:  Classic 2020.09 64bits

**Additional context**

**Comment by Jamesstevens-3rd** [comment]
I have had very little success in getting **Classic Addons Archive** to work in a new tab, but it will work if you open a **File > New  Non-e10s Window**

if you find **New  Non-e10s Window** is greyed out and you have **Tab Mixed Plus** addon installed open the **TMP > Options > Links** and _untick_ **Enable Single Window Mode** and restart the browser
