### ISSUE TITLE
Youtube Time/Progress Bar problem

### ISSUE THREAD

**Issue by TH56** [MrAlex94/Waterfox#1781]
Youtube Time/Progress bar can't be moved forward or rewound.  Issue before and after update to
2020.09 (64-bit).  Progress bar works correctly on Chrome and Firefox.

**Comment by Squall-Leonhart** [comment]
works fine for me.

**Comment by hawkeye116477** [comment]
> 2020.09 

Classic or Current? Maybe try in safe mode.

**Comment by TH56** [comment]
Classic.  I will try in safe mode and get back to you.  I'm on a Windows 10 system which is up to date and have tried all the usual reloads, updates and reboots.  Funny thing is that when youtube is imbedded in a story on a webpage other than youtube it works fine - I can click on the time bar and advance to later in the vid or back to an earlier time in the vid.  Also works fine in Chrome or Firefox on my system.  Thanks for any further help and for your reply

  TH

**Comment by TH56** [comment]
Works fine in Safemode.  Now to find the addon that is screwing things up.  Thanks for the prod to use safemode.  I'm going to close this issue as solved now.
