### ISSUE TITLE
How to bypass "this addon could not be installed because it appears to be corrupt" issue on trying to install XUL addons in Current?

### ISSUE THREAD

**Issue by mzso** [MrAlex94/Waterfox#1786]
**Describe the bug**
I get "this addon could not be installed because it appears to be corrupt" whenever I try to install classic addons.

**To Reproduce**

Try to install XUL addon.

**Expected behavior**
Install, normally, or allow to force install addons

**My configuration** 
WF Current.

**Comment by hawkeye116477** [comment]
XUL addons must be first modified to work in WF Current. For example https://github.com/hawkeye116477/CS/releases/tag/current-1.0.0b1 should work.
