### ISSUE TITLE
Classic Endless page loop, not loading

### ISSUE THREAD

**Issue by sutex** [MrAlex94/Waterfox#1789]
Another site not working, trying to login I get an endless loop of this page refreshing, was working last month. 
https://www.originenergy.com.au/

Does waterfox have issues with Simple DNS Encrypt? Sites where working while using DNS Encrypt but lately lots don't   

Site loads no problem in latest Firefox with my Simple DNS Encrypt active

**Comment by hawkeye116477** [comment]
So it requires an account. Can you open the console (ctrl+shift+i, then console tab), then try to login and show us output from console?

**Comment by sutex** [comment]
Cant login, the page loads but clicking on the login link, and after entering login details, page goes into an endless refresh/reload. Star Citizen does not hold login as well, again that works in Firefox.

**Comment by hawkeye116477** [comment]
> Cant login, the page loads but clicking on the login link, and after entering login details, page goes into an endless refresh/reload. 

I told you to try to login, it doesn't need to be successful, so just do what you described you did, but additionally show us output from console.

**Comment by sutex** [comment]
Output from console?
Cant seem to add the image or the zip , it won't let me do it here

**Comment by sutex** [comment]
An unable to edit the above, posted to see if it had uploaded but was not showing

Cant copy and paste the text Body is too long (maximum is 65536 characters)

**Comment by hawkeye116477** [comment]
> Cant copy and paste the text Body is too long

Then make txt file and attach it :smile:.

**Comment by sutex** [comment]
Cant even add a txt file, which I tried to do, drag and drop , which is why I tried a zip, it won't let me do it
When I move it across to upload it open another window..  Opening to upload wont work either lol

**Comment by sutex** [comment]
[Archive 20-10-15 03-01-26.har.zip](https://github.com/MrAlex94/Waterfox/files/5379824/Archive.20-10-15.03-01-26.har.zip)

I'm now using Firefox latest to upload this Waterfox classic would not let me. And the edit is now working too 👍 
![2020-10-15 03_03_31-Window](https://user-images.githubusercontent.com/10361359/96022552-91de1280-0e98-11eb-9012-bba75f3da3ba.png)
