### ISSUE TITLE
Waterfox Classic 2020.09+ - GitHub doesn't work

### ISSUE THREAD

**Issue by Z0nder** [MrAlex94/Waterfox#1790]
GitHub stopped working few hours ago. Things doesn't work and grayed out:

![alt text](https://i.imgur.com/QGfInj3.png)

**Comment by magiruuvelvet** [comment]
As an extend the notification page is broken too. Clicking on buttons navigates to the page the form POST action is pointing to, rather than staying on the notification page. GitHub definitely deployed something to production some hours ago and now everything is broken in Waterfox :(

GitHub is slowly killing browsers which aren't Chromium-based I can feel it.

**Comment by hawkeye116477** [comment]
Yeah, seems that it works only if you enable webcomponents, but when you do that, then some other pages could be broken, because webcomponents support in Classic is incomplete.

**Comment by mkruselj** [comment]
Yeah I cannot see if I have a new push on my branch on Pull Requests page, nor can I create a PR.

Also if I want to merge/squash and merge someone's PR, the button is not working at all.

What gives?

**Comment by Purfview** [comment]
> 
> 
> Yeah, seems that it works only if you enable webcomponents, but when you do that, then some other pages could be broken, because webcomponents support in Classic is incomplete.

Thanks for the hint.
So far it works with dom.webcomponents.enabled = true

**Comment by IzzySoft** [comment]
Alternative [hint from Reddit](https://www.reddit.com/r/waterfox/comments/jbql07/github_no_longer_works_with_waterfox_classic/) should globally activating webcomponents break other sites for you: Install [Polly from here](https://github.com/zakius/Polly/releases), which was "created to allow users of Waterfox Classic (and possibly other Firefox derivatives) to load polyfills at will". Then go to Github. Once the page is loaded, open Polly's popup menu (the icon looks like a puzlle piece) and tick the Webcomponents-Bundle.js check-box. Reload the page, works again.

**Comment by tcreek** [comment]
Most of everything on GitHub is now broken. Have you tried adding an image? I cannot it with Classic Waterfox.

Look what happens when you try to edit your post

![Screenshot from 2020-10-21 10-21-52](https://user-images.githubusercontent.com/4149717/96802792-351ab480-13d0-11eb-8015-1fadce5f60ff.png)

Also, I just tried the GitHub third party login access to a site. When I click on "Authorize," nothing happens.

**Comment by IzzySoft** [comment]
@tcreek have you tried Polly, from my post just before yours?

> Have you tried adding an image?

Yes, works fine (see below).

> Look what happens when you try to edit your post

![image](https://user-images.githubusercontent.com/6781438/96805926-0671fd80-1413-11eb-84a4-59c5ac0f5612.png)

Yes? And yes, I'm using Waterfox Classic. With Polly, as described in my previous comment. Just give it a try :wink:

**Comment by tcreek** [comment]
I did give it a try, and why I am posting the issue here also I am using this version on Windows and Linux, and it's the same exact same issue across the board on both of them.Not just this GitHub site, but also issues on many many sites starting as a few days ago: "Update your browser" "Version no longer supported" and it goes on and on.

**Comment by decembre** [comment]
Tested Polly, but not working....
Always impossible to drag a screenshot into the comment form by example.
I follow the instruction:
"Once the page is loaded, open Polly's popup menu (the icon looks like a puzlle piece) and tick the Webcomponents-Bundle.js check-box. Reload the page, works again."

**Comment by IzzySoft** [comment]
@decembre well, it worked for me. Though I must admit that I still notice some rare cases (like, 1 out of 50) where it seems to fail. So far, simply reloading again did the trick then. Not sure if the OS makes a difference here (I'm on Linux Mint if it matters).

**Comment by decembre** [comment]
Retested for GitHub (with Polly and not the tweak in aboout:config ) and ... the drag screenshot function don't work.

Same for YouTube Music...
Like i said in:
<a href="https://github.com/MrAlex94/Waterfox/issues/1800">Waterfow Classic 56.3 : Problem in YouTube Music (no drag possible in right playlist)</a>
![Youtube Music - PB - Drag item in list - Waterfox Classic - GIF 24-08-2020 13-20-45](https://user-images.githubusercontent.com/868778/96934339-56f46400-14c2-11eb-8a64-c1653b049a23.gif)
The drag item function don't work with Polly.
What settings i need to choose in Polly for solving this issue ?
My config:
Waterfox 56.3 and Win10

**Comment by IzzySoft** [comment]
@decembre glad it works for you with Github as well (I was already confused). No idea with YT as I don't use that. You could try ticking the other 3 boxes as well, but no guarantees – it might be something completely different altogether.

What did I read recently sums it up nicely: 10..20 years ago we had web browsers to view HTML web pages. Today they've mutated into VMs running some operating system to work web applications… So your VM lacks some instructions for the YT application – or the OS in it needs an update…

**Comment by decembre** [comment]
Sorry , nothing work... (was confused with my different profiles when testing...)
You answer too quickly, before i re edit my comment!
:-)
About Youtube music, with the setting 'tick the Webcomponents-Bundle.js check-box", the playlist don't load.
And whit the others... nothing load!

Actually, the only thing which work for both issues,  is the about:config tweak:
dom.webcomponents.enabled to "true"

**Comment by IzzySoft** [comment]
Well, then there might be a difference between WF running on Linux (where the addon does the trick) and WF running on Windows. No further ideas then, sorry.

(did I wait long enough this time before pressing the green button? You didn't edit your comment yet … :speak_no_evil: :smile:)

**Comment by decembre** [comment]
Thanks for your patience !
Yes, that's a hell all these changes:
Yet, we need tweak too much (just to maintain things working) and sometime with wrong idea or future disappointment .
I think we take more time to play around issue than make other things more interesting.

**Comment by LeeBinder** [comment]
very cool (Polly), thanks for the hint - github working fine here again in WF classic 2020.10 macOS.

@hawkeye116477 : do you have a rough timeline for completion of webcomponents support in Classic?

@Z0nder : can you please edit the title to 

Waterfox Classic 2020.09+ - GitHub doesn't work

(simply add a **+**) - thank you.

**Comment by LeeBinder** [comment]
@Z0nder : can you please edit the title to 

Waterfox Classic 2020.09+ - GitHub doesn't work

(simply add a **+**) - thank you.

**Comment by hawkeye116477** [comment]
> do you have a rough timeline for completion of webcomponents support in Classic?

I was counting more on Moonchild Team that they continue some work, but seems that for now nothing moved, they even changed the due date to unknown. So I'll tell you same what they said, it'll be ready when it will be ready :smile:.

**Comment by LeeBinder** [comment]
gotcha!

**Comment by tcreek** [comment]
I have also noticed the old Microsoft Edge Browser is no longer functioning on GitHub also

**Comment by hawkeye116477** [comment]
Seems that GH/MS have fun again, changed labels colors. So there's another thing to implement => https://bugzilla.mozilla.org/show_bug.cgi?id=1519519.

**Comment by Squall-Leonhart** [comment]
use https://github.com/JustOff/github-wc-polyfill instead, less crashy

**Comment by JustOff** [comment]
Please note that `github-wc-polyfill` requires e10s to be disabled as Mozilla failed to fix [bug #1261585](https://bugzilla.mozilla.org/show_bug.cgi?id=1261585).

**Comment by LeeBinder** [comment]
@JustOff I read though [bug #1261585](https://bugzilla.mozilla.org/show_bug.cgi?id=1261585) briefly but don't have the slightest idea what "e10s" are, if they are enabled by default in WF, and how to disable them. Could you share a brief summary about this "e10s" requirement? Thank you.

**Comment by JustOff** [comment]
e10s (electrolysis)  == multi-process mode, i.e.:

`about:preferences` -> `General` -> `Startup` -> `Enable multi-process Waterfox` - should be unchecked.

**Comment by hawkeye116477** [comment]
> I was counting more on Moonchild Team that they continue some work, but seems that for now nothing moved, they even changed the due date to unknown. So I'll tell you same what they said, it'll be ready when it will be ready

New update: seems that we can't count on them now, cuz they archived repository and they are now providing only source tarballs. Apparently they don't like forks. So seems that they also don't want Pull Requests or maybe they are inviting to some private repo. 

So now will be more work required, cuz sometimes I could just make patch from their changes and only small changes were required, cuz between 52 and 56 not changed so much. Anyway, looks like that I'll need to do some research and do that by myself some day or maybe Seamonkey author or someone else will surprise us.

**Comment by Squall-Leonhart** [comment]
as long as its a git tarball it should retain the change list

**Comment by hawkeye116477** [comment]
@Squall-Leonhart Well, unfortunately, tarball doesn't contain whole git repository. So analyzing that could be harder, cuz between releases it could contain many changes, especially that there are no commits. 

You can read [their statement](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fforum.palemoon.org%2Fviewtopic.php%3Ff%3D5%26t%3D27369) if you're curious what they say, why they done that.

**Comment by LeeBinder** [comment]
@hawkeye116477 that's sad news :(. Any idea who or at least which fork Moonchild alludes to when he writes

> blatant disregard of the MPL by some forks and subsequent personal and vicious attacks against our devs and the project and browsers as a whole

?

**Comment by hawkeye116477** [comment]
@LeeBinder Maybe this => `https://www.reddit.com/r/palemoon/comments/pexate/pale_moon_developers_abuse_mozilla_public_license/`. You can find a lot of stories on palemoon subreddit if you're curious. 
I'll leave that without comment, but if you want to continue discussion about it, then maybe reddit would be better for this :smile:.

**Comment by LeeBinder** [comment]
thanks for the link, and heck, no discussion here for sure.

Well maybe apart from, if to or not wear masks in GithHub issue rooms.

(just being silly)
