### ISSUE TITLE
Focus on getting classic add-ons up-to-date

### ISSUE THREAD

**Issue by sutex** [MrAlex94/Waterfox#1794]
I use Classic because of my Add-ons

Given the ongoing issues with Classic, is it possible to get my add-ons to work with, the more 'modern; version of Waterfox
Maybe a project focused on getting classic, add-ons up-to-date.

**Everything below is my core add-ons Those marked as * I can't live without!**
AutomaticSaveFolder{1.0.5b129} *
AutoPrivate{1.7.4} *
CookiesManager+{1.14.3}
DownloadStatusBar{15.0.0.1} *
FEBE{8.9.3.1}
FoxClocks{4.3.2} *
FTDeepDark{14.3} *
MouseZoom{0.4.9.1-signed.1-signed} *
NoScript{5.1.9}
ProfilePassword-Firefox{0.3.19} *
QuickFoxNotes{2.8.6} *
ScrapBook{1.5.14} *
SpeedDial{0.9.6.17} *
TabMixPlus{0.5.5.0} *
X-notifierforGmailHotmailYahooAOL{4.2.16} *

**Comment by hawkeye116477** [comment]
I think that you should rather ask about that developers of these extensions.

**Comment by sutex** [comment]
And after that, would Waterfox has a base addon collection
