### ISSUE TITLE
[Request] Time to bring back the 32 bit builds of Waterfox for android

### ISSUE THREAD

**Issue by mikeloeven** [MrAlex94/Waterfox#1795]
Just saying there are still a good amount of X86 androids around and with the horrible abortion of a UI mozilla has dumped on the mobile world and removal of most advamced settings we are pretty much without a functional browser. Kindly consider reviving the 32 bit waterfox builds just so we can have a working fork on non flagship devices

**Comment by hawkeye116477** [comment]
> working fork on non flagship devices

Flagship device isn't required to have 64-bit Android. For example I've Redmi Note 5 AI. Anyway, future ARM mobile CPUs will drop 32-bit support. The other thing worth mention is that Waterfox currently haven't any Android build in Play Store.

**Comment by LeeBinder** [comment]
I'd LOVE to see the old 32bit ARM Waterfox refreshed, too.

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/issues/730
