### ISSUE TITLE
Waterfow Classic 56.3 : Problem in YouTube Music (no drag possible in right playlist)

### ISSUE THREAD

**Issue by decembre** [MrAlex94/Waterfox#1800]
Test link:
[music.youtube](https://music.youtube.com/watch?v=8-SlvZxMTcA&list=RDAMVM7ss-xmvLGFw)
I can't drag item in the list (right panel).
I see the drag cursor when i hover an item in the playlist, but i can't drag it.
Here a screenshot (with Waterfox classic 56.3):
![Youtube Music - PB - Drag item in list - Waterfox Classic - GIF 24-08-2020 13-20-45](https://user-images.githubusercontent.com/868778/96889839-4c68a900-1487-11eb-8c34-608bb39cfb6d.gif)
Test in many different profiles:
Same problem.

In Firefox Quantum and Chrome:
All work fine.
Here a Gif screenshot (with Firefox Quantum) of the normal use:
![Youtube Music - PB - Drag item in list - Quantum Normal - GIF 24-08-2020 13-20-45](https://user-images.githubusercontent.com/868778/96890319-d31d8600-1487-11eb-98db-e919de246062.gif)

PS:
There is too a problem with GitHub:
Nothing work when i want post an issue (for that i need to use Firefox Quantum):
No possible to drag a screenshot in the form
-Add link not working too

**Comment by hawkeye116477** [comment]
PS: Solution for GH is already written on https://github.com/MrAlex94/Waterfox/issues/1790#issuecomment-709530207.

**Comment by decembre** [comment]
About Polly:
I have installed it, but no change about the problem with GitHub...
Same for YouTube Music.
How to use it ?
I follow the instruction:
"Once the page is loaded, open Polly's popup menu (the icon looks like a puzlle piece) and tick the Webcomponents-Bundle.js check-box. Reload the page, works again."

But if i change in about:config:
 dom.webcomponents.enabled to "true"
Solve the problem.
For the  YouTube problem (no dragging) too.
But if it possible i prefer a solution like Polly (if working)

**Comment by lfmnovaes** [comment]
I'm using Waterfox 2020.09 rn and I can't reproduce the issue u r experiencing. Win10 here, and I didn't do any "tweak".
Edit: just noticed that might be a "classic" problem.

**Comment by decembre** [comment]
Yes, seems a problem with only Waterfox Classic

**Comment by Jamesstevens-3rd** [comment]
> About Polly:
> I have installed it, but no change about the problem with GitHub...
> Same for YouTube Music.
> How to use it ?
> I follow the instruction:
> "Once the page is loaded, open Polly's popup menu (the icon looks like a puzlle piece) and **tick the Webcomponents-Bundle.js check-box**. Reload the page, works again."

yes but that's not all you must also put a tick in the **Use request modification method for this domain** the latest version is 1.5 and once I updated I had to untick **Use request modification method for this domain** restart the browser then go to GitHub and re-enable it for Poly to work. again

![enable-this](https://user-images.githubusercontent.com/55051487/101280265-0dd14880-37c0-11eb-8c72-8e297d51ba36.png)

**_TIP_**: to restart Waterfox and keep all open tabs type **about:profiles** and click the button **Restart Normally**

_EDITED:_ for spelling and grammar

**Comment by decembre** [comment]
Where find a Polly release now?
This one is deleted:
<a href="https://github.com/zakius/Polly/releases">zakius /  Polly</a>

**Comment by BallM4788** [comment]
> 
> 
> Where find a Polly release now?
> This one is deleted:
> [zakius / Polly](https://github.com/zakius/Polly/releases)

@decembre 
[Go here.](https://github.com/MrAlex94/Waterfox/blob/2d608155ebfe27504fdb44b06175e52c73f6c030/browser/extensions/zakius@polly.xpi) You probably already know what to do from here, but in case you don't:
1) Click either "Download" or "View raw" (both will do the same thing)
2) Make sure "Open with" is selected and Waterfox is displayed in the dropdown menu.
2a) If Waterfox is not displayed in the dropdown menu, select "Other...". A window titled "Choose Helper Application" should appear. Select "Waterfox".
2b) If Waterfox isn't displayed after doing the above, click the "Browse..." button. An "open file" screen should appear. Navigate to the folder where `waterfox.exe` is located (on Windows, this is almost always `C:\Program Files\Waterfox`). Either double-click on `waterfox.exe`, or click it once and then click the "Open" button.
2c) Click the "OK" button.
3) Click the "OK" button. A window should appear asking if you want to install the extension. Select "Yes".

**Comment by decembre** [comment]
Thank!

But now after the install and restart of Waterfox, 
when i applies the previous checked options (shown in the screenshot above),
my test link don't load (blank page).
Any idea about that .

ps:
I try too to check  each options , one by one, but same problem.
