### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1805]
is there gonna be android support or should i continue using iceraven?

**Comment by tcreek** [comment]
Huh?

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/issues/730

**Comment by mohibo** [comment]
> 
> 
> #730

this issue is not updated since a year ago

**Comment by tcreek** [comment]
Has anyone even bothered to look on the Google Play store?

**Comment by vehosah** [comment]
> Has anyone even bothered to look on the Google Play store?

Play Store doesn't even have it lmao

**Comment by tcreek** [comment]
That's how I got it on my Android phone

**Comment by vehosah** [comment]
> That's how I got it on my Android phone

Huh?

**Comment by tcreek** [comment]
huh? I got it on my phone via the Play Store. Not hard to understand

**Comment by vehosah** [comment]
> huh? I got it on my phone via the Play Store. Not hard to understand

Show us the link then?
