### ISSUE TITLE
Looking For A Button To Turn Off Release Notes Display On Updates

### ISSUE THREAD

**Issue by reluctantuser** [MrAlex94/Waterfox#1806]
Every Waterfox update includes an automatic display of "release notes" when the browser reboots. I understand the importance of telling the user what you changed/fixed/deleted/etc. but ...

... if you run the browser in what I call "kiosk mode", then the user has to attach at least a mouse to the kiosk machine and close the window with the "release notes" page.

What I call "kiosk mode": Enabling the browser to auto-run a URL when the browser is automatically started.

In my case, I use Linux. I auto-login into the desktop session; "lightdm" supports that.

I configure the desktop to auto-run the browser. I have tested this under XFCE and LXDE; it works every time. It might work in other variations & combinations of window managers and desktop UI.

I set the home URL of the Waterfox browser to the URL that I want to display; an internal security camera in my case.

I set the Waterfox browser to autostart my homepage every time it starts.

I may have missed a detail or 3 in this explanation, but the purpose is simple: auto-start the mini PC, or reboot it, and the OS auto-loads the desktop which auto-loads the browser which auto-loads the security camera webpage. All without user intervention; no mouse or keyboard required in my setup because the PC is solely for driving a display (not interactive).

That's why having Waterfox display the "release notes" on the first reboot after an update is annoying to me.

That's why I am looking for a way to turn off the display of these "release notes" after Waterfox updates.

Maybe there is a way to do that is not obvious to me, or maybe not. That's the reason for this issue.

**Comment by reluctantuser** [comment]
Is the answer from the bot definitive? An official statement by the developer in response to my question?

**Comment by reluctantuser** [comment]
Since no response is forthcoming from a real human being to my questions....

I have found an alternate solution - use some other browser.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
[This](https://github.com/mozilla/policy-templates/issues/604) should be useful for you.
