### ISSUE TITLE
[Classic] Steam announcements broken

### ISSUE THREAD

**Issue by kazerniel** [MrAlex94/Waterfox#1810]
**Describe the bug**
Steam's own announcements (so not games or groups) show no content, just header and footer. I tried reloading the page with Ctrl+F5. Adblocker is off. Last time I checked ~3 weeks ago, it worked. It works in Brave.

**To Reproduce**
1. Go to https://steamcommunity.com/games/593110/announcements/detail/2922233151830890571 or https://steamcommunity.com/games/593110/announcements/detail/2922233151838517106
2. See error

**Expected behavior**
To load the page's body content.

**Screenshots**
(Attaching images and previewing Github tickets seems broken too.)
https://imgur.com/a/sRvinOc

**My configuration**
 - Device: PC
 - OS: Windows 10
 - Version: Classic 2020.10 (64-bit)

**Comment by reallyuniquename** [comment]
>invalid regular expression flag s

Related #1738, #1737

**Comment by hawkeye116477** [comment]
That should be working fine now.
