### ISSUE TITLE
Unable to open pages who's SSL certificate has expired

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [MrAlex94/Waterfox#1824]
Recently my Waterfox (2020.03.1, and 2020.10) stopped allowing me to add exceptions to SSL certificate issues.  In particular, I'm no longer able to open sites (including one of my own) whose SSL certificate has expired.  In the past I was able to add an exception, but now that option is not available, even under advanced.  Moreover, I'm now unable to even view the certificate information via the 'lock' icon.

Have there been changes in this area?  Does something need adjustment in the about:config?

**Comment by MrAlex94** [comment]
Is this on classic or current? Neither should stop you from doing this though.

**Comment by Squall-Leonhart** [comment]
depends on the nature of the expiration.
