### ISSUE TITLE
Waterfox Classic 2020.10 - broken setTimeout JS function.

### ISSUE THREAD

**Issue by stalker780** [MrAlex94/Waterfox#1825]
Waterfox Classic 2020.10 seems to have broken setTimeout JS function.
It cannot pass parameters to a function. It worked in older versions of Waterfox/Firefox for many years.
Also it works in Firefox 60-83 and other modern browsers.

OS: Windows 10

https://jsfiddle.net/g39scL1q/1/

**Comment by hawkeye116477** [comment]
I can't reproduce that. It works fine on my end.

**Comment by stalker780** [comment]
Hmmm... Strange. I will check on another PC

**Comment by stalker780** [comment]
Looks like I've got problems with one of extensions. Cause it works in safe mode.

Closing.
