### ISSUE TITLE
Windows: Waterfox G3.0.0.1 installer hijacks .pdf extension to itself without asking

### ISSUE THREAD

**Issue by SuperHirmu** [MrAlex94/Waterfox#1826]
Install Waterfox G3.0.0.1 on Windows 7 (up to date with November 2020 updates - extended support regime).

Adobe Acrobat DC installed as default for PDF files. Except after WF G3 installation, all .pdf files now open on Waterfox! :-1: 

I certainly did not ask that to happen during or after install, just FYI. Oh well, I went back to WF Classic; little quirks like that .pdf hijacking and bigger dealbreakers such as: "Tabs cannot be placed below bookmarks", and "distinct lack of Multirow Tabs" aren't helping.  :-1: :-1: :-1:

**Comment by tcreek** [comment]
Most modern browsers now days will load the PDF in a tab

**Comment by SuperHirmu** [comment]
I'm sure they do. However, when you're browsing _local files_, and you have dedicated app (Adobe Acrobat) to open .pdf with, surely you don't want to trade it for a rogue web browser appropriating .pdf extension to itself without even asking.
