### ISSUE TITLE
Auto copy within script

### ISSUE THREAD

**Issue by DLoper** [MrAlex94/Waterfox#1830]
We have an application that automatically copies information when right clicking on the line it is listed in.  This function does not work in Waterfox, it does work in Firefox, Chrome and others.   The report is as follows:  document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.

C;an you give me any insight as to how to fix this?  I do not know if it is something that can be addressed from the browser level or if it will need to be addressed in the application.  The vendor for this application is willing to implement whatever needs to be implemented to fix.

Thanks!
Don

**Comment by hawkeye116477** [comment]
> This function does not work in Waterfox

Waterfox Current or G3 or Classic? In case of Classic [Async Clipboard API](https://bugzilla.mozilla.org/show_bug.cgi?id=1461465) isn't implemented, so that's may be the problem. So it will work only if document.execCommand is executed inside event handlers.
