### ISSUE TITLE
Youtube is 99% dead in Classic

### ISSUE THREAD

**Issue by psonnosp** [MrAlex94/Waterfox#1832]
**Describe the bug**

In safe mode the mainpage looks like this
![Untitled-1](https://user-images.githubusercontent.com/28609335/99889188-eec8a780-2c52-11eb-97d1-a004116bda25.png)
Just empty grey shapes and nothing can be clicked.

And the [video page](https://www.youtube.com/watch?v=R8SZtNhL_W4)s look like this
![Untitled-2](https://user-images.githubusercontent.com/28609335/99889230-5979e300-2c53-11eb-9478-8d124674c6c7.png)
The video plays and controls work but that's it, you can't scroll or click a thing outside the window.

**To Reproduce**

1. Go to https://www.youtube.com/ and https://www.youtube.com/watch?v=R8SZtNhL_W4
2. Voilá!

**Expected behavior**

That the pages load in full and work as in any other browser.

**Screenshots**

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: Classic 2020.10 x64

**Additional context**

**Comment by Squall-Leonhart** [comment]
WFM.

**Comment by psonnosp** [comment]
WFM?

**Comment by tcreek** [comment]
May want to try a new profile. WFM (Works for Me).

**Comment by psonnosp** [comment]
It was the user agent switcher addon that was FUBAR and the setting was in place even when WF was restarted with all addons disabled but a reinstall fixed it.
Sorry for bothering you ;)
