### ISSUE TITLE
kaggle.com doesn't load

### ISSUE THREAD

**Issue by OzoneReloaded** [MrAlex94/Waterfox#1833]
**Describe the bug**
https://www.kaggle.com/ doesn't work properly. Page resets after a few seconds of loading.

**To Reproduce**
1. Go to 'https://www.kaggle.com/'

**My configuration**
 - OS: Windows 10
 - Version: Waterfox Current 2020.10 (64 bit)

**Comment by OzoneReloaded** [comment]
Could someone confirm please?

**Comment by hawkeye116477** [comment]
I can confirm, but Waterfox Current is EOL, so this won't be fixed. You will need to migrate to Waterfox G3.

However that bug is also on Waterfox Classic.

**Comment by OzoneReloaded** [comment]
> 
> 
> I can confirm, but Waterfox Current is EOL, so this won't be fixed. You will need to migrate to Waterfox G3.
> 
> However that bug is also on Waterfox Classic.

I didn't know about existence of G3 at all and thought Current is the main branch. Thank you!

**Comment by tcreek** [comment]
I can confirm with Waterfox Classic on Linux and Windows 10

**Comment by hawkeye116477** [comment]
Looks like, this should be implemented => https://bugzilla.mozilla.org/show_bug.cgi?id=1374612 to fix that.

**Comment by tcreek** [comment]
Kaggle seems to display now in 2021.04.02
