### ISSUE TITLE
Waterfox Classic 2020.10 can no longer operate Gitea sites

### ISSUE THREAD

**Issue by IzzySoft** [MrAlex94/Waterfox#1836]
**Describe the bug**
I don't know when exactly this started, but with WF Classic it's no longer possible to use drop-downs in Gitea. Tried this with codeberg.org as well as with self-hosted Gitea (running Gitea 1.12.6) and their test instance at try.gitea.org. No dice, even with a fresh profile (so addons are ruled out as cause). Errors in the console range from CSP errors (disabling CSP does NOT solve it) to different JS errors.

Cross-checking with other browsers (I tried recent TOR browser and Chromium against codeberg.org, Codeberg team tried different other browsers like the latest Firefox) did not reproduce the issue, so it's definitely bound to Waterfox.

**To Reproduce**

1. Go to any Gitea instance (e.g. https://try.gitea.io/ – bugmenot has some logins)
2. Log in
3. Try to open any of the drop-downs (there are eg. 2 in the upper-right corner)
4. See error -- ahem, see nothing: the drop-down does not open.

**Expected behavior**

Drop-Down should open, permitting e.g. access to one's profile, settings, logout etc.

**My configuration** 

 - Device: PC
 - OS: Linux Mint 18.3 (LTS)
 - Version: Classic 2020.10

**Additional context**

All those drop-downs are driven by JavaScript.

**Comment by IzzySoft** [comment]
PS: Work-around for others affected by this is DISABLING Javascript for the specific site. Menues become accessible again (turned into CSS menues it seems). Verified this for codeberg.org and my self-hosted Gitea instance.

**Comment by hawkeye116477** [comment]
I can't reproduce that.

**Comment by IzzySoft** [comment]
Now I'm baffled. I can even reprodice it in a fresh profile, and tried it against any Gitea instance known to me. It worked before (as I wrote, I'm not sure at what time these issues started). So what else could I try to narrow it down? You did try with Classic @hawkeye116477, not just Current, right? And with Javascript enabled for the Gitea sites? And while logged in (those drop-downs are not visible otherwise)?

**Comment by hawkeye116477** [comment]
Yes, Classic, Javascript is enabled for all sites and logged in with GitHub account. Maybe something is wrong only on your side, bad ISP or something else.

**Comment by IzzySoft** [comment]
Which causes something like

    SyntaxError: expected expression, got keyword 'import'[Learn More]         stlview.js:11:8
    Content Security Policy: The page’s settings observed the loading of a resource at https://codeberg.org/js/eventsource.sharedworker.js (“child-src 'none'”). A CSP report is being sent.

when I enable Javascript in Waterfox Classic – but not in other browsers? I'm open for ideas what I could try – but "bad ISP" sounds a bit unlikely to me (not that I could try with some other ISP to verify that).

"Something wrong on my side" was one of the first things I assumed, and hence tried with a new profile as well as with other browsers… But if it works in all browsers but WF – and in the latter not even in a fresh profile, I've no idea what I could try or what on my end it could be.

**Comment by hawkeye116477** [comment]
> SyntaxError: expected expression, got keyword 'import'[Learn More]         stlview.js:11:8

I also see that on `codeberg.org`, but drop-downs works. However on Gitea no errors.

**Comment by IzzySoft** [comment]
Thanks! So one thing ruled out (I thought that might have been the culprit).

Pretty strange. Well, at least I can use described work-around (though I can no longer log out – that's the only menu entry being JS itself). Wish I knew how to further track this down, I'm out of ideas. Looks like something specific to *my* Waterfox installation then – as it works with Classic for you, with other browsers even for me, but with Classic reproducible happens to me with each and every Gitea instance I try, even in a fresh profile…

> However on Gitea no errors.

Indeed that specific error is only shown on Codeberg.org (which btw runs Gitea). With my self-hosted instance I see a different error (`DOMException [SecurityError: "The operation is insecure."` in 2 different places) which is not present on Codeberg. But nowhere the drop-downs work, unless I disable Javascript.

Though it might be unrelated, on what OS did you try?

**Comment by hawkeye116477** [comment]
@IzzySoft Linux (Manjaro).

**Comment by IzzySoft** [comment]
Thanks! So it theoretically *could* be related to Mint, though I doubt it… Well, should I find something, I'll update. Meanwhile, maybe some other Mint users can confirm (or state the opposite).

**Comment by IzzySoft** [comment]
OK, now it gets really funny: I just tried it on another machine of mine, also running Mint 18.3 with Waterfox Classic 2020.10 – and cannot reproduce the issue there either! I'm totally clueless what else to check. Going from here I'd usually start with a fresh profile on the affected machine – but I already did that without success. Hints and ideas are much welcome!

(vague hope: 2020.11 might be coming soon – maybe it fixes itself, wouldn't be the first time)

**Comment by Squall-Leonhart** [comment]
purge the machines dns cache and any host file like things.

**Comment by IzzySoft** [comment]
@Squall-Leonhart thanks – good idea, as it seems to be a "local thing" bound to this one installation.

But DNS cache would not explain the problem existing for my local, self-hosted instance, having a fixed local IP that did never change. No external resources involved. And if it were *the machine's* DNS cache, other browsers should show the same problem (which they do not).

**Comment by IzzySoft** [comment]
Just for a last note: I never figured what the culprit was. Still using Classic as my main driver, I switched to G3 for Github/GitLab/Gitea meanwhile. All works fine there.
