### ISSUE TITLE
G3 breaks Slack

### ISSUE THREAD

**Issue by nofishonfriday** [MrAlex94/Waterfox#1840]
Hi, 

just updated to G3 and now I get this when trying to enter a [Slack](https://slack.com/) workspace:
![G3vsSlack](https://user-images.githubusercontent.com/7658194/100104351-599dfc80-2e66-11eb-9a01-1396a45ce648.jpg)

Worked fine with the Waterfox version I used before (latest non G3 version), I'm on Win 8.1.
(I know I can use the Slack app as workaround, just thought it would be nice to make it working again also in Waterfox if there's a possibility).

Thanks for the work you do with Waterfox. :)

**Comment by MrAlex94** [comment]
Has been fixed in G3.0.1 :-)

**Comment by nofishonfriday** [comment]
Fix confirmed, thank you.
