### ISSUE TITLE
Waterfox G3 Does not show window or close fully

### ISSUE THREAD

**Issue by Captain-ALM** [MrAlex94/Waterfox#1841]
**Describe the bug**
When starting waterfox, the window does not show and another attempt to start it has to be made for the window to show.
Also, when closing all open windows waterfox remains open in the background (However explicitly pressing quit in the menu does terminate it).

**To Reproduce**

_Not opening straight away_
1. Attempt to start waterfox when it is not running at all (EG: After a restart or full quit)
2. No windows will show
3. Attempt another launch and a new window will show

_Not fully terminating_
1. Close all open windows
2. Check running processes, waterfox is still running (And on windows '- appversion' is appended)

**Expected behavior**
A new window should show when the browser is launched.
When all windows are closed, waterfox should not have any processes running.

**Screenshots**
![Screenshot from 2020-11-25 16-55-52](https://user-images.githubusercontent.com/32275498/100259417-1912b180-2f40-11eb-92c0-942ee6a5e420.png)
![scrnshot](https://user-images.githubusercontent.com/32275498/100260237-15cbf580-2f41-11eb-9264-f31bd936aabe.png)

**My configuration** 
 - Device: PC
 - OS: Windows 10 20H2
 - Version: G3.0.0 (G3.0.0.1)

**Also tested with configuration**
 - Device: PC
 - OS: GNU\Linux Debian Buster Stable
 - Version: G3.0.0 (G3.0.0.1)

**Additional context**
Tested on both Windows 10 and Debian Linux with behavior being the same.

Attached below are the terminal logs for the browsers on both operating systems:
[waterfoxconsolelogwindows.log](https://github.com/MrAlex94/Waterfox/files/5598084/waterfoxconsolelogwindows.log)
[waterfoxterminallogdebian.log](https://github.com/MrAlex94/Waterfox/files/5598115/waterfoxterminallogdebian.log)

It also looks like someone raised it on reddit as well:
[https://www.reddit.com/r/waterfox/comments/jzo4fn/waterfox_g3_stays_in_memory_after_i_close/](https://www.reddit.com/r/waterfox/comments/jzo4fn/waterfox_g3_stays_in_memory_after_i_close/)

**Comment by MrAlex94** [comment]
Hi! Could you test out [this build](https://cdn.waterfox.net/releases/tests/waterfox-78.5.0.en-US.win64.installer.exe) for Windows? If you override the install at `C:/Program Files/Waterfox Current` it should (hopefully) fix most of your issues.

When the final release is out you can just override the install again.

**Comment by Captain-ALM** [comment]
Hello,
Thank You, the test build works!

**Comment by Captain-ALM** [comment]
Also, the latest release (3.0.1) works on Debian as well.

**Comment by Captain-ALM** [comment]
Closing as the release is out.
