### ISSUE TITLE
G3 fails to launch on El Capitan & ruins user profile for older versions

### ISSUE THREAD

**Issue by BezzleBedeviled** [MrAlex94/Waterfox#1843]
Normally this wouldn't be a problem (nobody expects new software to always run on legacy OSes), except that Waterfox Current's immediately prior versions not only don't ask (by default) before upgrading, but fail to test/sandbox the launch.

**Comment by GJRobert** [comment]
+1
Waterfox G3 officially requires only macOS 10.10, but it does not run on my El Capitan either.

Message when running from command line:
```
Minimum OS version requirement not met!
```

My profile from Classic remains intact, though.

**Comment by GJRobert** [comment]
Duplicate of #1839

**Comment by GJRobert** [comment]
Duplicate of #1839
