### ISSUE TITLE
Upgrading to G3 might be super buggy

### ISSUE THREAD

**Issue by ibeladi-mrsool** [MrAlex94/Waterfox#1844]
**Describe the bug**

Upgrading to G3 might be super buggy

**To Reproduce**

Non-approved self-upgrading

**Expected behavior**

Asks to upgrade

**Screenshots**

N/A

**My configuration** 
 - Device: PC
 - OS: Linux Mint
 - Version: Classic -> G3

**Additional context**

Until G3 is fully ready, the upgrade should not be forced, and should show a warning.
After first surprise run of G3, I saw a new and clean profile, I had to go to the file system to make changes to point to the old profile.
Also, I encountered a crash that rendered the browser semi-useless after recovery, did not fully-recover and was in a state in which most users will just drop it and find an alternative.

So, again; Until G3 is fully ready, the upgrade should not be forced, and should show a warning, and I would rather having it optional at all times (with the warning of G3 not ready to upgrade to)

**Comment by MrAlex94** [comment]
Hey Ibrahim

Thanks for the feedback - I think I have managed to resolve most of the issues now. Would you mind testing [here](https://cdn.waterfox.net/releases/tests/waterfox-78.5.0.en-US.win64.installer.exe)? The build is unsigned, but should run. If you override the install at C:/Program Files/Waterfox Current - it should allow you to switch profiles and set your old as default again!

When the final release is out you can just override the install again.

**Comment by ibeladi-mrsool** [comment]
You are all welcome. 
I will try it later on, when I have my computer nearby.
BTW, I am using Linux Mint.

**Comment by MrAlex94** [comment]
Ibrahim, I have pushed out G3.0.1 if you'd like to give it a try and see how it works for you. Should resolve the above issues.
