### ISSUE TITLE
Windows 10 G3 2 clicks of shortcut needed to start browser

### ISSUE THREAD

**Issue by RPYoshi** [MrAlex94/Waterfox#1847]
**Describe the bug**
Nuisance not bug. On a fresh power on of Windows it takes two tries to open Waterfox. The first time starts many "Waterfox -APPVERSION" background processes but no window appears. The second time starting brings up the window and moves the background processes to the main Apps section in Task Manager. When I close all windows the remaining processes get sent back to background section. Only requires one click on Waterfox shortcut to open a new window again.

**To Reproduce**
1. Restart Windows
2. Click Waterfox shortcut
3. *Nothing shows up*
4. Click Waterfox shortcut again
5. Window appears

**Expected behavior**
Old behavior starts Waterfox on first click. I would assume this is the correct behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/6041818/100479636-d1fdfb00-30bc-11eb-9680-23aebda1dbe3.png)

![image](https://user-images.githubusercontent.com/6041818/100479512-7895cc00-30bc-11eb-8e50-7d61a9d3df63.png)

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: G3 64-bit (screen shot attached)

**Additional context**
I have not reset my configuration from the most recent release, however I did reset my configuration for version Current 2020.07.1 when there was a search bar bug.

**Comment by Captain-ALM** [comment]
#1841

**Comment by Captain-ALM** [comment]
This seems to be fixed for the latest version (3.0.1) which as of now can be manually downloaded from the Waterfox website.
Although installing it over an ugraded Waterfox Current install needs the install path set manually.
[https://www.waterfox.net/blog/waterfox-G3.0.1/](https://www.waterfox.net/blog/waterfox-G3.0.1/)

**Comment by RPYoshi** [comment]
Great, I couldn't find the previous issue before. Sorry for the disturbance.
