### ISSUE TITLE
Site allo.ua don`t work on Classic

### ISSUE THREAD

**Issue by Viator76** [MrAlex94/Waterfox#1853]
OS:Windows 10 Pro 1909,
Browser:Waterfox Classic 2020.10

1)Opened allo.ua see OK,
2)Opened https://allo.ua/ua/tradein/ or https://allo.ua/ua/planshety-i-gadzhety/ or https://allo.ua/ua/naushniki-i-akustika/ etc... css problems, on G3 OK.

**Comment by hawkeye116477** [comment]
That should be fixed on Classic 2020.12.

**Comment by MrAlex94** [comment]
Please re-open if not.

**Comment by Viator76** [comment]
Don`t work!
http://imglink.ru/show-image.php?id=99700672806e7fa6ac7d28dc277b48bb
http://imglink.ru/show-image.php?id=3cf6f6f77aef9810bce3358c544e8c71
http://imglink.ru/show-image.php?id=f3eb3fe85b63fe24d1cba6d0ec373a92

**Comment by Viator76** [comment]
<a href='http://imglink.ru/show-image.php?id=99700672806e7fa6ac7d28dc277b48bb'> <img src='http://imglink.ru/thumbnails/18-12-20/c0dc83628359a9c38ec167f988aec4cc.jpg' alt='хостинг картинок' border='0'> </a>
<a href='http://imglink.ru/show-image.php?id=3cf6f6f77aef9810bce3358c544e8c71'> <img src='http://imglink.ru/thumbnails/18-12-20/b13f61dd7e1ec8777054c38ed5e4e1c1.jpg' alt=' выложить фото' border='0'> </a>
<a href='http://imglink.ru/show-image.php?id=f3eb3fe85b63fe24d1cba6d0ec373a92'> <img src='http://imglink.ru/thumbnails/18-12-20/543b0e55b3767265422a8355ae657de6.jpg' alt='фотохостинг' border='0'> </a>

**Comment by hawkeye116477** [comment]
Ok, by looking again `https://allo.ua/ua/tradein/` is working fine, other subpages isn't, looks like I missed something or maybe they changed something again.
