### ISSUE TITLE
G3 waterfox.exe description shows 'Waterfox -APPVERSION'

### ISSUE THREAD

**Issue by SaltfishAmi** [MrAlex94/Waterfox#1854]
**Describe the bug**
**Screenshots**
![Capture](https://user-images.githubusercontent.com/14184974/100761552-001d6b00-342e-11eb-9602-78a01cd805e9.PNG)
![Capture2](https://user-images.githubusercontent.com/14184974/100761584-057ab580-342e-11eb-8a90-ff128ec039fb.PNG)

I don't think any further explanation is necessary.

**My configuration**
 - Device: PC
 - OS: Windows 10
 - Version: both G3.0.0 and G3.0.1 have this issue

```
File: C:\Program Files\Waterfox\waterfox.exe
Size: 558944 bytes
MD5: EF6D407165EA49619818C7608F77F121
SHA1: 4D002209CC763478713D3DD840C788D7419C3BC9
```

**Comment by MrAlex94** [comment]
Aware of the issue - there was an update to Visual Studio which caused this weird bug, still investigating it.

**Comment by MrAlex94** [comment]
Fixed with https://github.com/MrAlex94/Waterfox/commit/28aef7046ceb10418f07b0b15fc51da080e366fb
