### ISSUE TITLE
Unable to Enable TabMix Plus on G3

### ISSUE THREAD

**Issue by tcreek** [MrAlex94/Waterfox#1855]
I according to the Firefox site:

 xpinstall.signatures.required to false & extensions.langpacks.signatures.required to false should allow unsigned Add-Ons to be enabled
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

Looking in about:config, I see both are set to FALSE, but yet I am enable to enable Tab Mix Plus

![TabMix](https://user-images.githubusercontent.com/4149717/100797782-48b23580-33e8-11eb-8062-b5a07739c414.JPG)

**Comment by MrAlex94** [comment]
Tab Mix Plus doesn't work on G3, which is why. It only works on classic.

**Comment by hawkeye116477** [comment]
Please check out https://bitbucket.org/onemen/tabmixplus/issues/2/bring-tmp-legacy-to-ff78-and-so-the and https://github.com/onemen/TabMixPlus/pull/1.

**Comment by tcreek** [comment]
Is not Tab Mix Plus a NPAPI add-on which FireFox dropped support for ?

![Screenshot from 2020-12-04 11-19-13](https://user-images.githubusercontent.com/4149717/101193748-a762f380-3622-11eb-999d-d64ac7e0a895.png)

The main page does not say for (For Waterfox Classic only), and the download link take you to the newest current version of Waterfox.

Maybe either clarify the main web site page, or reopen this

**Comment by hawkeye116477** [comment]
@tcreek Plugin isn't same thing as extension. Tab Mix plus is „legacy" (XUL/XPCOM) extension, not NPAPI plugin.

```
http://forums.mozillazine.org/viewtopic.php?f=8&t=2121149
https://anydifferencebetween.com/difference-between-plugins-and-extensions/
```
