### ISSUE TITLE
Waterfox stopped working on Ubuntu 18.04

### ISSUE THREAD

**Issue by pwegr** [MrAlex94/Waterfox#1856]
I see this message when I try to run Waterfox:

XPCOMGlueLoad error for file /home/user/Programs/waterfox/libmozsqlite3.so:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/user/Programs/waterfox/libmozsqlite3.so)
Couldn't load XPCOM.

Few days ago it was working ok. 
In application.ini it says it is 
Version=78.5.0
BuildID=20201118170824

I hope I don't have to install new glibc

**Comment by hawkeye116477** [comment]
What is written on official website?

![2020-12-03_15-49](https://user-images.githubusercontent.com/19818572/101044037-3c141580-357f-11eb-9fe4-e836d516da59.png)

So it's not a bug, it's a feature :smile:

If you want to make sure that Waterfox will work fine for your distro, then there are unofficial AppImage packages (compatible with glibc 2.17+) and repositories with deb and rpm packages.

**Comment by pwegr** [comment]
Thanks for pointing that out. So it seems that with one of the recent updates official Waterfox dropped support for Ubuntu 18.04.
