### ISSUE TITLE
waterfox classic and g3 resilio sync display issue

### ISSUE THREAD

**Issue by smeveriss** [MrAlex94/Waterfox#1862]
Hi.
In both these brousers latest versions, when running resilio server in nvda, only part of the tree is detecteed.
Either the top menu with options to add things, or the end of the screen.
I can't navigate down or up with curser, but when tabbing things do display, the options and extras don't seem to work either.
version 08 of classic doesn't do this.
For the most part issues I have had with websites seem to be gone bar the hp support website which likes to crash waterfox, however the hp website has a lot of stuipidness when accessing its support even in 08, and uses to much power as it is and it likes to do bad things even to me so well its a lot better than it used to.
I can't see any options, or anything on the screen with the newer version yet on 08 it all works.
Does this have to do anything with the web components and other such things?

**Comment by smeveriss** [comment]
Adding to this issue, I have managed to get resilio sync to render properly at times, however if say there is an error, after fixing it and refreshing the page then does not render right.
Sometimes I can  get it back with a closing and restarting of windows.
The other big issues for me are the hp support website.
It just doesn't want to get the all the frame with all the drivers in it.
You can produce this with nvda loaded but maybe if you go to support.hp.com, click drivers and enter a notebook or whatever number in to the input box, my code is 4nz14pa for example, click the open drivers button and then open all and things seem to be all over the place, text, links, etc.
I am convinced that this is some sort of focus issue.
The other thing to watch out for is after brousing for a while and entering a heavily scripted website like hp.com, dropbox.com, skype.com, etc, waterfox will lock up completely and will need to be closed.
That site will work well afterwards but only if the brouser is restarted spaciffically for that site or group of sites, and shut down.
The biggest issue is the rendering of the hp site.
I also see this in addons manager when after making changes the manager will show up as lank and I need to close and reopen the app for things to do whatever.
Compaired to pree g3 and classic 2020.10 though this version really tries hard to be stable.
I currently use classic 202012, and have a copy of 08 portable for the sites that don't play nice with it.
I have learned that edge chromium will work for some more sites so well that may be it.
I'd post this all on reddit but unfortunately after seemingly authorising via google, reddit refuses to aknowledge its logged in.

**Comment by candrapersada** [comment]
why waterfox classic does not sync addons?
