### ISSUE TITLE
Waterfox classic crashes when open AAC Bitstream

### ISSUE THREAD

**Issue by alice0775** [MrAlex94/Waterfox#1863]
**Describe the bug**
Waterfox classic, tab crashes when open  AAC Bitstream

Build ID: 20201208163116
User Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3

**To Reproduce**
1. Open https://www2.iis.fraunhofer.de/AAC/multichannel.html
    or direct open https://www2.iis.fraunhofer.de/AAC/7.1auditionOutLeader_v2_rtb.mp4

**Expected behavior**
No crash

**Screenshots**
NaN

**My configuration** 
 - Device: PC
 - OS: Windows 10 Home version 1909 64bit
 - Version: Classic 2020.12

**Additional context**
Regression window:
  Good: Waterfox56.2.13
  Bad: Waterfox Classic 2020.01.1

**Comment by hawkeye116477** [comment]
It's probably this => https://bugzilla.mozilla.org/show_bug.cgi?id=1509875, 2/3 parts already done, only updating libcubeb left.
