### ISSUE TITLE
Waterfox Classic 2020.12 crashes when sigin in google.

### ISSUE THREAD

**Issue by sungnix** [MrAlex94/Waterfox#1864]
**Describe the bug**
Waterfox Classic 2020.12 crashes when sigin in google.
The Waterfox dosen't crash, but the tab crashes.

**To Reproduce**
1. Go to 'https://google.com'
2. Click on 'SIgn in'
3. See error

**Screenshots**
https://i.imgur.com/uSZM8df.gif

**My configuration**
 - Device: MacBook Air (M1, 2020)
 - OS: macOS Big Sur Version 11.0.1
 - Version: Classic 2020.12/56

**Comment by Shumaher** [comment]
also this version is not compatible with vk.com. there is no way to send a message. so I rollback to 2020.09 for now.
I'm too lazy to create another issue about this, sorry)

**Comment by MrAlex94** [comment]
Assuming you're running via Rosetta? `Classic` is built with `-march=core2 -mtune=core2` - I assume Rosetta can't translate SSE3+ calls?

**Comment by zhouhui-monstar** [comment]
> Assuming you're running via Rosetta? `Classic` is built with `-march=core2 -mtune=core2` - I assume Rosetta can't translate SSE3+ calls?

Yes, I'm runing Waterfox Classic by rosetta.
If I uncheck 'Open using Rosetta', Waterfox Classic can not be launched.

**Comment by zhouhui-monstar** [comment]
> Assuming you're running via Rosetta? `Classic` is built with `-march=core2 -mtune=core2` - I assume Rosetta can't translate SSE3+ calls?

Yes, I'm runing Waterfox Classic by rosetta.
If I uncheck 'Open using Rosetta', Waterfox Classic can not be launched.

**Comment by sungnix** [comment]
> Assuming you're running via Rosetta? `Classic` is built with `-march=core2 -mtune=core2` - I assume Rosetta can't translate SSE3+ calls?

Yes, I'm runing Waterfox Classic by rosetta.
If I uncheck 'Open using Rosetta', Waterfox Classic can not be launched.
