### ISSUE TITLE
Calling document.open/write in srcdoc when onload is called (which does document.open) will throw NS_ERROR_MALFORMED_URI

### ISSUE THREAD

**Issue by edanp** [MrAlex94/Waterfox#1867]
**Describe the bug**
Waterfox Classic 2020.12 (64-bit) - Linux
I had the "NS_ERROR_MALFORMED_URI" when calling window.open/write inside an iframe with srcdoc

**To Reproduce**
1. Run the HTML: `<iframe srcdoc="<script>window.onload=function(){document.write('hello');};</script>"></iframe>`
2. See error

**Expected behavior**
See an iframe with "hello"  (for first example)

**Actual behavior**
JavaScript error: about:srcdoc, line 1: NS_ERROR_MALFORMED_URI

Another HTML example producing same error using document.open()
`<iframe srcdoc="<script>window.onload=function(){var iframe = document.createElement('iframe');document.body.appendChild(iframe);iframe.contentDocument.open();iframe.contentDocument.close();};</script>"></iframe>`

**Additional context**
I tracked down the Firefox bug report. It was fixed on later versions and hoping it can also be fixed in waterfox.
https://bugzilla.mozilla.org/show_bug.cgi?id=1421137
https://bugzilla.mozilla.org/show_bug.cgi?id=1368005
https://bugzilla.mozilla.org/show_bug.cgi?id=1489308

**Comment by neutrino38** [comment]
As curiosity, I looked at the fixes and it seems to me that they are quite complex. For example fix of bug 

https://bugzilla.mozilla.org/show_bug.cgi?id=1489308

Resulted in the following commits

https://hg.mozilla.org/mozilla-central/rev/6f00a2d89b5f
https://hg.mozilla.org/mozilla-central/rev/f2b0ceb55ced
https://hg.mozilla.org/mozilla-central/rev/b393e04da7e9
https://hg.mozilla.org/mozilla-central/rev/015db4a424d9
https://hg.mozilla.org/mozilla-central/rev/6504b5468b32
https://hg.mozilla.org/mozilla-central/rev/c1113b00d864
https://hg.mozilla.org/mozilla-central/rev/2166dac4d26c
https://hg.mozilla.org/mozilla-central/rev/8e1196296ad4
https://hg.mozilla.org/mozilla-central/rev/5fbeaa1c3997
https://hg.mozilla.org/mozilla-central/rev/a01586b62cf5

It's way above my abilities to merge such a change.
