### ISSUE TITLE
Waterfox Classic 2020.10 says it's up to date

### ISSUE THREAD

**Issue by 4meters** [MrAlex94/Waterfox#1869]
**Describe the bug**
No update available for Waterfox Classic 2020.10 via built-in browser updater.

**To Reproduce**
1. Go to 'Help'
2. Click on 'About Waterfox'
3. See that Waterfox checks for updates and show it is up to date but in fact it isn't

**Expected behavior**
Update to Waterfox Classic version 2020.12 should show and it should be possible to install it.

**Screenshots**
https://imgur.com/a/NnvvOai

**My configuration** 
 - Device: Desktop PC
 - OS: Windows 7 x64 Home Premium SP1
 - Version: Classic 2020.10

**Additional context**
Updates worked before there is problem only with automatic update from 2020.10 to 2020.12

**Comment by MrAlex94** [comment]
Has been fixed.
