### ISSUE TITLE
Cannot save page as html only

### ISSUE THREAD

**Issue by rebop** [MrAlex94/Waterfox#1878]
**Describe the bug**

Cannot save selection as html only

**To Reproduce**
This is something I use. Works perfectly in Classic. Did not work in Current and I added the bug. Never fixed.

1. Export some or all of your bookmarks as HMTL
2. Open that file
3. Select some of those bookmarks
4. Right click on selection and choose :view selection source"
5. A new tab opens. Choose File, save page as
6. Choose any name .htm and save page as html ONLY

In Classic, the page appears in the saved location. In Current or G3, nothing appears in the saved location.

**Expected behavior**
A file named xxxx.htm will be created in your saved location with the subset of bookmarks you have selected.

**My configuration** 
 PC - Win 7 and 10
Classic 2020.12 WORKS
Current G3.02? Latest Does Not

**Comment by InvisibleManX** [comment]
Might I ask you, why would you need to perform such a peculiar set of actions in the first place, even if it did work? 

Saving a page as HTML only works just fine, if you do it after opening some html page on the internet, 
just as it's supposed to work.

**Comment by rebop** [comment]
First, apologies. Should have been "Cannot save a selection on a page as html Only". Can, indeed, save entire pages.

Now this actually is an elegant solution for an issue I have.

I have two laptops. One personal, one work.  I have tons of bookmarks and folders in bookmarks in both. A lot.

On the work laptop I keep only business bookmarks. On the personal, I keep both business and personal bookmarks.

If I am out working on my personal laptop and delete, update, change, add a business bookmark I will eventually want to add or update those to the business computer.

So, I will export all bookmarks from personal to html. Then open the html in a browser (G3 for this discussion). I then select the folders and bookmarks I want to change, edit, copy on that page.

Right click and view selection source. Save page as HTML Only.

Now, when I open the business laptop and import that file, it imports only those bookmarks I wanted to update. If it imports a FOLDER 1 and I already have a FOLDER 1, then deleting the existing on the businesses laptop gives me the current folder with updated bookmarks.

Works so well.

Works in Classic.

Used to work in Firefox - have not tried since I moved to Waterfox years ago.

**Comment by InvisibleManX** [comment]
@rebop 
I see. 

In this case, I would suggest an alternative way of doing so. 

I personally would organize it this way: Keep a separate folder called "BUSINESS" on a personal laptop, inside of which I'd have a structure of subfolders and business bookmarks only. 

After doing so, you can manage all business related bookmarks inside that "BUSINESS" folder. 

And once you need to import all business bookmarks into your business laptop's browser, 
you simple do this: 

1. Export your public browser bookmarks into JSON format backup. 
2. Open a bookmark manager window inside a browser, then select and remove every bookmark but that "BUSINESS" folder. 
3. If you need to get rid of that BUSINESS folder, you may select all subfolders and bookmarks inside it, choose "Cut" and then go to a root folder of bookmarks and choose "Paste" and after it's done, get rid of the empty  BUSINESS folder. 
4. Export all your current bookmarks as a separate backup (HTML or JSON, whichever works), and use that backup to import all those bookmarks to your business laptop. 
5. Remove all your bookmarks from a public laptop's browser, and then import back the original backup you made in the very beginning. 

As a result, you'll have your public laptop's browser the way it was, and all your business related bookmarks and folders would be imported into your business laptop.

**Comment by rebop** [comment]
I gave one example. There are others. The solution works so well for me on all of the situations I need to prune, move, copy, etc my bookmarks so I am afraid your solution will not work for me.

And since this works in Classic, why cannot it not be turned on, or patched, or made to work in Current?
