### ISSUE TITLE
'Ripple' effect when Scrolling through Pages

### ISSUE THREAD

**Issue by ZN0N15** [MrAlex94/Waterfox#1881]
**Describe the bug**

Constant Ripple effect when scrolling through any website ranging from sites that are Articles, Socials, Video/Media Platforms etc. 

At First I thought that the issue was my Compositor [Picom ](https://github.com/jonaburg/picom), I've messed with the config and made sure Vsync was on with/without experimental-backends and I've even gone to test other Browsers such as Firefox, Brave, Chromium, Vivaldi, Edge-dev and all of them don't seem to have the same Issue I'm having with Waterfox. 

To make it very clear, these Ripple effects Aren't like normal Screen Tearing where it's One Big tear on screen in each frame like not having Vsync. Instead, its Small Multiple screen tears in a row which makes it look like a Wavy Rippling effect when Scrolling (Honestly "Screen Tearing" is the closest description I can make out of it, because frames kind of shift either up or down when scrolling causing it to "Ripple" in a smooth way, and the "tearing" aspect is the thing that isn't noticeable). And it only happens when I scroll Slowly, when I scroll very fast it's barely noticeable but it's still visible when looking at it carefully.

I tried a fresh install, including the Classic version and the issue is definitely there. I've tried with or without extensions, and even with default settings it's still visible. I tried replicating the issue with other browsers like the ones I mentioned above but I can't seem to reproduce it at all, so it's only happening with Waterfox.

**To Reproduce**
1. Go to pages that are Article based, Socials (like FB/Twitter/Insta) Video Plats(Like YT/Twitch) etc.
2. Scroll **Slowly**, Up or Down through the page

**Expected behavior**

Smooth Scrolling. No Screen Tearing or Ripple effects.

**My configuration** 
 - Device: PC/HP Laptop
 - OS: Arch Linux
 - Kernel: 5.4.74-1-lts

**Additional context**

It does not seem to matter how Heavy the website is. I've gone through pages where it's only Text and no images visible at all, and the ripple effect is still very visible when scrolling.

**Comment by hawkeye116477** [comment]
Which Waterfox version and is it G3, Current (G3 replaces Current) or Classic?

**Comment by ZN0N15** [comment]
> Which Waterfox version and is it G3, Current (G3 replaces Current) or Classic?

I've tried both G3 and Classic. I also tried Current version which I installed from the [AUR](https://aur.archlinux.org/packages/waterfox-current-git/) and it's the same. Currently I have G3 installed. And I'm having trouble trying to get a proper screenshot to show what it actually looks like. 

I've been trying to fiddle with my compositor for a while now and I can't seem to figure out the issue, and I can't replicate it from other Browsers, especially chromium based ones, which makes me believe that this is indeed an issue on waterfox.

**Comment by Squall-Leonhart** [comment]
its not a waterfox issue, its the entire incorrect as heck mozilla vsync implementation.

**Comment by ZN0N15** [comment]
> its not a waterfox issue, its the entire incorrect as heck mozilla vsync implementation.

Really? That's weird. I don't seem to have the same issue with the latest version of Firefox. And I just tested out IceCat and Tor and I found the same issue. So the main Mozilla browser doesn't have this issue whereas other browsers based off of it Has the issue(?)...

**Comment by reallyuniquename** [comment]
@ZN0N15
Latest Firefox is v84. Waterfox is based on v56.

**Comment by silverwings15** [comment]
@reallyuniquename Waterfox G3 is based on FF ESR78

**Comment by reallyuniquename** [comment]
@mimecry That's still half a year behind.

**Comment by silverwings15** [comment]
just correcting your misinfo. half a year behind is significantly different than 2.5 years behind

**Comment by reallyuniquename** [comment]
I was mainly referencing to IceCat/Tor Browser/Classic comparison, all of them have the same issue. 

> half a year behind is significantly different than 2.5 years behind

It is not when it's still bugged.

**Comment by silverwings15** [comment]
literally wrong and still trying to argue..

**Comment by silverwings15** [comment]
if you just said, all of those browsers are based on an older version of FF, then nobody would've batted an eye. just take the L and acknowledge that your initial post was totally off base

**Comment by reallyuniquename** [comment]
I've already told you I was talking about Classic. I don't know why are you so triggered.

**Comment by silverwings15** [comment]
you weren't talking about Classic in your initial reply when you dismissively implied that half a year behind is the same thing as 2.5 years behind

also Tor Browser 10 and Icecat (depending on where you get it from) are both based on FF 78 ESR, so you still can't compare them to Waterfox Classic, unless you want to insist that 56 = 78

not my problem if you think that my politely correcting your erroneous statements makes me sound 'triggered'

**Comment by ZN0N15** [comment]
Well, seeing as this issue applies to all mozilla browsers, I managed to find a fix using a [Firefox Tweak](https://wiki.archlinux.org/index.php/Firefox/Tweaks#Enable_OpenGL_compositor) that force enables OpenGL/WebRender Compositor. Don't know why it's turned off by default, but it managed to fix the screen tearing altogether.

**Comment by reallyuniquename** [comment]
@mimecry I was talking about Classic in my initial reply as well. Chill lol.

**Comment by silverwings15** [comment]
you said "That's still half a year behind", referring to the latest Waterfox, and implying that there wouldn't be any differences between a browser based on FF 56 and another based on FF 78, even if there isn't any in this particular situation

**Comment by reallyuniquename** [comment]
> there wouldn't be any differences between a browser based on FF 56 and another based on FF 78

In relation to this issue clearly there is none, correct.
