### ISSUE TITLE
[Waterfox G3] WebGPU Fails to Build Under Archlinux

### ISSUE THREAD

**Issue by ilikenwf** [MrAlex94/Waterfox#1888]
I'm not sure what to do with this, I'd assume something on my system is too new?

```17:20.78 dom/clients/api
17:22.34 In file included from Unified_cpp_dom_webgpu1.cpp:110:
17:22.34 /media/disk/Linux/makepkg/waterfox-current-git/src/Waterfox/dom/webgpu/ipc/WebGPUParent.cpp:426:29: error: no member named '_0' in 'mozilla::webgpu::ffi::WGPUBufferBinding'
17:22.34         bgb.resource.buffer._0.buffer = entry.mValue;
17:22.34         ~~~~~~~~~~~~~~~~~~~ ^
17:22.34 /media/disk/Linux/makepkg/waterfox-current-git/src/Waterfox/dom/webgpu/ipc/WebGPUParent.cpp:427:29: error: no member named '_0' in 'mozilla::webgpu::ffi::WGPUBufferBinding'
17:22.34         bgb.resource.buffer._0.offset = entry.mBufferOffset;
17:22.34         ~~~~~~~~~~~~~~~~~~~ ^
17:22.34 /media/disk/Linux/makepkg/waterfox-current-git/src/Waterfox/dom/webgpu/ipc/WebGPUParent.cpp:428:29: error: no member named '_0' in 'mozilla::webgpu::ffi::WGPUBufferBinding'
17:22.34         bgb.resource.buffer._0.size = entry.mBufferSize;
17:22.34         ~~~~~~~~~~~~~~~~~~~ ^
17:22.34 /media/disk/Linux/makepkg/waterfox-current-git/src/Waterfox/dom/webgpu/ipc/WebGPUParent.cpp:432:34: error: member reference base type 'mozilla::webgpu::ffi::WGPUTextureViewId' (aka 'unsigned long') is not a structure or union
17:22.34         bgb.resource.texture_view._0 = entry.mValue;
17:22.34         ~~~~~~~~~~~~~~~~~~~~~~~~~^~~
17:22.34 /media/disk/Linux/makepkg/waterfox-current-git/src/Waterfox/dom/webgpu/ipc/WebGPUParent.cpp:436:29: error: member reference base type 'mozilla::webgpu::ffi::WGPUSamplerId' (aka 'unsigned long') is not a structure or union
17:22.34         bgb.resource.sampler._0 = entry.mValue;
17:22.34         ~~~~~~~~~~~~~~~~~~~~^~~
17:23.31 BUILDSTATUS BUILD_VERBOSE dom/bindings
17:23.63 5 errors generated.
```

This issue seems to also apply to IceCat 78:
https://aur.archlinux.org/packages/icecat/

**Comment by hawkeye116477** [comment]
See https://svnweb.freebsd.org/ports/head/devel/rust-cbindgen/Makefile?revision=559038&view=markup&pathrev=559038.

Seems that problem is with cbindgen 0.16.0, so FreeBSD maintainers temporarily downgraded package.

**Comment by ilikenwf** [comment]
I can confirm cbindgen 0.15.0 works for making it build.

Thanks!

**Comment by hawkeye116477** [comment]
Patch is now available at https://bugzilla.mozilla.org/show_bug.cgi?id=1684180, tested and seems that works fine :smile:.

**Comment by ilikenwf** [comment]
Nice! Would you be open to merging into a fork and pull requesting or do you want me to?

**Comment by ilikenwf** [comment]
I can confirm this fixes build with newer cbindgen variants. It will eventually come from upstream but @MrAlex94 it may be worth merging in now?

**Comment by MrAlex94** [comment]
Sure, will cherry-pick it tomorrow.

**Comment by ilikenwf** [comment]
Thank you for this and your years of work!

**Comment by ilikenwf** [comment]
@MrAlex94 just a reminder - I'm still having to patch this on Arch:
https://hg.mozilla.org/releases/mozilla-esr78/raw-rev/a1f99bfc3ee5

**Comment by hawkeye116477** [comment]
@ilikenwf https://github.com/MrAlex94/Waterfox/commit/1da3c4637b745870942a6dfeadf692597b0ce715

Seems that branch „future" won't be used now, so you need to switch to „current" branch.
