### ISSUE TITLE
Some RSS Feeds Won't Load

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [MrAlex94/Waterfox#1889]
Spefically, when I try to browse: https://www.animationscoop.com/feed/ 
All that shows is this:

```
XML Parsing Error: junk after document element
Location: https://www.animationscoop.com/feed/
Line Number 534, Column 1:
<br />
^
```

But `firewarden chromium` is able to view the feed, and the ctrl+shift+e response tab shows the unrendered plaintext feed...

**Comment by hawkeye116477** [comment]
It works fine on Classic 2020.12.

**Comment by neurodiverseEsoteric** [comment]
I opened the profile in g3 (kpe), which made it impossible to load in earlier versions
