### ISSUE TITLE
[Waterfox classic] window.customElements is undefined

### ISSUE THREAD

**Issue by Vulpovile** [MrAlex94/Waterfox#1891]
**Describe the bug**
TypeError: window.customElements is undefined on certain websites

**To Reproduce**
1. Open console
2. Go to github.com, most visible in a repo

**Expected behavior**
This should not happen, and pages should load correctly

**Screenshots**
https://i.imgur.com/lii228s.png

**My configuration**
 - Device: PC
 - OS: Windows 8.1
 - Version: Classic 2020.12 (64-bit)

**Comment by hawkeye116477** [comment]
Duplicate of https://github.com/MrAlex94/Waterfox/issues/1790. Workaround at https://github.com/MrAlex94/Waterfox/issues/1790#issuecomment-709530207.

**Comment by Vulpovile** [comment]
> 
> 
> Duplicate of #1790. Workaround at [#1790 (comment)](https://github.com/MrAlex94/Waterfox/issues/1790#issuecomment-709530207).

That worked great! Though I hope the issue will be fixed soon in general so a workaround isn't necessary

**Comment by Y-Less** [comment]
I keep getting this despite using the Polly work-around.  Every time I have to refresh the page, it doesn't seem to inject correctly half the time.

**Comment by reallyuniquename** [comment]
Did you enable response modification in Polly settings?

**Comment by Y-Less** [comment]
Ahh, no, that could be it thanks.
