### ISSUE TITLE
[Waterfox G3] SSSE3 mandatory requirement

### ISSUE THREAD

**Issue by denosys** [MrAlex94/Waterfox#1893]
I noticed that from G3 (current) waterfox doesn't work anymore without SSSE3(??) and for me (maybe I'm not alone) it's a big problem because I have some AMD four core APU's that have only SSE3 or SSE4a but not SSSE3 and they are still very good for browsing the web.

Probably classic still works, but I would like to stay with current channel.

Firefox, the most recent 84.0.1 and also the beta, don't require these SSSE3 extensions (Pentium 4 or newer processor that supports SSE2).Same for Chrome or other browsers.

So I would like to ask, why waterfox G3 needs these extensions and "standard" firefox or other recent browsers not? it is possible to do something about this because I would like to still use waterfox but if this SSSE3 remains mandatory, I have to go back to using firefox,chrome or the others. They work perfectly on my systems while waterfox start from G3 to crash (before G3 it works ok) at start (almost certainly for these SSSE3 extensions) in every OS that I tried.
So probably this it's not a "bug" (Idon't know why it assigned this label to my issue...) but more a request, to know if it can be done something to revert back this SSSE3 requirements, that as I explained before don't even exist on "standard" firefox...

Many thanks for your time

**Comment by HubAl49** [comment]
Hope that I'm not intruding here, and that the following is of use ...

It seems that something similar to issue #995 (which I raised) may have reappeared.

Looking at the G3 code, there are 3 '.mozconfig' files that specifically refer to '-mssse3' -
1. .mozconfig-production
2. .mozconfig-x86_64-unknown-linux-gnu
3. .mozconfig-x86_64-w64-mingw32

although the remaining 3 '.mozconfig' files (.mozconfig, .mozconfig-x86_64-apple-darwin, .mozconfig-x86_64-pc-windows-msvc) don't

Can't figure out why Waterfox is the only program that I have come across that has this restriction on the CPU instruction set.

**Comment by MrAlex94** [comment]
This has now been bumped to SSE4.2. @HubAl49, this is for performance reasons.
