### ISSUE TITLE
G3 & W764 - Cannot use mousepad/touchpad to scroll pages

### ISSUE THREAD

**Issue by Waterfoxer** [MrAlex94/Waterfox#1894]
G3 on W764 SP1 Acer laptop, **cannot use the laptop's mousepad/touchpad  to scroll pages** by swiping a finger up/down the side of the pad, like normal.  Does not work in safe mode either.

Mousepad works literally everywhere else, including in WF Current and all previous WF versions. 

Scrolling also works fine in the latest Firefox (v84x). Just not G3.

NOTE: Mar 2021 update - a workaround has been posted [here](https://old.reddit.com/r/waterfox/comments/kez68p/touchpad_scrolling_bug/gnrir3q/)   which is to set the preference “ui.window_class_override” to “MozillaWindowClass” ... this works but no one really knows if it will break something else or cause issues. I hope Alex or a dev can comment or simply see this and correct the bug in an upcoming release 'the right way' if this isn't a good way to go about it. Thanks.

**Comment by alecmascot** [comment]
This makes G3 unusable for me..

**Comment by Waterfoxer** [comment]
For me as well. I was going to try it again to see if anything's changed, but since no one has addressed the bug here, probably it hasn't been fixed. :(

**Comment by Waterfoxer** [comment]
Well I have G3 1.1 installed (just upgraded from 2020.10) and the scrolling issue remains... so back to 2020.20 for me...
