### ISSUE TITLE
[CLASSIC]  Sites fail to work/load correctly possible cause!

### ISSUE THREAD

**Issue by sutex** [MrAlex94/Waterfox#1896]
For a long time I could not use Waterfox classic to keep my login details with Star Citizen forum page https://robertsspaceindustries.com/spectrum/community/SC

As I had the **Enable multi-process Waterfox** ticked, enabled. But disabling the multi-process Waterfox, the Spectrum forum holds my login information and works!

**Comment by Squall-Leonhart** [comment]
still just you, WF retains my SC login just fine.

**Comment by sutex** [comment]
**Enable multi-process Waterfox ticked, SC login fails,** Disabling the multi-process my SC login just fine.

**Comment by Squall-Leonhart** [comment]
**JUST YOU**

**Comment by sutex** [comment]
Short lived, https://robertsspaceindustries.com/spectrum/community/SC is back to **not** holding my login
Even if I run Waterfox without any addons loaded I get the same  _stuff ups_  of pages not loading correctly. 

And JUST YOU, is such a great help. but hey that's the general nature of help and reporting an ongoing issue here. 
If you cant  help solve this issue DON'T COMMENT just go troll someone else, with your opinions  :)

**Comment by Squall-Leonhart** [comment]
"just you" is enough for you to look at your frigging extensions and personal profile's configuration.

nobody else can tell you what you did to it.

**Comment by sutex** [comment]
With all them disabled I still have the same issue. Thanks for your unhelpful input once again.

**Comment by Squall-Leonhart** [comment]
delete webappstore.sqlite, yours is corrupt.

**Comment by sutex** [comment]
And if I do that what will happen to the functionality of my browser , is that like a 'reset' my setup is wiped?

**Comment by Squall-Leonhart** [comment]
it's data stored by websites,  such as the position of a video on video sites like XtremeCDN.

**Comment by sutex** [comment]
No idea what XtremeCDN is. So it's not going to reset my browser to defaults and wipe all my settings, all I really need to know

**Comment by sutex** [comment]
Really tried of peasants

**Comment by Squall-Leonhart** [comment]
the file only holds site data, and has a history of developing consistency errors that cause it to not retain session data if a site uses it instead of cookies, the nvidia forum for example will also logout across a refresh or navigation when the file is no longer storing data properly.

> Really tried of peasants

Thats ok, i'm equally tired of impatient karens.
