### ISSUE TITLE
❔ How do I add desktop icon and Waterfox to path

### ISSUE THREAD

**Issue by nandgator** [MrAlex94/Waterfox#1897]
I downloaded Waterfox from https://www.waterfox.net/download/, a `tar.bz2` archive. After extracting I put it into `/opt/waterfox` and added an `alias waterfox=/opt/waterfox/waterfox` in `~/.bashrc`. Then I tested waterfox launch and yea it worked fine!

I found a `.desktop` file at `~/.local/share/applications/` and edited it's content as:

```desktop
[Desktop Entry]
Name=Waterfox
Version=1.0
Type=Application
Exec=waterfox #alias
Icon=/opt/waterfox/browser/chrome/icons/default/default128.png
Terminal=false
Categories=Network;
Comment=Waterfox
```

But I cannot find the application icon in [slingshot](https://github.com/elementary/applications-menu).

**OS**: elementary OS 5.1.7
**Waterfox**: G3.0.2 (64-bit) based on Gecko 78.6.0

| Slingshot | `Waterfox.desktop` |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/38415384/103454941-99ca8780-4d0e-11eb-9543-d54723e4f931.png) | ![Screenshot from 2021-01-02 15-27-51](https://user-images.githubusercontent.com/38415384/103454978-21b09180-4d0f-11eb-8bf9-065a0a7f4161.png) |

What is the correct sequence of steps to be done after downloading that archive?

**Comment by hawkeye116477** [comment]
Just use installer script from https://github.com/hawkeye116477/install-waterfox-linux. I wouldn't recommend putting it into root directories like /opt, cuz that prevents automatic updates.

**Comment by nandgator** [comment]
Thanks! that is a neat script, starred 🌟  would they make it official?

**Comment by nandgator** [comment]
Closing (it's become irrelevant for me), feel free to comment if anyone else faces the same issue.
