### ISSUE TITLE
🐞: Top snackbar text is illegible

### ISSUE THREAD

**Issue by nandgator** [MrAlex94/Waterfox#1898]
**Describe the bug**
First off not sure what to call this yellow bar (alert bar maybe?):

![Screenshot from 2021-01-02 15-13-39](https://user-images.githubusercontent.com/38415384/103455167-a51eb280-4d10-11eb-93b6-ac9f73377646.png)

See that text in <kbd>Use Waterfox as my default browser</kbd> and <kbd>Options</kbd> buttons? It's is barely visible.

**To Reproduce**
1. Go to system setting, set a different browser as default.
2. Launch Waterfox
3. That yellow bar appears.

**Expected behavior**
The text in the buttons are legible.

**My configuration** 
 - Device: Dell xpsl502x
 - OS: elementary OS 5.1.7
 - Version: G3.0.2 (64-bit) based on Gecko 78.6.0

**Additional context**
Theme: Abyss

**Comment by hawkeye116477** [comment]
It's weird, cuz I see that.
![2021-01-02_11-37](https://user-images.githubusercontent.com/19818572/103455630-f9189f80-4cee-11eb-89d1-9b52fdf1efb4.png)

**Comment by nandgator** [comment]
![image](https://user-images.githubusercontent.com/38415384/103455770-d8b00b80-4d15-11eb-8ef5-cceb24d0df25.png)

Fresh install from [your script](https://github.com/hawkeye116477/install-waterfox-linux).

**Comment by nandgator** [comment]
Closing (it's become irrelevant for me), feel free to comment if anyone else faces the same issue.
