### ISSUE TITLE
cannot use DRM 

### ISSUE THREAD

**Issue by alonetrifle** [MrAlex94/Waterfox#1902]
Hello;
wanted to test waterfox came into this issue :
when trying to play spotify web (DRM based) it skips song untill some random or if i hit next button it will stop skipping but it will be same after refresh

**Comment by hawkeye116477** [comment]
Are you using adblocker?

**Comment by alonetrifle** [comment]
> 
> 
> Are you using adblocker?

yes but i also tried disabling it didn't change

**Comment by BugFixesAndPerformanceImprovements** [comment]
This is still an issue with a clean install of Waterfox G3.0.2, no addons installed and with the same symptoms as described in this reddit post: https://www.reddit.com/r/waterfox/comments/kezut8/spotify_problems_on_waterfox_g302/

**Comment by ghost** [comment]
still same problem. please someone be fixed it.
