### ISSUE TITLE
[Waterfox G3] Crashes immediately on open - MacOS 11.1

### ISSUE THREAD

**Issue by brucew2013** [MrAlex94/Waterfox#1905]
Brand new Mac Mini (M1,2020). First app install, fresh WF G3.0.2.
Open, five second, crash reporter and error: cannot collect data.
Uninstalled, reboot, fresh download three times fail.
Please advise.

**Comment by MrAlex94** [comment]
I believe Rosetta does not support the aggressive build flags Waterfox is built with. May change with coming updates.
