### ISSUE TITLE
Is there a reason for having both waterfox-bin and waterfox executables after building

### ISSUE THREAD

**Issue by magnus-ISU** [MrAlex94/Waterfox#1906]
After building waterfox, there are two binary files generated which will run waterfox - one is called "waterfox" and one "waterfox-bin". `diff waterfox waterfox-bin` produces no output. Why is a duplicate created?

**Comment by hawkeye116477** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=658850#c13.

**Comment by magnus-ISU** [comment]
Okay, so its mozilla's fault. Should I close this issue (waterfox probably doesn't need to worry about this)?
