### ISSUE TITLE
Bug in xpcom/io/SpecialSystemDirectory.cpp

### ISSUE THREAD

**Issue by magnus-ISU** [MrAlex94/Waterfox#1907]
Or at least I'm 69.420% sure its a bug, as https://www.cplusplus.com/reference/cstdlib/getenv/ says about getenv

> The pointer returned points to an internal memory block, whose content or validity may be altered by further calls to getenv (but not by other library functions).

Unless clang breaks specification to define that subsequent calls do not change the original value, or that website is incorrect

A call to getenv is made on line 226, another call is made at 232, and the value of the first pointer is used at line 235 and also 312.

**Comment by MrAlex94** [comment]
Better filed with Mozilla than here.
