### ISSUE TITLE
WebExtensions that don't specify a background colour are nearly impossible to read using a dark theme

### ISSUE THREAD

**Issue by TheBeardOfTruth** [MrAlex94/Waterfox#1925]
Version (current, not classic):
![image](https://user-images.githubusercontent.com/53689060/106371557-11b7bc00-6366-11eb-979a-f55648fe5b88.png)

example of problem:
![image](https://user-images.githubusercontent.com/53689060/106371563-25632280-6366-11eb-861c-383c66ce6527.png)

This happens with both the photon and australis dark themes themes, I'd assume third-party dark themes would do it as well but I've no interest in checking.

**Comment by TheBeardOfTruth** [comment]
Why was this closed, if I may ask? 

This behaviour works as intended in firefox and is problematic in waterfox. (In firefox with dark theme it draws them with a white background and dark text), it's a pretty impactful UI issue and is still present in G3.2.1

**Comment by hawkeye116477** [comment]
Well, Mozilla fixed that only for out of process webextensions, which are disabled on WF Classic, cuz it's not ready to be enabled, it's incomplete in current state.

https://bugzilla.mozilla.org/show_bug.cgi?id=1527048
