### ISSUE TITLE
Waterfox Current (G3) and Firefox.

### ISSUE THREAD

**Issue by roman6626** [MrAlex94/Waterfox#1926]
What is the difference now between Waterfox Current (G3) and Firefox? Specifically, on all counts? Why is Waterfox better?
I would like to hear the developer's answer. I searched on Reddit, but I couldn't find the answer. Only different thoughts.
There is no specific information on the site either. Unfortunately.

**Comment by jorg35** [comment]
The difference is that Waterfox is outdated and rarely updated.

**Comment by roman6626** [comment]
> The difference is that Waterfox is outdated and rarely updated.

This is all clear. It's about something else. :-)
To create your own assembly, you need it to be somewhat different from the original. In a technical aspect.
I would like to hear the specifics, what distinguishes her from the parent.
It is very strange that nothing is written about this on the official website of the product.
You need to know the meaning of installing this browser (it's not about the Classic)

**Comment by roman6626** [comment]
It doesn't even fix or return tools that it has carved out of Mozilla's code. Everything is like Firefox.
Everything that went missing in Firefox went missing in Waterfox.

**Comment by jorg35** [comment]
I gave up on that cheesy browser.

**Comment by roman6626** [comment]
> I gave up on that cheesy browser.

So what's a good browser right now?

P.S. But there is still no answer to the question.

**Comment by roman6626** [comment]
Silence. Nobody knows.
Conclusion - no different. Only a tag. :-)

P.S. And there are more bugs.

**Comment by vcekron** [comment]
https://github.com/MrAlex94/Waterfox/commits/current

**Comment by roman6626** [comment]
> https://github.com/MrAlex94/Waterfox/commits/current

I am not an expert programmer. I think it is possible to say it in understandable words. List all significant differences from Firefox. Moonchild, for example, does it right on the official website.
