### ISSUE TITLE
Refresh Waterfox on Portable resets installed version as well!!

### ISSUE THREAD

**Issue by Jamesstevens-3rd** [MrAlex94/Waterfox#1928]
pretty much as the title suggests, 

I have portable 2021.01.1 on my desktop in a folder Waterfox Browser, also the Classic 2021.01.1 Installed version in Program Files, the Refresh Waterfox button in about:support for Portable does not respect Installed Classic and consequently reset both.

**Comment by Jamesstevens-3rd** [comment]
OK I now know what is going on here, portable does not have that feature... sorry

what I did was start portable from the WaterfoxPortable.exe shortcut when I had Classic running at the same time and what actually happens is that you will start a second copy of Classic (Installed Version) and not the portable version at all!

so I thought I was starting portable and resting it when all along I was resting my installed version of classic instead... bummer!

**Comment by MrAlex94** [comment]
That's right..the portable browser is run from a separate .exe and it doesn't know that it's being run that way. So when it re-launches, it just tried to run the system version of Waterfox installed.
