### ISSUE TITLE
WFox G3 - Cursor not active when loading 'Home' the first time

### ISSUE THREAD

**Issue by GitMeier** [MrAlex94/Waterfox#1930]
When I go from any webpage to my home screen (by clicking the Home-button or hitting [Alt-Home] keys,
the cursor is not active/visible in any text field.
When I 'go Home' again it is active in the address field.

The reason I care is that I do a lot of browsing with only the keyboard.
After I 'go Home' I usually type a new web address or search term and hit [Enter] to get going.
Since upgrading to G3 I find myself typing without realizing that nothing prints because of this bug.

I would expect that already after the first time I click the Home-button or hit [Alt-Home] keys
that the cursor is active in the address or search text-field.

**Comment by MrAlex94** [comment]
This may be fixed in the next major release of Waterfox due towards Q3.
