### ISSUE TITLE
[Feature] Tab group and 2 level tab bar.

### ISSUE THREAD

**Issue by nobk** [MrAlex94/Waterfox#1931]
Very usefully feature better than Tab Mix Plus.
![2021-02-04 01 26 11 help vivaldi com b5d865c85667](https://user-images.githubusercontent.com/4659870/106785109-04f9d780-6688-11eb-8df0-125f16834f23.png)

**Comment by MrAlex94** [comment]
Thanks for the feedback - will keep it in mind.
