### ISSUE TITLE
Roboform

### ISSUE THREAD

**Issue by PiliJ** [MrAlex94/Waterfox#1935]
Hello,
Waterfox version 3.1.0 and addon Roboform 9.1.3.0.
The button "All logins" does not work under Waterfox, but well under Firefox et Edge.

![Image 000](https://user-images.githubusercontent.com/33757855/107054184-15b56500-67d0-11eb-9ffd-03bb140d6789.jpg)

Cordially.

**Comment by MrAlex94** [comment]
Appreciate the report - it's up to Roboform to properly support Waterfox.
