### ISSUE TITLE
WF Classic, Mac, doesn't play video on Youtube or anywhere (OSX 10.7.5. MacBook2007)  

### ISSUE THREAD

**Issue by MacMoinsen** [MrAlex94/Waterfox#1936]
Waterfox Classic 2021.01.1 (64-Bit) and versions after 56.2.11 don't play videos on any websites.

On YouTube, the player shows a black area with an error message saying:

"An error occured. Please try again later. (Playback ID ...)"  

---
Mac OSX 10.7.5 MacBook 2007, Core2Duo, GMA950 graphics
Sorry, that again...

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
You can check [unofficial package](https://github.com/aeiouaeiouaeiouaeiouaeiouaeiou/waterfox-osx/releases/tag/2021.01.1-osxfix-classic) which built in native OS X environment.
