### ISSUE TITLE
OS X 10.9

### ISSUE THREAD

**Issue by RJVB** [MrAlex94/Waterfox#1938]
Waterfox being (currently) based on FF 78 ESR it must be able to run on OS X 10.9 . Does anyone seeing this happen to know of an up-to-date build for 10.9, or if not, would it be feasible to make the official build target that version instead of 10.10?
FWIW, there's a 10.10 SDK for OS X 10.9 and the Firefox build itself still supports versions as low as 10.9.0 .

**Comment by roman6626** [comment]
Why even now, when Waterfox passed into the hands of Systems1, the same people continue to make the browser - 1 ... 3 people? Where is the big new team that was talked about?

**Comment by RJVB** [comment]
I have no idea what that has to do with my issue but whatever.

I tried to build the thing myself. I don't know how people manage to do this on 10.7 as I understand they do, but I got stuck on trying to install cbindgen. Apparently the dependencies of that require a newer Rust version than the one I managed to install on 10.9 .

If anyone has a brilliant idea how to get unstuck I'd be all ears!

**Comment by RJVB** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou pointed me here: https://github.com/aeiouaeiouaeiouaeiouaeiouaeiou/waterfox-osx/releases/tag/G3.1.0-osxfix-current

Exactly what I was looking for, so thanks!

Sadly it looks like I get the same kind of graphics glitches that forced me to deactivate hardware acceleration in FF 78-esr (for the long-running default browser; I have a separate profile for things like watching streaming videos).
Curiously, Waterfox also seems to be somewhat slower than the official build: the antutu html5 test score is around 25500 against 27500 for FF 78-esr (using a stock profile). That's on a MBP 8.1 (mid 2011, i7 @ 2.6Ghz). On my much more modest Linux notebook (1.6Ghz N3150) I'm getting around 19500 vs 17500 using official Waterfox vs. Firefox builds (but that's the FF Dev Edition so maybe 78 ESR would be faster too here?)

**Comment by MrAlex94** [comment]
Looks like @aeiouaeiouaeiouaeiouaeiouaeiou doesn't build with LTO, which may explain the performance discrepancy.

**Comment by RJVB** [comment]
Maybe he can "fix" that but in my experience there is rarely a significant performance gain to using LTO. Then again ... the performance differences cited above aren't exactly huge.
