### ISSUE TITLE
libstdc++ ABI issue on Linux

### ISSUE THREAD

**Issue by RJVB** [MrAlex94/Waterfox#1939]
Trying to start Waterfox on an older Linux installation I get

```
> /opt/waterfox/waterfox
/opt/waterfox/waterfox: relocation error: /opt/waterfox/waterfox: symbol _ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
Exit 127
```

In a nutshell this means that my libstdc++ (from GCC 9.3!) has not been built with the C++11 ABI. I've been able to remedy that by downloading the corresponding lib from Ubuntu 18.04 and "side-load" that library; the browser runs just fine after that.

I think it should be possible to bundle libstdc++ with the other private library copies
 (like libnssutil3).

FWIW, checking if `waterfox` was a shell wrapper script I noticed that this binary and `waterfox-bin` are identical and should probably be hard-linked. For comparison, `firefox` and `firefox-bin` are both binaries too but the former is almost 40x smaller than the latter (so probably a wrapper/launcher).

**Comment by hawkeye116477** [comment]
Well, as I know, official package has specific depends, for example glibc 2.28 is requried. 

Maybe try one of my packages from https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-g3-kpe or https://appimage.github.io/Waterfox_Third_Generation/. More details at `https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage`.

**Comment by RJVB** [comment]
Good to know, thx.

(You wouldn't be able to cross-compiler for Mac and target 10.9 by any chance? (Clang is inherently a cross-compiler and will generate MachO binaries when asked nicely - but I suppose you knew that.)

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
See #1936.

**Comment by RJVB** [comment]
Thanks, but I think that has more to do with my other ticket about Mac OS X 10.9 ... ;)
