### ISSUE TITLE
Trivial bookmarks bug

### ISSUE THREAD

**Issue by MagikGimp** [MrAlex94/Waterfox#1940]
This has been a bug for ages now so I thought it about time I mentioned it. I have no idea whether it's specific to the Waterfox code-base or is a legacy Firefox issue.

How to recreate:
1. Create a bookmark with the star button.
2. Extend the folder selection and choose one.
3. Now contract the folder selection and open the recently used folders drop-down list.
4. It is not possible to select a new folder from this list unless the bookmarks overlay is closed and re-opened.

As I say, not a huge problem but it's been around for as long as I've used Waterfox (a couple of years now).

PS: Ironically GitHub's editor tools (buttons) are also not supported in Waterfox! Should that be considered another issue?

**Comment by MagikGimp** [comment]
Also, using the keyboard to move the selected item to "Choose..." and pressing Enter/Return occasionally gives a funny result of a floating menu.

**Comment by MrAlex94** [comment]
May be worth seeing if you can reproduce the bug and file it with Mozilla - better it goes upstream as it'll make it's way to Waterfox anyway :-)
