### ISSUE TITLE
 [Classic] MOZ-2021-0001 status?

### ISSUE THREAD

**Issue by reallyuniquename** [MrAlex94/Waterfox#1943]
https://www.mozilla.org/en-US/security/advisories/mfsa2021-06/

Isn't it applicable to Waterfox Classic as well?

**Comment by hawkeye116477** [comment]
Well, Moonchild added that https://repo.palemoon.org/MoonchildProductions/UXP/commit/aab1c211a6a4ced65a61b630b962bc870ed8c324, so it's rather applicable to Classic too.

**Comment by reallyuniquename** [comment]
Seems like a critical bug. I sure hope @MrAlex94 will patch this asap.

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/e075bab1fb696b34f9ed813a9d398379c02c451b

Builds available soon.

**Comment by reallyuniquename** [comment]
@MrAlex94 Any ETA on those builds?

**Comment by MrAlex94** [comment]
Re-opening this, macOS and Linux build fine but Windows errors out:

```
15:54.46 In file included from c:/Users/akontos/Waterfox-Classic/objdir-classic/gfx/angle/src/libANGLE/Unified_cpp_angle_src_libANGLE8.cpp:128:
15:54.46 c:/Users/akontos/Waterfox-Classic/gfx/angle/src/libANGLE/formatutils.cpp(750,9): error: invalid use of member 'compressed' in static member function
15:54.46     if (compressed)
15:54.47         ^~~~~~~~~~
15:54.47 c:/Users/akontos/Waterfox-Classic/gfx/angle/src/libANGLE/formatutils.cpp(752,51): error: invalid use of member 'compressedBlockHeight' in static member function
15:54.49         CheckedNumeric<GLuint> checkedBlockHeight(compressedBlockHeight);
15:54.49                                                   ^~~~~~~~~~~~~~~~~~~~~
15:54.49 2 errors generated.
15:54.49 mozmake.EXE[5]: *** [c:/Users/akontos/Waterfox-Classic/config/rules.mk;1068: Unified_cpp_angle_src_libANGLE8.obj] Error 1
15:54.49 mozmake.EXE[5]: *** Waiting for unfinished jobs....
15:56.96 dom_abort.lib.desc
16:02.88 mozmake.EXE[4]: *** [c:/Users/akontos/Waterfox-Classic/config/recurse.mk;73: gfx/angle/src/libANGLE/target] Error 2
16:02.88 mozmake.EXE[4]: *** Waiting for unfinished jobs....
```

**Comment by MrAlex94** [comment]
Ignore

**Comment by reallyuniquename** [comment]
Missing `const` in the end of `computeDepthPitch` declaration?

**Comment by MrAlex94** [comment]
🤦‍♂️ That looks to be it.

Although I got there by uplifting [newer versions](https://github.com/MrAlex94/Waterfox/pull/1952) of ANGLE. 

@reallyuniquename, do you have a Windows system available? Wondering if I can send you a test to see if everything ANGLE related is okay (WebGL websites etc).

**Comment by reallyuniquename** [comment]
Sorry, I don't have Windows system available right now and I've had some browser related issues with video drivers in the past.

**Comment by MrAlex94** [comment]
Builds are out:
**https://www.waterfox.net/download/**

**Comment by neurodiverseEsoteric** [comment]
Waterfox-g3 still can't play videos it just crashes the tab...

**Comment by hawkeye116477** [comment]
This is topic about Classic...
