### ISSUE TITLE
G3 [Feature Request] Toggle Status bar via Menubar > &View > &Toolbars

### ISSUE THREAD

**Issue by SaltfishAmi** [MrAlex94/Waterfox#1944]
Like in IE:

![Untitled](https://user-images.githubusercontent.com/14184974/107477967-a8c91300-6bb3-11eb-9134-a5286123ab31.png)

**Comment by MrAlex94** [comment]
This is available in G4.
<img width="394" alt="image" src="https://user-images.githubusercontent.com/4728920/138850559-0704cd29-664c-41bf-8290-29a7b2000fe6.png">
