### ISSUE TITLE
Windows 2 versions of Waterfox "installed" 3.0.1 and 3.1.0 after auto update

### ISSUE THREAD

**Issue by RPYoshi** [MrAlex94/Waterfox#1945]
I was looking at the installed applications on my computer and noticed that I have 2 versions of Waterfox installed. I performed a reinstall of version 3.0.0 and allowed for auto updates to fix issues. Never installed 3.1.0 by hand.

![image](https://user-images.githubusercontent.com/6041818/107689876-62d58300-6c77-11eb-9b32-f8391f41e176.png)

![image](https://user-images.githubusercontent.com/6041818/107689947-75e85300-6c77-11eb-9656-c4a102be5c83.png)

Checked install directory and only one version is there.

**Comment by MrAlex94** [comment]
Very odd - usually entries into the registry like that are handled only by the installer itself (not the browser). Unfortunately I can't reproduce - but please re-open if you see this happening again.
