### ISSUE TITLE
[Waterfox Classic] Nvidia.com "Download driver selector" resets the field to its default value

### ISSUE THREAD

**Issue by Killogy** [MrAlex94/Waterfox#1947]
When I change Product Series:, Product: or Operating System:  other than default value, the field is reset to its default value so I can´t choose the one I want.

This problem is happening by using mouse pointer.  Using keyboard and Tabulator key to select a field and downarrow to change selection is working properly and I´m able to select what I want.

https://www.nvidia.es/Download/index.aspx?lang=en

**Comment by hawkeye116477** [comment]
Looks like that same problem is on Waterfox G3 and latest Firefox. It works correctly only on Chromium-based browsers. So Nvidia should rather fix that.

**Comment by Killogy** [comment]
I tested on Waterfox G3 and it works correctly.

Using Ublock Origin and blocking scripts one by one, blocking this one https://images.nvidia.com/nvFrame/1.0/p/js/_libs/jquery-1.10.1-migrate.js, fields can´t be expanded, so this .js is the culprit?

**Comment by Squall-Leonhart** [comment]
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/

Should be able to rewrite it to true using a Adblock/Ublock rewrite filter.

**Comment by Killogy** [comment]
Fixed, I used addon Modify Header Value (HTTP Headers) and added this HTTP Header.

**URL**    https://www.nvidia.       
**Domain and Sub** [X]  
**Header Name** User-Agent 
**Remove**  [X]

Header Value field was left empty.
