### ISSUE TITLE
Off-by-1 in scrolling the tab bar

### ISSUE THREAD

**Issue by nxdiamond** [MrAlex94/Waterfox#1949]
I have a 1920x1200 screen.  Waterfox Classic 2020.01 (64-bit) displays the menu bar at the top and Bookmarks sidebar at the left.  The tab bar is displayed below the menu bar, above the address bar, and not affected by the presence of the sidebar farther down.

The tab bar has a clickable < at the left, 18 tabs for some of the pages open, and a clickable > at the right.  This display is correct.

A double-click on the < at the left or on the > at the right causes the list of 18 tabs to scroll by 19 items instead of 18.  Therefore when I am searching for some particular tab, sometimes I can't find it.  I think this is an off-by-1 bug.

In Waterfox, a single click on the < or > scrolls the tab bar by 1 item which I think is correct.  Luckily Waterfox didn't inherit Firefox's bug of scrolling the tab bar by 2 items.  However, I don't know if the off-by-1 in double-click is inherited from Firefox or original to Waterfox Classic.

**Comment by MrAlex94** [comment]
I believe it's inherited from Firefox - unless someone submits a patch for it, I'll have to close this issue as we don't have resources for Classic.
