### ISSUE TITLE
Can't log out

### ISSUE THREAD

**Issue by nxdiamond** [MrAlex94/Waterfox#1950]
The way to report a bug in Waterfox is to log in to github and post here.  github said it doesn't support this browser (Waterfox Classic) but allowed me to post anyway.  However, when I click on the avatar at the upper right of the github page of Waterfox issues, intending to log out, github says something went wrong and it doesn't display the logout menu.

**Comment by Killogy** [comment]
Yes, also you can´t edit your post.

Change User-Agent has no effect.

**Comment by hawkeye116477** [comment]
It's already known problem. Just use Polly extension as a workaround.

https://github.com/MrAlex94/Waterfox/issues/1790#issuecomment-709530207

**Comment by Killogy** [comment]
> 
> 
> It's already known problem. Just use Polly extension as a workaround.
> 
> [#1790 (comment)](https://github.com/MrAlex94/Waterfox/issues/1790#issuecomment-709530207)

Thank you so much.
