### ISSUE TITLE
[Waterfox Classic][Feature Request] DNS over HTTPS

### ISSUE THREAD

**Issue by Killogy** [MrAlex94/Waterfox#1953]
I want to know if is possible to include this feature into Watefox Classic even if only is possible to enable it or disable it though **about:config**

My ISP is blocking some streaming website and the Domain is changed everytime to bypass this blocking. One of the recommendations from website owner is enable **DNS over HTTPS** and to change some options under **about:config,** so we can load the blocked Domain and no need to wait for a Domain change.

network.security.esni.enabled **true**
network.trr.mode **2**

I tested it on Waterfox G3 and it works. 

Sadly Waterfox Classic do not includes this feature and I would to know if this feature can be added. 

I tested these values and addon https://addons.mozilla.org/es/firefox/addon/easydoh/ and it doesn´t works.

**Comment by hawkeye116477** [comment]
I think that all is possible, if we want to do that. However, as I know, the plan was to push only security updates to Classic. Seems that currently I'm the only one who adds something other than that, but I'm rather planning to continue adding only „compatibility fixes" for websites. So chances are rather low that will be added by some good Samaritan.

**Comment by Killogy** [comment]
Ok thank for letting me know, I did´t know only security updates will be pushed to Classic. 

Anyway if at any moment that good Samaritan comes here, maybe he/she can think about if DNS over HTTPS feature provides a extra security because increases user privacy and security cause without DoH anyone listening to packets on the network knows you are attempting to visit some specific website, as it is doing my ISP.

**Comment by roman6626** [comment]
So Basilisk in this respect is better than the Waterfox Classic?

**Comment by hawkeye116477** [comment]
As I know Basilisk doesn't have DNS over HTTPS.

**Comment by roman6626** [comment]
I mean, Basilisk isn't just releasing security updates like Waterfox Classic. It continues to evolve. And Classic is a dead-end branch. That will soon die.

**Comment by MrAlex94** [comment]
Classic is only being updated with security patches unless someone submits a patch for this feature.
