### ISSUE TITLE
G3.1.0 (64-bit) Issue locking and Freezing up. 

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#1954]
The newest G3.1.0 (64-bit) is constantly become unresponsive and locks up.
Watching Live Streaming Videos on Multiple Sites it just stops resounding then
it will Lock Up on Netflix as well. Youtube, Facebook, News Sights just wants to
freeze up. Ive reset it ran in Safe Mode without Ad-Ons or with them does not make a difference

**Comment by A0R-R0CKS** [comment]
The newest G3.1.0 (64-bit) is constantly become unresponsive and locks up. 
 Watching Live Streaming Videos on Multiple Sites it just stops resounding then 
 it will Lock Up on Netflix as well. Youtube, Facebook, News Sights just wants to 
 freeze up. Ive reset it ran in Safe Mode without Ad-Ons or with them does not make a difference

**Comment by jorg35** [comment]
Because it's the worst browser.

**Comment by wbak1102** [comment]
And that's the truth.

**Comment by wbak1102** [comment]
Iceweasel has at least got a Language Pack.
