### ISSUE TITLE
Show tab container indicators on tabs in floe and abyss themes

### ISSUE THREAD

**Issue by aekaisato** [MrAlex94/Waterfox#1955]
In the default Firefox themes, tab containers create colored "bars" to represent different containers. This allows the user to see the various containers at a glance, without having to open every tab or separate them by window. It would be useful to have a similar indicator (a bar, dot, etc.) on the Waterfox default themes to keep this accessible.

Default Firefox themes: https://i.vgy.me/fToKGx.png
Default Waterfox themes: https://i.vgy.me/KGYFhX.png

**Comment by MrAlex94** [comment]
This is now available in the default G4 theme Lepton, but won't be in the Australis themes unless implemented by the author of said themes.
