### ISSUE TITLE
Crash on start in versions 2020.12 and up with multiprocess enabled

### ISSUE THREAD

**Issue by andreacc** [MrAlex94/Waterfox#1957]
Steps to reproduce the issue: Go to about:config, create "browser.tabs.remote.force-enable" boolean and set to true. Restart waterfox and the browser crashes instantly.

The problem only happens on versions 2020.12 and up (2021.01 and 2021.02). It didn't happen on 2020.10.

Also, it doesn't happen if waterfox is executed as admin.

Additional info: Using Windows 7 x64 pt-BR.

The option "browser.tabs.remote.force-enable" is set to enable multiprocess. I can't have a browser without multiprocess, as it is too slow.

Here is the image of the Windows crash: [screenshot]( https://i.postimg.cc/6TsSxWq8/Screenshot-1613753736.png)

Sorry that is in portuguese. The full message is:
>   Problem Event Name: APPCRASH
>   Application Name: waterfox.exe
>   Application Version: 56.4.0.7716
>   Application Timestamp: 602aa1bb
>   Fault Module Name: KERNELBASE.dll
>   Fault Module Version: 6.1.7601.24559
>   Fault Module Timestamp: 5f28ed89
>   Exception Code: 00000725
>   Exception Offset: 000000000000b87d
>   OS Version: 6.1.7601.2.1.0.256.1
>   Locale ID: 1046
>   Additional Info 1: c938
>   Additional Info 2: c93832beccc419cda936161cfa5520e9
>   Additional Info 3: 82fc
>   Additional Info 4: 82fcf0e00dfad53f399a7b8b7f93fa23

There was another one after that with the following message:
>   Problem Event Name: APPCRASH
>   Application Name: waterfox.exe
>   Application Version: 56.4.0.7716
>   Application Timestamp: 602aa1bb
>   Fault Module Name: xul.dll
>   Fault Module Version: 56.4.0.7716
>   Fault Module Timestamp: 602aa213
>   Exception Code: 80000003
>   Exception Offset: 00000000004a9cb8
>   OS Version: 6.1.7601.2.1.0.256.1
>   Locale ID: 1046
>   Additional Info 1: 9e9e
>   Additional Info 2: 9e9e27dd73a10b462d0e5a8c6a522324
>   Additional Info 3: 2ceb
>   Additional Info 4: 2cebfe9a41ffc8cd06991e37319c5593

**Comment by reallyuniquename** [comment]
https://github.com/MrAlex94/Waterfox/issues/1873#issuecomment-758331715

**Comment by andreacc** [comment]
Thanks @reallyuniquename , that worked.

Executing Waterfox as admin, or disabling multiprocess also worked for me.

**Comment by Squall-Leonhart** [comment]
~~repair your broken windows install with an inplace upgrade.~~

~~This issue does not occur in the absence of system or windows profile corruption.~~

Your Kernalbase.dll is outdated and 6.1.7601.24559 has been linked to other applications crashing on start,

install a recent cumulative update that brings you up to 6.1.7601.24562 at the minimum.

I do not have the stated issue with the forced multiprocess configuration on Windows 7.

![image](https://user-images.githubusercontent.com/1098176/108618954-11e33d00-7476-11eb-9276-03c92052a771.png)
