### ISSUE TITLE
Waterfox classic 2021-2 and Github

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#1959]
1 - Waterfox cant display the full text of github when clicking in the 3 dots that are shown when a phrase has a big text.

2 - I cant see the open/closed issues of the milestone, perhaps this happens with other sections of the site too https://github.com/qbittorrent/qBittorrent/milestone/65?closed=1

**Comment by ruboard** [comment]
Waterfox classic generally works disgusting on Github
and this applies not only to the cases described above

**Comment by Felipefpl** [comment]
I see, do you know if this is something too hard to fix?

**Comment by reallyuniquename** [comment]
@Felipefpl Workarounds for that have been discussed multiple times.

https://github.com/MrAlex94/Waterfox/issues?q=is%3Aissue+classic+github+doesn't+work

**Comment by decembre** [comment]
@Felipefpl
> 
> 
> I see, do you know if this is something too hard to fix?

A direct link to the solution is better:
use https://github.com/JustOff/github-wc-polyfill 
Read:
https://github.com/MrAlex94/Waterfox/issues/1790#issuecomment-753688496

**Comment by LeeBinder** [comment]
Suddenly, even though all my settings appear correct and still are - just double-checked - in the comment field, when I type : , now no icons are suggested anymore, like thumb up etc. In WF current it's still working.

Cleared cache, restrated WF, re-set polly settings - no go :(

Same in new user profile + adjusted settings per instructions.

Can you folks please test in WF Classic and report back if it's just me?

**Comment by Felipefpl** [comment]
Everyone - i know about polyfill and it doesnt work, when i click in the 3 dots to expand a phrase it doesnt do it. I'd rather hope someone will add the lacking web components that will make github work for real. ;)

**Comment by LeeBinder** [comment]
yee-ha, Github **_fixed_** with [Waterfox Classic 2021.03](https://www.waterfox.net/download/#classic) 👍 🥇 (at least for me in WF Classic 2021.03 for macOS)

From [What’s new in Waterfox 2021.03](https://www.waterfox.net/blog/waterfox-2021.03-release/#-whats-new-in-waterfox-202103):
> Implementation and activation of [PerformanceObserver](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/PerformanceObserver). Helps load websites such as GitHub.

A big **THANK YOU** to @MrAlex94 @hawkeye116477 !!

**Comment by hawkeye116477** [comment]
Well, to avoid confusion for other readers - it still additionally requires webcomponents polyfill from Polly, but previously using Polly alone wasn't enough.

**Comment by LeeBinder** [comment]
@hawkeye116477 what puzzles me is that in WF Classic 2021.03 the icon from the built-in polly which used to be in the far right of the toolbar is gone. I now again have to install the latest publicly available `polly-refs.tags.v1.9.xpi` from zakius (which I luckily had saved) to have icon and functionality back.

I verified this even in a brand-new empty profile.

I doubt that's intended? Did Polly accidentally drop out of 2021.03 (at least the macOS compile)?

**Comment by hawkeye116477** [comment]
@LeeBinder If you'll read changelog, then you'll know that's intended. There were complaints that there are a lot of logs in console and users didn't know how to use it, so it was removed from Waterfox installer. For some users it could also cause crashes. So it wasn't ready to be integrated, if it were just like my Polish Cookie Consent extension, then it could be better.

**Comment by LeeBinder** [comment]
@hawkeye116477 oh, my bad - just had limited time last nite - thanks for the pointer.

I've been wondering - you saved zakius's work at https://github.com/hawkeye116477/Polly
but there is no installable xpi. I had it saved so I'm lucky. But, let me ask:

1. what's the official spot you point users to to download the most current polly xpi? Even kiyn does not provide a xpi package at https://github.com/kiyn/Polly/releases
2. how come you don't supply a xpi package over at https://github.com/hawkeye116477/Polly/releases?
3. and how come your latest code release there is v.1.2, even though zakius was already at v.1.9, at least reflected by kiyn?

**Comment by hawkeye116477** [comment]
> how come you don't supply a xpi package over
> and how come your latest code release there is v.1.2, even though zakius was already at v.1.9, at least reflected by kiyn?

I didn't updated this. I forked it when zakius had 1.2 to make Pull Request for auto-update functionality.

Seems that latest is on https://github.com/MrAlex94/Waterfox/raw/classic/browser/extensions/zakius%40polly.xpi.

**Comment by LeeBinder** [comment]
> Seems that latest is on https://github.com/MrAlex94/Waterfox/raw/classic/browser/extensions/zakius%40polly.xpi.

yep thanks, that's the latest v.1.9 👍 

kinda odd that such an important link is hidden like that ..

**Comment by MrAlex94** [comment]
Unfortunately there's no documentation or usage instructions - it's rather unfriendly as is.

If someone wants to write up how to use, I'd be more than happy to add it to the wiki.
