### ISSUE TITLE
New version G3.1.1

### ISSUE THREAD

**Issue by wbak1102** [MrAlex94/Waterfox#1962]
There is a new version of G3.1.1 but still no Language Pack ??

**Comment by jorg35** [comment]
@wbak1102- Polish  Language Pack >>[https://uploadfile.pl/pokaz/2140250---glit.html](url)

**Comment by jorg35** [comment]
@wbak1102-Polish Language Pack W.g3.1.1 >>https://uploadfile.pl/pokaz/2140250---glit.html

**Comment by wbak1102** [comment]
@jorg35  Thanks a lot.

**Comment by MrAlex94** [comment]
Coming in the next release.
