### ISSUE TITLE
[minor] "See what's new." link missing trailing slash

### ISSUE THREAD

**Issue by superloach** [MrAlex94/Waterfox#1963]
![image](https://user-images.githubusercontent.com/30514424/109011416-d798bc00-767e-11eb-8479-d1b3c27a3971.png)
Clicking "See what's new." takes you to https://www.waterfox.net/blog/waterfox-G3.1.1 - a 404 page.
The post was actually at https://www.waterfox.net/blog/waterfox-G3.1.1/ (note the trailing slash).

This could be a badly configured webserver for the blog, or simply the wrong URL being pushed with the update.

Either way, very minor issue, but an issue nonetheless. Thanks for the great browser :)

**Comment by MrAlex94** [comment]
Indeed, will be fixed :-)
