### ISSUE TITLE
Lost all bookmarks after upgrade

### ISSUE THREAD

**Issue by bugsysop** [MrAlex94/Waterfox#1965]
Years of bookmarks vanished after upgrade to last version...

Waterfox Current crashed, thus i upgraded to Waterfox G3.1.1 (on MacOS Mojave)... and nothing... all is lost

Note: for various reason I was _not_ using Sync

**Comment by Jamesstevens-3rd** [comment]
no idea where MacOS saves the Waterfox profile but put this in the address bar **about:profiles** and you should see you previous profile, hopefully all you data is intact inside.

**Comment by bugsysop** [comment]
Thank! This is in effect a solution to _go back_ to a previous profile...

Quite hacky and undocumented.
