### ISSUE TITLE
Classic: Can no longer browse to 127.0.0.1

### ISSUE THREAD

**Issue by tcreek** [MrAlex94/Waterfox#1968]
I keep some servers up in different locations, and keep some of the important web based access listening on 127.0.0.1. So the only means to access it is to use SSH tunnel in conjunction with proxy set up in a browser. I noticed over a year ago or so, Firefox stopped working in this way. So I started using Waterfox to to that.

Now since the recentl Feb 2021 update, browsing to 127.0.0.1 no longer functions. I have an old copy of Waterfox portable(56.2.10) on a USB stick, and was able to again browse to that internal address.

Why is that happening, and can we get it fixed?

**Comment by reallyuniquename** [comment]
I can't reproduce this. Which option are you using, `-L` or `-D`?

**Comment by tcreek** [comment]
The -D option

**Comment by tcreek** [comment]
Here is a guide to show exactly how I do it

https://www.math.ucla.edu/computing/kb/creating-ssh-proxy-tunnel-putty

Except one item, instead of "localhost' in the proxy settings, I put 127.0.0.1

**Comment by reallyuniquename** [comment]
So you want to forward requests to 127.0.0.1 through SSH proxy, i.e. access "remote localhost"? That has never been possible with default settings on Waterfox nor Firefox.

You would have to edit `network.proxy.no_proxies_on` for that.

**Comment by tcreek** [comment]
Been doing it for years, and now all of a sudden it is broken

**Comment by reallyuniquename** [comment]
Doubt that, my guess is you had a profile configured for that and then something got reset.

So what is your `network.proxy.no_proxies_on` set to? 

As for the latest Firefox there's additional config entry `network.proxy.allow_hijacking_localhost` you need to toggle.

**Comment by tcreek** [comment]
So I double checked the profile, and it was as you mentioned got reset somehow.

Thanks for poinint that out. I should have checked that first.
