### ISSUE TITLE
Major / Easy Bug Fix - Developer Console being polluted

### ISSUE THREAD

**Issue by jabcreations** [MrAlex94/Waterfox#1973]
The developer console (which I use more than a zealot) is being polluted with the following:

```
running injector  injector.js:19:1
injector received response  injector.js:2:5
injecting polyfills into document tree  injector.js:7:5
Array [  ]  injector.js:9:5
```

That references the following internal script:

```
function handleResponse(message) {
    console.log('injector received response');
    if (message.isRequest) {
        console.log('was handled by response handler');
        return;
    }
    console.log('injecting polyfills into document tree');
    enabledScripts = message.enabledScripts ? message.enabledScripts : [];
    console.log(enabledScripts);
    enabledScripts.forEach((scriptName) => {
        const scriptElement = document.createElement('script');
        scriptElement.src = browser.runtime.getURL(scriptName);

        const parentElement = document.head || document.documentElement;
        parentElement.insertBefore(scriptElement, parentElement.firstChild);
    })
}

console.log('running injector');
browser.runtime.sendMessage({action: 'get'}).then(handleResponse, (error) => {
    console.log(error);
    console.error(error);
})



```

I have read that it's supposed to improve compatibility, great. But it needs to not require me to clear the console every single time I'm working in it which is literally hundreds of times literally every single day.

**Comment by hawkeye116477** [comment]
Yeah, it's from Polly extension (https://github.com/MrAlex94/Waterfox/blob/classic/browser/extensions/zakius%40polly.xpi).

Currently not everyone know how to use that extension, so maybe it should be removed or modified to make job automatically (inject polyfills to specific sites) and also button for toggling logs.

**Comment by jabcreations** [comment]
Thank you for the link. I can't seem to either remove it or find a way to edit out the console.log pollution. I do get the general idea behind it though it should be an extension. If you go to about:support you'll see it listed under "Features"...how the heck do we disable a feature? This is why building my own browser, engine, OS, etc are high on my list of things to do once my web business gets big enough, people just dump things all over the place adding to an already giant mess.

**Comment by reallyuniquename** [comment]
Well you can just move `/Waterfox/browser/features/zakius@polly.xpi` to any folder and then install it as normal extension if you want to continue using it.

If you are going to edit something inside that XPI file don't forget to set `xpinstall.signatures.required` to `false` before installing modified version.

**Comment by hawkeye116477** [comment]
> don't forget to set xpinstall.signatures.required to false

Waterfox already has that by defautl.

**Comment by reallyuniquename** [comment]
Yeah I remember seeing that in the commits but I wasn't sure since I run my own default config on top of whatever is shipped.

**Comment by MrAlex94** [comment]
I think I may disable polly in the next release, wasn't as straightforward to use as I had hoped.

**Comment by jabcreations** [comment]
It's all about execution. If this was an optional extension that could easily be removed then yes. However I have to use Advanced Find and Replace to search for matching strings in order to determine how to disable this. ...and I still have to do it a second time as I don't know how to disable a "feature".

Most issues with compatibility for Waterfox (Classic) aren't code though rather lazy "developers" sniffing user agents. Extending JavaScript capability is absolutely a great idea to keep Waterfox working with the developers who blindly rush to use cutting edge code on live websites...code that isn't necessary the vast majority of the time.

It's kind of like Cyberpunk 2077. If they had marked the game as "early release" people would have been more forgiving. I use Waterfox as my default browser for 95%+ of all browsing with another for temporarily heavy RAM use websites; I have not knowingly encountered compatibility issues.

Also, never pollute the developer console, I practically live there on a daily-basis as a developer.

**Comment by MrAlex94** [comment]
Should be fixed with the last release.
