### ISSUE TITLE
OSX 10.11.6

### ISSUE THREAD

**Issue by marcinbbb** [MrAlex94/Waterfox#1974]
I wanted to give Waterfox a try on my vintage Macbook Pro late 2008 with its max. OSX 10.11.6 and it seems only Current version 2020.10 works well

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
This is because of this [strange commit](https://github.com/MrAlex94/Waterfox/commit/5cfadfd21d03e9751ad020557418bda0331f8bd7) which actually sets the [10.12](https://en.wikipedia.org/wiki/MacOS_Sierra) system version as the minimum requirement. I don't understand why it was decided to do this.

**Comment by marcinbbb** [comment]
Hi, is there a workaround?

Best,
M.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
#1988 has been merged, so this should work in the next update release.

**Comment by marcinbbb** [comment]
Yes indeed works with G3.2.0 thanks!
