### ISSUE TITLE
[Classic] Upwork freelance user settings doesn't load

### ISSUE THREAD

**Issue by queuewindow** [MrAlex94/Waterfox#1982]
Using Waterfox Classic 2021.02 on Windows 10, the user settings page for freelancers on Upwork (found at https://www.upwork.com/freelancers/settings/contactInfo) fails to load. Instead it returns a grey blank page. I've tried turning off all my add-ons but it doesn't help.

The page is working on my system in other browsers.

**Comment by MrAlex94** [comment]
Please re-open with a publicly accessible link that is broken.
