### ISSUE TITLE
[Waterfox Current] [hawkeye116477 repo, kpe patch] All tabs crashing on 2020.10

### ISSUE THREAD

**Issue by TheBeardOfTruth** [MrAlex94/Waterfox#1983]
Arch linux, 5.10.14

Problem:
Start the browser, try to open a website -- "Gah. Your tab just crashed.", this does not affect priviliged pages like about:config, about:blank, settings, add-ons etc.

Reproducible in safe mode: Yes.
Reproducible under a new profile: Yes.
Reproducible after reboot: Yes.

Reinstalling did not work either.

Expected behaviour:
The ability to load pages.

Relevant dmesg output:

```
[Mar 9 17:33] WebExtensions[3628]: segfault at 0 ip 00007f2ea6627fc3 sp 00007ffdf0c0f400 error 6 in libxul.so[7f2ea6333000+6a7a000]
[  +0.000007] Code: 0c b3 06 e8 8f be d0 ff 41 8b 7d 08 e8 36 03 ff 02 8b 7d 08 e8 2e 03 ff 02 48 8d 05 90 56 81 04 48 8b 0d c8 1b b3 06 48 89 01 <c7> 04 25 00 00 00 00 3d 02 00 00 ff 15 c4 0c b3 06 00 00 00 00 00
[  +2.205738] Web Content[3562]: segfault at 0 ip 00007f2469f11fc3 sp 00007ffcc20ad090 error 6 in libxul.so[7f2469c1d000+6a7a000]
[  +0.000016] Code: 0c b3 06 e8 8f be d0 ff 41 8b 7d 08 e8 36 03 ff 02 8b 7d 08 e8 2e 03 ff 02 48 8d 05 90 56 81 04 48 8b 0d c8 1b b3 06 48 89 01 <c7> 04 25 00 00 00 00 3d 02 00 00 ff 15 c4 0c b3 06 00 00 00 00 00
[  +0.005255] Web Content[3710]: segfault at 0 ip 00007fbc7d64efc3 sp 00007ffdbf370ba0 error 6 in libxul.so[7fbc7d35a000+6a7a000]
[  +0.000011] Code: 0c b3 06 e8 8f be d0 ff 41 8b 7d 08 e8 36 03 ff 02 8b 7d 08 e8 2e 03 ff 02 48 8d 05 90 56 81 04 48 8b 0d c8 1b b3 06 48 89 01 <c7> 04 25 00 00 00 00 3d 02 00 00 ff 15 c4 0c b3 06 00 00 00 00 00
[ +10.231616] Web Content[3787]: segfault at 0 ip 00007f2e916eafc3 sp 00007ffc358433f0 error 6 in libxul.so[7f2e913f6000+6a7a000]
[  +0.000015] Code: 0c b3 06 e8 8f be d0 ff 41 8b 7d 08 e8 36 03 ff 02 8b 7d 08 e8 2e 03 ff 02 48 8d 05 90 56 81 04 48 8b 0d c8 1b b3 06 48 89 01 <c7> 04 25 00 00 00 00 3d 02 00 00 ff 15 c4 0c b3 06 00 00 00 00 00
[Mar 9 17:34] Web Content[5368]: segfault at 0 ip 00007f9dc8afbfc3 sp 00007ffd0308ac30 error 6 in libxul.so[7f9dc8807000+6a7a000]
[  +0.000009] Code: 0c b3 06 e8 8f be d0 ff 41 8b 7d 08 e8 36 03 ff 02 8b 7d 08 e8 2e 03 ff 02 48 8d 05 90 56 81 04 48 8b 0d c8 1b b3 06 48 89 01 <c7> 04 25 00 00 00 00 3d 02 00 00 ff 15 c4 0c b3 06 00 00 00 00 00
[  +0.274280] Web Content[5333]: segfault at 0 ip 00007f7b7b93a251 sp 00007fff9f9b0bc0 error 6 in libxul.so[7f7b7b641000+6a7a000]
[  +0.000009] Code: be 04 00 00 00 48 89 d9 31 c0 e8 8a 8f d3 ff e9 a4 fd ff ff e8 f0 7b d0 ff 48 8d 05 02 14 81 04 48 8b 0d 3a d9 b2 06 48 89 01 <c7> 04 25 00 00 00 00 07 07 00 00 ff 15 36 ca b2 06 48 c7 44 24 28
[Mar 9 17:35] Web Content[5472]: segfault at 0 ip 00007f41974c0fc3 sp 00007fffc2d5d810 error 6 in libxul.so[7f41971cc000+6a7a000]
[  +0.000011] Code: 0c b3 06 e8 8f be d0 ff 41 8b 7d 08 e8 36 03 ff 02 8b 7d 08 e8 2e 03 ff 02 48 8d 05 90 56 81 04 48 8b 0d c8 1b b3 06 48 89 01 <c7> 04 25 00 00 00 00 3d 02 00 00 ff 15 c4 0c b3 06 00 00 00 00 00
[  +1.982543] Web Content[5507]: segfault at 0 ip 00007f2e84e4efc3 sp 00007fff077b5d00 error 6 in libxul.so[7f2e84b5a000+6a7a000]
[  +0.000009] Code: 0c b3 06 e8 8f be d0 ff 41 8b 7d 08 e8 36 03 ff 02 8b 7d 08 e8 2e 03 ff 02 48 8d 05 90 56 81 04 48 8b 0d c8 1b b3 06 48 89 01 <c7> 04 25 00 00 00 00 3d 02 00 00 ff 15 c4 0c b3 06 00 00 00 00 00
[Mar 9 17:45] Web Content[16324]: segfault at 0 ip 00007fef7cdbbfc3 sp 00007ffe78fdfcd0 error 6 in libxul.so[7fef7cac7000+6a7a000]
[  +0.000013] Code: 0c b3 06 e8 8f be d0 ff 41 8b 7d 08 e8 36 03 ff 02 8b 7d 08 e8 2e 03 ff 02 48 8d 05 90 56 81 04 48 8b 0d c8 1b b3 06 48 89 01 <c7> 04 25 00 00 00 00 3d 02 00 00 ff 15 c4 0c b3 06 00 00 00 00 00

```

The offset is always 6a7a000 in libxul.so, so that's probably where the problem is.

Output from running waterfox (using the new profile since it now wants to start that one by default, convenient eh?):

```
cocaine@nihil ~ $ waterfox-current
console.log: "Loaded BootstrapLoader"
*** UTM:SVC TimerManager:registerTimer - id: xpi-signature-verification
*** UTM:SVC TimerManager:registerTimer - id: browser-cleanup-thumbnails
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 1325: uncaught exception: 2147746065
Sandbox: unsupported fd-relative fstatat(22, "", 0x7FFF8FA0EE80, 4096)
Sandbox: seccomp sandbox violation: pid 17029, tid 17029, syscall 262, args 22 140690290575194 140735603076736 4096 0 0.
Sandbox: unsupported fd-relative fstatat(47, "", 0x7FFF8FA100F0, 4096)
Sandbox: seccomp sandbox violation: pid 17029, tid 17029, syscall 262, args 47 140690290575194 140735603081456 4096 1 0.
Sandbox: unsupported fd-relative fstatat(47, "", 0x7FFF8FA0E640, 4096)
Sandbox: seccomp sandbox violation: pid 17029, tid 17029, syscall 262, args 47 140690294847410 140735603074624 4096 140689976501824 0.
Sandbox: unsupported fd-relative fstatat(47, "", 0x7FFF8FA0E6A0, 4096)
Sandbox: seccomp sandbox violation: pid 17029, tid 17029, syscall 262, args 47 140690294847410 140735603074720 4096 140689976501728 0.
Sandbox: unsupported fd-relative fstatat(22, "", 0x7FFCA4790270, 4096)
Sandbox: seccomp sandbox violation: pid 17067, tid 17067, syscall 262, args 22 140392203929434 140723067880048 4096 0 0.
Sandbox: unsupported fd-relative fstatat(29, "", 0x7FFCA47914C0, 4096)
Sandbox: seccomp sandbox violation: pid 17067, tid 17067, syscall 262, args 29 140392203929434 140723067884736 4096 1 0.
Sandbox: unsupported fd-relative fstatat(29, "", 0x7FFCA47914C0, 4096)
Sandbox: seccomp sandbox violation: pid 17067, tid 17067, syscall 262, args 29 140392203929434 140723067884736 4096 1 0.
Sandbox: unsupported fd-relative fstatat(29, "", 0x7FFCA478F9F0, 4096)
Sandbox: seccomp sandbox violation: pid 17067, tid 17067, syscall 262, args 29 140392208201650 140723067877872 4096 140391917499056 0.
Sandbox: unsupported fd-relative fstatat(29, "", 0x7FFCA478FA50, 4096)
Sandbox: seccomp sandbox violation: pid 17067, tid 17067, syscall 262, args 29 140392208201650 140723067877968 4096 140391917498768 0.
Sandbox: unsupported fd-relative fstatat(47, "", 0x7FFF8FA100F0, 4096)
Sandbox: seccomp sandbox violation: pid 17029, tid 17029, syscall 262, args 47 140690290575194 140735603081456 4096 1 0.

```

And here's the output we get when entering a url in the address bar and attempting to resolve it:
```
[Parent 16955, Gecko_IOThread] WARNING: pipe error (131): Connection reset by peer: file /usr/src/packages/BUILD/waterfox-current-kpe/src/waterfox-current-kpe-2020.10/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
[Parent 16955, Gecko_IOThread] WARNING: pipe error (50): Connection reset by peer: file /usr/src/packages/BUILD/waterfox-current-kpe/src/waterfox-current-kpe-2020.10/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358

###!!! [Parent][MessageChannel] Error: (msgtype=0x53001B,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x1E0074,name=PBrowser::Msg_StopIMEStateManagement) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x1E008F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x1E008F,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

```

So it appears there's a pipe error, researching this further finds me some old firefox issues where the recommended workaround is setting `browser.tabs.remote.autostart = false`, this appears to merge firefox to a single-process browser.

Thus the question is, how can I further debug this issue? What could cause this and how can I test for it and/or overcome it? Notably my workaround involves using midori, which is also a multi-process browser. Do they use a different type of IPC or is this an issue with this build? I'd rollback but I don't appear to have any previous packages available so I can't test if it's reasonably just an issue with 2020.10 or if it's something on my system (though what would be a good question, nothing on my system has changed since last reboot when it worked fine).

The follow-up question then seems to be, how can waterfox become more resilient to this issue? Is it at least possible for it to give a more useful message than "your tab crashed"? Saying "there was an error" isn't very helpful.

**Comment by hawkeye116477** [comment]
Waterfox „Current" is discontinued. So if you have problems you should migrate to Waterfox G3.

**Comment by TheBeardOfTruth** [comment]
This is news to me, but I can, and will, absolutely try that.

EDIT:

It appears I cannot. The package returns a 404.

Checking https://software.opensuse.org/download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-g3-kpe tells me the repo hasn't changed, so that means something's probably wrong with the package or with the repo... or with my pacman instance. 

```
pacman -S waterfox-g3
resolving dependencies...
looking for conflicting packages...

Packages (1) waterfox-g3-kpe-1.0-0

Total Download Size:    72.42 MiB
Total Installed Size:  197.79 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'waterfox-g3-kpe-1.0-0-x86_64.pkg.tar.zst' from download.opensuse.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.

```
I tried with waterfox-g3-kpe first, it didn't work so I tried dropping kpe but it seems pacman wants that version either way.

**Comment by TheBeardOfTruth** [comment]
It is worth noting that was done following a pacman -Sy.

**Comment by hawkeye116477** [comment]
Well, main repository has newer 1.1 version, but some mirror has old version, so it tries to download old version from download.opensuse.org (it downloads information about what is available  from download.opensuse.org, but got redirected to mirror and then tries to download it from download.opensuse.org)... It happens sometimes for some time, It's already known issue, I reported that to openSUSE, but they responded that they don't know how to fix that and closed that. 
So as I wrote on aur: 
> If you got 404, then temporarily try to replace download.opensuse.org with downloadcontent.opensuse.org. That should enforce direct download without mirror.

Or go to https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/Arch/x86_64/waterfox-g3-kpe-1.1-0-x86_64.pkg.tar.zst.mirrorlist, you should see available mirrors, which you can use in server field.

**Comment by TheBeardOfTruth** [comment]
I see, thank you. I tried building from source but OOM'd on linking which is more or less what I expected from having tried the same thing a couple years back.

I'll update my mirrorlist.

"we don't know how to fix, closed" sounds unproductive, that seems like a good opportunity to leave it open so people that do know can see it. Well whatever, I'm not gonna tell OpenSUSE how to do their thing.

**Comment by TheBeardOfTruth** [comment]
Okay. Got G3 1.1 set up

The setup screen crashes, reliably, on the step labeled "automatic privacy"

```[Mar10 13:52] MediaDe~hine #1[112250]: segfault at 0 ip 00007f3b1cb25d2b sp 00007f3b08041c80 error 4 in libmozsandbox.so[7f3b1cb19000+17000]
[  +0.000021] Code: 05 00 00 00 89 c6 4c 89 c2 31 c0 e8 7f 6c ff ff 48 89 c3 48 85 c0 79 c2 e8 d2 6b ff ff 48 63 18 48 f7 db eb b5 83 f8 9c 74 09 <80> 3a 2f 0f 85 9b 00 00 00 41 89 f9 41 81 e1 ff f6 ff ff 75 16 0f
[  +7.299445] MediaDe~hine #1[112326]: segfault at 0 ip 00007fc44d7ddd2b sp 00007fc437054c80 error 4 in libmozsandbox.so[7fc44d7d1000+17000]
[  +0.000011] Code: 05 00 00 00 89 c6 4c 89 c2 31 c0 e8 7f 6c ff ff 48 89 c3 48 85 c0 79 c2 e8 d2 6b ff ff 48 63 18 48 f7 db eb b5 83 f8 9c 74 09 <80> 3a 2f 0f 85 9b 00 00 00 41 89 f9 41 81 e1 ff f6 ff ff 75 16 0f
[  +2.500217] MediaDe~hine #1[112392]: segfault at 0 ip 00007fe7040bed2b sp 00007fe6ed954c80 error 4 in libmozsandbox.so[7fe7040b2000+17000]
[  +0.000017] Code: 05 00 00 00 89 c6 4c 89 c2 31 c0 e8 7f 6c ff ff 48 89 c3 48 85 c0 79 c2 e8 d2 6b ff ff 48 63 18 48 f7 db eb b5 83 f8 9c 74 09 <80> 3a 2f 0f 85 9b 00 00 00 41 89 f9 41 81 e1 ff f6 ff ff 75 16 0f

```

This step, anyway:
![SS_2021-03-10_13-54-25](https://user-images.githubusercontent.com/53689060/110632764-49592580-81a8-11eb-8947-c87e710c2159.png)


I'm just gonna ignore the welcome to waterfox thing for now, to see if it crashes in other places as well will report-back when I've got some pages loaded to see if the waterfox-current issue this thread is about is still present or if it ought to be closed (or renamed for whatever the crash in this post is, or whatever really)

**Comment by TheBeardOfTruth** [comment]
Update:

It still crashes in g3 with `browser.tabs.remote.autostart = true`, though only some websites by the looks of it.

The welcome to waterfox thing mentioned in the last comment, youtube, and presumably any other site using accelerated content.

dmesg:

```
[Mar10 14:00] MediaDe~hine #1[113238]: segfault at 0 ip 00007fd79608cd2b sp 00007fd7776fcc80 error 4 in libmozsandbox.so[7fd796080000+17000]
[  +0.000019] Code: 05 00 00 00 89 c6 4c 89 c2 31 c0 e8 7f 6c ff ff 48 89 c3 48 85 c0 79 c2 e8 d2 6b ff ff 48 63 18 48 f7 db eb b5 83 f8 9c 74 09 <80> 3a 2f 0f 85 9b 00 00 00 41 89 f9 41 81 e1 ff f6 ff ff 75 16 0f
[ +18.053524] MediaDe~hine #1[113355]: segfault at 0 ip 00007efbff9ead2b sp 00007efbd7e0dc80 error 4 in libmozsandbox.so[7efbff9de000+17000]
[  +0.000017] Code: 05 00 00 00 89 c6 4c 89 c2 31 c0 e8 7f 6c ff ff 48 89 c3 48 85 c0 79 c2 e8 d2 6b ff ff 48 63 18 48 f7 db eb b5 83 f8 9c 74 09 <80> 3a 2f 0f 85 9b 00 00 00 41 89 f9 41 81 e1 ff f6 ff ff 75 16 0f
[Mar10 14:01] MediaDe~hine #1[113458]: segfault at 0 ip 00007f632bd9bd2b sp 00007f630118ec80 error 4 in libmozsandbox.so[7f632bd8f000+17000]
[  +0.000016] Code: 05 00 00 00 89 c6 4c 89 c2 31 c0 e8 7f 6c ff ff 48 89 c3 48 85 c0 79 c2 e8 d2 6b ff ff 48 63 18 48 f7 db eb b5 83 f8 9c 74 09 <80> 3a 2f 0f 85 9b 00 00 00 41 89 f9 41 81 e1 ff f6 ff ff 75 16 0f

```

**Comment by hawkeye116477** [comment]
Ok, seems I found source of problem. I used https://github.com/MrAlex94/Waterfox/releases/tag/G3.1.1 for building, but official build uses little newer commit (https://github.com/MrAlex94/Waterfox/commit/c7366c76404f72a884e48ddfa16c13d806061206), so wrong commit is tagged. I'll rebuild today then.

**Comment by hawkeye116477** [comment]
I can confirm that. Looks like that same is if I compile it locally, but doesn't happens on for example builds for Debian 9 and official build. So it's probably something related with newer build tools, maybe it's https://bugzilla.mozilla.org/show_bug.cgi?id=1680166, I'll check.

Update: I was right. It works fine with added patch from BMO.

**Comment by TheBeardOfTruth** [comment]
I see, I'll keep an eye out for a fixed build then -- I don't have enough ram to build it locally except maybe if I run my machine headless.

**Comment by hawkeye116477** [comment]
Fixed build is available now.

https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/Arch/x86_64/waterfox-g3-kpe-1.1-1-x86_64.pkg.tar.zst.mirrorlist
