### ISSUE TITLE
Waterfox Classic break some functions (Edit and Citation) on Greasyfork site

### ISSUE THREAD

**Issue by decembre** [MrAlex94/Waterfox#1984]
When i post in a discussion or in a feedback of a script,
the button "Citation" don't have an effect for me.
    I need copy past with the good format blockquote to have it.
AND
   I can't only re-edit the text within 5 minutes of posting.

Read here:
<a href="https://greasyfork.org/fr/discussions/greasyfork/74813-edit-our-feedback#comment-189494">After tested on 2 different Waterfox profiles, its seems a Waterfox Classic Problem!.  With Firefox Quantum and Chrome all is ok!  What in Waterfox Classic can interfere with these functions?</a>

**Comment by hawkeye116477** [comment]
Well, in console:

`TypeError: window.customElements is undefined`

So Waterfox doesn't break anything. It doesn't support Custom Elements, so you need to use polyfill for Webcomponents (Polly).

**Comment by decembre** [comment]
Copy of my reply in Greasyfork forum
![PB - Waterfox + Gresyfork - Poly - Custom Elements - 2021-03-10_185711](https://user-images.githubusercontent.com/868778/110676727-96eb8780-81d4-11eb-87d0-ce4006775ce3.jpg)

Thanks:
I added <a href="https://github.com/kiyn/Polly">Polly (forked from hawkeye116477/Polly)</a> and use these settings (see the screenshots):
Now "Citation" work and hopefully the others functions too.

It solve this problem for Waterfox Classic, but maybe i added to much things?

**Comment by hawkeye116477** [comment]
> maybe i added to much things

Webcomponents-bundle.js should suffice and eventually „use request modification".

**Comment by decembre** [comment]
Seems good with your suggestions.
Is their a place where all these options are explained ?

**Comment by hawkeye116477** [comment]
Except links on Polly's readme, there is no other information.

**Comment by decembre** [comment]
That's short.
But Polly solve so many problems with waterfox!

Anyway thanks for the help...
The next time i think i drop an eye in the console....
;-)
