### ISSUE TITLE
2021.02 (64-bit) crash with NVDA

### ISSUE THREAD

**Issue by tareasR** [MrAlex94/Waterfox#1990]
When starting NVDA Waterfox 2021.02 (64-bit) running in Windows 10 totally crash.
After disabling options/General/Enable multi-process Waterfox, it seems to be possible to use NVDA.

![waterfox-crash](https://user-images.githubusercontent.com/2643363/111056045-7aa05280-8441-11eb-8f6c-fb562fa0dbf8.png)

**Comment by Squall-Leonhart** [comment]
just you.
