### ISSUE TITLE
[Waterfox Classic] Unable to enable new sites in uBlacklist extension

### ISSUE THREAD

**Issue by user234683** [MrAlex94/Waterfox#1991]
This extension blocks sites from appearing in search results but is not working properly in Waterfox classic.

Steps to reproduce:
1. Download [uBlacklist](https://addons.mozilla.org/en-US/firefox/addon/ublacklist/)
2. Go to the options for the extension. Add this line: `*://*.reddit.com/*`
3. Select Enable for duckduckgo, and accept the new permissions
4.  Compare https://duckduckgo.com/?q=test+site%3Areddit.com&ia=web vs https://www.google.com/search?q=test+site%3Areddit.com&ie=utf-8&oe=utf-8
5. The site is blocked on google but not duckduckgo. This issue does not happen on Firefox.
6. Restart Waterfox. Going back to the options page, duckduckgo is no longer enabled.

The following error appears in the browser console right after accepting the new permissions: `TypeError: browser.contentScripts is undefined`

Waterfox version: 2021.02 (64-bit)

**Comment by hawkeye116477** [comment]
See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts. It's supported from FF 59, so it won't work on 56. Developer should set correct supported FF version.

CC @iorate

**Comment by user234683** [comment]
Yes, but are there plans to support this WebExtension API in Waterfox Classic? Waterfox Classic is trying to add support for as much of WebExtensions as possible, right?

**Comment by hawkeye116477** [comment]
> Waterfox Classic is trying to add support for as much of WebExtensions as possible

Well, officially there are no such plans. Some things got ported by me, cuz I'm using uBO.

Main developers rather planned to add only security updates. Novelties are added only by volunteers.
