### ISSUE TITLE
[Classic] Collaboard app is not working properly

### ISSUE THREAD

**Issue by DvP17** [MrAlex94/Waterfox#1994]
Unfortunately, the whiteboard app Collaboard (https://www.collaboard.app/) does not work properly with Waterfox Classic. Mouseover and dragging of notes does not work as it should.

Waterfox version: 2021.02 (64-bit)

**Comment by MrAlex94** [comment]
Wouldn't surprise me if it's using HTML standards not supported by Waterfox. Unless someone submits a patch to fix, this issue will be closed.
