### ISSUE TITLE
Memory leak in Waterfox Classic

### ISSUE THREAD

**Issue by Vulpovile** [MrAlex94/Waterfox#1995]
While opening a single HTML4 page, Waterfox ends up using more than 1GB of RAM total in up to 4 processes. Sometimes it manages to crash and run out of memory on a computer that has 16GB or RAM. I haven't had this problem before until recently.

**Comment by Felipefpl** [comment]
Got lots of RAM usage too if i open a lot of pages and then close them after some time, waterfox keeps spending A LOT of RAM for pages that arent even there.....

**Comment by Squall-Leonhart** [comment]
not a valid bug report, use the template.
