### ISSUE TITLE
Page loading issue

### ISSUE THREAD

**Issue by newsjunkie247** [MrAlex94/Waterfox#1997]
This site doesn't load articles fully anymore: https://www.adweek.com/media/the-new-yorker-launches-subscribers-only-virtual-event-the-new-yorker-live/ It works in Firefox Nightly/Chrome. It's not a paywall issue as those both let me load at least one full article.

**Comment by bruhdev1290** [comment]
I am not able to reproduce this issue can you give additional information are you using waterfox classic or the current version.

**Comment by newsjunkie247** [comment]
Waterfox Classic. It will load an initial paragraph, but if you load it in Firefox or Chrome, it should load an entire article.

**Comment by Felipefpl** [comment]
the same happens on twitter, waterfox classic loads the 1st part of twitter but it loads the rest a few seconds AFTER scrolling.

**Comment by newsjunkie247** [comment]
In my case it doesn't load the full article at all. and Twitter loads fine for me.

**Comment by MrAlex94** [comment]
Unfortunately hard to debug without a premium account. But wouldn't surprise me if it's using HTML features not supported by Waterfox Classic.
