### ISSUE TITLE
[G3] Import Profile imports nothing

### ISSUE THREAD

**Issue by suamor** [MrAlex94/Waterfox#2000]
**Description**
Importing an existing profile from firefox does not work. Nothing will be imported.
I tried different profiles: 2017 (oldest), ESR, 2020 (last autumn)
For each import I cleaned up .mozilla/firefox folder, so it only had one single profile.

**Preconditions**
1. No Web browser is running
2. Checked with recent firefox 86.0 profile manager that profiles are recognized
3. Start new profile for waterfox-g3 without any options (and remove them after each test)

**Misbehavior/Reaction**
1. Existing classic and current profiles are ignored and not imported. Instead a message is shown that a new profile was created
2. Waterfox reports succesful import of Firefox profile but in reality imports nothing.

**Expected behavior**
Profile is imported (Passwords, Bookmarks, Addons that are supported, Session)

**Environment**
Ubuntu 20.04 LTS

**App Version**
Waterfox Ltd. Waterfox G3.1.1

**Remark**
1. I want to migrate older profiles and it is critical that I'm able to at least import older passwords and bookmarks. Session can be backuped with addons. There is no other password import function.
2. Firefox has an password import function that is missing from Waterfox (known issue, will be changed in the future)
3. Firefox Account cannot import anything stored from older browser versions (older than last autumn).

**Comment by suamor** [comment]
I tested import on firefox 86 and had no issues importing the profile from last autumn.

**Comment by MrAlex94** [comment]
I cannot reproduce either. I would suggest modifying profiles.ini to point to the profile you'd like to use. I apologise it's not an elegant way - but bugs like this are hard to resolve.
