### ISSUE TITLE
Waterfox to get option to manage optional extension permissions on about:addons

### ISSUE THREAD

**Issue by candrapersada** [MrAlex94/Waterfox#2002]
Waterfox users who install browser extension may be familiar with the permissions prompt that is displayed when extensions get installed. Extension developers may use a default set of features that require no permissions but need to request permissions if APIs are needed that provide extra functionality.

While most of the permissions are required for functionality, e.g. a tab managing extension needs access to browser tabs and website data, some permissions may be optional. Optional permissions are usually required if a user enables certain functionality that is not enabled by default.

To give you an example. [The Simple Tab Groups extension](https://addons.mozilla.org/de/firefox/addon/simple-tab-groups/) requests six required permissions when it is installed. You may enable access to the browser's bookmarks in the options, and that requires the permission to access bookmarks of the browser; this is an optional permission as it is not enabled by default and not required for the extension's default functionality.

Optional permissions are not listed in about:addons, Waterfox's internal management page for extensions, at the time of writing. That's a problem, as managing of these optional permissions depends on the extension's author integration of an option to revoke these permissions again. Additionally, it is impossible to quickly check which extensions have optional permisssions.

Mozilla added an option to Firefox 84 Nightly to display and manage optional permissions on the about:addons page.

![image](https://user-images.githubusercontent.com/36833664/111962360-cd09ff00-8b24-11eb-9c65-c4e2d6a7f41d.png)

Just open any of the installed extensions on the page and switch to the permissions tab. There you find required and optional permission groups.

While you cannot modify required permissions, you may toggle optional permissions with a click or tap on the switch on the page. Revoking optional permissions may lead to a loss of functionality, as certain features will become unavailable due to a lack of permissions.

so please add the option to manage optional extension permissions without waiting for Gecko 91.3 in Waterfox

**Comment by MrAlex94** [comment]
Sorry, this will have to come in the next major release - it's not a trivial change and backporting would likely take a while (at which time the next major release would be available).
