### ISSUE TITLE
Bookmarks New Folder

### ISSUE THREAD

**Issue by s3dbw** [MrAlex94/Waterfox#2009]
When trying to create a new folder, either by right clicking on bookmarks or going through the show all bookmarks page, the new folder box is completely blank and does not allow you to enter details?

![New Folder](https://user-images.githubusercontent.com/81376784/112502620-202cbd80-8d82-11eb-91d6-4703e213007a.JPG)

**Comment by MrAlex94** [comment]
How odd - are you using a custom theme or anything like that?

**Comment by s3dbw** [comment]
No, Bing wallpaper in background only

**Comment by MrAlex94** [comment]
Do you still have this issue with G4?

**Comment by s3dbw** [comment]
Just update to G4 and problem solved!! Thanks
