### ISSUE TITLE
[Classic]Ubereats.com no longer loads the payment details on the checkout screen

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox#2010]
## Expected behavior
Added payment details are loaded

## Actual behavior
Payment button does not change from "Add payment method"

Adding a payment method fails because the method is already added.

## Steps to reproduce the problem

  1. Add anything from any store to your basket.
  1. Navigate to the checkout

![image](https://user-images.githubusercontent.com/1098176/112577794-35205400-8e49-11eb-9376-3a3722649156.png)

**Comment by MrAlex94** [comment]
Looks like Polly doesn't fix the issue completely - unlikely this will be fixed in classic unless someone submits a patch for it.
