### ISSUE TITLE
Classic 2021.02 - Downloads FAIL, every time, everywhere, every file.

### ISSUE THREAD

**Issue by SPWGitHub** [MrAlex94/Waterfox#2011]
Downloads FAIL, every time, everywhere, every file.

**Comment by Felipefpl** [comment]
I have this problem too but it happens once in a while.

**Comment by Squall-Leonhart** [comment]
fix your computer.

**Comment by SPWGitHub** [comment]
Fix your keyboard !
Steve Wilson
      (͡° ͜ʖ ͡°)

**Comment by SPWGitHub** [comment]
!
