### ISSUE TITLE
[G3][Feature Request] Native Apple Silicon Support

### ISSUE THREAD

**Issue by UInt2048** [MrAlex94/Waterfox#2013]
Rather than using Rosetta 2, if possible, please allow a native Apple Silicon build!

(It would also be great for Classic to take care of #1864.)

Also being asked for on Reddit: https://old.reddit.com/r/waterfox/comments/mbpm7h/apple_silicon_version/

Edit: Firefox already supports this as of Firefox 84.0.

**Comment by MrAlex94** [comment]
It will arrive with the next ESR due in the coming months. If there's time, we'll try before - but officially it comes with the next ESR.
