### ISSUE TITLE
[Classic] Add dark moded default theme

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2020]
I don't like the compact theme, I want to see a dark mode like what G3 has, in Classic.

**Comment by hawkeye116477** [comment]
Well, it's already on Linux, when I'm switching to dark OS theme, then Classic default theme also switches to dark mode (except preferences/options).

**Comment by ghost** [comment]
I want a full dark theme. Something like [this theme](https://www.mediafire.com/file/bof16of0i9i0kdn/%2528XUL%2529_THEME__FT_DeepDark-14.4.7.xpi/file) but with the looks of the default one.

**Comment by MrAlex94** [comment]
Sorry, this will only be for default themes included.
