### ISSUE TITLE
Waterfox Classic 2021.03 is not possible to post a comment on vk.com (repeat)

### ISSUE THREAD

**Issue by ruboard** [MrAlex94/Waterfox#2022]
https://github.com/MrAlex94/Waterfox/issues/1956
"Starting with Waterfox Classic 2020.12, it is not possible to post a comment on https://vk.com Waterfox Classic 2020.10 works fine
the submit comment button is not active"
replacing ucrtbase.dll 10.0.10240.16390 solves the problem
https://images2.imagebam.com/4a/ec/31/edaf721374204991.JPG

**Comment by Squall-Leonhart** [comment]
Don't open duplicate issues.

I'm amused that 2021.3 was built without acknowledging the conversation alex was tagged in though, means he isn't paying any attention at all to user issues he has caused.
