### ISSUE TITLE
[G3] Scrollbar-color stops working for Abyss and Floe themes

### ISSUE THREAD

**Issue by hawkeye116477** [MrAlex94/Waterfox#2025]
When you enable Abyss or Floe theme, then scrollbars aren't colored if `scrollbar-color` CSS property is set.
Go to http://wpt.live/css/css-scrollbars/viewport-scrollbar.html and you will see the problem. Scrollbars are even thinner on that two themes. I don't know if that was intended, but maybe at least overriding that by websites should be allowed.

**Comment by MrAlex94** [comment]
This is what I'm seeing:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/4728920/119854868-57962280-bf09-11eb-97b7-cd61720d38f1.png">
<img width="609" alt="image" src="https://user-images.githubusercontent.com/4728920/119854918-654ba800-bf09-11eb-810a-ae28a1a6a8b1.png">

Is that not correct?

**Comment by hawkeye116477** [comment]
It's correct, unfortunately I see that. Reproduced on Linux and W10.

![2021-05-27_19-22](https://user-images.githubusercontent.com/19818572/119869723-de0a2e80-bf20-11eb-9453-53990d93156a.png)

**Comment by MrAlex94** [comment]
G4 shouldn't have this problem anymore with the Lepton/Australis themes.
