### ISSUE TITLE
Bookmark sync creates duplicates.

### ISSUE THREAD

**Issue by Haiyami** [MrAlex94/Waterfox#2026]
I see the sync option is still using Firefox's system/servers to back up bookmarks. Just to let you know their bookmark sync function is very broken and they Firefox has no intention of fixing it. When syncing bookmarks between devices duplicates will often be made. I am wondering if development of waterfox can get away from the Firefox sync system and create a true backup/sync system like how server/raids on hard drive data does. So if one device adds like 10 bookmarks to a list of 1000 instead of syncing 1010 bookmarks to the other device it would just update the current saved bookmarks by adding just those 10? As of right now when bookmark syncing happens bookmarks will get duplicated. I've had this issue on windows 7 and windows 10. Also if one computer is using Waterfox current and the other is using waterfox classic, the bookmarks end up getting corrupted.

Is there no plan to fix the backup/restore/syncing of bookmarks function? While I love the tagging system of firefox type bookmarks, I hate how broken it's backup/restore and syncing function is. It needs vast improvement.

**Comment by MrAlex94** [comment]
We are definitely looking into an alternative solution - but unsure of any timelines.
