### ISSUE TITLE
Images using GPU Memory even when hardware acceleration disabled

### ISSUE THREAD

**Issue by jabcreations** [MrAlex94/Waterfox#2030]
Right now with just a few tabs open Waterfox is using roughly ~1142 megabytes of GPU memory! I unfortunately still only have a 4GB video card (290X). I disabled hardware acceleration and restarted with no noticeable effect. Then I went to the Windows 10 Pro x64 Task Manager and added the "Dedicated GPU memory" column and sorted it by that column. I then killed the process using the most RAM, my homepage! It's a basic XHTML and CSS page with some weather maps. So I naturally disabled images using an older competent version of Chris Pederick's Web Developer toolbar to disable images and the GPU RAM usage dropped like a rock.

The thing is - I have zero idea of how to stop Waterfox from dumping images in to my GPU's memory. I do get to occasionally enjoy a video game though I literally have to close my browser (and all of the related work) just to free up GPU memory that shouldn't even be getting used to begin with. With no browsers open the dedicated GPU usage is reported around half a gigabyte.

**Comment by Squall-Leonhart** [comment]
Working as intended.

Though you clearly don't understand how Windows handles Virtualization of video memory (browsers are dumped to page)

**Comment by jabcreations** [comment]
Yeah no I don't want the browser wasting my GPU memory.

Also I have the page file disabled because I don't hate my hard drive, hate performance or am too cheap to buy a sufficient amount of RAM.

**Comment by Squall-Leonhart** [comment]
Then you're a fool, suffer.

**Comment by jabcreations** [comment]
Closing due to troll.
