### ISSUE TITLE
Blank window when opening external link

### ISSUE THREAD

**Issue by tom-cor** [MrAlex94/Waterfox#2033]
Hi everyone! I'm using Linux Mint 20.1 Cinammon at the moment, but I ran into the same problem while testing it on a Ubuntu VM.
Anytime I try to open an external link, from Whatsapp or an app takes me to the browser to get a login token, Waterfox opens a blank window.
I really like Mozilla based browsers, but this issue is quite troublesome. Does anyone know how to solve this? Maybe I installed it incorrectly.
If anyone has a tutorial on how to do it, I would really appreciate it!

**Comment by tom-cor** [comment]
I found the solution, just another newbie linux user haha

**Comment by locrianz** [comment]
Would you mind sharing the solution for other people having this problem?

**Comment by Kangaroux** [comment]
Workaround: https://github.com/BrowserWorks/waterfox/issues/3575#issuecomment-2731208762
