### ISSUE TITLE
Issue #2034 is the users own doing

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox#2035]
1> Windows requires a page file for proper operation, by disabling it the user has removed the ability for windows to properly manage virtualized video memory.

> Also I have the page file disabled because I don't hate my hard drive, hate performance or am too cheap to buy a sufficient amount of RAM.

He has displayed a complete ignorance to windows internals and how the system operates, like every fool ever that disables the page file.

Refer to: https://azius.com/pagefile-yes1/
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/paging-video-memory-resources

2> The reported behavior in that issue is the same behavior in Firefox, GDI still consumes video memory, textures still get decoded to video memory regardless if the Renderer is drawing directly into the compositor or not.

3> No, the customer is not always right.

**Comment by AM4Ryzen** [comment]
Can you like not be an asshole?

**Comment by Squall-Leonhart** [comment]
> 
> 
> Can you like not be an asshole?

Can you develop an intelligence above the level of swearing in a public git project?

No?

Move along.

**Comment by MrAlex94** [comment]
Sorry, but this is not an issue related to the development of Waterfox. Issue tracking is also not for discussions.
