### ISSUE TITLE
Classic 2021.03 - Youtube.com still completely useless!

### ISSUE THREAD

**Issue by SPWGitHub** [MrAlex94/Waterfox#2038]
![Youtube_Useless](https://user-images.githubusercontent.com/22408621/114641685-94cb8b80-9ca0-11eb-9200-f499fc0d818c.png)
Classic 2021.03 - Youtube.com still completely useless!

**Comment by SPWGitHub** [comment]
Also, to successfully insert the screenshot, I had to use Chrome.  I hate the thought of giving up WF Classic, but it seems the day is nearing.

**Comment by gerov1** [comment]
Well for me youtube.com working completely fine. Both on Classic 2021.02 and 2021.03

**Comment by SPWGitHub** [comment]
I just tried safe mode. No dice.
Then I tried a clean profile. Works fine.
Man, it's gonna take days to rebuild my profile! 😞 😧 😢

**Comment by hawkeye116477** [comment]
Just remove extension for YouTube or custom user-agent overrides.

**Comment by SPWGitHub** [comment]
@hawkeye116477

"tried safe mode. No dice."

How is your suggestion even relevant?
