### ISSUE TITLE
Stylus Addon + Waterfox Classic : can't install Usercss ?

### ISSUE THREAD

**Issue by decembre** [MrAlex94/Waterfox#2040]
Posted too on Stylus Addon (Github):
[invalid regexp group](https://github.com/openstyles/stylus/issues/1220)

With Waterfox Classic 56.5,
when i want install an userstyle from USw or USO,
By example for <a href="https://userstyles.world/style/34">Stylus Black Edition by BillyCool</a>

With my principal profile, i have an error massage:
"Stylus a échoué à parser le usercss :
invalid regexp group"

Or on an other profile:
"Stylus a échoué à parser le usercss :
can't access lexical declaration `metaParser' before initialization"

I tested too with disable userscripts ...

On Chrome / Firefox Quantum , no problem.

Note:
I have the same error message when i copy paste the usercss code in the Stylus editor...

Am i alone with this problem?

**Comment by hawkeye116477** [comment]
There was already reply => https://github.com/openstyles/stylus/issues/1220#issuecomment-812862606

That feature isn't implemented in WF Classic, so it won't work.

**Comment by decembre** [comment]
Ok, but it's a" WontFix"?

**Comment by hawkeye116477** [comment]
Well, authors of that extension said that they will fix that by themselves, even someone made Pull Request.

![2021-04-15_11-20](https://user-images.githubusercontent.com/19818572/114846135-ab76fd00-9ddc-11eb-857b-6bb0e0b6f96c.png)

**Comment by decembre** [comment]
thanks:
so, wait and see....
