### ISSUE TITLE
Google voice breaks on 2021.03 (64-bit) Classic

### ISSUE THREAD

**Issue by code-issues-pull** [MrAlex94/Waterfox#2045]
voice.google.com

Applied the 2021.03 (64-bit) update this morning and since then google voice fails to render properly. I've tried on my main profile and an alternate profile that has zero addons.

Changing user agent does not resolve the issue either.

Console output has a LOT of this happening:  
> Error: The expression cannot be converted to return the specified type.
eka/<@https://www.gstatic.com/_/voice/_/js/k=voice.voice_module_set.en_US.R9smC-bCmL4.O/am=RA/d=1/ct=zgms/rs=AJAOlGme1pci35hid7HzcsC1v639FndlcA/m=base:363:169
Vb/<@https://www.gstatic.com/_/voice/_/js/k=voice.voice_module_set.en_US.R9smC-bCmL4.O/am=RA/d=1/ct=zgms/rs=AJAOlGme1pci35hid7HzcsC1v639FndlcA/m=base:44:216
_.f.eV@https://www.gstatic.com/_/voice/_/js/k=voice.voice_module_set.en_US.R9smC-bCmL4.O/am=RA/d=1/ct=zgms/rs=AJAOlGme1pci35hid7HzcsC1v639FndlcA/m=base:2090:31
_.f.subscribe@https://www.gstatic.com/_/voice/_/js/k=voice.voice_module_set.en_US.R9smC-bCmL4.O/am=RA/d=1/ct=zgms/rs=AJAOlGme1pci35hid7HzcsC1v639FndlcA/m=base:2089:358
Sba.prototype.call@https://www.gstatic.com/_/voice/_/js/k=voice.voice_module_set.en_US.R9smC-bCmL4.O/am=RA/d=1/ct=zgms/rs=AJAOlGme1pci35hid7HzcsC1v639FndlcA/m=base:2194:72
_.f.subscribe@https://www.gstatic.com/_/voice/_/js/k=voice.voice_module_set.en_US.R9smC-bCmL4.O/am=RA/d=1/ct=zgm[…] <gv-side-nav expanded="true" embedded="true">

**Comment by code-issues-pull** [comment]
Still broken on 2021.04.1 (64-bit)

**Comment by code-issues-pull** [comment]
Still broken on 2021.04.2 (64-bit)

**Comment by jiangzhenjerry** [comment]
I doubt WF Classic will ever fix issues like this. WF Classic itself (which is a fork of very old Firefox codebase) doesn't handle polyfills well, so it requires extra coding (per site) - or a polyfill add-on plus user's knowledge of how to configure polyfills. Please hope for the best, but don't get frustrated if it never gets fixed.

**Comment by newsjunkie247** [comment]
It still works in 2021.02. So doesn't seem like a Polyfill issue.

**Comment by Avrution** [comment]
Interesting that it still works in 2021.02 - should mean something can be worked out?

**Comment by MrAlex94** [comment]
Unfortunately without a patch from someone to fix this - will have to close the issue.

**Comment by hawkeye116477** [comment]
Can someone check how it's on build from https://github.com/hawkeye116477/Waterfox/releases/tag/classic_perf_fix? It needs to be extracted with WinRAR or 7-Zip.

**Comment by jiangzhenjerry** [comment]
@hawkeye116477 Well done, your build renders Google Voice correctly on my end :) Windows 11 x64 Enterprise.
