### ISSUE TITLE
Waterfox Classic 2021.3 - Cant Watch/Listen Videos at Crunchyroll

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2046]
I can see/listen the ads' videos but not the main videos that come after them. I reported this to the site but couldnt get no good answer from them about that, i did what was told in the FAQ, cleaned cache but it didnt work so i deduce this is a bug from waterfox.

Edit - i was able to watch videos there a few times but now i cant do it, didnt change ANYTHING in the browser that could create such problem.

**Comment by ChrisIdema** [comment]
Maybe you have the same problem as me. I cannot play videos on DRM-protected videos on Udemy: https://github.com/MrAlex94/Waterfox/issues/2101

Can you check if there is a similar error code in your web console when trying to play a crunchyroll video?

**Comment by ChrisIdema** [comment]
I checked and got this error (in latest waterfox version, did not try classic):
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource `
By disabling my ad blocker the error disappeared and I could play a video on Crunchyroll.

**Comment by MrAlex94** [comment]
Seems an issue with CR supporting older browsers. Unfortunately there's no easy fix unless someone finds the relevant HTML spec not supported and implements it.
