### ISSUE TITLE
Impossible to enable GTK file chooser in G3 under KDE?

### ISSUE THREAD

**Issue by sonofevil** [MrAlex94/Waterfox#2047]
It seems that ever since I switched to G3 (from Hawkeye116477's Arch repo*), there is no longer any way to enable the GTK file chooser. I used to be able to do this via GTK_USE_PORTAL=0, but this no longer works. I set the variable in the launch command & checked with `ps eww <process ID>` that it's in fact set to 0 for the app.

This problem persists with a fresh profile. I have uninstalled kwaterfoxhelper and am only running waterfox-g3-kpe. Other GTK apps are able to use the GTK file chooser with no issue. If I terminate the xdg-desktop-portal background processes, they get restarted as soon as I click "Open File".

I don't know what else could possibly cause this from my side.

*I tried to compile Waterfox myself, but I got a compile error after 3 hours. Hawkeye does not have a bugtracker for their packages, so while I'm not 100% sure this is a problem caused by the official source, there seems to be no proper way to complain downstream, so please excuse if I'm at the wrong address.

Waterfox version: waterfox-g3-kpe-2.0-0 Arch 64bit build from Hawkeye116477
OS: EndeavourOS with KDE Plasma.

Steps to reproduce: 

1: Run `GTK_USE_PORTAL=0 waterfox-g3`
2: Go to "Open file"

Expected result: GTK file chooser opens.
Actual result: KDE file chooser opens.

**Comment by sonofevil** [comment]
I just found out there is a waterfox-g3-bin 2.1-1 package on AUR now, so I tried installing that, but that didn't change anything about the issue.

**Comment by hawkeye116477** [comment]
Well, by default GTK file chooser is available.

> Hawkeye does not have a bugtracker

It's here => https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/.

**Comment by sonofevil** [comment]
https://forum.kde.org/viewtopic.php?f=309&t=157161

This person had the same issue with Firefox, so maybe the cause isn't Waterfox-specific? Could be either due to an update to how XDG portal interacts with Firefox, or an update to Firefox code which got pulled by Waterfox. Or convergent bugvolution. Presumable the issue they had is still unresolved, but unlike me they no longer want to disable the KDE file picker.

Btw if I uninstall xdg-desktop-portal-kde (but leave xdg-desktop-portal-gtk in place), Waterfox is no longer able to open *any* file picker. This makes me think that going for the kde portal is hardcoded into the app. Unless there is some obscure about:config setting that I can't find.

**Comment by sonofevil** [comment]
Hold on - after closing all xdg processes and allowing them to restart via service, xdg seems to have realized that the kde portal is no longer installed and now opens the gtk file picker. Yay!

So yeah, uninstalling the kde portal is a functional workaround after all. It's just weird that this behavior can't be achieved through environment variables anymore.
