### ISSUE TITLE
Why is my Bookmarks no longer Visible with 2021.03 (64-bit) Classic ?

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#2050]
Since the last update my Book Mark Toobar is gone and can not get it back why is it gone?

**Comment by hawkeye116477** [comment]
Well, looks like that's problem on your side, cuz I can't reproduce that.

Maybe good would be pasting unprocessed data from `about:support`.

**Comment by A0R-R0CKS** [comment]
[image: image.png]
