### ISSUE TITLE
goldbolt.org (compiler explorer) doesn't work: no content is displayed

### ISSUE THREAD

**Issue by Bu11etmagnet** [MrAlex94/Waterfox#2052]
![image](https://user-images.githubusercontent.com/7579651/115275144-bcf43800-a141-11eb-8cc9-a609fd713371.png)

Waterfox Classic 2021.03 (64-bit), Windows 10 64-bit

**Comment by hawkeye116477** [comment]
From console: `SyntaxError: invalid identity escape in regular expression`.

**Comment by mattgodbolt** [comment]
For what it's worth the "fix" (or at least one of them) is coming in a newer Monaco. If it's something the browser wants to support the patch that fixed it might give clues: https://github.com/microsoft/vscode/pull/118400/files#diff-dde3b56145713053f086e5ce1fcea39c4cb171d4555b6ab91256c7cf2b39e9afR1061

**Comment by MrAlex94** [comment]
Thanks @mattgodbolt 👍
