### ISSUE TITLE
Search bar appears in toolbar automaticaly

### ISSUE THREAD

**Issue by AdolfMuffin** [MrAlex94/Waterfox#2053]
Waterfox shows me the search bar, so I have no clue on why Waterfox does it. So even when I remove the search bar from toolbar, it appears again in a hour. I thought, this happens because of using the Firefox and Waterfox under same  Firefox account, and Waterfox tries to synchronize appearance with Firefox settings, but I also have disabled search bar on Firefox too.

**Comment by MrAlex94** [comment]
Make sure both these preferences are set to `false` in `about:config`:
`services.sync.prefs.sync.browser.search.widget.inNavBar`
`browser.search.widget.inNavBar`

**Comment by jaoord** [comment]
why is there no settings screen option for `browser.search.widget.inNavBar` or am i overlooking it?
