### ISSUE TITLE
Silent crash in safe mode

### ISSUE THREAD

**Issue by HYBRID-BEING** [MrAlex94/Waterfox#2055]
Not sure why or when it started, but I no longer can run my profile in Waterfox. Don't recall installing any new extensions before this, though. Everything seems fine in a clean new profile. In broken one, I'm presented with a safe mode prompt, and after selecting "Start in Safe Mode", Waterfox window appears, but instantly closes (along with any waterfox.exe process).

Water fox version is 2021.03, running on Windows 10 Home 1909.

**Comment by MrAlex94** [comment]
Very strange. Unfortunately it's hard to debug - I can only suggest [creating a new profile](http://kb.mozillazine.org/Profile_Manager) and moving over [pieces of your profile](http://kb.mozillazine.org/Profile_folder_-_Firefox#Files) (when it's closed of course!) and seeing which component causes the crash?

**Comment by MrAlex94** [comment]
Classic has now been moved to "security" mode only - so any fixed will have to be submitted, if you are still facing this issue.
