### ISSUE TITLE
Waterfox 2021.04.01 port Bug: This address is restricted.

### ISSUE THREAD

**Issue by andreacc** [MrAlex94/Waterfox#2057]
When trying to access localhost:3000 I get

"This address is restricted. This address uses a network port which is normally used for purposes other than Web browsing. Waterfox has canceled the request for your protection."

Searching the web I got the solution to add "network.security.ports.banned.override" value "3000" to about:config. But it didn't worked.

**Comment by colvacdir** [comment]
MacOS 10.12.6
Waterfox Classic 2021.04.1

Can't access the "Test your browser" link on https://www.ssllabs.com/ as of the latest update.

It now redirects to:
Moved Permanently
The document has moved here.

Clicking on "here" shows this error message:
This address is restricted
This address uses a network port which is normally used for purposes other than Web browsing. Waterfox has canceled the request for your protection.
Try Again

It seems to be blocking port 8443. Works fine on 2021.03.

I believe this is related to:
[Classic] security patches #2054
[Bug 1698503 - robuster port blocking. r=dragana, a=RyanVM](https://github.com/MrAlex94/Waterfox/pull/2054/commits/8fad8b54e74b2b2ab50861f2050bae284ec95989)

Line 1268:  `if (port || port >= std::numeric_limits<uint16_t>::max()) {`

Correction?: `if (port <= 0 || port >= std::numeric_limits<uint16_t>::max()) {`

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@colvacdir @MrAlex94 You also need to cherry-pick [this commit](https://github.com/MrAlex94/Waterfox/commit/dc4eac2116f1e553320e8652d70edd5e17d16125).

**Comment by jcea** [comment]
Being hit by this too. Please, publish a waterfox update.

**Comment by code-issues-pull** [comment]
Just override in about:config https://www.ryadel.com/en/firefox-this-address-is-restricted-override-fix-port/

**Comment by code-issues-pull** [comment]
Just kidding, override doesn't seem to work. So yeah, this is a fun update.

**Comment by stalker780** [comment]
Same for port :1500

**Comment by DAVe3283** [comment]
> @colvacdir @MrAlex94 You also need to cherry-pick [this commit](https://github.com/MrAlex94/Waterfox/commit/dc4eac2116f1e553320e8652d70edd5e17d16125).

While I agree that commit should be picked, it wasn't in the previous release (https://github.com/MrAlex94/Waterfox/blob/2021.03-classic/netwerk/base/nsIOService.cpp#L1257), so that isn't the problem/fix here, it seems.

**Comment by stalker780** [comment]
Installing Waterfox 2021.04 over Waterfox 2021.04.01 does not fix this issue

**Comment by nveaa1** [comment]
@stalker780 

I can also confirm that installing Waterfox 2021.04 over Waterfox 2021.04.01 did not fix this issue for me either.

Installing Waterfox 2021.03 seemed to fix it, though.

**Comment by B-IT** [comment]
It´s a nice DOWNGRADE !

**Comment by jcea** [comment]
Please, release 2021.04.02 ASAP!.

**Comment by 117649** [comment]
So all url with a port section are blocked now.

**Comment by MrAlex94** [comment]
Builds are almost ready and release imminent. Sorry about the hubub.

**Comment by wagle** [comment]
I feel uncomfortable opening port 5001 on my browser to the entire planet.  Is there any chance of adding ip-address ranges or something to the port numbers?

**Comment by DAVe3283** [comment]
@wagle you are not opening the port on the browser to incoming traffic. This is un-blocking it for _outgoing_ traffic, such as connecting to a web server running on a non-standard port. That is a common scenario in home labs or with things like Plex.

**Comment by wagle** [comment]
@DAVe3283 Yeah, I wasn't thinking clearly.  I still feel uncomfortable being able to do port 5001 to the entire planet, but not as much.  I pretty much have waterfox walled off to only talk to my local personal wiki on port 5001.

**Comment by wagle** [comment]
Maybe I don't have a problem with non-localhost URLs.  I use redirector to forward those to choosy to forward them to a battened down modern firefox or (ugh) chrome.  My wiki critically depends on two firefox extensions that firefox decided to block, but that work fine on waterfox classic.  Well, until now.

**Comment by DAVe3283** [comment]
This is way off topic for the bug (which I can confirm has been fixed by Waterfox Classic 2021.04.2), but if you want to restrict what ports Waterfox can connect to, the right tool is an OS-level firewall. I think you can even do what you want with the built-in Windows firewall on Windows 7 and newer.

**Comment by wagle** [comment]
If a firewall is the solution for off host traffic, the question becomes "why is on host traffic being restricted?".

Yeah, a bit off-topic, but it was really hard to find this, an active discussion site for waterfox.  Lots of dead ones.  And, I wasn't expecting this to go on for a sort-of "yes / no" question.

**Comment by DAVe3283** [comment]
I am not sure I follow what you are asking. If you think Waterfox shouldn't be restricting what ports you can connect to at all, and let a firewall/security appliance enforce that, then I completely agree. This "feature" was inherited from Firefox, perhaps there is a discussion somewhere there that explains what they were thinking. I personally disagree with the feature even existing, so I can't explain what it is supposed to do/fix.
