### ISSUE TITLE
Tab crashes when opening wikipedia - classic 2021.4

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2059]
I made searches using qwant and tried to open 2 different wikipedia's pages several times and those crashed for no reason.

**Comment by jiangzhenjerry** [comment]
This issue was already fixed yesterday in [2021.04.1](https://www.waterfox.net/blog/waterfox-2021.04-release/). Please upgrade your Classic.

**Comment by Felipefpl** [comment]
i see, thanks for the reply.
