### ISSUE TITLE
waterfox startup error 

### ISSUE THREAD

**Issue by allblue** [MrAlex94/Waterfox#2063]
After installing in the Mac system, the startup error is reported, and there is no residual configuration on the computer.

![图片](https://user-images.githubusercontent.com/844763/115947804-ccd29a00-a4fc-11eb-887d-c05ff68466f5.png)

btw：I have encountered it several times on windows, it can be restored after deleting the profile directory.

**Comment by hawkeye116477** [comment]
Did you installed language pack from AMO? It's incompatible with Waterfox, so you need to remove it to fix that.

**Comment by allblue** [comment]
> 
> 
> Did you installed language pack from AMO? It's incompatible with Waterfox, so you need to remove it to fix that.

yeah，u r right
Even through i installed language pack from waterfox's github, the solution is the same
