### ISSUE TITLE
Waterfox Classic 2021.04+ breaks Kee 2.5.6 RPC support

### ISSUE THREAD

**Issue by DeepMac** [MrAlex94/Waterfox#2064]
Using Waterfox 2021.03 and less I can always use the Kee 2.5.6 legacy extension to integrate KeePass for Windows into my browser. Requires using the Keepass RPC plugin (https://github.com/kee-org/keepassrpc/releases)

After updating to 2021.04.1, I discovered the Kee extension will always report that I'm not logged into KeePass database, regardless if I actually am.

Troubleshooting, I tried flushing my KeePass plugin cache, removing the RPC plugin and flushing the cache and then re-installing the plugin, restarting the browser, the Keepass application and the PC. I finally downgraded to Waterfox Classic 2021.04 and the issue persisted. Then I downgraded to Waterfox 2021.03 and was able to re-establish an RPC connection to the database.

It seems like something introduced while moving to the Classic/G3 releases is preventing the Kee 2.5.6 extension from communicating to the RPC listener on the localhost. Possibly a security-related setting?

I can provide additional data if necessary, please just ask. :)

**Comment by MrAlex94** [comment]
Unfortunately we had to block some ports due to them being used by malware - I'm assuming you've been hit by that. I can't really recommend any good way to fix it unfortunately. 2021.04.2 attempted to fix it, unfortunately if that doesn't resolve the issue not sure what to suggest.

**Comment by tiatin** [comment]
I confirm from my side that 2021.04.2 fixed issue with Kee: at least for 1.8.0 and 2.5.6 versions. If it was connected to blocked port, then in the future it is possible to troubleshoot it by changing default KeePassRPC port 12546 to some different one.

**Comment by DeepMac** [comment]
@MrAlex94 details on the malware issue? Was it specific to Kee and RPC or more generic?

**Comment by DeepMac** [comment]
Confirming that 2021.04.2 fixes the RPC issue I experienced with 2021.04.01 and Kee 2.5.6, using KeePass 2.4.7 x64 on a Win10 system. Thanks!

**Comment by MrAlex94** [comment]
Nothing Waterfox specific. Mozilla keeps a list of ports to block; they add new ones when they find malware in the wild using them.

**Comment by DeepMac** [comment]
Thanks. I'm curious if the info here https://www.ryadel.com/en/firefox-this-address-is-restricted-override-fix-port/
would allow me to bypass that with the .01 update, may test and report later.
