### ISSUE TITLE
Waterfox classic 2021.4 doesnt install in a new installation of Win7 x64 with UAC disabled

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2065]
I did the installation of win7 and had UAC disabled because it's bad, i couldnt install waterfox because of this, only when i enabled it i was able to install it without a problem.

**Comment by MrAlex94** [comment]
It requires UAC elevation to install, since it's adding registry entries and being installed into program files usually. Use the portable edition if you don't want UAC.
