### ISSUE TITLE
Waterfox classic 2021.04.1 "Automatic proxy configuration URL" not working

### ISSUE THREAD

**Issue by allenz8512** [MrAlex94/Waterfox#2067]
OS：Windows 10 21H1
Version：Waterfox classic 2021.04.1

Waterfox wouldn't follow proxy when "Automatic proxy configuration URL" sets（use PAC script），and does not follow script in system proxy settings when "Use system proxy settings" selected.

The issue is not exists when fallback to old version.

**Comment by reallyuniquename** [comment]
Have you tried 2021.04.2?

**Comment by allenz8512** [comment]
> Have you tried 2021.04.2?

Seems it's fixed in 2021.04.2，thank you
