### ISSUE TITLE
osx64 Waterfox Classic 2021.04.2 Download 404 Error

### ISSUE THREAD

**Issue by colvacdir** [MrAlex94/Waterfox#2070]
The setup file is in the 'update' folder for osx64 version, therefore you get a 404 error when trying to download. Should be in the 'installer' folder. Just fyi. Cheers!

**Comment by UInt2048** [comment]
The correct link is: https://cdn.waterfox.net/releases/osx64/installer/Waterfox%20Classic%202021.04.1%20Setup.dmg

**Comment by colvacdir** [comment]
> The correct working link that properly installs 2021.04.2 is: https://cdn.waterfox.net/releases/osx64/installer/Waterfox%20Classic%202021.04.1%20Setup.dmg

Actually, that is the link for macOS Waterfox Classic version _**2021.04.1**_.

The link for macOS Waterfox Classic version _**2021.04.2**_ on [this page](https://www.waterfox.net/download/) is broken because the file is in the wrong folder, as I mentioned above. It simply needs to be put into the correct folder.

**Comment by MrAlex94** [comment]
Thanks for catching that. Has been fixed.
