### ISSUE TITLE
Waterfox Classic 2021.4.2 Google Workspaces Issues

### ISSUE THREAD

**Issue by miguelramosv78** [MrAlex94/Waterfox#2071]
Key functionality in Google Workspaces is no longer working:

- Google Drive: Right click on file, Sharing - sharing box does not load
- Sharing in Google Docs (as above)
- Google docs: Version history and document details now greyed out

**Comment by MrAlex94** [comment]
Looks like Google pushed out some incompatible updates (can reproduce). Not sure we can fix anything on our side unless someone submits patches for the HTML feature required.
