### ISSUE TITLE
Add support for Tor

### ISSUE THREAD

**Issue by Limits0x** [MrAlex94/Waterfox#2073]
# Description
I want to use Tor with Waterfox. I know I can use the Tor Browser. But, I really like the ui of Waterfox. My present setup is starting up Tor from the command line and connecting to it through Waterfox. The problem with this setup is that I cannot create a new identity or circuit and the circuit does not seem to sync accross websites.
# Suggestion
It would be amazing if a toggle could be added to Waterfox to connect to Tor and options to create a new Identity or Circuit.

**Comment by MrAlex94** [comment]
There is rudimentary support for onion addresses I believe - but actual support for the Tor protocol is not in the scope for Waterfox, and it's quite critical to use Tor Browser with it as it contains features to compliment proper anonymisation.

**Comment by Limits0x** [comment]
Thanks for replying. I'll use tor browser for browsing tor. And use waterfox for regular browsing.
