### ISSUE TITLE
2021.04.02 Still breaks things like Plex server

### ISSUE THREAD

**Issue by warpfactor999** [MrAlex94/Waterfox#2074]
When you go to run the Plex server, Waterfox reports it is trying to load software to play audio or video. Plex worked great prior to version 2021.04.01. Now the port isn't blocked but the application still is.
Please fix, and get it right this time? After 10 years with Waterfox I'm about ready to shift over to Brave.

**Comment by vanowm** [comment]
Are you trying connect to plex server remotely? I have no issues running on local network using local IP and via app.plex.tv
