### ISSUE TITLE
[Classic] Javascript: invalid regular expression flag ÿ

### ISSUE THREAD

**Issue by BallM4788** [MrAlex94/Waterfox#2075]
**OS:** Windows 7 Professional (64-bit), Service Pack 1
**Waterfox version:** Classic, 2021.04.2
### Summary
Some regex evaluations fail with the console message "`invalid regular expression flag ÿ`". This is similar to [Firefox Bug 1452619](https://bugzilla.mozilla.org/show_bug.cgi?id=1452619), but not identical. Most notably present in usages of `eval()`, though may possibly occur under different circumstances as well.
### Notes
 * The issue disappeared in 2021.04.1, but reappeared in 2021.04.2.
 * Issue appears even in fresh profiles.
 * Does not occur when the regex pattern and flags are enclosed in parentheses (ex: `eval( "("+pattern+")" );`).
 * Does not otherwise seem to be affected by the content or flags of the pattern itself.

### Example of what happens: [Link to example (runs locally)](https://jsfiddle.net/kwyhfm4v/)
![waterfox_2021-04-23_17-00-53](https://user-images.githubusercontent.com/3979617/116465555-ffe59800-a832-11eb-9c2f-a3131c4b768b.png)
### Example's expected behavior:
![waterfox_2021-04-25_13-19-18](https://user-images.githubusercontent.com/3979617/116465641-1c81d000-a833-11eb-82e7-908708fdb4ce.png)

**Comment by BallM4788** [comment]
It is possible that this could be related to #1807, which as of now does not seem to be resolved.

**Comment by reallyuniquename** [comment]
My guess is it's https://github.com/MrAlex94/Waterfox/issues/1956#issuecomment-784894669.

Anyway this is something to look at. Pinging @MrAlex94, this time it should be easier to reproduce.

**Comment by hawkeye116477** [comment]
Well, that works fine on Linux, so reallyuniquename probably is right.

**Comment by Squall-Leonhart** [comment]
This has nothing to do with #1807, 21.04.2 is again using ucrtbase 10.17134.12, where as 21.04.1 was using 10.10240.0.

Were these releases built by 2 different people?

utilise this updated 10.17134.191 dll, which includes the fix for EOL expression parsing
[ucrtbase.zip](https://github.com/MrAlex94/Waterfox/files/6367293/ucrtbase.zip) (drop and replace onto the existing waterfox copy of the dll)

That Firefox bug is 100% whats going on here.

@hawkeye116477 this backport could be taken into WF Classic to fix it without changing out the dll / compiler.
https://bugzilla.mozilla.org/attachment.cgi?id=8968490&action=diff

> 
> When we're parsing the regexp flags here: https://searchfox.org/mozilla-central/rev/7ccb618f45a1398e31a086a009f87c8fd3a790b6/js/src/frontend/TokenStream.cpp#2002
> 
> After the 'g' we send EOF through ucrtbase!isalpha (via JS7_ISLET: https://searchfox.org/mozilla-central/rev/7ccb618f45a1398e31a086a009f87c8fd3a790b6/js/src/util/Text.h#39)
> 
> Under 17133.1, ucrtbase!isalpha(-1) returns true (at least in English locale), and it throws off our parser's logic. Under 16299, ucrtbase!isalpha(-1) returned false.

**Comment by BallM4788** [comment]
@Squall-Leonhart That dll does seem to have fixed the problem. I'll keep the issue open because, as you said, a more foolproof fix should be implemented.

**Comment by MrAlex94** [comment]
It's related to build system - we've updated it, so next release will be the test.

**Comment by Squall-Leonhart** [comment]
This has been fixed both by updating the toolchain, as well as the implementation of ASCIIAlpha in 6e7af44c936f803ccf10fb727e4ed5651249d622

Either way should have done it, but now theres no chance of a recurrence xD
