### ISSUE TITLE
[Classic] uBlock Origin unable to inject scripts into facebook.com

### ISSUE THREAD

**Issue by zakius** [MrAlex94/Waterfox#2076]
Using mozregression I pinpointed first build that works to be 67a1, if change related to that could be backported it would be great

**Comment by Felipefpl** [comment]
if you are using the latest dev version of ublock this is a problem of ublock reported in the commits section.

**Comment by zakius** [comment]
Luckily it was possible to work around this issue in uBlock Origin but it may potentially cause other things to break as there is some difference in handling the script by the engine

https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=4e98200ee53017fe8cd037abf948ebaabd33f229&tochange=b482c6618d72ac38a9a82fbccf425e0a7f8b6129

this is the smallest list of changes I was able to gather using mozregression but nothing obviously related seems to be there

**Comment by hawkeye116477** [comment]
Well, gorhill declared that's compatible with FF 57, but as you mentioned it's not working correctly even with FF 57, so maybe this should be reported as a bug to him.
