### ISSUE TITLE
Wordpress Elementor Plugin not working in Waterfox G3

### ISSUE THREAD

**Issue by slumbergod** [MrAlex94/Waterfox#2078]
I spent the last week wondering why no one else was reporting this issue about the visual text editor not working for the Elementor WordPress plugin. I stopped using WordPress in Waterfox Classic because it was not working properly so I installed G3 to prepare myself for the day when Waterfox Classic was no longer working with enough of my regularly visited websites.

G3 was working fine with WordPress and Elementor until the recent release of Elementor 3.2.0, 3.2.1, and 3.2.2

Now I realise that it is Waterfox and not a bug in Elementor or WordPress. Everything works correctly in the latest Firefox.

So just a heads-up for anyone else scratching their head wondering why WordPress isn't working properly in Waterfox G3.

**Comment by MrAlex94** [comment]
Well from the looks of it they've introduced features not supported in Firefox ESR 78 (which Waterfox is based on, for now). You'll have to wait for the next major Waterfox revision.

If it works on Firefox ESR - reopen.
