### ISSUE TITLE
Vox.com ad display issues

### ISSUE THREAD

**Issue by newsjunkie247** [MrAlex94/Waterfox#2079]
The ad boxes don't appear on Vox.com articles like: https://www.vox.com/2021/4/30/22412137/biden-congress-speech-100-days-fdr-new-deal in Classic. Among the errors in the console is: "Error: Cannot set user agent for iframe with location different to this page"

**Comment by hawkeye116477** [comment]
So it's good, adblocker isn't needed :smile:
