### ISSUE TITLE
[G3.2.1 64-bit, hawkeye116477] Crashing on amazon with javascript enabled

### ISSUE THREAD

**Issue by TheBeardOfTruth** [MrAlex94/Waterfox#2080]
Arch linux, 5.11.13

Problem:
navigate to Amazon (tested on .se, .com, .de, .fr, & .co.uk), ensure javascript is turned on.
It should crash when you **use the search feature** (that is to say it should crash on any amazon.com/s?k=search&... url)

This will also cause a cascade crash of other lodaed pages (e.g youtube, certain email clients) though I've not noticed any patterns on what sites crash from it, and they only crash when amazon crashes.

All of these tests have been done on amazon.se, I have not verified that amazon.com/.de/.fr etc crash for every permutation listed, only with having all addons on and all off.  (one critical difference might be that amazon.com defaults to list view for me and amazon.se has grid view, I don't see an obvious option for changing this so I can't verify if this is related)

Reproducible in safe mode: 
No, but after extensive testing (by turning every addon off and trying to enable any addon) plenty of well supported addons cause the crash.

+ Decentraleyes
       happens even when the site is whitelisted, i.e when decentraleyes does not inject anything. It being loaded is sufficient to trigger the crash.

+ Ublock origin
     happens even when amazon is whitelisted
     
+ Disconnect
    and you guessed the pattern, even when amazon is whitelisted

+ HTTPS Everywhere
    pattern holds, even when HTTPS everywhere is off, it crashes just from it being loaded.

+ NoScript
   obviously doesn't crash when we blacklist amazon from using javascript, but that goes without saying
   
+ Privacy Badger
   as expected, the pattern holds; whitelist amazon and we still crash.

Reproducible under a new profile: 
Yes, as soon as my addons sync back in it crashes. It does not crash if I don't sync, sync might pull some about:config settings in but even if it doesn't, having to re-apply all my settings would take hours or days and I don't see an obvious way to automate this.

Expected behaviour:
Not crashing.

**Comment by MrAlex94** [comment]
Unfortunately can't help with hawkeyes repo - but I've got amazon working on all my test systems (macOS, Ubuntu 16, Windows 10 21H1). Sorry can't be of more help.

**Comment by hawkeye116477** [comment]
Well, I installed every addon mentioned and can't reproduce that too. So maybe it's rather something from `about:config`.
In `about:support` you should have modified settings mentioned.

**Comment by TheBeardOfTruth** [comment]
Hmm, it only mentions modified important settings, I took the liberty of making a paste for them https://pastebin.com/SVnUVpzL

Though most of these seem entirely innocuous, things like locale settings and whether I enabled ffmpeg vaapi support or not.
