### ISSUE TITLE
[Classic] Fix the history and bookmarks bug

### ISSUE THREAD

**Issue by Midou36O** [MrAlex94/Waterfox#2082]
### **Detailled explanation of the bug:**
The history and bookmarks (favorite or star icon) doesn't save at all, for starring a page it just does an animation and nothing more.

### **To Reproduce the behavior:**
 **A. Bookmarks bug**

   1. Go to a Website
   2. Click on The star button
   3. Notice how the star animation gets triggered
   4. Open the favorites page
   5. Nothing in there

 **B. History bug**

   1. Go to a website and browse for a while
   2. press CTRL + H or open history
   3. Nothing in there too.

### Expected behavior:
Starring saves the page in the bookmark folder, and history gets logged.

### Screenshots:
**History bug:**

![image](https://user-images.githubusercontent.com/45198486/117335050-3d2cd400-ae8a-11eb-9ac0-c1590e5c2e85.png)

**Starring bug:**

![image](https://user-images.githubusercontent.com/45198486/117335124-546bc180-ae8a-11eb-997b-fddcf43324c7.png)

(based on palemoon but the contents should have been similar)

**Expected History content:**

![image](https://user-images.githubusercontent.com/45198486/117335169-5f265680-ae8a-11eb-8b28-49a395ea5244.png)

**Expected Bookmarks (Star) content:**

![image](https://user-images.githubusercontent.com/45198486/117335186-6483a100-ae8a-11eb-8c3b-9029288c475c.png)

### Desktop :

   OS: Windows 7 Ultimate SP1
   Version:

![image](https://user-images.githubusercontent.com/45198486/117335230-72392680-ae8a-11eb-980d-78cabdece582.png)

**Comment by reallyuniquename** [comment]
Is your profile directory writable?

**Comment by Midou36O** [comment]
![image](https://user-images.githubusercontent.com/45198486/117538366-5d2cd680-aff5-11eb-96f7-2be67e8242fd.png)
![image](https://user-images.githubusercontent.com/45198486/117538418-9d8c5480-aff5-11eb-92a3-bc2ed580ccc4.png)

Yes it is writable
(note: SandBoxing the app isn't the  issue, i already tried installing it without sandboxie and it didn't work too.)

**Comment by reallyuniquename** [comment]
I doubt it's a Waterfox issue, such critical bug would have been already reported. Probably something wrong with your environment. Anything in browser console?

**Comment by Midou36O** [comment]
Bookmarking shows this up:
![image](https://user-images.githubusercontent.com/45198486/117665235-25a76100-b192-11eb-8f91-15ca78cd7f3c.png)

History doesn't show up in the console.

**Comment by reallyuniquename** [comment]
Can you reproduce this on fresh clean profile without sandbox on up to date Windows (as in updated in 2021)?

**Comment by Midou36O** [comment]
Err... i don't think windows 7 gets security updates anymore, also, the same error appear when not using sandbox.
Hope this will be useful.

**Comment by reallyuniquename** [comment]
Have you tried launching Waterfox with clean and fresh profile? Does the issue still persist?

>i don't think windows 7 gets security updates anymore

It does. Waterfox has ongoing issues with outdated Windows setups like #2075.

**Comment by MrAlex94** [comment]
Have closed - unable to reproduce this.

**Comment by Squall-Leonhart** [comment]
I too cannot reproduce this across any of my 4 waterfox profiles.

I suspect this is due to a corrupt places.sqlite, you can try to preserve your session with steps here https://superuser.com/questions/111998/how-do-i-repair-a-corrupted-firefox-places-sqlite-database, or if you don't keep the same tabs across sesssions, just delete the file and the next startup will restore bookmarks from the backup file.
