### ISSUE TITLE
Base64 PNG image not calculated or displayed correctly

### ISSUE THREAD

**Issue by SchitzelKraft** [MrAlex94/Waterfox#2084]
This strange bug popped up when I wanted to do some banking. 

1) Go to this banking site
https://www.snsbank.nl/online/web/mijnsns/inloggen/#/inloggen
2) Select QR-code
3) See generated base64 PNG image. It should look like a QR-code but for me in doesn't.

another clear example is inserting an image in Google Docs.

Found in G3.2.1 (64-bit) GECKO 78.10.0 on MacOS 11.3 (20E232)

Tried safe mode, but got the same results

Checked in recent versions of
- Chrome
- Opera
- Safari (also tech preview)
- Firefox (also dev edition) 
It all seems to work here.

Example of wrongly generated image.
![image](https://user-images.githubusercontent.com/56701469/117995017-81a7ec00-b330-11eb-9e8c-7cd34650a5c9.png)

HTML output in Waterfox. Copy pasting this in any browser shows the broken image
`<img data-bb="qrCode" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAM0AAADNCAYAAAAbvPRpAAAD00lEQVR4nO3Zoa0QCBAA0TVUAQIMFVABRxW0QAIK0ARxBVAAtWBJfjhzpZCQYNDIUZtNnn5m/Mz/r36/f/zmny/fn3z798Wzh+efHz4+ff3rw6Ofb398/e/dy0+c8799tgM4v+azHcD5NZ/tAM6v+WwHcH7NZzuA82s+2wGcX/PZDuD8ms92AOfXfLYDOL/mPg3n0X0azqP7NJxH92k4j+7TcB7dp+E8uk/DefTZDuD8mvs0nEf3aTiP7tNwHt2n4Ty6T8N5dJ+G8+g+DefRZzuA82vu03Ae3afhPLpPw3l0n4bz6D4N59F9Gs6j+zScR5/tAM6vuU/DeXSfhvPoPg3n0X0azqP7NJxH92k4j+7TcB59tgM4v+Y+DefRfRrOo/s0nEf3aTiP7tNwHt2n4Ty6T8N59NkO4Pya+zScR/dpOI/u03Ae3afhPLpPw3l0n4bz6D4N59FnO4Dza+7TcB7dp+E8uk/DeXSfhvPoPg3n0X0azqP7NJxHn+0Azq+5T8N5dJ+G8+g+DefRfRrOo/s0nEf3aTiP7tNwHn22Azi/5j4N59F9Gs6j+zScR/dpOI/u03Ae3afhPLpPw3n02Q7g/Jr7NJxH92k4j+7TcB7dp+E8uk/DeXSfhvPoPg3n0Wc7gPNr7tNwHt2n4Ty6T8N5dJ+G8+g+DefRfRrOo/s0nEef7QDOr7lPw3l0n4bz6D4N59F9Gs6j+zScR/dpOI/u03AefbYDOL/mPg3n0X0azqP7NJxH92k4j+7TcB7dp+E8uk/DefTZDuD8mvs0nEf3aTiP7tNwHt2n4Ty6T8N5dJ+G8+g+DefRZzuA82vu03Ae3afhPLpPw3l0n4bz6D4N59F9Gs6j+zScR5/tAM6vuU/DeXSfhvPoPg3n0X0azqP7NJxH92k4j+7TcB59tgM4v+Y+DefRfRrOo/s0nEf3aTiP7tNwHt2n4Ty6T8N59NkO4Pya+zScR/dpOI/u03Ae3afhPLpPw3l0n4bz6D4N59FnO4Dza+7TcB7dp+E8uk/DeXSfhvPoPg3n0X0azqP7NJxHn+0Azq+5T8N5dJ+G8+g+DefRfRrOo/s0nEf3aTiP7tNwHn22Azi/5j4N59F9Gs6j+zScR/dpOI/u03Ae3afhPLpPw3n02Q7g/Jr7NJxH92k4j+7TcB7dp+E8uk/DeXSfhvPoPg3n0Wc7gPNr7tNwHt2n4Ty6T8N5dJ+G8+g+DefRfRrOo/s0nEef7QDOr7lPw3l0n4bz6D4N59F9Gs6j+zScR/dpOI/u03AefbYDOL/mPg3n0X0azqP7NJxH/wOOVP3/+jQcFQAAAABJRU5ErkJggg==" aria-label="QR Code">`

**Comment by MrAlex94** [comment]
How odd - I can reproduce this. I wonder if it's a macOS issue? Will try and repro on Windows soon.

**Comment by SchitzelKraft** [comment]
I will download a Windows 10 Disc Image and try it out.

**Comment by SchitzelKraft** [comment]
Works on my old Windows laptop.
![image](https://user-images.githubusercontent.com/56701469/119876646-a0ed6e80-bf17-11eb-840a-c52ae8f79b4b.png)

**Comment by SchitzelKraft** [comment]
To be more specific about Google Docs.

1) Go to spreadsheets https://docs.google.com/spreadsheets
2) Insert>image>image in cell

Resizing seems to change/fix it.

https://user-images.githubusercontent.com/56701469/119893279-af915100-bf2a-11eb-9f73-c64131d5396f.mov

**Comment by noplanman** [comment]
I've had this issue for a very long time: https://github.com/wallabag/wallabag/issues/4813

Seems to be a Waterfox / Firefox issue, as it's ok in other browsers.

**Comment by MrAlex94** [comment]
Ah I see - it's also a Firefox issue. Unfortunately a fix will have to land upstream. Is a bug filed with Mozilla?

**Comment by SchitzelKraft** [comment]
I've seen it work in Firefox (86 & 88).
<img width="914" alt="Screenshot 2021-06-01 at 14 18 46" src="https://user-images.githubusercontent.com/56701469/120322086-8c242880-c2d3-11eb-9e1e-d0137f6d1a8b.png">
<img width="821" alt="Screenshot 2021-06-01 at 14 17 54" src="https://user-images.githubusercontent.com/56701469/120322092-8dedec00-c2d3-11eb-8ac8-2265c37da27b.png">

**Comment by noplanman** [comment]
@SchitzelKraft Could you post the base64 image data of the QR Code that works for you in Firefox?

As you mention in your first post, it's like the image data itself is broken, rendering the image incorrectly on any other browser.

**Comment by SchitzelKraft** [comment]
A base64 QR code I got from snsbank.nl in Firefox. This one looked right (as they all do, in my situation).

`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAM0AAADNCAYAAAAbvPRpAAAIrElEQVR4nO2YQXIcMQwD/f9PJxcfPSkx4ALQuFE1N1EgKPYe9uvr6+tPy/eTtu/bViqHY/aKb6rW9MUbsC7btlI5HLNXfFO1pi/egHXZtpXK4Zi94puqNX3xBqzLtq1UDsfsFd9UremLN2Bdtm2lcjhmr/imak1f97Lh6/nhcCy+oqZ3A5oLfIGm692A5gJfoOl6N6C5wBdout4NaC7wBZqudzuGZvvhHOcc2VLzS820vRfTu/U04xjWdjag6eoFaD4wrO1sQNPVC9B8YFjb2YCmqxeg+cCwtrMBTVcvQPOBc45sim5cIiXbjXmB5gPZFN24REq2G/MCzQeyKbpxiZRsN+YFmg9kU3TjEinZbswLNB/IpujGJVKy3Zj3SmiaFvoDD7KaI9XzdramPQWagYAGaIBmKKABGqAZCmiABmiGAhqgGUGzLccAt2sdvTT9IGzXbi+vQ0Aj1jp6ARqgGTXTXuvoBWiAZtRMe62jF6ABmlEz7bWOXoDmUmhSnzIszv2+c8Ev3kB8+Jy781zwizcQHz7n7jwX/OINxIfPuTvPBb94A/Hhc+7Oc7Hvxw7LtT1oxWPbd9vjLXmbdGUSoAGapK5MAjRAk9SVSYAGaJK6MgnQAE1SX8rwtwfddO601rGo7RCmdmM7x+C+7sEADdC0vRHQlD2I4qsIaIAGaIYCGqABmqGARoRmO8i22mHdrk3B2j6X1EyBBmiABmh2at/ywE3za6oFGqABGuNMgQZogGb6HU/L0OD2AB3aXtSmxVJqlTfarl3fyeNuUg0CzfG5plqgSTYINMfnmmqBJtkg0Byfa6oFmmSDQHN8rqn21dC0L+D2sim1b1m21EKf3nfBHgAN0ADNpBZoBrVAAzTf54AGaIBmUgs0g1qgAZrvc59fGLHB6qV8i0dT7QVgAo3S81s8mmqBZhBk+9xbFhpogObxvu1zb1looAGax/u2z71loYHmF0KTGvR2zykPZVZN/W3ncOjBG2i27wMaTUDzUKs0rfQHNECz0AvQbN8HNJqA5qFWaVrpD2iARu7FYXLcjGGJHHIAt92fQymo13+ItgbyL5PjZoAGaICmL7BDQHPuCzQPJsfNAA3QAE1fYIeA5tz3SmhSD6c0fXrOAZzjgR0Qbp871QcW2jEDoNn2VfoDGqCRBTRAM6kFmj9AAzSzWqD5AzRAM6uNQaM0qARW5Bj+tlIL3Z6taScfvp4GFQEN0ADNUEADNEAzFNAADdAMBTRAE4XGMVSx6eoHcfwgbH+OHEpex7lBf0DjqE3NpSmHktdxbtAf0DhqU3NpyqHkdZwb9Ac0jtrUXJpyKHkd5wb9AY2jNjWXphxKXse54/5OTbbhanrM1FKmsikzSCm1az/ep5gADdC4BDRiEKDRsikzSAloxCBAo2VTZpAS0IhBgEbLpswgpXpoHMaKr8PjxmVz/BA5fmAcgEh5t5vZFtDkcigeQDNoZltAk8uheADNoJltAU0uh+IBNINmtgU0uRyKx6uhecugHUPdzqvMVMnb5Hta27RrQAM0Ud/T2qZdAxqgifqe1jbtGtAATdT3tLZp14AGaKK+p7VNu7b+t05T4FOP9hk49NvgUu4DGqAZ+QIN0ADN0BdogAZohr5AAzRAM/QFmiA0scDLvkovp7XbHg41/Tht7wHQAM1HBDTBIO2+Si+ntdseDgFNMEi7r9LLae22h0NAEwzS7qv0clq77eHQq6FJGZ8OwSHHoqZgdZzb9mia6YMv0LzlgYEGaIDGmEM5t+3RNNMHX6B5ywMDDdAAjTGHcm7bo2mmP/oeHzQ8SAq4pl4Upd7ot80KaMp6UQQ05wKagW97L4qA5lxAM/Bt70UR0JwLaAa+7b0oAppzrUOzPaztwWw/3LaHYykdy+YAxLFD6z0r4YAGaIBmGA5ogAZohuGABmiAZhgOaIDmV0Kz/cBKbWqAjvscvo5a5b4mX7EWaIAGaIDmHwKaruVN+QIN0AAN0ADN//g6apX7mnwt0KTCDYLULOW2R+oHRpHjjRRfsefu5RDDAQ3QAM0wHNAADdAMwwEN0ADNMBzQAM3+XqUC33if41xTtlTt+pJvg5lq5sb7HOeasqVqgebJ+ML7HOeasqVqgebJ+ML7HOeasqVqgebJ+ML7HOeasqVqXwPN8YUXLq9j0Kdqn31sUZt+ONYvBBpJ7bMHGqABmoX7gEa9EGgktc8eaIAGaBbu+3XQpBa66TFTn2NW2zM9rXX0EpwV0AAN0Az7AxqgAZphf0ADNEAz7A9ogAZoRv1tBzmt3fZQcrT3fKq3zKodQqC5oOdTvWVWQPNQu+2h5Gjv+VRvmRXQPNRueyg52ns+1VtmBTQPtdseSo72nk/1llldCY1jCI6lbHqQ09qUhyOvcl/q+7Hn0yCOwNuPBDRAAzRAAzRAAzRAkwcDaJZqTwU0QFMnBzSppUxlU3I4IEzddzxDqUODgAZoXPcBzaAWaIDmqRZogAZohrVAAzRAM6x9+HYXa/sxlcGkenHAsF2r5FVqlWxBjzwsQDO/b7tWyavUAg3QAM2wFmiABmiGtUADNEAzrH0NNA45HtORLbXQ7bXb57b7O619+IBm29fRX3st0HxAQAM0ai/b9wEN0ERrgeYDAhqgUXvZvm8dmsGFHx+WA5AmCLfnvO2RyhvcP6BJeSi+QAM0QDP0BRqgAZqhL9AADdAMfYEGaGxwbdc2zc+x+Nv9OTw+cF9Pg8q5VG3T/IAGaEbnUrVN8wMaoBmdS9U2zQ9ogGZ0LlXbND+gAZqor0OOBVR8lfsccw7uWvfyAg3QTHy3zwHNwNchoNEENGW+DgGNJqAp83UIaDTVQ7Ot1JKnFlXpL/UjkZp9qnZwDmhOzwEN0HyfA5rTc0ADNN/ngOb0HNAAzfc5oDk9BzRA833u/x9p+3MMK5VDUdMMHL6OuSj3AQ3QAM3wPqABGqAZ3gc0QAM0w/uABmiAZnjfXzvm9JzuPhu9AAAAAElFTkSuQmCC`

**Comment by SchitzelKraft** [comment]
Here the bug can be reproduced without clear use of base64 conversion (could be a step in the upload process though). 
https://uppy.io/examples/dashboard/

**Comment by noplanman** [comment]
So it seems to be some weird browser conversion issue 😕 

I can confirm the data URI you posted works for me in all browsers.

@SchitzelKraft Thanks for providing the link. Hope that can help anybody working on this issue to find a fix.

**Comment by SchitzelKraft** [comment]
https://user-images.githubusercontent.com/56701469/120374581-3ec2ae00-c309-11eb-88ab-1c3515f3614b.mp4

**Comment by Squall-Leonhart** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1342437

**Comment by SchitzelKraft** [comment]
Finally found the solution!


<img width="414" alt="Screenshot 2021-10-08 at 11 25 24" src="https://user-images.githubusercontent.com/56701469/136533341-7712fd97-bc22-482e-b2ca-2775a305e770.png">

Waterfox/Firefox needs permission. The dialog is hidden in the address bar.

**Comment by noplanman** [comment]
@SchitzelKraft Cool, thanks for the update!

The other fix mentioned else where, is to disable `privacy.resistFingerprinting` in `about:config`, but really your solution here is better 👍 

I always thought that pop-up comes automatically if the browser window wants / needs the permission, but clearly not.
