### ISSUE TITLE
[classic] [linux] 2021.03 build failure : "error: could not compile `syntex_syntax`"

### ISSUE THREAD

**Issue by clasatas** [MrAlex94/Waterfox#2087]
linux, rust 1.52.1
 "error: could not compile `syntex_syntax`"

   Compiling syntex_syntax v0.58.1
error[E0423]: expected function, tuple struct or tuple variant, found struct `ast::Name`
   --> /home/portage/tmp/portage/www-client/waterfox-2021.03/work/Waterfox-2021.03-classic/third_party/rust/syntex_syntax/src/symbol.rs:146:27
    |
146 |                       name: ast::Name($index),
    |                             ^^^^^^^^^
...
165 | / declare_keywords! {
166 | |     // Invalid identifier
167 | |     (0,  Invalid,        "")
168 | |
...   |
231 | |     (56, CrateRoot, "{{root}}")
232 | | }
    | |_- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by hawkeye116477** [comment]
I can't reproduce that. What's in your mozconfig?

**Comment by clasatas** [comment]
The same error: https://github.com/rust-lang/rust/issues/68729
My .mozconfig:

ac_add_options --enable-application=browser
ac_add_options --enable-optimize=-O2 # Workaround known breakage
ac_add_options --with-default-mozilla-five-home=/usr/lib64/waterfox # 
ac_add_options --disable-updater # disable_update_strip
ac_add_options --disable-strip # disable_update_strip
ac_add_options --disable-install-strip # disable_update_strip
ac_add_options --with-system-zlib # system_libs
ac_add_options --with-system-bz2 # system_libs
ac_add_options --enable-release # Enable by Gentoo
ac_add_options --disable-gold # -gold
ac_add_options --enable-pie # enabled by Gentoo
ac_add_options --disable-debug # -debug
ac_add_options --disable-tests # -debug
ac_add_options --disable-debug-symbols # disabled by Gentoo
ac_add_options --enable-startup-notification # +startup-notification
ac_add_options --enable-necko-wifi # +wifi
ac_add_options --enable-dbus # +dbus
ac_add_options --with-system-nspr # 
ac_add_options --with-nspr-prefix=/usr # 
ac_add_options --with-system-nss # 
ac_add_options --with-nss-prefix=/usr # 
ac_add_options --x-includes=/usr/include # 
ac_add_options --x-libraries=/usr/lib64 # 
ac_add_options --with-system-libevent=/usr # 
ac_add_options --prefix=/usr # 
ac_add_options --libdir=/usr/lib64 # 
ac_add_options --disable-crashreporter # 
ac_add_options --with-system-png # Gentoo default
ac_add_options --enable-system-ffi # 
ac_add_options --disable-gconf # 
ac_add_options --with-intl-api # 
ac_add_options --enable-skia # 
ac_add_options --enable-default-toolkit=cairo-gtk3 # 
ac_add_options --target=x86_64-pc-linux-gnu # 
ac_add_options --host=x86_64-pc-linux-gnu # 
ac_add_options --disable-pulseaudio # -pulseaudio
ac_add_options --enable-alsa # -pulseaudio
ac_add_options --enable-content-sandbox # Sandbox
ac_add_options --enable-system-sqlite # +system-sqlite
ac_add_options --with-system-jpeg # +system-jpeg
ac_add_options --with-system-icu # +system-icu
ac_add_options --with-system-libvpx # +system-libvpx
ac_add_options --with-system-harfbuzz # +system-harfbuzz
ac_add_options --with-system-graphite2 # +system-harfbuzz
ac_add_options --disable-jack # -jack
ac_add_options --with-app-name=waterfox # 
ac_add_options --with-app-basename=waterfox # 
ac_add_options --with-branding=browser/branding/unofficial # 
ac_add_options --with-distribution-id=org.waterfoxproject # 
ac_add_options --disable-tests # 
ac_add_options --disable-debug # 
ac_add_options --disable-rust-debug # 
ac_add_options --disable-debug-symbols # 
ac_add_options --disable-jprof # 
ac_add_options --disable-dmd # 
ac_add_options --disable-instruments # 
ac_add_options --disable-callgrind # 
ac_add_options --disable-vtune # 
ac_add_options --disable-gc-trace # 
ac_add_options --disable-perf # 
ac_add_options --disable-ipdl-tests # 
ac_add_options --disable-gtest-in-build # 
ac_add_options --disable-accessibility # 
ac_add_options --disable-b2g-bt # 
ac_add_options --disable-b2g-camera # 
ac_add_options --disable-b2g-ril # 
ac_add_options --disable-clang-plugin # 
ac_add_options --disable-crashreporter # 
ac_add_options --disable-debug-js-modules # 
ac_add_options --disable-faststripe # 
ac_add_options --disable-gamepad # 
ac_add_options --disable-gconf # 
ac_add_options --enable-install-strip # 
ac_add_options --disable-libproxy # 
ac_add_options --disable-ios-target # 
ac_add_options --disable-maintenance-service # 
ac_add_options --disable-mozril-geoloc # 
ac_add_options --disable-necko-wifi # 
ac_add_options --disable-parental-controls # 
ac_add_options --disable-safe-browsing # 
ac_add_options --disable-signmar # 
ac_add_options --enable-strip # 
ac_add_options --disable-trace-logging # 
ac_add_options --disable-updater # 
ac_add_options --disable-url-classifier # 
ac_add_options --disable-valgrind # 
ac_add_options --disable-verify-mar # 
ac_add_options --without-debug-label # 
ac_add_options --with-pthreads # 
ac_add_options --enable-webrender # 
ac_add_options --enable-stylo # 
ac_add_options --enable-rust-simd # 
ac_add_options --enable-elf-hack # 
ac_add_options --disable-dump-painting # 
ac_add_options --disable-logrefcnt # 
ac_add_options --disable-reflow-perf # 
ac_add_options --disable-ccache # 
mk_add_options MOZ_OBJDIR=/home/portage/tmp/portage/www-client/waterfox-2021.04.2/work/Waterfox-2021.04.2/wf
mk_add_options XARGS=/usr/bin/xargs
ac_add_options --enable-extensions=default

**Comment by hawkeye116477** [comment]
As I suspected, you need to disable stylo (it's broken, may need many fixes, even it was problematic in older rust versions, browser was crashing on some websites, there was the lack of volunteers to fix that).

**Comment by clasatas** [comment]
Yes, disabling stylo helped, also had to disable webrender. Compiling moved on and now have tons of errors С++ ... :) Probably it is necessary to close issue and open a new one for the new bugs.
