### ISSUE TITLE
inforum.com stops responding

### ISSUE THREAD

**Issue by hockeymikey** [MrAlex94/Waterfox#2088]
To reproduce go to any page on https://www.inforum.com/. You should have it freeze up and get a message about a script not responding. Stop the script and then you're fine after but it happens for every page load on the site.

**Comment by MrAlex94** [comment]
I can reproduce on Classic - don't think we can do anything on our side, bar running the website with JavaScript disabled.

**Comment by hockeymikey** [comment]
Why, what's the cause of it you think?

**Comment by MrAlex94** [comment]
Unsupported HTML feature, if I'm not misunderstanding the error logs. Unfortunately most of them are not trivial to backport.

**Comment by hockeymikey** [comment]
What HTML features? Maybe I could bug their end too on it for better compatibility of browsers.
