### ISSUE TITLE
[Classic] Randomly freezes OS

### ISSUE THREAD

**Issue by hockeymikey** [MrAlex94/Waterfox#2089]
I am using Arch with the most up to date version of Waterfox Classic of writing (2021.04.1). Sometimes Waterfox causes the OS to totally freeze and I have to restart the computer. I know it only happens when it's open or I'm browsing on Waterfox. Not sure how I can help debug this but give me some ideas and I can see what I can get next time it happens.

**Comment by hockeymikey** [comment]
Happened consistently today. Only had two tabs open, a field and stream chat window with customer service and a google image tab. Very strange and annoying

**Comment by tcreek** [comment]
I think it could be related to hardware acceleration. Maybe try unchecking that option

**Comment by MrAlex94** [comment]
Yes, please try with e10s disable and hardware acceleration disabled (in General on about:preferences).

**Comment by hockeymikey** [comment]
Trying without session manager enabled. So far so good, but we will see.
