### ISSUE TITLE
Navigation on trakt.tv not working.

### ISSUE THREAD

**Issue by psonnosp** [MrAlex94/Waterfox#2095]
I'm on Classic 2021.04.2 (64-bit) and I don't know what happened but all of a sudden the URL isn't updating when navigating on trakt.tv. So if I'm at https://trakt.tv/shows/schitt-s-creek/seasons/2/episodes/12 and click to see the next episode https://trakt.tv/shows/schitt-s-creek/seasons/2/episodes/13 loads but the address field never changes so can't use the back button to go back to episode 12.

First tried with add-ons disabled but no change so tried a new profile but still the same.

It still work as normal in other browsers so have they made changes to the site that isn't following the standards or is it something that Waterfox just can't handle yet or a bug?

If it's the site that has f-ed up please help me with what exactly so I can report it to them so they hopefully can fix it.

Cheers!

**Comment by MrAlex94** [comment]
Unfortunately I can't reproduce - seems to work fine for me?

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/4728920/119861513-62ec4c80-bf0f-11eb-8932-fd7008ab3432.png">
