### ISSUE TITLE
Option to disable Ctrl + Q (Quit)

### ISSUE THREAD

**Issue by Bixilon** [MrAlex94/Waterfox#2097]
I am using Waterfox for everything and sometimes I accidentally press `Ctrl + Q` instead of `Ctrl + W`. Then Waterfox just quits, closing all tabs and more importantly all private tabs.

Some workarounds are here:
 - https://bugzilla.mozilla.org/show_bug.cgi?id=52821
 - https://superuser.com/questions/1318336/how-to-disable-ctrlq-shortcut-in-firefox-on-linux

But setting `browser.sessionstore.warnOnQuit` to `true` is simply no option to me, I don't want this extra confirmation when pressing `Alt + F4` or just the red closing button.

Btw. using Linux with KDE

Thanks

**Comment by MrAlex94** [comment]
The bug fix for 52821 will land in the next major release of Waterfox (not that far away now, latest around some time 2021-08-10).

**Comment by Bixilon** [comment]
Thanks!

**Comment by MrAlex94** [comment]
For reference, the commits are:
https://github.com/MrAlex94/Waterfox/commit/cb04d0eac4dccc8d494f22df732b4dde505c79d3
https://github.com/MrAlex94/Waterfox/commit/98018ecb9a6fd61e8c636f4f1c7bd9991f3380a1
