### ISSUE TITLE
Roboform

### ISSUE THREAD

**Issue by PiliJ** [MrAlex94/Waterfox#2099]
Hi,
I'm a user of Roboform and when i clic on the icon (not in the notification bar but in the menu of Waterfox), there is a function "All logins" which normally opens a window on the right containing all connections.
I have just noticed that this function is inoperative under the G 3.2.1 version whereas it works perfectly under Waterfox Classic 2021.04.2 (and Firefox in particular).
Version of the addon of Roboform is 9.1.7.3 (the last).
Thank you

**Comment by MrAlex94** [comment]
Unfortunately it's up to the developers of Roboform to support Waterfox.
