### ISSUE TITLE
Please integrate Private Tab + Addon Bar/Status Bar straight into Waterfox

### ISSUE THREAD

**Issue by DaiDucDaiUy** [MrAlex94/Waterfox#2100]
These 2 great addons have been removed from firefox store, so not many people know how to install them for FF Quantum/Waterfox
https://github.com/xiaoxiaoflood/firefox-scripts

**Comment by hawkeye116477** [comment]
Status Bar is already in Waterfox G3.

**Comment by MrAlex94** [comment]
Private tabs may make it to the next major version of Waterfox.

**Comment by DaiDucDaiUy** [comment]
> 
> 
> Status Bar is already in Waterfox G3.



Thanks. I see but Status bar in Waterfox G3 actually less flexible xiaoxiaofloor's script >"<
https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/chrome/status-bar.uc.js

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/d1c1162eea226566965fe66d265692e7fc2bf6be
