### ISSUE TITLE
Course videos on Udemy.com do not play (CODE:5 MEDIA_ERR_ENCRYPTED)

### ISSUE THREAD

**Issue by ChrisIdema** [MrAlex94/Waterfox#2101]
Course videos on Udemy.com do not play. They use DRM. Preview videos _do_ play, but not the videos of actual purchased course. And they both work in chrome and firefox. I disabled all plugins, tried safe mode, and cleared cache.

This is the video in question:  https://www.udemy.com/course/machinelearning/learn/lecture/6087182

The problem occurs on both waterfox and waterfox classic for windows 10.

In the console I see the following error:

```
VIDEOJS: ERROR: (CODE:5 MEDIA_ERR_ENCRYPTED) Request failed with status code 403 
{
  "code": 5,
  "message": "Request failed with status code 403",
  "responseStatus": 200,
  "responseURL": "https://www.udemy.com/assets/7236304/encrypted-files/out/v1/c5b4051cfb20411db4edc79951694400/06c8dc12da2745f1b0b4e7c2c032dfef/842d4b8e2e014fbbb87c640ddc89d036/index.mpd?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjIxMzI4MTYsInBhdGgiOiJvdXQvdjEvYzViNDA1MWNmYjIwNDExZGI0ZWRjNzk5NTE2OTQ0MDAvMDZjOGRjMTJkYTI3NDVmMWIwYjRlN2MyYzAzMmRmZWYvODQyZDRiOGUyZTAxNGZiYmI4N2M2NDBkZGM4OWQwMzYvIn0.KgRklwDywDbYHzyPfjYKePnRc-CxrEKCvQ02ijhVqwk&provider=cloudfront&v=1",
  "responseContentType": "application/dash+xml"
}
```

**Comment by Felipefpl** [comment]
hi, i saw your question, i was able to run the small video of the girk speaking, what is the address of the video you want to see? I wont purchase a course to see what is the problem. ;) :P

**Comment by ChrisIdema** [comment]
I meant to ask you if you had the same error code on Chrunchyroll. I decided to check myself and I think I solved your problem, see my comment there.

I have problems with course videos of this course: https://www.udemy.com/course/machinelearning/learn/lecture/60871822  . I can play the introduction video just fine since that one is not DRM protected. But the video's of the paid course are blocked. All of the free course play just fine too. Only the paid ones don't play.

I'd be happy to gift someone a course if they can fix this problem.

**Comment by tcreek** [comment]
You may want to specify what you are trying to look at. I have that very course, and all videos play just fine, and I am using Classic 2021.04.02. Some of the "videos" are really not videos, but just displays some texts.

**Comment by ChrisIdema** [comment]
This course video doesn't play: https://www.udemy.com/course/machinelearning/learn/lecture/6087182

It doesn't play on the classic or non-classic version with me.

**Comment by tcreek** [comment]
WFM

**Comment by ChrisIdema** [comment]
What browser version do you use?

I tried both Waterfox G3.2.1 (64-bit) and Waterfox classic 2021.04.2 (64-bit). Browser cache cleared, all addons disabled. Also tried safe mode.

**Comment by MrAlex94** [comment]
403 error suggests permission denied - which I've seen sometimes with user agents websites don't like. ]

Try setting `general.useragent.override` to a `string` such as `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0` in `about:config` and see if it likes that.

**Comment by ChrisIdema** [comment]
Still doesn't play.

**Comment by tcreek** [comment]
I am using Classic 2021.04.02, both on Linux and Windows 10. Though to use GitHub anymore, I have to use another browser. It;s just broken on GitHub

**Comment by ChrisIdema** [comment]
I'm getting the following network error:
`{"errorcode":371000005,"errormsg":"Widevine license acquisition failed >> Verified media path cannot be verified","errorid":"5f076876-93ed-45e9-bd22-1da880340a50"}`

I also tested on a different machine, same problem.

**Comment by MrAlex94** [comment]
Did some digging - unfortunately the DRM module Classic uses is outdated. I'll try updating it, but it's a constant churn (thanks, Google...) so may not work again for Classic. The changes to support newer widevine versions are quite substantial. 

I'll close this - as I'll try get it in the next release. If that doesn't work, unfortunately it never will.

**Comment by ChrisIdema** [comment]
Still doesn't work in Waterfox G3.2.5 (64-bit). I'll keep using Firefox then. As it is the only non-chromium browser that works for me. The browser market is basically a duopoly.

**Comment by tcreek** [comment]
> Still doesn't work in Waterfox G3.2.5 (64-bit). I'll keep using Firefox then. As it is the only non-chromium browser that works for me. The browser market is basically a duopoly.

I suspect something is wrong on your end. While thew number of web sites which no longer function on Waterfox Classic is snowballing, Udemy fully still works great for me.

**Comment by tcreek** [comment]
Also there are a number of non Chrome and Firefox based browsers you can use, but those are on Linux.

**Comment by Yurovskyy** [comment]
just to keep things updated, the drm videos on udemy still dont work on waterfox. I think it's not a end problem with @ChrisIdema. I'm using waterfox on windows and i've tried everything (disabled security stuff and reinstalled the drm stuff) and still dont work. I'm going to download firefox just to see the video xD
