### ISSUE TITLE
[Current/G3] Bookmark Toolbar context menu greyed-out 

### ISSUE THREAD

**Issue by AkazaAkarinn** [MrAlex94/Waterfox#2105]
This seems to be an older bug, as [reported ](https://www.reddit.com/r/waterfox/comments/et72se/bookmark_bar_context_menu_greyedout/)over a year ago. To quote that report:

> This bug has been introduced since the last update. On Waterfox Current 2020.01. After the browser is open for some time, when I right click on an item on the bookmark bar, the context menu is all greyed-out. Can't choose anything. Restarting the browser fixes this though. Can't pinpoint when this happens, but it's only happened when my browser has been open for hours..so far.

I'm having the exact same issue. I've had G3/Current for a while as a secondary browser, but only noticed now because I recently tried making G3 my main browser.

- **Triggered by time and opening Options tab/about:preferences:** After the browser is open some time or opening the Options tab (about:preferences), right clicking a bookmark on the Bookmark Toolbar brings up a greyed-out context menu. 
- **Only appears to affect one window:** When I have two windows open, this issue typically only happens to one window. If this issue is happening and you open a new window, the new window does not suffer from this issue unless I open the Options tab in that window too.  
- **Only fixed by restarting the browser and the Customize tab:** Clicking on Customize and then done seems to resolve this issue temporarily. 
- **Likely not caused by extensions or themes:** The issue continues to happen in safe mode and using the default theme

**Waterfox Version:** G3.2.1 (64-bit)
**OS:** Windows 8.1

**Comment by MrAlex94** [comment]
How odd - can reproduce this. Will try and see what could be the issue.

**Comment by adamp01** [comment]
Note the above PR only addresses the issue as a result of opening about:preferences as long as the bookmarks bar is in the default position (top). Hopefully should be able to get out a more robust fix at some point.
