### ISSUE TITLE
Can I install my favorite chrome extensions in the future?

### ISSUE THREAD

**Issue by DaiDucDaiUy** [MrAlex94/Waterfox#2107]
I tried installing my favorite chrome extension but failed with the message "this addon could not be installed because not all of its features are supported"
https://chrome.google.com/webstore/detail/beecost-tr%E1%BB%A3-l%C3%BD-mua-s%E1%BA%AFm/hfgkoaengklibhfagaababcngpehggmm

P/s: Status bar in Waterfox G3 actually less flexible xiaoxiaofloor's script >"<
https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/chrome/status-bar.uc.js

**Comment by MrAlex94** [comment]
> I tried installing my favorite chrome extension but failed with the message "this addon could not be installed because not all of its features are supported"

Eventually we are aiming to add parity with all of Chrome's WebExtensions API. Since some of them are missing in Firefox, it may take a while.
