### ISSUE TITLE
dot dev domains not working

### ISSUE THREAD

**Issue by noplanman** [MrAlex94/Waterfox#2108]
**Describe the bug**
I can't browse to any ".dev" domains, all I get is "Server Not Found".

Works perfectly in Tor Browser, so the domain names definitely work.

**To Reproduce**
(In safe-mode, so no plugins active)

1. Go to any ".dev" website, like https://laravue.dev/
2. Doesn't work (for me)

**Expected behavior**
To have the website load correctly.

**System (please complete the following information):**
 - OS: macOS 10.13.6 High Sierra
 - Version: G3.2.1

**Comment by MrAlex94** [comment]
I cannot seem to reproduce this error on macOS 11.4. Could potentially be a DNS issue. Are there any modified `network.dns.` preferences in `about:config`? (They will show up as **bold**).

**Comment by noplanman** [comment]
Strange, it seems to be some local / router issue, as I also can't access ".dev" domains in other browsers.
So weird, I wonder when this started happening. Seems that the Tor Browser resolves the DNS differently, so it works there.

Clearly not a Waterfox issue, so closing off.
