### ISSUE TITLE
3 issues on waterfox classic - New user

### ISSUE THREAD

**Issue by xlovinglyx** [MrAlex94/Waterfox#2115]
Hi, i'm using waterfox classic for the first time cause palemoon is finally being bipolar & dumping support
for all legacy addons. I Have 3 issues:

i would so much love to have a status bar like the old firefox used to have, directly selectable
from Menu bar/view/toolbars..

is there a way to disable multi process it shows various windows in task managers processes & i don't know if
it's responsible but when i tweak "customize", it doesn't affect other windows .....

& the tabs at bottom can't be moved to the bottom without obtaining a ridiculous empty space & displacing
tabs..

This below is the result of a userstyle..

![tried a userstyle](https://user-images.githubusercontent.com/53103638/120928157-c92d5800-c6e3-11eb-8349-0e0a6832e3a7.png)

& perfection on pale moon:
![perfect palemoon](https://user-images.githubusercontent.com/53103638/120928185-e06c4580-c6e3-11eb-9c53-c9b4c0345bf1.png)

**Comment by Squall-Leonhart** [comment]
This is not a bug, its a user feature and support request.

**Comment by xlovinglyx** [comment]
can this be added on next release ?

**Comment by reallyuniquename** [comment]
>is there a way to disable multi process

There is a checkbox for that although this is not recommended. Open options, general tab.

>i would so much love to have a status bar like the old firefox used to have

You would have to install legacy addon for that.

>the tabs at bottom can't be moved to the bottom without obtaining a ridiculous empty space & displacing
tabs..

You would have to manually adapt your userstyle to Waterfox.

>can this be added on next release ?

It's probably a firm "no". Watefox Classic is Firefox 56 in maintenance mode meaning you get security patches and maybe some new features or fixes if someone actually volunteers to implement them.

**Comment by xlovinglyx** [comment]
"i would so much love to have a status bar like the old firefox used to have"

-You would have to install legacy addon for that

you probably mean "classic archive addon" that contains tones of addons, as there's no such thing as a named "legacy addon"
as an xpi. but your reply remains indirect, as i've tried many status bar options & non did the job. & in status 4 evar addon,
i still can't see my (link status redux addon) DATED by viewing time links INSIDE the status bar of status 4 evar, cause status 4 evar is too old, & only a clean integrated to waterfox as a View/Toolbars option could allow full compatibility.



"the tabs at bottom can't be moved to the bottom without obtaining a ridiculous empty space & displacing tabs.."

-You would have to manually adapt your userstyle to Waterfox.

Could you suggest me userstyle commands, i have no coding knowledge at all. i'll try to adapt your codes
changing numeric values only. if so, look at the screenshots i already provided, i'd like that strange empty space
that looks like an empty large new toolbar "removed".. & the gap before the first tab too.

I also can't find a way to make the reload button from the url bar disappear, in order to put it after <-  -> @
buttons, & form the icons library, making sure the stop appears when i try to reload it.

**Comment by reallyuniquename** [comment]
>Could you suggest me userstyle commands

You need basic knowledge of CSS to customize your stylesheet, then you can follow [this](https://github.com/Aris-t2/CustomCSSforFx/#how-to-find-item-ids-and-attributes) tutorial.

> you probably mean "classic archive addon" that contains tones of addons, as there's no such thing as a named "legacy addon"

Sure there is. No, I mean exactly legacy addons as opposed to modern web extensions which are also supported by Waterfox Classic. Both are distributed as XPI file.

> i've tried many status bar options & non did the job

Beggars can't be choosers.

**Comment by xlovinglyx** [comment]
Beggars can't be choosers.

true mate, 

i'm now dumping waterfox for the total lack of support & i'll remind u something quickly before my departure.
ppl that use browsers arent supposed to have computer knowledge nor want to learn an entire tutorial & test
thousands of codes till the required tab or space moves.

good luck with ur waterfox.

**Comment by reallyuniquename** [comment]
Suite yourself.

>ppl that use browsers arent supposed to have computer knowledge

You are not supposed to use incompatible custom theme from different browser and expect that someone would fix it for you either.

**Comment by xlovinglyx** [comment]
The theme are just 2 pictures, it doesn't add spaces. I believe it's Aris code that doesn't apply on that last waterfox legacy version.
& now i have better, each time i open a link, my home page appears in a snap before the link is opened. so if i get zero help & just remarks like learn computer languages, i'm going nowhere with this.

**Comment by timur-g** [comment]
Please remove "bug" tag, it's not. 

_"i would so much love to have a status bar like the old firefox used to have"_
I don't understand what you want to achieve. Status bar at the bottom? I used to have it in old Firefox, but I gave up in WF. 
You should start from what you want to see there. 

_& the tabs at bottom can't be moved to the bottom .._ (do you mean "to the top"?)
In your screenshot you have top shown. I don't see why you are using menus, browser doesn't need them really. 
Tabs can be put on top. 

I customized WF to be like old FF with "Classic Theme Restorer v1.7.8.2019.07.07" addon to have old search etc. But I keep tabs on top, menu not needed. I like "PrefBar" addon to have it's commands on top.
