### ISSUE TITLE
CSS math functions min(), max() and clamp()

### ISSUE THREAD

**Issue by notpushkin** [MrAlex94/Waterfox#2117]
We're looking into using `clamp()` in our new project, which isn't supported by Waterfox yet. Those are [supported by all evergreen browsers](https://caniuse.com/css-math-functions) (and some older versions) so there is no reason for us not to use it but sadly it's not yet supported in Waterfox. Is this a good place for requesting this kind of a feature?

Related: [Can I use](https://caniuse.com/css-math-functions), [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=css-min-max)

**Comment by hawkeye116477** [comment]
> it's not yet supported in Waterfox

Well, do you know that there is more than one Waterfox? It's supported in Waterfox G3. In case of Classic, officially will be only security updates, new features may come only if some volunteer will make Pull Request for that.

In case of that feature, Mozilla did that only for Servo, so this won't be that straightforward, someone would need to rewrite that for Gecko.

**Comment by MrAlex94** [comment]
This will be closed since it won't realistically be coming to Classic unless someone ports over the patch.
