### ISSUE TITLE
gitlab.com login page doesn't load in waterfox, does load in firefox

### ISSUE THREAD

**Issue by ChrisIdema** [MrAlex94/Waterfox#2121]
Windows 10.
Waterfox G3.2.1 64-bit
Link: https://gitlab.com/users/sign_in

When opening it remains stuck at the following screen:
```
Checking your browser before accessing gitlab.com.

This process is automatic. Your browser will redirect to your requested content shortly.

Please allow up to 5 seconds…
```

It does work in waterfox classic 2021.04.2 (64-bit) and in firefox

**Comment by hawkeye116477** [comment]
Do you know that there is more than one Waterfox, which is it, what version you have? Too little information. Please fill in template.

**Comment by ChrisIdema** [comment]
> 
> 
> Do you know that there is more than one Waterfox, which is it, what version you have? Too little information. Please fill in template.

Kind of implies the waterfox version of waterfox and not the waterfox classic version and the latest update, but I added more information.

**Comment by reallyuniquename** [comment]
Right. Do you use any custom configs or addons related to privacy, fingerprinting or cloaking? You are getting server side blocked by Cloudflare.

**Comment by ChrisIdema** [comment]
All addons are disabled. I tested it in safe mode.

**Comment by reallyuniquename** [comment]
Custom preferences are not affected by safe mode.

**Comment by ChrisIdema** [comment]
Same in Waterfox G3.2.3 64-bit

**Comment by ChrisIdema** [comment]
> 
> 
> 403 error suggests permission denied - which I've seen sometimes with user agents websites don't like. ]
> 
> Try setting `general.useragent.override` to a `string` such as `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0` in `about:config` and see if it likes that.

Removing this setting fixed it for me.
