### ISSUE TITLE
Github Bug report editor do not work

### ISSUE THREAD

**Issue by Peke** [MrAlex94/Waterfox#2122]
Using clean https://cdn.waterfox.net/releases/win64/portable/WaterfoxPortable_2021.04.2_English.paf.exe I can't use any of the GitHub Issue: Bug report Editor buttons eg. Code/Link/... This is consistent with other sites also.

**Comment by Peke** [comment]
Same thing happens in 2021.6 :(

**Comment by hawkeye116477** [comment]
It's nothing new. See https://github.com/MrAlex94/Waterfox/issues/1959.

**Comment by Peke** [comment]
Yeah that seams to be the case, I guess more and more sites and things ill not work that ell :( 
Last one is https://wordpress.org/plugins/supportcandy/ where edit box which is behind iframe -> HTML -> Body do not allow editing :( and it worked few months ago without a problem.

**Comment by MrAlex94** [comment]
No user friendly solution for this unfortunately.

**Comment by hawkeye116477** [comment]
Well, if Moonchild Productions continue their work, then I'll also try to port that.
