### ISSUE TITLE
[G3.2.1] Refreshing some long-lived tabs causes entire browser to hang for a while

### ISSUE THREAD

**Issue by SwooshyCueb** [MrAlex94/Waterfox#2124]
**Describe the bug**
I leave a couple of twitch streams open in my browser, and after having the tab open for like a day or so, sometimes refreshing the page will cause the entire browser to hang. Sometimes this also happens with Google Voice, which I also keep in a pinned tab, though usually I have to keep it open for at least four days before refreshing will cause a hang.

It happens with other pages too sometimes, but Twitch and Google Voice are the ones I can get it to happen *most consistently* with.

Also now that I'm writing this, it has occurred to me that this bug report might look like a clever ploy to get a few extra viewers for my favorite streamer, but I promise this is not the case.

**To Reproduce**
1. Go to https://www.twitch.tv/zzzphauxe (or anyone who streams on Twitch for a few hours most days)
2. Leave the tab open for a few days, using the browser regularly otherwise.
3. Try to refresh the Twitch page.
4. Become frustrated as your entire web browser locks up for fifteen minutes.

**Expected behavior**
The page refreshes and the browser does not lock up.

**System (please complete the following information):**
 - OS: Arch Linux, kernels 5.7 and 5.12 with AUFS and Futex2 patchsets. (You can see the PKGBUILDS for my kernel packages [here](https://github.com/SwooshyCueb/pkgbuild-linux-kitsinger/) though I'm not sure how relevant this is)
 - Waterfox G3.2.1 (waterfox-g3-kpe 2.1-0 package by hawkeye116477)
   - IIRC, This happened with Waterfox Current as well, but I don't remember what version I was using. It was before I switched over to G3.

**Additional context**
I wouldn't have to reload Google Voice at all if not for a (known, I think?) Firefox bug that causes the js running in the page to break after a while. Messages stop coming in and typing in the message box doesn't cause the send button to become clickable.

Potentially relevant addins installed:
  - FrankerFaceZ (Like RES but for Twitch. Though even if this addin is causing the problem on the Twitch page, it doesn't explain why the problem also happens with Google Voice.)
  - Hover Zoom+ (I think this injects a bit of js into every page, and it does tend to slow down image gallery pages sometimes)
  - KeePassXC-Browser
  - Stylus (Though none of the userstyles I have installed affect Twitch or Google Voice)
  - Tab Session Manager
  - uBlock Origin (I have it disabled on Twitch though, as I have a legacy Twitch Turbo sub which means I don't get ads anyway)

Installed addins that are almost definitely not relevant:
  - Honey (problem was happening before this extension was installed)

Here's the full json from about:support: https://hastebin.com/suqudaxotu.json

Not sure if it matters, but I have FrankerFaceZ [configured](https://hastebin.com/depamaniyu.json) to always take me to the player page and load the chat, even if the streamer is offline.

**Comment by Squall-Leonhart** [comment]
this is because video services are notorious for delaying GC to the point that tab memory has been swapped out to disk, or caused a single process instance of the browser to consume excessive amounts of memory due to fragmentation of the heap.

**Comment by MrAlex94** [comment]
All I can recommend is upgrading to G4 to see if things have been improved in Gecko that this isn't so much of an issue. Fixing this is likely out of the scope of Waterfox and more a platform bug.
