### ISSUE TITLE
Videos not playing on Waterfox Classic for Mac

### ISSUE THREAD

**Issue by Yoshibros11** [MrAlex94/Waterfox#2126]
Hi, I have a clean install of the latest version (2021.06) of waterfox classic on a os x lion machine. The issue is that no html5 videos load. Vimeo, YouTube, Dailymotion, everything. Regular firefox (45 esr) and Chrome work fine for videos. What is the problem? Already tried 1: Disabling all plugins 2: Creating a new profile 3: Clearing site data/cache.

**Comment by Peacock365** [comment]
Turning off multiprocess under about:preferences#general (at the top of the page) fixed it for me, however, something broke video playback on Waterfox Classic if multiprocess windows are enabled.

I am referring this to @dbsoft who is currently about to patch the Mac version of Waterfox Classic anyway.

**Comment by Yoshibros11** [comment]
Multiprocessor is off. In fact it would not let me turn it on, when I checked the box it got unchecked if I restarted or refreshed the preferences page.

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the FOI act or other applicable privileges) or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.
________________________________

**Comment by MrAlex94** [comment]
Hi, I think this has always been a problem. After Firefox 49 I believe they started removing platform code for those versions which is why videos don't play, since there's no code to handle it.

**Comment by Yoshibros11** [comment]
Why did they remove the code? Is there anything I can do to make it work, like install a codec or something? New versions of Firefox play fine on other macs and so does Firefox 45 esr which is what my Mac supports.

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the FOI act or other applicable privileges) or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.
________________________________
