### ISSUE TITLE
[Waterfox G3.2.3.1] NPAPI plugin

### ISSUE THREAD

**Issue by hurumori** [MrAlex94/Waterfox#2129]
Hello
I heard that the NPAPI plugin can be used with Waterfox G3.2.3.1 (Waterfox Current), but it doesn't seem to work.
It works fine with Waterfox Classic.
![210612-065532](https://user-images.githubusercontent.com/43722233/121766651-84476c80-cb8e-11eb-9565-27d750988c86.jpg)

The applet tags used are as follows.

`<APPLET code="c.ShiPainter.class" archive="spainter.jar,res/normal.zip" name="paintbbs" width="450" height="475">`
`<param name="header_magic" value="S">`
`<param name="dir_resource" value="res/">`
`<param name="res.zip" value="res/res_normal.zip">`
`<param name="tools" value="normal">`
`<param name="layer_count" value="3">`
`<param name="quality" value="1">`
`<param name="tt.zip" value="res/tt.zip">`
 `<param name="url_save" value="imgsave.cgi">`
 `<param name="url_exit" value="toko_oya.cgi?mode=newtokof&id=ID5zGXebYsrn5915793291623447986">`
`<param name="send_language" value="sjis">`
`<param name="send_header" value="mode=new&pass=mnAsqujPz39Us&name=%82%c8%82%c8%82%b5%2a1ZYaC&applet=shipainter&width=250&height=325&pstim=1623447986&quo=1&no=&id=ID5zGXebYsrn5915793291623447986&mbname=0&mbicon=&tochu=&type=&">`
`<param name="animation_max" value="0">`
`<param name="compress_level" value="5">`
`<param name="image_width" value="250">`
`<param name="image_height" value="325">`
`<param name="image_interlace" value="false">`
`<param name="image_jpeg" value="true">`
`<param name="image_size" value="300">`
`<param name="layer_count" value="3">`
`<param name="poo" value="false">`
`<param name="quality" value="1">`
`<param name="send_advance" value="true">`
`<param name="send_header_count" value="true">`
`<param name="send_header_timer" value="true">`
`<param name="thumbnail_compress_level" value="30">`
`<param name="thumbnail_width" value="200">`
`<param name="thumbnail_height" value="260">`
`<param name="thumbnail_type" value="animation">`
`<param name="thumbnail_type2" value="jpeg">`
`<param name="undo" value="630">`
`<param name="undo_in_mg" value="20">`
`<param name="java_arguments" value="-Xms1G -Xmx1G -Xnoclassgc -Dsun.java2d.noddraw=true -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=256M -Xverify:none">`
`</APPLET>`

The sites where applets exist are as follows. 
https://oekakiart.net/oeb10/
![210612-144143のコピー](https://user-images.githubusercontent.com/43722233/121766825-92e25380-cb8f-11eb-804a-ef803179c625.jpg)

I'm sorry if my perception is wrong.
Waterfox has helped me a lot.
Thank you so much for developing it!

**Comment by MrAlex94** [comment]
Sadly NPAPI implementation going forward has become incredibly difficult and this will have to be closed.
I do apologise that there is no resolution for this issue.
