### ISSUE TITLE
HD not supported in prime video.

### ISSUE THREAD

**Issue by AnkyPainter** [MrAlex94/Waterfox#2130]
Hello,

I recently changed from Firefox; the change was super smooth, up until I wanted to watch an show on Amazon Prime Video where it popped up with the box in the screenshot.

I tried searching for this problem but the only thing I could find was an close issue on this github with no solution insight.

**Describe the bug**
Unable to play videos on Amazon Prime Video in High-Definition.

**Screenshots**
![prime video being a cunt](https://user-images.githubusercontent.com/85837460/121813071-1a69b880-cc9d-11eb-8e68-af9466ebe7c2.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Version: G3.2.3

**Comment by MrAlex94** [comment]
Unfortunately this has always been an issue. We use a proper user agent override but it seems that's not enough - I'm not sure what checks amazon does to verify if a browser supports HD+ playback, but seems Waterfox doesn't meet those requirements (even if it technically does).

**Comment by AnkyPainter** [comment]
Thanks for the reply and help. I guess I could always just use another browser to watch prime. Thank you.
