### ISSUE TITLE
[classic] Gitlab.com view issue broken

### ISSUE THREAD

**Issue by c33s** [MrAlex94/Waterfox#2132]
**Describe the bug**

most interface section in gitlab.com are missing while viewing an issue
see bugreport on gitlab https://gitlab.com/gitlab-org/gitlab/-/issues/333598

**To Reproduce**
1. Go to https://gitlab.com/gitlab-org/gitlab/-/issues/333595
2. See missing interface parts

**Screenshots**
see linked ticket

**System (please complete the following information):**
 - OS: win
 - Version: classic 2021.06

**Comment by hawkeye116477** [comment]
From console => `ReferenceError: customElements is not defined`

So looks like that's same problem as with GitHub - they started using Web Components. Polly helps for both cases.

**Comment by c33s** [comment]
not so easy to get polly as the official repo is archived https://github.com/zakius/Polly
according to https://www.waterfox.net/blog/waterfox-2021.02-release/ polly should be integrated but if i create an new empty profile there is no polly.

for reference: i had to enable `polyfills/Webcomponents-ce.js` to make gitlab work again (previously i had only enalbed `polyfills/WEbcomponents-Bundle.js` for github `polyfills/WEbcomponents-Bundle.js` is enough).

edit: if polly is the official fix feel free to close

edit2: ad polly see https://github.com/MrAlex94/Waterfox/issues/1958

**Comment by hawkeye116477** [comment]
> polly is the official fix

It's rather semi-official, but officially for Classic will be only security updates. However that doesn't mean that Pull Requests for new features are forbidden for contributors, but as Moonchild said it's not that easy => https://repo.palemoon.org/MoonchildProductions/UXP/issues/1593.

**Comment by MrAlex94** [comment]
Unfortunately - as hawkeye has mentioned - unless someone provides a fix, will have to close this issue.

**Comment by timur-g** [comment]
Also reported on https://gitlab.com/gitlab-org/gitlab/-/issues/333598.
