### ISSUE TITLE
No Video with Supported Format an MIME Type

### ISSUE THREAD

**Issue by Haiyami** [MrAlex94/Waterfox#2136]
**Describe the bug**
So with the third generation release I can no longer play videos that support the format with MIME type. I've tried installing lightspark in windows 10 as a flash player emulator. Clear the cookies and cache, install a flash emulator plug in and also tried the firefox Noplug add on. None of these work. 

**To Reproduce**
1. Go to https://chan.sankakucomplex.com/post/show/24216440  (Warning NSFW)
2. See error

**Expected behavior**
The video should play automatically or give a play button in the video box. I you can't

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10 Pro 
 - Version 21H1

**Additional context**
I can get this to work in Brave Browser and chrome, but it refuses to work in watefox. I'm very confused. Also I can't do a manual install Media Feature Pack because I have Windows 10 Pro NT type. To install the Media Feature Pack manually I must have Windows KN or Windows N. The NT types I think already come with the Media Feature Pack installed. So I'm at a loss here.

**Comment by molitar** [comment]
I think it goes back to this so the Waterfox developers need to remove the 48K limit.

https://bugzilla.mozilla.org/show_bug.cgi?id=1698639

**Comment by MrAlex94** [comment]
This is a platform rather than Waterfox specfic bug. Please file a bug with Mozilla and hope they patch it :-)
