### ISSUE TITLE
Classic 2021-6 - Cant download files from transifex.com

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2141]
### What happened?

click in any translation here https://www.transifex.com/sledgehammer999/qbittorrent/language/pt_BR/

select "download file to translate" or "download to use" - an spinning icon is displayed but the download never starts, tested on firefox and it works (after spinning for some time), this didnt happen with the previous version.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by hawkeye116477** [comment]
> this didnt happen with the previous version

It's not entirely true, it was working some time ago, but then it stopped, because webmasters made changes.
By looking at console, looks like there is a some request which is blocked by CSP, cuz it's from another domain and there is Same Origin Policy.

**Comment by Felipefpl** [comment]
I see, i reported the problem to transifex too but they didnt say anything about this change, i hope they fix it. But the download works on firefox although it takes some time to start.

**Comment by hawkeye116477** [comment]
Well, I found the culprit, that was fixed in FF 63. I'll submit PR.

**Comment by Felipefpl** [comment]
That is great, thanks for fixing it.

**Comment by Felipefpl** [comment]
I tested this on classic 2021-7 and it works (although the download takes some time to start, it should come faster) so i'm closing this.
