### ISSUE TITLE
Very popular Russian webstore site not working!

### ISSUE THREAD

**Issue by NKSoft7** [MrAlex94/Waterfox#2142]
### What happened?

Ozon.ru - when you try to log-in, the login window just animates forever and doesn't load.. New Firefox and other browsers are fine with it.. Safe mode doesn't help.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
[ERROR] SecurityError: Permission denied to access property "dispatchEvent" on cross-origin object  libs.98ed8ec13f3a198ba16a.js:12:86176
[DEBUG]: Additional infolibs.98ed8ec13f3a198ba16a.js:12
Object { date: Date 2021-06-28T15:24:27.302Z, type: "log", url: "https://www.ozon.ru/my/legaldetails/", exception: SecurityError, abGroup: 47, browser: "Mozilla/5.0 (Windows NT 6.1; Win64;…", platform: "desktop", xcid: "19c50e9aa516e1d54d4d87b78e157079", layoutId: 2697, experiments: "1007:2430,1011:2440,1055:2561,1077:…", 4 more… }  libs.98ed8ec13f3a198ba16a.js:12:86377
SecurityError: Permission denied to access property "dispatchEvent" on cross-origin object  inject.js:65
XML Parsing Error: no root element found
Location: https://xapi.ozon.ru/api/logs-gateway/input
Line Number 1, Column 1:  input:1:1
[ERROR] SecurityError: Permission denied to access property "dispatchEvent" on cross-origin object  libs.98ed8ec13f3a198ba16a.js:12:86176
[DEBUG]: Additional infolibs.98ed8ec13f3a198ba16a.js:12
Object { date: Date 2021-06-28T15:24:27.628Z, type: "log", url: "https://www.ozon.ru/my/legaldetails/", exception: SecurityError, abGroup: 47, browser: "Mozilla/5.0 (Windows NT 6.1; Win64;…", platform: "desktop", xcid: "19c50e9aa516e1d54d4d87b78e157079", layoutId: 2697, experiments: "1007:2430,1011:2440,1055:2561,1077:…", 4 more… }  libs.98ed8ec13f3a198ba16a.js:12:86377
SecurityError: Permission denied to access property "dispatchEvent" on cross-origin object  inject.js:65
XML Parsing Error: no root element found
Location: https://xapi.ozon.ru/api/logs-gateway/input
Line Number 1, Column 1:  input:1:1
[ERROR] SecurityError: Permission denied to access property "dispatchEvent" on cross-origin object  libs.98ed8ec13f3a198ba16a.js:12:86176
[DEBUG]: Additional infolibs.98ed8ec13f3a198ba16a.js:12
Object { date: Date 2021-06-28T15:24:34.840Z, type: "log", url: "https://www.ozon.ru/my/legaldetails/", exception: SecurityError, abGroup: 47, browser: "Mozilla/5.0 (Windows NT 6.1; Win64;…", platform: "desktop", xcid: "19c50e9aa516e1d54d4d87b78e157079", layoutId: 2697, experiments: "1007:2430,1011:2440,1055:2561,1077:…", 4 more… }  libs.98ed8ec13f3a198ba16a.js:12:86377
SecurityError: Permission denied to access property "dispatchEvent" on cross-origin object  inject.js:65
XML Parsing Error: no root element found
Location: https://xapi.ozon.ru/api/logs-gateway/input
Line Number 1, Column 1:  input:1:1
[ERROR] ReferenceError: ReadableStream is not defined  libs.98ed8ec13f3a198ba16a.js:12:86176
[DEBUG]: Additional infolibs.98ed8ec13f3a198ba16a.js:12
Object { date: Date 2021-06-28T15:24:35.962Z, type: "log", url: "/my/legaldetails/", exception: ReferenceError, abGroup: 47, zone: "layout", browser: "Mozilla/5.0 (Windows NT 6.1; Win64;…", platform: "desktop", errorCode: "COMPOSER_FETCH_LAYOUT", xcid: "19c50e9aa516e1d54d4d87b78e157079", 6 more… }  libs.98ed8ec13f3a198ba16a.js:12:86377
[ERROR] Error: Invalid data from composer  libs.98ed8ec13f3a198ba16a.js:12:86176
[DEBUG]: Additional infolibs.98ed8ec13f3a198ba16a.js:12
Object { date: Date 2021-06-28T15:24:35.968Z, type: "log", url: "/my/legaldetails/", exception: Error, abGroup: 47, browser: "Mozilla/5.0 (Windows NT 6.1; Win64;…", platform: "desktop", xcid: "19c50e9aa516e1d54d4d87b78e157079", layoutId: 2697, experiments: "1007:2430,1011:2440,1055:2561,1077:…", 4 more… }  libs.98ed8ec13f3a198ba16a.js:12:86377
XML Parsing Error: no root element found
Location: https://xapi.ozon.ru/api/logs-gateway/input
Line Number 1, Column 1: input:1:1
[ERROR] SecurityError: Permission denied to access property "dispatchEvent" on cross-origin object  libs.98ed8ec13f3a198ba16a.js:12:86176
[DEBUG]: Additional infolibs.98ed8ec13f3a198ba16a.js:12
Object { date: Date 2021-06-28T15:24:40.022Z, type: "log", url: "https://www.ozon.ru/my/legaldetails/", exception: SecurityError, abGroup: 47, browser: "Mozilla/5.0 (Windows NT 6.1; Win64;…", platform: "desktop", xcid: "19c50e9aa516e1d54d4d87b78e157079", layoutId: 2697, experiments: "1007:2430,1011:2440,1055:2561,1077:…", 4 more… }  libs.98ed8ec13f3a198ba16a.js:12:86377
SecurityError: Permission denied to access property "dispatchEvent" on cross-origin object  inject.js:65
XML Parsing Error: no root element found
Location: https://xapi.ozon.ru/api/logs-gateway/input
Line Number 1, Column 1:
```

**Comment by NKSoft7** [comment]
Well, actually, it's not G3, it's Classic.. I'm confused - can I file an issue for Classic?.. Is it going to be supported in future?

**Comment by hawkeye116477** [comment]
Well, it's written on the form `Please do not report Classic bugs`, but what if theoretically some security fix will cause problems.... I think that if it's not final version, then it should be allowed to report Classic bugs, cuz people are not infallible.

Anyway if your issue isn't regression, isn't working in previous versions, then that would be probably closed, cuz Classic officially will receive only security fixes, other things only from contributors.
Maybe I could help, but that logs doesn't say anything special and I don't known Russian and Google says that can't translate site.

**Comment by reallyuniquename** [comment]
>[ERROR] ReferenceError: ReadableStream is not defined  libs.98ed8ec13f3a198ba16a.js:12:86176

If that's the cause polyfill for Streams API might help (if there's one).

**Comment by hawkeye116477** [comment]
Streams API is also partially implemented (`dom.streams.enabled` and `javascript.options.streams`).

Polyfill is on https://github.com/MattiasBuelens/web-streams-polyfill#readme, but currently no one maintains Polly extension, so probably that won't be helpful for him.

**Comment by NKSoft7** [comment]
> Well, it's written on the form `Please do not report Classic bugs`, but what if theoretically some security fix will cause problems.... I think that if it's not final version, then it should be allowed to report Classic bugs, cuz people are not infallible.
> 
> Anyway if your issue isn't regression, isn't working in previous versions, then that would be probably closed, cuz Classic officially will receive only security fixes, other things only from contributors.
> Maybe I could help, but that logs doesn't say anything special and I don't known Russian and Google says that can't translate site.

Sorry for missing this.. Here's the [link](https://ibb.co/1R6LyTz) showing how to login. After clicking the login button we get a small white window with dots animating forever.. Also thanks all for previous suggestions, but it seems to be too hard for me to figure out fully because I'm not a Web geek unfortunately.. I could of course install Polly extension if it could help(?).. But this all is really frustrating and I just can't get - did it get that bad that you have to compile yourself a browser every week if you want to get some stable and _comfortable_ one..? )) I mean, in ealier days APIs and standards never changed, just sometimes extended.. I also only see the real usability and necessity of Waterfox only in Classic version for such addons as Session Manager which I use this browser for at all! Without Session Manager, frankly, I'd switch to new Firefox because it got much better in terms of speed though still worse than Chrome or Opera but very memory economic in return). BTW, I'm really surprised that SessionManager-like addon isn't still built into any of the browser, it's really a must and it will be just more and more popular in future.. Of course, it is probably would be nice to have a privacy-and-simplicity-oriented variant of Firefox, but probably, it also can give issues like this and I need at least one just stable browser.. That all forces me right now to give a try to Basilisk browser.. )

**Comment by reallyuniquename** [comment]
Open `about:config` in Waterfox and toggle `dom.streams.enabled` and `javascript.options.streams` to `true`. Maybe that would help.

**Comment by hawkeye116477** [comment]
> That all forces me right now to give a try to Basilisk browser

Basilisk haven't Streams API implemented (Waterfox Classic has that partially implemented). 

PS: Basilisk is based on FF 52, so it may even haven't some features which Classic has, in case of html5test, Waterfox Classic wins. I know, they are porting some features, but unfortunately that test shows that still there are some features which Classic has, but Basilisk not. However there are also some features which Basilisk has, but Classic didn't, cuz they ported some features from newer Firefox versions. Anyway by doing Pull Requests, I'm trying to catch up them now :smile:.

**Comment by NKSoft7** [comment]
> 
> Open `about:config` in Waterfox and toggle `dom.streams.enabled` and `javascript.options.streams` to `true`. Maybe that would help.

That helped!!! Thank you so much! If I recall correct, at first I've read your reply not carefully and set them both to "false", or maybe I even didn't try it yet and by default they were set to "false".. :)  It works and I don't have to change the browser and work without SessionManager!!! ..yet )). Actually, I have a session "db" of SessionManager sync with OneDrive to have my sessions (including current) synced between work, home, or wherever I am so that's important for me..

> Basilisk haven't Streams API implemented (Waterfox Classic has that partially implemented).

Yes, I've already found that out, it doesn't even have the above options in config and it doesn't work with my issue site also.. 

P.S. it's also frustrating that Github doesn't work too and I have to switch to Firefox to comment..

**Comment by tcreek** [comment]
I am sorry to say, but while the number of sites not functioning for Waterfox classic is snowballing, I have also been testing Firefox alongside. Both current version and v78 ESR. I am starting to see a LOT of sites not fully functioning with Firefox altogether.

Sorry, but until we can get others to stop using Chromium based browsers, all web sites soon enough are going to be made for it. 

At this point freaking Microsoft Edge now has more active users than Firefox.

**Comment by MrAlex94** [comment]
Classic is really becoming long in the tooth - security patches are the only thing being applied unless someone provides feature patches.

I'll close this since it appears some sort of workaround has been found.
