### ISSUE TITLE
[Classic] Can´t play video content from Mitele.es

### ISSUE THREAD

**Issue by Killogy** [MrAlex94/Waterfox#2148]
Since weeks ago Waterfox Classic can´t play video content from Mitele.es, player loading icon on screen just animates forever and never starts.

https://www.mitele.es/programas-tv/cuarto-milenio/temporada-16/programa-40_1009027075034/player/

Tested on previous Waterfox Classic versions and does not works.

Waterfox G3 is working properly.

So something on Mitele.es side has changed and now Waterfox Classic stopped working.

Maybe issue is something similiar as this one https://github.com/MrAlex94/Waterfox/issues/2142

**Comment by hawkeye116477** [comment]
Can you show browser's console logs (right click => Inspect => Console)?

**Comment by Killogy** [comment]
Yes

Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  blank
GET https://www.mitele.es/programas-tv/cuarto-milenio/temporada-16/programa-40_1009027075034/player/ [HTTP/2.0 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  player
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  player
GET https://baul.mediaset.es/dist/styles.bundle.css [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/headerMtweb.bundle.css [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/footerMtweb.bundle.css [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/styles/accengage.css [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/MSPlayerWrapper.bundle.css [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/navigationMtweb.bundle.css [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/prePlayer.bundle.css [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/testAB.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/runtime.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/dryPageMtweb.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/js/sibbo/prebid_mitele.min.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/js/polyfill/encoding.js [HTTP/2.0 200 OK 0ms]
GET https://securepubads.g.doubleclick.net/tag/js/gpt.js [HTTP/2.0 200 OK 0ms]
GET https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/nonAdBlock/adjs.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/nonAdBlock/adframe.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/vendor.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/headerMtweb.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/navigationMtweb.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/footerMtweb.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/MSPlayerWrapper.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/prePlayer.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://www.googletagmanager.com/gtag/js [HTTP/2.0 200 OK 0ms]
GET https://cdns.gigya.com/js/gigya.js [HTTP/1.1 200 OK 0ms]
GET https://webpixel.smartmeapp.com/smapixel.min.js [HTTP/2.0 200 OK 0ms]
GET https://album.mediaset.es/cimg/1001/2019/12/05/logo_mitele_05ff_05ff_05ff.png [HTTP/2.0 200 OK 0ms]
GET https://album.mediaset.es/atenea/backup_poster_e49ec340bd.png [HTTP/2.0 200 OK 0ms]
GET https://album.mediaset.es/cimg/807010/2021/06/26/cuartomilenio_663_ec66.jpg [HTTP/2.0 200 OK 0ms]
GET https://album.mediaset.es/eimg/10000/2021/06/27/clipping_A9LywA_9f27.jpg [HTTP/2.0 200 OK 0ms]
GET https://static.zuora.com/Resources/libs/hosted/1.3.0/zuora-min.js [HTTP/1.1 200 OK 0ms]
GET https://baul.mediaset.es/dist/styles.bundle.css [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/headerMtweb.bundle.css [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/footerMtweb.bundle.css [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/runtime.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/fonts/Flama-Basic.woff [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/fonts/Flama-Light.woff [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/dryPageMtweb.bundle.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/prePlayer.bundle.css [HTTP/2.0 200 OK 0ms]
GET https://ms20.spxl.socy.es/pixel/js/MS20_873_234_125/aHR0cHM6Ly9naXRodWIuY29tL01yQWxleDk0L1dhdGVyZm94L2lzc3Vlcy8yMTQ4 [HTTP/2.0 200 OK 0ms]
GET XHR https://mab.mediaset.es/1.0.0/get [HTTP/2.0 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  player
GET https://baul.mediaset.es/dist/assets/fonts/Flama-Basic.woff [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/fonts/Flama-Light.woff [HTTP/2.0 200 OK 0ms]
GET XHR https://roulette.mediaset.es/v1/play/mtweb [HTTP/2.0 200 OK 0ms]
GET https://securepubads.g.doubleclick.net/gpt/pubads_impl_2021062901.js [HTTP/2.0 200 OK 0ms]
GET XHR https://securepubads.g.doubleclick.net/pagead/ppub_config [HTTP/2.0 200 OK 0ms]
GET https://s.go-mpulse.net/boomerang/7VRN7-TTE4X-5RS2A-WGG92-HEMEZ [HTTP/2.0 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  player
GET XHR https://ms20.spxl.socy.es/pixel.json [HTTP/2.0 200 OK 219ms]
GET https://www.google.com/pagead/conversion_async.js [HTTP/2.0 200 OK 0ms]
GET XHR https://mab.mediaset.es/1.0.0/get [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/google/shaka/shaka-player.compiled.debug.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/hls/hls-0.13.1.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/comscore/comscore-7.4.1.200701.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/conviva/conviva-core-sdk.min.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/omniture/videoheartbeat.min.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/js/indigitall/sdk.min.js [HTTP/2.0 200 OK 0ms]
GET https://baul.mediaset.es/dist/assets/omniture/visitorapi.min.js [HTTP/2.0 200 OK 0ms]
GET https://cdn.dashjs.org/v3.1.0/dash.all.min.js [HTTP/1.1 200 OK 0ms]
GET https://tags.bkrtx.com/js/bk-coretag.js [HTTP/1.1 200 OK 0ms]
GET https://imasdk.googleapis.com/js/sdkloader/ima3.js [HTTP/2.0 200 OK 0ms]
GET https://connect.facebook.net/en_US/fbevents.js [HTTP/2.0 200 OK 0ms]
GET XHR https://mab.mediaset.es/1.0.0/get [HTTP/2.0 200 OK 0ms]
GET XHR https://mab.mediaset.es/1.0.0/get [HTTP/2.0 200 OK 0ms]
GET XHR https://roulette.mediaset.es/v1/rebound [HTTP/2.0 200 OK 203ms]
GET https://googleads.g.doubleclick.net/pagead/viewthroughconversion/586458331/ [HTTP/2.0 200 OK 249ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  player
GET https://baul.mediaset.es/dist/assets/web-workers/checkRun.min.js [HTTP/2.0 200 OK 0ms]
GET https://medicion.mediaset.es/js/modern/s_code.js [HTTP/2.0 200 OK 0ms]
GET https://connect.facebook.net/signals/config/1792536134202652 [HTTP/2.0 200 OK 0ms]
GET XHR https://baul.mediaset.es/WbYQx/defaultview/LHn3c/fuckadblock.js [HTTP/2.0 404 Not Found 250ms]
GET https://www.google.com/pagead/1p-user-list/586458331/ [HTTP/2.0 200 OK 250ms]
GET XHR https://dpm.demdex.net/id [HTTP/1.1 200 OK 188ms]
GET https://www.google.es/pagead/1p-user-list/586458331/ [HTTP/2.0 200 OK 47ms]
GET XHR https://baul.mediaset.es/defaultview/adjs.js [HTTP/2.0 404 Not Found 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  player
GET https://mediaset.demdex.net/dest5.html [HTTP/1.1 200 OK 141ms]
GET https://cm.everesttech.net/cm/dd [HTTP/1.1 302  297ms]
GET https://dpm.demdex.net/ibs:dpid=411&dpuuid=YOG5SAAAAJE8kBHl [HTTP/1.1 200 OK 47ms]
GET https://c.amazon-adsystem.com/aax2/apstag.js [HTTP/2.0 200 OK 0ms]
GET XHR https://cdns.eu1.gigya.com/sdk.config.get [HTTP/1.1 200 OK 0ms]
GET https://connect.facebook.net/signals/config/154862309291125 [HTTP/2.0 200 OK 0ms]
GET https://pagead2.googlesyndication.com/pagead/js/r20210630/r20190131/show_ads_impl_with_ama.js [HTTP/2.0 200 OK 0ms]
GET https://googleads.g.doubleclick.net/pagead/html/r20210630/r20190131/zrt_lookup.html [HTTP/2.0 200 OK 0ms]
GET XHR https://c.amazon-adsystem.com/cdn/prod/config [HTTP/2.0 204 No Content 0ms]
GET XHR https://c.amazon-adsystem.com/bao-csm/aps-comm/aps_csm.js [HTTP/2.0 200 OK 0ms]
GET https://cdns.eu1.gigya.com/gs/webSdk/Api.aspx [HTTP/1.1 200 OK 0ms]
GET https://imasdk.googleapis.com/js/core/bridge3.470.1_es.html#goog_1411053286 [HTTP/2.0 200 OK 0ms]
GET https://pagead2.googlesyndication.com/omsdk/releases/live/omweb-v1.js [HTTP/2.0 200 OK 0ms]
GET https://partner.googleadservices.com/gampad/cookie.js [HTTP/2.0 200 OK 234ms]
GET https://googleads.g.doubleclick.net/pagead/ads [HTTP/2.0 403 Forbidden 47ms]
GET https://adservice.google.com/adsid/integrator.js [HTTP/2.0 200 OK 281ms]
GET https://adservice.google.es/adsid/integrator.js [HTTP/2.0 200 OK 125ms]
GET https://www.googletagservices.com/activeview/js/current/osd.js [HTTP/2.0 200 OK 0ms]
GET https://adservice.google.es/adsid/integrator.js [HTTP/2.0 200 OK 47ms]
GET https://adservice.google.com/adsid/integrator.js [HTTP/2.0 200 OK 46ms]
GET XHR https://cdns.eu1.gigya.com/sdk.config.get [HTTP/1.1 200 OK 0ms]
GET https://cdns.gigya.com/js/GenesisExchange_Gigya.min.js [HTTP/1.1 200 OK 0ms]
GET XHR https://pagead2.googlesyndication.com/getconfig/sodar [HTTP/2.0 200 OK 140ms]
GET XHR https://c.go-mpulse.net/api/config.json [HTTP/1.1 200 OK 327ms]
GET https://tpc.googlesyndication.com/sodar/sodar2.js [HTTP/2.0 200 OK 0ms]
GET XHR https://login.mitele.es/accounts.webSdkBootstrap [HTTP/1.1 200 OK 203ms]
GET https://tpc.googlesyndication.com/sodar/sodar2/224/runner.html [HTTP/2.0 200 OK 0ms]
GET https://www.google.com/recaptcha/api2/aframe [HTTP/2.0 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  blank
GET https://pagead2.googlesyndication.com/pagead/sodar [HTTP/2.0 204 No Content 109ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  blank
GET https://cdns.eu1.gigya.com/gs/sso.htm [HTTP/1.1 200 OK 0ms]
GET https://cdns.eu1.gigya.com/gs/sso.htm [HTTP/1.1 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
GET XHR https://cdns.eu1.gigya.com/sdk.config.get [HTTP/1.1 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
GET XHR https://cdns.eu1.gigya.com/sdk.config.get [HTTP/1.1 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
GET https://pagead2.googlesyndication.com/bg/u5qa6Bce0_JDlbgkcQuMCffbH_LjsHWDv7QaTzlh7sk.js [HTTP/2.0 200 OK 0ms]
GET https://pagead2.googlesyndication.com/pagead/show_companion_ad.js [HTTP/2.0 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  blank
GET https://cdns.eu1.gigya.com/gs/sso.htm [HTTP/1.1 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
GET XHR https://cdns.eu1.gigya.com/sdk.config.get [HTTP/1.1 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  sso.htm
GET https://connect.facebook.net/es_ES/sdk.js [HTTP/2.0 200 OK 0ms]
GET https://connect.facebook.net/es_ES/sdk.js [HTTP/2.0 200 OK 0ms]
Unable to check <input pattern='*'> because the pattern is not a valid regexp: nothing to repeat  player
GET XHR https://www.facebook.com/x/oauth/status [HTTP/2.0 200 OK 250ms]
GET https://pagead2.googlesyndication.com/pagead/gen_204 [HTTP/2.0 204 No Content 46ms]
TypeError: this.refreshGPTAds is not a function[Learn More]  headerMtweb.bundle.js:1

**Comment by hawkeye116477** [comment]
And we have explanation => `Unable to check because the pattern is not a valid regexp`, so they use some new regexp feature, which Classic doesn't support, so it's not the same as issue you marked. Officially it won't be fixed, you can only count on external contributors.

**Comment by Killogy** [comment]
Ok thanks
