### ISSUE TITLE
white bar at top when recording with OBS

### ISSUE THREAD

**Issue by 0lm** [MrAlex94/Waterfox#2151]
### What happened?

When using OBS on Waterfox Window, there is a thin white bar on top of the screen. (the white bar is from begin of the window up to the end of the window. Not only above the tabs, but generally on top of waterfox window). This only happens when using OBS on Waterfox. When using OBS on Firefox, there is no problem.

Is this an issue that needs to be fixed in OBS, or in Waterfox?

I added a screenshot here: https://i.imgur.com/JNi0tz0.png
That's the preview OBS is giving me, the white bar at top. (the black stuff is just what I censored, since that's not necessary information for this bug)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
This may have been due to the Floe/Abyss themes. Does this still occur in G4?
