### ISSUE TITLE
[Classic] Support for lookbehind regex syntax

### ISSUE THREAD

**Issue by reallyuniquename** [MrAlex94/Waterfox#2152]
### Summary

Some regex evaluations fail with the console message `SyntaxError: invalid regexp group`. 

### Notes

I think Waterfox Classic is lacking support for lookbehind regex syntax.

### To Reproduce

Script snippet that instantly fails if you run it.

```js
const r = /\[@(?<id>\d+)\|(?<name>.+?)\]/g;
```

**Comment by hawkeye116477** [comment]
Well, it could be a lot of work, for first [updating to Mozilla's new V8 regexp parser](https://repo.palemoon.org/MoonchildProductions/UXP/issues/1675) is needed.

**Comment by reallyuniquename** [comment]
I suppose this can't be fixed with polyfills?

**Comment by EternityEngine** [comment]
I've run into a similar error in Classic ([link](https://www.tumblr.com/login)): `SyntaxError: invalid identity escape in regular expression`

The problem code appears to be:

```javascript
g = new RegExp("(?:\\p{RI}\\p{RI}|\\p{Emoji}(?:\\p{Emoji_Modifier}|\\u{FE0F}\\u{20E3}?|[\\u{E0020}-\\u{E007E}]+\\u{E007F})?(?:\\u{200D}\\p{Emoji}(?:\\p{Emoji_Modifier}|\\u{FE0F}\\u{20E3}?|[\\u{E0020}-\\u{E007E}]+\\u{E007F})?)*)|[\\u{1f900}-\\u{1f9ff}\\u{2600}-\\u{26ff}\\u{2700}-\\u{27bf}]", "gu");
```

**Comment by hawkeye116477** [comment]
@reallyuniquename Rather no, but good news is that Moonchild Team resumed the work on this. So it'll be little easier to port this, less work and #2192 is introduction.
