### ISSUE TITLE
Waterfox 2021.06 Classic 64  Book Mark Tool Bar Blank 

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#2154]
### What happened?

With the past 3 updates of Waterfox Classic 2021.06 now the Book Mark Tool Bar is completely Blank none of my Book Mark Links are showing. The Tool bar is just blank. 

I;ve tried to uninstall and reinstall and reimport the links nothing resolves this issue. 
![image](https://user-images.githubusercontent.com/20975332/124660433-2e57a300-de74-11eb-8ca0-844a2008b63c.png)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by Killogy** [comment]
Bookmarks toolbar is working well for me, I see my bookmarks there and I can add more.

You can test creating a new Waterfox profile,

**Comment by A0R-R0CKS** [comment]
It did the same thing with a new profile , I even tried to delete and restore one nothing.

**Comment by Killogy** [comment]
I have 8 Waterfox Classic 2021.06 (64-bit) profiles and are working properly.

Instead restoring your links from a backup, creates new toolbar bookmarks instead. Maybe backup is corrupt or import function is not importing them properly, So if you can add new bookmarks manually, the problem maybe is related to reimport or backup integrity.

Try reinstalling old Waterfox Classic version and running without any addon installed.

Waterfox Classic 2021.04
https://cdn.waterfox.net/releases/win64/installer/Waterfox%20Classic%202021.04%20Setup.exe
Waterfox Classic 2021.03
https://cdn.waterfox.net/releases/win64/installer/Waterfox%20Classic%202021.03%20Setup.exe
Waterfox Classic 2021.02
https://cdn.waterfox.net/releases/win64/installer/Waterfox%20Classic%202021.02%20Setup.exe
Waterfox Classic 2021.01
https://cdn.waterfox.net/releases/win64/installer/Waterfox%20Classic%202021.01%20Setup.exe

P.S: I tested and when I reimported bookmarks, toolbar bookmarks are not being imported to the correct Toolbar bookmarks folder, they are imported to a new Toolbar bookmarks folder, at bottom of the Bookmarks Menu, so they are not showing. 

Then you need to manually drag/drop toolbar bookmarks imported into the correct Toolbar bookmarks folder is on top of Bookmarks Menu and under All Bookmarks.
