### ISSUE TITLE
[Classic 2021.06 (64 bit)] not works correct to load the page:

### ISSUE THREAD

**Issue by manuelsongokuh** [MrAlex94/Waterfox#2163]
### What happened?

simple: go to site: https://invent.kde.org/multimedia/kdenlive  or https://invent.kde.org/multimedia/kdenlive/-/issues/1130

not see bottom the coomants, nothing.. but before was works perfect.. and now not works..

please check it..what is up to Classic.

i try open firefox laster: works, chromium works, waterfox current works..

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux

**Comment by hawkeye116477** [comment]
The problem is that Classic doesn't fully support Web Components and they are disabled by default. It's same as #2132.
