### ISSUE TITLE
Formatting error on mandarake.co.jp

### ISSUE THREAD

**Issue by chrisrtxv** [MrAlex94/Waterfox#2165]
### What happened?

Mandarake is a Japanese secondhand store. I've found since updating to 3.2.3 that product search pages no longer format correctly. [This page can be used as a representative example](https://order.mandarake.co.jp/order/listPage/list?categoryCode=02) What should be happening is products in squares populating the field to the right of the sidebar menu. Instead, the product listings are stretched out to many times the width of the window itself, and pushed below the sidebar content, making any page like this functionally unreadable.

I've checked this in safe mode, but the issue persists so I've ruled out addons being at fault. I've also been able to check this on Chrome and the pages display normally, and as expected, so I don't think it's a newly introduced error from any change to the site itself. I've only updated in to 3.2.x in the last few days, so I'm unsure if this occurred in the immediately prior releases, but I can confirm that the pages had been displaying correctly in 3.1.x. Updating to 3.2.4 today has had no effect on the issue.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
This seems to have been resolved in G4 -  I have compared it to Firefox and both seem to render the same.
