### ISSUE TITLE
Waterfox Support for OpenSuse Leap 15.3 (current release of OpenSuse)

### ISSUE THREAD

**Issue by FranzGotsis** [MrAlex94/Waterfox#2167]
This is a request for hawkeye:

Your service for OpenSuse using the Open Build Service runs very well. At the moment it just does not include OpenSuse Leap 15.3 which is the latest stable release of OpenSuse.

I would be very grateful for a "classic" and a "g3 current" release of Waterfox running on OpenSuse.

If there is any way that I can help to make this happen let me know.

Kind Regards from Munich, Germany

**Comment by hawkeye116477** [comment]
Then I'm inviting you to https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/issues :smile:

**Comment by FranzGotsis** [comment]
Hello Hawkeye,

this is a workable feature (I know), but I still do like the rpm-packaging, that you have done so well those past years as it integrates into the system and the update procedures. I know that there are workarounds for app images.

In fact there should be only a small a amount of changes necessary (compared with OpenSuse Leap 15.2), as the base libraries of OpenSuse Leap 15.2 and 15.3 are quite similar and as far as I understand the changes are backwards compatible.

I know that I am asking a lot. In case I can contribute to make that happen, I am happy to help.

kind regards

**Comment by hawkeye116477** [comment]
Well, I wanted to say that linked place is dedicated for submitting issues with my Waterfox repositories.

Anyway, package is done. instructions are under SLE (I know should be under openSUSE, seems that some bug on OBS side).

**Comment by FranzGotsis** [comment]
Sorry, it took me a while to understand:

I found the package under Suse Linux Enterprise (SLE) which was correctly labelled for OpenSuse Leap 15.3 (which is identical to Suse Linux Enterprise - as one of the changes to the OpenSuse project).

As the package does not show up directly using OpenSuse Leap 15.3 I got the wrong impression that there is no package for that release.

Maybe you could add some information on the waterfox Internet-Site. If I would look for the package I would check the OpenSuse Build Service and if I do not find anything I would look for hints on the waterfox site. That leads to the wrong impression that there are no Waterfox packages, which is untrue.

In fact anything works as expected once I include the proper repository. The way to upgrade an OpenSuse Leap 15.2 installation to Leap 15.3 is therefore a bit more cumbersome, as the automatic switch to the new release (zypper dup --releasever=15.3) will not work with waterfox. The proper procedure is to delete the waterfox repository from the list of trusted repositories, upgrade the Version of OpenSuse Leap 15.2 to Leap 15.3 and the include the repository of Waterfox from your site
https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-g3-kpe
and things work as before.

I hope that the project is maintained as before and that you keep doing this work as it facilitates the usage of waterfox on OpenSuse (and I guess on a number of other platforms, too).

kind regards from Munich, Germany

**Comment by hawkeye116477** [comment]
> Maybe you could add some information on the waterfox Internet-Site

I'm not belonging to Waterfox team, so I can't add information to `https://www.waterfox.net/` site. I can only promote it on reddit and http://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage :smile:
