### ISSUE TITLE
[Classic] Text fields have invisible borders on 2021.07

### ISSUE THREAD

**Issue by reallyuniquename** [MrAlex94/Waterfox#2168]
### Summary

After updating Waterfox Classic to 2021.07 on one of my Windows machine I noticed that some textfields no logner have any visible borders (`<input>`, `<textarea>`). It happens only if page doesn't specify any related styles so the issue is probably with `-moz-appearance`. 

If I click on any field its borders become visible for a moment with the correct style. If I set `background-color` to something like `white` then borders appear too but with a weird style.

### Notes

I remember seeing a lot of related commits in June. Now this is either completely borked for Windows or for some reason Waterfox started to pull wrong colors and/or style from the system theme.

I went through the `-moz-appearance` options and setting it to `menulist-button` shows the correct styling for text fields but it has some unwanted side effects like extra padding. So at least one of the options gets it right.

### To Reproduce

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_test
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea

![image](https://user-images.githubusercontent.com/10516120/126061078-d640d913-bfb5-479a-994b-4121d1876635.png)

**Comment by MrAlex94** [comment]
PR that should fix this has been merged.
