### ISSUE TITLE
The following CA certs have expired and can be removed

### ISSUE THREAD

**Issue by david-dick** [MrAlex94/Waterfox#2173]
### What happened?

The following CA certs have expired and can be removed from waterfox

AddTrust External Root expired on Sat May 30 20:48:38 2020
AddTrust Low-Value Services Root expired on Sat May 30 20:38:31 2020
QuoVadis Root CA expired on Thu Mar 18 05:33:33 2021
Sonera Class 2 Root CA expired on Tue Apr  6 17:29:40 2021
Staat der Nederlanden Root CA - G2 expired on Wed Mar 25 22:03:10 2020

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
This should be done in G4 now 👍
