### ISSUE TITLE
Cant see the search bar - Classic 2021-7

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2176]
### What happened?

I cant see the search bar below the "ROMs / Search for a specific ROM:" in the site https://edgeemu.net/ - this worked in the previous version and it works on firefox 90.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Killogy** [comment]
It works for me. https://imgur.com/0EYe1Ei

**Comment by Killogy** [comment]
its there if you click on it, simply search box border is missing or is transparent, when you click then search border appear.

**Comment by Felipefpl** [comment]
I know but still a bug. ;)

**Comment by hawkeye116477** [comment]
It's duplicate of #2168.
