### ISSUE TITLE
"New Window" opens large.

### ISSUE THREAD

**Issue by dallas6672** [MrAlex94/Waterfox#2178]
### What happened?

If I go to "File" > "New Window" or "New Private Window", the new window that opens is much larger than my original Waterfox window. Also occurs if I right click the pinned Taskbar icon and choose "New Window" or "New Private Window".

When I open Waterfox up normally, the first window opens up to it's previously saved size like expected. Tried recreating the "xulstore.json" file but issue still occurs.

Noticed after upgrading to G3.2.4.1

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
G4 no longer appears to have this issue. Please re-open if you are still faced with it.
