### ISSUE TITLE
Waterfox classic 2021-7 crashes in this site

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2179]
### What happened?

waterfox crashes on https://www.solasta-game.com/ - not only the tab where the site is loaded crashes but all other opened tabs crash too. The site works flawlessly on firefox.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Killogy** [comment]
I tested and banner animation is the culprit so using Ublock Origin and blocking https://www.solasta-game.com/storage/337/ta-banner-animation-2021-6.mp4 fixes the crashing.

**Comment by Felipefpl** [comment]
> I tested and banner animation is the culprit so using Ublock Origin and blocking https://www.solasta-game.com/storage/337/ta-banner-animation-2021-6.mp4 fixes the crashing.

I see but why it doesnt crash firefox?

**Comment by Killogy** [comment]
Because Waterfox Classic is obsolete, maybe can´t be fixed because maybe is not a problem related of security updates.

I tested Waterfox 2020.10 and problem is happening too.

**Comment by hawkeye116477** [comment]
Looks like it's only on Windows and toggling `media.wmf.enabled` to false and enabling VLC plugin to play video prevents crashing too.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
> 
> 
> I tested and banner animation is the culprit so using Ublock Origin and blocking https://www.solasta-game.com/storage/337/ta-banner-animation-2021-6.mp4 fixes the crashing.

This video also does not play on Firefox 90, web console shows the error "Can't decode H.264 stream because its resolution is out of the maximum limitation". Found details on [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1427280#c4):

> On Windows, we cannot play this video because it exceeds the resolution limit (4092 x 2304 pixels). 
MS spec: https://msdn.microsoft.com/en-us/library/windows/desktop/dd797815(v=vs.85).aspx

**Comment by hawkeye116477** [comment]
From my analyze looks like that it could crash because incomplete work for fixing Bug 1397141 done by MrAlex94.

**Comment by Felipefpl** [comment]
I dont know if this is related but the same things happens here https://www.krafton.com/en/index.html - i didnt want to create a new thread because this could be the same error, or not.

**Comment by hawkeye116477** [comment]
@Felipefpl I can't reproduce that.

**Comment by Felipefpl** [comment]
> @Felipefpl I can't reproduce that.

Strange, i got the same crashes here but it worked on firefox.
