### ISSUE TITLE
Cannot switch to Light/Dark theme after G3.2 update

### ISSUE THREAD

**Issue by zethriller** [MrAlex94/Waterfox#2186]
### What happened?

Description of bug:
Trying to switch to Light/Dark theme doesn't work, instead it throws an error in the browser console.
(See log output below)

Restarting with addons disabled have no effect.
This profile has been in use since G3.0.0, and i noticed this bug since G3.2.0 as far as i can remember.
On my other machine, the profile in use is much more recent, and the bug cannot be reproduced on this one.

Steps to reproduce:
- Open the addons manager, themes tab
- Try to switch from Default, Abyss or Floe to Light or Dark

Any clue on how to deal with this without recreating a new profile (if possible) please ?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Uncaught (in promise) TypeError: addon.userPermissions is null
    shouldShowPermissionsPrompt chrome://mozapps/content/extensions/aboutaddonsCommon.js:156
    handleEvent chrome://mozapps/content/extensions/aboutaddons.js:2821
    registerListeners chrome://mozapps/content/extensions/aboutaddons.js:3024
    connectedCallback chrome://mozapps/content/extensions/aboutaddons.js:2753
    show chrome://mozapps/content/extensions/aboutaddons.js:4577
    show chrome://mozapps/content/extensions/extensions.js:557
    loadViewInternal chrome://mozapps/content/extensions/extensions.js:451
    loadView chrome://mozapps/content/extensions/extensions.js:361
    loadViewFn chrome://mozapps/content/extensions/extensions.js:494
    handleEvent chrome://mozapps/content/extensions/aboutaddons.js:2952
    registerListeners chrome://mozapps/content/extensions/aboutaddons.js:3024
    connectedCallback chrome://mozapps/content/extensions/aboutaddons.js:2753
    show chrome://mozapps/content/extensions/aboutaddons.js:4577
    show chrome://mozapps/content/extensions/extensions.js:557
    loadViewInternal chrome://mozapps/content/extensions/extensions.js:451
    loadView chrome://mozapps/content/extensions/extensions.js:361
    loadViewFn chrome://mozapps/content/extensions/extensions.js:494
    load chrome://mozapps/content/extensions/aboutaddons.js:1659
    initialize chrome://mozapps/content/extensions/aboutaddons.js:1758
    initialize chrome://mozapps/content/extensions/aboutaddons.js:1755
    initialize chrome://mozapps/content/extensions/aboutaddons.js:4521
    _htmlBrowserLoaded chrome://mozapps/content/extensions/extensions.js:531
    promise callback*getHtmlBrowser chrome://mozapps/content/extensions/extensions.js:530
    initialize chrome://mozapps/content/extensions/extensions.js:551
    initialize chrome://mozapps/content/extensions/extensions.js:272
    initialize chrome://mozapps/content/extensions/extensions.js:51
    EventListener.handleEvent* chrome://mozapps/content/extensions/extensions.js:24
aboutaddonsCommon.js:156:36
```

**Comment by Killogy** [comment]
It woks properly for me, I´m using Abyss theme and I can switch between them.

Maybe you can test it by creating a new Waterfox profile, if it works then restores copy/paste multiples files from your other profile (current profile) to the new one to know which file is the culprit.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1647931
As noted in the bug this should not affect the current version, but apparently it happens.

**Comment by zethriller** [comment]
Thank you for the bug report reference.
As stated in comment 7 i was able to fix it by editing my profile extensions.json, replacing each occurence of:
```
"userPermissions": null,
"optionalPermissions": null,
```
to:
```
"userPermissions": {
  "permissions": [],
  "origins": []
},
"optionalPermissions": {
  "permissions": [],
  "origins": []
},
```

--> Solved
