### ISSUE TITLE
Waterfox Classic crashes when microphone is used

### ISSUE THREAD

**Issue by Vulpovile** [MrAlex94/Waterfox#2194]
### What happened?

Visiting https://www.midomi.com/ or BlackBoard collaborate causes waterfox classic to crash.

### Reproducible?

- [x] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Vulpovile** [comment]
Does not happen in firefox.

**Comment by hawkeye116477** [comment]
Some people some time ago reported similar thing and maybe that depends on hardware, cuz I can't reproduce that.

**Comment by Vulpovile** [comment]
> 
> 
> Some people some time ago reported similar thing and maybe that depends on hardware, cuz I can't reproduce that.

I will see if I can figure out exactly what causes it, what kind of hardware, os, etc.
I am experiencing this on Windows 7 64 bit with an i5-2500K, GTX 970 and 16GB RAM

**Comment by Squall-Leonhart** [comment]
update your sound driver for the device.

don't use any recording enhancements in the driver.
