### ISSUE TITLE
Waterfox G3.2.4.1 cannot open a tab Fedora Rawhide

### ISSUE THREAD

**Issue by usdanskys** [MrAlex94/Waterfox#2195]
### What happened?

This is with Fedora Rawhide updated on 3-Aug-2021. I set up a new profile. Upon first run, the tab shows "Tab crash reporter" and on the page, I see the lines below. The URL bar shows https://www.waterfox.net/blog/waterfox-G3.2.4.1/?new Any entry in the address bar produces a crashed tab as below
Waterfox G3.2.4.1 works properly on Fedora 34. Waterfox-Classic works properly with Fedora Rawhide. Firefox 90.0.2 works properly (am using it to file this bug) Not sure where to find the appropriate logs.

========================
   Gah. Your tab just crashed.
   We can help!
   
   Choose Restore This Tab to reload the page.Gah. Your tab just crashed.
   We can help!

   Choose Restore This Tab to reload the page.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux

**Comment by hawkeye116477** [comment]
What error is when you open it from console?

**Comment by usdanskys** [comment]
Not sure what's important, so here is the full output when starting Waterfox G3.2.4.1 from the terminal

[msgs_from_terminal.txt](https://github.com/MrAlex94/Waterfox/files/6932839/msgs_from_terminal.txt)

**Comment by usdanskys** [comment]
I did a strange thing today. I decided to make a copy of the profile that works with the latest Waterfox-Classic and try it with Waterfox G3.2.4.1. Guess what? It works. So I tried created a new profile before starting G3.2.4.1 in case something on my system had changed. G3.2.4.1 doesn't work with the new profile.
