### ISSUE TITLE
Close tabs on the Left

### ISSUE THREAD

**Issue by koplenov** [MrAlex94/Waterfox#2203]
I often use the "close right tabs" or "close other tabs" function, but when I should close only and only tabs on the left, I find that I cannot do it from the same menu, why?

The lack of this feature is especially acute when you open a hundred other tabs...

If we have this drop-down menu, then why don't we have "Close tabs on the Left"?

Hey, maybe after all these years this will finally show up? :D

Context:
![image](https://user-images.githubusercontent.com/25139987/128701364-292ebd58-d6b9-4d14-987a-cb803c068fc9.png)

Heart-cry

**Comment by hawkeye116477** [comment]
There are extensions on AMO to do that.

**Comment by koplenov** [comment]
Can I have more details about AMO?

**Comment by hawkeye116477** [comment]
@koplenov https://addons.mozilla.org/firefox/addon/close-tabs-left/

**Comment by koplenov** [comment]
That is, solve it through an extension - okay.

At the same time I ask if there is a simple way to make the Pocket extension work?
Ideally, a version from Firefox.

**Comment by krystian3w** [comment]
> Close tabs on the Left

Maybe out of the box in WaterFox G3 based on Firefox 91 ESR or Firefox 103/106 ESR?

Now I can't found source who added this into Firefox 88 code.


---

> Pocket extension work?

If last WebExtension addon no longer works (https://www.reddit.com/r/firefox/comments/3ackbm/pocket_306_download_for_those_who_want_the/ - maybe last liked version) may need backport chrome addon or backport few code from Firefox without cut.

**Comment by hawkeye116477** [comment]
> Now I can't found source who added this into Firefox 88 code.

Well, it's on https://bugzilla.mozilla.org/show_bug.cgi?id=1009728 :smile:

**Comment by MrAlex94** [comment]
This is now in G4 :-)
