### ISSUE TITLE
Could we get Pointer Events support for classic?

### ISSUE THREAD

**Issue by Megalomaniak** [MrAlex94/Waterfox#2217]
**Is your feature request related to a problem? Please describe.**
Pen tablet pressure doesn't work and sites/web applications have to fall back to using a polyfill that lerps time as pressure.

**Describe the solution you'd like**
For the `dom.w3c_pointer_events.enabled` that's been in `about:config` since ff 28 to be turned into a fully fledged non beta feature.

**Describe alternatives you've considered**
There is nothing. Waterfox classic is the only browser I'm willing to even poke with a stick from a distance. There are no alternatives. NaN.

**Additional context**
I want my pen tablets pressure to be used via pointer events instead of a polyfill lerping time so I could use my pen tablet in photopea. Photopea uses pressurejs library for pressure support however the pressurejs library seems to not look for whatever is the result of enabling `dom.w3c_pointer_events.enabled` in `about:config` thus falling back on that infuriating polyfill.

**Comment by hawkeye116477** [comment]
It's already supported and enabled by default, but Pointer Events API is huge and even Firefox hasn't implemented all things from it.

**Comment by Megalomaniak** [comment]
Yeah after further tests I couldn't get it working in chromium or opera either. I do have ink enabled(necessary for browsers to even work with the wacom at all) and I know that pressure works in ink - pressure for brush size works in windows sticky notes and pen input wouldn't even be offered if ink was off.

**Comment by MrAlex94** [comment]
I don't think a full implementation will realistically come to Classic. The workload would be huge.
