### ISSUE TITLE
[WaterFox Classic] Unsupported JS functions/API ? - (Make an userscript Unusable with Waterfox Classic)

### ISSUE THREAD

**Issue by decembre** [MrAlex94/Waterfox#2221]
### What happened?

It's related to this userscript:
<a href="https://greasyfork.org/fr/scripts/423851-simple-youtube-age-restriction-bypass">Simple YouTube Age Restriction Bypass</a>
After a test, i see it don't work with Waterfox Classic, but work fine with Firefox Quantum.

My report to the author:
Script not working for:
https://www.youtube.com/watch?v=DAsZjMizTJ0

1- (v.2.1.3 + Greasmonkey + Firefox Classic v.56.5):
go to the login page...

2 - (v.2.1.3 + Tampermonkey + Firefox Classic v.56.5):
Stay on the video ... but don't do nothing...

But....
3- v.2.1.3 work fine with Firefox Quantum + Tampermonkey:
play the video.

Its author said:
"Yeah, now looks like no supported JS functions/API.
Waterfox Classic 2021.04 (aka 56.5) maybe no backported needed new Javascript features."

Can you do something about this problem ?

Read the whole discussion:
<a href="https://greasyfork.org/fr/scripts/423851-simple-youtube-age-restriction-bypass/discussions/93645">Waterfox Classic 2021.04 (aka 56.5) maybe no backported needed new Javascript features.</a>
Note:
Sorry, i don't see where to add bugs for classic.....

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by decembre** [comment]
Read too from zerodytrash, the developer of "Simple YouTube Age Restriction Bypass":
<a href="https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/57">Yes, thats because Waterfox Classic doesn't support ECMAScript 2020 features like &quot;optional chaining&quot; used by this script :(</a>

**Comment by hawkeye116477** [comment]
Well, officially for Classic won't be any new features unless external contributors will make PR for it.

**Comment by Felipefpl** [comment]
> Well, officially for Classic won't be any new features unless external contributors will make PR for it.

I know it's off-topic but i didnt want to create a thread for this: the next classic release will be updated to 91.02 ESR? It would be nice to have all features that firefox got on waterfox.

**Comment by hawkeye116477** [comment]
> the next classic release

No, Classic is and still will be separate. Release based on next ESR will be rather called G4 or something like that.
Anyway, GH is not the best place for that discussions. I'm inviting you to reddit.

**Comment by Felipefpl** [comment]
i see, thanks for the reply.

**Comment by krystian3w** [comment]
Existing label "`PR wanted`"?

**Comment by c33s** [comment]
> Anyway, GH is not the best place for that discussions. I'm inviting you to reddit.

why not use github discussions?

**Comment by krystian3w** [comment]
Not enabled on this repo:

* https://github.com/WaterfoxCo/Waterfox/discussions = error 404

* [../discussions](../discussions "now: 'https://github.com/WaterfoxCo/Waterfox/discussions'") = error 404, "`../`" should works without HTTP redirect 3xx after repo or organization try change name into new

**Comment by hawkeye116477** [comment]
@c33s Owner said some time ago that there are too much places, so he doesn't want to add next one. Reddit also works better on WF Classic, doesn't need webcomponents.

**Comment by decembre** [comment]
About this problem, it seems they find a working solution for Waterfox Classic too!
read;
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/57
