### ISSUE TITLE
When I click on a link, it is always the same page that appears.

### ISSUE THREAD

**Issue by OursBlanc42** [MrAlex94/Waterfox#2225]
### What happened?

A bug happened!
Hi there. Excuse my ignorance with waterfox , comptuer, and github.

Since few days, each time i click on a link (from discord, from my email, or steam...) ; I always get the same page. (an article on a geek news site I visited several weeks ago)

For example, if i click on link like : https://www.google.com 

I don't arrive on the google site, but on the article I quoted above.
It does that regardless of the link.
I tried to reinstall Waterfox without success.

do not hesitate to ask me for more information;

regards

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
@OursBlanc42 - could you upgrade to G4 and see if this issue still occurs?
