### ISSUE TITLE
CSS rendering is weird in 2021.08, and some Add-ons are disabled.

### ISSUE THREAD

**Issue by beehiveharvest** [MrAlex94/Waterfox#2226]
### What happened?

After upgrading to Waterfox 2021.08, Google's image search and other sites with tiled images are not displayed properly.

Also, some Add-ons are disabled (Add-ons that were working fine until 2021-07). There is no way to enable them.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by beehiveharvest** [comment]
P.S.
The above bug report is for Waterfox 2021.08.

**Comment by hawkeye116477** [comment]
> Google's image search and other sites with tiled images are not displayed properly

For me it looks fine. Can you give some URL and screenshots? 

> There is no way to enable them.

Just go to `about:config` and create `extensions.checkCompatibility.56.6` boolean pref with value `false`.

**Comment by beehiveharvest** [comment]
I downloaded the new version of **Waterfox 2021.08.1** today.

The bugs I was encountering, the tiling of Google Image Search and other sites' images, plus the problem of Add-ons being disabled, have been resolved.

Thanks to the author!
