### ISSUE TITLE
[SOLVED][CLASSIC] 2021.08 Mac-Version doesn't launch at all

### ISSUE THREAD

**Issue by LeeBinder** [MrAlex94/Waterfox#2228]
### What happened?

So we're requested to not post classic bugs anymore? I dare say, if the error is, `The application “Waterfox Classic” can’t be opened` anymore at all, that's more than a bug.

Tested in macOS Big Sur, Catalina, Mojave

Reproduced by not just me, but also by at least one other user, see https://www.waterfox.net/blog/waterfox-2021.08-release/#commento-login-box-container

Suggestion by hawkeye116477: 

> ask @MrAlex94 about it, probably he needs to tweak config for GH Actions.

### Reproducible?

- YES

### Version

CLASSIC 2021.08

### What platform are you seeing the problem on?

macOS

### Relevant log output

```shell
.
```

**Comment by MrAlex94** [comment]
https://cdn.waterfox.net/releases/osx64/installer/Waterfox%20Classic%202021.08.1%20Setup.dmg

**Comment by LeeBinder** [comment]
Thank you @MrAlex94 - u da man 👍
