### ISSUE TITLE
Cosmetic bug: The tags' colors aren't displayed correctly (Waterfox Classic)

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2231]
### What happened?

I reported this to github because i thought it was a bug from the site (to my shame it wasnt their fault): the color of the tags are displayed differently in waterfox and firefox, here is how it's displayed on waterfox:

https://www.hostpic.org/images/2108271729260329.gif

And here is how they are seen in firefox 91:

![Sem título](https://user-images.githubusercontent.com/5569804/131698038-59b6d4e0-fead-4b02-8c76-1cc191f558de.gif)

As you can see (or not) they are hard to see on waterfox.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by hawkeye116477** [comment]
> G3.𝑋 (Current)

You forgot to write/edit that's only on Classic, not on G3. Well, it's CSS problem, GH uses new feature. I'll answer for MrAlex => this won't be fixed unless someone will provide Pull Request, cuz official team unfortunately have another plans than Moonchild and only wants to provide security fixes for Classic and new features only mainly by Mozilla in new ESR releases in Waterfoxes called G3/G4/G5, etc. Well, there are only 2 people in team, Moonchild have more.

**Comment by Felipefpl** [comment]
> You forgot to write/edit that's only on Classic, not on G3.

Yeh, sorry for that, there isnt this option in the drop-down box so i wrote in the title of the issue.

> Well, it's CSS problem, GH uses new feature. I'll answer for MrAlex => this won't be fixed unless someone will provide Pull Request, cuz official team unfortunately have another plans than Moonchild and only wants to provide security fixes for Classic and new features only mainly by Mozilla in new ESR releases in Waterfoxes called G3/G4/G5, etc. Well, there are only 2 people in team, Moonchild have more.

I see, i hope more ppl will come in the future then, plz dont close this, perhaps someone will come to fix it. Thanks for the infos.

**Comment by hawkeye116477** [comment]
> there isnt this option in the drop-down box so i wrote in the title of the issue.

Well, you could just also click three dots to edit your post :smile: Drop-down appears only one time, after you submit post, it's possible to edit and replace values with whatever you want.

**Comment by Felipefpl** [comment]
> Well, you could just also click three dots to edit your post smile Drop-down appears only one time, after you submit post, it's possible to edit and replace values with whatever you want.

Not that, i meant the drop-down box where you select between versions G 3x or G 4x. ;)

**Comment by hawkeye116477** [comment]
> meant the drop-down box where you select between versions

I talked about the same, it only appears one time when opening issue, then after submitting you can click three dots to edit your post and replace all with whatever you want.

In case of that colors, problems is seems that Classic doesn't support min/max for colors (https://bugzilla.mozilla.org/show_bug.cgi?id=1609428 - seems Servo-only).

**Comment by Felipefpl** [comment]
i see, is it something easy to fix?

**Comment by MrAlex94** [comment]
Unfortunately not - unless someone submits a patch for this is won't be done. There were quite a few changes between Gecko 56 -> 74.

**Comment by Felipefpl** [comment]
> Unfortunately not - unless someone submits a patch for this is won't be done. There were quite a few changes between Gecko 56 -> 74.

a pity, i hope someone will take care of this in the future.
