### ISSUE TITLE
Where to find the browsers web apis?

### ISSUE THREAD

**Issue by Osiris-Team** [MrAlex94/Waterfox#2236]
I browsed the source code but I couldn't find the javascript browser apis which get loaded into the javascript context before loading a page. Any ideas where to find them?
Examples for browser apis:
```js
document.findByElementId('id');
console.log('Something');
```

**Comment by MrAlex94** [comment]
Do you mean the [Web APIs](https://developer.mozilla.org/en-US/docs/Web/API) (the same feature level available to Firefox 78) or the actual privileged browser APIs which are only available to the browser itself and not websites?

**Comment by Osiris-Team** [comment]
@MrAlex94 Yes I guess its web apis then.

**Comment by MrAlex94** [comment]
Okay, that link should suffice then. Just look for compatibility with Firefox 78.

**Comment by Osiris-Team** [comment]
@MrAlex94 I meant in the source code of this repository.
