### ISSUE TITLE
Waterfox G3 display issues with shoppinglist.google.com

### ISSUE THREAD

**Issue by ChooChooAl** [MrAlex94/Waterfox#2240]
### What happened?

I've moved to waterfox browser on Linux.
Linux Mint 20.2
![waterfox](https://user-images.githubusercontent.com/26556059/132576741-28e35ee5-02e0-48e3-8ea4-554314f1efe7.png)

Issue is with https://shoppinglist.google.com
When your add-on is installed I get the following display that is distorted.  Note words "menu" (top left should be hamburger type menu), "add"  (center), user account logo (probably alternate text),  and "chevron_right" (probably alternate text).. 

![Shopping List](https://user-images.githubusercontent.com/26556059/132576791-ac3ac82c-76e8-4df0-9c4f-6239e87a0993.png)

This is what Firefox does.  Which is what I think it should be.
![Shopping list FF](https://user-images.githubusercontent.com/26556059/132576872-daed2b3d-8d69-4326-82b7-820afd863d77.png)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux

**Comment by ChooChooAl** [comment]
Additional Info.  I have an add-on called 'localcdn' that if removed will fix the issue.   It shouldn't as you can see from the firefox screenshot that it works over there with localcdn installed.

**Comment by InvisibleManX** [comment]
I have issues with weather.com as well! 

When loading 10 days or hourly tabs for some locations (not for all) they just disappear, as if collapse into nothing after a few seconds, for no reason at all. 

Same in Firefox of the same version Waterfox is built upon. The site worked just fine before. And yes, I disabled all addons before testing. I think weater.com updated something and now doesn't support older versions of Firefox (and Waterfox G3) properly.

**Comment by MrAlex94** [comment]
Since G4 this bug should not be appearing anymore.

> Additional Info. I have an add-on called 'localcdn' that if removed will fix the issue. It shouldn't as you can see from the firefox screenshot that it works over there with localcdn installed.

Could be a case of localcdn not supporting some newer features of the libs it has.
