### ISSUE TITLE
Wordpress doesnt work like it should

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2244]
### What happened?

Go here https://wordpress.com/ and click in "start your website", a msg will come saying that there is no support for waterfox. After clicking to continue you'll be stuck in this webpage with this view:

![Sem título](https://user-images.githubusercontent.com/5569804/132892138-3d14fd40-51bf-4fc0-88d0-269faaf8b900.gif)

Instead you should be seeing this one:

![Sem título](https://user-images.githubusercontent.com/5569804/132892226-6623d26c-274e-487b-b36c-b147fb39f8a1.gif)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Waterfox Classic 2021-8

### What platform are you seeing the problem on?

Windows

**Comment by hawkeye116477** [comment]
It's probably because Classic doesn't support one of the [ES2020 proposals](https://repo.palemoon.org/MoonchildProductions/UXP/issues/1734).

**Comment by Felipefpl** [comment]
> It's probably because Classic doesn't support one of the [ES2020 proposals](https://repo.palemoon.org/MoonchildProductions/UXP/issues/1734).

I see, btw, i found another site with a problem:

https://gettr.com

Waterfox doesnt display anything here, the site works fine on firefox.

**Comment by Felipefpl** [comment]
Why this was closed? I dont see a commit where these problems were fixed.

**Comment by hawkeye116477** [comment]
@Felipefpl Official statement is that Classic will receive only security fixes. Other features may be provided only by external contributors through Pull Request.

**Comment by Felipefpl** [comment]
> @Felipefpl Official statement is that Classic will receive only security fixes. Other features may be provided only by external contributors through Pull Request.

hawkeye - I understand, it's a pity :/ - thanks for the reply.
