### ISSUE TITLE
Waterfox classic 2021-9 doesnt work on Win7

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2252]
### What happened?

I installled over waterfox classic 2021-8 and i also made a clean install of the latest version and the browser doesnt start. I had to re-install the previous version over the old installation to make it work again.

### What platform are you seeing the problem on?

Windows

**Comment by Squall-Leonhart** [comment]
Works fine, you're most likely using a version of windows 7 that hasn't been updated since jan 2020 and thats the problem.

![image](https://user-images.githubusercontent.com/1098176/134633355-f372a713-5252-4507-967f-4a00d067d632.png)

**Comment by Felipefpl** [comment]
i'm using the most updated version and like i said i tried 2 installs with no success, also, when i go to about box i see that waterfox cant detect the 2021-9 version and the "what's new" link points to august's version.
