### ISSUE TITLE
Classic 2021.08.01 Can't type in comment or reply fields on Facebook

### ISSUE THREAD

**Issue by SPWGitHub** [MrAlex94/Waterfox#2254]
### What happened?

Can't type in comment or reply fields on Facebook. No text or space appears.  Key presses aren't recognized.

### Reproducible?

- [X] I have tested this on Firefox.  Not reproducible. Not reproducible on G4.x either.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows 10 x64

**Comment by SPWGitHub** [comment]
Also happens on V. 2021.09

**Comment by NoNameNeeded2000** [comment]
It's exactly the same with Waterfox Classic.

**Comment by SPWGitHub** [comment]
> It's exactly the same with Waterfox Classic.

This bug report **_is pertaining to Waterfox Classic_**

**Comment by NoNameNeeded2000** [comment]
Right, but you also wrote G4 as the version that is affected so I was a little confused.

Anyway, it doesn't work with Waterfox Classic and it's been like that for months, if I remember correctly, so it's about time to find a solution.

**Comment by SPWGitHub** [comment]
I discovered a workaround for this!!

Paste any character into the comment or reply field and you can type! (as long as you don't delete that character first, but you can highlight and replace it.) 

You can also use the "Reply" button to insert a tag, or you can insert an emoji.  As long as **_something_** exists in the field, you can type.

**Comment by MrAlex94** [comment]
Please stop reporting bugs around Classic - this has been noted for a while and I doubt an easy solution will be found.
