### ISSUE TITLE
[Classic] getTransceivers is not a function

### ISSUE THREAD

**Issue by hockeymikey** [MrAlex94/Waterfox#2257]
### What happened?

Trying to use Discord voice channels and the RTC will not connect. I get the following error "getTransceivers is not a function" in console and seems to be the issue. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
TypeError: i.getTransceivers is not a function
```

**Comment by hawkeye116477** [comment]
See https://repo.palemoon.org/mcp-graveyard/UXP/issues/1764. It could be a lot of work to fix that. You can make PR if you want, but maybe better would be using Discord app instead of :smile:.
