### ISSUE TITLE
Odd behaviors

### ISSUE THREAD

**Issue by q64ceo** [MrAlex94/Waterfox#2258]
### What happened?

Two annoying bugs are about as annoying as a fly that just wont go away!

1. The search bar keeps on adding itself back to the navigation bar. Even after I have both removed it via "customize toolbar" and checked the I only want the address bar in preferences it still comes back. EDIT: after I clicked on "add comment" the search box is back LOL.

2. First letter of Facebook posts for replies moves itself to the end of the line. Here is an animated GIF that shows you what I mean: https://ibb.co/z6DfKdH

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
@q64ceo - G4 should have resolved these issue (I've tested out the Facebook and removing the search bar). Please re-open if still facing them!
