### ISSUE TITLE
Please update bootstrap loader for legacy extension to newerst version

### ISSUE THREAD

**Issue by 117649** [MrAlex94/Waterfox#2264]
The bootstrap loader have under go many updates. Waterfox should just catch on. This fall behind already cause some extension can't be update to its newest version.

**Comment by 117649** [comment]
https://github.com/WaterfoxCo/Waterfox/issues/2098

Same problem all goes back to G3.

Please at least fix this in G4.

@adamp01 @MrAlex94 @hawkeye116477 

literally no work required just use the new version of the file.

**Comment by adamp01** [comment]
@117649 

Please can you direct me to a download of the addon you are trying to install here. I can then make sure that the updated boostrap loader is working as intended before I PR for this.

**Comment by 117649** [comment]
@adamp01 
https://github.com/p1usminus/roomybookmarksredux/releases/latest
https://github.com/117649/SavedPasswordEditorRedux/releases/latest
https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions

**Comment by adamp01** [comment]
@117649 

I had a quick look into this yesterday and adding the additional lines for optionsType caused a very unhelpful error to be thrown. It'll take some time to delve into this and I currently have quite a few higher priorities, but I will get around to it. 

If you want to have a crack at it all the BootstrapLoader code is in `browser/components/extensions/common`, and it is registered with the AddonManager in `browser/components/BrowserGlue.jsm#1014`.

**Comment by 117649** [comment]
> I had a quick look into this yesterday and adding the additional lines for optionsType caused a very unhelpful error to be thrown. 

@adamp01 
Can you describe what the error is?

**Comment by 117649** [comment]
https://github.com/WaterfoxCo/Waterfox/pull/2328
@adamp01 @MrAlex94 @hawkeye116477

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/2ed42c3d1a4ba955aeae11b74b129a0b365909ae
