### ISSUE TITLE
Waterfox unusable Ubuntu 21.10 beta

### ISSUE THREAD

**Issue by q64ceo** [MrAlex94/Waterfox#2267]
### What happened?

Tabs are crashing before I even have a chance to load anything.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
notsure@notsure-ASUS-TUF-Gaming-A15-FA506IU-TUF506IU:~$ /usr/local/lib/waterfox/waterfox
console.log: "Loaded BootstrapLoader"
*** UTM:SVC TimerManager:registerTimer - timerID: xpi-signature-verification interval: 86400 skipFirst: false
*** UTM:SVC TimerManager:registerTimer - timerID: browser-cleanup-thumbnails interval: 3600 skipFirst: false

###!!! [Parent][MessageChannel] Error: (msgtype=0x390074,name=PContent::Msg_LoadURI) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x39004B,name=PContent::Msg_UnregisterSheet) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x39004B,name=PContent::Msg_UnregisterSheet) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x39004A,name=PContent::Msg_LoadAndRegisterSheet) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x39004A,name=PContent::Msg_LoadAndRegisterSheet) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x210054,name=PBrowser::Msg_UpdateEffects) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x21006F,name=PBrowser::Msg_UpdateDimensions) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x210054,name=PBrowser::Msg_UpdateEffects) Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

[Parent 4376, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /home/notsure/Desktop/Waterfox/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 19

###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

[Parent 4376, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /home/notsure/Desktop/Waterfox/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 19

(waterfox:4376): LIBDBUSMENU-GTK-CRITICAL **: 03:16:03.766: dbusmenu_menuitem_property_set_shortcut: assertion 'gtk_accelerator_valid(key, modifier)' failed
JavaScript error: resource:///modules/ContentCrashHandlers.jsm, line 50: TypeError: can't access property "permanentKey", browser is undefined
*** UTM:SVC TimerManager:notify - fire timerID: browser-cleanup-thumbnails intended time: 3600 (1970-01-01T01:00:00.000Z)
*** UTM:SVC TimerManager:notify - notified timerID: browser-cleanup-thumbnails
```
EDIT: Tested Classic, getting same results with the log showing the following

###!!! [Parent][MessageChannel] Error: (msgtype=0x150079,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

**Comment by hawkeye116477** [comment]
What libc6 version you have? I assume that's probably 2.34, so that's why you got a problem, right?

Seems that unfortunately Mozilla didn't added patches for that to ESR 78. 

I had problems with compiling it even on Fedora Rawhide, but found patches which I'm using now:
* https://src.fedoraproject.org/rpms/icecat/blob/rawhide/f/icecat-glibc-dynstack.patch ([BMO 1721326](https://bugzilla.mozilla.org/show_bug.cgi?id=1721326))
* https://src.fedoraproject.org/rpms/icecat/blob/rawhide/f/mozilla-1715254_glibc_2.34.patch

**Comment by q64ceo** [comment]
You are correct. I am using libc6 2.34. I have compiled Waterfox myself from the source.

How would I apply these patches to the code? My apologies but I am learning this as I'm doing this.

**Comment by hawkeye116477** [comment]
> How would I apply these patches to the code? 

After downloading raw version of them, go to Waterfox source directory and from terminal/console type `patch -Np1 -i patch_dir/icecat-glibc-dynstack.patch`, etc.

PS: If you're compiling with Clang 13, then additional patch might be needed => https://build.opensuse.org/package/view_file/home:hawkeye116477:waterfox/waterfox-g3-kpe/mozilla-1707096.patch?expand=1.

**Comment by q64ceo** [comment]
Thank you but I've got Clang 12.

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/663780de60a08e66a823a8cacc8a69c857390831

**Comment by hawkeye116477** [comment]
That fix was only for Classic, but OP asked about G3 too.
