### ISSUE TITLE
HTML output element not working

### ISSUE THREAD

**Issue by jabcreations** [MrAlex94/Waterfox#2268]
### What happened?

I [tested Firefox 56](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output#examples) and the output element worked, Waterfox Classic does not.

I don't know if the output element is particularly popular any where though this is certainly a regression that I discovered while working on an HTML validator.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by hawkeye116477** [comment]
Well, I've Classic too and output element works.

**Comment by jabcreations** [comment]
I apologize, I couldn't see the text. Invalid and closing...
