### ISSUE TITLE
Toolbar bookmarks do not always display.

### ISSUE THREAD

**Issue by ChooChooAl** [MrAlex94/Waterfox#2271]
### What happened?

Some bookmarks on the bookmarks toolbar do not show the favicon, however the tab does show it.
![Stores-favicon](https://user-images.githubusercontent.com/26556059/134828383-caee20d7-f218-4e30-a635-9e5211061aa3.png)

This works in Firefox.  
Waterfox is G3.2.6 (64-bit)
Linux Mint Cinnamon 20.2 64bit.  

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux, Windows

**Comment by MrAlex94** [comment]
This still happened in G4 and happens in G5. It appears to be something inherited from Firefox, as I still get that issue with them as well. One of our team members submitted a patch to Mozilla relating to favicons that might fix this in upcoming versions.
