### ISSUE TITLE
Typing Issue 

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#2272]
### What happened?

A bug happened! When Typing on several sites the Cursor jumps to the begining after the First Letter of a new Sentence. 
Facebook,  Fox News Feedback on Stories etc., I have to start typing and then Hit End to reset Cursor to proper place.  

Example... 
estT
elloH
odayT

G3.2.6 (64-bit)
Even with Addons Dissabled 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by sonofevil** [comment]
Same here.

Version: G3.2.6 64bit
OS: Arch Linux

Before entering the first letter: https://i.imgur.com/FrBqxGm.png
After: https://i.imgur.com/ASwfCy1.png

**Comment by MrAlex94** [comment]
This should be fixed in G4, please re-open if not.
