### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wkuzma** [MrAlex94/Waterfox#2278]
### What happened?

A bug happened!

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
I have updated to 2021.08.1 (64 bit) and have a problem with most web sites 
showing pictures ( CW network and Tubi ) also Facebook will just keep loading 
all my messages not allowing me to type a new one this only happens on Waterfox
  - when I use Firefox or chrome all web sites are normal.  
This happened after the update.

I even had to post this using Chrome since Waterfox would not allow me to select any of the boxes to post the bug
```

**Comment by wkuzma** [comment]
I downgraded to 2012.07 (64 bit) and it solved the above listed problems I had to set waterfox to never update to prevent the problem from coming back.

**Comment by hawkeye116477** [comment]
CW network and Tubi are geo-locked. Do you have another examples? Screenshots would be also good.

If it doesn't work in 2021.08, but work in 2021.07, then it's possible that's related with user-agent changes.

In case of:
> I even had to post this using Chrome since Waterfox would not allow me to select any of the boxes to post the bug

I don't have that problem. You need Polly installed.

**Comment by wkuzma** [comment]
![Scan_20211002](https://user-images.githubusercontent.com/11543804/135729217-202d0cf5-0c5c-4229-a8f1-2884473b0106.jpg)
I am unable to reproduce the problem since down grading to 2021.07   however here is a picture of what I did view when I used 2021.08
I also just noticed I could not attach a photo with waterfox I had to use firefox to attach this picture

**Comment by hawkeye116477** [comment]
> solved the above listed problems

It's interesting, cuz I checked previous version and Facebook issue is same.

Have you more example sites or only those which you mentioned (geo-locked)?

**Comment by wkuzma** [comment]
seems it is just the examples I gave since I mainly use those  as for the Facebook it did correct the problem on my system 
I use windows 10
hmm another problem when responding to posts in facebook you cannot type  Damm I may have to give up Waterfox  and stich with Firefox  That is what I am using to even edit this post since waterfox would not show the edit button

**Comment by hawkeye116477** [comment]
The only problem with Facebook which I currently see is that comments section doesn't work properly, but it's same even on older browser versions. To fix that someone needs to implement `InputEvent.data`. That looks like not that small work to do, so it won't be rather fixed on this month.

**Comment by wkuzma** [comment]
I did not notice that since I hardy do the comments but its the same here cannot type in the comment section
