### ISSUE TITLE
Add redirection to firefox add-ons' site

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2281]
**Is your feature request related to a problem? Please describe.**

Waterfox classic doesnt redirect to a site containing extensions.

**Describe the solution you'd like**

I want waterfox classic to redirect to firefox extensions' site or any other site containing the legacy extensions.

**Describe alternatives you've considered**

No alternatives.

**Additional context**

None.

**Comment by MrAlex94** [comment]
Anyone on Classic by now probably knows where to get extensions from. Since the focus is not classic anymore, this is going to be closed.
