### ISSUE TITLE
Search providers go missing

### ISSUE THREAD

**Issue by q64ceo** [MrAlex94/Waterfox#2284]
### What happened?

For some odd reason my search providers are removing themselves and defaulting to Amazon as my search engine. Yes, all of them, from Bing to Google.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by Felipefpl** [comment]
Qwant engine isnt working for some countries, a problem from the engine itself, perhaps it would be better to leave it out of waterfox for some time, It would be nice to have brave and mojeek engines since they work like duckduckgo.

**Comment by q64ceo** [comment]
I was able to fix it by copying over addonStartup.json.lz4 from my Firefox profile folder to my Waterfox profile folder. Strange.
