### ISSUE TITLE
Preferences - Tab Bar Position

### ISSUE THREAD

**Issue by robvthof** [MrAlex94/Waterfox#2291]
Is it possible to add to G4 the possibility in Preferences menu for Tab Bar Position like in G3? 
Gives the option to position the tab bar under the address bar. In combination with multi-line in TabMixPlus works great! 
Perhaps also consider to integrate TabMixPlus in G4? 

<img width="249" alt="Screenshot 2021-10-04 at 15 58 47" src="https://user-images.githubusercontent.com/85563078/135865036-ae0db193-11ee-4066-a93c-f14f36428ff0.png">

**Comment by adamp01** [comment]
@robvthof 

This has been added in https://github.com/WaterfoxCo/Waterfox/pull/2289

It will be available from the next beta release.
