### ISSUE TITLE
G4.0.0b1 Duolingo & Google & tab bar position

### ISSUE THREAD

**Issue by zqqw** [MrAlex94/Waterfox#2292]
### What happened?

On Duolingo there is a bell sound if the question is answered correctly. It sounds broken and wrong in this version of Waterfox, also in the latest stable Firefox. This is when using Alsa sound, no pulse audio installed. In Waterfox G3 it sounds fine.
There is no Google search engine option in Waterfox G4 and you cannot click a green + to add the site if you go to it, there are some Firefox extensions that enable it to be added though, but possibly not for all locales, for instance there is a Google UK and US but not too many more that I see there, although it solves my personal requirements anyway. Firefox has this option included as standard. I know you probably want to support alternatives but sometimes they don't give the answer when Google does.
[userChrome.css.gz](https://github.com/WaterfoxCo/Waterfox/files/7281611/userChrome.css.gz)
There is no option to have the tool bar under the address bar, this is the same in Firefox. So I had to add that file which is modified slightly, following the instructions here:
https://support.mozilla.org/en-US/questions/1339095

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by adamp01** [comment]
@zqqw 

For the Duolingo issue, as it is also on the latest Firefox version, we will probably not be working on this ourselves.

For the Google issue, could you open the the browser console (ctrl+shift+j) just after startup and copy/paste the output here. I believe this is likely related to an issue that we have resolved for b2 that should be released soon.

For the tool bar position, I have added this option to about:preferences (along with some others from G3) for b2 as well. Currently you can go to about:config and set browser.tabs.toolbarposition to one of: topabove, topbelow, bottomabove, bottombelow.

**Comment by zqqw** [comment]
That should be easier than adding the css file, thank you. Here is the output for Google in a fresh profile at startup:
[waterfox1.txt.gz](https://github.com/WaterfoxCo/Waterfox/files/7286438/waterfox1.txt.gz)

**Comment by MrAlex94** [comment]
Search issue you had is fixed in https://github.com/WaterfoxCo/Waterfox/commit/8c03b158fdb1f2fdbebd0d23357c5bb18e02c947, which should be the last unresolved one.
