### ISSUE TITLE
[classic] backport Block new requests asking to allow notifications 

### ISSUE THREAD

**Issue by eadmaster** [MrAlex94/Waterfox#2293]
Is is possible to backport this feature/setting from upstream FF?
["Block new requests asking to allow notifications"](https://support.mozilla.org/en-US/kb/push-notifications-firefox#w_how-do-i-stop-firefox-asking-me-to-allow-notifications)

It seems missing in latest WF classic, and the only alternative seems disabling notifications altogether.

**Comment by MrAlex94** [comment]
This probably won't be backported,
