### ISSUE TITLE
Tab Crashes when visiting addons.mozilla.org

### ISSUE THREAD

**Issue by shanoaice** [MrAlex94/Waterfox#2299]
### What happened?

Whenever I tried to open addons.mozilla.org, the tab will immediately crash (from the developer tool it seemed lika that Waterfox was able to manage to fetch the contents of the page but for some reasons it failed to display it). Sometimes it was able to display the tab for just a moment and then I will still crash.

### Reproducible?

- [x] I have tested this on Firefox. (not reproducible and shouldn't be related to upstream......)

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by shanoaice** [comment]
This bug is not (and possibly?) not related to Firefox. I've tested on it for a few times.

**Comment by freezewind** [comment]
Same here, but not only addons.mozilla.org.
One more example https://www.synology.com/
It also will immediately crash.
Version:
G4.0.0b2
Win10

**Comment by shanoaice** [comment]
On Linux (though I think this should be a separate issue) I can successfully open addons.mozilla.org without problem, but it does not recognize Waterfox G4 (perhaps because of my problematic PKGBUILD, or perhaps it's a problem of Waterfox) and does not allow me to install addons.

**Comment by plant7403** [comment]
> 
> 
> Same here, but not only addons.mozilla.org. One more example https://www.synology.com/ It also will immediately crash. Version: G4.0.0b2 Win10

Fully agree, addons crashes and synology
G4 beta 2 i suppose

**Comment by zqqw** [comment]
Works fine for me on Linux using Waterfox G4.0.0b2 (4th Generation) build from here:
https://github.com/WaterfoxCo/Waterfox/releases
I can search and install extensions, e.g here:
https://addons.mozilla.org/en-US/firefox/addon/worldwide-radio/
I just click download file and it installs and works

**Comment by shanoaice** [comment]
> 
> 
> Works fine for me on Linux using Waterfox G4.0.0b2 (4th Generation) build from here: [WaterfoxCo/Waterfox/releases](https://github.com/WaterfoxCo/Waterfox/releases) I can search and install extensions, e.g here: [addons.mozilla.org/en-US/firefox/addon/worldwide-radio](https://addons.mozilla.org/en-US/firefox/addon/worldwide-radio/) I just click download file and it installs and works

Seems like to be a Windows-only issue, hmm......I've also tested on Linux and it works fine.

**Comment by ShadyWhite** [comment]
Same here, and when I try to login to google.com. Tab will also immediately crash.

**Comment by MrAlex94** [comment]
I am also able to reproduce this. Will have a look and see what the issue could potentially be.

**Comment by MrAlex94** [comment]
An update: the fix should be as simple as setting `security.sandbox.content.win32k-disable` to `false`.

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/cc2aef7744b64d3242fe75004c58162a8c4266d6

Please reopen if still having issues.
