### ISSUE TITLE
Can't pay with PayPal on eBay - G4.0.0b2

### ISSUE THREAD

**Issue by zqqw** [MrAlex94/Waterfox#2300]
### What happened?

Trying to purchase an item on eBay UK with PayPal, everything went apparently normally until the Pay Now button in the little PayPal pop up window was pressed, which should have concluded the transaction. It then just came back again, pressing it again didn't help, selecting allow or deny cookies made no difference. This was also the case in b1, so I tried b2, and then in b2 with a clean profile. Tricky to test unless you happen to have something on there you are buying of course!
Console and terminal messages attached.
It worked in Firefox.
[waterfox-paypal.txt.gz](https://github.com/WaterfoxCo/Waterfox/files/7310681/waterfox-paypal.txt.gz)
x.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
This should be resolved in G4.0.1 and is probably due to site isolation, which has been disabled.
