### ISSUE TITLE
Video does't loading/play vk.com WC 2021.09 

### ISSUE THREAD

**Issue by ruboard** [MrAlex94/Waterfox#2306]
### What happened?

https://vk.com/video-186465759_456239049
error code Player.initVideo
https://images4.imagebam.com/7a/7b/eb/ME48M4L_o.JPG

**Comment by ghost** [comment]
Try media.webm.enabled;false

**Comment by ruboard** [comment]
> 
> 
> Try media.webm.enabled;false

no, it has nothing to do with it. if you set this parameter to true then a black screen will appear instead of the video, it will be even worse

It seems that the problem with the video in VK is due to "TypeError: i.e(...).then(...).then(...).finally is not a function" (https://vk.com/dist/a1ce2afe72d9e76a1e16588a7be78769.adaa4926c56b8111dc01.js:1:121219). This file is a native video player VK.COM

**Comment by ruboard** [comment]
Why was it closed?
The problem is not solved
You haven't even explained anything
