### ISSUE TITLE
Addon - undo close tab doesn't work - G4.0.0b3

### ISSUE THREAD

**Issue by freezewind** [MrAlex94/Waterfox#2308]
### What happened?

The button on toolbar has no effect after clicking.
I also tested with a new profile with the same result.

Addon is here:
https://addons.mozilla.org/en-US/firefox/addon/undoclosetabbutton/

Version:
G4.0.0b2
Win 10 21H1

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by freezewind** [comment]
Same in G4.0.0b3

**Comment by freezewind** [comment]
In G4.0.0.1, it works, but the addon button always gray out.

**Comment by MrAlex94** [comment]
Seems like that is the design of the button? Either way, closing since the add-on works.

**Comment by freezewind** [comment]
Ok, just for a note that it is not the design of the button.
I just test with firefox 91.2.0esr, it doesn't gray out.
![image](https://user-images.githubusercontent.com/3954389/138088259-bcf5626c-086b-4b1b-9941-20d54852b897.png)
