### ISSUE TITLE
Classic 2021.10 - Several Add-Ons Crippled or Entirely Non-Functional After Update to THIS Version.

### ISSUE THREAD

**Issue by SPWGitHub** [MrAlex94/Waterfox#2309]
### What happened?

Several Add-Ons Crippled or Entirely Non-Functional After Update to THIS Version.

Scroll To Top - Dead Functionality, Options Erased
Classic Theme Restorer - Loses Some Various Mods
Tab Mix Plus - Loses Some Various Mods

Probably more, but I downgraded back to 2021.09, which still has Facebook reply/comment bug and so does 2021.10.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by hawkeye116477** [comment]
I checked CTR (newest experimental version from GH) and Scroll To Top and seems that almost all works fine. There is only one problem in case of Scroll To Top extension - there is no arrow image, it's blank, but same is on 2021.09.

PS: I chose Scroll To Top from Classic Addons Archive, but there are also similar extensions on AMO, so I'm not sure which one you are taliking. If it's from AMO, then post link.

**Comment by Squall-Leonhart** [comment]
not seeing an issue with TMP either.

**Comment by SPWGitHub** [comment]
![Clipboarder 2021 10 14-002](https://user-images.githubusercontent.com/22408621/137406072-cda4cda5-1822-4ea6-9b03-3b90fa486086.png)

![Clipboarder 2021 10 14-003](https://user-images.githubusercontent.com/22408621/137406121-69d5d374-ada1-4ec4-a90d-c69b6280e385.png)

![Clipboarder 2021 10 14-004](https://user-images.githubusercontent.com/22408621/137406186-93395e77-ceb1-47a9-bfa8-6822216484d6.png)

The following highlights stop working:

![Clipboarder 2021 10 14-005](https://user-images.githubusercontent.com/22408621/137406219-3a7ebb83-ec0f-4b0d-8cc4-a207c987d22c.png)

![Clipboarder 2021 10 14-006](https://user-images.githubusercontent.com/22408621/137406331-f0092bd1-5a3e-47f6-9205-9d59332168eb.png)

As for STT, it completely loses functionality on most pages, even with its button on a toolbar.

**Comment by Squall-Leonhart** [comment]
Well yes, i suppose when you use outdated extensions bad things happen.

0.5.8.1 is latest for TMP
1.7.8.2019.06.23 is latest for CTR.

**Comment by SPWGitHub** [comment]
> Well yes, i suppose when you use outdated extensions bad things happen.
> 
> 0.5.8.1 is latest for TMP 1.7.8.2019.06.23 is latest for CTR.

Mind supplying links for those?  And, does that version of CTR work in FF 57+?

**Comment by Squall-Leonhart** [comment]
[tab_mix_plus-0.5.8.1-fx.zip](https://github.com/WaterfoxCo/Waterfox/files/7350012/tab_mix_plus-0.5.8.1-fx.zip)

This is my personal version of it, i remove a change to tab scrolling that made the mouse wheel scroll 3 tabs at a time isntead of 1

>         } else if (Tabmix.isVersion(530)) {
>          scrollAmount = delta * tabStrip.lineScrollAmount;

>  And, does that version of CTR work in FF 57+?

57+ removed all compatibility with what CTR does.

https://github.com/Aris-t2/ClassicThemeRestorer/releases/download/1.7.8.2019/CTR_v1.7.8.2019.06.23.xpi

https://github.com/Aris-t2/ClassicThemeRestorer/releases/download/1.7.8.2019/CTR_v1.7.8.2019.10.27.xpi is actually the latest, but i see no reason to install it at this time.

**Comment by SPWGitHub** [comment]
@Squall-Leonhart Thanks. I'l play around with those, but I'm steering clear of WFC 2021.10 for now.

**Comment by 117649** [comment]
> 
> 
> @Squall-Leonhart Thanks. I'l play around with those, but I'm steering clear of WFC 2021.10 for now.

Official!!: 
https://bitbucket.org/onemen/tabmixplus/downloads/

Version already updated to work on FF78+ code base on:
http://tabmixplus.org/

**Comment by SPWGitHub** [comment]
> Official!!: 
> https://bitbucket.org/onemen/tabmixplus/downloads/
> 
> Version already updated to work on FF78+ code base on: 
> http://tabmixplus.org/

@117649 - Terrific!  Thanks!  Do you happen to know if CTR is being redeveloped for FF78+?

**Comment by SPWGitHub** [comment]
> Official!!: 
> https://bitbucket.org/onemen/tabmixplus/downloads/
> 
> Version already updated to work on FF78+ code base on: 
> http://tabmixplus.org/

@117649 - Terrific!  Thanks!  Do you happen to know if CTR is being redeveloped for FF78+?

**Comment by 117649** [comment]
> @117649 - Terrific! Thanks! Do you happen to know if CTR is being redeveloped for FF78+?

NO. Use custom CSS.

**Comment by SPWGitHub** [comment]
> 
> 
> > @117649 - Terrific! Thanks! Do you happen to know if CTR is being redeveloped for FF78+?
> 
> NO. Use custom CSS.

Riiiggghht... Gee, why didn't I think of that?  I must be nuts using WFC and all of these old FF extensions when I can simply write custom style sheets and import a million icons and bitmaps and oh, let's not forget all the java script, sure, simple!

**Comment by 117649** [comment]
> 
> 
> > > @117649 - Terrific! Thanks! Do you happen to know if CTR is being redeveloped for FF78+?
> > 
> > 
> > NO. Use custom CSS.
> 
> Riiiggghht... Gee, why didn't I think of that? I must be nuts using WFC and all of these old FF extensions when I can simply write custom style sheets and import a million icons and bitmaps and oh, let's not forget all the java script, sure, simple!

Yeah. 
So you know why there won't be a CTR anymore. It not like drop files from old version into new.
The old files are in XUL they had to be rewrite into HTML5.
Completely refactor all those old .xul across all those version is just not worth the time.
Cherry-pick what you can't get ride of and only refactor that.

**Comment by SPWGitHub** [comment]
> 
> Yeah. So you know why there won't be a CTR anymore. It not like drop files from old version into new. The old files are in XUL they had to be rewrite into HTML5. Completely refactor all those old .xul across all those version is just not worth the time. Cherry-pick what you can't get ride of and only refactor that.

Just because I realize that it's a lot of work and some of what it involves, doesn't mean I have the slightest clue of HOW to do the work.  I'm not a coder.  I'm a hardware/OS/configurator/modifier/power user, but development is FAR beyond my skill set.

So, as long as there's a browser that runs XUL, I'll be happy with TMP, CTR, CFFB, RFE and UAS just as they are. Except Google is trying to eliminate the effectiveness of UAS, which will suck, bad.

**Comment by MrAlex94** [comment]
2021.10 was just a few security issues. There's nothing pertaining to add-on code to break anything. I appreciate it's not a great situation but Classic is long in the tooth and is most likely vulnerable to a quite few security issues. It's a borderline impossible situation to remedy, requiring too much engineering effort.
