### ISSUE TITLE
some include/cpp files missing <inttypes.h>

### ISSUE THREAD

**Issue by Manoa1911** [MrAlex94/Waterfox#2316]
### version: 4.0.0b3

js/src/util/DumpFunctions.cpp
js/src/jit/x64/BaseAssembler-x64.h
js/src/frontend/Parser.cpp
js/src/jit/x86-shared/BaseAssembler-x86-shared.h
js/src/vm/ArrayBufferObject.cpp
js/src/vm/CodeCoverage.cpp
js/src/vm/JSONPrinter.cpp
js/src/vm/JSObject.cpp
js/src/vm/JSONParser.cpp
js/src/vm/Value.cpp
js/src/gc/Pretenuring.cpp
js/src/gc/Nursery.cpp
js/src/gc/Statistics.cpp

is this the right correction ?
#define __STDC_FORMAT_MACROS 1
#include <inttypes.h>
#define PRIu64    "llu"
#define PRIu32    "lu"
#define PRId64    "lld"
#define PRId32    "ld"
#define PRIx32    "lx"
#define PRIx64    "llx"
#define PRIxPTR   "llx"

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
0:14.75 /mnt/ExcelStor/build/firefox/Waterfox-G4.0.0b3/js/src/vm/ArrayBufferObject.cpp:832:42: error: expected ')' before 'PRIu64'
 0:14.75      wasm::Log(cx, "new Memory({initial:%" PRIu64 " pages}) succeeded",
 0:14.75               ~                           ^~~~~~~
 0:14.75                                           )
```

the build is success and runs but the window contents stops drawing after clicking on any of the extension icons that open a popup window, this specific problem is not limited to WF and I have it also in official FF94, looks like they broke something because latest WF3 release working perfectly fine and doesn't have the bug but it's a long way to go to compare them :(
probably a problem with some major new system since 89+

**Comment by MrAlex94** [comment]
More information is needed, please let me know what you're building with and on what platform.

**Comment by Manoa1911** [comment]
it's slackware x64 14.1, I tried clang but it segfault so I had to use gcc which work fine, clang might be my local problem I maybe miscompiled it (with wrong build options), it's gcc 8.3.1, I looked into the possibility that it's a window manager problem but when both iceWM and fluxbox show exact same behavior it's hard to say the problem is that. if you are asking about the includes and headers I added them to those files in the right location and the build succeded and run fine besides that display freezing problem :) slackware64 14.1 is history it originally come with gcc 4

**Comment by MrAlex94** [comment]
Sadly, might need to be something you push for upstream to Mozilla.
