### ISSUE TITLE
Waterfox disappear

### ISSUE THREAD

**Issue by alexh8** [MrAlex94/Waterfox#2317]
### What happened?

Hello,

I'm trying to use Waterfox.
I say "trying" because while using it, almost on every session, I encounter a website that makes the windows of Waterfox to disappear.
No error message, no warning, nothing… Just the program shuts down.

Here is an example of webpage that makes the program crash:
https://www.bodemerauto.com/boutique/enjoliveur-eldo-14-pouces-renault-clio
Of course it works with all other browsers.

Then I reload the program, it reloads the page automatically, and close down again.
I restart in Safe mode, same thing, just closing down.

This is really annoying and makes Watefox not usable.

If you could help, that would be really appreciated.
Thanks.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Could you try G4 and see?

**Comment by alexh8** [comment]
> 
> 
> Could you try G4 and see?

I changed to G4, and the problem seems to be gone.
Thanks you very much!

I have another problem now. All the bookmarks have been synced, however none of the password are there.

**Comment by MrAlex94** [comment]
> > Could you try G4 and see?
> 
> I changed to G4, and the problem seems to be gone. Thanks you very much!
> 
> I have another problem now. All the bookmarks have been synced, however none of the password are there.

Is this on `G4.0.1`?

**Comment by alexh8** [comment]
> Is this on `G4.0.1`?

Yes it's on G4.0.1 (64-bit).

I've been struggling for more than a week now.

Logins and passwords list is empty. It's still there on my mobile or other computers with Firefox browsers.
Moreover, bookmarks are there, but new bookmarks made from Waterfox won't be uploaded to the account.

Any idea ?

**Comment by MrAlex94** [comment]
Sorry, I missed this! Hopefully with the latest updates you didn't have the password issue anymore :-)
