### ISSUE TITLE
Mozilla Add-on Library complains that to use these extensions you will have to download FIREFOX

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2319]
### What happened?

Waterfox G4

Cannot right-click on themes and choose  **Opens Link in New Tab**.  If I click on a theme I want, it tells me I need Firefox.  I can still click on  **Download File** and it will download and install it.

Installing regular extensions (as distinct from Themes) runs into the same problems.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
This has been fixed in G4.0.1
