### ISSUE TITLE
Preview of downloaded themes is not working (all showing in monochrome)

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2320]
### What happened?

Downloaded Themes all show as monochrome, so, when wanting to switch to a new theme, it is impossible to know what it will look like until actually switching to it.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Can't seem to reproduce this. Do you have a screenshot?

**Comment by MrAlex94** [comment]
I assume you may mean that they appear slightly greyed out:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/4728920/139243858-7792185b-1554-475c-89e3-03a238b0236e.png">

If not, please upload a screenshot and re-open this issue.
