### ISSUE TITLE
Waterfox G4 - Title Bar should be either in "View" Menu

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2322]
### What happened?

Switching on the  **Title Bar**  should not be something one finds accidentally when  **customizing**  a toolbar.

It should be under the  **View**  menu like the other toolbars one can turn ON or OFF

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
This isn't a bug. Even Classic doesn't have a View > Title Bar option.

If you'd like to submit a patch, I'll happily review it.
