### ISSUE TITLE
Zoom Control - Full Screen - Screenshot should automatically be in the Status Bar

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2323]
### What happened?

By default  **Zoom Control**,  **Full Screen**  should automatically be in the Status Bar, just like they were in Waterfox G3 without the user needing to go into Customize Toolbar.

I also think the  **Screenshot**  control should be there too.

![image](https://user-images.githubusercontent.com/89191739/137975209-113ec18f-4742-476b-9038-e556bf4b8d0c.png)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Have added these now in this PR: https://github.com/WaterfoxCo/Waterfox/pull/2498

**Comment by Objectivite** [comment]
Thanks Adam.

O.
