### ISSUE TITLE
I also downloaded and installed version 4.0 - now lost over 1500 bookmarks, and much more

### ISSUE THREAD

**Issue by benherrmann1** [MrAlex94/Waterfox#2325]
### What happened?

Been using Waterfox for years.  My most current version was the latest version of 3.0 (I believe it was 3.2.6 (whatever the latest version was).  During that time I had over 1500 bookmarks, tons of extensions, log-ins, passwords, and other things stored.  Now they are all gone.  Version 4.0 wiped out everything!!!

I am running Windows 10 (version 21H1), 64 Bits.  Is there anywhere I can look to find all of those lost items?  And if so, how do I go about restoring them - I am panicking because I use Waterfox for work?

As an aside, I tried to install the Firefox extensions again - one by one - but they won't install, and all I get is an indicator that said I have to use Firefox to use those extensions.  What the hell?

Ben Herrmann
Fuquay-Varina, NC

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
No need to open another issue. It has been identified in https://github.com/WaterfoxCo/Waterfox/commit/25c98a6caab83934c8eb2a3ee57b3b7e58f650ca.

Your profile data hasn't been lost, please wait for G4.0.0.1 to come out ASAP. It is building as we speak.

**Comment by benherrmann1** [comment]
Thanks - I appreciate that.

Ben

**Comment by benherrmann1** [comment]
Thanks for putting out the new (corrected) version so quickly - all is well now and everything that was lost is now restored.

**Comment by MrAlex94** [comment]
Glad to hear :-)
