### ISSUE TITLE
Waterfox G4 - Speaker icon on a tab overwrites the tab's site icon

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2326]
### What happened?

In Waterfox G3, if you happen to be on a site which plays sound, like YouTube, the  **speaker icon**  appears on the **right side** of the tab, leaving the left side for the site's icon, like below :+1: 

![image](https://user-images.githubusercontent.com/89191739/138004938-c9210846-d141-47c9-8fe2-9c400203db4f.png)

In Waterfox G4, however, the speaker icon **incorrectly displays on the left side of the tab**, completely overwriting that site's icon, as shown below :+1: 

![image](https://user-images.githubusercontent.com/89191739/138005191-701859c6-f754-4725-b945-f130007ab2c9.png)

The problem with this is that when you have 3 or more tabs  **from different websites**  all playing sound (some muted, of course), because the icon is overwritten you do not know which tab is for which website when you want to go back to one of the tabs.

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
This is by design, because having the mute button right next to the close button is terrible UX.
