### ISSUE TITLE
Waterfox G3 v3.2.6 updated automatically to G4 v4.0.0.1 despite setting set to "let me choose" !!!

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2330]
### What happened?

Wow, now that was a nasty one.

On my main machine, which is always set to  **LET ME CHOOSE to install updates**, my G3 3.2.6 just updated itself to 4.0.0.1 with all its  **TABS at bottom**  bug.

Had to re-install 4.0.0.0 over the top.

In case that bug is carried over into 4.0.0.1, you may want to look at the   _Check for updates settings_  Alex.

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by InvisibleManX** [comment]
I can only help you by giving you this info, which I'm using myself: 
[https://newbedev.com/how-to-stop-firefox-update-notifications](https://newbedev.com/how-to-stop-firefox-update-notifications)

By using the following instructions, you can disable updates  for as long as you need. You won't even see notifications. 

To add a policy, follow the steps:

Go to the firefox installation directory (for any supported OS).
Create a directory called `distribution`.
Change directory into "distribution".
Create a file called `policies.json`
And paste this code:

```
{
    "policies": {
        "DisableAppUpdate": true
    }
}
```

Save the file, and quit the editor.

Restart Firefox if it's already running.
To confirm, you can go to the URL about:policies and check if there's an entry like this:

```
Policy Name     Policy Value
DisableAppUpdate    true
```

**Comment by Objectivite** [comment]
> 
> 
> I can only help you by giving you this info, which I'm using myself: https://newbedev.com/how-to-stop-firefox-update-notifications
> 
> By using the following instructions, you can disable updates for as long as you need. You won't even see notifications.
> 
> To add a policy, follow the steps:
> 
> Go to the firefox installation directory (for any supported OS). Create a directory called `distribution`. Change directory into "distribution". Create a file called `policies.json` And paste this code:
> 
> ```
> {
>     "policies": {
>         "DisableAppUpdate": true
>     }
> }
> ```
> 
> Save the file, and quit the editor.
> 
> Restart Firefox if it's already running. To confirm, you can go to the URL about:policies and check if there's an entry like this:
> 
> ```
> Policy Name     Policy Value
> DisableAppUpdate    true
> ```

Thanks InvisibleManX,

I knew about that solution as we implement it as standard on  **Firefox**  on all our PCs.  As soon this happened to earlier I told my colleagues and well implemented on  **Waterfox as well**.

But Thanks anyway for posting as others might need it.

O.

**Comment by MrAlex94** [comment]
The browser definitely should not have updated automatically if Let me Choose was selected. I will run some tests to see if I can reproduce and have a fix so it doesn't happen in the future.

**Comment by MrAlex94** [comment]
We added an option in G5 to disable auto-updates.
