### ISSUE TITLE
Waterfox G4 v4.0.0.1  -  Tabs are at the bottom at all times - impossible to change this

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2333]
### What happened?

Hi Alex,

You closed my previous bug report without picking up this  **major problem**  with 4.0.0.1.

I have had to revert to  **v4.0.0.0**  and copy settings from AppsData\Roaming\Waterfox  to  **AppsData\Roaming\Waterfox Limited**  because v4.0.0.0 is a lot more usable than v4.0.0.1  because of this tab issue.

The tabs are at the bottom of the screen,  **overwriting the Status Bar**  and no amount of tweaking either in Settings or about:config solves the problem.

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@Objectivite - some pref naming has changed in G4, the change from old to new pref naming is done on migration from G3->G4, or for any profile where `browser.migration.version` is less than 116. The prefs that control all this are now:
browser.tabs.toolbarposition -> topabove, topbelow, bottomabove, bottombelow
browser.bookmarks.toolbarposition -> top, bottom
browser.statusbar.enabled -> true, false

**Comment by MrAlex94** [comment]
We'll use https://github.com/WaterfoxCo/Waterfox/issues/2362 as the issue to track this, since it provides more information we can work off of.
