### ISSUE TITLE
Waterfox G4 - Speaker icon (again !)

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2334]
### What happened?

Hi Alex,

Your response :  _This is by design, because having the mute button right next to the close button is terrible UX._

The current implementation, not being able to recognize what website a site is on, thanks to the icon, **is even worse UX**.

**Having tabs is based on the immovable premise that one is going to be able to recognize the tab thanks to the website icon** - otherwise tabs would not be so popular and would lose their raison d'être, and I speak as both a programmer and a user.

Find a solution, even if it means going back to the way it was because ..... no-one ever complained about it !

But having one icon, the speaker icon, replace the "must-never-be-removed" site icon, is  **terrible UX**.

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by InvisibleManX** [comment]
I totally agree! 

The icons for sites should always be visible!

**Comment by MrAlex94** [comment]
This is not a bug, stop re-opening this issue. 

Please switch theme if you do not like this.
