### ISSUE TITLE
Waterfox G4 - this is the developer we are dealing with

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2336]
### What happened?

His response about the speaker icon which had people agreeing with it :

----------------------

This is not a bug, stop re-opening this issue.
Please switch theme if you do not like this.

----------------------

Priceless.

Why even be a developer !!

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by InvisibleManX** [comment]
Okay, I understand your frustration myself (really disappointed with the direction of G4 and that most likely I won't be able to even run it on my PC). 

But, keeping on making various posts, especially like this one, simply to vent your frustrations, isn't gonna change or solve anything.

**Comment by Objectivite** [comment]
> 
> 
> Okay, I understand your frustration myself (really disappointed with the direction of G4 and that most likely I won't be able to even run it on my PC).
> 
> But, keeping on making various posts, especially like this one, simply to vent your frustrations, isn't gonna change or solve anything.

I think it is important people know what they are dealing with so they simply do not waste their time raising issues - that was the reason I posted it, not to vent any frustration - I am done with it.

I even helped the guy solve issues in G3, and yesterday in G4 pointing to where the profile was being stored, and this is what I get.

I hope others realize it is pointless raising any issues - you admit as such yourself in your own comment.

O.

**Comment by adamp01** [comment]
This has already been quite a discussed item, so quoting my exact reply from #2279 (with regards to the location of the Mute Tab overlay in both Proton and Lepton):

> The reason for this is due to Mozilla updating where the Mute Tab overlay is rendered, thus making it impossible to do much with just css. If you take a look here: https://searchfox.org/mozilla-central/source/browser/base/content/tabbrowser-tab.js#23
> The tab-icon-overlay is the class that the Mute Tab overlay falls into. It would be possible to amend this and move that line down to just above the tab-close-button on line 39, but that would break the Proton theme for users who prefer that (and probably give us some merge conflicts when pulling from Firefox at some point).
> Whilst I do agree the overlap of the overlay and the favicon isn't the most appealing of things, I think it is still preferable to how Proton handles things:
> <img alt="image" width="90" src="https://user-images.githubusercontent.com/47503375/135865097-7024b6c0-904e-4162-a6e0-53a2c34feb94.png"><img alt="image" width="89" src="https://user-images.githubusercontent.com/47503375/135865134-ef4a5276-150b-40fe-bbf9-3e56d1c4a8a5.png"> 
> Vs. Lepton:
> <img alt="image" width="96" src="https://user-images.githubusercontent.com/47503375/135865234-efa7e0c3-ec01-436f-9f01-b6ed0472bca4.png">

I can assure you that by raising issues you are not wasting time, as a lot of what you have mentioned over the past day is being actioned as a priority.

We appreciate your patience in our fixing of these issues.
