### ISSUE TITLE
Waterfox G4.0.0.1 - UI is largely an exact copy of Firefox's proton design

### ISSUE THREAD

**Issue by Sollace** [MrAlex94/Waterfox#2337]
### What happened?

Waterfox just updated today, and I'm disappointed to see none of my previous complaints have been addressed. The browser is still mimicking the design of Firefox 91 (which I specifically switched to Waterfox to get away from) with no option to switch back to the Firefox 78 look.

All that's been done is change the shape of the tabs, lock it to compact mode, and add a bunch of icons to the menus, which largely just makes Proton, the already childishly awful design, look slightly worse.

Here are the problems I have with Proton, now applied to Waterfox G4(since it is using Proton now):

1. Context menus do not fit with the rest of my system, they are absolutely MASSIVE, and can be summarized as "looks like MS Edge"
2. The main hamburger menu has been rearranged to look like MS Edge. It is either missing or buried several options that were present in Waterfox G3 (just like Firefox)
    i.e. "Customize" Is now hidden in a sub-menu
3. Thumbs on the new tabs page are small and don't show previews of their websites any more (just like Firefox)
4. You can no longer collapse sections in the new tabs page
5. My OS theme does not show in the tab menu unless I select the FF default theme and set `browser.proton.enabled` to `false`
6. The fix for the above breaks the Waterfox Lepton theme
7. (see screenshot) Checked and Unchecked boxes in the options pages are indistinguishable (just like Firefox)
![image](https://user-images.githubusercontent.com/6429283/138136937-33780bac-7177-4d6f-9f81-c4ca57c285f4.png)

8. The UI is "locked" to compact (unsupported) mode, which makes everything look unnaturally cramped (just like firefox)
9. All (ALL) icons are mimicking MS Edge and are often not as distinct or visible as they were before (just like firefox)
10. (see screenshot) some menu options have icons whilst others don't
![image](https://user-images.githubusercontent.com/6429283/138136720-95f2b0f3-7756-4db7-a8a7-a165efe41136.png)
11. (see screenshots) Various flyouts and dropdowns have superfluous padding and rounded corners, even with compact mode and Lepton.
![image](https://user-images.githubusercontent.com/6429283/138139190-e6b4bde0-a33a-458f-a014-381a83572706.png)

 
Overall, as I already said before, I don't like _ANY_ of the things Mozilla has done in Firefox 91. Not a single bit of Proton. I don't want to see it. I don't want to be reminded of it, ever, and if Waterfox is going to go the same route then I'm sorry to say I have no reason to use this browser any more.

At this point I'd might as well go back to Firefox, because from a design standpoint they are both equally as awful.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Thank you for the feedback.

* Waterfox uses Lepton (based on Photon, from Firefox 57->90) by default and will include an Australis theme in the near future.
* Waterfox looks like Proton because it is Proton if you select proton.

If you would like to commit the changes you seek for this piece of [Free Open Source Software](https://en.wikipedia.org/wiki/Free_and_open-source_software), I will happily review it.

**Comment by Sollace** [comment]
> Waterfox looks like Proton because it is Proton if you select proton.

No, fresh install without changing any settings. The only thing that's _not_ proton is the tab shapes. The menus, context menus, popups, and everything else is still using Proton.

Lepton does not look like Photon. It's not even remotely similar.
