### ISSUE TITLE
Waterefox G3.2.6 (64-bit) - Cannot Create or Delete Bookmark Folders

### ISSUE THREAD

**Issue by avidleeCurious** [MrAlex94/Waterfox#2338]
### What happened?

When right clicking either the Bookmark Toolbar or using the Bookmark Manager, any attempt to create a New Folder results in an empty dialog box (where the new name should be) with a grayed out 'Add' button and a functional 'Close' button.

Copy/Paste functions do not work when right clicking in toolbar or manager. Delete functions do not work under similar circumstances. Separators can be added to Bookmark Toolbar but not removed.

The issue does not occur on Firefox.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Since G3.2.6 has been superseded by G4, could you test on G4 and if you still have the issue - reopen this one?
