### ISSUE TITLE
What Did You Do?

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2339]
### What happened?

The latest Update is a wank. SLOW (Firefox runs like a Lambo alongside it).  It doesn't maintain persistent logins and doesn't respond half the time to Login dialogue drops downs.  Appearance of Data entry lags keystrokes by two or three or FOUR seconds.  Photos, Feeds, and Twitter embeds take MINUTES to load.  Logging into Disqus on one tab does not carry over to any other tabs.  The browser HANGS, Freezes, won't exit - has to some times be Process killed to stop it.  My latest Firefox does not have these problems when running side by side!

So yeah I'm just bitchin cause I can't fix it, only you guys can Gues i can retrograde for a while or go back to firefox...

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by InvisibleManX** [comment]
If we add there stopping supporting even SSE 4.1 processors, while Firefox supports SSE 2, 
considering the new gen version manages to get such reponses from people like yours even after attempts to speed it up in comparison to other browsers, it's all really sad. 

One decision managed to kill Waterfox basically as a product. Yes, it might not seem this way, but after a month or several months it will become apparent. 

People will be running to Firefox really fast, and the only thing that can stop all this in time is a quick polishing of  G4 into a working state (so that the issues you reported here wouldn't be all over it), and of course adding the support of CPUs back, just as it always supported them.

**Comment by MrAlex94** [comment]
@RockyFaher please could you go to `about:support` and then click "Copy text to clipboard" and paste the output here?

@InvisibleManX - the majority of users support SSE4.2. It is a very common instruction set now. Nothing is going to happen.

**Comment by InvisibleManX** [comment]
> the majority of users support SSE4.2. It is a very common instruction set now. Nothing is going to happen.

Well, it's not just about old CPUs. As people mentioned in other topics, there are Atom processors, just a few years old that won't run it. 

In any case, now that we got this response I see there's no way back. 

Best of luck with this approach then. Perhaps you're right. 

I myself have to depart now. 
I do thank you for a few years of good experience with Waterfox Classic and G3, though. 

Now I'm forced to go to Firefox ESR 91. But after some setting up it didn't turn out so bad. And it feels faster than G3 still, so at least nothing horrible happened I guess.

**Comment by spdfnet** [comment]
> It doesn't maintain persistent logins
This was happening from time to time already, but now it's mostly all the time?
I 'fix it' by reloading the tab, then the cookies are read propery.

**Comment by spdfnet** [comment]
> It doesn't maintain persistent logins

This was happening from time to time already, but now it's mostly all the time?
I 'fix it' by reloading the tab, then the cookies are read propery.

**Comment by ghost** [comment]
<html><body>


      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="app-basics-title">Application Basics</h2>

      

Name | Waterfox
-- | --
G4.0.0.1
20211019232943
 
default
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0 Waterfox/91.3.0
Windows_NT 6.3 9600
Enabled
1/1
1/1               Enabled by default
10
Inactive
Missing
Missing
Missing
false



    
</body>
</html>

**Comment by ghost** [comment]
So its 'Processor Support'?  My laptop is too old?  How many times have I read some 'User' insist he would rather jump off the roof than give up his beloved [insert version here] machine, OS, Application than upgrade and shook my head.

At first I thought; "This has to be me", so I was right the first time.  I am officially an Old Man...

**Comment by MrAlex94** [comment]
@RockyFaher your laptop/computer is completely fine, the other user went a bit off-topic. For your logins not being remembered, you can toggle `privacy.firstparty.isolate` to `false` in `about:config` and then restart the browser - it should bring back your old login sessions/cookies.

**Comment by MrAlex94** [comment]
G4.0.1 should resolve your session and data issues, available in a few hours.
