### ISSUE TITLE
New tabs page - Recent activity part broken (settings and sometimes wiew)

### ISSUE THREAD

**Issue by MDM-79** [MrAlex94/Waterfox#2341]
### What happened?

The **New tabs** page has - _**Recent activity**_ part broken (settings and sometimes wiew):

![1](https://user-images.githubusercontent.com/87946426/138273082-2732bb83-149b-400e-92bb-89b78d5cbccb.png)
![2](https://user-images.githubusercontent.com/87946426/138273084-c4eeb3ee-474c-4fe2-896d-c5ec1a92eaf9.png)
![3](https://user-images.githubusercontent.com/87946426/138273076-ae595837-cf44-4ee4-9a1e-fd371151783a.png)

Can't even adjust the number of rows, even if I chose 4 - nothing happens. And as in the pic, sometimes the Recent activity part is gone until Waterfox restart.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
None needed...
```

**Comment by adamp01** [comment]
I've found the issue for row count not updating, that will be fixed for G4.0.2. Need to look into why it disappears on reload still.
