### ISSUE TITLE
Sync - Settings not selectable

### ISSUE THREAD

**Issue by MDM-79** [MrAlex94/Waterfox#2342]
### What happened?

In Sync - the **_Settings_** is not selectable for syncing.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
None
```

**Comment by MrAlex94** [comment]
@MDM-79 this was disabled by default to stop users who have Firefox from syncing preferences that will break settings on Waterfox and vice versa. 

It should be unticked rather than disabled completely so I will remedy that soon.

**Comment by MDM-79** [comment]
Good idea, because I for example have only Waterfox on all of my devices and so do want to sync! (like on G3)

**Comment by MrAlex94** [comment]
> @MrAlex94 why are you deleting comments?

I'm not - they're being hidden because they're off-topic like this. Completely irrelevant to this issue.

**Comment by MrAlex94** [comment]
@MDM-79 this has been commited in https://github.com/WaterfoxCo/Waterfox/commit/baa29f484793b1b7a9a0e84b4adcc77515d82956 and will be available in G4.0.1 which will be ready by the end of the day.

**Comment by MDM-79** [comment]
I confirm, it works again!
Tnx'
