### ISSUE TITLE
Vivaladi Fox addon break Lepton theme on G4

### ISSUE THREAD

**Issue by 117649** [MrAlex94/Waterfox#2344]
### What happened?

When ever vivaladi fox changes bar colors on Waterfox it disable Lepton theme and restore it to Firefox default.
Firefox with Lepton theme don't have this problem.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Peacock365** [comment]
Vivaldi Fox only supports Proton and will not work with Lepton. Only the extension developer can potentially fix this, please contact the dev. This is not a Waterfox issue. Switch to Proton for the time being if you want to use Vivaldi Fox.
