### ISSUE TITLE
G4 profile directory confusion on Linux

### ISSUE THREAD

**Issue by ilu33** [MrAlex94/Waterfox#2345]
### What happened?

Linux Debian 11 and 12.

G4 (G4.0.0.1) creates ~/.mozilla/.waterfox. That is, it creates .waterfox inside ~/.mozilla. If ~/.mozilla doesn't exist, it either freaks out and crashes (first test) or creates a directory with a preference style name, but not with a full set of files and subdirectories, inside ~/.cache/waterfox (second test).
The G3 directories are not picked up by G4.

Another test:
If ~/.mozilla/.waterfox exists, it uses that.
If ~/.mozilla exists, but without the .waterfox subdir, it creates/uses that.
If ~/.mozilla does not exist, it creates/uses ~/.config/mozllla/.waterfox and also ~/.cache/waterfox/ plus subdir (it always creates ~/.cache/waterfox, but that remains empty if ~/.mozilla exists).

It never uses ~/.waterfox and ~/.config/waterfox and  ~/.cache/waterfox which would be the correct locations. Please do not interfere with directories belonging to mozilla.

Is G4 the equivalent of "Firefox nightlies"? Or is it meant to be the "stable" version? It seems to lack testing and I'm not sure whether I should have served G4 to users at all ... Does G3 (current) still get security updates?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Apologies for this - I pulled in a patch to follow the "modern" [XDG Base Directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) spec but instead of picking up the existing directory it's ignore it completely. I'll roll back the patch and will have this fixed in the next update.

**Comment by MrAlex94** [comment]
This has been commited in https://github.com/WaterfoxCo/Waterfox/commit/25fd6c8fa61f9d92ec7fd5b20cfe5159024a0012 and will be available in G4.0.1 later today.
