### ISSUE TITLE
[website] Downloads page empty due to getting 401 on github-api request

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2346]
### What happened?

![github-api-401_20211021192045](https://user-images.githubusercontent.com/59403389/138343110-af3285ac-8e8e-4c72-b91f-d397b52b9398.png)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```http
GET: https://api.github.com/repos/WaterfoxCo/Waterfox/releases/latest
Status: 401 Unauthorized
Version: HTTP/2
Transferred: 1.10 KB (90 B size)
Referrer Policy: strict-origin-when-cross-origin
```
```

**Comment by MrAlex94** [comment]
Thanks for the information! Fix is done and should be live soon :-)

**Comment by MrAlex94** [comment]
All good now 👍
