### ISSUE TITLE
Mozilla fingerprinting workaround - have you tried this?

### ISSUE THREAD

**Issue by Yuumiau** [MrAlex94/Waterfox#2348]
Hey,

browsing extensions to mimic a firefox to access one website blocking Waterfox I've stumbled upon a potential fix for Mozilla not recognizing Waterfox as the same kind as Firefox.

I've tested the following changes in my own browser and it works perfectly fine.

https://ninetailed.ninja/extensions-modify-mozilla-sites.html?src=amo

**Comment by adamp01** [comment]
@Yuumiau - Thanks for raising this - I'm submitting a PR to include `pref("privacy.resistFingerprinting.block_mozAddonManager", true);` in `000-waterfox.js` for this tomorrow AM, as it does indeed allow us to override the default (Waterfox) UA on moz domains.
