### ISSUE TITLE
Confused graphic on web pages

### ISSUE THREAD

**Issue by Warrior69** [MrAlex94/Waterfox#2351]
### What happened?

A bug happened!
The new Waterfox 4.0.0.1 (64bit) works worst than the old G 3.2.6 one.
Putting as example, the https:/www.nutaku.net/home and the games into it. It was working ok with the version before the new one. As soon as Waterfox updated itself the new version, so many glitches, screen blinking, screen over screen appears in the 4 corners of the screen as if the screen was splitted in 4 different areas. The stable image remain on the desktop, but the blinking images are disturbing the games.
Unfortunately I can't add a picture because the disturb it's so fast that I can't take a picture, but you can easily go to the site and (try to) play "Booty Calls" (as example). While the game is loading PVP partner, looks like the vga is burning!!!

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Can you upgrade to [G4.0.1](https://www.waterfox.net/download) and test?

**Comment by Warrior69** [comment]
I did the upgrade and the problem it's still on. I see the problem (glitching) happend even with the initial menu and, in a little part, with the initial GitHub page too. Only where there are no images, there's no glitching. It seems something goes wrong with the charging of the images that it wasn't happening before, with the 3.x version of Waterfox.

**Comment by Warrior69** [comment]
The ONLY way to make it work through the glitching is to go to the settings and disable the hardware acceleration and/or the "impostazioni predefinite" (I don't know how it's written in english 'cause I use the italian version of Waterfox).

**Comment by MrAlex94** [comment]
With G5, the experience should be better!
