### ISSUE TITLE
Pressing "T" on YouTube switches to private browsing rather than putting the video in widescreen

### ISSUE THREAD

**Issue by jack-jjm** [MrAlex94/Waterfox#2355]
### What happened?

On a YouTube video, when you press T it's supposed to put the video in "theater mode" (widescreen). Since the latest Waterfox update, it instead puts the tab in private browsing mode. In other words, Youtube is not able to override Waterfox's default keyboard shortcut. Based on [this](https://old.reddit.com/r/waterfox/comments/qdtwon/the_new_t_keyboard_shortcut_to_switch_to_private/) discussion on Reddit, it seems like this might be a failure of the  shortcut override permission specific to youtube.com.

Waterfox G4.0.0.1, Ubuntu 20.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by Jaitsu** [comment]
I'm experiencing this _everywhere_ if I press T while not typing into a text box. Pressing T with no additional modifier key is switching the current tab into/out of private browsing.

**Comment by jack-jjm** [comment]
> I'm experiencing this _everywhere_ if I press T while not typing into a text box. Pressing T with no additional modifier key is switching the current tab into/out of private browsing.

That's a feature, I believe. I don't necessarily agree with it either. A single-key shortcut to bring up the search box (which the apostrophe key does) is one thing, a single-key shortcut that *immediately refreshes the page and destroys its state* is another.

**Comment by Physics-Dude** [comment]
Same issue here. Seems to be linked to this change. "P" and "T" commands should be using its defined modifier key. I made a comment the other day with more info.

reference: https://github.com/WaterfoxCo/Waterfox/commit/43e46ba36e12abde7f01baf9c91a790281b8a0e5

Windows 10

**Comment by jack-jjm** [comment]
> Same issue here. Seems to be linked to this change. "P" and "T" commands should be using its defined modifier key. I made a comment the other day with more info.
> 
> reference: [43e46ba](https://github.com/WaterfoxCo/Waterfox/commit/43e46ba36e12abde7f01baf9c91a790281b8a0e5)
> 
> Windows 10

Can this be hotfixed by the user?

**Comment by adamp01** [comment]
Thanks for raising this - I'll remove the Private Tab shortcuts for now.

**Comment by mk-fg** [comment]
> Can this be hotfixed by the user?

If your browser is built without mandatory addon signing (which I don't know if official releases of Waterfox are), then you can easily do that by unpacking `waterfox/browser/features/extensibles@waterfox.net.xpi` file (path might be system-dependent, it's a simple zip), reverting changes made by 43e46ba linked above to privatetab/background.js in there (lowercasing prefix key names), and packing it back to that .xpi file.

On my linux box here, it looks something like this:
```
% unzip /usr/lib/waterfox/browser/features/extensibles@waterfox.net.xpi
% nano privatetab/background.js
% mv /usr/lib/waterfox/browser/features/extensibles@waterfox.net.xpi{,.bak}
% zip -r /usr/lib/waterfox/browser/features/extensibles@waterfox.net.xpi *
```
Doing this allowed me to type this message :)

Pretty sure above method should not work if you're using Waterfox that is built to require addon signing though (without `MOZ_REQUIRE_SIGNING=` line in mozconfig), and then I think only option might be to disable that `extensibles@waterfox.net.xpi` bundled addon entirely via policy file, as mentioned in this comment - https://support.mozilla.org/en-US/questions/1265135#answer-1239106
That would disable Waterfox features implemented by that extension, but should make input text boxes on sites generally usable.

**Comment by jack-jjm** [comment]
Seems to be fixed as of `G4.0.2.1`.
