### ISSUE TITLE
Multiple issues 

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#2356]
### What happened?

The ypingt issue is still there not as bad but still happens. 
When Posting on Facebook I start composing a new Post and when I click to submit that everything is erased and never post especially when adding images. The Browser acts like I am clearing what I created its intermittent. 

When you go to click on Help and About and click on what's new it takes you to a Page is not Found might want to check that.
https://www.waterfox.net/blog/waterfox-G3.2.6/

The Get involved link also in that Help about is not working at all. 
in fact the other links in the Help About / about waterfox does not work!!! 

Finally when Watching Youtube Videos say I want to advance the play and after 2 or 3 times its locks up the plaything video. 
![image](https://user-images.githubusercontent.com/20975332/138565057-c6aff7a0-6494-4e88-b85d-53fc0d9c5f86.png)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by Felipefpl** [comment]
> Finally when Watching Youtube Videos say I want to advance the play and after 2 or 3 times its locks up the plaything video. ![image](https://user-images.githubusercontent.com/20975332/138565057-c6aff7a0-6494-4e88-b85d-53fc0d9c5f86.png)

I'm having problems with youtube on latest Waterfox Classic too, the site now gives me somewhat often an error saying the internet doesnt work, i have to press F5 or click on reload to make the site work again, i didnt have this problem previously.

**Comment by A0R-R0CKS** [comment]
This is what I am running.... The Videos get unresponsive ... 
Watching TUBI.TV Movies stop playing have to reload after clearing Cache, 
My Cable TV Live on web also will play for 20 - 25 min and lock up. 

![image](https://user-images.githubusercontent.com/20975332/138570283-79ac54a5-04c3-4e60-a7d6-0497c677ac10.png)

**Comment by MrAlex94** [comment]
Hopefully now with G4 (and G5) this was resolved. We've fixed What's new links as well as support links (although some still need writing).
