### ISSUE TITLE
Waterforx G4 v4.0.1  -  No preview on themes

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2358]
### What happened?

In case anyone cares about fixing bugs (running this browser with updates completely disabled by policy is the safest option).

No previews on **Themes** - the odd ones that do preview are all monochrome.

The same themes all display fine in Firefox, **and in colour**.

From "experience" this will be my only interaction for this bug report.

![image](https://user-images.githubusercontent.com/89191739/138589370-0e75bb86-2594-431c-ac98-d26766b50fb8.png)

O.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
This is due to `extensions.getAddons.cache.enabled` being set to false for [privacy](https://blog.mozilla.org/addons/how-to-opt-out-of-add-on-metadata-updates/) reasons:

> In order to keep this information updated, Firefox will ask the Mozilla Add-ons gallery for information about the add-ons you have installed once a day. This involves sending the identifiers of each add-on you have installed to Mozilla, **as well as information on how long it last took Firefox to start up**.

I may just unlock the preference so users can change at will rather than set it on by default.

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/ddf9615278cf6d9c104e014750bb5da83369f8d9

Next update, feel free to toggle it to true. Bare in mind it may take a while to fetch the information.
