### ISSUE TITLE
Can' t use NPAPI plugin on waterfox g4

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2360]
### What happened?

It seems that after upgrading waterfox g4 the browser no longer supports NPAPI plugins such as the flash player plugin, I tried to access pages containing flash resources but it didn't work.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/issues/2129#issuecomment-998897678
