### ISSUE TITLE
G4.0.1 Not reading it own profiles but want to read Classic's profile and sabotage .

### ISSUE THREAD

**Issue by 117649** [MrAlex94/Waterfox#2363]
### What happened?

This is just outrages.
G4.0.0's profile path is **%APPDATA%\Waterfox Limited\Waterfox** different from classic
G4.0.1's profile path is **%APPDATA%\Waterfox** same of the classic.
This is terrible. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
G4.0.0 had an incorrect path being used and was fixed relatively quickly with G4.0.0.1

Waterfox G3 has used this same structure for years without issues as do G4 profiles.  Profiles in Current/G3/G4 are structured as `{Salt}.68-edition-default` whereas Classic has the structure of `{Salt}.default`. 

I am using both G4 and Classic side by side in the same location - are you actually facing any issues with profiles?

![image](https://user-images.githubusercontent.com/4728920/138717607-d06932e2-79c0-4425-8c4d-842601d30dcf.png)

As you can see in the picture above, classic has its own profile set as default properly as does G4.

**Comment by 117649** [comment]
> `{Salt}.68-edition-default` whereas Classic has the structure of `{Salt}.default`.
> 
> I am using both G4 and Classic side by side - are you actually facing any issues with profiles?

I've set G4.0.0 to use the profile path of Firefox which is same name of the classic.
And after upgrade I can't run G4 and Classic side by side. If classic is running it ask to close classic.
If I do it my classic profile get read and break.

Now I have to recovery my profile for classic.
I'll try create a new profile for G4.0.1 after see if it works.

**Comment by MrAlex94** [comment]
>  I'll try create a new profile for G4.0.1 after see if it works.

Did this work?

**Comment by 117649** [comment]
Yes

**Comment by MrAlex94** [comment]
Okay, will close this issue then.
