### ISSUE TITLE
Issue with DNS over HTTPS when using Cisco VPN

### ISSUE THREAD

**Issue by ehoffman2** [MrAlex94/Waterfox#2365]
### What happened?

Running the new G4 4.0.0.1 work flawlessly until I connect to work PC with Cisco Anyconnect.
Using Linux (Kubuntu 20.04)

The thing is that the VPN connection does not re-route the default gateway.  It's just an added, non-intrusive, route.

Normal route:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         RT-AC66U_B1-264 0.0.0.0         UG    100    0        0 eth0
link-local      0.0.0.0         255.255.0.0     U     1000   0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.10.0    0.0.0.0         255.255.255.0   U     100    0        0 eth0
192.168.20.0    0.0.0.0         255.255.255.0   U     0      0        0 vmnet8
```
With Cisco VPN:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.10.1    0.0.0.0         UG    100    0        0 eth0
link-local      0.0.0.0         255.255.0.0     U     1000   0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.240.0   U     0      0        0 cscotun0
p.....002.p.... 0.0.0.0         255.255.255.255 UH    0      0        0 cscotun0
p.....003.p.... 0.0.0.0         255.255.255.255 UH    0      0        0 cscotun0
172.18.99.0     0.0.0.0         255.255.255.0   U     0      0        0 cscotun0
192.168.10.0    0.0.0.0         255.255.255.0   U     100    0        0 eth0
192.168.10.1    0.0.0.0         255.255.255.255 UH    0      0        0 eth0
192.168.20.0    0.0.0.0         255.255.255.0   U     0      0        0 vmnet8
192.168.36.0    0.0.0.0         255.255.255.0   U     0      0        0 cscotun0
192.168.37.0    0.0.0.0         255.255.255.0   U     0      0        0 cscotun0
192.168.96.0    0.0.0.0         255.255.248.0   U     0      0        0 cscotun0
...-..-..-....s 192.168.10.1    255.255.255.255 UGH   0      0        0 eth0

(Note that I obfuscated sensitive IP/names)
```

So, the default route is the same.

The only think I could see is that the Cisco AnyConnect creates a route entry 192.168.10.1/32 (my default gw) to 0.0.0.0 with metric 0.  Not sure why.  However, this seems to only affect Waterfox.  Could this affect TLS only?

Old Waterfox, and newer Firefox, works perfectly.  But Waterfox G4 4.0.0.1 will not render a lot of the sites.  For example, Youtube does not work at all.

Going to dev console, in the network tab, I see the request, but never see a response.  Wireshark does show TLS activity though.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by ehoffman2** [comment]
After further testing, one thing that the VPN put in place is changes to the DNS resolver.  It insert my company's DNS first, followed by the original DNS.

I managed to make Waterfor work properly by either:
- In Waterfox network settings, change proxy setting from "Use system proxy settings" to "No Proxy"
or
- Disable "Enable DNS over HTTPS".

Hope this help...

Eric

Edit: The first workaround does not work, it's really HTTPS over DNS.

I tries using the same resolver as I have in Firefox by using custom provider with CIRA Canadian Shield (149.112.121.10 or 149.112.122.10) and still have issues.  If I disable DNS over HTTPS it works (and if I'm not connected VPN to work, it works).

As said, the traffic is routed to my home gateway directly to the cloud (default traffic is not routed through Cisco tunnel)

**Comment by MrAlex94** [comment]
Thank you for the work! HTTPS over DNS should now be off by default https://github.com/WaterfoxCo/Waterfox/commit/cdcb65585660081227b74e850e9d2e2dc3ea023d - I can only assume Firefox will have the same issues, so will close this bug.

If you do think this is just Waterfox specific though, do let me know and I'll re-open this bug 👍
