### ISSUE TITLE
Waterfox G4 v4.0.1 on a new system has no status and no tabs bar control

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2366]
### What happened?

If you install  **Waterfox G4 v4.0.1**  on a system that never had Waterfox installed before, you get zero Status Bar, no ability anywhere to get the Status Bar to show, and your tabs are at the top above the address bar, and you get zero Tabs Bar position control in the user interface.  Changing the settings in  about:config  does not work either.

I installed in  C:\Program Files\Waterfox-G4\

If, however, you uninstall v4.0.1, install 4.0.0.1, and then install v4.0.1 over the top of 4.0.0.1, then you get everything back.
 Luckily I had saved 4.0.0.1, just in case (from experience!).

Just extraordinary !

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Artanejp** [comment]
I started 4.0.1 Linux/x64 build, this issue has not reproduced, at least initially.

**Comment by adamp01** [comment]
@Objectivite - could you include browser console (ctrl+shift+j) output and some screenshots of about:preferences for this please? I am unable to replicate this behaviour.

**Comment by MrAlex94** [comment]
We've pushed a few updates since then, and since we never get responses this issue will be closed.
