### ISSUE TITLE
Improved password generator

### ISSUE THREAD

**Issue by BananasGoMoo** [MrAlex94/Waterfox#2368]
I really like having a password generator built into Waterfox(/Firefox), however the default generator by Firefox does not include symbols, which is an issue for some sites. I was hoping the generator could be improved to include symbols (ie: !?%$ etc.)

Other password generators such as LastPass include options for adding symbols. If you could also add an option in the settings to enable it that would be ideal, but just changing the default generator would be fine too, I think.

I'm not sure how many other people use the password generator but I think improving it over the default Firefox one would be good since it seems like they aren't really working on improving it at the moment.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
The function of generating special characters was [already implemented](https://github.com/WaterfoxCo/Waterfox/blob/current/toolkit/components/passwordmgr/PasswordGenerator.jsm#L29), but for some reason is not enabled by default in generator.

**Comment by MrAlex94** [comment]
> The function of generating special characters was [already implemented](https://github.com/WaterfoxCo/Waterfox/blob/current/toolkit/components/passwordmgr/PasswordGenerator.jsm#L29), but for some reason is not enabled by default in generator.

I believe this is based on the domain name, per [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1686071).

Problem is, different websites have different password rules and IMHO a lot of them are inconsistent and complex with no reasoning behind them. For example, `P4$sword` is not a better password than `hJuLYevYmr6lkVTXRL2TU3xlHUzmn`, yet a lot of websites would not allow the latter but require the former instead.

I believe by default it's set to the lowest common denominator for what will work with most websites (randomly capitalised alphanumeric). Then if a popular website has special requirements, it's added to RemoteSettings.

I'm not sure there's an easy way to solve this problem without UX clutter.
