### ISSUE TITLE
Colours in userChrome.css don't work with System theme in 4.0.1

### ISSUE THREAD

**Issue by Wonderer0** [MrAlex94/Waterfox#2369]
### What happened?

When WF upgraded itself to 4.0.0.1 I didn't like the new appearance, so downloaded and manually installed the Lepton theme from [black7375/Firefox-UI-Fix](https://github.com/black7375/Firefox-UI-Fix).  I was using WF's built-in System theme, and I tweaked the Lepton theme's `userChrome.css` to make the colours even more like my Windows theme (`--lwt-accent-color:  --moz-accent-color`, `--tab-selected-bgcolor: Highlight`).  Everything was looking as expected.

However when WF updated itself to 4.0.1 the colours specified in `userChrome.css`no longer seemed to take effect if the System theme was being used, but they did if the Light theme was being used.  Other style features, such as the shape of the tabs, remained OK, which indicated that `userChrome.css` was still being used.

I was using my tweaked `userChrome.css` and a high contrast Windows 10 theme that uses a tweaked `aerolite.msstyles`.  However the problem still occurs when using the original Lepton theme and the normal "Windows (light)" theme (which doesn't use the tweaked `aerolite.msstyles`).  In this case the toolbars should change colour to `rgb(229, 229, 235)`, but remain white if the System theme is being used.

When I downgraded WF to 4.0.0.1 the colours returned be being as expected.  They are also correct in Firefox (93.0) when the Lepton theme is installed.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Hi! Could you try using one of the Dark/Light compact themes?

**Comment by Wonderer0** [comment]
Hi

The situation is more complicated than I first realised.  Below are the results of some tests for 4.0.0.1 and 4.0.1 using the 7 built-in themes and two compact ones that I downloaded.  Searching for "compact theme" didn't find an obvious Compact Light or Compact Dark, so I tried the two below.

The tests were all run under the following conditions:
- Windows Light theme.
- Lepton's `userChrome.css` tweaked to make the colours more obvious: `--lwt-accent-color: yellow` (affects toolbars), `--tab-selected-bgcolor: red` (affects selected tab).
- Density set to "Compact (not supported)". (But it does seem to affect the density).
- Themes were enabled from `about:addons`, then WF restarted using "Clear startup cache..." in `about:support`.  This is because sometimes the colours worked OK immediately after enabling the theme but didn't after WF was restarted.
- Unfortunately I did these using my normal profile, but can try repeating them using a new default one if necessary.

"Y"/"N" show which colours were/weren't as expected:

|       | 4.0.0.1  | 4.0.0.1   | 4.0.1    | 4.0.1     |
| ----- | :------: | :-------: | :------: | :-------: |
| **Theme** | **Toolbars** | **Sel'd tab** | **Toolbars** | **Sel'd tab** |
| Waterfox Lepton | Y | Y | Y | Y |
| System | Y | Y | N | N |
| Light | Y | N | Y | N |
| Waterfox Australis Light | N | N | Y | N |
| Dark | N | N | N | N |
| Waterfox Australis Dark | N | N | N | N |
| Waterfox Alpanglow | N | N | N | N |
| Simple Compact Grey | N | N | N | N |
| Compact Design | N | N | N | N |

**Comment by Wonderer0** [comment]
Hi

The situation is more complicated than I first realised.  Below are the results of some tests for 4.0.0.1 and 4.0.1 using the 7 built-in themes and two compact ones that I downloaded.  Searching for "compact theme" didn't find an obvious Compact Light or Compact Dark, so I tried the two below.

The tests were all run under the following conditions:
- Windows Light theme.
- Lepton's `userChrome.css` tweaked to make the colours more obvious: `--lwt-accent-color: yellow` (affects toolbars), `--tab-selected-bgcolor: red` (affects selected tab).
- Density set to "Compact (not supported)". (But it does seem to affect the density).
- Themes were enabled from `about:addons`, then WF restarted using "Clear startup cache..." in `about:support`.  This is because sometimes the colours worked OK immediately after enabling the theme but didn't after WF was restarted.
- Unfortunately I did these using my normal profile, but can try repeating them using a new default one if necessary.

"Y"/"N" show which colours were/weren't as expected:

|       | 4.0.0.1  | 4.0.0.1   | 4.0.1    | 4.0.1     |
| ----- | :------: | :-------: | :------: | :-------: |
| **Theme** | **Toolbars** | **Sel'd tab** | **Toolbars** | **Sel'd tab** |
| Waterfox Lepton | Y | Y | Y | Y |
| System | Y | Y | N | N |
| Light | Y | N | Y | N |
| Waterfox Australis Light | N | N | Y | N |
| Dark | N | N | N | N |
| Waterfox Australis Dark | N | N | N | N |
| Waterfox Alpanglow | N | N | N | N |
| Simple Compact Grey | N | N | N | N |
| Compact Design | N | N | N | N |

**Comment by MrAlex94** [comment]
Thank you for the detailed issue report - very helpful! 

Just to clarify:

> When WF upgraded itself to 4.0.0.1 I didn't like the new appearance, so downloaded and manually installed the Lepton theme from black7375/Firefox-UI-Fix.

The default theme is the same as the one you manually installed - is there any reason for the difference? Or was it so you could tweak the colours?

As for the columns - I'm assuming Toolbars/Sel'd tab is meant to be for each specific version rather than you testing on the same version twice; from what I gather Lepton is the only one that applies correctly with userChrome changes?

This is odd as I'd expect `System` to be the one to handle everything appropriately since it is the only "unstyled" theme.

I can't imagine your changes working with every theme, but since they work with Lepton is the desired outcome not achieved?

**Comment by Wonderer0** [comment]
> The default theme is the same as the one you manually installed - is there any reason for the difference? Or was it so you could tweak the colours?

> I can't imagine your changes working with every theme, but since they work with Lepton is the desired outcome not achieved?

I originally installed Lepton manually to tweak the colours to make them as close as possible to my Windows theme.  But then tweaked it to remove the icons in the menu bar (File ...), and also to prevent the close-tab crosses from appearing when going to select a tabs.  I kept closing them instead of selecting them when the tab-bar is crowded.

black7375 has lots of very useful [tips](https://github.com/black7375/Firefox-UI-Fix/wiki/Tips) for customising Lepton, and I might also want to apply some others.  I didn't investigate how to tweak the WF Lepton extension, but assumed that my changes would be undone whenever the extension is updated.  This is why I installed the theme manually.  It also enabled me to use the WF System theme underneath, which was the best at keeping my system colours.

> As for the columns - I'm assuming Toolbars/Sel'd tab is meant to be for each specific version rather than you testing on the same version twice; from what I gather Lepton is the only one that applies correctly with userChrome changes?

Columns 2 / 3 show whether or not the toolbars / selected-tab had the correct colours in 4.0.0.1.  Columns 4 / 5 show the results of the same experiments after upgrading to 4.0.1.  (You might have been looking at an earlier version of the table that had incorrect version numbers for about an hour.  I was interrupted while correcting them, and ended up with two copies of the comment).  Yes, Lepton is the only one at enables the colours to be applied correctly in both releases.

> This is odd as I'd expect System to be the one to handle everything appropriately since it is the only "unstyled" theme.

This is exactly what the way I would like it to work.  A thin layer of styling that passes through the Windows theme as much as possible, but can be overridden by custom styling in userChrome.css and userContent.css (I have also tweaked the latter to restore Windows scrollbar colours).  Unfortunately those colours in userChrome.css, and possibly others, no longer take effect. 

Most of the statements in `userChrome.css` are `!important`, presumably so that they override the built in ones.  Could it be that some of the built in ones have also been made `!important`, and so can no longer be overridden?

**Comment by Wonderer0** [comment]
The problem described above comes about when trying to use the built in System theme, which I now realise is apparently is no longer present in the latest releases of WF.  How is it that it is still useable at all, is it still partly implemented?

Disabling all themes, as described in issue #2416 makes the colours correct, i.e the same as they used to be in G3 and still are in Firefox.  So if a more user-friendly way can be found to disable them all, for example by a tick box, that would solve the problem.

I had hoped that the Empty Theme I created would have the same effect as disabling all the themes, but it makes the tab-bar background white rather than the system colours.  Why is this, what's the difference between an empty theme and not having any theme enabled?  Is there a way for me to create a theme that has the same effect as not having any theme enabled?

**Comment by MrAlex94** [comment]
You can now customise the look and feel by going to Settings > Look & Feel, which allows you to disable completely any customisations we've made.
