### ISSUE TITLE
Address bar not auto-focusing properly on new windows

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2370]
### What happened?

I recently switched to Waterfox from Firefox after... accidentally updating Firefox and letting forced Proton take over it.
So far it's been pretty good but my ONLY issue with it is that which the title mentions.

Opening a new window via the keyboard shortcuts (Ctrl+N normally, Ctrl+Alt+P for private ones) does not seem to effectively highlight the address bar for immediate typing, and I have to manually click on it for it to properly focus.
Which is odd behavior, because the address bar DOES highlight in blue as if it was in focus, it just does not respond to keyboard input. It works fine in new TABS, just not in new WINDOWS.

I can use F6 to "properly" highlight it, but it requires two presses as the first one seems to "unfocus" it because it believes it's actually in focus.

This was not an issue in Firefox, which I switched from today.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@LazierTomato - Thanks for raising this - I'll work on a solution for (hopefully) the next release.
