### ISSUE TITLE
Tabs in wrong location on secondary browser windows after restart

### ISSUE THREAD

**Issue by dochego** [MrAlex94/Waterfox#2376]
### What happened?

With settings: "Restore previous session" and Tab bar position "Top below address bar":

- Open a second browser window, and open a website there. Tabs are in the correct position (below address bar).
- Close browser.
- Start browser again. Two browser windows open, but only in the first one are the tabs in the correct location (below address bar). In the second browser windows, the tabs are shown above the address bar, with no possibility to move them below the address bar.

Reproduced in new (empty) profile with no extensions.

Might be related to issue #2362 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux, Windows

**Comment by adamp01** [comment]
@dochego - thanks for this, I'll aim to push a fix tomorrow.

**Comment by Yay295** [comment]
Was a fix for this added? I just updated to 4.0.2 and I'm seeing this issue.

**Comment by adamp01** [comment]
@Yay295 - Not yet, I have been pulled onto some other issues but this is near the top of the priority list.

**Comment by adamp01** [comment]
Apologies for the delay on this one, but should now be fixed in G4.0.4. Please re-open the issue if that isn't the case for you.
