### ISSUE TITLE
impossible to upgrade to 4.

### ISSUE THREAD

**Issue by Pliut** [MrAlex94/Waterfox#2379]
### What happened?

A bug happened!

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
G3.2.6 (64-bit) seems to be up to date , when I try to upgrade still remain this old version
```

**Comment by InvisibleManX** [comment]
Firstly, try to check and confirm that your computer supports G4, as explained in this post: 

https://github.com/WaterfoxCo/Waterfox/issues/2377#issuecomment-954881930

**Comment by Jaitsu** [comment]
Same thing on my PC. Oddly, my laptop updated fine. About Waterfox page just says "Waterfox is up to date."

**Comment by MrAlex94** [comment]
We withheld the automatic updates while we ironed out some issues - they should now be available!
