### ISSUE TITLE
Google and Startpage search suggestions not working

### ISSUE THREAD

**Issue by Jaitsu** [MrAlex94/Waterfox#2380]
### What happened?

Google Search and Startpage suggestions are once again not working, possible recurrence of #1163. Bing, Ecosia, DuckDuckGo, etc. are working normally.
![example-google](https://user-images.githubusercontent.com/463807/139501792-2065dbfe-b0c0-440d-9317-6ca4338d86cb.png)
![example-bing](https://user-images.githubusercontent.com/463807/139501799-fe4135df-3abf-4b75-b060-a54891e76608.png)

### Reproducible?

- [x] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by BananasGoMoo** [comment]
happening for me again as well.

**Comment by stu-carter** [comment]
Also occurs for me on G4.0.2.1 (64-bit Windows).  Thanks.

**Comment by apfsx** [comment]
Also happens for me. Has anyone discovered a workaround?

**Comment by dfgrgavr** [comment]
Same problem here. I think i revert back to g3.xx . I hope that will not mess everything...

**Comment by Avrution** [comment]
Really figured this issue would be fixed by now.  I'm sure if it was related to Bing and revenue for using that engine it would have been more of a priority.

**Comment by dfgrgavr** [comment]
Problem is still in 4.0.3.1.  :(

**Comment by adamp01** [comment]
Google is fixed: https://github.com/WaterfoxCo/Waterfox/pull/2479
