### ISSUE TITLE
G4.0.2 about:addons - themes is broken

### ISSUE THREAD

**Issue by Pizzapops** [MrAlex94/Waterfox#2386]
### What happened?

The graphics for themes are not displayed for themes from Mozilla.org. 
Only basic themes included with Waterfox have a graphic display.
**Waterfox** with NO Chrome mods
![2021-11-03_H2Ofox_1](https://user-images.githubusercontent.com/33039961/140013485-0eae616d-f57c-4d19-bca4-52587520195f.jpg)
**Firefox ESR, 94, Beta and Nightly** with Aris & my UserContent.css mods
![2021-11-03_Fx_ESR](https://user-images.githubusercontent.com/33039961/140013618-d07ae562-7367-479c-8984-97d0f4c49bcf.jpg)
**Waterfox**  with Aris & my UserContent.css mods
![2021-11-03_H2Ofox_2](https://user-images.githubusercontent.com/33039961/140014184-72f13807-2df6-4f5d-9705-5d78d6437418.jpg)
When upgrading G3 to G4, I noticed this right away. I wiped Waterfox off my computer (including ALL profiles) and did a fresh install. First graphic is the results. This was not a problem with G3.2.6.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
From the [release notes](https://www.waterfox.net/docs/releases/G4.0.2):
> You can now toggle `extensions.getAddons.cache.enabled` to populate extension information in `about:addons`.

After setting the value to `true`, it'll take a bit to update.

**Comment by Pizzapops** [comment]
@MrAlex94 
Thanks for the quick response.  Updating meant deleting and re-adding themes. It worked but was very slow.
