### ISSUE TITLE
graphics not displaying on a webshop ...

### ISSUE THREAD

**Issue by tom-r** [MrAlex94/Waterfox#2387]
### What happened?

try this link please 

https://www.bobshop.com/de/castelli/winterjacke-alpha-ros-2-2/
It's a normal webshop ... 
It displays OK (with graphics, tumbnails, pictures) in waterfox G2.3.6, chromium, opera, firefox 93 (the latest available on Fedora 34), but not in waterfox G4.0.1 and G4.0.2
There are simply empty frames for all graphics.
Same problem with all plugins disabled.
![grafik](https://user-images.githubusercontent.com/1923035/140020808-c9297731-922b-4ceb-bec5-89c29efd87a2.png)

It should look like (CBP screenshot)
![grafik](https://user-images.githubusercontent.com/1923035/140020959-af5dc5cc-d171-4b57-86e0-1816f2115a63.png)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Wow, that website has a lot of scripts and a lot of error message, with adblock and tracking protection off.

 I can reproduce the issue - it's most likely a preference flipped for privacy causing the issue, more unlikely but still possible is it could have an issue with the Waterfox user agent. Will look into it.

**Comment by MrAlex94** [comment]
This works properly in G5, with Adblock and tracking protection on 👍
