### ISSUE TITLE
Ability to change Re-open in Private Tab Shortcut

### ISSUE THREAD

**Issue by GuestJim** [MrAlex94/Waterfox#2391]
While the ability to open a private tab is nice, the "T" shortcut has proven problematic for me multiple times. When a field is focused, this single-key shortcut usually is not a problem, but I have encountered situations where a field loses focus on its own as I'm typing. This can result in losing whatever I was working on, because the contents of the form is wiped when it is reopened in a private tab.

My suggestion is to give the user the ability to change the Re-open in Private Tab, and possibly all keyboard shortcuts. Especially with this being a single-key shortcut and with such potential to disrupt workflow, making this a built-in feature seems reasonable to me.
Changing it to a different shortcut would also be fair, though I haven't a specific one to suggest, but I do think opening up shortcuts to the user would be a very desirable feature overall. Plus, if you have the list of shortcuts to change, you also have the list of shortcuts. I can't suggest a different shortcut for re-opening in a private tab because I don't know what any others are, and what might prove to be a conflict.

**Comment by adamp01** [comment]
@GuestJim - The Private tab "T" only shortcut was a bug, it was supposed to be "Ctrl+Alt+T". This has been rectified in the latest version.

**Comment by GuestJim** [comment]
Hadn't seen it reported as a bug, or mentioned in the change logs, so thanks for the information. I still think a built-in means of changing keyboard shortcuts would be a good feature, but with this change the need is certainly reduced.
