### ISSUE TITLE
Turn Off Update Notice

### ISSUE THREAD

**Issue by pokerino** [MrAlex94/Waterfox#2392]
Since I changed from Firefox to Waterfox, I have been relatively satisfied, but now in G4 I see that Waterfox begins to have the same problem I had with Firefox. When I still very satisfied with G3.2.6 I would be happy to stay on this version and not update again. 

What I wish is an opportunity to turn off the annoying recurring reminder of Update and Have An Options to Never Update Again. 

Another solution could be to provide more options in newer versions to allow functions and GUI to change in newer versions.

**Comment by this-is-your-do** [comment]
See https://github.com/WaterfoxCo/Waterfox/issues/2330#issuecomment-947591210 for disabling update notifications while G4 continues to have regressions from G3.

**Comment by MrAlex94** [comment]
We added an option in G5 to disable auto-updates.
