### ISSUE TITLE
Theme previews not being displayed - Again !

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2394]
### What happened?

This issue was closed but is not fixed.

Do the developers even TEST their fixes ???  All one has to do is .... TEST !!!  The names of the themes are in the screenshot, all that is needed to fix things is basic ...... TESTING !

**Waterfox**

![image](https://user-images.githubusercontent.com/89191739/140438318-bcc2e857-412b-4148-9bac-49952d462d29.png)

**Firefox**

![image](https://user-images.githubusercontent.com/89191739/140438588-4d17a01b-0740-4537-be29-ceb1258a141f.png)

O.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
If you open an issue again without replying to the previous ones, I will have to remove your permissions for opening issues.

Set `extensions.getAddons.cache.enabled` to `true` and a wait a while for it to populate with data if you want theme previews.

The previous issue you opened and failed to reply to has this information in it: https://github.com/WaterfoxCo/Waterfox/issues/2358
