### ISSUE TITLE
Tubi DRM ISSUES 

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#2395]
### What happened?

When l Sign In on Tubi to watch Movies I keep getting DRM issues do not get this with Firefox, Chrome
So I can not watch movies on this Site even in Safe Mode ...
It also times out on Pluto TV as well watching Programs or Movies.... 

This is persistent 
Running Latest 64 Bit 78.14.0 G3.2.6 
Either on Windows 7 64 Bit or Windows 10 PC's and Laptops...
All Machines are clean not Spyware, Malware, or Virus 

All Codec's updates. 

Cleared Cache no good
Safe Mode does not work, 

![image](https://user-images.githubusercontent.com/20975332/140447723-8b144f97-1691-4f7c-b5f3-7c18650967d9.png)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by wkuzma** [comment]
I have the same problem

**Comment by MrAlex94** [comment]
G5 has updated DRM. Does this issue still occur? We can't test due to not being in the US.

**Comment by wkuzma** [comment]
seems to be ok for me

**Comment by A0R-R0CKS** [comment]
My PC will not support G4 or G5 or I would of switched. The CPU does Not support SSE4.2 which is why G4 and G5 will not install. I am on Fixed Income / Disability after I spent 6 months in a Hospital for both a Stroke and Heart Attack. So I got to make my PC get by a while longer. If I could update the DRM Codecs that would get me by on things a while.
