### ISSUE TITLE
Line at bottom of screen, Noticeable at Full screen when watching videos

### ISSUE THREAD

**Issue by gallonmate** [MrAlex94/Waterfox#2398]
### What happened?

There's a line at the bottom of the browser at all times. Most noticeable when viewing a webpage or video full screen, and opposite of the theme color of the browser. For example with light themes, Full screen, there will be a white line along the bottom of the browser. The line changes colors with themes, so it's UI issue. Reported on both Windows and Mac Os. Work around is changing the theme of the browser to match the color of the current viewed content in the browser.

https://www.reddit.com/r/waterfox/comments/qdhfcc/g4_has_white_border_at_bottom_of_window/
https://www.reddit.com/r/waterfox/comments/qnl6bs/full_screen_introduces_white_line_along_bottom_of/hjhddud/?context=3

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

macOS, Windows

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/270e8b3c5145950aa773f8a52f4187f27c113f02
