### ISSUE TITLE
Waterfox G4.x doesn't works on Windows 8.1

### ISSUE THREAD

**Issue by katar7** [MrAlex94/Waterfox#2400]
### What happened?

Hello.
When I try to start Waterfox G4.x, it crashes with the message shown in the attachment (sorry for the Russian).
I deleted the user data, but it does not help.

![waterbug](https://user-images.githubusercontent.com/74004757/140605783-b6e23713-adaa-4dd7-8b3d-467d8241e12e.png)

### Reproducible?

- [x] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Waterfox G4 requires SSE4.2. Does your CPU support it?

**Comment by katar7** [comment]
> 
> 
> Waterfox G4 requires SSE4.2. Does your CPU support it?

No, he doesn't support it. Thanks for your help
