### ISSUE TITLE
Miss "Re-start with add-ons disabled"

### ISSUE THREAD

**Issue by ZTrainor** [MrAlex94/Waterfox#2402]
"Re-start with add-ons disabled" really came in handy sometimes.  Hoping it will be restored in a future release.  Thank you.

**Comment by MrAlex94** [comment]
If you go to `about:profiles` there is a button to "Restart with Add-ons Disabled":

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/4728920/140727307-d9bcb6e3-cf23-4e2d-b382-42cf10f1f5b7.png">

Would you find it beneficial having this in a more accessible location?

**Comment by ZTrainor** [comment]
Thank you so much!  Really appreciate this!
