### ISSUE TITLE
[BUG] Waterfox does not allow adding keywords to custom search engines.

### ISSUE THREAD

**Issue by pyrox0** [MrAlex94/Waterfox#2403]
### What happened?

I wanted to add an `@gh` keyword to search github, but when I entered it, it disappeared. This problem does not appear in firefox.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

macOS

### Relevant log output

```shell
N/A
```

**Comment by MrAlex94** [comment]
Tested in G5, this should work as expected! `@gh` expanded to the below:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/4728920/194115661-7797de99-6647-4469-966c-24b626671db5.png">
