### ISSUE TITLE
Fav Icon and Status Bar issues

### ISSUE THREAD

**Issue by satovey** [MrAlex94/Waterfox#2406]
### What happened?

A bug happened!Waterfox Current;
On YouTube.com when opening a new tab, the fav icon does not appear.

![YouTube Fav Icon Issue](https://user-images.githubusercontent.com/458436/140654082-721bd93d-e664-4f19-af92-7b6a9f7e320a.JPG)

Waterfox does not always maintain the visible status bar selected option. On two occasions, I have had to go into view - Toolbar and recheck status bar.

Firefox left me, so firefox is not installed on my system.

Waterfox 4.0.2.1
Windows 8.1
The drop down boxes on this page do not select in Waterfox classic.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Status bar issues should be resolved.

And YouTube icon will be hidden behind the "a video is playing in this tab" icon, by design.
