### ISSUE TITLE
Youtube randomly hangs and maxes CPU after update from G3 to G4.0.2.1

### ISSUE THREAD

**Issue by AkazaAkarinn** [MrAlex94/Waterfox#2408]
### What happened?

Updated directly from G3 to G4.0.2.1. Soon noticed an issue with Youtube. Occasionally when watching a video and then opening a new video or going back to Youtube home via the icon in the top left corner of the page (both within the same tab), I experience a browser hang up during the loading process where the page freezes on the current video and Waterfox maxes out my CPU usage at around 98-99%. The browser recovers relatively quickly, especially if I try closing the offending tab. It has yet to cause the entire browser to crash or my PC to crash. I can't really pin down what causes it to occur, sometimes the new video/home loads fine, other times I get the hangup. It does seem to occur more often or possibly only when the current video is playing at the time (haven't confirmed this yet). It also occurs when going from a video to a channel page. 

Naturally this never happened on G3 nor have I experienced max CPU spikes except when trying to open many tabs at once. Hardware acceleration was on in G3 and is still on now. Also disabled Enhanced Tracking Protection for Youtube because I think I had to do this in G3 plus I'm using ublock and Noscript anyway. Issue also happens across themes. I have also updated my graphics drivers to the latest one, but this didn't resolve it either. I'm using Win8.1 with an i7-6700K CPU and 6GB GTX 1060.

Furthermore, occasionally when using other programs with Waterfox minimized, when I go to bring up Waterfox I get a empty screen (colored the same as my system background color) briefly before the Waterfox/tab shows back up. This doesn't appear specific to Youtube though. 

Here's another [user ](https://www.reddit.com/r/waterfox/comments/qn1mps/youtube_randomly_hangs_and_maxes_cpu_after_update/hjnjf0e/ )who is experiencing this issue and is also using Windows 8.1 and using a GTX card and intel processor. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Unfortunately this is likely to relate to platform changes. If this hasn't improved in G5, there's not much we can do sadly.

**Comment by kopach** [comment]
I'm experiencing this in G5, unfortunately. I'm using MacOS 12.6.1
