### ISSUE TITLE
bookmark bar always at top

### ISSUE THREAD

**Issue by nixedit** [MrAlex94/Waterfox#2410]
### What happened?

A bug happened!
I have the bookmarks bar set to "bottom" within the settings, however whenever G4 launched, the bookmarks bar is always at the top of the window. when I go back into settings, it's still marked as bottom.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
This should've been fixed in a G4 update from a while ago.
