### ISSUE TITLE
Status bar disappears when closing and reopening Waterfox

### ISSUE THREAD

**Issue by this-is-your-do** [MrAlex94/Waterfox#2411]
### What happened?

Even though I've enabled the status bar in Settings, when I close and reopen waterfox - the status bar is back to being disabled (and I have to enable it in Settings again).

Sometimes, it takes 2 close-and-reopens of waterfox for the bug to occur, but never more, it appears.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Objectivite** [comment]
> 
> ### What happened?
> 
> Even though I've enabled the status bar in Settings, when I close and reopen waterfox - the status bar is back to being disabled (and I have to enable it in Settings again).
> 
> Sometimes, it takes 2 close-and-reopens of waterfox for the bug to occur, but never more, it appears.
> ### Reproducible?
> 
>     * [ ]  I have tested this on Firefox.
> 
> 
> ### Version
> 
> G4.𝑋 (Future)
> ### What platform are you seeing the problem on?
> 
> Windows
> ### Relevant log output
> 
> _No response_

I can very easily reproduce this bug in 4.0.2.1.

It only takes one CLOSE of Waterfox in my case.  Constantly have to re-enable it in **Settings**.

O.

**Comment by Avrution** [comment]
Also plagued with this issue at least 50% of the time.

**Comment by MrAlex94** [comment]
Can you test with `G4.3.0.1` and see if the issue still occurs?

**Comment by Objectivite** [comment]
This has been fixed with  G4.3.0.1

O.

**Comment by Avrution** [comment]
Fixed
