### ISSUE TITLE
Synchronize bookmarks on Waterfox G4.0.2.1(64 bits) on Windows 10 Pro

### ISSUE THREAD

**Issue by PauloLaScience** [MrAlex94/Waterfox#2415]
### What happened?

I'm trying to synchronize Firefox account on Waterfox G4. Extensions, Passwords are working but history and bookmarks are not working and stay empty. I try also to import from html or restore backup didn't work.
See [https://github.com/WaterfoxCo/Waterfox/issues/2414](#2414)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Unfortunately not much we can do on our side regarding this, as we don't touch much of the Sync modules.
