### ISSUE TITLE
User Agent issues in v4.0.2.1  (not present in 4.0.1)

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2419]
### What happened?

www.bloomberg.com/europe  complains about using a browser called Waterfox 91.3.1.

This problem  **does NOT happen**  in v4.0.1,  only in the latest v4.0.2.1  and it is obvious why as the user agent is incorrect.

![image](https://user-images.githubusercontent.com/89191739/141260526-c64de408-dd71-467e-b46e-e357a51d5619.png)

O.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
https://github.com/WaterfoxCo/Waterfox/pull/2494

**Comment by Objectivite** [comment]
Thanks Adam - All Good.

O.
