### ISSUE TITLE
TabMixPlus incompatibilities with Lepton and Australis themes.

### ISSUE THREAD

**Issue by JohnEdwa** [MrAlex94/Waterfox#2423]
### What happened?

I noticed that [TabMixPlus](https://github.com/onemen/TabMixPlus) seems to have incompatibilities with the Lepton and Australis themes, I would assume because they use CSS IDs or overrides that aren't what TMP expects them to be.

Not sure if it's something that can be fixed from Waterfoxes side, or if it would need special handling in TabMixPlus, but I though I'd report it here first anyway as making Waterfox be as compatible with default FF addons as possible seems like the better solution in contrast to requiring addons to add support individually.

Tab Width set to 150-250px, with 3-row multi-tab bar: 
How it should be, dark theme:
![image](https://user-images.githubusercontent.com/5417183/141656239-de805ebf-d765-4be6-a53f-6b0202b0d4fb.png)

Australis, completely broken.
![image](https://user-images.githubusercontent.com/5417183/141656246-e008f259-8403-49d6-8e8c-3603f1ad1518.png)

Lepton, last row missing.
![image](https://user-images.githubusercontent.com/5417183/141656252-1542a316-cd9d-4a14-bdce-337719690338.png)

---

[EDIT]

For Lepton, the width of the tabs is being overridden by:
```
userChrome.css:1181 @(-moz-proton)
	.tabbrowser-tab[fadein]:not([pinned]):not([style*="max-width"]) {
		max-width: 240px !important;
	}
```
And the multirow tab bar is broken by:
```
userChrome.css:1212 @(-moz-proton)
.toolbar-items, .tabbrowser-tab {
--tabbar-max-height: 38px;
max-height: calc(var(--tabbar-max-height) + var(--space-above-tabbar));
}

userChrome.css:1217 @(-moz-proton)
:root[uidensity="compact"] .toolbar-items, :root[uidensity="compact"] .tabbrowser-tab {
--tabbar-max-height: 36px;
}

userChrome.css:1212 @(-moz-proton)
:root[uidensity="touch"] .toolbar-items, :root[uidensity="touch"] .tabbrowser-tab {
--tabbar-max-height: 45px;
}
```
disabling these fixes the issues.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
This won't be fixed, unless TMP wants to support those themes, but I can't imagine so. If you want to use TMP, use the Firefox themes, which should be available.
