### ISSUE TITLE
Customize toolbar: can't remove bookmark icon

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2427]
### What happened?

Small bug, something that was possible in G3. I can't remove the bookmark icon in the top bar when clicking 'customize toolbar
<img width="252" alt="Screenshot 2021-11-15 at 20 41 50" src="https://user-images.githubusercontent.com/91443226/141796830-f02f26d2-3ec0-433d-89c9-916d1b15d9f8.png">

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

macOS

**Comment by Objectivite** [comment]
> ### What happened?
> 
> Small bug, something that was possible in G3. I can't remove the bookmark icon in the top bar when clicking 'customize toolbar <img alt="Screenshot 2021-11-15 at 20 41 50" width="252" src="https://user-images.githubusercontent.com/91443226/141796830-f02f26d2-3ec0-433d-89c9-916d1b15d9f8.png">
> ### Reproducible?
> 
>     * [x]  I have tested this on Firefox.
> 
> 
> ### Version
> 
> G4.𝑋 (Future)
> ### What platform are you seeing the problem on?
> 
> macOS
> ### Relevant log output
> 
> _No response_

Drag it down to the  **INBUILT** icons below.  That works.

O.
