### ISSUE TITLE
Update 4.0.2.2 disables TabMixPlus

### ISSUE THREAD

**Issue by robvthof** [MrAlex94/Waterfox#2428]
### What happened?

I (manually) updated to 4.0.2.2
TabMixPlus was disabled. I tried re-starting and then re-installing TabMixPlus. 
It looks like it is active in the add-ons list but there is no menu in Tools and Tabs jump to top of windows. 

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

macOS

**Comment by MrAlex94** [comment]
This should be fixed with https://github.com/WaterfoxCo/Waterfox/commit/a5d8a7ffc5ab07d47a0cc871bcc25f34052f9fdc. Build will be released next week fixing it.

Please re-open if it doesn't.
