### ISSUE TITLE
G4.0.3 menu falls off the screen

### ISSUE THREAD

**Issue by strotee** [MrAlex94/Waterfox#2429]
### What happened?

I installed 4.0.3 and noticed the menu falls off the screen, the text gets chopped off when the browser is maximized. 

![Untitled](https://user-images.githubusercontent.com/15714473/142035343-9d156ac8-69f9-436b-bec5-fc1abcb6dfb2.png)

Edit: When one goes to Customize Toolbar, the menu shifts down (looks normal), then clicking Done it shifts the menu up/off-screen.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
This should now be resolved in `G4.0.3.1`.
