### ISSUE TITLE
4.0.3 - Incorrect pixel calculations --> Menu bars disappears off the top of the screen + Tab Bar position settings lost

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2430]
### What happened?

Have reverted to 4.0.2.1 as 4.0.3 is unworkable

Menu problem when maximized :+1: 
![image](https://user-images.githubusercontent.com/89191739/142039314-b09287d7-0745-44df-8a2c-e36a1c5f319e.png)

Also, The tab bar position settings were wiped out with this install - none of the 4 options were chosen so the tabs appeared in the middle of the Menu Bar !

Worse - even after setting the tab bar settings again, and the status bar settings, on restart they are both lost !

Phew !!!!

O.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Jaitsu** [comment]
+1. Even without the menu bar shown, the tops of tabs are being cut off (which is putting the tab X button in contact with the top of the screen, meaning clicks that would usually be above the button/tab are closing tabs.

**Comment by MrAlex94** [comment]
Can you test with `G4.3.0.1` and see if the issue still occurs?

**Comment by Objectivite** [comment]
> Can you test with `G4.3.0.1` and see if the issue still occurs?

This has been fixed in 4.3.0.1

O.
