### ISSUE TITLE
AUR bin package that updates automatically on release using github-actions

### ISSUE THREAD

**Issue by ItzYanick** [MrAlex94/Waterfox#2432]
**Is your feature request related to a problem? Please describe.**
I always love to have bin packages that install programs to my linux pc without any hassle. Having a AUR bin package with the precompiled bins would not only add a very easy way of installation but also a faster way as I would not have to self compile the code on my own hence installing all the dependencies for building.

**Describe the solution you'd like**
A addition to the github-actions files for the release cycle. These additions would automatically push a PKGBUILD to the AUR with the correct version tag in it. The PKGBUILD script will then download the newest release here from Github, extract it, put it into the right direction and will add a .desktop file for the desktop environment. This way we do not have to upload the package with the files to the repo. I already found this on the Github Marketplace that easily adds all that is needed. Only a functional PKGBUILD as well as a AUR account are in need ["Publish AUR package"](https://github.com/marketplace/actions/publish-aur-package).

**Describe alternatives you've considered**
One alternative would be to publish Waterfox to flatpak. This would also add the ability to let user outside of the Arch repo be able to download the browser without any hassle. The only thing to be considered would be to check if there is a way to automatically publish it using github-actions.

**Comment by hawkeye116477** [comment]
Package is already available on AUR => https://aur.archlinux.org/packages/waterfox-g4-bin.

**Comment by ItzYanick** [comment]
interesting... i was searching for waterfox on the AUR and I only found g3 and classic. It did not show me any g4 packages. Anyway thank you! I will therefore close this issue.
