### ISSUE TITLE
Global Menu Support Removed in Linux

### ISSUE THREAD

**Issue by Patlen123** [MrAlex94/Waterfox#2433]
### What happened?

G4 has removed global menu support from Waterfox which was patched back after Firefox removed it in in one of the early G3 versions

### Reproducible?

- [x] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by hawkeye116477** [comment]
Well, G4 was remade from scratch, no one added commit for global menu support. For G3 I made PR for it some time ago.
Maybe I'll see soon what can be done.

**Comment by weslyraji** [comment]
Can Global menu support be added to the new G5 release ?

**Comment by jobukkit** [comment]
It would be great if KDE global menu support could be added back to G6.

This may only be possible on X11, though.

**Comment by erydactyl** [comment]
Same here. I find it useful to use with a searchable HUD-like application

**Comment by hawkeye116477** [comment]
> Same here.

It's already available in G6.

**Comment by MrAlex94** [comment]
Indeed, it's a part of G6 now, so will close this.
