### ISSUE TITLE
G4.0.3 crashes when update is done will not launch

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#2434]
### What happened?

I tied to install the  G3.3.2.6 78.14.0 and it crashes when launching, 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Will need some more information.

- What version were you on before you upgraded?
- Did you auto-update or manually update?
- What are your hardware specs?

**Comment by A0R-R0CKS** [comment]
Currently G3.2.6 (64-bit) is what I am running
Manual Download and Update
AMD Phenom II AM3 X4 965 8MB 140W 3400MHz Black Edition 16 Gig Ram 4 Gig ATI Video Card....

**Comment by MrAlex94** [comment]
Unfortunately this processor lacks the required instruction sets for Waterfox to run.
