### ISSUE TITLE
Flash Pluggin 

### ISSUE THREAD

**Issue by Com874** [MrAlex94/Waterfox#2435]
### What happened?

So I installed the new update of Waterfox, I use the software for many things including Flash 
The new update however now makes it more harder to use the plugin. I thought at first  it was removed, only for me to find out about this....  "Plugins such as Flash can now be enabled, but require you to interact to have web pages run it for security reasons." I tried every step of enabling flash but I simply got no luck unlike last time.  May I have some assistance on this issue? (hoping that I'm not stressing anyone out)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by kirk86** [comment]
I have the exact same issue running waterfox on OSX. Verison G3xx worked just fine with flash but now I can't watch some lectures which are on old flash recording but still very important for me. Any help with this is much appreciated?

**Comment by gamer191** [comment]
> I tried every step of enabling flash but I simply got no luck unlike last time

I'm having the same issue, can you please tell me what the steps are? (I thought you just have to install flash 32.0.0.371 and interact with the website)

**Comment by kirk86** [comment]
I fixed this by uninstalling waterfox and installing [waterfox classic](https://github.com/WaterfoxCo/Waterfox-Classic)
