### ISSUE TITLE
Boostrapped Addons broken after browser restart

### ISSUE THREAD

**Issue by girst** [MrAlex94/Waterfox#2437]
### What happened?

Bootstrapped (legacy) addons are disabled after restarting the browser. dis-and re-enabling them in about:addons makes them run again.

affected version: 403

STR, in a clean profile:
1. install e.g. [VimFx](https://github.com/akhodakivskiy/vimfx/releases/tag/v0.24.5). Note that the addon works (toolbar icon present)
2. open browser console and restart waterfox (ctrl-shift-j, then ctrl-alt-r)
3. when the browser comes back, notice that vimfx' icon is gone and the browser console displays an error: 
  > Error: Cannot find loader for bootstrap XPIProvider.jsm:1902:15
4. in `about:addons`, dis- and reenable the addon. it will work again

This bug is present in Waterfox 4.0.3, but not in 4.0.2. The regression might be caused by https://github.com/WaterfoxCo/Waterfox/commit/2ed42c3d1a4ba955aeae11b74b129a0b365909ae#diff-cdac344cca10ffbd0e07538389cdfd4777eeb5a8dc586f8cdfe75e17dfee27cd, which changes when the BootstrapLoader is loaded. Since I'm not a Waterfox user, the time i want to spend debugging this is limited. I just ran 403 and 402 and compared results.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
JavaScript error: resource://gre/modules/addons/XPIProvider.jsm, line 1902: Error: Cannot find loader for bootstrap
```

**Comment by girst** [comment]
also, the linked commit's message suspiciously looks like a Jira-ticket-ID. I was unable to find the ticketing system, though. is this public?

**Comment by MrAlex94** [comment]
Should be fixed with https://github.com/WaterfoxCo/Waterfox/commit/a5d8a7ffc5ab07d47a0cc871bcc25f34052f9fdc

Have tested and add-ons persist through restarts.

Sorry about that!

> also, the linked commit's message suspiciously looks like a Jira-ticket-ID. I was unable to find the ticketing system, though. is this public?

The ticketing system is not public,  but all it's doing is tracking all the changes we make here.
