### ISSUE TITLE
Tab bar position

### ISSUE THREAD

**Issue by dfgrgavr** [MrAlex94/Waterfox#2438]
### What happened?

Hi!

First, thank your works, all the developers of waterfox.

In latest version of Waterfox (non classic), Tab bar position setting everytime reseted after second restart. 

To get rid this problem, i set the prefs.js file read only mode,  but im sure developers will repair in the next version, because its an inconvenient solution.

Thank you, and Keep up the good work guys!

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by gwin7ok** [comment]
The same is true for display setting of status bar

**Comment by MrAlex94** [comment]
Can you test with `G4.3.0.1` and see if the issue still occurs?

**Comment by gwin7ok** [comment]
That Issue does not happen at G4.3.0.1 Thank you for fixing

**Comment by dfgrgavr** [comment]
> That Issue does not happen at G4.3.0.1 Thank you for fixing

Can you confirm that tab bar position problem cured too? Thank you!

**Comment by dfgrgavr** [comment]
> Can you test with `G4.3.0.1` and see if the issue still occurs?

I will test soon, thank you for dealing with this.

**Comment by MrAlex94** [comment]
@dfgrgavr, please re-open if you see the issue still occurs.

**Comment by dfgrgavr** [comment]
> @dfgrgavr, please re-open if you see the issue still occurs.

Working fine! Thank you the fast repair. :)
