### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2440]
**Is your feature request related to a problem? Please describe.**

Well yes, it is sort of a problem with Firefox and this browser as there is no native translation feature.

**Describe the solution you'd like**

To be able to automatic or choose to translate web pages using Bing or Google without needing to open a new tab or such, basic translation like how it is in Edge or Chrome.

**Describe alternatives you've considered**

An extension but I cant' find any good ones.

**Additional context**

**Comment by MrAlex94** [comment]
https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/
