### ISSUE TITLE
Automatic update from 3.2.6 to 4.0.2.1 is a disaster --> suggests that not all required files/settings are overwritten/merged by install

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2446]
### What happened?

We forgot to disable automatic updates on two PCs, one a Windows 8.1 PC, the other one a Windows 10 Build 21H2.

In both cases the user's 3.2.6 Waterfox updated to 4.0.2.1. and the end-user then straight away complained.  The result was -

a)  Tab bar is at the bottom of the screen in one, and in the middle of the Favourites Bar in the othe !!

b)  Changing the Tab Bar settings makes no difference whatsoever.

c)  The only thing that works is starting a new profile with  ABOUT:PROFILES,
     which of course is a disaster for the end-user (cookies, passwords, themes, add-ons - we can at least restore
     the bookmarks from the previous profile).

This suggests that the install either does not thoroughly overwrites and/or merge some files and settings.

This, incidentally, has actually been the  **main problem**  across this whole 3.2.6 to any of the versions (4.0, 4.0.1, 4.0.2, 4.0.2.1, 4.0.3) saga.

And just to  **re-emphasize** :  it is not just the fact that the Tab Bar ends up in crazy positions, it is also the fact that there is no way to solve the problem, whether through Settings or about:config.

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by thecreator1965** [comment]
Windows 10 Pro 64-Bit Build 19044.1348
For me, installed and working Waterfox 2021.10 64-Bit Browser.
After manual upgrade using Waterfox.G4.0.2.1.Setup or Waterfox.G4.0.3.1.Setup Waterfox is not opening up.

I have used Revo Uninstaller Free to remove all Waterfox files and folders and installed Waterfox G4.0.2.1 by itself with no Extensions, Waterfox does not open up or launch when clicking on Waterfox to open up.
