### ISSUE TITLE
First install and cannot launch

### ISSUE THREAD

**Issue by sSiDs** [MrAlex94/Waterfox#2449]
### What happened?

A bug happened!
https://ibb.co/NTMjtmz
Win 10 1607 ENT

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
What processor? I assume it's one that doesn't support SSE4.2.
