### ISSUE TITLE
Tabs are in one window at the bottom, second window above address bar

### ISSUE THREAD

**Issue by WDenda** [MrAlex94/Waterfox#2452]
### What happened?

A bug happened?
Tabs are in one window at the bottom below content (setting: Bottom below status bar), while in the second window the tabs are above the address bar at the same time. (see picture)

![Waterfox_Tabfehler](https://user-images.githubusercontent.com/8401627/143491401-6d6caa05-6854-4839-857c-1074838e177f.JPG)

Safe mode does not change this. I've never seen this on *any* Firefox up to 94.0.2 (64-Bit) on MS Windows 10. This happens only with Waterfox, up to G4.0.3.1 (64-Bit).

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Objectivite** [comment]
The only way you'll be able to cure it is to create a new profile with  ABOUT:PROFILES  then restore your Bookmarks from your old profile.

Everything else, themes, extensions, cookies, passwords, you will have to recreate.  Search for upgrading from 3.2.6 to any of the G4 versions, including 4.0.3.1 and you'll get the picture - it's broken and unlikely to be fixed (I am not one of the developers - just telling you as coldly as possible).  Save yourself time and aggravation and go through the ABOUT:PROFILES process.

O.

**Comment by WDenda** [comment]
@Objectivite "Search for upgrading from 3.2.6 to any of the G4 versions"

I've started with V4, never had V3 Classic installed. So, will the new profile further work without this issue, or do I have to expect this to happen again?

Thank you!

**Comment by Objectivite** [comment]
Ouch - new install !

Well the ABOUT:PROFILES solution will still work.

As to whether you can expect this again, have a look at the list of problems and the replies and make up your own mind - if listening to users, not treating them like idiots, believing that they do have problems and  **are following**  suggestions, improves, then the situation will improve.

O.

**Comment by WDenda** [comment]
Creating a new profile did not help.
Same issue after closing the browser with two windows, and reopening with 'restore last session'. One window Tabs on top, other with tabs at the bottom.

So far, I'll stop using this browser until this is fixed. HAND!

**Comment by dochego** [comment]
This appears to be the same issue as #2376 (which is present in a new profile). A fix seemed to be imminent but hasn't landed yet.

**Comment by adamp01** [comment]
@WDenda @Objectivite @dochego 
This one has been a bit of a pain to resolve for various reasons. I've done a bit of a chunky rewrite to attempt to resolve it, https://github.com/WaterfoxCo/Waterfox/pull/2475. This will be included in G4.0.4. If it still isn't fixed after this PR please comment again on this issue and I'll try another avenue.

**Comment by Objectivite** [comment]
**Thank You Very Much** Adamp01 for taking it seriously, addressing it, and letting us know.

Much much appreciated.

O.

**Comment by WDenda** [comment]
@adamp01 
Thank you very much for caring about this, you made Waterfox usable for us, again.

I checked this issue just now with G4.0.5.1 and two windows open with five different tabs each on W11Pro 64bit, it seems to be fixed. I'm happy again.
