### ISSUE TITLE
About:Config setting reset with 4.0.3.1

### ISSUE THREAD

**Issue by SpinningQuarks** [MrAlex94/Waterfox#2453]
### What happened?

Just updated my browser and I noticed one of my custom about:config settings was reset. The setting is browser.search.openintab and I had it set to True. Not sure if this indicates that other user-set about:config options have been reset on this update or not, and it's obviously a pretty minor thing, but I figured I'd report it anyways.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@SpinningQuarks - thanks for raising this, it's certainly a weird one and nothing that was adjusted for G4.0.3.1 would indicate the potential for resetting this preference. I'm going to close the issue for now but if you notice repeated occurrences feel free to re-open and I can try to delve further into it.
