### ISSUE TITLE
Built for GLIBC 2.30 -- won't run on Debian Buster

### ISSUE THREAD

**Issue by romanrm** [MrAlex94/Waterfox#2456]
Buster is the development codename for Debian 10. It was released on 2019-07-06, and got the latest updated version (10.11) on 2021-10-09. According to https://wiki.debian.org/DebianReleases, end of life date for Debian Buster is planned to be around 2022-08.

https://packages.debian.org/buster/libc6 Package: libc6 (2.28-10).

Clicking "Download for Linux" on the Waterfox website and trying to run Waterfox G4.0.3.1: 

XPCOMGlueLoad error for file /opt/waterfox/libnspr4.so:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /opt/waterfox/libnspr4.so)
Couldn't load XPCOM.

Is there any must-have reason to require GLIBC 2.30 and exclude such a relatively new distro? In that case would be nice to detail your system requirements a bit more, rather than implying there's just one "Download for Linux" which should work everywhere. And if you only care about the latest possible release of each distro, then that would be really disappointing.

**Comment by hawkeye116477** [comment]
> must-have reason to require GLIBC 2.30

Rather no, probably simple modification on https://github.com/WaterfoxCo/Waterfox/blob/current/.github/workflows/push.yml#L276 to use Docker image for CentOS 7 or some other distro for compiling would suffice. 
The only problematic looks like that 7-zip Alpha version, which can't run on some older distros, but it doesn't seem needed for Linux.

As a evidence I still can build it for Debian 10 => https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-g4-kpe :smile:.

**Comment by JiaOkay** [comment]
Firefox supports
But WaterFox not supports
Why must be GLIBC 2.30

![图片](https://user-images.githubusercontent.com/38833358/156690134-8578ee02-14ba-47d4-ac68-c00df35f5b9f.png)

**Comment by csonuryilmaz** [comment]
@hawkeye116477 thanks for the link. From there, I've downloaded v4.1.0 (latest by now) for Debian 9 and it seems working. :tada:

**Comment by JiaOkay** [comment]
@csonuryilmaz  I am so sorry,it's still not work on my computer
This is my systeminfo
![image](https://user-images.githubusercontent.com/38833358/162856273-5ed30339-138d-4471-b05d-a2c6ea12715e.png)

lost some dependencies
![image](https://user-images.githubusercontent.com/38833358/162857089-ebf90eb9-22dc-4cfe-b7f5-2a76feaba2f6.png)

**Comment by hawkeye116477** [comment]
But be aware @JiashunLi that he/she talked about my own build of Waterfox, not that official one.

Anyway, if we are talking about official one, that depends which you highlighted, are already included in Waterfox package. The only missing is glibc/libc6 2.29+.

Based on your screenshot I guess that for you package for Debian 10 or AppImage would work fine.
