### ISSUE TITLE
Tab Bar Position

### ISSUE THREAD

**Issue by Deki2000** [MrAlex94/Waterfox#2458]
### What happened?

A bug happened!

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
General Settings: Tab Bar Position -> Top below address bar.
On Waterfox start Tab Bar Position is first above address bar and then switch to below address bar.
```

**Comment by adamp01** [comment]
@Deki2000 - Thanks for raising this, https://github.com/WaterfoxCo/Waterfox/pull/2475 should make sure that the tab bar is moved before chrome is painted (amongst other things).

Let me know if you still have an issue with G4.0.4 and I can re-open this.

**Comment by Marekx89** [comment]
its not work, top below address bar is hiding, see attachment
![obrazek](https://user-images.githubusercontent.com/66966848/146583551-2c66a34b-4618-4132-806f-9f1816f41660.png)
