### ISSUE TITLE
Chrome extension "Typio Form Recovery" doesn't work

### ISSUE THREAD

**Issue by antoniomonteirojr** [MrAlex94/Waterfox#2459]
### What happened?

I installed Waterfox G4.0.3.1 and installed the Typio Form Recovery extension from the Chrome Web Store.
https://chrome.google.com/webstore/detail/typio-form-recovery/djkbihbnjhkjahbhjaadbepppbpoedaa

However the extension does not work in Waterfox, it does not retain data placed in forms, nor does it display the extension icon on the forms.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by DavideCannonito** [comment]
how did you even get it to install :( I have same problem as this guy here #2602
