### ISSUE TITLE
App window with twice buttons

### ISSUE THREAD

**Issue by Jogrefer** [MrAlex94/Waterfox#2461]
### What happened?

I activated fullscreen (F11), then while hovering the tab bar the icons of the window have been twice showed

![Error](https://user-images.githubusercontent.com/73208204/143986327-598ecb72-cc70-45f5-9307-0524a06b4cbf.png)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
What specific version of G4?

**Comment by Jogrefer** [comment]
4.0.3.1 (64 bits)

![image](https://user-images.githubusercontent.com/73208204/144270184-ea672fc2-b101-433c-8126-0f2f9f97d917.png)

**Comment by adamp01** [comment]
I'll take a look at this one, hopefully for next release.
