### ISSUE TITLE
G4.0.3.1: Still necessary or advised to copy config.js ->Resources and config-prefs.js -> Resources/defaults/prefs?

### ISSUE THREAD

**Issue by LeeBinder** [MrAlex94/Waterfox#2464]
Not a feature request, not a bug report, but a question due to the release notes not providing an answer:

I see "Issues installing bootstrapped extensions have now been resolved". I also testify that my legacy bootstrapped Extensions from  [xiaoxiaoflood /firefox-scripts/Extensions](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions) now load w/o the two bootstrapper files present in the WF app.

Even though I don't see them inside the WF G4.0.3.1 app: have they been integrated in some way into WF G4 (similar to polyfill having gotten integrated in WF Classic)?

**Comment by adamp01** [comment]
@LeeBinder - We did integrate the bootstrap loader into Waterfox

**Comment by LeeBinder** [comment]
awesome - you folks **rock** 👍
