### ISSUE TITLE
Oddities with private windows/tabs

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2466]
### What happened?

I've noticed an odd thing regarding the semi-recent private tab feature. Specifically regarding the combination of those and REGULAR private windows.

Putting aside my personal feelings that _private tabs on an already-private window are a bit redundant_, I wanted to point out: the bookmark menu COMPLETELY prohibits the opening of regular tabs when right clicking them on a (non-private) window. The regular "open in new tab/window" options are grayed out, ONLY allowing the private tab which adds the second layer of private browsing on top and is somewhat annoying to have to undo every time.
Right clicking empty SPACE on the bookmark bar allows me to open all of them at once on regular tabs, it's just when clicking on an individual bookmark that it grays out every option except the private tab one.

Testing it right now, I have a regular window open with a handful of tabs, and a private window for testing, and it's the non-private window that is showing this issue, oddly enough. No matter how many more windows I open, it's only private ones that allow full use of that right click bookmark menu without graying out most options.
It doesn't seem to matter how many private windows I have open, or even if I have any at all, the options are just grayed out regardless on any windows that aren't private.

EDIT: Testing it again a couple days later the behavior seems to be inverted this time... Still not sure what caused it that first time.
Regardless, private tabs being the only option for those in already-private WINDOWS can be somewhat annoying and would be a nice adjustment to do eventually.

Side note, and this is more of a suggestion while I'm on the topic, but how feasible would it be to make private tabs a setting that can be toggled on and off, for people that aren't interested in that feature? Just an option to remove it from right click/context menus to avoid accidental use of it, essentially.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@LazierTomato 

Thanks for all the notes here.

I've actually been refactoring a lot of Waterfox specific features recently and have fixed "Private tab stuff showing in a Private window" - it was an oversight during the initial implementation, I'll be PR'ing it hopefully for the next release. 

The bookmark context menu issue has been raised a lot and has been fixed for the next release.

**Comment by adamp01** [comment]
Forgot to mention, the ability to toggle Private Tab context menu options on/off is something I have on a list of nice things to add. So is on my radar and will be implemented as and when I have the time.
