### ISSUE TITLE
Typo on Web Page - https://www.waterfox.net/

### ISSUE THREAD

**Issue by Mr-Batyote** [MrAlex94/Waterfox#2468]
### What happened?

I was unable to find any contact information on the website besides twitter or here, and I cannot comment on Twitter profiles, so here is my grammatical "bug" report.  There is a transposed letter on the home screen of your web page, nothing critical but just an immediate error that stuck out to me and really detracts from the otherwise sleek look of your site. Great work everyone.

Typo discovered is "soemtimes" instead of "sometimes," found under the "Private Tab" header of your Features layout
![Waterfox Screenshot](https://user-images.githubusercontent.com/95484896/144612665-ff015d89-0013-436c-9b7e-b98fd9a7164e.png

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Thanks! Has been fixed and will be live soon.
