### ISSUE TITLE
Searching with address bar, no suggestions from Google

### ISSUE THREAD

**Issue by Pilouface95** [MrAlex94/Waterfox#2469]
### What happened?
Not working only for Google. For Bing, Wikipedia etc. it was okay.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux

**Comment by adamp01** [comment]
@Lamb666 - Thanks for raising this, https://github.com/WaterfoxCo/Waterfox/pull/2479 should fix.
