### ISSUE TITLE
Credit card web sites---- Chase, ATT etc

### ISSUE THREAD

**Issue by bigboy65** [MrAlex94/Waterfox#2473]
### What happened?

Even though I have the latest Waterfox, most Credit card websites say your browser is not compatable then it wants you to update to the latest version, have tried agent switcher with no results, work around is to go to Microsoft Edge....

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@bigboy65 - I'm going to do some custom user agent work early next week, or the week after. Would you be able to add a list of any sites that you are having issues with as this should hopefully be a quick fix for us.

**Comment by jburf** [comment]
Using G4.0.8, Chase.com still has the same issue... would appreciate a fix.
Thanks!

**Comment by digital-pet** [comment]
Just an update, this issue persists in 4.1.4 - chase.com fails to even load the stylesheet even with all extensions disabled. The website works, however, in firefox.

**Comment by digital-pet** [comment]
This issue still exists in G5.1, this should not have been closed.
