### ISSUE TITLE
Inspect Element & Other Menus Not Opening

### ISSUE THREAD

**Issue by Petrifyingz** [MrAlex94/Waterfox#2477]
### What happened?

Inspect element not opening any menu when invoked from the right click menu or from the keyboard shortcut. Issue has only started occurring ever since my browser updated to G4. Other bugs I've been getting are things such as the settings button from the hamburger menu doing absolutely nothing, the same goes for the add-ons button.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@Petrifyingz - Would you be able to do the below to help debug this please?
1. Right after you notice one of these issues occurring open the Browser Console (Ctrl+Shift+J), should be in a pop-up window, and copy any relevant error lines on here. Best way to see what is actually relevant is by looking at what errors (if any) appear when you attempt to open settings or close a tab etc and it doesn't work.
2. Could you also provide a list of addons you are using?
