### ISSUE TITLE
Stuff like settings don't open and some tabs stay open when closed

### ISSUE THREAD

**Issue by Test-Account666** [MrAlex94/Waterfox#2478]
### What happened?

Hello!

I have a really annoying problem!
If I click on "Settings", nothing happens.
I have to manually type "about:preferences", which is annoying, but typically not a huge problem.
As long as I don't need to go on special pages I don't know the name of...

For example: I wasn't able to do anything in the addons tab, because I just didn't know the url.

Also... Sometimes when I close a tab (With pressing down the scroll wheel) the tab just stays open.
It disappears from the tab list, but I still see it and can interact with it, as long as I don't switch to another tab or open a new one.

I'm using Linux, ArcoLinux and the latest version (G4.0.3.1) (At least the updater does not find any new updates)

I switched to Waterfox, because it's a fork of Firefox and fixed a massive glitch I have with Firefox...
I really don't want to give up on Waterfox

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by adamp01** [comment]
@TheBlackEntity - thanks for raising this. I'll add these onto the list of things to look into, seems like it's Linux specific as quick tests on Windows/Mac don't appear to reproduce the behaviour you have mentioned.

**Comment by Petrifyingz** [comment]
Same happens to me on Windows.

**Comment by Test-Account666** [comment]
> @TheBlackEntity - thanks for raising this. I'll add these onto the list of things to look into, seems like it's Linux specific as quick tests on Windows/Mac don't appear to reproduce the behaviour you have mentioned.

I also should mention that this issue is not always present.

Most of the time it starts occuring after hibernation. But also when trying to change settings of addons (or at random) sometimes.

Addons like "TabSearch" seem to break while Waterfox is in "glitch state"

**Comment by adamp01** [comment]
@TheBlackEntity - Ok interesting - would you be able to do two things for me please?
1. Right after you notice one of these issues occurring open the Browser Console (Ctrl+Shift+J), should be in a pop-up window, and copy any relevant error lines on here. Best way to see what is actually relevant is by looking at what errors (if any) appear when you attempt to open settings or close a tab etc and it doesn't work.
2. Could you also provide a list of addons you are using?

**Comment by thunderstone135** [comment]
I'm also experiencing this along with big space between tabs.

![Untitled](https://user-images.githubusercontent.com/96173732/146665955-3be244c2-ee67-4e7c-8541-142faf367b5e.png)

This happens whether I'm using an addon or not because I tried it with all addons disabled.
