### ISSUE TITLE
Color Mode Not Available when printing web page.

### ISSUE THREAD

**Issue by thecreator1965** [MrAlex94/Waterfox#2481]
### What happened?

A bug happened!
Open Waterfox G4.0.3.1 64-Bit Browser
Go to Web page with Colors.
Go File then Print,
Result Print Preview page loads only in Gray Mode. Color Mode is not available.

Tested in Chrome and it prints page in Color.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Objectivite** [comment]
Update to 4.0.4 which has fixed a lot more issues than are described in the Release Notes.

I have just tried the steps you mentioned, using www.bbc.co.uk and www.cnnc.om, and I had no problems printing in colour.

O.

**Comment by thecreator1965** [comment]
Hi Objectivite,
Failed too.
