### ISSUE TITLE
Netflix error for Waterfox

### ISSUE THREAD

**Issue by R-a-v-e-n** [MrAlex94/Waterfox#2483]
### What happened?

As of early hours Tuesday December 7, 2021 (what a date!), Netflix videos no longer play on Waterfox.
They receive the Netflix Error F7121-3078, with the message “Pardon the interruption, Looks like your browser
is no longer supported. Please install the latest version or try another browser”.

Two days prior, Netflix videos (including the first half of the SAME movie now unviewable) had been possible
to watch without any problems at all. No browser or system changes had occurred in the meantime.

The browser was Waterfox Current G4.0.3.1 (64-bit), on a macOS BigSur 11.6.1 MacBook – both the most recent –
and, following instructions, the MacBook was rebooted, the browser restarted, but the same Error recurred.

The error was reported online to Netflix, and by chat to Netflix. The Netflix advisor remarked that Waterfox
is *not* one of the Netflix supported browsers (although Firefox is), and suggested that Waterfox contact
Netflix to coordinate updates to become compatible with Netflix again.
-----
*** NOTE: This error has continued, as of Thursday December 9, 2021, with Waterfox Current G4.0.4 (64-bit), after the Widevine update. ***
-----

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

macOS

**Comment by poynty** [comment]
Temp work around here:

https://github.com/WaterfoxCo/Waterfox/issues/2462#issuecomment-987491049

Work around tested and working Win 10 Waterfox Classic 2021.10, not tried G4.0.4 but presume it will work.

Adapted the filenames for Windows libraries but the theory is the same, copy from the latest version of Firefox, overwrite Widevine in the Waterfox profile.

**Comment by MrAlex94** [comment]
Hi,

Could you go to `about:plugins` and copy/paste the output for Widevine:

```
Widevine Content Decryption Module provided by Google Inc.

    File: 4.10.2391.0
    Path: /Users/akontos/Library/Application Support/Waterfox/Profiles/xxqudr3j.68-edition-default/gmp-widevinecdm/4.10.2391.0
    Version: 4.10.2391.0
    State: Enabled
    This plugin enables playback of encrypted media in compliance with the Encrypted Media Extensions specification. Encrypted media is typically used by sites to protect against copying of premium media content. Visit https://www.w3.org/TR/encrypted-media/ for more information on Encrypted Media Extensions.
```

**Comment by R-a-v-e-n** [comment]
Widevine Content Decryption Module provided by Google Inc.

    File: 4.10.2391.0
    Path: /Users/Raven/Library/Application Support/Waterfox/Profiles/k72xu250.68-edition-default/gmp-widevinecdm/4.10.2391.0
    Version: 4.10.2391.0
    State: Enabled
    This plugin enables playback of encrypted media in compliance with the Encrypted Media Extensions specification. Encrypted media is typically used by sites to protect against copying of premium media content. Visit https://www.w3.org/TR/encrypted-media/ for more information on Encrypted Media Extensions.

**Comment by R-a-v-e-n** [comment]
I am now able to view Netflix videos again. No system updates at *this* end.

**Comment by mikeloeven** [comment]
Looks like immediately after the update water fox is just slow getting the wide vine plugin update for me going into plugins menu and manually clicking check for updates resolved this

**Comment by adamp01** [comment]
Thanks for that @mikeloeven - hopefully your comment alongside the update will help any other users facing this issue.
