### ISSUE TITLE
[Website] Peek not Peak

### ISSUE THREAD

**Issue by kibibites** [MrAlex94/Waterfox#2485]
### What happened?

Sorry if here is the place for the wrong issue, but I cannot find a place to submit issues about the website.

Typo seen here:
<img width="415" alt="Screen Shot 2021-12-09 at 11 39 41 AM" src="https://user-images.githubusercontent.com/47074495/145464564-97c61e09-244e-4a30-8e65-162af06aae6c.png">

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

macOS

**Comment by adamp01** [comment]
@sourTaste000 - This is a good place to report, thanks for raising. I've amended this and it's getting pushed out now.
