### ISSUE TITLE
High title bar in full screen mode on Mac OS Catalina

### ISSUE THREAD

**Issue by freebian666** [MrAlex94/Waterfox#2486]
### What happened?

Hello!
I have high title bar in full screen mode:
<img width="1256" alt="Screen Shot 2021-12-10 at 2 32 47 PM" src="https://user-images.githubusercontent.com/70696173/145551741-3962543a-cca5-4364-ad7c-dfa2ea6dc08c.png">

Waterfox G4.0.4 (64-bit)
macOS Catalina 10.15.7 (19H1519)
Macbook Pro 16" core i9

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

macOS

**Comment by adamp01** [comment]
@freebian666 - Thanks for reporting this - that certainly isn't right. I suspect I know what is causing it so early next week I'll ask you to test some things out in the browser console. Unfortunately I'm unable to replicate this on the Mac machines I have available so this will be the only way we can get this fixed for you.

**Comment by freebian666** [comment]
Ok, thank you
I'll be glad to help

**Comment by adamp01** [comment]
@freebian666 - Unfortunately a fix for this is going to be quite a bit more complicated than I initially suspected, so it's going to be a while before we can get to this. We are aware of it and are tracking it internally.

**Comment by freebian666** [comment]
@adamp01 - Okay, thanks for the info and your work!
