### ISSUE TITLE
I got my Waterfox banned by Widevine, apparently.

### ISSUE THREAD

**Issue by CaptainFrosty** [MrAlex94/Waterfox#2487]
### What happened?

My cable company uses Widevine to stream TV on the browser. It always worked on Waterfox before, with DRM enabled, but I messed around with a few about:config settings and apparently Widevine didn't like it. Now it doesn't work even with a fresh profile with normal settings. The response header says the license for my device was revoked. It works fine on Edge, but I don't really want to use Edge for anything. I would purge Edge from my system if I were brave enough to believe I wouldn't break the OS. I'd rather not keep a copy of Firefox around just for that either. How are they tracking that I'm still using this browser? Fingerprinting resist is on, I'm not giving them my canvas, and I've changed user agent and headers. Maybe something is still residing in local storage, I'll try wiping all that again. Any insight would be appreciated.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Hi,

Could you try running Waterfox in [Troubleshooting Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode?redirectslug=troubleshoot-firefox-issues-using-safe-mode&redirectlocale=en-US#w_how-to-start-firefox-in-4troubleshoot-modesf5safe-modesf) and then navigating to the website to test if it works?

If not and you feel comfortable doing so - maybe try a [fresh profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)?

If it doesn't work - you can always switch back to your old profile.

**Comment by CaptainFrosty** [comment]
@MrAlex94  Thanks for the suggestions. It started working again one day after I updated Waterfox. Must have been a temporary ban of my device. Clearly I had some issue with my widevine plugin or maybe a security setting they didn't like.
