### ISSUE TITLE
Certificate Authentication Failure after updating to G4.0.4

### ISSUE THREAD

**Issue by PatG1958** [MrAlex94/Waterfox#2492]
### What happened?

The following happens when trying to connect to a Microsoft address but other non-microsoft addresses seem to work. Only started after I upgraded to G4.0.4 this morning. Any pointers would be appreciated. My IT says all my certificates are up to date and good... The URL works in Chrome no problem.....
================================
Secure Connection Failed

An error occurred during a connection to support.microsoft.com. The OCSP response does not include a status for the certificate being verified.

Error code: MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by suamor** [comment]
This is a missing feature on mozilla side:
https://bugzilla.mozilla.org/show_bug.cgi?id=966856

It would be good to coordinate any implementation on this occasion with mozilla.

**Comment by valinet** [comment]
It goes to show how much Microsoft cares about open source. Like, they could have pinged Mozilla and let them know they are about to do this and give them a few days, or God forbid, even make a contribution themselves. But like, why do that, when you can silently and as fast as possible do this, and hopefully a few unknowing people also switch to Microsoft Edge in the meantime? I mean, for corporate Microsoft, it can't get any better than that. Typical Microsoft, as if continuously bloating Windows with Microsoft Edge advertisements wasn't enough. I can't believe no one there noticed almost none of their sites work in Firefox when they push this change.

**Comment by adamp01** [comment]
We'll monitor the Mozilla bug and pull in the patch as soon as it is ready.
As mentioned in the bug, you can set `security.ssl.enable_ocsp_stapling` preference to false in about:config to access the sites that are currently erroring. I'm not recommending this is something you should do, just making you aware of what you can do.

**Comment by adamp01** [comment]
We are going to pull the fix in for the next release (should be tomorrow).

**Comment by adamp01** [comment]
Should be fixed with G4.0.5.1
