### ISSUE TITLE
Unable to play embedded webm 

### ISSUE THREAD

**Issue by molitar** [MrAlex94/Waterfox#2500]
### What happened?

I have tried a new install of Waterfox Classic and a safe mode start of Waterfox G3 as well as new profile. Neither is able to play this webm video. Firefox and Chrome plays the video just fine. Waterfox will not at all.

SFW video:
https://www.webmfiles.org/demo-files/

NSFW:
https://chan.sankakucomplex.com/post/show/29651114

Both file types report 'Video can not be played because the file is corrupt'  but totally wrong as it plays fine in all other browsers.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by Yay295** [comment]
Both videos play in G4.0.5.1 for me.
