### ISSUE TITLE
Dark themes incompatible with bottom Tab Bar position option - Tab bar looks white and blends letters and backround color together making tabs invisible

### ISSUE THREAD

**Issue by skooter7** [MrAlex94/Waterfox#2501]
### What happened?

![Clipboard Image (1)](https://user-images.githubusercontent.com/96396657/146694603-95036fe0-ef94-4712-9e4a-881752e6ff26.jpg)

As you can see other than the highlighted tab all other tabs seem invisible and the tab bar has that white color. When the tab bar is at the top it looks perfectly normal

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Thanks for raising this. I'll push a fix ASAP.

**Comment by adamp01** [comment]
https://github.com/WaterfoxCo/Waterfox/pull/2503
