### ISSUE TITLE
Change Lepton Theme Status Bar Text Color

### ISSUE THREAD

**Issue by thunderstone135** [MrAlex94/Waterfox#2506]
**Is your feature request related to a problem? Please describe.**
Hi, is it possible to change the Lepton Theme status bar color from grey to white?

From this:
![Untitled1](https://user-images.githubusercontent.com/96173732/146937459-07a17876-6444-4841-a9d2-e66531153c70.png)

To this:
![Untitled2](https://user-images.githubusercontent.com/96173732/146937487-dea37e24-89d8-41f4-883a-97944a458afb.png)

**Describe the solution you'd like**
I was able to change the color on userChrome.css by using this:
```
#status-text > #statuspanel-label
{ color: rgb(255, 255, 255) !important; }
```
I was thinking that it would benefit everyone if the text color is changed internally.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by adamp01** [comment]
Status text will default to be more visible, option in about:preferences to maintain existing behaviour.
https://github.com/WaterfoxCo/Waterfox/pull/2527
