### ISSUE TITLE
Add-ons evaporated

### ISSUE THREAD

**Issue by dcexpat** [MrAlex94/Waterfox#2509]
### What happened?

A bug happened! Upgraded to G4.0.5.1 today and none of the 4 add-ons I use load or function. Forget Me Not says it needs containers even though containers are enabled. Last Pass, Duckduckgo Privacy Essentials, and Copy Me That, along with Forget Me not only do not function, the icons fail to appear in their usual location next to the search bar. As to your question regarding Firefox, I also use Firefox and the current version 95.0.2 does not have this problem. If push comes to shove, I can live without the others but not forever, but Last Pass is critically important more than once daily. Please, what to do? Thanks very much.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@dcexpat - Would you be able to open the browser console (Ctrl + Alt + J) and copy the logs here please? If you scan through you should be able to see some relevant output when you attempt to install one of the addons you mentioned.

**Comment by dcexpat** [comment]
Screenshot attached. I guess I wasn't clear. The add-ons are not newly installed. They were installed many, many versions ago. I know you hear this all the time. This time it's true. I didn't change anything except perform the update to Waterfox. 
![image](https://user-images.githubusercontent.com/96524673/147247985-eb10edf4-de20-4ed3-a936-b56c7ac5828c.png)

**Comment by dcexpat** [comment]
Subsequent to the previous message, I disabled LastPass and restarted Waterfox. That generated a firestorm of activity in the log, more than will fit in a screencap. Then I re-enabled LastPass and and a half dozen new entries appeared in the log. Would be happy to send the log file if I knew the name and location. Thanks. (I'm willing to accept that I'm an idiot for not knowing more than I do)

**Comment by adamp01** [comment]
@dcexpat - That is exactly what I need to be able to debug this for you. You should be able to just select it and copy paste it either here, or in a [gist](https://gist.github.com/). If you could do that for me I can start investigating, as I have tried to replicate the issue by migrating from G4.0.4 to G4.0.5.1 with no luck. Unfortunately a fix for this isn't going to come until next week in a best case scenario due to the time of year.

**Comment by dcexpat** [comment]
@adamp01 Thank you for your help. I am grateful May your holidays are everything you hope for and more.

[waterfoxlog.txt](https://github.com/WaterfoxCo/Waterfox/files/7775730/waterfoxlog.txt)

**Comment by adamp01** [comment]
@dcexpat - Do you know which version of Waterfox you were on prior to the update here?

Happy holidays to you too!

**Comment by dcexpat** [comment]
@adamp01 Honestly, I can't say for sure. I presume it was the immediately prior version. With browsers, for security as well as feature reasons, I tend to respond immediately (well, within minutes of first seeing it) to the update notices that pop up. It's possible I skipped one but the odds of that are about equal to those of winning the powerball.

**Comment by dcexpat** [comment]
Hello @adamp01. I get it. I'm only one person and this seems not to be affecting scads of Waterfox users which means I am, appropriately, not high on the priority list. No harm, no foul. Unfortunately, It also means that without these few add-ons functioning, I will have to stop using Waterfox, much to my regret. I wish you and the team well and look forward to rejoining your user base.

**Comment by MrAlex94** [comment]
Hopefully G5.1 is of some help with these issues, but unfortunately they are almost always impossible to debug.
