### ISSUE TITLE
Notification about DRM copy protection between address bar and tab bar

### ISSUE THREAD

**Issue by ckroenicke** [MrAlex94/Waterfox#2510]
### What happened?

A bug happened!
I am using my Waterfox with the tab bar below the address bar (both on the top).
Since updating to Waterfox 4 the message to active the DRM copy protection is displayed between adress bar and tab bar.
![grafik](https://user-images.githubusercontent.com/24443540/147082305-1e348bcf-90e5-4fcd-983b-ea1c1aa06409.png)

I expected that message to be displayed below the tab bar (like in Waterfox 3).

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Due to the way the tabs are "moved", not really possible to fix.
