### ISSUE TITLE
Can't open weblinks in Thunderbird 91.3.2 in Waterfox G4.0.5.1

### ISSUE THREAD

**Issue by amerigena** [MrAlex94/Waterfox#2511]
### What happened?

Internal email links in Thunderbird will not open w Waterfox (this has affected all versions; updates do not affect the issue) when it's set as default browser. Links open w any other (Chrome, Firefox, Vivaldi) set as default.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Odd, do you have this issue in G5?
