### ISSUE TITLE
Help > About Waterfox links to Mozilla and not Waterfox Websites

### ISSUE THREAD

**Issue by elaine-jackson** [MrAlex94/Waterfox#2512]
### What happened?

If you click Help > About Waterfox, you'll see a popup. The line "Want to help, Make a Donation or Get Involved" links to Mozilla's donation website and to Mozilla's contributing website. I don't know if Waterfox accepts community funding, but I think those links should go to Waterfox specific resources. (E.g. The GitHub repo and if applicable your donations page). Thoughts?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Fixed in G5.
