### ISSUE TITLE
Cannot add certain search engines to waterfox

### ISSUE THREAD

**Issue by Lewistheshrk** [MrAlex94/Waterfox#2513]
### What happened?

on version G4.0.5.1

For some reason I cannot add some search engines. 
When on some websites like github or youtube the magnifying glass shows the little plus to add the pages search bar as an option.
websites like bing, google and wikipedia don't show the icon to add the search engine.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
That's likely due to them already being in Waterfox and causing conflicts.
