### ISSUE TITLE
Remove emoji from restart button in menu

### ISSUE THREAD

**Issue by nevinpuri** [MrAlex94/Waterfox#2514]
![image](https://user-images.githubusercontent.com/39220032/147257493-600a6593-d029-4f3f-9990-c93441b47300.png)
Looking at this menu, the restart button looks really out of place. I'd suggest removing the emoji to make it more uniform with the rest of the items.

I'm curious as to what you guys think, as I could be wrong as well.

**Comment by Objectivite** [comment]
I disagree - it matches the **Windows 10**  Start Menu - it is a small visual reminder that you are about to do something drastic (aka - restarting means you might lose all your open tabls depending on how you restart), etc...

Well done on the developers for me.

O.

**Comment by thunderstone135** [comment]
That's odd. I'm using the latest version (4.0.5.1) and I have this:

![Untitled](https://user-images.githubusercontent.com/96173732/147376840-eca199ec-aeab-4ee1-9296-5a305bcbe053.png)

Are you using a different version? Or a custom userChrome.css?

**Comment by Objectivite** [comment]
Thanks Thunderstone135.

This Feature Request Thread is now becoming a Bug post.

I am on 4.0.5.1 and I do not have a  userChrome.css and mine is like Nevin1901's :+1: 

![image](https://user-images.githubusercontent.com/89191739/147382957-ed9252ad-fe86-44c5-a4dd-6659e660e4ef.png)

O.

**Comment by thunderstone135** [comment]
And the plot thickens. LOL. Anyway, I tried playing with the themes and I'm still getting the same one I posted above (only with different color). There's most likely a problem with the update process. The omni.ja (inside the browser folder) file is probably not getting updated properly.

**Comment by adamp01** [comment]
Hi guys - Lepton should give an appMenu like @thunderstone135, Firefox Proton and Waterfox Australis themes will give like @Nevin1901 and @Objectivite. See examples here (from Mac - the "Restart" item isn't added to the appMenu on Mac btw):
Lepton:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/47503375/147389289-456511ff-4d43-47d2-b0ef-4f453e9f1365.png">
Proton and Australis:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/47503375/147389296-b04f3425-531a-4ffe-adb9-dd2f73fc4f21.png">

**Comment by Objectivite** [comment]
Thanks for the answer Adam.

All makes sense now.

I'll close the Bug I opened for this.

O.
