### ISSUE TITLE
Better animations for moving tabs from/to windows on Ubuntu

### ISSUE THREAD

**Issue by EmmanuelMess** [MrAlex94/Waterfox#2516]
### What happened?

Moving tabs from and to windows can be very clunky, especially when the new tab is in a window in front of the windows you want to put it in. I would be nice if there were a redesign of the UX in that aspect oriented around speed and ease of use.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Thanks for the suggestion, but unlikely to happen with Waterfox in its current form.
