### ISSUE TITLE
Waterfox 4.0.5.1  --  about:cache incorrectly reports Disk Cache figures when disk caching is disabled and all caching put to RAM

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2520]
### What happened?

Hello,

I set this setting to **TRUE**  
**browser.cache.memory.enable**

and this setting to **FALSE** 
**browser.cache.disk.enable**

With that configuration  about:cache  incorrectly reports the Disk Cache (it gives it the same figures as the Memory Cache).

![image](https://user-images.githubusercontent.com/89191739/147484356-9c214389-510c-4ab7-ab5d-1894975c4289.png)

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Sounds like a platform bug, rather than a Waterfox specific one.
