### ISSUE TITLE
How do I dissable Waterfox Update Notification 

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#2524]
### What happened?

After Having a disastrous time with latest G4 update still not working and then messing up everything, 
I went back to G3.2.6 and had to quickly disable the auto update settings.  
Now every time I open up waterfox it still gives me alerts there is an update I dont want to see them how 
do I disable that. 

I do not even want it to check for updates till I am ready so how do we stop this because 
its only Always Check and update or Check and let me choose no just do not check options.... 

Till G4 can install on Windows 7 Corporate 64 Bit and install and work without Drm and Media issues, 
I will stick to what works. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by Objectivite** [comment]
Create a folder called  "distribution"  in your Waterfox G3 install folder, unzip the attached Zip file into it and that will do it.

From then on you will not be prompted for updates and it will not update - if you go to  **"Help \ About Waterfox"**  you will see this (except that yours will say  "Version 3.2.6").

You can check the file @ www.virustotal.com.

![image](https://user-images.githubusercontent.com/89191739/147658873-5ccb4c11-f827-4e27-a476-f01aa5b437c0.png)
[Mozilla_Firefox_65+_Disable_Auto_Updates_Policy.zip](https://github.com/WaterfoxCo/Waterfox/files/7788668/Mozilla_Firefox_65%2B_Disable_Auto_Updates_Policy.zip)

O.
