### ISSUE TITLE
Certain Videos Do Not Play

### ISSUE THREAD

**Issue by Radiowhiz** [MrAlex94/Waterfox#2525]
### What happened?

In G4.0.5.1 and in earlier versions (Windows 10) certain videos display with a > button and when pressed a Pause bar is displayed, along with the 10 second back and forward arrows, but there is no progress bar and nothing is played.  A thumbnail of the videos (this one from CNN) shows a "Now Playing" banner.  I have disabled all of the extensions/add-ons and tried it in Developer Mode too.  Is this the "Safe" mode?  If not how do you reboot without add-ons?  Another one from the same CNN site works but plays a commercial before the video.  I do not have this problem in Chrome but it fails in Firefox as well.  If I successfully play another one of the videos from the scroll-bar below and return to this one, it no longer fails.  Using https://www.cnn.com/2021/12/29/middleeast/seafood-fraud-sfs-trace-dubai-spc-intl/index.html?utm_term=16408647745960b12c3f88a21&utm_source=cnn_Five+Things+for+Thursday%2C+December+30%2C+2021&utm_medium=email&bt_ee=8TuZKsJhpt0hOFZ%2F58Nj7MlHe9nUQr4%2B2CokLyQ%2FQKc9Fhj9gQqf4cAibM306SRD&bt_ts=1640864774598

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Sounded like a potential webcompat issue that should be resolved in G5. Please re-open if that's not the case!
