### ISSUE TITLE
Waterfox G4.0.5.1/G4.0.6 AVIF Image Loading Issue

### ISSUE THREAD

**Issue by phyco1991** [MrAlex94/Waterfox#2529]
### What happened?

Image embeds containing arguments in the URL from imgix.net do not load in Waterfox G4.0.5.1

Error message is "The image "URL" cannot be displayed because it contains errors."

Not reproducible in Firefox or Chrome.

**Working example -** 
https://plecom.imgix.net/bo-669168-1329.jpg

**Non-working example -** 
https://plecom.imgix.net/bo-669168-1329.jpg?auto=format

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Transparent image with source https://plecom.imgix.net/iit-255729-646349.png?auto=format&w=350&h=350 unable to load. Trying light background image chiefWebScript-main.030c9ffe852bddaaea34.js:2:42614
Transparent image with source https://plecom.imgix.net/iit-255736-646349.png?auto=format&w=350&h=350 unable to load. Trying light background image chiefWebScript-main.030c9ffe852bddaaea34.js:2:42614
Transparent image with source https://plecom.imgix.net/iit-286450-648826.png?auto=format&w=350&h=350 unable to load. Trying light background image chiefWebScript-main.030c9ffe852bddaaea34.js:2:42614
Transparent image with source https://plecom.imgix.net/iit-286452-648826.png?auto=format&w=350&h=350 unable to load. Trying light background image chiefWebScript-main.030c9ffe852bddaaea34.js:2:42614
Transparent image with source https://plecom.imgix.net/iit-261735-647161.png?auto=format&w=350&h=350 unable to load. Trying light background image chiefWebScript-main.030c9ffe852bddaaea34.js:2:42614
Transparent image with source https://plecom.imgix.net/iit-261734-647161.png?auto=format&w=350&h=350 unable to load. Trying light background image chiefWebScript-main.030c9ffe852bddaaea34.js:2:42614
Image with source https://plecom.imgix.net/iil-255729-646349.jpg?auto=format&w=350&h=350 unable to load. Failing over to blank image. chiefWebScript-main.030c9ffe852bddaaea34.js:2:42865
Image with source data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7 unable to load. Failing over to blank image. chiefWebScript-main.030c9ffe852bddaaea34.js:2:42865
Image with source https://plecom.imgix.net/iil-286450-648826.jpg?auto=format&w=350&h=350 unable to load. Failing over to blank image. chiefWebScript-main.030c9ffe852bddaaea34.js:2:42865
Image with source data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7 unable to load. Failing over to blank image. chiefWebScript-main.030c9ffe852bddaaea34.js:2:42865
Image with source https://plecom.imgix.net/iil-261734-647161.jpg?auto=format&w=350&h=350 unable to load. Failing over to blank image.
```

**Comment by Yay295** [comment]
The first URL fetches a JPG image, while the second fetches an AVIF image. Waterfox seems to be having problems with AVIF images.

**Comment by herod2k** [comment]
Same problem here, drop.com suddenly stopped to show all the images (E.g. https://massdrop-s3.imgix.net/product-images/poseidon-linear-custom-mechanical-switch/FP/9pysndAkTWOQF1h4RCnX_0798_copy.jpg?auto=format&fm=jpg&fit=fill&w=120&h=80&bg=f0f0f0&dpr=2&q=35). I was going to open a bug report but I saw this and I've realized that is related to imgix and the parameters on the url.

**Comment by falzm** [comment]
Also experiencing this issue with PNG images and Waterfox G4.0.6 (macOS Intel), e.g.:

* https://www.datocms-assets.com/50397/1641216276-personnalmanagement.png?auto=format&dpr=1&w=112
* https://axeptio.imgix.net/2019/01/Cookie-jetpack-vide.png?auto=format&fit=crop&w=170&h=auto&dpr=1

**Comment by anonvoy** [comment]
I have the same problem with images from berliner-zeitung.de (Waterfox G4.0.6, Linux):

From https://www.berliner-zeitung.de/news/cdu-politiker-vaatz-fordert-ruecktritt-der-gesamten-zdf-fuehrung-li.207700:

* https://berliner-zeitung.imgix.net/2022/01/23/bfe0a01c-307c-40ef-891b-c1a2e8de8130.jpeg?rect=1%2C0%2C4760%2C3173&w=1024&auto=format is the image used in the article - AVIF format, it's not shown, instead an error message is displayed (image cannot be displayed because it contains errors)
* https://berliner-zeitung.imgix.net/2022/01/23/bfe0a01c-307c-40ef-891b-c1a2e8de8130.jpeg is the image without the extra parameters - JPG file, which is displayed without problems

**Comment by bamzero** [comment]
I was using [Don't "Accept" image/webp](https://addons.mozilla.org/en-US/firefox/addon/dont-accept-webp/) add-on to strip webp but realised it also has the option for AVIF which is doing the job as a workaround if you don't want to stay on 4.0.4

**Comment by anonvoy** [comment]
Kickstarter also seems to be affected, see https://www.reddit.com/r/waterfox/comments/sjzzh2/kickstarter_images_missing/

**Comment by anonvoy** [comment]
> I was using [Don't "Accept" image/webp](https://addons.mozilla.org/en-US/firefox/addon/dont-accept-webp/) add-on to strip webp but realised it also has the option for AVIF which is doing the job as a workaround if you don't want to stay on 4.0.4

That works, thank you.

**Comment by phyco1991** [comment]
Kind of disappointing that this still hasn't been fixed, a month after being reported. It clearly impacts a variety of different sites and given it wasn't present in G4.0.4 it should not be that difficult to determine what has caused it and either regress the change or patch it.

**Comment by ksy36** [comment]
This issue with avif has been addressed in Gecko, but looks like it hasn't made it to Waterfox yet. 

Temporarily changing `image.avif.enabled` to `false` in `about:config` will fix the issue in Waterfox (this will need to be reverted back once this issue is resolved).

**Comment by taciturnaxolotl** [comment]
I also have this issue on [https://Unsplash.com](https://Unsplash.com) was referred from my issue #2561. @ksy3g your `about:config` trick worked for me. I'll be happy when this is resolved as its a annoying error.

**Comment by adamp01** [comment]
This will be fixed with the next release of Waterfox.

**Comment by taciturnaxolotl** [comment]
Awesome! I am glad that this will be resolved!

**Comment by phyco1991** [comment]
Confirmed fixed in G4.0.7! Thanks
