### ISSUE TITLE
Improved Downloading

### ISSUE THREAD

**Issue by afzl-wtu** [MrAlex94/Waterfox#2530]
No other browser support download videos and mp3 from youtube and other streaming website, except third-party paid  softwares and extra extensions. Everyone want such a browser which has built in features. You can check people asking on different websites.
Specially on Linux there is no good downloader except XDM. It is also outdated now.
So please add feature to download videos from stream websites as well as download a video from cache that is recently watched.
Also add resume download by refreshing link if it expires...
These enhancements give a boost to WaterFox over other browsers in market.
Thanks in advance.

**Comment by adamp01** [comment]
Unfortunately that is against the terms of service for YouTube (and other streaming services), so that will not be implemented in Waterfox or any other legitimate service.
