### ISSUE TITLE
How to update on Linux to the latest version <SOLVED>

### ISSUE THREAD

**Issue by RektalTk** [MrAlex94/Waterfox#2537]
### What happened?

I have got G4.0.5.1 on Linux. About Waterfox shows info that  is up to date.
I am currently on the default update channel.
But the latest version is Waterfox-G4.0.6.en-US.linux-x86_64.tar.bz2.
How to update to the latest version on Linux? 

I am using Firefox too but browser is updating from repositories.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by adamp01** [comment]
@RektalTk - I'll take a look and see if I can reproduce.

**Comment by RektalTk** [comment]
I see that there is a G4.0.7 version but browser can't update by itself.
Update is not working on Linux.

**Comment by RektalTk** [comment]
I need to merge the G4.0.7 Waterfox folder with G4.0.6 folder to update my browser and keep my bookmarks and settings

**Comment by adamp01** [comment]
@RektalTk - What distro are you on? And are you using the tarball from the Waterfox website/CDN/github or a package from another source?

Would you be able to provide some logs by doing the following: 
1. Go to `about:config` search for `app.update.log` and make sure it is set to `true`.
2. Open the browser console, Ctrl + Shift + J and filter output (bar at top) to `AUS`.
3. Open the AppMenu -> Help -> About Waterfox
4. Copy and paste the AUS logs here.

On my Ubuntu VM everything is working as expected.

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/47503375/155517437-c32a107f-24a3-420e-a5a5-70f98c6e1fd8.png">

**Comment by RektalTk** [comment]
I am using [Sparky Linux](https://sparkylinux.org/) Debian based distro.
1. App.update.log was set to false. I have changed it.
2. AUS logs:
`AUS:SVC Creating UpdateService
AUS:SVC Logging current UpdateService status:
AUS:SVC UpdateService.canUsuallyCheckForUpdates - able to check for updates
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC getCanApplyUpdates - testing write access /home/rektal/waterfox/update.test
AUS:SVC shouldUseService - returning false
AUS:SVC getCanApplyUpdates - able to apply updates
AUS:SVC gCanStageUpdatesSession - testing write access /home/rektal/waterfox/update.test
AUS:SVC gCanStageUpdatesSession - testing write access /home/rektal/update.test
AUS:SVC gCanStageUpdatesSession - able to stage updates
AUS:SVC Elevation required: false
AUS:SVC Other instance of the application currently running: false
AUS:SVC Downloading: false
AUS:SVC End of UpdateService status
AUS:SVC UpdateManager:_loadXMLFileIntoArray - XML file does not exist. path: /home/rektal/waterfox/active-update.xml
AUS:SVC Checker: checkForUpdates, force: true
AUS:SVC Creating UpdateService
AUS:SVC Logging current UpdateService status:
AUS:SVC UpdateService.canUsuallyCheckForUpdates - able to check for updates
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC getCanApplyUpdates - testing write access /home/rektal/waterfox/update.test
AUS:SVC shouldUseService - returning false
AUS:SVC getCanApplyUpdates - able to apply updates
AUS:SVC Elevation required: false
AUS:SVC Other instance of the application currently running: false
AUS:SVC Downloading: false
AUS:SVC End of UpdateService status
AUS:SVC UpdateService.canUsuallyCheckForUpdates - able to check for updates
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC waitForOtherInstances - beginning polling
AUS:SVC waitForOtherInstances - no other instances found, exiting
AUS:SVC Checker:getUpdateURL - update URL: https://aus.waterfox.net/update/Waterfox/G4.0.7/Linux_x86_64/default/Linux%205.16.0-1-amd64%20(GTK%203.24.31%2Clibpulse%2015.0.0)/ISET:SSE4_2,MEM:15853/2402220wfx/default/update.xml?force=1
AUS:SVC Checker:checkForUpdates - sending request to: https://aus.waterfox.net/update/Waterfox/G4.0.7/Linux_x86_64/default/Linux%205.16.0-1-amd64%20(GTK%203.24.31%2Clibpulse%2015.0.0)/ISET:SSE4_2,MEM:15853/2402220wfx/default/update.xml?force=1
AUS:SVC Checker:onLoad - request completed downloading document
AUS:SVC Checker:onLoad - Getting sslStatus failed.
AUS:SVC Checker:onLoad - number of updates available: 0
AUS:SVC UpdateService:removeDownloadListener - Warning: Didn't remove non-existent listener
AUS:SVC getCanApplyUpdates - testing write access /home/rektal/waterfox/update.test
AUS:SVC shouldUseService - returning false
AUS:SVC getCanApplyUpdates - able to apply updates
AUS:SVC Checker:getUpdateURL - update URL: https://aus.waterfox.net/update/Waterfox/G4.0.7/Linux_x86_64/default/Linux%205.16.0-1-amd64%20(GTK%203.24.31%2Clibpulse%2015.0.0)/ISET:SSE4_2,MEM:15853/2402220wfx/default/update.xml
AUS:SVC UpdateService.canUsuallyCheckForUpdates - able to check for updates
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC Checker: checkForUpdates, force: false
AUS:SVC UpdateService.canUsuallyCheckForUpdates - able to check for updates
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC Checker:getUpdateURL - update URL: https://aus.waterfox.net/update/Waterfox/G4.0.7/Linux_x86_64/default/Linux%205.16.0-1-amd64%20(GTK%203.24.31%2Clibpulse%2015.0.0)/ISET:SSE4_2,MEM:15853/2402220wfx/default/update.xml
AUS:SVC Checker:checkForUpdates - sending request to: https://aus.waterfox.net/update/Waterfox/G4.0.7/Linux_x86_64/default/Linux%205.16.0-1-amd64%20(GTK%203.24.31%2Clibpulse%2015.0.0)/ISET:SSE4_2,MEM:15853/2402220wfx/default/update.xml
AUS:SVC Checker:onLoad - request completed downloading document
AUS:SVC Checker:onLoad - Getting sslStatus failed.
AUS:SVC Checker:onLoad - number of updates available: 0
AUS:SVC Checker: checkForUpdates, force: true
AUS:SVC UpdateService.canUsuallyCheckForUpdates - able to check for updates
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC Checker:getUpdateURL - update URL: https://aus.waterfox.net/update/Waterfox/G4.0.7/Linux_x86_64/default/Linux%205.16.0-1-amd64%20(GTK%203.24.31%2Clibpulse%2015.0.0)/ISET:SSE4_2,MEM:15853/2402220wfx/default/update.xml?force=1
AUS:SVC Checker:checkForUpdates - sending request to: https://aus.waterfox.net/update/Waterfox/G4.0.7/Linux_x86_64/default/Linux%205.16.0-1-amd64%20(GTK%203.24.31%2Clibpulse%2015.0.0)/ISET:SSE4_2,MEM:15853/2402220wfx/default/update.xml?force=1
AUS:SVC Checker:onLoad - request completed downloading document
AUS:SVC Checker:onLoad - Getting sslStatus failed.
AUS:SVC Checker:onLoad - number of updates available: 0
`

Now I have to wait to next G4.0.8 update. I don't know why app.update.log was set to false. I have set automatically install updates (recommended) on Waterox.

**Comment by RektalTk** [comment]
Update is working. I have updated to G4.0.8 today.

**Comment by adamp01** [comment]
Thanks for confirming
