### ISSUE TITLE
Waterfox can't update by itself

### ISSUE THREAD

**Issue by ShadowElixir** [MrAlex94/Waterfox#2538]
### What happened?

Whenever Waterfox tries to update, it fails and gives me an error, the only way to update Waterfox is to update manually.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@ELXShadow - This is for G4.X correct? Could you show me the error you get please?
