### ISSUE TITLE
When you've closed your last tab, browser should show blank page upon restart

### ISSUE THREAD

**Issue by kreeben** [MrAlex94/Waterfox#2540]
When you have set up Waterfox to restore previous session on startup but in your last session you closed all your tabs, the most reasonable action for the browser to take upon restart is to show a blank page. This was implemented in FF around version 90 (perhaps even earlier).

**Comment by PrussianJaeger** [comment]
You have the ability to do this in the settings.  Under Settings > Home, click on the Waterfox Home (Default) and click Blank Page.

**Comment by kreeben** [comment]
No, that doesn't work or is not what I mean. As I mentioned, I have set up WF to restore previous session. But when I click "close" on the last of my open tabs, that should mean I have closed the session. Next time I open WF a blank page or WF home page should show.

**Comment by kreeben** [comment]
This was apparently fixed in v5.
