### ISSUE TITLE
[G4.0.6] Typo 'Firefox' in 'Problem loading page'

### ISSUE THREAD

**Issue by mukhumaev** [MrAlex94/Waterfox#2544]
### What happened?

If an error occurs during the page opening, the text with the word Firefox is displayed.

![6a2Pdnv](https://user-images.githubusercontent.com/47594681/150870724-a7774e24-d366-49fc-a7ad-c66500cd841a.png)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by adamp01** [comment]
Thanks @mukhumaev - I'll get this sorted
