### ISSUE TITLE
Multiple Tools missing from "Customize Toolbar" on new profiles

### ISSUE THREAD

**Issue by Tydoki** [MrAlex94/Waterfox#2545]
### What happened?

Some tool are missing...
zoom tools
full screen
screenshot

Old
![waterfox_xtX3kUV2d1](https://user-images.githubusercontent.com/49407654/150903198-90d9256b-86cf-45e3-81c8-cb56cb8a9f81.png)

New
![waterfox_k5WEPrO8QH](https://user-images.githubusercontent.com/49407654/150903209-1f90de6f-b882-459e-8dd4-20420c283da4.png)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@Tydoki - We set those widgets as default items in the Status Bar, which is why they will be missing from the Customize page. I didn't full consider this when implementing. We'll have a think about what to do regarding this.

**Comment by Tydoki** [comment]
@adamp01 Ah okay. Yeah I use to use the zoom tools within my main toolbar. I've never used the status bar. I've never really seen a use for it.

**Comment by adamp01** [comment]
If you have the status bar showing when you go into Customize, you should be able to drag from there to wherever you want.

**Comment by Tydoki** [comment]
Ah okay. I'd suggest just have the status bar auto open when you go to customize. Thanks!

**Comment by adamp01** [comment]
Agreed - will update so that this happens. Thanks for raising this one!
