### ISSUE TITLE
[bug] "firefox" still present as a name in certain strings

### ISSUE THREAD

**Issue by tx46** [MrAlex94/Waterfox#2549]
### What happened?

When a web socket fails to connect, the error message says "Firefox can’t establish a connection to the server at <url>". Notice the stylized apostrophe (’ instead of ') in can't.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Firefox can’t establish a connection to the server at wss://....
```

**Comment by thunderstone135** [comment]
Hi, I also noticed this in the latest version (G4.0.7) on Windows.

![Imgur](https://i.imgur.com/Mm1oNeJ.png)
