### ISSUE TITLE
Visibility:hidden in combination with backdrop-filter

### ISSUE THREAD

**Issue by JoniVanderheijden** [MrAlex94/Waterfox#2550]
### What happened?

A client reported an issue with a website I look after (myer.com.au). They mentioned that they continuously saw a blurry overlay, which was only supposed to be there when interacting with our menu.

I investigated and it seems it's linked to the browser (Waterfox).

Are you across any issues that would make the browser not respect the inline styling `opacity: 0; visibility: hidden;`? You can look for the class `MuiBackdrop-root` to find the element on myer.com.au.

This is not there in Firefox.

It's that visibility: hidden isn't being respected by Waterfox when used in conjunction with thebackdrop-filter property
backdrop-filter is disabled in Firefox which is likely why we don't see this bug in that browser

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Thanks for raising this @JoniVanderheijden. `layout.css.backdrop-filter.enabled` is locked as true in Waterfox as it is used by one of our default themes. We are going to have a discussion about this one and will let you know the outcome.

**Comment by adamp01** [comment]
Pref is now unlocked, so users can flip it if required.
