### ISSUE TITLE
Can't select version and platform on Github bug report

### ISSUE THREAD

**Issue by Schn4pper** [MrAlex94/Waterfox#2555]
### What happened?

I am unable to select the version and the platform in the Github bug report form... When I click on it, the items show up but nothing happens when I select one of them, making it impossible to submit the issue as the version is a mandatory field... I have used Chrome to create the bug report.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Hi - If this is for G3 we won't fix as we are only developing G4 now.
