### ISSUE TITLE
Crash on G3.2.3 . Is this the latest stable version?

### ISSUE THREAD

**Issue by adonios77** [MrAlex94/Waterfox#2559]
### What happened?

![crash](https://user-images.githubusercontent.com/67506714/152080001-b552a74d-991f-4986-b709-3a48f9ec4ff0.PNG)
Is G3.2.3 the latest stable?  

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@adonios77 - [G4.0.7](https://github.com/WaterfoxCo/Waterfox/releases/tag/G4.0.7) is the current stable release. G3.2.3 is from 07 Jun 2021, and had a follow up release the next day.

**Comment by adonios77** [comment]
The ONLY version that works is G323 & G326(prtbl). (I'm on 64bit windows 7 & 10 dual boot)
The G4.x versions says something gibberish about SSE4.2. I assume that works ONLY for those who have "something" that called "SSE4.2".

So, for example, it's not working on "**AMD Athlon**(tm) **64** X2 Dual Core Processor 3800+   2.00 GHz" like mine.
I wondering how many people understand what SSE4.2 means, and I assume that's even very few own this "SSE4.2" .

I used Firefox since always but the last years Firefox plight enforcing things more & more every day and the rest browsers even more. I know many firefox users that don't want to get updates, because loosing their settings/tools, and this is sad but true.
  That's why **Waterfox is my only hope** but... I don't see it comes. :(
