### ISSUE TITLE
Can't select Dark Theme when using Lepton Theme on Linux

### ISSUE THREAD

**Issue by techsk8** [MrAlex94/Waterfox#2562]
### What happened?

Using `waterfox-g4-bin-0.6-0`package from AUR on Arch.
### On Linux that doesn't work by any means that I know of.
I only get the Lepton white and can't switch to the dark variant, a thing that on Windows 10 works by nicely asking you which one you want to use just after installation. Is there any way to fix that and make the dark theme work on Linux also? 
I've also tried the official build from the waterfox website but no joy. Thanks

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Could you try creating a new number var in `about:config` called `ui.systemUsesDarkTheme` with a value of `1`?

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/4728920/152767068-41335509-9acd-46f2-8c95-ae06ea37b225.png">

**Comment by techsk8** [comment]
Thanks for the tweak, but it doesn't work. Restarted it a few times, still doesn't do anything.
![image](https://user-images.githubusercontent.com/71723339/152790154-c79c3ca0-8707-4ed6-bad1-436eb630d4a8.png)

**Comment by Tau5** [comment]
I'm experiencing the same thing, I don't know hot to fix it

**Comment by techsk8** [comment]
I haven't found any fix yet either, @Tau5.

**Comment by adamp01** [comment]
Unfortunately all the CSS for Lepton relies upon the system theme AFAIK, so I believe this is a known issue for Arch that currently we won't be able to fix.

Maybe @black7375 has had similar issues raised in the Lepton repo?

**Comment by black7375** [comment]
In pure Firefox, there was no theme color related report.
I'll investigate after a later time.

The current guess is that the manifest value is forced.
https://github.com/WaterfoxCo/Waterfox/blob/current/browser/themes/addons/lepton/manifest.json

IMO, The ideal way to solve this bug is to distinguish between `layout theme`(`lepton`, `australis`) and `lw-theme`(just color, header image).

**Comment by adamp01** [comment]
I think I should be able to add a pref and build some functionality to force using the `dark_theme` outlined in the manifest. I'll have a play around when I have time.

**Comment by techsk8** [comment]
That would be amazing @adamp01. Looking forward to hearing from you any news!

> Unfortunately all the CSS for Lepton relies upon the system theme AFAIK, so I believe this is a known issue for Arch that currently we won't be able to fix.

The issue it's not only in Arch. It's on every Linux Distro I've tested it on: Debian, Kali, Ubuntu.
I always use Dark themes with my Linux Distros hence the issue.

**Comment by adamp01** [comment]
The PR I've just done will enable the `ui.systemUsesDarkTheme` pref to actually work on Linux distros.

I'm doing an additional PR to add a toggle for that to `about:preferences` as well.

**Comment by techsk8** [comment]
Adam. That's just amazing news. Thank you for your efforts. Much much appreciated! 😄 
By the way, since we're at it, I was wondering if Waterfox will ever have group tabs like Brave has? I'm asking this cause I've read in some GH thread that this is totally impossible to implement in any Firefox-based browser :/ Thanks
