### ISSUE TITLE
removing a bookmark does not work

### ISSUE THREAD

**Issue by SkySpnc** [MrAlex94/Waterfox#2563]
### What happened?

the bug: removing bookmarks does not work
expected: the bookmark gets removed upon clicking remove bookmark
actual: nothing happens

### Reproducible?

- [x] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by SkySpnc** [comment]
![waterfox_QmeL3AHHt1](https://user-images.githubusercontent.com/83870752/152665818-6dcf8d99-3525-4f95-81e3-e859ae511c93.gif)

**Comment by SkySpnc** [comment]
also happens in troubleshoot mod
![waterfox_BrowNTzzRF](https://user-images.githubusercontent.com/83870752/152665838-6372be37-427c-4ff6-93ba-badd02ab3c8f.gif)
e

**Comment by adamp01** [comment]
@SkySpnc - I need some more information here before I can do anything about this. 

1. Version of Waterfox?
2. Operating system
3. Some attempt to retrieve relevant logs -> Ctrl + Shift + J will open the browser console, if you then attempt to remove the bookmark and see any new errors pop up please post them here.

**Comment by SkySpnc** [comment]
@adamp01 
1 g4.0.7 64bit
2 Windows 10 21h2 19044.1526
3 errors in attached
![image](https://user-images.githubusercontent.com/83870752/155864082-8f60e5df-410b-4080-bea2-400d859adb05.png)

**Comment by baudren** [comment]
I also encounter this issue, on
1. Waterfox version G4.0.7 (64-bit)
2. Windows 10 Enterprise, 20H2, 19042.631

with the exact same errors in the browser console (different guid of course)

**Comment by adamp01** [comment]
Seems like your `places.sqlite` has become malformed (I'll look into that as a separate piece). Did you import anything from another profile? Perhaps from Classic?

A suggestion to hopefully remedy this would be:
1. Go to `about:profiles` and open you current profiles root directory.
2. Create a new profile from `about:profiles`.
3. Copy everything from you current profile to the newly created profile, but make sure to delete `places.sqlite`.
4. Launch the new profile in a new browser from `about:profiles`.
5. After a short period of use the browser should import your bookmarks from the bookmark backups folder (it's a delayed process, so can't give you a definitive amount of time on this  - may also need to restart with the new profile as well).
6. Attempt to delete the bookmarks again (note: history will be lost as that is also stored in `places.sqlite`).

**Comment by SkySpnc** [comment]
seems to have worked. cheers.

one extra thing tho. image below is just a little annoying. outdated term, and should be using they as not everyone identifies as him or her. it feels exclusive and not inclusive, the opposite of what id imagine waterfox is going for.
![image](https://user-images.githubusercontent.com/83870752/156865288-4a01fbba-7284-40be-9416-1ba5f207a8d7.png)

**Comment by SkySpnc** [comment]
just a little bit of extra information before closure tho: this happens every time ive installed waterfox. it may be because i also have firefox installed

**Comment by adamp01** [comment]
@SkySpnc  - Thanks for highlighting the wording there, I will get that updated on Monday morning as it certainly is exclusive and unnecessary. 

Having Firefox installed shouldn't be an issue as profile directories are kept separate, the only thing I could imagine causing this is if you used the profile importer (import bookmarks etc.) and something went wrong. If that is the case it would be good to know as it gives me somewhere to start troubleshooting.

When you say "Every time I've installed Waterfox", you mean installing on a new system or installing an update?

**Comment by SkySpnc** [comment]
@adamp01 every machine ive tried it seems to happen, although i skip bookmark importing. it may be that.
i mean installing on a new machine/ os install

**Comment by baudren** [comment]
@adamp01 Removing the `places.sqlite` file from my profile directory solved the issue for me. There was a `places.sqlite-corrupted` file, as well, and yes, I tried to import my bookmarks from Firefox just after the install, which failed. Maybe this caused the issue, at least on my side.

Thank you in any case for the help and investigation, cheers!

**Comment by adamp01** [comment]
Thanks for the information both - I'll take a look into bookmark/history migration to see if we can stop this from happening.
