### ISSUE TITLE
The conversation website

### ISSUE THREAD

**Issue by TonyH1234** [MrAlex94/Waterfox#2565]
### What happened?

Images are not displaying at theconversation.com
Firefox and Chrome don't have this problem.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by ksy36** [comment]
This is a duplicate of https://github.com/WaterfoxCo/Waterfox/issues/2529
