### ISSUE TITLE
Package as a flatpak?

### ISSUE THREAD

**Issue by PrussianJaeger** [MrAlex94/Waterfox#2566]
I'm newer to Linux and in the process of moving over from Windows, and I was trying to install Waterfox but it wasn't incredibly intuitive and didn't work properly on my system.  Perhaps packaging and distributing Waterfox as a flatpak would be better?  It is not only more user friendly, but also will work across distributions without fail, won't have any dependency issues, can be easily updated, and easily installed.

**Comment by ronyAhmed1200** [comment]
Or package as a appimage.. As nowadays appimage are ruling the world of software/ package...

**Comment by PrussianJaeger** [comment]
Not really, flatpaks are basically the future.  ElementaryOS is fully flatpak based now; they're the most used between flatpaks, appimages, and snaps.  They can be automatically updated without external tools and they work with the system and themes, whereas appimages can't, and flatpaks are just better for most applications' usages.  An appimage would be fine for a one-use application or old software to keep it isolated, but for a browser flatpak is better, especially to receive security updates as soon as they come out.

**Comment by hawkeye116477** [comment]
> Or package as a appimage

AppImage already exists => https://appimage.github.io/Waterfox_Fourth_Generation/.

------------------------------
In case of Flatpak, problem may be that it requires packaging some of the additional dependencies with it and that could be problematic from license side.

**Comment by adamp01** [comment]
Hi - as it stands we won't be releasing a flatpak. I will make a note to add some usage instructions to the README for the tarball.
