### ISSUE TITLE
Winget is giving me an older version

### ISSUE THREAD

**Issue by thedoggybrad** [MrAlex94/Waterfox#2567]
### What happened?

I upgraded to Waterfox G4.0.7 using the installer when I type winget upgrade --all (Winget Updates Programs) it will give the G4.0.6 so to cancel it I type CTRL + C. Can anyone submit the latest version to winget-pkgs to get around to not manually update each programs i havw because winget is giving older version of Waterfox.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by thedoggybrad** [comment]
Can anyone add it to winget-pkgs to fix the issue? I can't.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Winget packages are supported by community, an update [was already added](https://github.com/microsoft/winget-pkgs/pull/45757) a few hours ago.

**Comment by thedoggybrad** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou it is still giving me 91.5.0 (G4.0.6) instead of 91.6.0 (G.4.0.7) since the new version was named G again not starting with 91 so winget may be confused of what is really is the new version.

**Comment by thedoggybrad** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou I have already the latest version so, why winget is giving me the older version again. Can you create manifest for 91.6.0 here: https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/Waterfox/Waterfox

**Comment by thedoggybrad** [comment]
Can anyone help me.

**Comment by thedoggybrad** [comment]
I will just open a new one
