### ISSUE TITLE
Waterfox G4.0.7 Latest Release Crash on Launch 

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#2568]
### What happened?

Once more I try to run an install of G.4 Waterfox on my Windows 7 PC and Laptops
The Machines currently have G3.2.6 (64-bit) 
Both Machines have a Quad Core 3ghz AMD and Both have 32 Gig Ram... 
The Installer starts and when completed when you go to launch it there it crashes... 
![image](https://user-images.githubusercontent.com/20975332/153623207-dc06d94a-d3a0-426e-9fcc-feaf36a5c93b.png)

The Problem Details 
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	waterfox.exe
  Application Version:	91.6.0.8076
  Application Timestamp:	62053878
  Fault Module Name:	waterfox.exe
  Fault Module Version:	91.6.0.8076
  Fault Module Timestamp:	62053878
  Exception Code:	c000001d
  Exception Offset:	0000000000006d5b
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	a911
  Additional Information 2:	a911e4f90f6027f6a361a93a31bad0db
  Additional Information 3:	91f5
  Additional Information 4:	91f59583d2b8218b63be7015a938860c

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Every since G.4 has been released it will not Install I try each update release and same thing over and over again. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
We are currently profiling installers built with different compile flags, and we may re-introduce support to non SSE4.2 instruction sets in a future release. As it stands right now, this is to be expected.
