### ISSUE TITLE
Issue with this Bug Report Page and Waterfox G3.2.6 (64-bit)

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#2569]
### What happened?

When I am filling out a Bug Report on here using waterfox 
G3.2.6 (64-bit) 
I can not chose Current Version Filed nor the OS when Submitting why is it blocked?
I have to use Chrome to post the issues I am having why are the fields not selectable in Waterfox G3.2.6 (64-bit)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Closing as G3.2.6 is no longer being updated.
