### ISSUE TITLE
in xubuntu 21.10 won't run 4.0.7 version

### ISSUE THREAD

**Issue by NektoNektovich** [MrAlex94/Waterfox#2570]
### What happened?

cpu intel pentium(r) dual-core e6300 @2800GHz  xubuntu 21.10 - 64bit won't run 4.0.7 version. firefox 97.0- 64bit works fine. I believe that you removed support for old hardware, unlike the original firefox, you discriminate against users of old, but quite up-to-date hardware :(

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by hawkeye116477** [comment]
As a alternative, you can try one of my packages (AppImage or from apt repository) following with https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/blob/master/README.md.

**Comment by NektoNektovich** [comment]
> As a alternative, you can try one of my packages (AppImage or from apt repository) following with https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/blob/master/README.md.

thanks, appimage works! 👍 It would be nice to have a link to download appimage waterfox on the official website!
