### ISSUE TITLE
Requesting Support for WEB RTC INSERTABLE STREAMS to allow End-to-End Web RTC Support.

### ISSUE THREAD

**Issue by thedoggybrad** [MrAlex94/Waterfox#2578]
Requesting Support for WEB RTC INSERTABLE STREAMS to allow End-to-End Web RTC Support.

**Comment by MrAlex94** [comment]
Please follow the Mozilla bug filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1749547
