### ISSUE TITLE
Compatibility issue with chrome add-ons. 

### ISSUE THREAD

**Issue by krusion** [MrAlex94/Waterfox#2580]
### What happened?

When I try to install chrome add-ons I get this error: 
"This addon could not be installed because not all of its features are supported. " 

I tried installing two different add-ons but get the same message. 
The addons I tried to install were ublock origin (I was able to install it from the firefox add-ons) and Real Debrid Download Manager which is not available on firefox store. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@krusion - Currently there is one major API that Firefox/Waterfox doesn't support that Chrome extensions use extensively, `externally_connectable`. We don't have the capacity in the team to look at integrating this as it stands.

**Comment by DavideCannonito** [comment]
you even got to installing (even tho it failed)? me and an another user cant #2602 tl;dr: it asks to save or "open" the file. how did you get to install chrome extentions pls
