### ISSUE TITLE
Remove automatic updates & update notifications from AUR package.

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2581]
**Is your feature request related to a problem? Please describe.**
Since the Waterfox AUR package is seldom updated in time, the options to automatically install updates/receive update notifications are useless because 1: the package manager of choice will automatically handle those updates & 2: the AUR package is never updated in time, which leads to annoying notifications like [this one](https://i.imgur.com/IomLtVe.png).

**Describe the solution you'd like**
Remove automatic updates & update notifications from the AUR package.

**Describe alternatives you've considered**
Using Librewolf.

**Additional context**
N/A

**Comment by adamp01** [comment]
Closing this as the AUR package is not maintained by the core Waterfox team.

**Comment by ghost** [comment]
@hawkeye116477

**Comment by hawkeye116477** [comment]
@SkMyPP Done => https://aur.archlinux.org/cgit/aur.git/commit/?h=waterfox-g4-bin&id=a9f8bffb59dd40099444fcefb474980825926251.
