### ISSUE TITLE
Marionette mode

### ISSUE THREAD

**Issue by GermanAizek** [MrAlex94/Waterfox#2582]
@MrAlex94,
Marionette mode supported? If yes, then which version of geckodriver is required for use.
I found in this repository `testing/geckodriver` latest commit 2020.
How many features have been added to the browser since then and are not implemented in `testing/geckodriver`?

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Linux, Windows

**Comment by adamp01** [comment]
Marionette mode isn't something that we consider when building the browser, although it is kept up to date with the latest changes to ESR91 from Firefox. Looks like the most recent changes in G4 were in July 2021: https://github.com/WaterfoxCo/Waterfox/tree/current/testing/geckodriver.

**Comment by GermanAizek** [comment]
@adamp01,
Can I participate in marionette support for waterfox?

**Comment by GermanAizek** [comment]
@adamp01,
Can I participate in marionette support for Waterfox? I can maintain the relevance of geckodriver work in your project, from experience I am current maintainer webdriverxx C++ api for Selenium Server Standalone.
More info: https://github.com/GermanAizek/webdriverxx
