### ISSUE TITLE
Change them to Firefox Leptopn and this happens

### ISSUE THREAD

**Issue by gotshadowbantempaccount** [MrAlex94/Waterfox#2589]
### What happened?

Change them to Firefox Lepton and this happens

client complain that he can't read item menu, and he is damn right ?

http://output.jsbin.com/acucan/9

![273170920_635292380873699_5330058284152088061_n](https://user-images.githubusercontent.com/88304290/155415095-2ac8034a-37e1-4f58-9602-bbe4fc8df2b8.jpg)

![ddddd](https://user-images.githubusercontent.com/88304290/155415409-6fc551a3-b79a-467b-b0fd-c4d192da5ca2.png)

Can you read on your screen ?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by black7375** [comment]
It would have been resolved in the latest version.
https://github.com/black7375/Firefox-UI-Fix/issues/320
https://github.com/WaterfoxCo/Waterfox/issues/2584
