### ISSUE TITLE
Video stream player fails to load

### ISSUE THREAD

**Issue by Yousuckatthis** [MrAlex94/Waterfox#2594]
### What happened?

Holy Crap!!!!!! The level and quantity of BS I have to go through, just to report a possible bug, is UNACCEPTABLE. Who the hell do you think you are? Why do I have to sign up at all? How could you know whether or not I use a particular password elsewhere, if you are not spying on me?? Or do you just LIE to people when they are trying to sign up? Is this what you wanted ALEX??  I could go on...but wont. I will copy this to other outlets to keep you honest.
 After update to G4.0.7 one specific website no longer works. the site is https://vaughn.live/atlantis_movies  The player fails to load. I do not know which player they are using.
It offers the error message : ERROR LOADING PLAYER: ID #3134, that becomes 3133 after a second. I have tried without addons, the other members on the site say it is working, it works with a chromium based browser and it used to work with the previous version of waterfox. So I hope you respond with an appropriate response and not a copy and paste try all this stuff before we will take you seriously. I have tried that stuff.  Here is the rest of the info you will want.
windows 10 pro 21h2 19044.1566  Experience Pack 120.2212.4170.0, I have the most current ver of JAVA, I have vlc installed as default player. I do not have FF installed and do not wish to.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by thunderstone135** [comment]
That's odd. I'm also using G4.0.7, and I checked the link you provided, but the movie loaded properly. Check the Browser Console (Ctrl+Shift+J) and see if you are getting any error.

**Comment by Yousuckatthis** [comment]
Hello and Thank you.

Did what you suggested, got this:

Unexpected event profile-after-change URLQueryStrippingListService.jsm:224
ExtensionPreferencesManager API ftpProtocolEnabled created but addSetting was not called.
Attempt to override an existing message: "onboarding-multistage-theme-label-light".
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_quickRestart” browser.xhtmlKey event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml

this.window.gBrowserInit is undefined ext-browser.js:1130
Error: Could not get children of file(C:\Users\SysCo\AppData\Local\Waterfox\Profiles\42amwo4m.default-default\thumbnails) because it does not exist PromiseWorker.jsm:106

1646684655900 addons.productaddons ERROR Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https." nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)" location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 152" data: no] Log.jsm:723

I had tried it without addons and still didn't work, but tried again just now and it works with addons disabled. So...can you determine which one or what type of addon it would be? I can of course go through them all. I have used these 5 addons for quite some time with no problems, and these are the only ones I use.

Ublock Origen
Popup Blocker Ultimate
Save Page WE
Easy Youtube downloader Express
New Tab Overide

Is there maybe still an issue on "your" side? I usually wait to update to new versions because "things" change and not for the better. Like the default bookmark location. Seriously, who thought that up?

Anyway thank you for your time.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------

**Comment by thunderstone135** [comment]
> 1646684655900 addons.productaddons ERROR Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https." nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)" location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 152" data: no] Log.jsm:723

I have a feeling that you just need to tweak a pref for this error.
I'm not sure which one, but you can try this 👇 
1. Go to about:support
2. Loof for Profile Folder, then click Open Folder
3. Look for prefs.js and copy it somewhere safe (just in case)
4. Create a user.js file
5. Copy the prefs [here](https://pastebin.com/raw/TTZYBCqS) to your user.js file
6. Restart Waterfox

The prefs I provided are mostly default with a few tweaks here in there to harden Waterfox a bit more.
Do take note that this is just a stopgap measure since I'm not that tech savvy.

**P.S.** If for some reason you are not comfortable with the changes, you can delete the user.js file and copy your saved pref.js back to your Profile Folder.

**Comment by Yousuckatthis** [comment]
Sorry about the wait. Had to deal with a car malfunction. So I created user.js with the prefs offered and added it to the profile folder. I did not remove the original prefs.js as you did not say to do so. Restarted browser, it did not fix the issue. I then deleted prefs.js and restarted the browser, again no luck.
After talking to you Waterfox has come out with yet another update. Opinions??Do you think I should fix my issue first, or install it and hope? :)

Thanks for your time.

P.S. The default settings are absurd. I can't even open a new tab without choosing from a list of what kind of page I want to open???

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by Yousuckatthis** [comment]
Well ! I cant undo the changes your user.js suggestion caused. Removing and replacing with the original does not work. I tried many ways of doing so. I STRONGLY recommend that you not tell anyone to do this in the future.
I used revo-uninstaller to completely remove WF. Saving my bookmarks of course. And reinstalled with G4.0.8 , re-added my addons and the website works now.

Again, thanks for trying. Consider issue resolved.

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by thunderstone135** [comment]
> Well ! I cant undo the changes your user.js suggestion caused. Removing and replacing with the original does not work.

That's odd. Normally, replacing prefs.js works in restoring settings. Unless, you restored it while Waterfox is open. If that's the case, then replacing prefs.js will not work.
> Again, thanks for trying. Consider issue resolved.

Well, I'm glad that you were able to fix the issue 👍
