### ISSUE TITLE
Background color not shown in bookmarks, history...

### ISSUE THREAD

**Issue by jburf** [MrAlex94/Waterfox#2597]
### What happened?

In previous versions, the Show All History/Manage Bookmarks tabs, would use the background color in settings. Now, it's bright white, which hurts my eyes, & I'm sure others... even if the background color is set to always override. I've always set it to high contrast only, & it always used the background color.
A fix would be great, as any dark theme doesn't effect those tabs.
Thanks!

(By the way, I don't have a recent version of Firefox installed, but on older versions, it used the background color for those tabs)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@jburf - Hey thanks for raising this, we will try to get to the bottom of it.

I've tested on Windows with G4.0.8 and high contrast with both Lepton and Firefox Dark themes, neither displayed the behaviour you have stated.

Would you be able to go to App Menu -> Help -> About Waterfox and let me know the version number that you are currently on when seeing this. 

If you could also let me know which theme you are using hopefully I can get this replicated.

**Comment by jburf** [comment]
Thanks for the reply. I'm using v4.07... just got the update to 4.08 msg, but haven't updated yet. It's happening with most any theme I try... a couple of the dark themes included with the install, those tabs display black. None of the included themes display my background color. I'm currently using "Real Windows Classic" theme, which is easier on my eyes.
But everything in background is bright white... ie: address bar, etc. The application menu on the far right of the address bar, does show my background color.
If there was some kind of overall brightness slider control, that would be helpful.
Again thanks for responding!

**Comment by jburf** [comment]
I updated to v4.0.8... no change.

**Comment by adamp01** [comment]
@jburf As this is not for the default themes, it makes things harder. I can see that "Real Windows Classic" was last updated in 2019. As Waterfox G4 is based on Firefox ESR91 there are going to be changes that the theme creator has not accounted for. Unfortunately, due to the sheer number of available themes and number of changes in Firefox between 2019 and ESR, we aren't going to be able to solve this one for you.

If it happens to many themes from mid-2021 onwards that are designed for ESR91 onwards please re-open and list those for me, otherwise it is up to the theme designer to update.

**Comment by jburf** [comment]
Thanks for your efforts. I guess I wasn't clear, it does happen with the default themes, like Firefox Modern Light, or Waterfox Australis Light. It happens with every theme I've tried, except the default dark themes, which display white text over black. 
If your background color displays in "Show All History" using the default light themes, could there be a setting in advanced settings that I have misconfigured?
Thanks again for your help!!

**Comment by MarkoIndaco** [comment]
Same happens to me. I notice that when activate some dark theme the Settings menu's are dark, so it accept the theme but, if i close the Settings tab and come back it turns to white, like it gets disabled in some way.
I notice that only the pages that comes from "about:-----" addresses are affected.
I'm using Waterfox G4.1.2.1
PS
I dont know if the issue could stand for but I have also the last stock FIrefox with lot of addons, and Waterfox synchronized with Mozilla account.
Thanks in advance for any help
