### ISSUE TITLE
make `dom.dialog_element.enabled` true by default

### ISSUE THREAD

**Issue by Yay295** [MrAlex94/Waterfox#2598]
**Is your feature request related to a problem? Please describe.**
The [HTML dialog element](https://developer.mozilla.org/en-US/docs/web/html/element/dialog) is now supported in every modern browser. It is also supported by the latest version of Waterfox (G4), but it was not enabled by default in Firefox until version 98. Since it seems to be working fine in Waterfox, I think it should be enabled by default so that sites using the dialog element will work,

**Describe the solution you'd like**
Make `dom.dialog_element.enabled` true by default.

**Describe alternatives you've considered**
I have changed this setting for myself.

**Comment by decembre** [comment]
Yes, tested on Waterfox Classic the about:config work too with it.
Test it after on:
<a href="https://developer.mozilla.org/en-US/docs/web/html/element/dialog">&lt;dialog&gt;: The Dialog element</a>
and
<a href="http://niutech.github.io/showModalDialog/demo.html">[showModalDialog polyfill demo](http://niutech.github.io/showModalDialog/demo.html)</a>

**Comment by MrAlex94** [comment]
Looks like they enabled it [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1733536), without worrying about fixing all the accessibility features. Will do the same tomorrow 👍
