### ISSUE TITLE
Slight margin issue on the waterfox website

### ISSUE THREAD

**Issue by jakenvac** [MrAlex94/Waterfox#2608]
### What happened?

Sorry if this isn't allowed here, not sure where else I can report it. I did check to see if there was a repository for the site to submit a PR myself but I couldn't find one.

For platforms that offer multiple downloads from the homepage; there is no margin between the two buttons.
I know this is a relatively small issue, but it's the small things that turn potential users away if something doesn't quite look right.

I have test with Waterfox, Firefox, Chromium & Safari.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9119973/158576012-27654206-501e-4f4c-8310-6ca5766cb50f.png">

Again if there is a public repository that I'm missing, please let me know and I'm happy to submit the PR myself.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

macOS

**Comment by adamp01** [comment]
Thanks @JakeHL - there isn't a public repo for the website, so here is the best place.

This has been on my to do list for a while but just not got round to it. I'll quickly fix this and a couple other things tomorrow AM.
