### ISSUE TITLE
Invalid property value: width fit-content

### ISSUE THREAD

**Issue by uvulpos** [MrAlex94/Waterfox#2613]
### What happened?

I do websites and stuff and I used the CSS property `width: fit-content`, but Waterfox says in inspector mode “invalid property value”, so I can't use it. My layout works just fine in Chrome and Firefox itself.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

macOS

### Relevant log output

```shell
---
```

**Comment by uvulpos** [comment]
**Jetbrains**
<img width="346" alt="Screenshot 2022-03-20 at 11 25 11" src="https://user-images.githubusercontent.com/53957681/159158311-5ae438c3-c122-4cd3-bd33-1685cc023505.png">

**Waterfox** (my mouse is over that warning sign)
<img width="321" alt="Screenshot 2022-03-20 at 11 34 00" src="https://user-images.githubusercontent.com/53957681/159158307-9016f7db-2018-4c91-8f04-8ffddc0ec16c.png">

**Firefox**
<img width="305" alt="Screenshot 2022-03-20 at 11 34 58" src="https://user-images.githubusercontent.com/53957681/159158355-314dcbf2-71f8-45b1-9be7-85ed3ba41dfa.png">

**Comment by adamp01** [comment]
@uvulpos - It's curious it works on FF, maybe they implemented differently after 91, [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content) suggests the only option on FF is to use the vendor prefix `-moz-fit-content`.

**Comment by uvulpos** [comment]
Mh, now it works in Waterfox but not in chrome anymore

```diff
-width: content-fit
+width: -moz-fit-content
```

**Comment by adamp01** [comment]
Use both in your css, if it's not available it will be ignored:
```
width: fit-content;
width: -moz-fit-content; 
```

**Comment by uvulpos** [comment]
@adamp01 It works for my case, but isn't this a bug you should fix? If it wouldn't work in FF either, ok, but this is clearly a  bug from waterfox 🤔
