### ISSUE TITLE
Some Icons Not Showing In Tools Menu > Browser Tools

### ISSUE THREAD

**Issue by thunderstone135** [MrAlex94/Waterfox#2614]
### What happened?

**Describe the bug**
Hi, I just wanted to let you know that some icons are not showing in the **Tools Menu > Browser Tools**. However, the icons in the **App Menu > More Tools** are all present.

**Expected behavior**
The icons in the **Tools Menu > Browser Tools** should reflect the icons showing in the **App Menu > More Tools**.

**Screenshots**

**_App Menu_**
![Imgur](https://imgur.com/XoJ6YnI.png)

**_Tools Menu_**
![Imgur](https://imgur.com/XDGNaMs.png)

**Additional context**
I also posted the issue [**here**](https://github.com/black7375/Firefox-UI-Fix/issues/349) just in case.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
N/A
```

**Comment by adamp01** [comment]
Will close this out once Lepton is updated and pulled in.

**Comment by thunderstone135** [comment]
The icons are still not showing in the **Tools Menu > Browser Tools** even after applying the latest [**commits**](https://github.com/black7375/Firefox-UI-Fix/commits/master). I'm not sure if this can be fixed via pure CSS. I tried to make modifications to the CSS by first looking inside browser.ja, but I'm having a hard time finding any CSS related codes. I'm beginning to suspect that this is hard coded 🤔
