### ISSUE TITLE
Waterfox on flathub

### ISSUE THREAD

**Issue by Darin755** [MrAlex94/Waterfox#2616]
I noticed that waterfox is only available for linux through a download of an archive containing the raw binaries. They are all in the same folder which is a bit contrary to the linux/unix file structure. It is also a bit insecure to download random binaries off the internet and run them without some sort of verification. Flatpak works on many distros and would allow for a stable and easy to install app that can be run on many Linux machines without hassle. It also allows for a official application source that is difficult to tamper with.

**Comment by Darin755** [comment]
For anyone looking for an alternative installation method for Linux there is a app image.
https://www.appimagehub.com/p/1275115

**Comment by Darin755** [comment]
On further inspection it seems that it is quiet out of date - use at your own risk

**Comment by hawkeye116477** [comment]
There is better up to date AppImage on `https://appimage.github.io/Waterfox_Fourth_Generation/`.

Anyway, if someone wants official Flatpak or any other container package, then that was already discussed ago many times and rather won't happen.

**Comment by Darin755** [comment]
It looks like this app image is the best option
