### ISSUE TITLE
MacOS Mouse Buttons 4 and 5 not working properly

### ISSUE THREAD

**Issue by aschroeder27** [MrAlex94/Waterfox#2619]
### Expected Behavior
Mouse Button 4 triggers "Browser back"
Mouse Button 5 triggers "Browser forward"

### Actual behavior
Mouse Button 4 and 5 both share the scrolling behavior of mouse button 3.

### Notes
This exact bug existed in Firefox and was fixed in version 92.

[See this Stackoverflow answer](https://stackoverflow.com/a/68532003)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

macOS

**Comment by adamp01** [comment]
@aschroeder27 - thanks for raising, will get the fix for that pulled in.
