### ISSUE TITLE
Build System

### ISSUE THREAD

**Issue by black7375** [MrAlex94/Waterfox#2635]
**Is your feature request related to a problem? Please describe.**
While searching, I found an interesting project.

**Describe the solution you'd like**
If you're interested in rolling releases, it's worth a look.

- https://github.com/dothq/browser-desktop
  - https://dothq.github.io/melon/
- https://github.com/pulse-browser/browser
  - https://github.com/pulse-browser/gluon

**Comment by adamp01** [comment]
We are aware of both of these, but thanks for raising!
