### ISSUE TITLE
[webcompat] z2.fm - video or audio doesn't play

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2636]
### What happened?

Browser / Version: Waterfox 78.10.0
Operating System: Windows 7
Tested Another Browser: Yes Other

Problem type: Video or audio doesn't play
Description: There is no audio
Steps to Reproduce:
the music and download buttons don't work

Was opened on https://github.com/webcompat/web-bugs/issues/74010

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Closing as for unsupported Waterfox version.
