### ISSUE TITLE
[webcompat] phoenixfaucets.xyz - Site fails to load due to lightning scripts error

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2637]
### What happened?

URL: https://phoenixfaucets.xyz/home

Browser / Version: Waterfox 78.12.0
Operating System: Windows 10
Tested Another Browser: Yes Other

Problem type: Something else
Description: lighning scripts
Steps to Reproduce:
the site failed to load giving error lightning scripts issue

Moved from https://github.com/webcompat/web-bugs/issues/78314

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Closing as for unsupported Waterfox version.
