### ISSUE TITLE
[webcompat] www.wtnh.com - Content of the page is displayed blurry

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2639]
### What happened?

URL: https://www.wtnh.com/

Browser / Version: Waterfox 91.6.0
Operating System: Windows 10
Tested Another Browser: Yes Edge

Problem type: Site is not usable
Description: Page not loading correctly
Steps to Reproduce:
Site displays correctly when using Edge.

Opened originally on https://github.com/webcompat/web-bugs/issues/100196

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by newsjunkie247** [comment]
I have this same issue with this page: https://pix11.com/news/local-news/brooklyn/why-new-yorkers-are-booking-rentals-they-dont-plan-to-stay-in-power-in-numbers/ It works in troubleshooting mode, but it doesn't seem to have anything to do with extensions or hardware acceleration or usercrhome, and I also tried disabling some javascript options which also doesn't help. What other settings would be affected by troubleshoot mode ?

**Comment by joeb123456** [comment]
https://wgntv.com/ the same

**Comment by adamp01** [comment]
These issues are all related to the `backdrop-filter` preference. For now, go to `about:config` search for `layout.css.backdrop-filter.enabled` and set it to `false`.
