### ISSUE TITLE
[webcompat] www.tax.ny.gov - "Secure connection failed" when trying to log in

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2640]
### What happened?

URL: https://www.tax.ny.gov/online/

Browser / Version: Waterfox 91.3.0
Operating System: Windows 10
Tested Another Browser: Yes Edge

Problem type: Something else
Description: cannot connect securely to log on. Getting error PR_CONNECT_RESET_EROR on this website [www.tax.ny.gov/online](http://www.tax.ny.gov/online) and then click LOG IN
Steps to Reproduce:
Browser EDGE worked and would let me login

Opened originally on https://github.com/webcompat/web-bugs/issues/96798

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
UA override fixes - will be resolved next release.
