### ISSUE TITLE
[webcompat] book-costcopharmacy.appointment-plus.com - The page does not load as expected

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2641]
### What happened?

URL: https://book-costcopharmacy.appointment-plus.com/ctnrml6m/?e_id=5375

Browser / Version: Waterfox 78.9.0
Operating System: Windows 7
Tested Another Browser: Yes Other

Problem type: Site is not usable
Description: Page not loading correctly
Steps to Reproduce:
Page won't load, stays blank. Tried 2 browsers

opened originally https://github.com/webcompat/web-bugs/issues/69083

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Closing as for unsupported Waterfox version.
