### ISSUE TITLE
[webcompat] www.ctv.ca - Video can not be played

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2642]
### What happened?

URL: https://www.ctv.ca/shows/south-park/the-pandemic-special-s24e2401

Browser / Version: Waterfox 78.9.0
Operating System: Windows 10
Tested Another Browser: Yes Edge

Problem type: Video or audio doesn't play
Description: The video or audio does not play
Steps to Reproduce:
This video file cannot be played.(Error Code: 246000)

opened originally on https://github.com/webcompat/web-bugs/issues/69074

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Closing as for unsupported Waterfox version.
