### ISSUE TITLE
[webcompat] connect.intuit.com - Waterfox is an unsupported browser

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2644]
### What happened?

URL: https://connect.intuit.com/portal/app/CommerceNetwork/view/scs-v1-cc259093f193419b915f78b4b734590570e5d39292604ab8920f3d6f350cefcaaf6a10d01ed144d39576ffaff6d5ce8a?cta=viewinvoicenow&locale=en_US

Browser / Version: Waterfox 78.12.0
Operating System: Windows 10
Tested Another Browser: Yes Edge

Problem type: Site is not usable
Description: Page not loading correctly
Steps to Reproduce:
Can not connect on the web site with WaterFox.

opened originally on https://github.com/webcompat/web-bugs/issues/84808

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Closing as for unsupported Waterfox version.
