### ISSUE TITLE
Where are Waterfox versions that run with SSE3 etc.

### ISSUE THREAD

**Issue by adamp01** [MrAlex94/Waterfox#2645]
Where is the only version(s) that works at different than SS4 ? I'm talking about 3.2.3 or 3.2.6 etc. Why you removed them? Please can I find them somewhere?

_Originally posted by @adonios77 in https://github.com/WaterfoxCo/Waterfox/issues/2629#issuecomment-1086680237_

**Comment by adamp01** [comment]
@adonios77 - You can find all versions on the CDN: https://cdn.waterfox.net/releases/

**Comment by adonios77** [comment]
Thanks for your answer. **This .mar files is a very bad joke!** It needs a big study to just make it usable, therefore, unfortunately, **totally unusable**! So, I assume there is not installer or even zip file. Once again: only disappointed.

**Comment by adamp01** [comment]
For Windows: https://cdn.waterfox.net/releases/win64/installer/
For Linux: https://cdn.waterfox.net/releases/linux64/installer/
For Mac: https://cdn.waterfox.net/releases/osx64/installer/

**Comment by adonios77** [comment]
> For Windows: https://cdn.waterfox.net/releases/win64/installer/ For Linux: https://cdn.waterfox.net/releases/linux64/installer/ For Mac: https://cdn.waterfox.net/releases/osx64/installer/

This is **not usable** for "average" user. I downloaded but cannot use those.
(https://wiki.mozilla.org/Software_Update:Manually_Installing_a_MAR_file) *(for developers only)

**Comment by adamp01** [comment]
These are **not** .mar files. I have linked you to Windows exectuables, tarballs for Linux and disk images for Mac. I can assure you that they are usable by the average user, as this is how we distribute Waterfox.

**Comment by adonios77** [comment]
> These are **not** .mar files. I have linked you to Windows exectuables, tarballs for Linux and disk images for Mac. I can assure you that they are usable by the average user, as this is how we distribute Waterfox.

Oh! Sorry, I did not notice. **Thank you very much, again!** :)

Please add a link somewhere in official site of Waterfox as it is very hard to finded.
