### ISSUE TITLE
[webcompat] www.dailymail.co.uk - Images from stories are not loading

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2646]
### What happened?

URL: https://www.dailymail.co.uk/ushome/index.html

Browser / Version: Waterfox 91.3.1
Operating System: Windows 10
Tested Another Browser: Yes Edge

Problem type: Video or audio doesn't play
Description: There is no video
Steps to Reproduce:
Photos included in story not display with waterfox, but do display under edge.

Opened originally on https://github.com/webcompat/web-bugs/issues/93117

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Resolved in latest version.
