### ISSUE TITLE
[webcompat] www.hulu.com - Waterfox is an unsupported browser

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2647]
### What happened?

URL: https://www.hulu.com/watch/66c6da21-0c2a-48b3-9194-650f325c3041

Browser / Version: Waterfox 91.3.3
Operating System: Windows 10
Tested Another Browser: Yes Chrome

Problem type: Site is not usable
Description: Browser unsupported
Steps to Reproduce:
Upon attempting to play a video a message comes up prompting me to update my browser, as the current version is unsupported.

opened originally on https://github.com/webcompat/web-bugs/issues/95464

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by Darin755** [comment]
I am not sure how this is a bug. If Hulu chooses not to support waterfox there is not much that can be done on the waterfox side of things. With that being said there is a extension called Chameleon which can change the browsers agent string to a different browser. I have not tested it with waterfox but may be a place to start.
https://addons.mozilla.org/en-US/firefox/addon/chameleon-ext/

**Comment by karlcow** [comment]
@Darin755 This is part of the webcompat project.

A website is not working on a browser for a **user**, 

1. Trying to reproduce
2. Diagnosing the cause

A couple of causes can happen.

* website error, 
  * browsers team can suggest a fix and do outreach
  * browsers team can do site interventions. see `about:compat` in Firefox or [Quirks](https://github.com/WebKit/WebKit/blob/main/Source/WebCore/page/Quirks.cpp) for Safari, and so on.
* A bug in Gecko, Blink, WebKit, the relevant implementer opens a bug  on the relevant browser bug tracker.


I pushed the webcompat bugs reported by waterfox users to the waterfox repo, because they are not being diagnosed by the waterfox team/community. I have seen you made the decision to close a lot of them. That's a choice but at least they are not stalled.

* People from Chrome/Edge help diagnose issues here for their relevant Blink browsers
* People from Mozilla help diagnose bugs relevant to Firefox

Feel free in the future to suggest a solution for the users who reported this issues. You can track them 
https://github.com/webcompat/web-bugs/issues?q=label%3Abrowser-waterfox+

**Comment by adamp01** [comment]
@karlcow - I appreciate you moving the Waterfox relevant bugs here - we don't have a huge amount of resource so we don't typically monitor webcompat for issues as we get a lot of users reporting things directly here.

The bugs I closed are the one's relating to Waterfox G3 which was based on FF ESR78, as that hasn't been in development since ~September. 

The remaining one's relate directly to Waterfox G4 and I will be looking into fixes for these when I have some time.

Thanks again

**Comment by adamp01** [comment]
Should be resolved in the next release.
