### ISSUE TITLE
[webcompat] mewe.com - Waterfox is unsupported browser

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2649]
### What happened?

URL: https://mewe.com/modern-browser

Browser / Version: Waterfox 91.6.0
Operating System: Windows 10
Tested Another Browser: Yes Chrome

Problem type: Site is not usable
Description: Browser unsupported
Steps to Reproduce:
Since last update I get the following : Your browser is not supported.

We cannot provide a good experience to your browser.
To use this site, please upgrade to the latest version of Chrome, Firefox, Safari, Edge or some other modern browser.

Opened originally on https://github.com/webcompat/web-bugs/issues/99628

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by Darin755** [comment]
I am not sure how this is a bug. If Mewe chooses not to support waterfox there is not much that can be done on the waterfox side of things. With that being said there is a extension called Chameleon which can change the browsers agent string to a different browser. I have not tested it with waterfox but may be a place to start.
https://addons.mozilla.org/en-US/firefox/addon/chameleon-ext/

**Comment by karlcow** [comment]
see https://github.com/WaterfoxCo/Waterfox/issues/2647#issuecomment-1089688113

**Comment by adamp01** [comment]
This will be resolved in the next release.
