### ISSUE TITLE
[webcompat] www.trekbikes.com - The page does not load correctly

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2650]
### What happened?

URL: https://www.trekbikes.com/ca/en_CA/

Browser / Version: Waterfox 78.13.0
Operating System: Windows 10
Tested Another Browser: Yes Chrome

Problem type: Site is not usable
Description: Page not loading correctly
Steps to Reproduce:
Site loading just header tabs and they do no go to anywhere. Have cleared cache and cookies as well disabling add ons, IPV6, DNS still does not load.

Opened originally on https://github.com/webcompat/web-bugs/issues/86974

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Closing as for unsupported Waterfox version.
