### ISSUE TITLE
[webcompat] www.nbc4i.com - Page content is blurred

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2651]
### What happened?

URL: https://www.nbc4i.com/

Browser / Version: Waterfox 91.6.0
Operating System: Windows 10
Tested Another Browser: Yes Chrome

Problem type: Site is not usable
Description: Page not loading correctly
Steps to Reproduce:
Everything is blurred out except for the header.

Opened originally on https://github.com/webcompat/web-bugs/issues/100160

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by ghost** [comment]
everything is OK

**Comment by softvision-oana-arbuzov** [comment]
The issue still occurs. 
![image](https://user-images.githubusercontent.com/12184325/168536166-4a856f6d-9f2c-4475-afda-458b86bbcb1d.png)

**Tested with:**
Browser / Version:  Waterfox G4.1.2 (91.10.0)
Operating System: Windows 10 Pro

@jorg35 please reopen it.
