### ISSUE TITLE
[webcompat] writer.com - Page has CSS loading issues

### ISSUE THREAD

**Issue by karlcow** [MrAlex94/Waterfox#2652]
### What happened?

URL: https://writer.com/grammar-checker/

Browser / Version: Waterfox 78.5.0
Operating System: Windows 10
Tested Another Browser: Yes Chrome

Problem type: Something else
Description: https://writer.com/grammar-checker/ site not opening.
Steps to Reproduce:
https://writer.com/grammar-checker/ site is not loading, so checked in firefox and chrome browsers it's loading.

opened originally on https://github.com/webcompat/web-bugs/issues/68700

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Closing as for unsupported Waterfox version.
