### ISSUE TITLE
Waterfox G4 v4.1.0 (latest) - Open Link in New Tab missing + cookies and auto-signing into sites problems

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2657]
### What happened?

**Open Link in New Tab**  when right-clicking on a link, is now missing  (was ever present until 4.0.8)

![image](https://user-images.githubusercontent.com/89191739/161958730-daafda48-231b-4e71-9ea9-920366329a94.png)

Also, going to websites like  www.theguardian.com  keeps asking to agree for Cookies, and a number of sites, including The Guardian, do not auto-sign in as they used to, I have to keep clicking the LOGIN button on those sites to be logged in.  **This did not happen in 4.0.8.**

O.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
~~Thanks for the report. I can reproduce this issue when choosing a non-default theme on Windows 11. Will try and get a fix out ASAP.~~

Can I just confirm your version of Windows?

Edit #1: @Objectivite It actually looks like I can't reproduce this, I misread the right click context menu. Here's what it looks like on Firefox Dynamic theme, Windows 11 with G4.1.0.

Plain text domain:

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/4728920/161963103-d72249d0-b7ad-426f-bf8a-7cc5cc31a580.png">

Link:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/4728920/161963244-bc60b40f-ab93-4985-bd16-53dfd09bc639.png">

Do you have the same issue on both plain text domains and links? Can you consistently reproduce on a certain web page?

**Comment by Objectivite** [comment]
**Thank You.**

O.

**Comment by MrAlex94** [comment]
> **Thank You.**
> 
> O.

I've made an edit to the reply above.

**Comment by Objectivite** [comment]
Just testing - do not reply to this

https://www.cnn.com

https://github.com/WaterfoxCo/Waterfox/issues/2657

O.

**Comment by Objectivite** [comment]
OK - this is very interesting, and much more specific than I thought originally.

It works normally on a link that is highlighted as a link.

However, when I noticed it I was in the comments section of an article in the Guardian newspaper.  A user had put a link to a page on the Independent and in The Guardian comments page links are not clickable  BUT  if you highlight the whole link and right-click, Waterfox recognises that it is a link and gives you the menu.  In 4.0.8 that menu includes  Open in New Tab,  but it does not in 4.1.0  (I verified that).

So it is a very very specific instance - in all other instances I do get the  "Open in New Tab"  on the right-click.

You can access the Guardian comment in question at this link -

https://www.theguardian.com/commentisfree/2022/apr/06/bucha-ukrainians-russian-military-donbas#comment-155775557


O.

**Comment by MrAlex94** [comment]
It's a very odd one, shows fine for me:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/4728920/162000969-fbd170c4-7c08-410d-bb67-1b981e2152d5.png">

If you open up the [browser console](https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html#:~:text=You%20can%20open%20the%20Browser%20Console%20in%20one,from%20the%20keyboard%3A%20press%20Ctrl%2BShift%2BJ%28or%20Cmd%2BShift%2BJon%20a%20Mac%29.), do you see any error messages that might look relevant? I'd recommend right clicking a few times so any error message stands out.

**Comment by Objectivite** [comment]
Hi Alex,

What a strange one.

I went back to that comment, repeated the process and I had the same problem.  Then, noticing that the top of the popup was right up the top edge of my screen I thought  _"I wonder if it is because I have the comment too far up the page and the popup is not able to fully develop"_.   So I scrolled the page down a little bit to ensure that that Guardian comment was just below halfway, right-clicked and "Hey Presto" I now have the correct popup and  **Open Link in New Tab**  is showing.

Where it gets strange is that I then scrolled the page back up so that Guardian comment is near the top of the page and ..... it still works fine !

Without closing Waterfox I then opened a new tab, searched for that comment again, left it positioned near the top, right-clicked and ..... it still works.

Conclusion :  after all these tests and given how hard it was for me to reproduce after the first instance **I do not think you should waste any more time on this**.  If it happens again I will scroll down a little and it will work.

I am happy for you to close this incident.  I'll monitor the cookies issue (second part of the incident) - if I still have problems I'll open a new case.

O.
