### ISSUE TITLE
Asks To Refresh Waterfox On Clean Install

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2660]
### What happened?

Windows 10 recognizes fresh Waterfox installation as non-fresh and asks to refresh Waterfox.

Should I refresh or just ignore this message?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
If it is just a completely fresh install then running the refresh won't do anything of benefit, so can be ignored. This should only trigger if Waterfox hasn't been used for a significant period of time, however.

For reference, the refresh does things like resetting preferences, clearing cache etc.

**Comment by ghost** [comment]
Hi @adamp01 , I fully uninstalled Waterfox, deleted all Waterfox-named folders and did fresh installation, which was recognized as non-fresh.

Thanks, I will fully ignore the message.
