### ISSUE TITLE
G4.1.0 does not open new tabs + settings in appliction menu does not work

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2663]
### What happened?

Updated today to the latest version of waterfox and as mentioned above i can't open new tabs(which is annoying to say the least...), so not with clicking on + or using ctrl + T.

And also when opening the application menu i can't open settings, but it does open when using about:preferences.

After i discovered this, i reinstalled waterfox again, but the issue is still there.

W10(x64) pro latest build.

This is the 1st time i'm posting on github, so excuse me if my post is not complete enough, but at this moment this is what i can share.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
A faulty build was pushed out for about 10 minutes earlier today - could you try installing this version - https://cdn.waterfox.net/staging/x86_64/Windows_NT/Waterfox%20G4.1.0%20Setup.exe

**Comment by spitxa** [comment]
experienced the same issue as [heethoofd] but in mac intel mac (x64), same version G4.
on the flip side, is there any way to block automatic updates? it's really annoying when bugs like that show up and you have to swallow them. way better to update just in case the new release is really ready and tested.

**Comment by ghost** [comment]
> A faulty build was pushed out for about 10 minutes earlier today - could you try installing this version - https://cdn.waterfox.net/staging/x86_64/Windows_NT/Waterfox%20G4.1.0%20Setup.exe

Tnx, i just installed this version and everything appears to be normal.  Tabs and settings are working as expected :)

**Comment by adamp01** [comment]
@spitxa - There is a version here you can try here: https://cdn.waterfox.net/staging/x86_64/Darwin/Waterfox%20G4.1.0%20Setup.dmg

The version available through the website is also working fine now.

**Comment by adamp01** [comment]
@spitxa - Forgot to mention, you can go into `about:preferences` and declare how you wish updates to be handled: 
<img width="720" alt="image" src="https://user-images.githubusercontent.com/47503375/162391598-c280091a-cab6-4a05-ae44-1391aeb8b7a6.png">

**Comment by spitxa** [comment]
doble thanks, @adamp01 ! with that new version, everything working smooth now, and also for the updating info. thanks a lot.
