### ISSUE TITLE
Waterfox update (4.1.0) doesn't show up in the Help. It shows only 4.0.8 and claim to be updated when I was using latest 4.0.9.

### ISSUE THREAD

**Issue by Warrior69** [MrAlex94/Waterfox#2664]
### What happened?

Waterfox just doesn't update from 4.0.9 to 4.1.0.
I've tried both the .exe files, the update and the brand new installation, but it always come back to 4.0.8 (the old version) and it says i'ts updated too with that one
![Update](https://user-images.githubusercontent.com/21089994/162264495-80e11858-2497-40b9-9598-8128ea1aec70.jpg)
.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
A faulty release went out for about 10 minutes earlier today, could you try installing this version please: https://cdn.waterfox.net/staging/x86_64/Windows_NT/Waterfox%20G4.1.0%20Setup.exe

Also for clarity, there is no G4.0.9. The update is from G4.0.8 to G4.1.0.

**Comment by LeeBinder** [comment]
Same here, WF 4.0.8 macOS:

![Bildschirmfoto 2022-04-11 um 19 27 59](https://user-images.githubusercontent.com/39203497/162796256-91bed622-c3e3-4108-b354-a32f82dea9c6.jpg)

We've had this many times before. As usual, just activate the (in this current case 4.1.0) update in the **default** update channel .. ;)

**Comment by adamp01** [comment]
@LeeBinder - We have actually paused auto-updates temporarily and are going to release 4.1.1 today as auto-update to fix some small issues.

**Comment by LeeBinder** [comment]
@adamp01 great - thank you very much for all the improvements and for being prudent rather than pushing updates 👍

**Comment by adamp01** [comment]
4.1.1 should now be live.

**Comment by LeeBinder** [comment]
![Bildschirmfoto 2022-04-12 um 18 19 46](https://user-images.githubusercontent.com/39203497/163008510-1c521df0-7984-4243-87f7-d4326e3d4ce5.jpg)
👍
