### ISSUE TITLE
Waterfox extremely slow to load new sites

### ISSUE THREAD

**Issue by CompeyDev** [MrAlex94/Waterfox#2667]
### What happened?

Every time I try to visit a website that isn't cached, and has assets, rather than a simple HTML or a redirect, it takes about 2-4 minutes to load, or does not load at all. The second time I visit it however, it loads in a fraction of a second (unless using a private window, because no cache). Attempted restarting, resetting, uninstalling, removing temporary files, whitelisting in firewall and more, still doesn't seem to fix it. 

**Edit**: Now tried clean uninstalling and reinstalling, still doesn't seem to fix it. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by grngxd** [comment]
you also use windows 11 comp 🤦🏽

**Comment by CompeyDev** [comment]
> you also use windows 11 comp 🤦🏽

Could you elaborate? I'm unsure as to what you mean by that.

**Comment by adamp01** [comment]
@CompeyDev - Could you open the browser console (Ctrl+Shift+J) and please run the below command to ensure the browser is compatible with your hardware `Services.sysinfo.getProperty("hasSSE4_1")`. This should return true.

Could you also let us know you Windows version please?

**Comment by CompeyDev** [comment]
Using WaterFox right now, fixed it. Forgot to update this issue, but the error was a DNS issue and somehow only occurred with WaterFox and not other browsers, using Cloudflare's DNS seemed to fix it.
