### ISSUE TITLE
WhatsApp Web (new version) fails with classic -> upgrade to G4.1.0 helps

### ISSUE THREAD

**Issue by AlexanderStohr** [MrAlex94/Waterfox#2668]
### What happened?

when trying to run WhatsApp web version the latest versions just fail in classic Waterfox.
its happening when the screen says its preparing the existing messages - and simply gets stuck with that part.

upgrading to the new stream in version G4.1.0 helped - these service just works there as it should.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@AlexanderStohr  - The issue with Classic revolves around it being based on Firefox ESR56 (from 2016/2017). There are quite a few modern JavaScript features (optional chaining, for example) that are not supported in Classic, and we currently don't have the capacity within the core team to try and integrate these.
