### ISSUE TITLE
Shockwave Flash Plugin has Seemingly Vanished

### ISSUE THREAD

**Issue by KingGamingYT** [MrAlex94/Waterfox#2669]
### What happened?

I don't know if this has been reported before, or if I'm just dumb, but I can't find much of anything online about it. The flash plugin is just seemingly no longer installed in waterfox, despite the fact I have flash installed on my system. I can't view any flash content, it just thinks flash player isn't installed. Was flash functionality just removed in an update and has now been relegated to waterfox classic? Any help would be appreciated.
![image](https://user-images.githubusercontent.com/45918062/162594849-3050d79e-18b3-4db1-99f2-af78469202be.png)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@KingGamingYT - There has not been support for the Flash plugin in G4 due to security concerns. Support was still included in G3 and Classic.

**Comment by gamer191** [comment]
@adamp01 the [G4.0.3 changelog](https://www.waterfox.net/docs/releases/G4.0.3) suggests otherwise, so can I suggest updating it?

**Comment by KingGamingYT** [comment]
> @adamp01 the [G4.0.3 changelog](https://www.waterfox.net/docs/releases/G4.0.3) suggests otherwise, so can I suggest updating it?

If this is true and works right, Does that mean I can update again? I've just been on G3 for months and it has bugged me multiple times to update every time I open the application.

**Comment by gamer191** [comment]
@KingGamingYT No, because G4.0.3 came out last November and it definitely didn't re-enable flash

**Comment by KingGamingYT** [comment]
> @KingGamingYT No, because G4.0.3 came out last November and it definitely didn't re-enable flash

Ah, I couldn’t find a date on Waterfox’s release forums so I just disregarded it. Weird.
