### ISSUE TITLE
Pinned Container Tabs unpin on browser restart

### ISSUE THREAD

**Issue by taciturnaxolotl** [MrAlex94/Waterfox#2672]
### What happened?

I open my browser and expect my tabs to be still pinned but they have come unpinned.
This happens with the google container tabs plugin and when tested with normal container tabs they just disappear.
Firefox no longer has container tabs built in.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Linux

**Comment by adamp01** [comment]
@kcoderhtml - is this with all container tabs excluding Private?

**Comment by taciturnaxolotl** [comment]
Yes any of the container tabs built-in when pinned and the browser closed the tabs are not there any more on start up

**Comment by kcoderhtml** [comment]
Yes any of the container tabs built-in when pinned and the browser closed the tabs are not there anymore on start

**Comment by Painketsu** [comment]
same here, the latest update broke all my container tabs in general..

**Comment by Feranor** [comment]
Also, when you restart Waterfox, container tabs are restored, but they're no longer in any container.

**Comment by GuestJim** [comment]
I'm having the same behavior as Feranor mentions. When restarting Waterfox none of the tabs that had been in containers are anymore. It isn't too terrible as I have it set to automatically open them in the appropriate container when I load them, but this is still annoying.

**Comment by KSZYH00** [comment]
I have same issue as users above, pinned tabs are still here after restart, but with no 'context'. 
You can right-click and open pages in new tab with context, close tabs without context and pin again right ones, but this is super annoying doing it every browser start. (Especially having at least 10~15 pinned tabs with different modes)

**Comment by adamp01** [comment]
We are going to push out 4.1.2 soon to resolve this issue.
