### ISSUE TITLE
Multi-account Containers resetted after restart

### ISSUE THREAD

**Issue by ezellohar** [MrAlex94/Waterfox#2682]
### What happened?

After updating to 4.1.1 the containers information is not stored upon closing the browser. When I restart, it opens all tabs without a container, when before each tab was restored in the correct container. I've tested on latest Firefox ESR, and it works as I expect, i.e. all tabs are restored with the correct container.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Thanks, this issue has been raised a lot and I have just PR'd a fix that will come out as G4.1.2 soon.
