### ISSUE TITLE
Downloading problem

### ISSUE THREAD

**Issue by VasudeoSinha** [MrAlex94/Waterfox#2710]
### What happened?

**This is a very important problem** or a bug which needs to be fixed.The Downloads are failing as you can see in the following image

![Screenshot 2022-05-26 145111](https://user-images.githubusercontent.com/90196804/170459141-db62d844-b2ea-42ba-9677-9a2023357dad.jpg)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Hi,

Do you have any public links so we can test?

**Comment by VasudeoSinha** [comment]
I don't know how to make public links but you can guide me for that
And thank you for responding

**Comment by VasudeoSinha** [comment]
My problem has been fixed in the new release. Thanks
