### ISSUE TITLE
Checksums for latest Waterfox Release

### ISSUE THREAD

**Issue by gamesharkmike** [MrAlex94/Waterfox#2713]
### What happened?

https://www.waterfox.net/download/

```
It is essential that you verify the integrity of the downloaded files using the SHA signatures. Most operating systems support the `shasum` command. Download the accompanying .SHA512 file and check the contents of its file using cat. Compare that value to the output of shasum.
cat $DOWNLOADED_FILE.SHA512
# Output of cat command here.

shasum -a 512 $DOWNLOADED_FILE
# Output of shasum command here.

# If the output of both commands is the same, the file is likely to be safe.
```

Where can I get the checksums for the lastest waterfox release?

https://github.com/WaterfoxCo/Waterfox/releases/tag/G4.1.2.1
I see no checksums files :(

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
N/A
```

**Comment by catxeger** [comment]
I'm seeing the same issue for macos.

**Comment by adamp01** [comment]
We are looking into getting checksums displayed somewhere for users. Will get back to you on this.

**Comment by gamesharkmike** [comment]
Thank you.

I compared the latest version at the time of download to search result of the hash https://www.download3k.com/Install-Waterfox.html I wouldn't download WaterFox from there when I can DL from the offical sources, but the checksum was helpful.

Also, you can use the -c argument on the checksums files and it will autmatically calculate and compare the signature (good word, I was explaining hashing to someone not tech-savy and used the term  compare the calculated "MD5 number" but its hexadecial so there are letters A-F included also and used the term value instead), given the checksum files are formatted correctly (it's picky, even though the format and spacing is correct and it errors over the format, I think it's the endline character parsing).

EDIT: Newer shasum commands aren't as picky, however using the dos2unix command (available in Git Bash, WSL, Cygwin,etc) the encoding can be converted for use with older versions (ex the one included with the version of Git Bash I have installed).

In Python, "string".encode(), open file as "wb" and write the encoded byte string.

**Comment by MrAlex94** [comment]
With the latest version of the website, hopefully it does what you'd hope :-)

https://www.waterfox.net/en-US/download/
