### ISSUE TITLE
Some videos don't play on Instragam

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [MrAlex94/Waterfox#2715]
### What happened?

**Steps to reproduce:**
1. Navigate to: https://www.instagram.com/p/Ced9X1Yocci/
2. Attempt to play the video.
3. Observe the result.

**Expected Behavior:**
The video plays.

**Actual Behavior:**
The vidoe does not play.

**Tested with:**
Browser / Version: Waterfox Release G4.1.2.1 (64-bit) (91.10.0)
Operating System: Windows 10 Pro

**Note:**
1. The issue is not reproducible on Firefox and Chrome.
2. The issue is not reproducible on all videos on Instagram on Waterfox (e.g https://www.instagram.com/p/Ced2dQIKSAX/)
3. The issue is still reproducible on Waterfox even if I disable Enhance Tracking Protection.
4. This was previously reported here: https://github.com/webcompat/web-bugs/issues/105477, https://github.com/webcompat/web-bugs/issues/105480
5. Gif attached.
![VideoDoesNotPlay](https://user-images.githubusercontent.com/12184325/172559642-13b6e3f7-0958-4cc8-80e4-2b88ae49e9c1.gif)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
ErrorUtils caught an error:

oz_player_error - name: TypeError message: ReadableStreamDefaultController can only be constructed with a ReadableStream instance

Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs. GyaOhXSa8tR.js:56:563
    errorListener https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:56
    reportNormalizedError https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:56
    reportError https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:56
    k https://static.cdninstagram.com/rsrc.php/v3iA_i4/ys/l/en_US/VQuWA3W-iTR.js?_nc_x=Ij3Wp8lg5Kz:899
    f https://static.cdninstagram.com/rsrc.php/v3iA_i4/ys/l/en_US/VQuWA3W-iTR.js?_nc_x=Ij3Wp8lg5Kz:2080
    emit https://static.cdninstagram.com/rsrc.php/v3iSmz4/yC/l/en_US/lShZgKdO2s3.js?_nc_x=Ij3Wp8lg5Kz:40
    emit https://static.cdninstagram.com/rsrc.php/v3iSmz4/yC/l/en_US/lShZgKdO2s3.js?_nc_x=Ij3Wp8lg5Kz:40
    emitError https://static.cdninstagram.com/rsrc.php/v3iSmz4/yC/l/en_US/lShZgKdO2s3.js?_nc_x=Ij3Wp8lg5Kz:44
    load https://static.cdninstagram.com/rsrc.php/v3iSmz4/yC/l/en_US/lShZgKdO2s3.js?_nc_x=Ij3Wp8lg5Kz:187
    f https://static.cdninstagram.com/rsrc.php/v3iA_i4/ys/l/en_US/VQuWA3W-iTR.js?_nc_x=Ij3Wp8lg5Kz:2080
    a https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:220
    m https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:147
    q https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:147
    applyWithGuard https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:56
    c https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:56
    e https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:143
    r https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:143
    onmessage https://static.cdninstagram.com/rsrc.php/v3/yK/r/GyaOhXSa8tR.js?_nc_x=Ij3Wp8lg5Kz:143
```

**Comment by Squall-Leonhart** [comment]
Video plays fine, 

Using windows build from https://github.com/WaterfoxCo/Waterfox-Classic/actions/runs/2424783626

**Comment by NoNameNeeded2** [comment]
Video plays just fine for me.

**Comment by softvision-oana-arbuzov** [comment]
It seems to be working now for me too. I've checked with multiple videos and did not encounter the issue anymore. 
It might have been a temporary issue. 

**Tested with:**
Browser / Version: Waterfox Release G4.1.2.1 (64-bit) (91.10.0)
Operating System: Windows 10 Pro

I'll will close it.
