### ISSUE TITLE
Close/Minimise/Maximise buttons in the wrong position where the titlebar is hidden and the tab bar is under the address bar.

### ISSUE THREAD

**Issue by c-massie** [MrAlex94/Waterfox#2716]
### What happened?

[Screenshot.](https://i.imgur.com/9cQovXx.png)

Where the titlebar is hidden and the tab bar is under the address bar, the close, minimise, and maximise buttons are on the left of the tab bar, rather than on the left of the toolbar as expected.

Where the titlebar is shown, [these buttons appear in the correct position.](https://i.imgur.com/4YEiDtH.png)

This is in Mac OS 10.13. (High Sierra) I've not checked in Windows or Linux.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

macOS

### Relevant log output

```shell
N/A
```

**Comment by c-massie** [comment]
I've checked, and the same happens in Windows 10 and Pop OS Linux.

https://i.imgur.com/6ZZqCZV.png
https://i.imgur.com/46SCjpC.png

**Comment by adamp01** [comment]
This is currently by design. Will use this bug to track the feature request: #2732

**Comment by c-massie** [comment]
> This is currently by design. Will use this bug to track the feature request: #2732

The linked issue no longer exists.
