### ISSUE TITLE
Invalid protocols in waterfox docs website

### ISSUE THREAD

**Issue by noahdotpy** [MrAlex94/Waterfox#2720]
### A bug happened!
Some links [here](https://www.waterfox.net/docs/policies/privacy/#firefox-accounts) use invalid protocols like `ttps://`. There is also one that uses `http://` instead of `https://`.

### Examples pulled from the doc page:
[ttps://www.mozilla.org/privacy/firefox-monitor](ttps://www.mozilla.org/privacy/firefox-monitor)
[ttps://www.mozilla.org/privacy/firefox/#sync](ttps://www.mozilla.org/privacy/firefox/#sync)
[http://send.firefox.com/legal](http://send.firefox.com/legal)

### Reproducible?

- [x] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux, macOS, Windows

**Comment by adamp01** [comment]
I'll take a look at this and get it updated. Thanks for raising.

**Comment by adamp01** [comment]
Should now be resolved.
