### ISSUE TITLE
XPCOMGlueLoad error for file /opt/waterfox-g4/libxul.so: /usr/lib/libdbus-glib-1.so.2: file too short Couldn't load XPCOM.

### ISSUE THREAD

**Issue by Maritsu** [MrAlex94/Waterfox#2724]
### What happened?

Can't launch Waterfox, getting this error message:
`XPCOMGlueLoad error for file /opt/waterfox-g4/libxul.so:
/usr/lib/libdbus-glib-1.so.2: file too short
Couldn't load XPCOM.`

Issue also persists on Firefox.
Waterfox installed via the AUR (`yay -S waterfox-g4-bin`), Firefox installed via `pacman -S firefox`.

### Reproducible?

- [x] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Linux

**Comment by adamp01** [comment]
If the problem exists with Firefox as well, we won't have the capacity to look into this. We will be releasing a version of the browser based off of ESR102 around September which may change things.

**Comment by Maritsu** [comment]
Found the issue: `libdbus-glib` wasn't installed.
