### ISSUE TITLE
G4.1.3 Killed TabMixPlus

### ISSUE THREAD

**Issue by thunderstone135** [MrAlex94/Waterfox#2725]
### What happened?

After installing the G4.1.3, TabMixPlus got Disabled. I tried updating/reinstalling it, but I only receive the error:
```
This addon could not be installed because it appears to be corrupt.
```
I didn't have this problem on G4.1.2.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
N/A
```

**Comment by onemen** [comment]
I see this error in the console

```
TypeError: "freeze" is read-only[BootstrapLoader.jsm:79:1](resource:///modules/BootstrapLoader.jsm)
```

**Comment by MrAlex94** [comment]
Thanks for raising this. Will have a look at what has changed.

**Comment by adamp01** [comment]
Could I confirm you are using https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.8/tab_mix_plus-dev-build.xpi?

**Comment by thunderstone135** [comment]
> Could I confirm you are using https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.8/tab_mix_plus-dev-build.xpi?

Yes, I have that version installed 👍 
Although it's only working on G4.1.2 ATM 😿

**Comment by onemen** [comment]
It looks to me that you can remove this lines
https://github.com/WaterfoxCo/Waterfox/blob/e0db25c490374bea3ab9b6d2c5a3e35bd3da0f6b/browser/components/extensions/common/BootstrapLoader.jsm#L77-L90

this code is useless since `OPTIONS_TYPE_DIALOG` is set to 1 in the source code of AddonManager.jsm

**Comment by thunderstone135** [comment]
@onemen it worked 🎉 

Now I just have to wait for the Waterfox Team to implement the same changes 😸

**Comment by adamp01** [comment]
Thanks @onemen - I'll push this now and get a new build out in the next few hours.

**Comment by thunderstone135** [comment]
Problem solved 👍
