### ISSUE TITLE
Waterfox doen't find available updates (on M1 Mac).

### ISSUE THREAD

**Issue by aschroeder27** [MrAlex94/Waterfox#2730]
### What happened?

Waterfox doesn't recognize available updates and keeps saying "Waterfox is up to date".
It happened in version 4.0.1 (while 4.1.1 was available) and now again (4.1.1 -> 4.3.1).
I could manually install the update, all settings were kept.

Problem occurred on my M1 Mac, update works fine on my Intel Mac.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

macOS

**Comment by adamp01** [comment]
@aschroeder27 - Thanks for raising, we are aware of the issue and are working to get things resolved ASAP. It's related to an error in moving files during the release process.

**Comment by adamp01** [comment]
Should now be resolved.
