### ISSUE TITLE
G4.1.3 release page links to non-existant mfsa2022-25

### ISSUE THREAD

**Issue by Jypers** [MrAlex94/Waterfox#2731]
### What happened?

I installed the latest version of Waterfox, which brought up the release page on first run.  The release page links to a non-existant mfsa2022-25 as of June 24 2022 7:20AM CST.  Looks like a previous release for G4.1.3.1 does the same.

https://www.waterfox.net/docs/releases/G4.1.3

Link in above page directs to here:
https://www.mozilla.org/en-US/security/advisories/mfsa2022-25/

Same for this release page:
https://www.waterfox.net/docs/releases/G4.1.3.1

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Linux

**Comment by adamp01** [comment]
Thanks @Jypers - I'll get this updated to the correct advisory URL.

**Comment by Jypers** [comment]
Thanks @adamp01
