### ISSUE TITLE
Selecting the page scrolling power with the spacebar, PgUp & PgDn keys

### ISSUE THREAD

**Issue by koplenov** [MrAlex94/Waterfox#2733]
Spacebar, PgUp & PgDn do not scroll to the full page, but to half of it

I use a laptop without a mouse and often use the keyboard to navigate the page.

Now when I press Spacebar, PgUp or PgDn, the page scrolls completely.

This is often not convenient because you lose context, rather than scrolling would be smoother.

I propose to put in the settings how much the page will scroll when these keys are pressed (per page, half a page, a third of a page)

What do you think about that?

**Comment by MrAlex94** [comment]
Since this is inherited from Firefox, I'd recommend using this extension to get it how you'd like:

https://addons.mozilla.org/en-GB/firefox/addon/saka-key/

Seems to do what you'd like :-)
