### ISSUE TITLE
How to install Pocket extension?

### ISSUE THREAD

**Issue by ZedZipDev** [MrAlex94/Waterfox#2734]
### What happened?

A bug happened!

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Is it possible to install extensions in WF? 
For example, how to add Pocket which works in Chrome, FF etc?
```

**Comment by adamp01** [comment]
You can install any extension that is available on the Firefox web store (and compatible with ESR91): https://addons.mozilla.org/en-GB/firefox/
