### ISSUE TITLE
Building error Missing Mozilla API key

### ISSUE THREAD

**Issue by q64ceo** [MrAlex94/Waterfox#2735]
### What happened?

git clone into Waterfox here on Github

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
0:03.49 checking for the Mozilla API key... no
 0:03.49 ERROR: 
/Waterfox/mozilla-api': No such file or directory
```

**Comment by adamp01** [comment]
You can just remove this line: https://github.com/WaterfoxCo/Waterfox/blob/current/.mozconfig-x86_64-pc-linux-gnu#L44
