### ISSUE TITLE
Problem with accessiblehandler.dll COM registration

### ISSUE THREAD

**Issue by Malaach** [MrAlex94/Waterfox#2737]
### What happened?

WebAutoType Plugin for Keepass is not working with Waterfox anymore. I discussed the issue with the developer and he pointed me to accessiblehandler.dll as the culprit. I got this as advice:

"They've screwed something up with their accessibility handler COM registration. I'm not sure what, exactly, but if you unregister it by running, in an elevated command prompt:

regsvr32 -u "c:\program files\waterfox\accessiblehandler.dll"

That will work around the issue. Of course if you've installed Waterfox somewhere else, substitute the actual path to wherever you've installed it."

The workaround actually works so I have no doubt concerning his analysis. Problem was observed also some time ago with the 3.x branch and went away after a Waterfox update.

Ticket on Sourceforge: https://sourceforge.net/p/webautotype/tickets/28/

This does not happen with Firefox - tested with FF 101.0.1 x64.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@Malaach - We are going to be migrating the browser to ESR102 by the end of September so won't be able to tackle this in G4. Hopefully the move to ESR102 base will resolve this, but if not we can take a look once G5 is out.

It would be useful to know if the latest ESR91 Firefox also displays the same erroneous behaviour you are describing.

**Comment by Malaach** [comment]
> It would be useful to know if the latest ESR91 Firefox also displays the same erroneous behaviour you are describing.

Just tested with Firefox ESR 91.11.0esr x64 (from portableapps.com) which does NOT show the described behaviour. Hope that helps.

**Comment by Malaach** [comment]
>  so won't be able to tackle this in G4.

@adamp01 Now that's interesting - the problem is gone with the latest update to 4.1.3.2.

**Comment by adamp01** [comment]
Very strange - but I guess good that it is resolved for you. I'll close this for now but let me know if the same happens again, especially in the first version of G5.
