### ISSUE TITLE
Integrate password autofill on macOS

### ISSUE THREAD

**Issue by gagarine** [MrAlex94/Waterfox#2738]
MacOS provide now a mechanism for password managers to securely provide passwords to browsers (and any other application). It would be great for Waterfox to use it, instead of having to rely on each password manager having to implement their own extension and xpc channel.

The bug on Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1650212 

An example of password manager that integrate with Apple autofill is strongbox: https://strongboxsafe.com/updates/macos-big-sur-autofill/ 

This is how it looks:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/164074/177001407-3953f5da-fd52-48df-9d22-baaa737cd97b.png">

I doubt Mozilla will implement this feature. They seem to want to create a lock-in by forcing user to use their (poor) password manager. As side note: interestingly, Firefox on iOS can be used as a password provider, but not on macOS. This defeat the use of Firefox as a password manager on MacOS.

**Comment by MrAlex94** [comment]
This is a feature I would love to see as well, since I use macOS quite heavily. 
Unfortunately we'll have to wait for Mozilla on this, but it _does_ look like there's movement on it, albeit slow.
