### ISSUE TITLE
Property "pixelated" for image-rendering not recognized

### ISSUE THREAD

**Issue by DigiEggz** [MrAlex94/Waterfox#2739]
### What happened?

At some point the support for the [pixelated](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering) property for `image-rendering` was broken and no longer is recognized as a valid property.

Note: This problem was fixed in the main version of Firefox, but the ESR version still has the same issue.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=856337, Mozilla were just slow on the uptake to get this into Firefox. 

This will be resolved when we move to ESR102 which should be latest end of September.

**Comment by DigiEggz** [comment]
Alright, cool! Is it okay if I close this issue or should I leave it open until then?
