### ISSUE TITLE
Currently selected tab's background color is near-same as other tabs in dark theme mode

### ISSUE THREAD

**Issue by atErik** [MrAlex94/Waterfox#2740]
### What happened?

Hi Watefox devs. Thanks for this great project. Waterfox indeed consumes less resources.

Dark theme mode is very important to reduce (electrical) energy usage by computer/device,
and increases device component's life.
and also helpful for human eyes (when proper/suitable size fonts are used).

BUG / PROBLEM:
in Dark theme mode, in Watefox, in tab bar, the currently selected/used (active) Tab's background color is same or near-(very)-same as other tabs !!
so its (very) hard to figure out which exact tab i'm using.

in dark mode, currently selected tab, need to have a slightly different color than other tabs.

i'm using your Waterfox version G.4.1.3.1 , in macOS Catalina 10.15.7.

Thanks in advance.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

macOS

**Comment by adamp01** [comment]
Thanks for raising this issue.

The default theme for Waterfox is https://github.com/black7375/Firefox-UI-Fix, which does indeed have a different colour for active vs inactive tab (actually very similar to colour scheme of dark mode GitHub).

![image](https://user-images.githubusercontent.com/47503375/177558730-047d2018-3799-42ab-9b75-3906582978fb.png)

Unfortunately, we will not be making any changes here.
