### ISSUE TITLE
Watefox (derivative of Firefox) Data PRIVACY issue: Credit-Card,Address Data is Stored Without Asking !!

### ISSUE THREAD

**Issue by atErik** [MrAlex94/Waterfox#2741]
### What happened?

Hi Watefox devs,

as far as i understand, Waterfox is derivative of Mozilla Firefox.

BUGS / PROBLEMS :

(1) Waterfox (and firefox) does not show the Disable/Enable option to disable the auto storage of Credit-Card & Address form filling data, when Waterfox (or Firefox) starts for first time !!

(2) and when waterfox/firefox is restarted or runs for 2ND TIME,
then the Enable/Disable option appears for the CREDIT/DEBIT CARD number & (Billing) ADDRESS,
but the the data storage option is by default ON !! !! !! !! !! !! !!
So it is violating user's privacy rights,
and it also applied nuisance trickery(s) , by showing it only in the 2nd restart !! !! !! !! !! !!.

As waterfox/firefox has not asked me about those default mode of (confidential & private) data-collection operation(s), that it would AUTOMATICALLY begin to store confidential & private data, such as: Credit/Debit etc CARD or (billing/etc) ADDRESS info (that are entered/filled-up into a website's webpage form/textbox),
So waterfox+firefox is violating Privacy rights, CCPA laws, GDPR laws, UN's UDHR, etc, etc !!

SUGGESTED SOLUTION :
(1) Please show the CREDIT CARD & ADDRESS related AUTO DATA STORAGE/COLLECTION option, on the FIRST TIME, when waterfox/firefox starts,
and please keep it in DISABLE (unselected) state/mode,
then that will be "Respecting Privacy Rights" (by default).
Users who need to store Credit-Card & Billing Address, etc in Waterfox/Firefox, can Enable it by themselves by selecting the option.

Why waterfox/firefox by-default disrespecting very sensitive & confidential info/data privacy/protection & privacy-rights ? !!
Who created such nuisances & kept it in forefox for such long time,
and why mozila still keep on saying Firefox respects Privacy Rights, while their prodict are by-default set to violate privacy rights ?!

Please solve these big bugs, if possible.
please report to mozilla firefox bugzilla site if necessary.

Thanks in advance to consider to solve it, and if you solve it or if you assist in solving it.

by the way, i'm using Waterfox G4.1.3.1, in macOS catalina 10.15.7

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

macOS

**Comment by MrAlex94** [comment]
Hi,

Please report this directly to Mozilla, as it's something that's inherited from the platform.
