### ISSUE TITLE
userChrome not functioning as intended/expected 

### ISSUE THREAD

**Issue by Jhooda999** [MrAlex94/Waterfox#2743]
### What happened?

When I switched from FF to WF I brought my userChrome with me and it was functioning just fine. Two days ago I briefly turned off my Sidebery extension in an attempt to stream something more clearly but it ended up not working as I hoped. When I re-enabled it, the effect it had on Sidebery was not functioning as intended. 

userChrome pastebin: https://pastebin.com/XD0rM8gi

Intended effect (works on Firefox): Sidebar collapses to a small sliver on the left hand side of the screen. Mousing over it expands it to a large degree for access, mousing away collapses it again. 

Current effect: Sidebery doesn't collapse or expand. It stays on the left hand side about two thirds of the size of where it should expand to. However, it treats the screen as if it's still expanding/collapsing - it covers up part of the page I am currently on like it would when expanded, but it doesn't collapse to reveal it again. I also can't get the Sidebery settings button to show up which I think is related as I feel like it's trying to place it where it would be if it was working but because it doesn't expand that far it doesn't show it. 

This exact same userChrome is still functioning as intended on Firefox and it previously functioned as intended with Waterfox. I don't know what is preventing it from working now. 

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
👋 In G5, you can now explicitly turn off Waterfox customisation options:

You can turn this off by typing `about:config` in the address bar, search for `userChrome.theme.enable` and toggle it to `false`.

All your custom CSS/JS should now run as expected on G5 (although it must be updated to support Firefox ESR102!).
