### ISSUE TITLE
Infinite loading issue on 8.1

### ISSUE THREAD

**Issue by MoJo4000** [MrAlex94/Waterfox#2746]
### What happened?

On 8.1 Pro (N) clicking continue after entering my email address starts an infinite loading wheel of doom. I installed Firefox and it works on there, Synching is also working on my Win: 11 desktop although I haven't tried logging out and logging back in again.

### Reproducible?

- [Not reproducible ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Sorry about that! The issue was resolved in an earlier G4 release. (Assuming this regarding Sync in the browser).
