### ISSUE TITLE
[Question] What classic plugins are still supported in the current version of Waterfox?

### ISSUE THREAD

**Issue by Videogamer555** [MrAlex94/Waterfox#2748]
This isn't either a feature request or bug report. It's a question. I would like to know about exactly what plugins aren't supported in Waterfox Current, compared to Waterfox Classic.

Is Flash still supported in Waterfox Current?
Is Java still supported in Waterfox Current?
Or will I need Waterfox Classic for at least one of those plugins?

**Comment by MrAlex94** [comment]
Hi! You'll need to use Waterfox Classic for both of those now.

**Comment by Videogamer555** [comment]
Then I hope you don't plan to stop providing Waterfox Classic.
