### ISSUE TITLE
Account in China cannot be logged in

### ISSUE THREAD

**Issue by lyh061619** [MrAlex94/Waterfox#2750]
### What happened?

Click login synchronization to jump to the following connection

https://accounts.firefox.com/?context=fx_desktop_v3&entrypoint=fxa_app_menu&action=email&service=sync

It always shows that it is in process, and the login is unsuccessful

This problem can be logged in using Firefox 102

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by lyh061619** [comment]
I use the version of waterfox g4.1.3.1, and I have been unable to log in after I quit my account. This problem has plagued me for several days

**Comment by kamil445** [comment]
here u have fix for this https://github.com/WaterfoxCo/Waterfox/issues/2718

`open about:config add "https://accounts.firefox.com/" to "webchannel.allowObject.urlWhitelist" config option, then setup sync anagin`

For me worked

**Comment by lyh061619** [comment]
> here u have fix for this #2718
> 
> `open about:config add "https://accounts.firefox.com/" to "webchannel.allowObject.urlWhitelist" config option, then setup sync anagin`
> 
> For me worked

Thank you for your reply. I'll test it carefully

**Comment by lyh061619** [comment]
here u have fix for this https://github.com/WaterfoxCo/Waterfox/issues/2718 Problem solved, solution
Steps:
open about:config
add "https://accounts.firefox.com/" to "webchannel.allowObject.urlWhitelist" config option
setup sync
