### ISSUE TITLE
How do we track which ESR build is being used from Waterfox 4.1.3.2 onward ?

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2751]
### What happened?

Hello,

This is more of a question than a bug.

Now that you have removed "Waterfox"  from the  USER AGENT  field, there is no obvious way in  **"More Troubleshooting Information"**  to find out which Firefox ESR build Waterfox is using.

So, question - is this what we should be using in future to determine which ESR build Waterfox is using ?

![image](https://user-images.githubusercontent.com/89191739/178760353-bce645e3-6608-4c7b-a603-9f9eb0acd80d.png)

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Hi @Objectivite,

You could use `extensions.lastAppVersion` as that is calling `Services.appinfo.version`, which you could also enter into the browser console (cmd + shift + j).

Alternatively, currently each ESR change will result in a Waterfox "generation" change. So when we release the new ESR102 base Waterfox in ~September time it will be G5.

**Comment by Objectivite** [comment]
Thanks Adam for confirming and providing additional details.

O.
