### ISSUE TITLE
SEC_ERROR_UNKNOWN_ISSUER with Adguard

### ISSUE THREAD

**Issue by XedIZ** [MrAlex94/Waterfox#2755]
### What happened?

A bug happened!

Can't browse anything even with google or other trusted website because of this SEC_ERROR_UNKNOWN_ISSUER with adguard installed and running in your desktop. I tried it with firefox but all is working there. only here in waterfox that the problem occurs. please fix this. (I have latest Adguard, 7.10.1)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
SEC_ERROR_UNKNOWN_ISSUER
```

**Comment by adamp01** [comment]
Hi,

Seems like this is known to AdGuard and this should help you resolve: https://kb.adguard.com/en/windows/solving-problems/connection-not-trusted

Thanks,
