### ISSUE TITLE
Website footer logo redirects to the wrong url

### ISSUE THREAD

**Issue by redystum** [MrAlex94/Waterfox#2758]
### What happened?

The logo in the footer of the website is redirecting to the following url:
`https://www.www.waterfox.net/`

with the following html code:
```html
<a href="https://www.www.waterfox.net/" target="_blank" rel="noopener noreferrer" class="footerLogoLink_tutC"><img src="/img/logo.svg" alt="Waterfox" class="themedImage_BQGR themedImage--light_HAxW footer__logo"></a>
```
What was supposed to happen was redirect to the site itself.
Proposed resolution:
```html
<a href="https://www.waterfox.net/" target="_blank" rel="noopener noreferrer" class="footerLogoLink_tutC"><img src="/img/logo.svg" alt="Waterfox" class="themedImage_BQGR themedImage--light_HAxW footer__logo"></a>
```
(remove the duplicated www)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Linux, macOS, Windows

**Comment by adamp01** [comment]
@redystum - thanks for raising this - I'll get this rectified.
