### ISSUE TITLE
Waterfox 4.1.3 not launching on Fedora 36 KDE Plasma

### ISSUE THREAD

**Issue by jimb417** [MrAlex94/Waterfox#2762]
### What happened?

Returns error: "Illegal instruction" when executing: ./Downloads/waterfox/waterfox from the terminal

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Hi,

It sounds like your CPU doesn't support the required instruction set.

For G4, that was SSE4.2.
For G5, it has been lowered to SSSE3.
