### ISSUE TITLE
Bring back AI SSE3 support!

### ISSUE THREAD

**Issue by Purging5470** [MrAlex94/Waterfox#2770]
### What happened?

Dear developers! Return support for previous versions of AI SSE, namely SSE3 and older. Not all processors of your fans support SSE4.2. The same newest version of Firefox supports older versions of SSE. And any other popular browser supports older versions. How is it that your browser has the highest requirements in terms of computer configuration, but at the same time consumes the least resources among competitors? Is the point of these efforts to reduce the consumption of PC resources? Without SSE4.2 support, the browser does not start.
This is the only reason I switched back to the original Firefox. Treat this with understanding! Thank you for your attention!

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Due to to better understanding of how the optimisation (`-march` and `-mtune` in combo) flags work, [SSSE3](https://en.wikipedia.org/wiki/SSSE3#CPUs_with_SSSE3) is now the minimum requirement. This will go live when G5 gets released.
