### ISSUE TITLE
"Waterfox VPN" option in Incognito Mode

### ISSUE THREAD

**Issue by allanfherrera** [MrAlex94/Waterfox#2771]
### What happened?

While opening an Incognito Tab, in the bottom of the site, appears a **_"Waterfox VPN"_** link, which is just a Mozilla VPN ad, it ´s a bug because is an unwanted remaining of Firefox branding.

![VPN](https://user-images.githubusercontent.com/92060219/183927918-18ddfa27-4d98-4229-bc0c-127a8ba3e6aa.PNG)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@allanfherrera - thanks, we will make sure this is removed in G5.

**Comment by MrAlex94** [comment]
From testing, this does not appear to be there anymore.
