### ISSUE TITLE
Precompiled version of G5.0b1

### ISSUE THREAD

**Issue by the-r3dacted** [MrAlex94/Waterfox#2775]
**Is your feature request related to a problem? Please describe.**
I dunno how to compile Waterfox, and even if I did, there would be no automatic updates, and I could end up breaking something compiling it wrong.

**Describe the solution you'd like**
Precompiled version of G5.0b1

**Comment by wbak1102** [comment]
This is abnormal. As always, Alex is failing.?

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/releases/tag/G5.0b1
