### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by EmmanuelMess** [MrAlex94/Waterfox#2779]
### What happened?

No languages available in dropdown: 
"Waterfox can’t update your languages right now. Check that you are connected to the internet or try again."

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Linux

![image](https://user-images.githubusercontent.com/10991116/185178796-142d49e0-792e-456f-a323-d77e01a21f06.png)

**Comment by wbak1102** [comment]
And something is missing again. You can't do it.

**Comment by ghost** [comment]
Continuous problems.

**Comment by MrAlex94** [comment]
This is now merged and will be live in G5 Beta 2. The structure of l10n changed once again which caused some issues. But once the update comes out, you should be able to use the previously available languages, including any localised Waterfox specific strings :-)
