### ISSUE TITLE
G5.0b2 Bookmarks Manager

### ISSUE THREAD

**Issue by thunderstone135** [MrAlex94/Waterfox#2783]
### What happened?

Hi, I just want to report about the left side panel of the Bookmarks Manager instantly scrolling down to the bottom when I open it. I was able to reproduce this behavior both on an existing and fresh profile. In G4, no scrolling happens when I open the Bookmarks Manager. I'm not sure if this is intentional or just a bug, but I'm just used to opening the Bookmarks Manager without any instant scrolling. As far as I know, it has been that way even before Firefox changed its name from Phoenix.

![Imgur](https://imgur.com/f1s7q2C.png)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5 Beta

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
N/A
```

**Comment by thunderstone135** [comment]
**Update:**

Still happening with G5.0b2.

**P.S.** Modified title from b1 to b2.

**Comment by MrAlex94** [comment]
I can't say I can reproduce this:


https://user-images.githubusercontent.com/4728920/189077240-cc123e6f-2048-45b7-8c80-befb95f90c60.mov


https://user-images.githubusercontent.com/4728920/189080409-676ede04-8fe0-41ee-915c-89e3d7d13a73.mov

Frustrating it's happening to you - not sure what I can recommend here.

**Comment by thunderstone135** [comment]
@MrAlex94:
I noticed that your Bookmark Folders are in the **_All Bookmarks_** > **_Other Bookmarks_**.
Try putting all those folders in **_All Bookmarks_** > **_Bookmarks Menu_**.
Just drag the folders or cut/copy paste them to the **_Bookmarks Menu_**.

**Comment by thunderstone135** [comment]
**Update:**

Here's a video with more details 👇 

https://user-images.githubusercontent.com/96173732/189116837-5027121d-4c8b-4f96-80d0-c0c1627df939.mp4

**P.S.** The reason I use **_Bookmarks Menu_** instead of **_Other Bookmarks_** is for easy access in the Nav Bar as shown in the video.

**Comment by MrAlex94** [comment]
Ah yes I see.

On Firefox Develop Edition 105.0b8 this also happens. I think it may now be default behaviour?

https://user-images.githubusercontent.com/4728920/189152920-ad5893c9-c8ef-44bf-ac14-5a5c52e31c94.mov

**Comment by thunderstone135** [comment]
Is there a way to bring the old behavior back (where it doesn't scroll down automatically)?

**Comment by MrAlex94** [comment]
Not that I can see - spent a while to see which bug ID introduced this, found some related ones but not 100% sure if they're the ones related to. 

Maybe submit this to Mozilla - may not have been a deliberate change.

**Comment by thunderstone135** [comment]
I followed your advise and posted an **[issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1790173)** in Bugzilla.
Hopefully, this gets resolved within the 102 ESR timeline.
