### ISSUE TITLE
Google Search Suggestions missing in G5

### ISSUE THREAD

**Issue by newsjunkie247** [MrAlex94/Waterfox#2784]
### What happened?

Google search suggestions seem to be missing in G5 Beta. I'm using the Windows version. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5 Beta

### What platform are you seeing the problem on?

Windows

**Comment by ghost** [comment]
Continuous problems with G4 and G5.

**Comment by MrAlex94** [comment]
Fix in https://github.com/WaterfoxCo/Waterfox/commit/ad54959833991b2be52e536365edab1b34ce9565

> Continuous problems with G4 and G5.

This was fixed in [G4.0.5.1](https://github.com/WaterfoxCo/Waterfox/releases/tag/G4.0.5.1).
