### ISSUE TITLE
G5.0b1 add a option for choose theme pref. on fingerprint

### ISSUE THREAD

**Issue by Fenghuang19** [MrAlex94/Waterfox#2785]
**Is your feature request related to a problem? Please describe.**
Unlike the G4 version, which always send a light theme preference into the browser fingerprint, the G5b1 set it according to the browser theme. In my case it's a issue (I looking for a dark waterfox UI while asking the website to be displayed on a light theme).

**Describe the solution you'd like**
It will be great to get a extra option under website appearance for choose which theme preference is send on the fingerprint.

**Describe alternatives you've considered**
I tried to block the fingerprint reading (with privacy.resistFingerprinting => true) but it introduce severe scrolling lag, it make it unusable. 

**Additional context**
The add-on which affect the website theme like dark reader can't work properly while some site are displayed in their dark theme version.

**Comment by MrAlex94** [comment]
Is Settings > General > Language and Appearance > Website appearance what you want?

<img width="952" alt="image" src="https://user-images.githubusercontent.com/4728920/187711241-88267edc-f7e0-4d81-ab21-8a75b35f49c4.png">

**Comment by Fenghuang19** [comment]
I want to get the dark interface in waterfox about: page but the light version on the other site (like duckduckgo.com). In G5, it's only possible to get both on light or dark theme. 

If I set privacy.resistFingerprinting on true, it's possible to get dark waterfox about: page with duckduckgo page on light but it introduce a heavy scrolling lag.

**Comment by Fenghuang19** [comment]
The add-on "dark mode website switcher" solve partially this issue.
