### ISSUE TITLE
[G5 Beta] Address bar not focusing automatically in new windows

### ISSUE THREAD

**Issue by mr-nv** [MrAlex94/Waterfox#2790]
### What happened?

When you create a new window the browser isn't focusing on the address bar and you need to click on it to type in it
This was fixed before in issue #2370, but the issue came back in the newest beta version of Waterfox

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5 Beta

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Resolved in https://github.com/WaterfoxCo/Waterfox/pull/2791.
