### ISSUE TITLE
[G5.0b2 - Addon] addon can't find native application because REGPATH in NativeManifests.jsm changed to "Software\\WaterfoxLimited" 

### ISSUE THREAD

**Issue by freezewind** [MrAlex94/Waterfox#2794]
### What happened?

AdGuard Browser Assistant is an extension that connect AdGuard desktop app and browser together.
It show error message that "AdGuard is not installed or configured incorrectly"
![image](https://user-images.githubusercontent.com/3954389/190456863-17637efd-5c14-43cc-89b7-7ca13e9d6c8d.png)
 
Waterfox G4.1.5 doesn't have this error.
Firefox 102.2.0esr also doesn't have this error.

From the log in Browser Console, I find this line of log that should be related to this issue:
**00:33:59.562 ExtensionError: No such native application com.adguard.browser_extension_host.nm ExtensionUtils.jsm:58:5
    ExtensionError resource://gre/modules/ExtensionUtils.jsm:58
    startupPromise resource://gre/modules/NativeMessaging.jsm:81**

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G5 Beta

### What platform are you seeing the problem on?

Windows

### Relevant log output

> 00:33:58.966 1663259638966	addons.xpi	WARN	Checking C:\***\Waterfox\test\core\distribution\extensions for addons
00:33:59.185 NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFile.lastModifiedTime] config.js:35
    handleEvent config.js:35
00:33:59.222 Applying chrome://browser/content/overlays/tabfeatures.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:95:15
00:33:59.270 Applying chrome://browser/content/overlays/privatetab.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:95:15
00:33:59.284 Applying chrome://browser/content/overlays/statusbar.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:95:15
**00:33:59.562 ExtensionError: No such native application com.adguard.browser_extension_host.nm ExtensionUtils.jsm:58:5
    ExtensionError resource://gre/modules/ExtensionUtils.jsm:58
    startupPromise resource://gre/modules/NativeMessaging.jsm:81**
00:33:59.563 this.ports.get(...) is undefined ExtensionParent.jsm:378
    recvPortMessage resource://gre/modules/ExtensionParent.jsm:378
    recvPortMessage self-hosted:1115
    _recv resource://gre/modules/ConduitsChild.jsm:82
    receiveMessage resource://gre/modules/ConduitsParent.jsm:450
00:34:00.650 Error: Can't find profile directory. XULStore.jsm:66:15
    load resource://gre/modules/XULStore.jsm:66
    XULStore resource://gre/modules/XULStore.jsm:24
00:34:02.119 Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_quickRestart” browser.xhtml
00:34:02.119 Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml
00:34:02.119 Key event not available on some keyboard layouts: key=“p” modifiers=“alt control” id=“newPrivateTab-key” browser.xhtml
00:34:02.119 Key event not available on some keyboard layouts: key=“t” modifiers=“alt control” id=“togglePrivateTab-key” browser.xhtml
00:34:03.546 NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFile.lastModifiedTime] config.js:35
    handleEvent config.js:35

**Comment by freezewind** [comment]
I am new in firefox source code, but I have some finding after reading the code in NativeMessaging.jsm:81
```
    this.startupPromise = NativeManifests.lookupManifest(
      "stdio",
      application,
      context
    )
      .then(hostInfo => {
        // Report a generic error to not leak information about whether a native
        // application is installed to addons that do not have the right permission.
        if (!hostInfo) {
          throw new ExtensionError(`No such native application ${application}`);
        }
```
hostInfo should be the return of NativeManifests.lookupManifest

In resource://gre/modules/NativeManifests.jsm, I found out the only difference between G4, 102esr, and G5 is one line of code in line 34.
G5:
```
const REGPATH = "Software\\WaterfoxLimited";
```
G4 and 102esr
```
const REGPATH = "Software\\Mozilla";
```

**Comment by freezewind** [comment]
After createing a key in "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\WaterfoxLimited\NativeMessagingHosts\com.adguard.browser_extension_host.nm" and changing the default value to C:\ProgramData\Adguard\HostManifests\com.adguard.browser_extension_host.nm-waterfox-manifest.json or com.adguard.browser_extension_host.nm-firefox-manifest.json, the issue is solved.

However, I would suggest chagne back the REGPATH to Mozilla. Most extentions using NativeMessagingHosts wouldn't consider to compatible with Waterfox. In the user experience aspects, using Mozilla REGPATH can avoid these kind of compatibility problems with Native Messaging Hosts.

In fact, I think Adguard is compatible with Waterfox before. They create a key in "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Waterfox\NativeMessagingHosts\com.adguard.browser_extension_host.nm". However, Waterfox uses WaterfoxLimited instead of Waterfox recently. Connecting with Adguard developers to change this key may be another way to solve this issue, but it only solve the compatibility issue with Adguard only...

**Comment by MrAlex94** [comment]
This has been changed in the latest rebase: https://github.com/WaterfoxCo/Waterfox/commit/3b10a9d4ebd908a0f23a153aa4ac4fe544e0ac36#diff-f694ee8bea547a8a350464c05a93c2236a09b5e84c071caf2ecd5f85a0045ee6

It makes sense for Waterfox to be as compatible as possible. This will be live in Beta 3. So give it a whirl and let me know!

**Comment by freezewind** [comment]
Just try the Beta 3 version. It works like a charm. Thank you for the quick fixing.

**Comment by MrAlex94** [comment]
No problem! Glad it's working.
