### ISSUE TITLE
Search engines do not save & Bing is added again and again

### ISSUE THREAD

**Issue by 4w3Official** [MrAlex94/Waterfox#2801]
### What happened?

When trying to set Google as the default search engine, Bing is always added again - even after deleting it.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5 Beta

### What platform are you seeing the problem on?

Windows

**Comment by 4w3Official** [comment]
fixed (?) with G5.0 Beta 5 (Sep 23, 2022)

**Comment by MrAlex94** [comment]
Great! Let me know if this issue happens again.

**Comment by ibeladi-mrsool** [comment]
I am experiencing this
G5.0.1 (64-bit) on linux
Update: G5.0.2 as well
Update: G5.1 as well

**Comment by ashley-graves** [comment]
> I am experiencing this G5.0.1 (64-bit) on linux

Same here
