### ISSUE TITLE
Reenable CSP option in about:config

### ISSUE THREAD

**Issue by garoxas** [MrAlex94/Waterfox#2804]
**Is your feature request related to a problem? Please describe.**
[Bug 1754301](https://bugzilla.mozilla.org/show_bug.cgi?id=1754301) removed `security.csp.enable` in `about:config`, and this has also been applied to Waterfox in https://github.com/WaterfoxCo/Waterfox/commit/30828a6a4970f19cc37dced1e21812b086e36455 (though I only noticed it after upgrading to version 102.3.0esr)

**Describe the solution you'd like**
Revert this commit so users can freely choose whether they want to enable (default) or disable CSP in Waterfox

**Describe alternatives you've considered**
None, but I welcome any other suggestions so long that my add-on can work

**Additional context**
I'm currently using an add-on that uses `Function` call at its core and it won't run if CSP is enabled in Waterfox with `call to Function() blocked by CSP` error. I'm fully aware on the reason why they removed this in the first place, however replacing the `Function` call to other alternatives requires major rework on this add-on and I would like to avoid that
Also this option is disabled by default and well hidden in `about:config`, so I think it's pretty reasonable to have this option back

**Comment by garoxas** [comment]
Umm, this is embarassing but apparently I was using Firefox and not Waterfox just now 🤦‍♂️
Just checked with Waterfox G4.1.5 and the add-on still work, although I'm not too sure with G5 since it's based on Firefox 102 IIRC

**Comment by MrAlex94** [comment]
Yes, G5 has inherited this. I don't think this will be something we'll want to re-implement, sorry.
