### ISSUE TITLE
The top edge is not clickable in the compact theme (G5 beta)

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [MrAlex94/Waterfox#2805]
### What happened?

when changing theme density to compact the upper edge of the window becomes not responsive to mouse click so you can't change tabs unless you targeted the tabs just a little bit down to the edge which is pretty annoying
the bug is not found in the original firefox theme

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Please report this issue to the theme repo: https://github.com/black7375/Firefox-UI-Fix
