### ISSUE TITLE
Development of G4

### ISSUE THREAD

**Issue by rodrigofarias77** [MrAlex94/Waterfox#2806]
First of all, thank you for maintaining this project.

I have been using Firefox 91 ESR until its EOL, a few days ago. As far as I know, it was the last maintained version that still supported OpenGL compositing and GTK theming for widgets. I can only get consistent subpixel antialiasing with OpenGL.

Is the development of Waterfox G4 going to continue after 91 reached EOL? My understanding the that G5 is based on 102. Is it going to somehow support OpenGL compositing and GTK theming?

I am running Waterfox G4 1.5 on Arch Linux.

**Comment by MrAlex94** [comment]
Sadly, this won't be the case. G5 has now released and so G4 (and ESR91) will no longer maintained.

Re-implementing compositing won't be feasible either - sorry.
