### ISSUE TITLE
Waterfox 5.0  -  Add-on Dictionary / Language Pack wipe-out

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2815]
### What happened?

Installing  Waterfox 5.0  over   Waterfox 4.1.5  wipes out my Language Pack and Dictionary.

I had Waterfox 4.1.5 installed in English UK with a French Language Pack and a French Dictionary.

After installing Waterfox 5.0 over 4.1.5, they both disappeared and I had to re-install them.

O.

### Reproducible?

- [x] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Hey @Objectivite  - I _believe_ this is default behaviour not handled by us. However, we do distribute all installers with a range of alternative languages as default. Are these not sufficient for your case?
<img width="728" alt="image" src="https://user-images.githubusercontent.com/47503375/193791567-c5be729a-4822-4f5f-9efe-a4b84cd2a110.png">

**Comment by Objectivite** [comment]
Hi Adam,

Reading your reply I think I may have misled you a little bit.

As I work in the UK I install Waterfox with the UK language pack, so all the menus, etc..., are in English UK.  But as I often access French websites from my native France, I install the French dictionary to spell check when I am filling online forms on a French website.  It is that specific French dictionary that got wiped out by the Waterfox 5.0 install.

O.

**Comment by adamp01** [comment]
Understood - the dictionary is just an extension such as: https://addons.mozilla.org/en-US/firefox/addon/dictionnaire-fran%C3%A7ais1/ , correct?

If so I'll have to do some testing to see why that is getting wiped out.

**Comment by Objectivite** [comment]
Hi Adam,

You have got it spot on - that is the very add-on dictionary that I use.

O.

**Comment by adamp01** [comment]
I just tested an upgrade from G4.1.5 to G5.0.1 and the dictionary was maintained. If you are able to replicate this yourself, could you please send over any logs from the browser console (ctrl shift j) right after upgrade please?

**Comment by Objectivite** [comment]
Hmmmmm.

OK - I just tried installing 5.0.1 over 4.1.5 on a different PC to mine and got a Visual C++ runtime error - I have submitted a bug.


O.

**Comment by MrAlex94** [comment]
We'll keep an eye on this, in case anyone else has a similar issue, but thanks for reporting.
