### ISSUE TITLE
Use native full screen for video full screen on macOS

### ISSUE THREAD

**Issue by y2-Whyto** [MrAlex94/Waterfox#2817]
**Is your feature request related to a problem? Please describe.**

Yes. On macOS, a full-screen app is treated as a separate desktop and takes a place in Mission Control, so users can wipe between the full-screen app and the normal desktops. But now the full-screen of Waterfox just expand itself in the normal desktop without creating a new one and locating itself there. This makes it inconvenient for users to swipe out of and come back to the full screen. (You have to Esc or find and click the full-screen button every time)

**Describe the solution you'd like**

I hope on macOS, Waterfox could use system native full screen. It looks behaving like this (You can also check Chrome or other Chromium-based browsers for reference):

- When you click the full-screen button of a video, it pops out of the present desktop and goes to the right side of the screen.
- Then it locates itself in another full-screen window, taking up a new place of a desktop, which can be observed in Mission Control.
- When you hover your mouse to the top of the full-screen, the menu bar of the system and the title bar of the app show up. (Typical for a native full-screen app).

**Describe alternatives you've considered**

None.

**Additional context**

Chrome or other Chromium-based browsers on macOS has already implemented this feature. For the animated process of the description above, you can simply try out in one of them.

Also, I noticed that this feature is not yet implemented in original Firefox either. But I still hope you could consider this important feature, for I think you won't be limited to just the upstream.

**Comment by MrAlex94** [comment]
You can toggle `full-screen-api.macos-native-full-screen` to `true` if you'd like in `about:config`.

If you report no issues after using it for a while, please @ me and we'll enable by default.

**Comment by y2-Whyto** [comment]
> You can toggle `full-screen-api.macos-native-full-screen` to `true` if you'd like in `about:config`.
> 
> 
> 
> If you report no issues after using it for a while, please @ me and we'll enable by default.

Thank you! I've just enabled it. And I'll report my experience soon.

**Comment by y2-Whyto** [comment]
@MrAlex94 For your information, I haven't come across any issue by now. In my point of view, it's safe to turn this feature on.
