### ISSUE TITLE
macOS 10.12 error

### ISSUE THREAD

**Issue by TTPAUT** [MrAlex94/Waterfox#2820]
### What happened?

Good day! When launching a new version of G5.0, a crash occurs on mac OS 10.12.6
![photo_2022-10-04_02-30-23](https://user-images.githubusercontent.com/84172584/193705098-e54dddf2-da64-41af-b34a-cb6e2f06475c.jpg)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS

**Comment by MrAlex94** [comment]
What Mac do you have?

**Comment by TTPAUT** [comment]
![image](https://user-images.githubusercontent.com/84172584/193821974-305f4944-7e9b-42a2-a73d-95ad681ab757.png)


> What Mac do you have?

**Comment by MrAlex94** [comment]
Ah yes, sadly the requirements have been bumped to require [Nehalem](https://en.wikipedia.org/wiki/Nehalem_(microarchitecture)#Mobile_processors) or newer on macOS.

Auto-updates will not be seeded to processors without support for the appropriate instruction sets, unfortunately there's no way to stop DMG files from mounting on unsupported systems :(
