### ISSUE TITLE
Waterfox 5.0.1 Visual C++ installation error

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2824]
### What happened?

Hello,

Just installed  5.0.1  over 4.1.5 and got the attached error.

On completion Waterfox would not load.  I had to re-install 4.1.5 over the top.

![image](https://user-images.githubusercontent.com/89191739/193839051-6ac3bb2a-2c4f-43cf-893e-55f2bb54d845.png)

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
What Windows version is this? For G4, I applied the patch for https://bugzilla.mozilla.org/show_bug.cgi?id=1624546, but Mozilla haven't done so themselves. It looks like the majority of users don't face the issue - but I'd imagine on a clean install they would (the priority on this issue is odd).

**Comment by Objectivite** [comment]
Hello,

This was on newly set up PC with Windows 10 Build 21H2.

This PC has only ever seen one version of Waterfox, version 4.1.5  and 5.0.1  was the first over-the-top upgrade ever being performed on it.

O.

**Comment by MrAlex94** [comment]
Crazy Mozilla still don't bundle it!! My fault for not catching it. New installer is building now, will drop link here when it's done.

https://github.com/WaterfoxCo/Waterfox/commit/adad44d8f11409dbf219d471fef00e57e1e68c8d

**Comment by Objectivite** [comment]
Thank You.

O.

**Comment by MrAlex94** [comment]
https://cdn1.waterfox.net/waterfox/releases/G5.0.1/WINNT_x86_64/Waterfox%20Setup%20G5.0.1.exe should be live now with an updated SHA512 of `8e7ea065c3c97c762ec04d17062148fba005ddd06a07b472c83b6600c28386886db2e95e537df9bdf64c9de9838ee50b0af119545b7c1dcc88b9cdc5f5f170a4`

**Comment by Objectivite** [comment]
That works.

I installed it on the exact same PC where the official 5.0.1 threw up the Visual C++ Runtime error and it sailed through, it is up and running, and I confirm the fixes from Adam with regards to the themes.

O.

**Comment by MrAlex94** [comment]
Excellent! Cheers for the reports.
