### ISSUE TITLE
Remove lime green tab highlight

### ISSUE THREAD

**Issue by orazdow** [MrAlex94/Waterfox#2826]
I just received the update to 5.0.1. The biggest visual change is the rectangular tabs and the green accent bar over the active tab.
The green highlight is distracting to look at and doesn't look great in my opinion Is this intended, or possibly an unintended issue with Linux mint's theming? If it's not, I think it would be good to have the option to turn off this highlight bar. A picture is below:

![Screenshot from 2022-10-04 18-48-54](https://user-images.githubusercontent.com/10949483/193945470-479c8418-af83-402c-ad78-ed5dd2f2fb78.png)

In the meantime, I will try to install a previous release. Thanks.

**Comment by MrAlex94** [comment]
You can go to `about:config` and toggle `userChrome.tab.photon_like_contextline` to `false`.
