### ISSUE TITLE
G5.0.1 No longer opens bookmark folders/groups from bookmark sidebar

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2827]
### What happened?

If I open my bookmark sidebar normally I ctrl click to open a folder of bookmarks. Upon updating to G5.0.1 this no longer works. If I right click the folder it says "Open All Bookmarks" but if I select that...nothing.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

Side note the help page that loads is also a 404 "https://www.waterfox.net/support/Linux/firefox-help"

**Comment by adamp01** [comment]
@nPHYN1T3 -  I believe I have found the root cause for this, I will have a PR submitted so this is resolved for next release.

**Comment by ghost** [comment]
Aight ;) Sanke
