### ISSUE TITLE
Extra space on the left side of the tab bar in native full screen on macOS

### ISSUE THREAD

**Issue by y2-Whyto** [MrAlex94/Waterfox#2829]
### What happened?

After I click the enter full screen button of a window on macOS, there is extra space left on the left side of the tab bar of the full screen window, which is shown as follows (both pictures are taken in full screen window mode):

<img width="330" alt="Snipaste_2022-10-05_15-21-08" src="https://user-images.githubusercontent.com/42339192/194008351-ba5555a1-c3f0-44db-9f66-babc07396321.png">

<img width="330" alt="Snipaste_2022-10-05_15-21-24" src="https://user-images.githubusercontent.com/42339192/194008397-fa72aba6-029c-4329-be2f-a63474573c2e.png">

This is not the case on the original Firefox (version 105.0.2). On Firefox, there's no extra space on the left side of the tab bar in a full screen window.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G5.0.1 (64-bit)

### What platform are you seeing the problem on?

macOS

**Comment by MrAlex94** [comment]
Do you have a screenshot from Firefox depicting what you expect it to look like?

**Comment by y2-Whyto** [comment]
> Do you have a screenshot from Firefox depicting what you expect it to look like?

Yes. These are what Firefox (version 105.0.2) looks like

- in a normal window:

  - <img width="370" alt="Snipaste_2022-10-06_00-20-35" src="https://user-images.githubusercontent.com/42339192/194111447-92ca7659-3751-4283-9a04-8ca3950eca4a.png">

- in a full screen window:

  - <img width="370" alt="Snipaste_2022-10-06_00-20-16" src="https://user-images.githubusercontent.com/42339192/194111475-828d39b7-5c9b-47a7-b977-f57c9dd0cd72.png">
  - <img width="370" alt="Snipaste_2022-10-06_00-20-00" src="https://user-images.githubusercontent.com/42339192/194111740-5b248a14-a4db-4bc8-bb0b-e719e01ad84d.png">

You can see there is no extra space on the left side of the tab bar in full screen compared to Waterfox.

By the way, I rechecked the description of the bug, and I'm really sorry that I seemed to be ambiguous. I've also edited the bug description to clarify the issue.
