### ISSUE TITLE
`Open all bookmarks` not working

### ISSUE THREAD

**Issue by gtdeng** [MrAlex94/Waterfox#2837]
### What happened?

Steps to reproduce:
Open Bookmarks sidebar
Have bookmarks within a folder
Right click to `Open all bookmarks`

Expected:
Bookmarks to open new tabs within the browser

Actual:
Nothing happens; new tabs are not created/opened.

Workaround:
Right click `Open all bookmarks` in the bookmarks toolbar (instead of the sidebar)

Other:
This is not reproduceable on Firefox Dev 106.0b8 (64-bit).

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS

**Comment by MrAlex94** [comment]
This was resolved in https://github.com/WaterfoxCo/Waterfox/pull/2830 and the update with the fix will be pushed out soon.
