### ISSUE TITLE
Lingvanex

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2838]
I can install Google Translator plugin, having serious privacy issues. All data is just send to Google.

Is it possible to implement built in translator, translating more than 100 languages for Vivaldi Browser. They use https://lingvanex.com/

**Comment by MrAlex94** [comment]
We won't support this for the moment, but eventually Firefox Translation will become a part of Waterfox.

You can get the add-on here: https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/
