### ISSUE TITLE
Seach bar behaviour

### ISSUE THREAD

**Issue by Balzhur** [MrAlex94/Waterfox#2841]
### What happened?

Dedicated search bar (not the URL bar) does not react to mouse clicks - cannot select text with the mouse or place cursor somewhere in the search phrase for editing, instead mouse click selects all text and this text can be dragged by mouse.

Appeared in G5.0.x in G4.x.x it was perfectly fine.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by rider45** [comment]
Can confirm, just upgraded 2 days ago. have to use back key to delete text input

**Comment by uqus** [comment]
https://github.com/WaterfoxCo/Waterfox/issues/2833

**Comment by Balzhur** [comment]
> #2833

Perfect, thank you!
However that issue is closed and not displayed in the open issues, that's why a duplicate - I simply missed that.

**Comment by Kilzzz** [comment]
I can confirm the problem on Linux. Running up to date Manjaro.
