### ISSUE TITLE
Download checksum file has ending .sha512 while website mentions .SHA512.

### ISSUE THREAD

**Issue by halloleo** [MrAlex94/Waterfox#2845]
### What happened?

When I try to verify the download file for G5.0.1 the Downloads webpage [waterfox.net/waterfox/releases/G5.0.1/Darwin_x86_64-aarch64/](https://cdn1.waterfox.net/waterfox/releases/G5.0.1/Darwin_x86_64-aarch64/) mentions the checksum file has the ending `.SHA512` (note the **uppercase**  letters).

However the real accompanying checsum file has the ending `.sha512` (note the **lowercase** letters).

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS

**Comment by adamp01** [comment]
Thanks for raising this - I have updated the Download page to reflect the correct case.
