### ISSUE TITLE
Inhibit the close "X" on short tab LIKE BEFORE G5

### ISSUE THREAD

**Issue by UmiAkai** [MrAlex94/Waterfox#2846]
**Is your feature request related to a problem? Please describe.**
When browsing with many tabs, the tabs shorten, and the close "x" on tab was hidden but still there, when I move mouse to the tab with the intention to open it, the x popped out and I frequently hit that x and closed the tab instead.

**Describe the solution you'd like**
In G4.1.5, when there are many tabs, the background tab's close "x" were inhibited even if you move the mouse on it, I won't accidentally close it like in G5, if I want to close a background tab, I'll use mid mouse click anyway.

I see someone want the x there, but I don't, so please make it an option.

**Comment by skooter7** [comment]
Hey, it's not the same but you can completely remove the x button and just middle click on tab to close them.

Do this in about:config

userChrome.theme.enable = false

toolkit.legacyUserProfileCustomizations.stylesheets = true

and create a userchrome.css with just this code
```

#tabbrowser-tabs .tabbrowser-tab .tab-close-button {display:none!important}

#tabbrowser-tabs ~ #alltabs-button {display:none!important;}
```

To learn how to make a userchrome.css read this, it's incredibly detailed so anyone can do it

https://www.howtogeek.com/334716/how-to-customize-firefoxs-user-interface-with-userchrome.css/

**Comment by adamp01** [comment]
@UmiAkai - You should be able to do this by going to `about:config` searching for `userChrome.tab.close_button_at_hover` and setting that to false (or adding as a new boolean set to false). You will need to restart the browser for it to take effect.

In the next version of the browser to be released we have introduced a "Look & Feel" preferences page that will make doing this far simpler.
