### ISSUE TITLE
Can't seletc word in search bar

### ISSUE THREAD

**Issue by gotshadowbantempaccount** [MrAlex94/Waterfox#2853]
### What happened?

try to select some part of workds but keep selecting all it is normal to change some word in search :
AMD Ryzen 9 7950X 
AMD Ryzen 9 7950X  motherboard  :: change to
AMD Ryzen 9 7950X  cooling  :: change to
AMD Ryzen 9 7950X  1U colling  :: change to

Just can't do it have to type again or copy to notepad to edit

![nokurwajegomac](https://user-images.githubusercontent.com/88304290/195115388-f56933ae-739f-439c-a2f9-65b9279e476a.png)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by stu-carter** [comment]
Also the same problem on G5.0.1 (64-bit) Windows.

**Comment by adamp01** [comment]
Hi,

If you go to `about:config` and change `layout.forms.input-type-search.enabled` to false, then restart the browser you should be able to select text in the small search bar again.

**Comment by gotshadowbantempaccount** [comment]
its do the job thx
