### ISSUE TITLE
G5 Zoom percentage not showing in url bar

### ISSUE THREAD

**Issue by the-r3dacted** [MrAlex94/Waterfox#2856]
### What happened?

With Firefox, if the webpage zoom is anything other than 100%, the percentage will show in a button in the url bar. Waterfox G5, at least with the theme disabled doesn't show the button.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Hi,

This is a side effect of a feature. Unfortunately I can only push a fix for new users, not for existing users.

If you go to App Menu -> More Tools -> Customize Toolbar and then pull the zoom controls off the status bar at the bottom, the zoom button should appear in the URL bar again.

**Comment by the-r3dacted** [comment]
As an existing user it worked for me
