### ISSUE TITLE
Waterfox G5.0.1 right-click commands and merging text-background colors

### ISSUE THREAD

**Issue by bacounsel** [MrAlex94/Waterfox#2859]
### What happened?

I use Waterfox G5.0.1 with a dark mode add-on, i.e., Dark Background and Light Text v0.7.6, and run it on Windows 7.

When I right-clicked on a blank space in the tab bar where a box of commands would appear, it happened that when I pointed the mouse over any of the commands within the command box, both their text and the background colors would be merged in dark (black) color. This makes it hard to see the text clearly.

This problem has never occurred in Waterfox G4.1.5 or Firefox ESR 102.3.0. In both browsers, the text color was in yellow in contrast with the dark background color. I understand the yellow text came from a theme setting I had made to Window Color and Appearance of Windows 7.

I would be grateful if you could please restore the text color coding so it is consistent with the Window Color and Appearance settings.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
If you go to `about:config` and change `userChrome.theme.enable` to false are the colours then correct (ignoring other visual changes)?

**Comment by bacounsel** [comment]
I confirm the colors are correct following my toggling of the "userChrome.theme.enable" code to "false". It works fine, and I thank you, adamp01, very much.
