### ISSUE TITLE
(Not a bug) I installed waterfox-g4-bin and I installed waterfox-g-bin now, how do I move my configs from g4 to g?

### ISSUE THREAD

**Issue by RaptaG** [MrAlex94/Waterfox#2862]
### What happened?

Anything?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

**Comment by RaptaG** [comment]
Forgot to mention I mean the AUR packages

**Comment by hawkeye116477** [comment]
Just launch Profile Manager and choose your old profile.

PS: That aur packages are basically repackaged tarball from official website.
