### ISSUE TITLE
G4-G5.01 Lepton theme bugged buttons.

### ISSUE THREAD

**Issue by kamil445** [MrAlex94/Waterfox#2863]
### What happened?

Sometimes address bar and menu bar stopping working when i use lepton theme, just can't click on address bar and menu button. 
But i can click on bookmarks,home and downloads buttons without problems. Also can't close current opened tab (X button doesn't work too).
I can open new tab, close other tabs.
Sometimes it will back to normal after a while, but sometimes i need to restart Waterfox.

Here you have screen with doesn't working buttons.

https://imgur.com/FOrHYEG

When i disable Lepton theme (in g5 change userChrome.theme.enable to false) doesn't have this issue.

I'm using Windows 7 x64

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Please report this at [@black7375/Firefox-UI-Fix](https://github.com/black7375/Firefox-UI-Fix)
