### ISSUE TITLE
Can't set cursor location in search box by clicking the mouse

### ISSUE THREAD

**Issue by chriscjcj** [MrAlex94/Waterfox#2869]
### What happened?

1. Enter a couple of words in the search box and then take focus away from the search box.
2. Now click somewhere in the middle of the text that's in the search box. That will select all the text in the search box.
3. Let's say you want to add a word somewhere in the middle of the selected text. Try to click in the middle of the text that's in the search box so that your cursor appears in the middle of that text. It won't work.

You can hit the right or left arrow on your keyboard to unselect the text and have your cursor at the beginning or end. But, at any point, if you use your mouse to try to select the location of where you'd like your text cursor to be in the search box, it does nothing. You're must only use the arrow keys to move the cursor within the text box.

This behavior occurs on Waterfox G5.0.1 (64-bit) on Mac OS and Windows.

This behavior _**does not**_ occur on Firefox 105.0.3 (64-bit). 

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS, Windows

**Comment by adamp01** [comment]
See fix in #2853
