### ISSUE TITLE
Bitwarden "unlock with biometrics" doesn't work

### ISSUE THREAD

**Issue by kopach** [MrAlex94/Waterfox#2870]
### What happened?

Bitwarden uses native messaging permission (Exchange messages with programs other than Waterfox) to allow browser extension to be unlocked using biometrics.

Unfortunately, this feature doesn't work in Waterfox for me. Works in Chrome though.

![2022-10-17 23 59 27](https://user-images.githubusercontent.com/8749624/196291863-9111ea97-2d51-4c54-b266-d003ea3cb11b.gif)

---
I can enable this feature correctly in Firefox. 

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS

**Comment by adamp01** [comment]
Could you give this a try and let me know if it fixes please -

you could symlink as well:
ln -s ~/Library/Application\ Support/Mozilla/NativeMessagingHosts ~/Library/Application\ Support/Waterfox/NativeMessagingHosts

**Comment by kopach** [comment]
hi @adamp01 , your method did help. It works now for me. Thanks a lot for fast reply and help.
