### ISSUE TITLE
[G5.0.2] There's no way to disable Recent Bookmarks

### ISSUE THREAD

**Issue by luisbilhar** [MrAlex94/Waterfox#2880]
### What happened?

A bug happened!
I can't find any way to disable Recent Bookmarks list in version G5.0.2

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by J-Wildfire-T** [comment]
Not sure if this is what your looking for, but I use this setting under about:config

browser.bookmarks.editDialog.maxRecentFolders = 0

**Comment by luisbilhar** [comment]
> 

Hi @J-Wildfire-T . It's not this situation. I want to disable this: "Recent Bookmarks "

![recent bookmarks](https://user-images.githubusercontent.com/116814853/199075018-d3232824-0044-49e3-8d65-281179246ae8.jpg)

**Comment by MrAlex94** [comment]
This can't be disable unfortunately.
