### ISSUE TITLE
Blank window + "blocked from accessing Graphics hardware" when h/w acceleration enabled

### ISSUE THREAD

**Issue by Wonderer0** [MrAlex94/Waterfox#2884]
### What happened?

When WF (5.0.2) starts the contents of the current page is blank for a few seconds, then the URL bar, tabs etc all vanish as the window flashes and its entire contents go blank (white).  The window flashes several times, sometimes turning all black. The page is displayed normally after about 30 - 90 seconds.  The exact behaviour and time seem to depend upon whether or not the window is clicked in while this is happening.  Also Windows usually displays the notification "Application waterfox.exe has been blocked from accessing Graphics hardware.".

This problem occurs when "Use recommended performance settings" is ticked, but goes away when "Use hardware acceleration when available" is unticked.  It also occurs in a new profile with no add-ons.  It doesn't occur in Firefox (106.0.2) or WF G4 (4.1.5).

This is in Windows 10 using a fairly old (Sandy Bridge) integrated Intel HD Graphics 300 adapter.  The driver is up to date, and DISM ScanHealth doesn't find any problems. 

WF has lots of media changes from G4 → G5, could the problem be that my old graphics adapter can't support some of those new features?  If so it possible to disable hardware acceleration for them but retain it for the rest?

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Hi, it's likely ESR102 (what we are based on) blocking your hardware, and it could be that further upstream this has been resolved.

Unfortunately I can't say there's much we can do for this, sorry about that.

**Comment by Wonderer0** [comment]
> Hi, it's likely ESR102 (what we are based on) blocking your hardware, and it could be that further upstream this has been resolved.

I have installed FF ESR (102.5.0) and that works OK, as it did the latest current release (107.0), so it looks like the problem has been introduced in WF and this will have to be re-opened.

I noticed this bug because after upgrading WF it automatically tries to display the relevant WF release page upon restarting (e.g. https://www.waterfox.net/docs/releases/G5.1/?update).  Because this always failed I turned off h/w acceleration to be able to continue.

However I have now found that other pages display OK with it turned on (e.g. WF on GitHub and Reddit, bbc.co.uk, google.co.uk).  In fact the only website that I have found so far that has this problem is https://www.waterfox.net !

So I tried going back up the URL, successively deleting everything after the last `/`, in case it was just the release pages.  But every level caused this problem, including https://www.waterfox.net/docs/releases/ which gives a Page Not Found page.

I installed NoScript and set https://www.waterfox.net/ to be untrusted in the hope that it might block whatever was causing the problem, but it still occurs.

Do you have any idea why https://www.waterfox.net/ is causing this problem when other sites don't?  If not I can try eliminating parts of the Page Not Found page's source code in a local version to try to isolate the part that's causing the problem.  It's quite complex for a Page Not Found page, any idea which part is trying to get direct access to my graphics h/w?

N.B. Windows System Log gives warnings "Display driver igfx stopped responding and has successfully recovered.".  I can post the message's XML source if it helps, but it probably doesn't much.
