### ISSUE TITLE
Help Screen

### ISSUE THREAD

**Issue by DAMoran2022** [MrAlex94/Waterfox#2885]
Could we PLEASE get rid of that GOD-AWFUL blue help screen?? It is really hard for me to read compared to the original. I don't see that it serves any useful purpose.

**Comment by hawkeye116477** [comment]
Version number on help screen is also wrong. It looks like someone forgot to bump version number in https://github.com/WaterfoxCo/Waterfox/blob/G5.0.2/browser/config/version_display.txt.

**Comment by MrAlex94** [comment]
Sorry about that - will see if we can make it easier on the eyes.

@hawkeye116477, we no longer push the version number in the src, it happens at build time.
