### ISSUE TITLE
[SOLVED] 'Open With' Extension stopped working in WaterFox G5.x macOS

### ISSUE THREAD

**Issue by LeeBinder** [MrAlex94/Waterfox#2887]
**[EDIT]**: work-around provided by adamp01, see https://github.com/WaterfoxCo/Waterfox/issues/2887#issuecomment-1300049863 (to be copy/ pasted into Terminal > Enter)

### Platform information:

- issue occurring in macOS Intel, tested in Monterey 12.2.1 and Catalina 10.15.7
- issue **_not_** occurring in Windows
- not able to test in Linux (not installed)

### Affected Waterfox Version(s) and Profiles:

- G5.0.2/  G5 Beta 1 and Beta 3
- G5.0.2 updated from v.4 in my existing profile
- also in stock app directly downloaded from your website, in a new blank profile created from scratch

### What's the issue?

The extension **Open With** ([https://addons.mozilla.org/en-US/firefox/addon/open-with](https://addons.mozilla.org/en-US/firefox/addon/open-with)) suddenly cannot "connect to the outside world" anymore in macOS:

![Bildschirmfoto 2022-10-30 um 23 51 46](https://user-images.githubusercontent.com/39203497/198905663-e94a618b-b25e-4113-af6b-2b956eee191e.jpg)

After clicking onto "Open With options..." > Test Installation:

![Bildschirmfoto 2022-10-30 um 23 46 00](https://user-images.githubusercontent.com/39203497/198905488-89821a29-4ece-4271-bb3a-235b804a6d66.jpg)

Also no list with my browsers on the right. In other words, WF G5.x somehow blocks connecting to `open_with_mac.py`

### Verification/ Expected Behavior:

- [X] I have tested this on latest Firefox both release (v.106.0.3) and ESR (v.102.4.0esr) and also in the latest WF G4.x - it's still working in all 3, see screenshot (same in all 3 of those brwosers):

![Bildschirmfoto 2022-10-30 um 23 39 27](https://user-images.githubusercontent.com/39203497/198905125-6fbe51da-7af8-45fb-a609-b42188dd8009.jpg)

**Python in use**:
- v.3.8.2 in /usr/bin/python3 (stable for me)
- no change after updating to latest Python v.3.11

### Attempted steps trying to solve the issue to no avail:

- re-downloading and re-installing [open_with_mac.py](moz-extension://06c7ae55-8df0-4040-b78a-30365bf10ea6/native/open_with_mac.py)
- placing it right into the current active profile folder and install from there

### Relevant log output:

```shell
From console:

ExtensionError: No such native application open_with 5 ExtensionUtils.jsm:58:5
    ExtensionError resource://gre/modules/ExtensionUtils.jsm:58
    startupPromise resource://gre/modules/NativeMessaging.jsm:81
```
Let me know if you need any more info from me.

(other than this little bug your awesome flagship of a browser is working as mighty-fine as can be 👍 💯 🥇 !!)

**Comment by adamp01** [comment]
Hi @LeeBinder  - Seems like a native messaging issue. Would you be able to try running this command:
`ln -s ~/Library/Application\ Support/Mozilla/NativeMessagingHosts ~/Library/Application\ Support/Waterfox/NativeMessagingHosts`

**Comment by LeeBinder** [comment]
@adamp01 udaman - again working as supposed. Thanks for providing the fix!

I'll mark this issue solved but leave it open until release of WF G5.0.3 with this fix merged so others can find it, too, and profit.

**Comment by MrAlex94** [comment]
This should now be live in G5.1

**Comment by LeeBinder** [comment]
Confirmed - thank you Alex!
