### ISSUE TITLE
"Never Check for Updates"  does NOT work in either 5.0.1 or 5.0.2

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2888]
### What happened?

I had 5.0.1 set to  **"Never Check for updates"**  on a number of PCs.

I found this morning that not only did that not work - all 5.0.1 have been updated to 5.0.2 this morning but, worse, the setting  "Never check for updates"  has been changed back to Automatic Updates by the 5.0.2 update.

Since this problem is not mentioned in the list of fixes for 5.0.2 my assumption is that the problem is also present in 5.0.2

![image](https://user-images.githubusercontent.com/89191739/199182310-1431d649-7e64-40ac-a8cc-891f8b989e34.png)

I am now reverting back to the technique of creating a  DISTRIBUTION  directory in the Waterforx install folder and putting a POLICIES.JSON  file that disables automatic updates.

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Thanks for raising, I'll look into this.

**Comment by Objectivite** [comment]
Thank You.

O.

**Comment by MrAlex94** [comment]
This should now be live in G5.1 (Mozilla reset the preference for some reason in ESR102). Please re-open if it doesn't work.
