### ISSUE TITLE
Misinformed Update Available Prompt 

### ISSUE THREAD

**Issue by satovey** [MrAlex94/Waterfox#2889]
### What happened?

Waterfox 5.01 on Windows 8.1 prompts with 
update available. After clicking the link to go 
to the download page, the latest version available 
is Waterforx 5.01, The same version installed..

This does not occur in Firefox.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by TiCoKH** [comment]
Same on Window 10 64x version

**Comment by BobbsGit** [comment]
Same on Win 10-64bit. Updated Waterfox to G5.0.1 (current) on October 4, release day. Have received at least two little pop ups stating that a new release is available.

**Comment by ThorsGH** [comment]
Same on Linux, many popups. https://www.waterfox.net/download/ also shows 5.0.1.
5.0.2 is available, and has a docs page, just not advertised on the download site.

**Comment by AlphaElwedritsch** [comment]
start manual download:

https://cdn1.waterfox.net/waterfox/releases/G5.0.2/WINNT_x86_64/Waterfox%20Setup%20G5.0.2.exe

**Comment by MrAlex94** [comment]
Hi all,

G5.1 has been released - are you all still getting this issue?

**Comment by BobbsGit** [comment]
5.1 installed W10-64bit couple days ago. This issue seems to have been fixed. Thanks for asking.
