### ISSUE TITLE
Waterfox update not available to download

### ISSUE THREAD

**Issue by fr000gs** [MrAlex94/Waterfox#2896]
### What happened?

Waterfox G5.0.2 update not available to download from the [website](https://www.waterfox.net/download/).
Browser tells over and over to manually update.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

**Comment by AlphaElwedritsch** [comment]
https://cdn1.waterfox.net/waterfox/releases/G5.0.2/WINNT_x86_64/Waterfox%20Setup%20G5.0.2.exe

**Comment by fr000gs** [comment]
Thanks for the link for Windows 😶

**Comment by MrAlex94** [comment]
This should now be resolved, with the website updated and the updater working correctly.

**Comment by fr000gs** [comment]
The website seems not to be updated..
