### ISSUE TITLE
The foolish upgrade bug

### ISSUE THREAD

**Issue by VasudeoSinha** [MrAlex94/Waterfox#2897]
### What happened?

well this bug shows me day and night only one thing and that is -
![image](https://user-images.githubusercontent.com/90196804/201707750-fc38e220-78ef-43a1-ae9f-88eb211364cc.png)

I have updated my version of waterfox a hundred times and even reinstalled it but maybe the bug isn't satisfied so please give this bug some satisfaction 
Thank You

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by AlphaElwedritsch** [comment]
https://cdn1.waterfox.net/waterfox/releases/G5.0.2/WINNT_x86_64/Waterfox%20Setup%20G5.0.2.exe

**Comment by MrAlex94** [comment]
Could I confirm which version of Waterfox specifically you're on that's having this issue?

A new update has been pushed out which should hopefully stop this error from happening.

**Comment by VasudeoSinha** [comment]
i must say that I love opensource software for this reason. Literally How can a bug really survive.
really thank you
