### ISSUE TITLE
"Center Tab Content" glitches some tabs' end gradient

### ISSUE THREAD

**Issue by Chirunos** [MrAlex94/Waterfox#2899]
### What happened?

A bug happened! When there's a tab that its width has an approximate width of its title, the end gradient starts blinking on and off. Happens both with active and inactive tabs (never happened with unloaded tabs). My display resolution is 1366 (w) x 768 (h). Happens both when "Center Tab Label Only" is on or off

This bug also causes high CPU usage. I've tried switching between tabs and the high usage doesn't stop. It stops when I open a new tab, for example (it changes the width of all tabs, if there are tabs enough to cover the width of the display)

Debian 11 (stable) and Waterfox G5.1

Recording:
https://user-images.githubusercontent.com/85644671/202054122-40fd4aa4-86dd-4868-b09a-3c2dcdca5bb7.mp4

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Thanks for bringing this up.

Please submit the issue to the theme's repository: https://github.com/black7375/Firefox-UI-Fix

Once it's fixed there, we'll pull it in here :-)
