### ISSUE TITLE
"Display close tab button on hover of selected tab when many tabs are open" not working on macOS

### ISSUE THREAD

**Issue by y2-Whyto** [MrAlex94/Waterfox#2901]
### What happened?

On Waterfox G5.1 on macOS, when the feature "Display close tab button on hover of selected tab when many tabs are open" in "Look & Feel" is toggled on, the close buttons of the tabs don't seem to change except for getting **bolder** (or bigger I guess?).

Here is the Before & After：

- Before (Toggled off)
<img width="575" alt="Snipaste_2022-11-17_10-03-49" src="https://user-images.githubusercontent.com/42339192/202336313-0d8379cf-734d-4709-9627-dba2f4dc76b1.png">

- After (Toggled on)
<img width="575" alt="Snipaste_2022-11-17_10-04-48" src="https://user-images.githubusercontent.com/42339192/202336325-4f2d4a59-3b5b-4e4b-9f46-bc2fff9511c8.png">

As you can see, it is not actually identical with the demo picture beside the option in preferences. Please consider working on this issue. Many thanks.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS

**Comment by MrAlex94** [comment]
You don't have enough tabs open. If you open some more, the `X` will eventually stop displaying

<img width="641" alt="image" src="https://user-images.githubusercontent.com/4728920/202405266-cc862474-3c16-4133-a56a-b29b54baf830.png">

**Comment by y2-Whyto** [comment]
> You don't have enough tabs open. If you open some more, the `X` will eventually stop displaying
> 
> <img alt="image" width="641" src="https://user-images.githubusercontent.com/4728920/202405266-cc862474-3c16-4133-a56a-b29b54baf830.png">

Thanks. I tried again as the way you mentioned, and it actually worked.

Moreover, as it's currently for "many" tabs which fill up the tab bar, maybe you could kindly consider bringing this feature to any number of tabs? Or just provide an option for that? Some users maybe simply want a "cleaner" tab look (with no close button when not hovered on, for other tabs)

I'll open another issue for this feature request.
