### ISSUE TITLE
Add Enable/Disable top gap in fullscreen window mode 

### ISSUE THREAD

**Issue by TooManySugar** [MrAlex94/Waterfox#2902]
After update v5.1 at least on Windows using Waterfox theme in fullscreen window mode appeared gap above tabs menu and window control buttons. It would be great if this gap could be switched in new "Look & Feel" section

**Comment by TankedThomas** [comment]
Same issue here, but it looks more like a bug to me than intentional. It's not mentioned in the G5.1 changelog nor does there appear to be an option for it anywhere.

**Comment by GTR8000** [comment]
Refer to my thread on Reddit:  https://www.reddit.com/r/waterfox/comments/yvcrch/g51_extrawasted_space_at_top_of_browser

If you're not into Reddit, the fix is to set **userChrome.compatibility.os.windows_maximized** to **FALSE** in about:config

**Comment by TooManySugar** [comment]
Fixed at 2ecc7288e8183fa2d6c7b64567c0f7c35ca97f1f and in G5.1.1 release
