### ISSUE TITLE
enabling 'layout.css.has-selector.enabled' does not result in being able to use ":has"-selector

### ISSUE THREAD

**Issue by gpunktschmitz** [MrAlex94/Waterfox#2919]
### What happened?

I tried enabling the setting 'layout.css.has-selector.enabled' but it does not result in being able to use the ":has"-selector.
I'm running G5.1 on Linux.

I enabled the option in Firefox 107.0.1 where it works as expected.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

**Comment by thunderstone135** [comment]
The **[:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)** pseudo class selector was introduced in Firefox 103.
Waterfox is based on Firefox ESR 102. It's mentioned in **[Docs](https://www.waterfox.net/docs/releases/G5.0)** and in **[Twitter](https://twitter.com/Waterfoxproject/status/1539215644511588360)**.

**Comment by gpunktschmitz** [comment]
my bad. thank you!

**Comment by krystian3w** [comment]
>  where it works as expected.

But code still need fixes:

- no support dynamic change style e.g.: https://ameshkov.github.io/web/watchattr.html, https://codepen.io/jensimmons/pen/BarwGpV
- no support checking children / neighbours (`:has(>`, `:has(~` and `:has(+`).
- race condition on hide ~100 elements in one time, so few elements are not stylized
- fail match elements under matched e.g.: https://codepen.io/css4-selectors-com/pen/dRBLaK, https://codepen.io/jensimmons/pen/BaYoWea
