### ISSUE TITLE
Waterfox is identified as old Firefox

### ISSUE THREAD

**Issue by donsenilo1968** [MrAlex94/Waterfox#2952]
Some websites identifies Waterfox as an old Version of Firefox and prevent access.

**Comment by MrAlex94** [comment]
Hi!

That's on purpose - Waterfox identifies as the latest ESR. If we keep the Waterfox UA, websites break completely - if we give the latest Firefox UA, we may not support all features that websites would expect.

Only workaround is to use a [user agent](https://addons.mozilla.org/en-US/firefox/search/?q=user%20agent) add-on.
