### ISSUE TITLE
Flatpak for Waterfox

### ISSUE THREAD

**Issue by pascalrrr** [MrAlex94/Waterfox#2977]
**Is your feature request related to a problem? Please describe.**
The Waterfox Tarball for linux is a little cumbersome to use for most people, and with Linux becoming more popular (3%!), it would be ideal for the end user to install Waterfox as a Flatpak. 

**Describe the solution you'd like**
I am aware that the primary maintainer of this project would be too busy to maintain a Flatpak, so I would volunteer to publish and update a Flatpak for Flathub, the central repository of Flatpaks.

**Describe alternatives you've considered**
I have made a Flatpak that I didn't publish on Flathub, but it is inconvenient to find and install without a repository.

**Additional context**
I have already created a pull request on the Flathub repository, and I've done most of the hard work that's necessary. It contains the latest binary version of Waterfox for Linux, and has some screenshots and description elements. See the PR [here](https://github.com/flathub/flathub/pull/3909)

**Comment by hawkeye116477** [comment]
See https://github.com/WaterfoxCo/Waterfox/issues/2566#issuecomment-1049761025.

**Comment by pascalrrr** [comment]
I would be willing to maintain it for Flathub, I am aware the team wouldn't be able to maintain it. I just need adequate  permission from a contributor or domain manager to publish it. I would also be willing to upstream anything I add or change.

**Comment by nl255** [comment]
I would love to see this given that the steam deck relies on flatpaks in desktop mode.

**Comment by pascalrrr** [comment]
Don't personally have a Steam Deck, but I agree that this would be very helpful. I'm working with the Flathub contributors on this but at the current time I'm waiting for approval on the Waterfox team's part.

**Comment by Darin755** [comment]
I made this request last year

https://github.com/WaterfoxCo/Waterfox/issues/2616

**Comment by rabbit-stew** [comment]
A flatpak would be incredibly helpful. I've seen this requested many times for Waterfox.

**Comment by pascalrrr** [comment]
This issue is resolved, err kinda. I've got the app on flathub! You can now download Waterfox via your favorite Linux app store, although because this was done independently, it doesn't say so on the website. Will try to get into contact with Alex Kontos to get everything settled and up on the Waterfox site. See [on Flathub here!](https://flathub.org/apps/details/net.waterfox.waterfox)
