### ISSUE TITLE
NVIDIA Background App Max Framerate affects browser fps at all times

### ISSUE THREAD

**Issue by GloryOfNight** [MrAlex94/Waterfox#2979]
### What happened?

Setting up Background Application Max Frame Rate in NVIDIA Control Panel makes browser render at "background frame rate" all the time. 

if  Background Application Max Frame Rate - set to 20 fps. Browser would be much slower visually, even if active on screen.

### Reproducible? No

- [x] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

**Comment by GloryOfNight** [comment]
Firefox seems to be not affected by that issue.

**Comment by goodusername123** [comment]
This sounds very much like a driver profile issue as "waterfox.exe" is not recognized by the nvidia gpu drivers while "firefox.exe" has it's own profile.

I would recommend downloading this: https://github.com/Orbmu2k/nvidiaProfileInspector
and adding "**waterfox.exe**" to the "**Mozilla Firefox**" profile which should solve the issue you are having.

**Comment by GloryOfNight** [comment]
Thanks!
