### ISSUE TITLE
Hide URL Bar and Tabbar when fullscreen

### ISSUE THREAD

**Issue by aschroeder27** [MrAlex94/Waterfox#3001]
**Is your feature request related to a problem? Please describe.**
When presenting a website, I often want to hide all ui elements and view the website in actual fullscreen. But when toggling on fullscreen on macOS, the URL Bar and Tabbar stays visible.

**Describe the solution you'd like**
A solution to this problem would be to hide the ui elements or add an option to hide the ui elements.

**Comment by wtfiwinomgs** [comment]
@MrAlex94 I honestly dont think this is the same issue, the URL/tabbar OP mentioned is part of waterfox is it not? where as window taskbar showing when going into full screen video is involving windows, and doesn't happen on any of the prior version of windows, which make this a bug rather than feature request.

**Comment by MrAlex94** [comment]
> @MrAlex94 I honestly dont think this is the same issue, the URL/tabbar OP mentioned is part of waterfox is it not? where as window taskbar showing when going into full screen video is involving windows, and doesn't happen on any of the prior version of windows, which make this a bug rather than feature request.

Oh yes, you are correct - I'll re-open one of the previous ones. Apologies, too many tabs open 😅

**Comment by kopach** [comment]
hi @aschroeder27, I was also looking for this feature and found it. Basically, when in full screen - right click Tool bar (in any place, even on tab) and you'll find there "Hide Toolbars" option there
![image](https://github.com/WaterfoxCo/Waterfox/assets/8749624/8e164d12-67eb-44ac-bf03-125694553eac)

Found some video demonstrating this https://www.youtube.com/watch?v=GHgJFKM6tSQ
as well as support thread https://support.mozilla.org/en-US/questions/1172447

**Comment by aschroeder27** [comment]
Oh wow! Sorry, that I'm a bit late on this one but that indeed resolved this issue! thanks ;)
Have a nice holiday
