### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by x011** [MrAlex94/Waterfox#3007]
### What happened?

No replies to bug reports for long time already. Is this project dead?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Linux, macOS, Windows

**Comment by MrAlex94** [comment]
No, the project isn’t dead!

A lot of roadmapping and a lot of the bugs reported are either difficult to reproduce or not experience very often by very many people.

Security updates and the likes are the most important thing for the moment, which happen frequently and on time :-)

**Comment by x011** [comment]
Not everyone report bugs, but it doesn't mean these bugs don't affect many people. Apart from privacy features, Firefox experience is overall better than Waterfox. For example, automatic password filling, for Gmail, among other websites, isn't working properly.
