### ISSUE TITLE
Not function streaming netflix error  Waterfox G5.1.5

### ISSUE THREAD

**Issue by ivantor69** [MrAlex94/Waterfox#3022]
### What happened?

A bug happened!
![immagine](https://user-images.githubusercontent.com/5076311/234106363-c6fb52c2-5e43-49a0-a6a2-e954beb43b87.png)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

**Comment by mikeloeven** [comment]
This often happens when wide vine is updated. I am wondering if there is something waterfox can do to allow the widevine plugin to updated independently of the browser version so that this does not keep happening

**Comment by MrAlex94** [comment]
I have managed to fix this, so please keep an eye out on the next few updates (can’t confirm which exact one, but the moment it’s ready you’ll get it straight away). Just waiting for certain approvals and we should be good to go 👍

**Comment by MrAlex94** [comment]
This has now been fixed on Windows in G5.1.7. Please re-open if there are any issues.
