### ISSUE TITLE
Update G5.1.6 of Waterfox has broken video playback on Crunchyroll.

### ISSUE THREAD

**Issue by Haiyami** [MrAlex94/Waterfox#3040]
### What happened?

A bug happened! I can no longer play any videos on Crunchyroll after updating to version G.5.1.6. I have tried clearing the cookies and cache, uninstall and reinstall the browser and disable all the extensions but nothing is working.  DRM has also been checked.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
CODE: SHAK-6007-GENERIC
```

**Comment by DigiEggz** [comment]
A friend mentioned the same issue, including Netflix. The Netflix error code is: F7121-1331
It may be related to the problem mentioned a few weeks ago [here](https://www.reddit.com/r/waterfox/comments/12q4c9z/netflix_issue_f71211331/).

**Comment by Kaip0** [comment]
I have the same issue, I've narrowed it down to being a problem with the widevinecdm.dll in \AppData\Roaming\Waterfox\Profiles\<username>\gmp-widevinecdm\4.10.2391.0

I have fixed the issue by replacing widevinecdm.dll in the waterfox folder with the one from Edge's own ( \Program Files (x86)\Microsoft\Edge\Application\113.0.1774.42\WidevineCdm\_platform_specific\win_x64 )

[It appears to be the same solution found here on reddit regarding another widevine issue for netflix](https://www.reddit.com/r/waterfox/comments/r5yt91/netflix_just_broke/) (u/tip4toe commented on the thread the same above solution, only he chose to copy the widevinecdm.dll from chrome).

**Comment by DigiEggz** [comment]
Thank you for sharing a solution! Widevine is usually the culprit, more often than not.

**Comment by mikeloeven** [comment]
Can confirm widevine is still broken as of last update

**Comment by Haiyami** [comment]
> I have the same issue, I've narrowed it down to being a problem with the widevinecdm.dll in \AppData\Roaming\Waterfox\Profiles<username>\gmp-widevinecdm\4.10.2391.0
> 
> I have fixed the issue by replacing widevinecdm.dll in the waterfox folder with the one from Edge's own ( \Program Files (x86)\Microsoft\Edge\Application\113.0.1774.42\WidevineCdm_platform_specific\win_x64 )
> 
> [It appears to be the same solution found here on reddit regarding another widevine issue for netflix](https://www.reddit.com/r/waterfox/comments/r5yt91/netflix_just_broke/) (u/tip4toe commented on the thread the same above solution, only he chose to copy the widevinecdm.dll from chrome).

I tried this and it doesn't work. Firefox and Waterfox handle their directories a bit differently. Waterfox's widevine contains a License.txt file, a manifest.json file a widevinecdm.dll file, a widevinecdm.dll.lib file and a widevinecdm.dll.sig file. Unfortuantely just replacing the widevinecdm.dll file will not resolve the issue.

**Comment by MrAlex94** [comment]
Hi all!

FINALLY, after years, DRM is now fully supported. Currently I've got Windows working, and macOS will follow suit shortly. I've done a soft release of G5.1.7 which is now available for [download](https://cdn1.waterfox.net/waterfox/releases/G5.1.7/WINNT_x86_64/Waterfox%20Setup%20G5.1.7.exe).

I'll close this issue for now, but please re-open if you have issues.

**Comment by Haiyami** [comment]
Do you have an exe to update the current version of waterfox. This exe seems to want to do a fresh install.

**Comment by MrAlex94** [comment]
> Do you have an exe to update the current version of waterfox. This exe seems to want to do a fresh install.

It should upgrade if it points to an existing install directory?
