### ISSUE TITLE
Signature Verification error 

### ISSUE THREAD

**Issue by ykc21e8** [MrAlex94/Waterfox#3041]
### What happened?

I just want to know how to fix this in the future. 
![image](https://github.com/WaterfoxCo/Waterfox/assets/120526484/a8ceabb1-75c6-4183-a7e0-1aaf48327f2d)

Do I need to change the key, or just re-download?

I can't update anything because of this issue. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Err:7 http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_22.04  InRelease
  The following signatures were invalid: EXPKEYSIG 5E62D791625A271E home:hawkeye116477 OBS Project <home:hawkeye116477@build.opensuse.org>

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_22.04  InRelease: The following signatures were invalid: EXPKEYSIG 5E62D791625A271E home:hawkeye116477 OBS Project <home:hawkeye116477@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_22.04/InRelease  The following signatures were invalid: EXPKEYSIG 5E62D791625A271E home:hawkeye116477 OBS Project <home:hawkeye116477@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by MrAlex94** [comment]
@hawkeye116477

**Comment by hawkeye116477** [comment]
You need to remove GPG key and add it again. It's already explained at [pinned issues and discussions at my repo](https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/issues).

**Comment by ykc21e8** [comment]
Thanks I previously ignored this due to my lack of knowledge. 

For other beginners, you just have to replace the weblink with your version (e.g. https://download.opensuse.org/repositories/home:hawkeye116477:waterfox/Debian_9.0/Release.key) which you can identify from your output error when trying to update. Release the key, and follow it with sudo apt update. 

> You need to remove GPG key and add it again. It's already explained at [pinned issues and discussions at my repo](https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/issues).
