### ISSUE TITLE
Mozilla are going to stop to create Firefox for Windows 7, 8 and 8.1

### ISSUE THREAD

**Issue by JeanPaulLucien** [MrAlex94/Waterfox#3055]
As you know. Windows 10 has many telemetry. Mozilla knows about that. While I had not talking with Mozilla to ask stay a minimum Windows 7 support.
I suggest to continues to build Waterfox for Windows 7. 

In fact Windows users community requires a real independent browser.

P.S. I had an experience with Firefox 102 ESR. It's much worse than Firefox in the past.

**Comment by A0R-R0CKS** [comment]
Since new Firefox ESR is out that works with Windows 7 will you once again make a new release of Waterfox using the latest ESR?
102.12 64 Bit. I have Plugins I want to keep using and none of the newer Waterdox installs beyond G3.2.6....

**Comment by the-r3dacted** [comment]
I don't think this will be relevant for a while, but I've been tracking the commits.

Instead of making a list of commits I made a repo where I revert the respective commits and can be used as an example (don't use it as a base unless you want to be delayed by my schedule)
https://github.com/Eclipse-Community/gecko-dev-win7

**Comment by JeanPaulLucien** [comment]
> https://github.com/Eclipse-Community/gecko-dev-win7

Not found.

**Comment by the-r3dacted** [comment]
Yeah I was working on it but GitHub fucked it over by duplicating every commit I made and I just gave up. If this makes it so I need to move to Linux I'll just fucking cope and do it.

**Comment by JeanPaulLucien** [comment]
> 102.12 64 Bit

Firefox 102 ESR has many issues. It's like an alpha or beta. I was disappointed when I used this.

**Comment by the-r3dacted** [comment]
The 115 Beta is so much better, but there's a few bugs I've been meaning to report.

**Comment by JeanPaulLucien** [comment]
I ask to save to create Waterfox for Windows 7. My migration will be finished and Waterfox will be the general browser for me.

**Comment by MrAlex94** [comment]
When the next ESR rolls around in a years time, I doubt we'll be able to revert the many changes made by Mozilla, unfortunately.

For now though, G6 will keep support.

**Comment by the-r3dacted** [comment]
> > https://github.com/Eclipse-Community/gecko-dev-win7
> 
> Not found.

Well it is back, and there is a release now.
https://github.com/Eclipse-Community/r3dfox
