### ISSUE TITLE
Google Images search results crashes tab.

### ISSUE THREAD

**Issue by RobertZenz** [MrAlex94/Waterfox#3063]
### What happened?

Visiting Google Images search results crashes the tab 99% of the time (depends on results?). For example:

    https://www.google.com/search?q=waterfall&tbm=isch

The page loads and crashes after having been loaded, which leads me to believe it might be related to JavaScript. Disabling JavaScript will make the page load, however, it is basically a completely different page without it. This did not happen some weeks ago and it also happens with a new/blank profile.

Unfortunately I currently ain't got a recent version of Firefox to verify nor am I able to find any meaningful logs during the crash. I'll happily provide you with more information if you tell me where I can find or how I can procure it.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Linux

**Comment by RobertZenz** [comment]
Of course I find a relevant bug report *after* writing this issue: [Mozilla Bugzilla #1839669](https://bugzilla.mozilla.org/show_bug.cgi?id=1839669)

So, seems like something that also affects Firefox.

**Comment by MrAlex94** [comment]
No worries! This should be in G5.1.9 which has just soft released - with auto-update out tomorrow.

**Comment by RobertZenz** [comment]
Can confirm that it is fixed with G5.1.9.
