### ISSUE TITLE
Addon Installation Error: "Unsupported manifest version: 3"

### ISSUE THREAD

**Issue by y2-Whyto** [MrAlex94/Waterfox#3066]
### What happened?

Some addons on Firefox add-ons website is not supported, saying "You need an updated version of Firefox for this extension". My example: https://addons.mozilla.org/en-US/firefox/addon/cubox/

I manually downloaded the `.xpi` file and tried to install it from `about:debugging#/runtime/this-firefox`, however when I temporarily loaded it, there was an error saying "Unsupported manifest version: 3".

I don't know what has led to this circumstance. Are there chances that this could be fixed soon?

I'm currently using G5.1.9. I tried on latest Firefox (version 115.0.2 by now), and it worked flawlessly.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

macOS

**Comment by MrAlex94** [comment]
You can go to `about:config`, search for `extensions.manifestV3.enabled` and toggle it to `true`. That should let you install it 👍. Bare in mind, not all MV3 APIs are supported in G5, if you find that not everything works properly.

**Comment by y2-Whyto** [comment]
> You can go to `about:config`, search for `extensions.manifestV3.enabled` and toggle it to `true`. That should let you install it 👍. Bare in mind, not all MV3 APIs are supported in G5, if you find that not everything works properly.

Thank you for your reply ❤️️ Though it didn't work out for this plugin I posted even with that config enabled.

So I'm wondering what's the reason of this? Or could you please tell me when this manifest V3 feature could get fully supported? Is it possible on G6?
