### ISSUE TITLE
Enable ECS EDNS Client Subnet in DNS Queries

### ISSUE THREAD

**Issue by trimechee** [MrAlex94/Waterfox#3090]
Hello, i use the great Quad9 dns that block malware and even the bad crypto-mining and i need no more antivirus ! and Quad9 has a version with ECS EDNS Client Subnet enabled, and and then, the dns becomes more faster, and i discover ECS EDNS Client Subnet is sadly not enabled by default in web browser, it will be great to add option to enable quickly ECS EDNS Client Subnet, tahnk you so much :)

**Comment by yokoffing** [comment]
https://github.com/yokoffing/Betterfox/blob/29590403f513190709d25a61aa221d5659508476/Securefox.js#L638-L645

**Comment by yokoffing** [comment]
```
// PREF: EDNS Client Subnet (ECS)
// [WARNING] In some circumstances, this may result in suboptimal routing
// between CDN origins and end users [2].
// [1] https://en.wikipedia.org/wiki/EDNS_Client_Subnet
// [2] https://www.quad9.net/support/faq/#edns
// [3] https://datatracker.ietf.org/doc/html/rfc7871
//user_pref("network.trr.disable-ECS", true); // DEFAULT
```

https://github.com/yokoffing/Betterfox/blob/c797366efb0468df0e877af34eca5445cef5a8e2/Securefox.js#L645-L650

**Comment by trimechee** [comment]
Thank you my friend for these precious informations :) @yokoffing

**Comment by trimechee** [comment]
Hello @yokoffing  : I read that activating ECS makes it possible to circumvent geolocation and censorship of ip addresses based on geopgraphical location....apparently the old ECS is replaced by EDNS ....i think activating EDNS is one of the most great functions to bypass surveillance and censorship and we would no longer need vpn, the ISP and the state can no longer monitor us apparently

so what do you think about my discover ? is that really tre and it really works please ?

"Firefox – Blind your ISP & keep your data safe!

Today I will guide you How to Blind your ISP & keep your data safe!

Protect your privacy. Defend yourself against network surveillance
and traffic analysis and stop your isp from spying on you.

It’s simple and can be done via Firefox.
When you enable this, you don’t need a VPN to browse blocked websites,
It will unlock all domains worldwide.

about:config
esni.enabled
trr.mode
5) Search for “trr.mode”

Double click on it or right click and select Modify.

Set network.trr.mode to 2 to make DNS Over HTTPS.
It will secure your connection and unlock all blocked domain names.

Enter 2 and Click OK!

Note: Try 2 first, if you get error, set trr.mode to 1."

i make new researches and it seems that ESNI becomes ECH 

Encrypted Client Hello: the future of ESNI in Firefox
https://blog.mozilla.org/security/2021/01/07/encrypted-client-hello-the-future-of-esni-in-firefox/

**Comment by trimechee** [comment]
@yokoffing I wish to use ECS EDNS in order to use cdn and my connexion become more faster ans stable  : 


"The owner of self-serve [web archiving](https://en.wikipedia.org/wiki/Web_archiving) tool [Archive.today](https://en.wikipedia.org/wiki/Archive.today) has expressed concern over [Cloudflare 1.1.1.1](https://en.wikipedia.org/wiki/1.1.1.1) not passing the contents of this field on to the authoritative DNS server for Archive.today, and has in response configured the site's resolver to consider Cloudflare DNS requests invalid—effectively blocking 1.1.1.1 from resolving the website DNS records.[[4]](https://en.wikipedia.org/wiki/EDNS_Client_Subnet#cite_note-archiveis-4)

The owner of the site believes 1.1.1.1 too often routes recursive DNS requests in a non-geographically-optimal way, causing poorer connectivity than if the feature was available at all times.[[4]](https://en.wikipedia.org/wiki/EDNS_Client_Subnet#cite_note-archiveis-4)

[Cloudflare](https://en.wikipedia.org/wiki/Cloudflare) CEO [Matthew Prince](https://en.wikipedia.org/wiki/Matthew_Prince) cited privacy concerns as reason for 1.1.1.1 to not support ECS."


https://en.wikipedia.org/wiki/EDNS_Client_Subnet

**Comment by MrAlex94** [comment]
This is now enabled in Waterfox by default in the latest G6 beta versions.

Coupled with DNS over Oblivious HTTP and it's quite the privacy advantage of using Waterfox 😉

**Comment by trimechee** [comment]
Great ! Thank you so much Mr @MrAlex94  for adding DNS over Oblivious HTTP :)
