### ISSUE TITLE
Disable Electrolysis multi-process to reduce ram and battery use

### ISSUE THREAD

**Issue by trimechee** [MrAlex94/Waterfox#3093]
Hello, some times we use an old and not powerful pc and we don't have much ram memory and firefox use Electrolysis multi-process browsing so it will be good if our so beloved Waterfox browser adds option to disable electrolysis to free up memory ram and save battery, I found this:
"Firefox automatically uses settings based on the computer's hardware specifications [1].

Adjusting these settings can be done in Preferences or by changing the dom.ipc.processCount value to 1-8 and browser.preferences.defaultPerformanceSettings.enabled to false manually in about:config.

However we may hope to manually adjust this setting to increase performance even further or decrease memory usage on low-end devices.

In this case the Content process limit for the current user has been increased to 4: "

https://wiki.archlinux.org/title/Firefox/Tweaks#Change_Performance_settings

so my request please is to add an option to quickly set : " Content process limit" to 1 without digging into the internal settings of browser about:config because firefox offered this option to choose the number of Content process limit but afterwards, firefox removed this option sadly :(

i tried to set "browser.tabs.remote.autostart" to false but i checked in task manager, Electrolysis multi-process seems not to be disabled despite all these changes :(

**Comment by MrAlex94** [comment]
Unfortunately, this isn't something I plan on enabling on Waterfox.

Disabling electrolysis (e10s) or fission would make you lose out on substantial security, stability, and performance benefits. 

I don't even think it'll even be technically possible in the future.

You should be able to set the environment variable `MOZ_FORCE_DISABLE_E10S=1` though when launching Waterfox, that will disable it.

**Comment by trimechee** [comment]
I understand ! Mr @MrAlex94  thank you so much for your help and these precious informations :)
