### ISSUE TITLE
MPEG-DASH and HEVC/H.265 support

### ISSUE THREAD

**Issue by trimechee** [MrAlex94/Waterfox#3094]
Hello, may be these features may help to have even more smooth playback compared to many another web browsers that does not have these options enabled : 

Experimental MPEG-DASH support

https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) support

and

HEVC/H.265 support on Linux and Windows.

It will be great to have option to activate these features, thank you :)

**Comment by MrAlex94** [comment]
Unfortunately, it's not really feasible both from a technical or financial perspective. 

For the former, I just don't have the technical expertise for it, and it would be a massive project to take on.

For the latter, there are lots of licensing issues with MPEG-DASH and H265 - which makes it quite expensive to license overall. 

It's sad, but the reason why codecs such as AV1 have come about to compete with them.

**Comment by trimechee** [comment]
I understand , thank you ! 💯 

I read that Waterfox Classic and Waterfox Current support for Advanced Video Coding (H.264) and High Efficiency Video Coding (HEVC) (H.265)

https://www.reddit.com/r/waterfox/comments/dqnkvq/waterfox_classic_and_waterfox_current_support_for/

https://www.reddit.com/r/waterfox/comments/dq6i2w/can_waterfox_support_h264_above_level_51/

**Comment by VixiKitsune** [comment]
Firefox added hardware HEVC decoding using the OS's drivers in version 120 back in November.
Most Chromium browsers and Safari also have HEVC support now too.
Hardware HEVC decoding has been common in computers and smartphones for a while. Absolutely no reason for AVC to exist anymore

I wanted to try Waterfox the other week, but being behind on this feature makes it a hard no for me as I'm using HEVC in my own web project.

**Comment by trimechee** [comment]
Interesting ! Thank you :)

**Comment by Squall-Leonhart** [comment]
> Unfortunately, it's not really feasible both from a technical or financial perspective.

HEVC support can be implemented on the Media Foundation codec supplied by the system (as installed on MS Store)
*You* aren't required to license it for use via WMF

> I wanted to try Waterfox the other week, but being behind on this feature makes it a hard no for me as I'm using HEVC in my own web project.

Set media.wmf.hevc.enabled to 1 and have the [HEVC extension installed](https://apps.microsoft.com/detail/9nmzlz57r3t7?hl=en-US&gl=US)

**Comment by Squall-Leonhart** [comment]
> I wanted to try Waterfox the other week, but being behind on this feature makes it a hard no for me as I'm using HEVC in my own web project.

Set media.wmf.hevc.enabled to 1 and have the [HEVC extension installed](https://apps.microsoft.com/detail/9nmzlz57r3t7?hl=en-US&gl=US)

**Comment by trimechee** [comment]
Very instructive and interesting !! Thanks a lot @Squall-Leonhart :) 💯

**Comment by VixiKitsune** [comment]
> Set media.wmf.hevc.enabled to 1 and have the [HEVC extension installed](https://apps.microsoft.com/detail/9nmzlz57r3t7?hl=en-US&gl=US)

This has been working since FF 128 Was implimented into Waterfox 6.5 TY

**Comment by trimechee** [comment]
Yes, it seems firefox had implemented recently hardware acceleratin for HEVC....

**Comment by ugjka** [comment]
> Yes, it seems firefox had implemented recently hardware acceleratin for HEVC....

This avoids licensing issues as it is the hardware that's doing the decoding, i suppose.

On linux they use vaapi for that

**Comment by VixiKitsune** [comment]
> > Yes, it seems firefox had implemented recently hardware acceleratin for HEVC....
> 
> This avoids licensing issues as it is the hardware that's doing the decoding, i suppose.
> 
> On linux they use vaapi for that

Not yet implimented in Firefox for Linux.

I plan to take a look at contributing to Firefox when I have time.

**Comment by ugjka** [comment]
> > > Yes, it seems firefox had implemented recently hardware acceleratin for HEVC....
> > 
> > 
> > This avoids licensing issues as it is the hardware that's doing the decoding, i suppose.
> > On linux they use vaapi for that
> 
> Not yet implimented in Firefox for Linux.
> 
> I plan to take a look at contributing to Firefox when I have time.

> https://www.mozilla.org/en-US/firefox/137.0/releasenotes/
> Support HEVC playback on Linux.

I'm literally on FF now and can play 8K 60fps HEVC videos

**Comment by VixiKitsune** [comment]
> > > > Yes, it seems firefox had implemented recently hardware acceleratin for HEVC....
> > > 
> > > 
> > > This avoids licensing issues as it is the hardware that's doing the decoding, i suppose.
> > > On linux they use vaapi for that
> > 
> > 
> > Not yet implimented in Firefox for Linux.
> > I plan to take a look at contributing to Firefox when I have time.
> 
> > https://www.mozilla.org/en-US/firefox/137.0/releasenotes/
> > Support HEVC playback on Linux.
> 
> I'm literally on FF now and can play 8K 60fps HEVC videos

Oh nice! That's one less thing on my to do list! 😄
