### ISSUE TITLE
Open all bookmarks is broken in G6

### ISSUE THREAD

**Issue by the-r3dacted** [MrAlex94/Waterfox#3097]
### What happened?

Going to a bookmark folder, right clicking, and selecting open all bookmarks just does nothing. No bookmarks get opened.

This doesn't seem to be an issue on Firefox 115.0.3esr

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Thanks for the report, fixed in the above commit.
