### ISSUE TITLE
Widevine is not available in Waterfox

### ISSUE THREAD

**Issue by softvision-raul-bucata** [MrAlex94/Waterfox#3105]
### What happened?

1. Navigate to: about:addons
2. Click on the "Plugins" tab.
3. Observe the result.

**Expected result:**
The widevine plugin is available.

**Actual result:**
The plugin is missing.

**Notes:**
Not reproducible using Firefox.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
If this is for macOS, it's a known issue. Windows and Linux (starting in G6) now both support it fully.
