### ISSUE TITLE
SHA512 files to verify integrity are not provided

### ISSUE THREAD

**Issue by Traneptora** [MrAlex94/Waterfox#3107]
### What happened?

The website https://www.waterfox.net/download/ provides download links and provides instructions to make sure you verify the integrity of the files. The site explains the following:

> It is essential that you verify the integrity of the downloaded files using the SHA signatures. Most operating systems support the `shasum` command. Download the accompanying .sha512 file and check the contents of its file using cat. Compare that value to the output of shasum.

However, there's no link to the accompanying `.sha512` file, and it's not provided inline either. Appending `.sha512` to the download URL also does not work (it returns 404).

The download URL is: https://cdn1.waterfox.net/waterfox/releases/G5.1.10/Linux_x86_64/waterfox-G5.1.10.tar.bz2
This returns 404: https://cdn1.waterfox.net/waterfox/releases/G5.1.10/Linux_x86_64/waterfox-G5.1.10.tar.bz2.sha512

I'm assuming the link should not 404, but as it does, it's not immediately obvious how one should obtain the sha512sum. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
leo@gauss ~ :) $ curl -I 'https://cdn1.waterfox.net/waterfox/releases/G5.1.10/Linux_x86_64/waterfox-G5.1.10.tar.bz2'
HTTP/2 200 
date: Fri, 04 Aug 2023 20:12:55 GMT
content-type: application/x-bzip
content-length: 85825044
accept-ranges: bytes
cache-control: max-age=86400
etag: "1f6ef6a55a024393f54004c444f0c6c6"
last-modified: Tue, 01 Aug 2023 10:17:03 GMT
server: cloudflare
cf-ray: 7f19753d0bde2a24-ORD
alt-svc: h3=":443"; ma=86400

leo@gauss ~ :) $ curl -I 'https://cdn1.waterfox.net/waterfox/releases/G5.1.10/Linux_x86_64/waterfox-G5.1.10.tar.bz2.sha512'
HTTP/2 404 
date: Fri, 04 Aug 2023 20:13:00 GMT
content-type: text/plain;charset=UTF-8
content-length: 14
server: cloudflare
cf-ray: 7f19755ada0a62d6-ORD
alt-svc: h3=":443"; ma=86400
```

**Comment by hawkeye116477** [comment]
In case of Linux, looks like it's something messed up and file with checksum has little different name than tarball => `https://cdn1.waterfox.net/waterfox/releases/G5.1.12/Linux_x86_64/waterfox-G5.1.12.en-US.linux-x86_64.tar.bz2.sha512` (added **.en-US.linux-x86_64**).

**Comment by MrAlex94** [comment]
This has been fixed, and .sha512 files will be `https://cdn1.waterfox.net/waterfox/releases/G6.0.1/Linux_x86_64/waterfox-G6.0.1.tar.bz2.sha512`, in the next release.
