### ISSUE TITLE
When launching and closing v.6 beta, "Program has stopped working" error message appears 

### ISSUE THREAD

**Issue by jg-github** [MrAlex94/Waterfox#3110]
### What happened?

An error window that says "program has stopped working" appears in the middle of the screen on my Windows 7 Pro x64 installation.
![Waterfox](https://github.com/WaterfoxCo/Waterfox/assets/3807863/84e64530-f0ca-48e2-a4e6-b5fa579f86e3)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by jg-github** [comment]
I forgot to mention that when I close the error window by clicking "x" in the top-right corner, it disappears and the program appears to work 100% correctly. 

I've been using the v6. beta as my default browser for over a week, and besides this anomaly, everything else seems to be fine. 

The v6. beta is generally quite fast in rendering web pages and so far deals with scripts just fine. If I may comment, it works smoothly on sites involving PayPal and on Amazon.de where Palew Moon chokes.

**Comment by MrAlex94** [comment]
Does this still happen with G6.0?

**Comment by jg-github** [comment]
No. It's fine now. Thanks for the great work with Waterfox!
