### ISSUE TITLE
G6 not rendering Weather Underground correctly

### ISSUE THREAD

**Issue by GTR8000** [MrAlex94/Waterfox#3111]
### What happened?

(I posted this on Reddit, but I'll copy it here to make sure it gets seen by the developers.)

I'm seeing an issue where the 10 day forecast graphs are not being rendered correctly in G6 vs G5.

Here are two screenshots, one from G5 and one from G6, showing the difference. You can see all of those ugly lines in the G6 screenshot which should not be there.

URL is https://www.wunderground.com/forecast/KLGA

G5: https://ibb.co/BCdXP1Z

G6: https://ibb.co/Sxq3FXq

Tested in Firefox 116.0.2 and renders correctly.

PS - Please add G6 to the Version for these reports so we don't have to choose Other, thanks!

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by yokoffing** [comment]
I can reproduce the weird graph on G6 (macOS 11.7.8). It renders correctly on Firefox for me as well.

**Comment by MrAlex94** [comment]
Thanks, can reproduce this. Looks like `-funsafe-math-optimizations` is the root cause. Will remove and have this fixed for the next beta.

**Comment by GTR8000** [comment]
So, was this fixed in Beta 3 as mentioned two weeks ago? Issue is still open, so unclear.

**Comment by yokoffing** [comment]
Renders correctly in G6 Beta 3 now. We can close.
