### ISSUE TITLE
Add support for Array.prototype.findLastIndex()

### ISSUE THREAD

**Issue by aquierick** [MrAlex94/Waterfox#3115]
**Is your feature request related to a problem? Please describe.**
There are some pages that are breaking because they're using findLastIndex function, which is not supported by waterfox yet. This is already supported by Firefox.

**Describe the solution you'd like**
Add support for this function

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLastIndex

**Comment by yokoffing** [comment]
This was [built into Firefox 104+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLastIndex#browser_compatibility). Waterfox G5 is using Firefox 102 ESR, so it should be there when G6 (Firefox 115 ESR) is released.

**Comment by MrAlex94** [comment]
This will be in G6, which is currently in beta, as mentioned above.
