### ISSUE TITLE
6.0b1 and 6.0b2: no webpages load until a few-several hours have passed

### ISSUE THREAD

**Issue by jpuffsh** [MrAlex94/Waterfox#3118]
### What happened?

After every waterfox startup, go to any webpage (google, bing, youtube, etc). Simply nothing loads. Hourglass icon on the tab bar, so I hide the app for a few-several hours (approximate). When I unhide it, the tab has been loaded, and all webpages after that load as expected. After restarting waterfox, the issue re-emerges. Rinse and repeat. The rest of my browsers work just fine during this, so it's not an internet issue. Could it be macos firewall related? I'm not knowledgeable there. 

Waterfox 5.1.10 doesn't have this issue, tested just now. I haven't seen someone else have this 6.0 bug, so it's a bit odd. 
Out of 10 browsers I've been testing recently, waterfox 6.0 beta 1 and 2 are the only ones to have this issue across a span of their release timelines (probably has been a few wks, if not more). I have never had the chance to test this on macos ventura or before, so it's been on macos sonoma public builds (not developer builds). 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS

### (Potentially) Relevant log output (maybe better than nothing):

```shell
Via more settings -> browser console: 

services.settings: Ignoring preference override of remote settings server Utils.sys.mjs:69
services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment Utils.sys.mjs:70
1692058145214	addons.xpi	WARN	Checking /Applications/Waterfox.app/Contents/Resources/distribution/extensions for addons
Applying chrome://browser/content/overlays/tabfeatures.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:95:15
Applying chrome://browser/content/overlays/privatetab.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:95:15
Applying chrome://browser/content/overlays/statusbar.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:95:15
Key event not available on some keyboard layouts: key=“p” modifiers=“alt control” id=“newPrivateTab-key” browser.xhtml
Key event not available on some keyboard layouts: key=“t” modifiers=“alt control” id=“togglePrivateTab-key” browser.xhtml
Region.sys.mjs: Error fetching region Error: TIMEOUT
    _timeout resource://gre/modules/Region.sys.mjs:759
Region.sys.mjs:409:11
Region.sys.mjs: Failed to fetch region Error: TIMEOUT
    _getRegion resource://gre/modules/Region.sys.mjs:411
Region.sys.mjs:208:11
```

**Comment by the-r3dacted** [comment]
I've been dailying the browser since 6.0b1, and haven't seen this. Is it because of an old profile or extension?

**Comment by jpuffsh** [comment]
> I've been dailying the browser since 6.0b1, and haven't seen this. Is it because of an old profile or extension?

I've tried clean installing multiple times (which means deleting the "Application Support" files and such, via appcleaner.app). No extensions were on, no profiles, no mozilla sync, etc. I also don't have any vpn configurations installed, if that means anything.

**Comment by the-r3dacted** [comment]
Must be macOS related then, I use Windows.

**Comment by jpuffsh** [comment]
Issue is no longer present upon first impressions of 6.0b3
