### ISSUE TITLE
Remove the "Sign In" if I am not synced

### ISSUE THREAD

**Issue by trajano** [MrAlex94/Waterfox#3119]
**Is your feature request related to a problem? Please describe.**

It's a waste of space on the menu dropdown if I don't plan to use Firefox Sync.

**Describe the solution you'd like**

Just remove the button.  If we want to we can opt-in.

**Describe alternatives you've considered**

Ignoring the button

**Additional context**
![image](https://github.com/WaterfoxCo/Waterfox/assets/110627/7b3fa2d8-0735-49ab-a2cb-998553581309)

**Comment by trajano** [comment]
I am presuming it's removing something from https://github.com/WaterfoxCo/Waterfox/blob/future/browser/base/content/browser-sync.js

**Comment by MrAlex94** [comment]
If you go to `about:config`, look for `identity.fxaccounts.enabled` and toggle it to `false`, then restart the browser, it should remove all the references in the UI.

Please re-open if that's not the case, but it should work :-)

**Comment by trajano** [comment]
It works though it should really be the default.
