### ISSUE TITLE
Issue with download, upload speed

### ISSUE THREAD

**Issue by amackpro** [MrAlex94/Waterfox#3120]
### What happened?

currently i was uploading 2-3 gb files to google drive 
when used waterfox  wifi upload speed was max 1m/s 
meanwhile when used Microsoft edge it bumps up to 20m/s

i tried on latest and latest betas , issue is same

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by yokoffing** [comment]
![Screenshot 2023-08-21 at 11 51 11 PM](https://github.com/WaterfoxCo/Waterfox/assets/11689349/29e146f4-7f15-44a4-af85-07becefd0c36)

Fixed in Firefox 115, so this will be resolved in [Waterfox G6](https://github.com/WaterfoxCo/Waterfox/releases).

**Comment by MrAlex94** [comment]
Will close this, but feel free to re-open if the issue persists after upgrading to G6, when it releases.

**Comment by zeeid** [comment]
I have same issue ...
My Internet connection is 200Mbps Upload in Edge
but when i test upload in Waterfox G6.0.19 i got limit in 20-32Mbps
Please Fix it 

Thanks you @MrAlex94
