### ISSUE TITLE
G6.0b3 clicking url bar and pressing enter opens a new tab with your url or search

### ISSUE THREAD

**Issue by the-r3dacted** [MrAlex94/Waterfox#3122]
### What happened?

If on this page I clicked my URL bar, and pressed enter, it would open another of this page in a new tab. If I tried to do a search, it would open the search in a new tab. If I went to a URL, it would open the URL in a new tab, and so on.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by yokoffing** [comment]
Go to `about:config` and look up `browser.urlbar.openintab`. Change it to `false` to disable.

**Comment by the-r3dacted** [comment]
Well I fixed it, but why did G6 change that pref without any indication? It also appears to have changed some prefs relating to downloading too.

**Comment by jpuffsh** [comment]
> Well I fixed it, but why did G6 change that pref without any indication? It also appears to have changed some prefs relating to downloading too.

Following quote from the 6.0b3 release notes: "Waterfox's preferences have been gone through with a fine tooth comb, with a lot of assistance from yokoffing." So there's some rationale behind whatever was changed I guess. 

Edit: On second look, I just noticed that yokoffing is the founder of betterfox, in case you weren't aware.

**Comment by the-r3dacted** [comment]
I think I downloaded it so fast it didn't have the release notes at the time. Good to know that, but probably shouldn't have just done that on current installs at least without an informative page.

**Comment by the-r3dacted** [comment]
Another issue this caused, the referrer header got changed to only sent when clicking, this breaks PCPartPicker for example. Including Smart Referrer would be better.
