### ISSUE TITLE
Firefox UI Fix v8.0.0

### ISSUE THREAD

**Issue by thunderstone135** [MrAlex94/Waterfox#3125]
**Is your feature request related to a problem? Please describe.**
I just wanted to inform you that Firefox UI Fix v8.0.0 has been released.
I tested it on the latest Waterfox G6 Beta and it works fine.

**Describe the solution you'd like**
Please include it in the upcoming Beta releases if possible.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/9038cd1b013518e92c06554f14956cd422dc7672
