### ISSUE TITLE
G6.0 Beta 3 - no data in my router log

### ISSUE THREAD

**Issue by MDM-79** [MrAlex94/Waterfox#3126]
### What happened?

With G6.0 Beta 3 - no data in my router log, just a code message
Even "Clear" button on the page does not work.
But in Beta 2 or in the same time in Edge, A-OK
Had to go back to Beta 2...

![1](https://github.com/WaterfoxCo/Waterfox/assets/87946426/ffaa5682-18f6-4adc-8209-8900486f8e83)
![2](https://github.com/WaterfoxCo/Waterfox/assets/87946426/0fa39e3f-9c95-4325-90e8-a7d8503ba0bb)

### Reproducible?

- [x] I have tested this on - Edge

### Version

Beta 3

### What platform are you seeing the problem on?

Windows 10 x64

**Comment by MDM-79** [comment]
Hmmm, went back to beta 2, and again upgraded to Beta 3, and now it is OK..?

**Comment by MDM-79** [comment]
Other things seems to be broken too..
![3](https://github.com/WaterfoxCo/Waterfox/assets/87946426/864476d2-72d1-4300-b6cf-8c2348dba3f6)
![4](https://github.com/WaterfoxCo/Waterfox/assets/87946426/b2a09071-cb13-4e4f-911b-0787616b0e94)

**Comment by MrAlex94** [comment]
Could you to go about:config and find the following config options and toggle them to the values shown:

`network.cookie.sameSite.laxByDefault` → `false`
`network.cookie.sameSite.noneRequiresSecure` → `false`
`network.cookie.sameSite.schemeful` → `false`
`network.http.sendRefererHeader` → `2`

See if any of them make a difference?

**Comment by MDM-79** [comment]
I tried them one by one, and:
**network.http.sendRefererHeader → 2** (by mozzila _this_ is supposed to be the default..?)
Did the trick (without needing the first 3)!

But there are many other issues I noticed, mainly in the Settings; many option change on their own (from beta2 and previous), and some revert at each start: 
Play DRM-controlled content, Open previous windows and tabs, Zoom, Block dangerous downloads, Warn you about unwanted and uncommon software, History - Waterfox will, HTTP Referrer Header, Show search suggestions ahead of browsing history in address bar results.
Query OCSP responder servers to confirm the current validity of certificates - reverts to off always.

**Comment by MrAlex94** [comment]
Good to hear! Beta 4 will fix the issue then.

> Play DRM-controlled content, Open previous windows and tabs, Zoom, Block dangerous downloads, Warn you about unwanted and uncommon software, History - Waterfox will, HTTP Referrer Header, Show search suggestions ahead of browsing history in address bar results.
Query OCSP responder servers to confirm the current validity of certificates - reverts to off always.

Yes, the default pref values (ones you haven't changed yourself) have all been updated. OCSP has been disabled in favour of [CRLite](https://blog.mozilla.org/security/2020/01/21/crlite-part-3-speeding-up-secure-browsing/) :-)
HTTP Referrer Header is causing issues and will be set to the Firefox default as well.

**Comment by MDM-79** [comment]
Good job!
have been using Waterfox since day one (same with Firefox before) - yes I **am** _old_ enough... :)

Better remember to include the changes in the read-me, so no user gets puzzled, an reverts to now non-default, like me ;D
