### ISSUE TITLE
Slack won't be supported from September

### ISSUE THREAD

**Issue by nofishonfriday** [MrAlex94/Waterfox#3129]
### What happened?

<img width="789" alt="waterfox_slack" src="https://github.com/WaterfoxCo/Waterfox/assets/7658194/c6a9c081-58b0-4590-bbf6-9e964f4b9c74">

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Unfortunately a little early for G6, but you can upgrade to it now or wait for the release in the coming week or two.

**Comment by nofishonfriday** [comment]
Ah, if it's already handled in G6 (wasn't sure about it) that's fine.
Thanks.
