### ISSUE TITLE
Login cookies being blocked/lost on theguardian.com with G6.0b3

### ISSUE THREAD

**Issue by stu-carter** [MrAlex94/Waterfox#3130]
### What happened?

After signing in to www.theguardian.com with beta 3, any refresh of the page or clicking a link asks me to sign in again.  Not reproduceable on G6.0b2 with the same privacy settings.

Tried to change privacy tracking settings (custom->disable all) and add the website to the tracking exclusion list but no change.

Sign-on for the website first takes me to 'profile.theguardian.com' to sign-in and then back to 'www.theguardian.com'
Using the Dev tools, looks like around 5 cookies are missing when I return to 'www.theguardian.com' with beta3 vs beta2.

I tried it with another couple of websites but couldn't reproduce - the login session persisted as expected.

Thanks.  

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Could you to go `about:config` and find the following config options and toggle them to the values shown:

`network.cookie.sameSite.laxByDefault` → `false`
`network.cookie.sameSite.noneRequiresSecure` → `false`
`network.cookie.sameSite.schemeful` → `false`

Let me know if that makes any difference?

If it doesn't, _maybe_ the below will:

`network.http.sendRefererHeader` → `2`

Next beta should remedy the various issues people have been reporting with the prefs we've set.

**Comment by theQ23** [comment]
Not sure if the same but is related to cookies. kick.com i'm getting CSRF token mismatch when logging in. If I clear cookies I can get past the username and password part but the 2FA part I get the same token mismatch. Wasn't until the new beta release that I got these errors. Works fine in Firefox. I tried your tweaks above but no joy.

**Comment by stu-carter** [comment]
Thanks for the quick response @MrAlex94 .

The cookie options didn't work, but the `network.http.sendRefererHeader → 2` fixed it.

**Comment by MrAlex94** [comment]
Great! Beta 4 will remedy the issue then :-)
