### ISSUE TITLE
G5.1.11 Widevine broken on multiple streaming sites 

### ISSUE THREAD

**Issue by mikeloeven** [MrAlex94/Waterfox#3131]
### What happened?

As of updating to the current version of waterfox DRM playback is broken on several streaming sites confirmed on Netflix Crunchyroll and Amazon. re enabling DRM playback did not resolve the issue manually checking for plugin updates shows no updates for the plugin. Clearing cache cookies and deleting the wide-vine folder to force a re-download did not resolve the error still getting generic player failures 

Tested on most recent build of Firefox unable to reproduce issue only occurs on Waterfox

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Fixed in G5.1.12 which is being pushed live shortly :-)
