### ISSUE TITLE
Betterfox Fastfox by Default

### ISSUE THREAD

**Issue by golf1487** [MrAlex94/Waterfox#3134]
**Is your feature request related to a problem? Please describe.**
Waterfox is slow compared to FF Vanilla.

**Describe the solution you'd like**
[Betterfox Fasfox js all the time enabled by default](https://github.com/yokoffing/Betterfox/blob/esr115/Fastfox.js)

**Describe alternatives you've considered**
No alternative to Betterfox Fasfox as far as I know

**Additional context**
https://github.com/yokoffing/Betterfox

**Comment by MrAlex94** [comment]
The files aren't used directly, but I have been working with @yokoffing on this already and it's currently live in G6 Beta 3.

**Comment by golf1487** [comment]
@MrAlex94 is fastfox-type mad performance improvements coming by default in G6 release builds?

**Comment by yokoffing** [comment]
@golf1487 He already answered your question. Please stop spamming all the different browser repos.

**Comment by golf1487** [comment]
> @golf1487 He already answered your question. Please stop spamming all the different browser repos.

I'd like to know how @MrAlex94 is going to implement Fastfox-type mad performance tweaks starting from G6.
