### ISSUE TITLE
Chrome extensions not working in G6

### ISSUE THREAD

**Issue by HarukaMa** [MrAlex94/Waterfox#3140]
### What happened?

I bet you are already aware of this, but anyway.

Because of [this commit](https://github.com/WaterfoxCo/Waterfox/commit/a645de723e4e22c5f5a484fdaecf1a3b9696ab10), the chrome extension handler is not longer working as `osfile` has been removed. Personally tested on G6.0b4, but according to the commit time, this affects all G6 beta versions.

I was trying to cherry-pick the extension compatibility feature to latest vanilla firefox (not intended to redistribute, just personal use). 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux, macOS, Windows

**Comment by MrAlex94** [comment]
Thanks for this, helpful!
