### ISSUE TITLE
Add back the droplets

### ISSUE THREAD

**Issue by aaronliu0130** [MrAlex94/Waterfox#3143]
**Is your feature request related to a problem? Please describe.**
The new logo feels a bit too flat

**Describe the solution you'd like**
Add the little droplets on the top of the middle of the W back to the new logo

**Describe alternatives you've considered**
Use the old logo

**Additional context**
The changelogs state that the new logo is "popular" and I don't think so, it just feels less

![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/ae06a996-57cf-42b8-b9ff-b001abbb7208)
Here's a very awful mockup, to be clear I think the new logo's colors are good

**Comment by MrAlex94** [comment]
Not sure what version you're on? But since Beta 4, the "old" logo is in use. In reality, it's the currently logo.

**Comment by aaronliu0130** [comment]
Yes, but the changelog implies that the new logo will come back.
> A new logo has proven popular in general. There are some issues with it, which need fixing. While this occurs, builds will switch back to the old logo.

**Comment by MrAlex94** [comment]
I see - it's still being decided which way to go, but for now the "current" logo isn't going anywhere :-)
