### ISSUE TITLE
Waterfox G6.0b5 file version discrepancy

### ISSUE THREAD

**Issue by thunderstone135** [MrAlex94/Waterfox#3144]
### What happened?

I compared the latest (G6.0b5) and previous (G6.0b4) version of waterfox.exe and the result shows 👇

![Imgur](https://imgur.com/lFdjr1x.png)

Shouldn't both file show at least version 115?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by thunderstone135** [comment]
**Update:**

I compared the waterfox.exe of G5.1.13 and G6.0b5. They have different BuildID, but their file version is the same.

**Comment by MrAlex94** [comment]
How did you get the update for G6? Did you download an installer? There was an incorrect build of G6b5 pushed out for <20 minutes, which was fixed.

**Comment by MrAlex94** [comment]
I’ve tried to push out an update to anyone who has builds like that - have you received it?

**Comment by thunderstone135** [comment]
> How did you get the update for G6? Did you download an installer? There was an incorrect build of G6b5 pushed out for <20 minutes, which was fixed.

I got both G6 installers from the Waterfox Download and Github Release pages.

> I’ve tried to push out an update to anyone who has builds like that - have you received it?

Yep, it's good now.
