### ISSUE TITLE
Can't Download G6

### ISSUE THREAD

**Issue by thunderstone135** [MrAlex94/Waterfox#3151]
### What happened?

I tried to download from www.waterfox.net/en-US/download/, but the page just shows File Not Found.
The same goes for macOS and Linux. The previous versions seem to download just fine.
I also tried the update mechanism for G5.1.13 and G6.0b5, but it's not detecting any update.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by daniandtheweb** [comment]
That's not an issue. The release still hasn't been published.

**Comment by Traneptora** [comment]
It's officially the latest version on the website, and it's in releases on GitHub. How has it not been published?

**Comment by daniandtheweb** [comment]
The developer is probably preparing everything for the release. But if you can't download it he clearly still hasn't published it.

**Comment by thunderstone135** [comment]
> That's not an issue. The release still hasn't been published.

It is an issue because if a release was not published, then why is a download link showing in waterfox.net/download?

![Imgur](https://imgur.com/lTwz5BI.png)

As you can see in the screenshot, it is already released. Therefore, files should be available.
If no file is available, then there is no point showing download links.

> It's officially the latest version on the website, and it's in releases on GitHub. How has it not been published?

~I was talking about the links in waterfox.net/download (see screenshot above).~

~You are talking about these links 👇~
~https://github.com/WaterfoxCo/Waterfox/archive/refs/tags/G6.0.zip~
~https://github.com/WaterfoxCo/Waterfox/archive/refs/tags/G6.0.tar.gz~

~These links contain the source code of G6 and not the installer. Tools are needed to compile it.~

I see that you were replying to @DaniAndTheWeb. Ignore my comment.

> The developer is probably preparing everything for the release. But if you can't download it he clearly still hasn't published it.

If that's the case, then the links in waterfox.net/download should not be shown yet.
Seeing that there are links available, can only mean that G6 is already published.
Seeing that G6 is already published, can only mean that the installer for G6 is available.
Seeing that the installer for G6 is not available, can only mean that there is an issue.
Seeing that there is an issue, I decided to raise a ticket. Just simple logic.
That's why I'm wondering why you are carelessly deciding if a ticket raised is an issue or not.
How would you feel if you raised a ticket and other people told you that it's not an issue?

**Comment by thunderstone135** [comment]
Anyway, I just raised this ticket to notify @MrAlex94 that G6 files are not available.
Seeing that I'm able to download files now, can only mean that this issue is resolved.
