### ISSUE TITLE
new tabs everywhere

### ISSUE THREAD

**Issue by strotee** [MrAlex94/Waterfox#3153]
### What happened?

I recently downloaded/installed 6.0 and I noticed the browser isn't shy about opening new tabs. If I'm on a tab and click one of my bookmarks, it opens in a new tab. I'm thinking that's new, 5.1.13 opened the bookmark in the same tab (whether it was a new or already used tab). The only way that I've been able to stop it is to open a blank tab first and then I notice it opens in the same tab. 

Another time is when I click a link on a page, I expect the link to be opened in the same tab, not in a new tab.  _This appears fixed with my tinkering._

Is there some newly buried config that I need to set?

_Version dropdown in GitHub doesn't list 6.0._

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by FrogsInSpace** [comment]
Just wanted to report the same thing: 
Bookmarks now always open a new tab instead using the current tab

There is hope though :
Apparently the **browser.tabs.loadBookmarksInTabs** flag is inverted,
so to temporary fix the problem,  go to **about:config** and set **browser.tabs.loadBookmarksInTabs** to false 
=> problem solved until this issue gets fixed :)

**Comment by strotee** [comment]
Thanks, that worked.  @FrogsInSpace 👍

**Comment by phyco1991** [comment]
This is noted as fixed in G6.0.1 (https://www.waterfox.net/en-US/docs/releases/G6.0.1/) however after having installed it, the issue appears to still exist.

**Comment by reaper666735** [comment]
> This is noted as fixed in G6.0.1 (https://www.waterfox.net/en-US/docs/releases/G6.0.1/) however after having installed it, the issue appears to still exist.

i can confirm this is still not fixed in 6.0.1 i had to use the about:config "fix", you might want to re-add on the todo list for 6.0.2  ;p

**Comment by MrAlex94** [comment]
In G6.0.1 or later, if it's not working, could you let me know what the value of `loadBookmarksInTabs` is?

**Comment by phyco1991** [comment]
> In G6.0.1 or later, if it's not working, could you let me know what the value of `loadBookmarksInTabs` is?

Mine is set as true

**Comment by MrAlex94** [comment]
Thanks, I've double checked in G6.0.3 that is building as we speak, and the pref isn't set at all.

Please re-open if you still have the issue when the update is released.
