### ISSUE TITLE
G6 & userChrome.css support

### ISSUE THREAD

**Issue by slumbergod** [MrAlex94/Waterfox#3154]
### What happened?

Forgive me for posting here if it is not the right place. With the website update I can no longer find the places I used to post (forum/blog comments).

Yesterday I manually installed G6 in Manjaro linux. Upon starting my vertical bookmarks had disappeared. I have been using userchrome.css to arrange bookmark icons vertically without text. It seemed to break for me with G6. I just wondered if G6 has made changes to support for userchrome. As soon as I removed the G6 folder and reverted back to G5 the bookmarks appeared again correctly.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

**Comment by phyco1991** [comment]
CSS customisation is supported exactly the same as other versions, but some of the the element names have been updated which would explain why your existing code is no longer working properly. If you obtained the code online (i.e. from somewhere like https://github.com/MrOtherGuy/firefox-csshacks) and someone has updated it for Firefox 112 or later, that should work in G6.0
