### ISSUE TITLE
Not getting the update to G6 from beta (G6.0b5)

### ISSUE THREAD

**Issue by ibeladi-mrsool** [MrAlex94/Waterfox#3157]
### What happened?

Whenever I check for newer versions within the browser, it tells me that I am using the latest version.
I am using G6.0b5 (64-bit)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Linux

**Comment by gerov1** [comment]
Also not getting update from G5.1.13 (64-bit) on Windows.

**Comment by MrAlex94** [comment]
Just pushed the update to Beta today, and G5 should receive it the next day or two.
