### ISSUE TITLE
Video Link does not load.

### ISSUE THREAD

**Issue by HUD199** [MrAlex94/Waterfox#3158]
### What happened?

A bug happened!

Platform: Cumulative Update for Windows 11 Insider Preview (10.0.22631.2338) (KB5030305)

Page loads in Brave and Chrome. Partially loads in Waterfox and Firefox. Omits critical embedded video link.
https://tranzactcard.com/?refID=816357

Embedded Video Link does not appear on either Waterfox or Firefox. Does work on Brave (Chrome open source)
![Waterfox 2023-09-23_16-11-55](https://github.com/WaterfoxCo/Waterfox/assets/62719258/b9adcb52-8839-4c25-9d94-6bd758e113c1)
![Firefox 2023-09-23_16-30-29](https://github.com/WaterfoxCo/Waterfox/assets/62719258/f9eabdd4-9c92-481e-836a-43f4d9a352d
![Brave 2023-09-23_16-16-31](https://github.com/WaterfoxCo/Waterfox/assets/62719258/4b7b91e8-e59e-4af2-ad6a-9ad02030aeed)
4)
![Chrome 2023-09-23_16-36-59](https://github.com/WaterfoxCo/Waterfox/assets/62719258/ccef62f4-7206-42d5-80b8-4dc2a08e403c)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Applying chrome://browser/content/overlays/tabfeatures.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:99:15
Applying chrome://browser/content/overlays/privatetab.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:99:15
Applying chrome://browser/content/overlays/statusbar.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:99:15
```

**Comment by HUD199** [comment]
Microsoft Edge Browser loads page with embedded link.
Microsoft Edge
Version 117.0.2045.41 (Official build) (64-bit)
https://chloes.tranzactcard.com/

**Comment by MrAlex94** [comment]
Is it the video as seen below?
![image](https://github.com/WaterfoxCo/Waterfox/assets/4728920/6114eb4c-102e-4aa3-b405-09cda59d7e06)

**Comment by HUD199** [comment]
Exactly. The video link is missing.

--
Bob Huddleston
843-425-4510

**Comment by MrAlex94** [comment]
Looks like the website CSS needs to be improved for Waterfox/Firefox.
The `<a>` link under the `<div class="elementor-widget-container">` has a width of `0`. It's probably missing being assigned a class?
As you can see, if I assign it a width of `158px`, the button shows up (and works):
![image](https://github.com/WaterfoxCo/Waterfox/assets/4728920/046720b0-1570-4bfb-85dc-97b1096dd974)
Might be worth submitting this to the developers of the website?

**Comment by HUD199** [comment]
Good catch! Will pass on to TranzactCard web team.

--
Bob Huddleston
843-425-4510
