### ISSUE TITLE
Improper tab centering on 125% system scale

### ISSUE THREAD

**Issue by aaronliu0130** [MrAlex94/Waterfox#3160]
### What happened?

![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/e3970622-eed3-4f7e-a1a5-f73121290f5e)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by aaronliu0130** [comment]
This appears to be a consequence of the "center tab content" checkbox", but shouldn't centering mean things are *centered* instead of starting at the center? Also, center labels only is a bit off.
![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/48c5f85a-e341-472d-941d-c1ba2da1d803)

**Comment by OregSamSas** [comment]
I's the same for me on Windows 10.

**Comment by aaronliu0130** [comment]
seems fixed by something
