### ISSUE TITLE
Waterfox G6 keeps restoring session on normal close

### ISSUE THREAD

**Issue by aaronliu0130** [MrAlex94/Waterfox#3161]
### What happened?

Since upgrading to Waterfox G6, all my previous tabs are opened despite me closing the entire thing normally (by pressing the X button) on Windows. No leave site saving dialogue "Are you sure you want to..." is shown when something's unsaved either.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux, Windows

**Comment by MrAlex94** [comment]
If you go to Menu > Settings (about:preferences), is "Open previous windows and tabs" enabled?
![image](https://github.com/WaterfoxCo/Waterfox/assets/4728920/f2860ad7-3584-4b12-9676-d7e299e9c98f)

**Comment by aaronliu0130** [comment]
I didn’t enable that while in G5 but I’ll check when I get home

**Comment by aaronliu0130** [comment]
Also, regardless Waterfox should be checking for unsaved changes when it closes. The current behavior is exactly the same as if it crashed.

**Comment by aaronliu0130** [comment]
Yes, that is enabled in G6. Why is it on by default though?

I just checked and G6 indeed checks for unsaved work... idk how I arrived at the "crash" conclusion

**Comment by rthom91** [comment]
Enabled after update here as well. Please turn it off by default.

**Comment by MrAlex94** [comment]
I've made the following changes in G6.0.3:

![image](https://github.com/WaterfoxCo/Waterfox/assets/4728920/9e2a10ff-413e-4ebd-b472-c0eb8d5c2987)

* If you are closing more than 1 tab, you will be prompted for:
  * Confirmation you want to be notified of closing multiple tabs.
  * Confirmation you want your session to be restored.
  
This way, you can uncheck the session restore if you aren't familiar with the preference and stop being notified each time as well.

I understand to power users this is an annoying change, but the majority of Waterfox users aren't actually very technically inclined - so this way should ideally satisfy everyone, as you can easily uncheck the prefs you don't want.

Side note: If you've _already_ changed the session restore preference to something else, it won't be selected in the update, but the prompt will be there just to make you aware.

https://github.com/WaterfoxCo/Waterfox/commit/e69c80e3b6d9c9156c1582b2328c5f80fe95d84e

Feel free to carry on chatting in this issue, I'll keep an eye on it.

**Comment by aaronliu0130** [comment]
Sounds great!

**Comment by aaronliu0130** [comment]
![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/de943ce5-6bff-4483-bc3c-c7a50c11aa09)
@MrAlex94 When closing so much tabs that the browser warns you (e.g. open 35 tabs and close tabs to left), there should probably be no checkboxes

**Comment by MrAlex94** [comment]
You can just toggle `browser.tabs.warnOnCloseOtherTabs` to `false` in `about:config`.

Working on fixing the UI bug as we speak.

**Comment by aaronliu0130** [comment]
BTW it appears almost every dialog has this extra option
![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/3542af5b-90d0-4328-84dd-9f7ce81f2844)

**Comment by MrAlex94** [comment]
Thanks! Had a logic issue to fix, which should be resolved in the release due tomorrow.
