### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by slumbergod** [MrAlex94/Waterfox#3166]
### What happened?

I finally got the CSS issue fixed for vertical tabs I userChrome.css only to discover a memory leak that crashes my laptop. htop shows all the waterfox processes slowly increasing memory consumption. If I leave it long enough the laptop is completely unresponsive. Is anyone else experiencing this with G6.0.1?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

**Comment by slumbergod** [comment]
I have been having all kinds of grief with Waterfox G5 and cloudflare so I decided to try G6 again. 
Same problem. Waterfox eats all my system's memory to the point I can't even use the mouse. 

The same happens using the latest firefox with the same customisations and extensions. It would appear that a change to the FF source has created a problem with an extension. Now I will have to eliminate the extensions one at a time until I find the culprit.

**Comment by Squall-Leonhart** [comment]
theres a memory leak problem between uBO and RES, do you have those?

**Comment by slumbergod** [comment]
> theres a memory leak problem between uBO and RES, do you have those?

Apologies, I forgot to close this issue. After a lot of experimentation I discovered the memory leak was a result of a different extension running in the newer version of waterfox. No problem in the previous generation but definitely complained in the newer one. When I removed it the issue was resolved.
