### ISSUE TITLE
Incorrect shasum value for waterfox-G6.0.1.tar.bz2

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#3167]
### What happened?

The sha sum given on the website does not match the output of the `sha512sum` command.
[cdn1.waterfox.net/waterfox/releases/G6.0.1/Linux_x86_64/waterfox-G6.0.1.tar.bz2](https://cdn1.waterfox.net/waterfox/releases/G6.0.1/Linux_x86_64/waterfox-G6.0.1.tar.bz2)
When i run  sha512sum I get:
`4bc12f2fcd2e40f2d832e2650a770cc6ffae7adf6b0374fdd0208c1c82db1da984c1895e75050be6582b7873725d5344b3ca447b822b14fddcf16abc27b37f91`
On the website it says:
`192320cc82560e91679983d9110a8530b39c1cf05f2636bab4d3b50fa2f226c7c061a06edaa29b10012bd170879bbddfd8e9ce4f61cabd02018065b63204126a`

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
sha512sum waterfox-G6.0.1.tar.bz2
```

**Comment by MrAlex94** [comment]
Sorry about that, should be fixed.
You can always double verify by appending .sha512 to the end of the file.
