### ISSUE TITLE
Opinion: Waterfox for mobile OSes

### ISSUE THREAD

**Issue by JeanPaulLucien** [MrAlex94/Waterfox#3169]
It looks not good. I do not know a good software with good performance which develops for desktop and mobiles. Event Windows-MacOS-Linux gives issues. Windows 7, 8 and 8.1 user need browser. Mozilla reports about 12% user who use Firefox on Windows 7. 

Firefox 100+ is worse than Firefox 2. Firefox 100+ like alpha versions. I am afraid that Waterfox will follow to low performance software with set of bugs.

**Comment by aaronliu0130** [comment]
> a good software with good performance which develops for desktop and mobiles

There are a lot, for example Safari

Windows 7 to 8.1 are EOL, you shouldn’t be using it and almost nobody supports it or optimizes for it. Try Waterfox classic.

**Comment by hawkeye116477** [comment]
> Try Waterfox classic.

It's not updated for almost 1 year, better would be to check Pale Moon or Basilisk. However that's true that even better would be to switch OS.

**Comment by JeanPaulLucien** [comment]
> There are a lot, for example Safari

You confirmed my position. Apple has stopped development for Windows in 2012. Apple develops Safari for Apple OSes. iOS is not same as Android. Apple knows own OSes better than somebody else.

Mozilla has started to do a strange thing with Firefox in 2017. In fact Firefox 100+ is like Opera browser when they has solved to remake Opera. Finally Opera has spent time, lost market and was sold to chinese company.

**Comment by aaronliu0130** [comment]
If you're still using a discontinued OS from ~2012, a discontinued browser from ~2012 would be fine. Also, Waterfox classic.

Point is, developing for mobile does not somehow mean that it'll compromise the performance. Chrome and Firefox are also performant, Google knows ChromeOS and Android.

**Comment by MrAlex94** [comment]
Well, Android has been released - and iOS is somewhat in the pipeline. So it's coming!

**Comment by NovaAndrom3da** [comment]
Has there been any updates on the iOS app? I'm fairly excited to try it out.
