### ISSUE TITLE
Issue unpacking Linux waterfox-G6.0.2.tar.bz2 download - no "waterfox" directory

### ISSUE THREAD

**Issue by zqqw** [MrAlex94/Waterfox#3172]
### What happened?

The new Linux download, waterfox-G6.0.2.tar.bz2 doesn't unpack into the usual "waterfox" directory, instead the contents that would normally occupy that directory are unpacked into the current working directory.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

**Comment by jelabarre59** [comment]
Yes, that hit my setup.  I made the presumption it would extract to a "waterfox" directory as it had in the past, and extracted directly in /usr/lib64, messing up my existing libraries.  (yes, I should never presume, should I).

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/6b9ec48683c009379fac80f4943d54d91f28dbde fixes the issue.

**Comment by MrAlex94** [comment]
I have a staging build here, which seems to work as expected now from my testing: https://cdn1.waterfox.net/waterfox/staging/G6.0.4/Linux_x86_64/waterfox-G6.0.4.tar.bz2

**Comment by zqqw** [comment]
That has certainly fixed it, thank you.
