### ISSUE TITLE
The quick close cross on inactive tabs is gone

### ISSUE THREAD

**Issue by Demis6** [MrAlex94/Waterfox#3173]
### What happened?

The closing cross on inactive tabs that appeared when you hovered over the tab is gone. Pity. This ability to close an inactive tab in one click distinguished G5 from Firefox.

Also, the height of the tab bar and address bar has increased, which is bad. How to reduce it?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by jh34ghu43gu** [comment]
Came here to also complain about this, very annoying feature to have removed, would love to have an option to restore it or have it be default feature again.

**Comment by MrAlex94** [comment]
Sorry, an oversight on my part. Has been fixed and will be live in G6.0.3.
