### ISSUE TITLE
Overflow menu is KO / Extensions unreachable

### ISSUE THREAD

**Issue by didli** [MrAlex94/Waterfox#3174]
### What happened?

Since the latest G6.0.2, the overflow menu is KO : it's not showing up in the toolbar, unless you switch to customization mode (which makes it still inaccessible). Worst : I had 2 or 3 extensions in it (e.g, foxscroller), which are now also unreachable. Even removing and reinstalling the extension won't help : the extension is not showing up in the regular toolbar anymore.

### Version
G6.0.2

### What platform are you seeing the problem on?
Linux

**Comment by scoopscoop** [comment]
Been searching around for a fix to this, been happening since G6.0.2 on windows 10. Similarly, toggling/disabling extensions doesn't help. I can still reach addons from the addon page, and thankfully they're still working, but it's a rather painful workaround.

**Comment by MrAlex94** [comment]
It's an odd bug, I'm looking into the cause.

In the meanwhile, you can reset this pref to get it back:

Could you go to `about:config` search for `browser.uiCustomization.state` and hit the reset preference option (that sort of arrow looking button)?

**Comment by scoopscoop** [comment]
Thanks, that actually made the extension button show up. Functionality's changed a bit, but I've managed to mostly get things back the way they used to be.

**Comment by vaygr** [comment]
The extension button showed up, but extension icons still can't be added to the overflow menu.

**Comment by didli** [comment]
"Restore defaults" option from the customization mode was the way to go : from there, I got the extension icon button showing up, which in turn let me customize again some of my missing extensions and associated buttons. It seems firefox has introduced some changes in the way extensions and overflow menu works since v119 that I was not aware of.
- overflow menu is now only for the native/toolbars buttons in customization mode (and maybe some extensions that can show up there ?)
- extensions button replaces the previous overflow menu behavior

Is that it ?

**Comment by MrAlex94** [comment]
Yes, quite a few changes that seem to be a bit of a PITA to change the behaviour of.

If anyone still has the issue or can recreate it, would you mind testing this [Staging](https://cdn1.waterfox.net/waterfox/staging/G6.0.3/WINNT_x86_64/Waterfox%20Setup%20G6.0.3.exe) build to see if it fixes it? It won't allow the extension button to be removed, but it'll at least show it again!

EDIT: Okay, have test the fix and it works. Will push live today. Please re-open if you find any issues related to this that aren't inherited from Firefox.

**Comment by jelabarre59** [comment]
The link for your "Staging" build doesn't work anymore.  I would like to find a version that restores the full functionality of the Overflow Menu.  Firefox seem intent on never fixing it, and since one of the purposes of Waterfox is to fix stupid decisions in Firefox, this seems to be a perfect candidate.
