### ISSUE TITLE
New update G6.0.2 left private window with dark background & font. Fix: change theme

### ISSUE THREAD

**Issue by nowakommunikation** [MrAlex94/Waterfox#3175]
### What happened?

After the above update when in private window mode, the background of the address and search bar were black just like the text font, so not readable. Also the tabs font was a very light gray so barely readable. 

I fixed this by changing the theme to something else e. g. Alpenglow under "Extensions & Themes" in the settings menu. 

Never had to change the theme before. 

This just in case somebody else had the same issue. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

macOS

**Comment by MrAlex94** [comment]
If you want to use the default theme, you can go to `about:config` in the address bar, search for `userChrome.theme.private` and toggle the value to `false`.
