### ISSUE TITLE
Often, downloading brings up the save file dialog again now

### ISSUE THREAD

**Issue by aaronliu0130** [MrAlex94/Waterfox#3176]
### What happened?

![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/eda4656f-88ee-474b-9803-7fe092de22ad)
This didn't happen in G5

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
how do i even get logs
```

**Comment by MrAlex94** [comment]
You can toggle the preference `browser.download.useDownloadDir` to `true`.

This has always been the default, except when Mozilla removed the option between 97 -> some version just before 115, before reintroducing it.

Automatically downloading files is rather user hostile and was actually the cause of a serious [vulnerability](https://web.archive.org/web/20170520070441/http://defensecode.com/news_article.php?id=21) in Chrome, a few years back.

**Comment by aaronliu0130** [comment]
Sure. I'd heavily prefer to have this sort of stuff in changelogs though. The UI also looks quite a bit outdated and there's no corresponding pref (about:preferences) but that's just a nit.

BTW I think this should be closed as not planned.

**Comment by aaronliu0130** [comment]
@MrAlex94 I've toggled the config and restarted Waterfox but it still prompts.
![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/c05bf260-b82c-458a-abe8-49ca459ef961)
![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/81a99262-93a5-47e3-a46a-2c62447a45c9)

**Comment by MrAlex94** [comment]
These are all the related prefs I've changed by default:

```
// PREF: Enforce user interaction for security by always asking where to download
// [SETTING] General>Downloads>Always ask you where to save files
// false=the user is asked what to do
pref("browser.download.useDownloadDir", false);

// PREF: disable downloads panel opening on every download
pref("browser.download.alwaysOpenPanel", false);

// PREF: Disable adding downloads to the system's "recent documents" list
pref("browser.download.manager.addToRecentDocs", false);

// PREF: enable user interaction for security by always asking how to handle new mimetypes
// [SETTING] General>Files and Applications>What should Firefox do with other files
pref("browser.download.always_ask_before_handling_new_types", true);

// PREF: autohide the downloads button
pref("browser.download.autohideButton", false);

// PREF: open PDFs inline (FF103+)
pref("browser.download.open_pdf_attachments_inline", true);
```

Although odd that the pref you've toggle hasn't changed anything. Is that including after a restart?

**Comment by aaronliu0130** [comment]
I tried restarting waterfox, yes. I'll try restarting my PC after this match

**Comment by aaronliu0130** [comment]
Restarting my PC doesn't work either

**Comment by thunderstone135** [comment]
Try setting `browser.download.dir` to `C:\Users\<UserName>\Downloads`.
<UserName> is your Windows Profile Name. You can use other directories if you want.

**Comment by aaronliu0130** [comment]
I already have that config. Set it again for good measure. Still doesn't work.

**Comment by thunderstone135** [comment]
In `about:preferences` 👇

![Imgur](https://imgur.com/wyfojwz.png)
Is this option checked?

![Imgur](https://imgur.com/cyWhTmy.png)
Which option is selected?

**Comment by aaronliu0130** [comment]
@thunderstone135 Changing the second pref you sent did it, thanks!

@MrAlex94 I still think this and a way to revert should be mentioned in changelogs. I also disagree with not making the downloads panel open, it's not very intrusive and is more noticeable than the download icon changing.
