### ISSUE TITLE
Latest update (6.0.2) broke address bar drop-down menu

### ISSUE THREAD

**Issue by clawstheone** [MrAlex94/Waterfox#3177]
### What happened?

In the previous version, clicking once on the address bar immediately showed a drop-down menu of the most visited sites which was extremely convenient. After the update, clicking on the address bar doesn't do this anymore and you have to press the space key to show this menu again. Please fix this, having to press space bar is just an extra inconvenient step.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by KrzysztofMr** [comment]
I noticed the same with Waterfox 6.0.2 under Debian 11

**Comment by Objectivite** [comment]
Same problem here.  We really would prefer an extra day or two or three of testing, even an extra week of testing, rather than a rushed critical updates fix which breaks what was working in 6.0.1  (not that 6.0.1 did not have its own problems!).

Reverted back to 5.1.13

O.

**Comment by MrAlex94** [comment]
This will be remedied in G6.0.3, in the meanwhile you can go to `about:config` and toggle `browser.urlbar.suggest.topsites` to `true`.
