### ISSUE TITLE
Waterfox G6.0.2 focus is not set in address bar in new private window

### ISSUE THREAD

**Issue by KrzysztofMr** [MrAlex94/Waterfox#3183]
### What happened?

When opening new private window with key shortcut Ctrl+Shift+P cursor is not focused in address bar. Has to click address bar or use Ctrl+l to set ursor there before typing address.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by ghost** [comment]
I've found the same thing on any new window regardless of if it's private or not. Opening a new tab is fine though. Running macOS 14.0

**Comment by grandperoxide** [comment]
Same issue on Windows, I'm hoping this is a bug and not intentional, would love for this to be togglable at least. Thanks!

**Comment by ghost** [comment]
Fixed in G6.0.3!

**Comment by KrzysztofMr** [comment]
Confirm, fixed in G6.0.3
