### ISSUE TITLE
G6.02 uBlock Origin does not function properly on Bing

### ISSUE THREAD

**Issue by wiyosaya** [MrAlex94/Waterfox#3184]
### What happened?

When searching on Bing in G6.02 uBlock origin is very minimally functional if at all. The element hiding helper does not work at all.  These elements and uBlock origin in general, continues to function on Firefox. Why they no longer work on Bing is beyond me. I started seeing this only with G6.02. uBlock origin was properly functioning on Bing prior to the G6.02 release. I am experiencing this issue on multiple different computers.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by aaronliu0130** [comment]
Same but for Dark Reader. It appears Bing is now in the list of system pages that extensions cannot modify...

**Comment by aaronliu0130** [comment]
![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/b3e3a0b6-bdb7-4710-b5a7-8e6524fa679a)

**Comment by wiyosaya** [comment]
Personally, I would rather be able to donate than have bing blocked from using uBlock.

I guess there's always firefox for maintaining user's choice.

**Comment by MrAlex94** [comment]
Apologies, this wasn't meant to go live, this was testing in preparation for Waterfox Search. This is fixed in G6.0.3.

**Comment by aaronliu0130** [comment]
I think extensions should be able to modify Waterfox Search though, or at least give us an option to enable that. Also, what differences will it have with Storm? I'm new to this

**Comment by wiyosaya** [comment]
> Apologies, this wasn't meant to go live, this was testing in preparation for Waterfox Search. This is fixed in G6.0.3.

Thank you so very much.

**Comment by MrAlex94** [comment]
> I think extensions should be able to modify Waterfox Search though, or at least give us an option to enable that.

Extensions will be able to! I've explained [here](https://www.reddit.com/r/waterfox/comments/171bixl/comment/k3pndh9/?utm_source=reddit&utm_medium=web2x&context=3) why this was enabled (was meant to be just in the beta releases).

> Also, what differences will it have with Storm? I'm new to this

Storm was a little ahead of its time I suppose. It was designed as a search engine where the profits would be split with the charity of the users choice. But it was still Bing search results, but baby steps - would've worked up to where we are now I suppose!

This search engine will be Google search results (yes, actual results) _without_ any of the profiling or data collection. A lot of people argue that "pure" Google search results are still the best, as the personalised results sometimes completely miss the mark.

The biggest challenge so far is finding a respectful ad network. Mozilla has [Privacy Preserving Attribution](https://blog.mozilla.org/en/mozilla/privacy-preserving-attribution-for-advertising/), Apple/Safari has [Privacy Preserving Ad Click Attribution](https://webkit.org/blog/8943/privacy-preserving-ad-click-attribution-for-the-web/) and Google/Chrome has ["Privacy Sandbx"](https://www.google.com/chrome/privacy-on-the-web/). But, I have _yet_ to find a ad network that uses any of this tech.

Still, when it's time for testing, I'll make sure people have time to test and give feedback!
