### ISSUE TITLE
Search suggestion window on new tab

### ISSUE THREAD

**Issue by jdjk7** [MrAlex94/Waterfox#3185]
### What happened?

Prior to the last update, something I could do is:
1) open a new tab
2) click the address bar without typing anything, the search suggestions window appears
3) click one of my top visited sites and go to it.

After this past updated, clicking the address bar no longer makes search suggestions appear. This functionality is still present in Firefox.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
This has been "fixed" in G6.0.3, but feel free to enable it: 

Menu > Settings > Privacy and Security > Address Bar > Check "Shortcuts"

![image](https://github.com/WaterfoxCo/Waterfox/assets/4728920/30db6b6f-5787-47f8-94c2-eba81ed59810)
