### ISSUE TITLE
G6.0.3 - opening bookmarks with middle click won't close the bookmark folder anymore

### ISSUE THREAD

**Issue by muelli01** [MrAlex94/Waterfox#3189]
### What happened?

When clicking a bookmark link with middle mouse button to open it in a new tab, does not close the bookmark menu/folder anymore. You have to click outside the menu/folder to make it disappear.

Verified this with firefox 118.0.1 (latest in linux mint), this is not happening there.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by ghost** [comment]
I am using G6.0.3 on Linux Mint 21.2 and I get the same issue as the OP. When I middle-click on a bookmark in the bookmarks toolbar, the web page opens, but the bookmark folder doesn't close.

**Comment by Snowy-Altar** [comment]
Try setting browser.bookmarks.openInTabClosesMenu to True in about:config.

**Comment by ghost** [comment]
> Try setting browser.bookmarks.openInTabClosesMenu to True in about:config.

Thank you. That fixes the problem for me.

**Comment by muelli01** [comment]
same here, problem fixed! Thanks!
