### ISSUE TITLE
disable/murder/hide close tab button

### ISSUE THREAD

**Issue by DerGolgo** [MrAlex94/Waterfox#3192]
This feature existed informally until G6.0.3.

I had previously meddled with about:config to eliminate the close-tab button, which is a vital configuration for me, and which has kept working until the latest release.

I often have a lot of tabs open, and trying to select one, I very often hit the close-tab button unintentionally. Precise aiming is confounded by the sheer lack of real estate on tabs. The close button occupies too much of it.

I am also dealing with severely **diminished eyesight**, specifically homonymous hemianopsia to the right. The right half of my oem field of vision no longer exists, which often keeps me from noticing a close-tab button appearing on hover. Yes, the cutoff is that sharp. No, trying to change my browsing habits, just like my reading habits, has not eliminated the pitfall of missing another character, letter, glyph, symbol, etc., just to the right of where I'm looking. 

The following "remedies" unleashed on the latest release did **not** remedy:
- going to about:config and setting **browser.tabs.closebuttons** to false
- opening userChrome.css and adding 
```
#tabbrowser-tabs .tabbrowser-tab .tab-close-button {
   display:none!important;	
}
```

The modification to userChrome.css work, but only if tabs are not squished. A few tabs, at full width, back- and foreground, no close button. Open a few more, it only removes the button from the active tab but not from background tabs where it appears on hover, still.

I don't _need_ a bunch of checkboxes in the settings menu (though others might).
But some way, if not by menu then preferably in about:config, to disable the close-tab buttons is indispensable to me.

Any efforts by anyone to help me out are greatly appreciated.

**Comment by thunderstone135** [comment]
You can ditch `#tabbrowser-tabs` and `.tabbrowser-tab`. Just use `.tab-close-button` like this 👇
```
.tab-close-button {
   display: none !important;
}
```

**Comment by DerGolgo** [comment]
> You can ditch `#tabbrowser-tabs` and `.tabbrowser-tab`. Just use `.tab-close-button` like this 👇
> 
> ```
> .tab-close-button {
>    display: none !important;
> }
> ```

Thank you.
Unfortunately, it doesn't work. Situation remains as before. No close button on foreground tabs and background tabs that are full width. Close button appears on hover on squished background tabs.

**Comment by DerGolgo** [comment]
> You can ditch `#tabbrowser-tabs` and `.tabbrowser-tab`. Just use `.tab-close-button` like this 👇
> 
> ```
> .tab-close-button {
>    display: none !important;
> }
> ```

Thank you. Unfortunately, that didn't work.

Also, I thought I had replied here already. In any case, I apologize for my delayed reply.

**Comment by thunderstone135** [comment]
Can you post a screenshot? Also, what OS (Linux, Mac, Windows) are you using?

**Comment by thunderstone135** [comment]
By the way, I researched `browser.tabs.closeButtons` and it looks like Mozilla removed it 10 years ago.
https://bugzilla.mozilla.org/show_bug.cgi?id=865826

Personally, I don't use the pref, so I have no comment about its removal.
Also, I'm using Tab Mix Plus, and because of it I'm very much in control of all tabs.

**Comment by DerGolgo** [comment]
OS: Windows 10


Tab Mix Plus: I used to use that when I was still using Classic. At the time that I switched to Current, there was no equivalent. That was when I fuddled the buttons gone in about:config.
Is there a new version Tab Mix Plus for Current?! If so, could you point me in the approximate direction thereof?

Note on all those Extension icons: yes, I have tried disabling them all and restarting. The situation remained unaffected.

Screenshot 1: full-width tabs, no close-button on hover.
![Screenshot 2023-10-03 124331](https://github.com/WaterfoxCo/Waterfox/assets/48029807/be2e37b5-db22-4d75-998f-2b2f4628b528)
Screenshot 2: reduced-width tabs, close-button on hover.
![Screenshot 2023-10-03 124435](https://github.com/WaterfoxCo/Waterfox/assets/48029807/02dfdd8b-93f9-4ba0-b0ca-d91ccf757735)

**Comment by alan-wint** [comment]
Please re-enable the option to remove close buttons from tabs.  We have the middle mouse button to close tabs.

**Comment by thunderstone135** [comment]
@DerGolgo:
You can download and install the latest version of Tab Mix Plus below 👇
https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.17/tab_mix_plus-dev-build.xpi

**Comment by thunderstone135** [comment]
To remove the close tab button, just uncheck the corresponding option in Tab Mix Plus.

![Imgur](https://imgur.com/5dhSuOo.png)

**Comment by DerGolgo** [comment]
> @DerGolgo: You can download and install the latest version of Tab Mix Plus below 👇 https://github.com/onemen/TabMixPlus/releases/download/v1.0.0-pre.17/tab_mix_plus-dev-build.xpi

**_THANKYOUTHANKYOUTHANKYOU!!!_**

Now, therein lies a solution.
But as @alan-wint indicates, I'm not alone in missing this feature. 

I will close the issue with a comment. If anyone is unhappy using the gloriously reborn Tab Mix Plus, I suppose this issue can be reopened.

**Comment by cloudscalebytes** [comment]
@DerGolgo I am definitely not happy about installing such a convoluted plugin just to get back a feature that should never have been removed: https://github.com/onemen/TabMixPlus

> Since Firefox removed the internal component that loads legacy extension, in order to install Tab Mix Plus, or any other legacy extension, you have to install 3rd party helper script/extension.

That looks like a good way to destabilize the browser and raises security concerns.  Can you please re-open this issue?

**Comment by DerGolgo** [comment]
> That looks like a good way to destabilize the browser and raises security concerns. Can you please re-open this issue?

@cloudscalebytes I have repoened it. Though for me personally, using TabMixPlus is pretty perfect. The revival had passed me by and I would be using it even if I wanted the close tab buttons.

**Comment by thunderstone135** [comment]
> @DerGolgo I am definitely not happy about installing such a convoluted plugin just to get back a feature that should never have been removed: https://github.com/onemen/TabMixPlus
> 
> > Since Firefox removed the internal component that loads legacy extension, in order to install Tab Mix Plus, or any other legacy extension, you have to install 3rd party helper script/extension.
> 
> That looks like a good way to destabilize the browser and raises security concerns. Can you please re-open this issue?

If anyone have complaints about any features being removed, then point it to Mozilla. They removed the feature and not the author of Waterfox.

I posted this link in my previous comment, but it seems to be ignored 👇

https://bugzilla.mozilla.org/show_bug.cgi?id=865826

This issue was raised 10 years ago and contains the conversation of the feature being removed. This was reflected in Firefox 31.

**Comment by DerGolgo** [comment]
> If anyone have complaints about any features being removed, then point it to Mozilla. They removed the feature and not the author of Waterfox.

@thunderstone135 I don't think anyone was trying to find whom to blame for the absence of the feature. Rather, people want it back, and some are not keen on doing it by installing TabMixPlus. 
I'm willing to bet that anyone using Waterfox is doing so because Mozilla et al removed some feature or function from Firefox.

Requesting a re-implementation of this feature, even if Firefox hasn't had it for a decade, strikes me as no different than requesting the implementation of any other feature Firefox doesn't have or never had at all.

Should this issue perhaps be moved to wherever (new) features are requested, or re-labeled/re-categorized to reflect a feature request?
It perhaps should have been such a-priori, in which case, I apologize for spamming up the wrong segment of the issues page.

I gotta confess that I'm a noob to github discussions, so I'm fully useless in making the aforementioned moving/relabeling/recategorizing. 
Little help?

**Comment by thunderstone135** [comment]
> @thunderstone135 I don't think anyone was trying to find whom to blame for the absence of the feature. Rather, people want it back, and some are not keen on doing it by installing TabMixPlus. I'm willing to bet that anyone using Waterfox is doing so because Mozilla et al removed some feature or function from Firefox.
> 
> Requesting a re-implementation of this feature, even if Firefox hasn't had it for a decade, strikes me as no different than requesting the implementation of any other feature Firefox doesn't have or never had at all.
> 
> Should this issue perhaps be moved to wherever (new) features are requested, or re-labeled/re-categorized to reflect a feature request? It perhaps should have been such a-priori, in which case, I apologize for spamming up the wrong segment of the issues page.
> 
> I gotta confess that I'm a noob to github discussions, so I'm fully useless in making the aforementioned moving/relabeling/recategorizing. Little help?

It's not your fault. I just don't like it when people are barking up the wrong tree.

Putting that aside, the `browser.tabs.closeButtons` feature can be restored if @MrAlex94 or anyone (via Pull Request) can undo the changes made in here 👇

https://bug865826.bmoattachments.org/attachment.cgi?id=8409012

**Comment by SurealCereal** [comment]
Please add an option to hide the close button.  They are not needed as we have middle click.

**Comment by SurealCereal** [comment]
Please add an option to hide the tab close button. It is not needed with the middle mouse button being far more convenient.

**Comment by MrAlex94** [comment]
Is this what you're all after? https://github.com/WaterfoxCo/Waterfox/commit/d33398854671a98463cf5303d0fcf9770c3de249


https://github.com/WaterfoxCo/Waterfox/assets/4728920/1056b955-d664-4ca0-8b32-920f9affbc78

**Comment by SurealCereal** [comment]
> Is this what you're all after? [d333988]

Exactly that, thanks!

**Comment by S3NTYN3L** [comment]
Logic seems to be inverted.
`browser.tabs.closeButtons` defaults to `false` on my machine with buttons still visible.
Changing to `true` disappears them.

**Comment by S3NTYN3L** [comment]
> Logic seems to be inverted. `browser.tabs.closeButtons` defaults to `false` on my machine with buttons still visible. Changing to `true` disappears them.

Currenty broken in 6.5.2
