### ISSUE TITLE
Super slow web page load

### ISSUE THREAD

**Issue by Darkazas** [MrAlex94/Waterfox#3193]
### What happened?

Almost all web pages take almost minutes to load - YouTube, Google, you name it.
Starting Waterfox in troubleshooting mode doesn't change a thing.
With latest G5.1.13 (and earlier) that was no issue at all.

My system:
Windows 10 Pro
Version	22H2
OS build	19045.3448
RAM	16,0 GB

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by IdrisQe** [comment]
To corroborate this, I've also noticed pages loading slower in general since upgrading to G6.0.2 from G5.1.12, though not quite this slow.

**Comment by MrAlex94** [comment]
I've been working on the infrastructure for DoOH, and DNS resolutions should be way faster now. From the metrics:

50th Percentile has a response in 7ms
90th Percentile has a response in 37ms
99th Percentile has a response in 206ms 

May I ask which region you are in? Don't have to be too specific, just the general area. Will help me have an idea of where users who are getting bad performance are.

**Comment by IdrisQe** [comment]
Canada, specifically the west - but also I updated to 6.0.3 and speeds seem much better, though I found out later that I was having some intermittent and unexplained internet issues (thanks Shawgers) so that may have been the source of the slowness.

**Comment by Fehertukor** [comment]
I have the same problem, similar system and central-east Europe since upgrading to G6.0.2 and G6.0.3.
Important, that I have more than 50 open pages but about 5 of them loaded in and with the older version there was no similar problem. 
Loading times few seconds or in-between 30 sec.

Additionally sometime I get these message:
"Hmm. We're having trouble finding that site."
With multiple reloads it works and finds it

**Comment by Darkazas** [comment]
Lithuania, Eastern Europe. I‘m sitting on fiber optics and internet speeds are 400Mbits+.

**Comment by MrAlex94** [comment]
Alright all, I've made some more changes - could you let me know if this still happens over the next few hours?

**Comment by MrAlex94** [comment]
Just a follow up, looks like Cloudflare's resolver was actually having [issues](https://www.cloudflarestatus.com/incidents/j3h00yhjyw6p), right around the time users were getting the `Hmm. We're having trouble finding that site.` error.

**Comment by Darkazas** [comment]
Waterfox restart.
YouTube page is loading ~60s. 20s more to resume video clip from the moment before Waterfox shutdown.
The only relief is that this happening just once during Waterfox session.

Same can be said about almost any web site (google, amazon, wikipedia, …) – just loading times maybe shorter.

Still waiting for resolution…

**Comment by Fehertukor** [comment]
@MrAlex94 so I just checked and it seems better but there is still some slowness. I will test it again later today.

**Comment by hdk2d** [comment]
I am from Dominican Republic and I also have slow page loading since I upgraded to G6.0.

**Comment by MickiTee** [comment]
I'm in the UK and I've been having this problem constantly since the last update and I'm still having it. In fact I'm adding this comment from Firefox as Waterfox is so unresponsive!

As an example Amazon UK is taking 90secs+ to load! Takes less than 2secs in Firefox. I've cleared history, cache, cookies etc and this has made no difference.

Running on Dell Inspiron 3505 on Windows 10 Pro
Version	22H2
Installed on	‎06/‎04/‎2021
OS build	19045.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0

**Comment by MrAlex94** [comment]
To all those having issues, it's probably best to change the following for the time being:

Set `network.trr.mode` to `0` in `about:config`.

The next Waterfox update will have a GUI option for this in the Preferences page.

**Comment by Darkazas** [comment]
Yep – lags gone.
Thanx.
Waiting for Trusted Recursive Resolver issues to be solved.

**Comment by killingyouguy** [comment]
> To all those having issues, it's probably best to change the following for the time being:
> 
> Set `network.trr.mode` to `0` in `about:config`.
> 
> The next Waterfox update will have a GUI option for this in the Preferences page.

Thank you! I was getting 16 whole Kbps down and nothing was ever loading. Edge was fine. This fixed the issue immediately

**Comment by hdk2d** [comment]
> To all those having issues, it's probably best to change the following for the time being:
> 
> Set `network.trr.mode` to `0` in `about:config`.
> 
> The next Waterfox update will have a GUI option for this in the Preferences page.

This work thanks

**Comment by Darkazas** [comment]
Seems to be this problem is now really solved.

G**6.0.4**
    Changes
         You can now **disable Oblivious DNS** via the Preferences page. Go to Preferences → Privacy & Security → DNS over HTTPS.

**Comment by MrAlex94** [comment]
For those who have disabled DOOH, I've now migrated over to Fly and now have 38 regions deployed globally - could you see if this has improved speeds for you? Previous provider only had 6 regions to deploy to.

**Comment by Darkazas** [comment]
DNS over Oblivious HTTP changed to default protection – works fine.

**Comment by Fehertukor** [comment]
@MrAlex94 It seems OK now. I will keep testing.
