### ISSUE TITLE
GNU/Linux tarball does not extract into a waterfox folder - accessibility issue

### ISSUE THREAD

**Issue by andyprough** [MrAlex94/Waterfox#3197]
### What happened?

When extracting the tarball for versions G6+ on GNU/Linux distros, the contents of the tarball should extract into a new 'waterfox' folder. Instead the contents extract into the folder that G6 is downloaded into. This is causing problems for one of our sight impaired users who extracts the tarball by using a graphical file manager and using the 'extract here' option in the context menu. Unless they create a 'waterfox' folder first and download the tarball into that, they have to individually find about 55 files and folders and then drag and drop them into a new folder themselves - a very laborious process for someone who is having sight problems already.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Hi,

Sorry about that! I'll look into it and get it remedied ASAP.

**Comment by MrAlex94** [comment]
Just an update, this has been fixed and will go live with G6.0.4.

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/6b9ec48683c009379fac80f4943d54d91f28dbde

**Comment by MrAlex94** [comment]
I have a staging build here, which seems to work as expected now from my testing: https://cdn1.waterfox.net/waterfox/staging/G6.0.4/Linux_x86_64/waterfox-G6.0.4.tar.bz2
