### ISSUE TITLE
Pinned Tabs will Unload on Low Memory

### ISSUE THREAD

**Issue by GuestJim** [MrAlex94/Waterfox#3206]
### What happened?

The `browser.tabs.unloadOnLowMemory` config option is unloading pinned tabs. By their nature, pinned tabs should never be unloaded.
It also seems the unloadOnLowMemory feature is more aggressive than it had been in G5, as G6 seems to keep fewer tabs loaded than it had.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
From [this](https://www.reddit.com/r/firefox/comments/v947fg/comment/ibu9y9j/?utm_source=share&utm_medium=web2x&context=3) comment:

> >excluding tabs playing media, using Picture-in-Picture, or using WebRTC. Pinned tabs are deprioritized and are less likely to be unloaded.
>
> https://firefox-source-docs.mozilla.org/browser/tabunloader/
>
> Pinned tabs should appear at the bottom of the list on about:unloads and be unloaded only as a last resort. You can stop all tab unloading by changing browser.tabs.unloadOnLowMemory to false in about:config. Using an extension like [Auto Tab Discard](https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/) will give you more control.

**Comment by GuestJim** [comment]
Thank you for the response, Alex. If only to satisfy my curiosity though, has the algorithm that decides when to unload tabs been changed with G6?
I have had to set unloadOnLowMemory to false because I cannot have my work Slack and email (both pinned tabs) unloading on me. This never happened to me on G5, even when I was using a computer with less RAM, and yet it did happen on G6.

**Comment by Squall-Leonhart** [comment]
This feature from mozilla is actually a joke as they are using bad metrics to determine low memory events.

Windows 10+ do not follow the behaviors of 7 and 8, where min size of pagefile was atleast 1:1 (usually 1:1.5) with installed memory,  10 on the otherhand gives you a 5GB (at 32GB RAM) pagefile 

The reason i mention pagefils is that mozilla is running their memory notifiers against the total available size of the pagefile via ullAvailPageFile when they should be using ullAvailVirtual to track total Commit size

The tiny default pagefile on 10 and 11 which can quite quickly fill on an nvme or ssd under physical pressure.
