### ISSUE TITLE
Copying URLs from address bar doesn't convert spaces into %20 for sharing links

### ISSUE THREAD

**Issue by jh34ghu43gu** [MrAlex94/Waterfox#3207]
### What happened?

G5 Copying a link with a space in it would automatically copy the spaces as a %20 in order to have sharable links, currently in G6.0.3 they are copied as-is which breaks these links when shared elsewhere like here or on discord.

eg: https://backpack.tf/stats/Unique/Taunt%3A The Carlton/Tradable/Craftable should be copied as https://backpack.tf/stats/Unique/Taunt%3A%20The%20Carlton/Tradable/Craftable

Copying from the right click context menu still preserves this functionality.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
You can toggle `browser.urlbar.decodeURLsOnCopy` to `false` in `about:config` :-)
