### ISSUE TITLE
Streaming service with DRM not working in G6.0.3 Mac

### ISSUE THREAD

**Issue by v-127** [MrAlex94/Waterfox#3210]
### What happened?

I've been reading some issues created here with older versions of Waterfox, they had few workarounds but they just don't work... 

I'm using latest version of MacOS.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

macOS

### Relevant log output

Applying chrome://browser/content/overlays/tabfeatures.xhtml to chrome://browser/content/browser.xhtml [Overlays.sys.mjs:89:15](resource:///modules/Overlays.sys.mjs)
Applying chrome://browser/content/overlays/privatetab.xhtml to chrome://browser/content/browser.xhtml [Overlays.sys.mjs:89:15](resource:///modules/Overlays.sys.mjs)
Applying chrome://browser/content/overlays/statusbar.xhtml to chrome://browser/content/browser.xhtml [Overlays.sys.mjs:89:15](resource:///modules/Overlays.sys.mjs)
ReferenceError: getComputedStyle is not defined
    set resource:///modules/StatusBar.sys.mjs line 187 > eval:28
    update chrome://browser/content/tabbrowser.js:7377
    onStatusChange chrome://browser/content/browser.js:5488
    callListeners chrome://browser/content/tabbrowser.js:969
    _callProgressListeners chrome://browser/content/tabbrowser.js:983
    _callProgressListeners chrome://browser/content/tabbrowser.js:6566
    onStatusChange chrome://browser/content/tabbrowser.js:7088
[tabbrowser.js:974:23](chrome://browser/content/tabbrowser.js)
    callListeners chrome://browser/content/tabbrowser.js:974
    _callProgressListeners chrome://browser/content/tabbrowser.js:983
    _callProgressListeners chrome://browser/content/tabbrowser.js:6566
    onStatusChange chrome://browser/content/tabbrowser.js:7088
ReferenceError: getComputedStyle is not defined
    set resource:///modules/StatusBar.sys.mjs line 187 > eval:28
    update chrome://browser/content/tabbrowser.js:7377
    onStatusChange chrome://browser/content/browser.js:5488
    callListeners chrome://browser/content/tabbrowser.js:969
    _callProgressListeners chrome://browser/content/tabbrowser.js:983
    _callProgressListeners chrome://browser/content/tabbrowser.js:6566
    onStatusChange chrome://browser/content/tabbrowser.js:7088
[tabbrowser.js:974:23](chrome://browser/content/tabbrowser.js)
Applying chrome://browser/content/overlays/tabfeatures.xhtml to chrome://browser/content/browser.xhtml [Overlays.sys.mjs:89:15](resource:///modules/Overlays.sys.mjs)
Applying chrome://browser/content/overlays/privatetab.xhtml to chrome://browser/content/browser.xhtml [Overlays.sys.mjs:89:15](resource:///modules/Overlays.sys.mjs)
Applying chrome://browser/content/overlays/statusbar.xhtml to chrome://browser/content/browser.xhtml [Overlays.sys.mjs:89:15](resource:///modules/Overlays.sys.mjs)
DataCloneError: Function object could not be cloned. [ExtensionChild.sys.mjs:843](resource://gre/modules/ExtensionChild.sys.mjs)
Applying chrome://browser/content/overlays/preferences-general.xhtml to about:preferences [Overlays.sys.mjs:89:15](resource:///modules/Overlays.sys.mjs)
Loading eval'd script into about:preferences 2 [Overlays.sys.mjs:609:15](resource:///modules/Overlays.sys.mjs)
formatURLPref: Couldn't get pref:  datareporting.healthreport.infoURL [URLFormatter.sys.mjs:163:15](resource://gre/modules/URLFormatter.sys.mjs)
Applying chrome://browser/content/overlays/preferences-other.xhtml to about:preferences [Overlays.sys.mjs:89:15](resource:///modules/Overlays.sys.mjs)
Loading eval'd script into about:preferences [Overlays.sys.mjs:609:15](resource:///modules/Overlays.sys.mjs)
ReferenceError: getComputedStyle is not defined
    set resource:///modules/StatusBar.sys.mjs line 187 > eval:28
    update chrome://browser/content/tabbrowser.js:7377
    onStatusChange chrome://browser/content/browser.js:5488
    callListeners chrome://browser/content/tabbrowser.js:969
    _callProgressListeners chrome://browser/content/tabbrowser.js:983
    _callProgressListeners chrome://browser/content/tabbrowser.js:6566
    onStatusChange chrome://browser/content/tabbrowser.js:7088
[tabbrowser.js:974:23](chrome://browser/content/tabbrowser.js)
AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved [ConduitsParent.sys.mjs:362](resource://gre/modules/ConduitsParent.sys.mjs)
Uncaught ReferenceError: getComputedStyle is not defined
    set resource:///modules/StatusBar.sys.mjs line 187 > eval:28
    update chrome://browser/content/tabbrowser.js:7377
    _timer chrome://browser/content/browser.js:5679
[StatusBar.sys.mjs line 187 > eval:28:9](resource:///modules/StatusBar.sys.mjs%20line%20187%20%3E%20eval)

**Comment by HBunnick** [comment]
Netflix and Disney Plus not working, for me either:
DisneyPlus gives: errorcode 83
Netflix: no error but instantly logs me out and removes cookies

[x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

My Sys Info:

Mac OS: 12.6
Waterfox: G6.0.4
widevinecdm:
    File: 4.10.2557.0
    Version: 4.10.2557.0
    State: Enabled

**Comment by HBunnick** [comment]
Issue Still Persists Waterfox: G6.0.6

**Comment by HBunnick** [comment]
Still broken in Waterfox: G6.0.7

Got any Plans to look into this issue?

**Comment by HBunnick** [comment]
Still broken in Waterfox: G6.0.8

**Comment by knelldev** [comment]
Still broken in Waterfox G6.0.9 for me.
Feel free to ping me if you need any more information.

**Comment by HBunnick** [comment]
Still broken in Waterfox G6.0.11

**Comment by knelldev** [comment]
Seems to be still broken on G6.0.18

**Comment by MrAlex94** [comment]
G6.0.20 now has this fixed.
