### ISSUE TITLE
Video FREEZES on AMD Vega, Firefox works normally !!

### ISSUE THREAD

**Issue by AleoDan** [MrAlex94/Waterfox#3211]
### What happened?

Embedded video FREEZES after few seconds on Twitter, Facebook, Youtube with Ryzen5 2400G Vega11 driver 20.11.1 on Windows 8.1. This driver is known to NOT having any bugs with video decoding and playback on DVB streams or LAV codecs !!

The Waterfox G6.0.3 browser become non-responsive and it recovers only when minimized and maximized after few minutes. The video then plays normally and it freezes again after another few seconds.

Disabling hardware acceleration DOES NOT SOLVE the issue. Any other browser works normally, including Firefox ESR 115.3.1.

This is important since the most obvious reason to install Waterfox is because it still supports Windows 8.1 and 7 for now !!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
There is no log.
```

**Comment by AleoDan** [comment]
Same issue with driver 19.12.1, also a good driver without any known bugs.
The driver 20.4.1 do not freeze, but has the black screen bug, so is unusable.
These are the only 3 working drivers for Ryzen APU and Windows 7 or 8.1.

No issues with any NVIDIA graphic cards. Firefox ESR works with 19.12.1 and 20.11.1, no issues. Any video player and DVB stream works without any problems, hardware acceleration enabled. LAV filters works with hardware acceleration enabled.

So, this must be a Waterfox bug!

**Comment by AleoDan** [comment]
It seems that this is a problem with Vega hardware acceleration of video playback. The issue is present also on discrete AMD Vega cards and apeared to Firefox also after a recent update.

Disabling the hardware acceleration fixes the issue. It seemns that all AMD drivers are broken in respect to hardware acceleratio, as the issue manifets itself on Windows 11 with all drivers also.

**Comment by AleoDan** [comment]
It seems that this is a problem with Vega hardware acceleration of video playback. The issue is present also on discrete AMD Vega cards and also apeared to Firefox, after a recent update.

Disabling the hardware acceleration fixes the issue. It seems that all AMD Vega drivers are broken in respect to hardware acceleration, as the issue manifets itself also on Windows 11 with all recent drivers.

**Comment by MrAlex94** [comment]
Might be worth reporting to Mozilla so they can blacklist the drivers if they can reproduce.

**Comment by AleoDan** [comment]
After reading multiple forums, I succeeded to make it work without disabling hardware acceleration by switching DXVA from DirectX11 to DirectX9 in about:config like this:

media.wmf.dxva.d3d11.enabled = False
media.wmf.dxva.d3d9.amd-pre-uvd4.disabled = False

The video hardware acceleration issue is well known by almost all AMD video card users and by AMD itseltf, just they can't make a good driver, just can't...
