### ISSUE TITLE
gfx.crash-guard.d3d11layers.appVersion setting at 91.xx version

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#3219]
### What happened?

Version 6.0.4

All the  **gfx.crash-guard**  settings are at 91.xx version.

Is that expected ?

![image](https://github.com/WaterfoxCo/Waterfox/assets/89191739/01cd1850-21ab-41a2-b60d-30248326647a)

O.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Yes. It's expected and automatically generated by the browser when it's had a crash.

Nothing Waterfox specific here.
