### ISSUE TITLE
G6.0.4 -  about:config  no longer displays the usual Warning before taking the user into the settings

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#3222]
### What happened?

G6.0.4

**about:config**  no longer displays the usual  **"Proceed with Caution"**  prompt and warning before taking the user into the settings - it goes straight into the Settings.

Firefox still has the warning.

O.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Expected behaviour.
