### ISSUE TITLE
G6.0.4  -  Installing 6.0.4 over the top of 5.1.13 sets the  OPEN PREVIOUS WINDOWS AND TABS  setting

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#3224]
### What happened?

G6.0.4

Installing 6.0.4 over the top of 5.1.13 overwrites the  **Open Previous Windows and Tabs**  setting and sets it to ON !

![image](https://github.com/WaterfoxCo/Waterfox/assets/89191739/51dd1aaa-4b2e-4a68-9c98-7a78e30fb146)

O.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Yes. This is a change in G6 and you now get promoted when closing multiple tabs if you want to keep it this way.

Please read the release notes.
