### ISSUE TITLE
G.6.0.4  -  Block dangerous and deceptive content interferes with DNSFilter webfiltering

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#3226]
### What happened?

G6.0.4

The  **Block dangerous and deceptive content**  setting, which is turned on by default when installing 6.0.4 over the top of 5.1.13, interferes with  **DNSFilter  webfiltering** (Oblivious disabled, of course) and prevents DNSFilter from displaying its Website Blocked banner.

One has to disable this setting.

![image](https://github.com/WaterfoxCo/Waterfox/assets/89191739/643cfebf-1343-481c-8e53-6743b9eab5d3)

Not sure whether this categorizes as a bug but I am putting it out there for other users who upgrade to G6 and find that their **DNSFilter** webfiltering Block banners are not displaying.

O.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
You could make a post on Reddit for this.
