### ISSUE TITLE
G6 - Implement the Firefox  DISABLE UPDATES  registry key for Waterfox

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#3227]
There is a registry key for Firefox that is available and enables System Admins to set up **group policies** or  **logon scripts**  to disable auto updates on Firefox.

It would be good if the same was available for WaterFox.

The following explains how it works for Firefox.

![image](https://github.com/WaterfoxCo/Waterfox/assets/89191739/4db1347a-f01b-4d83-a7bd-cd0cad4a6944)

O.

**Comment by MrAlex94** [comment]
Waterfox doesn't prevent you from using group policies. They work in the same way, you just need to go to Waterfox's registry.

Feel free to do so.
