### ISSUE TITLE
Bring back native controls

### ISSUE THREAD

**Issue by the-r3dacted** [MrAlex94/Waterfox#3229]
**Is your feature request related to a problem? Please describe.**
Around Firefox 73 or so native controls were replaced with in browser ones. It was revertible for a bit, but they were removed.

**Describe the solution you'd like**
This contains a diff file for Firefox 115.3.1 ESR, this allows the use of native controls again.
https://github.com/ephemeralViolette/firefox-native-controls

**Describe alternatives you've considered**
I really don't think there's any other way

**Additional context**
This would for example replace the scrollbar with the native scrollbar. You still have to manually disable non-native controls in about:config, so this wouldn't effect normal users.

**Comment by IS4Code** [comment]
I believe this has been fixed by #3294.

**Comment by the-r3dacted** [comment]
I forgot I had opened this.
