### ISSUE TITLE
G6.0.4 Linux - About / References to Firefox in title and "Firefox is up to date"

### ISSUE THREAD

**Issue by SoloRobo** [MrAlex94/Waterfox#3235]
### What happened?

On G6.0.4 Linux 

Go to Burger Menu > Help > About Waterfox

Title reads "About Mozilla Firefox"
Checking for update returns "Firefox is up to date"

Other text references and links on this window follow a similar pattern:

![image](https://github.com/WaterfoxCo/Waterfox/assets/20973406/ab167069-5b6c-44b9-b392-1d4315b536fa)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by SoloRobo** [comment]
I've tried a fresh download of https://cdn1.waterfox.net/waterfox/releases/G6.0.4/Linux_x86_64/waterfox-G6.0.4.tar.bz2 and it isn't exhibiting any of the above, so perhaps the upgrade process bubbles these up.

It appears to be something related to which folder I am running waterfox-bin from. Possibly a GNOME bug, however I'm not sure how that manifests itself in the About window changing it's content.

**Comment by IanKemp** [comment]
I see the same thing on Windows 10 x64, my install is in `C:\Program Files\Waterfox`:

![image](https://github.com/WaterfoxCo/Waterfox/assets/1726434/bfed464e-8b89-4bb8-a94d-5443b820e96c)

**Comment by MrAlex94** [comment]
That's very odd - are you using any language packs that didn't come bundled with the browser? I can't reproduce this.

**Comment by SoloRobo** [comment]
Ah yes, I am using English (GB).

Changing it back to English (US) resolves the above.

**Comment by IanKemp** [comment]
I believe I have the same problem as @SoloRobo. Perhaps the language string lookup function could be patched to replace any mention of "Firefox" with "Waterfox" in these specific scenarios (although I'm sure that would be waaaaay down on the priority list).

![image](https://github.com/WaterfoxCo/Waterfox/assets/1726434/58150440-df2c-41af-9b16-1725ba72f0b5)

**Comment by MrAlex94** [comment]
Waterfox includes those language packs by default (and fixed to say Waterfox). You can go to the General page in preferences and scroll down to languages.

Could you uninstall the language packs you manually installed and try that instead?
