### ISSUE TITLE
G6.0.4 appearing as 'Out of date' on banking website (reporting as Firefox 115)

### ISSUE THREAD

**Issue by stu-carter** [MrAlex94/Waterfox#3239]
### What happened?

Waterfox is reporting itself as Firefox version 115 which was released in Jan 2023.  The latest Firefox available is 118 as of Oct 2023.

My e-banking site will block it soon as it considers it out of date, which is perhaps a little naive since 115 looks to have Extended Support.  I guess they just check if it is a certain number of versions older than the current.

Closing as it looks like a detection issue as Waterfox is not 'out of date'.

Thanks!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by stu-carter** [comment]
Closing as it looks like a detection issue as Waterfox is not 'out of date', it is based on Extended Support Release which does get security updates.

**Comment by daniandtheweb** [comment]
I've had issues like that on some sites. Just use some user agent editor extension to fake a newer version of firefox or chrome and most problematic pages will be fixed.

**Comment by stu-carter** [comment]
FYI for anyone in future.  I fixed the User Agent version without installing an extension.

Needed to add a new configuration setting in about:config.

- Name: general.useragent.override
- Type: String
- Value: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0

You can find the User Agent strings for Firefox here - https://www.whatismybrowser.com/guides/the-latest-user-agent/firefox
