### ISSUE TITLE
Execute custom JavaScript to fix browser's GUI, not website, not extension

### ISSUE THREAD

**Issue by jabcreations** [MrAlex94/Waterfox#3253]
I've fixed Vivaldi by using JavaScript to move GUI components in to their appropriate place and then cleaned up the remaining issues with CSS. This has worked quite well in making Vivaldi not so pointless combative.

Does Waterfox have a place that I can run my own custom JavaScript in the browser itself?

 - I am very aware of and regularly work with profiles in the AppData\Roaming\Waterfox directory.
 - I am very aware of and regularly work with AppData\Roaming\Waterfox\Profiles\\[profile]\chrome\userChrome.css
 - I am very aware of and can easily undo screwing up a profile.
 - I am very aware of and have not lost data from screwing up a profile.

So how do I run my own custom JavaScript to fix the browser's GUI?

**Comment by robbely** [comment]
It sounds like you want userchromejs - there are several tutorials for this (though from your post I imagine you can readily skip past bits). Here is the one I used:

[https://github.com/xiaoxiaoflood/firefox-scripts/tree/master#instructions](url)

The site also has lots of useful examples

EDIT: you might need to copy/paste the link as github seems to be sending it somewhere else.

**Comment by jabcreations** [comment]
Thank you though I managed to figure it out thanks to some help over at Mozillazine which you are welcomed to check out at [http://forums.mozillazine.org/viewtopic.php?f=38&t=3114953&p=14966172](http://forums.mozillazine.org/viewtopic.php?f=38&t=3114953&p=14966172). I'm actually trying to get back on finishing creating a more user-friendly tutorial over at the Fixed Firefox website though work takes precedence. Any way, thank you for taking the time to respond, I appreciate it!

**Comment by robbely** [comment]
You're very welcome - I'm glad you got it sorted :)
