### ISSUE TITLE
Bump the display version (the 115.x.x one)

### ISSUE THREAD

**Issue by aaronliu0130** [MrAlex94/Waterfox#3256]
**Is your feature request related to a problem? Please describe.**
The display version has remained the same across .03 to .05. This is very confusing to Windows‘s “Apps and Features” feature and package managers such as https://github.com/microsoft/winget-pkgs/pull/122324#issuecomment-1791532249 . 

**Describe the solution you'd like**
Bump that version according to semantic versioning every release.

**Describe alternatives you've considered**
Just use the G-something version as the display version

**Comment by aaronliu0130** [comment]
I accidentally pressed enter, still filling this out, hold on

Edit: Finished filling this out

**Comment by MrAlex94** [comment]
We should be reporting the display version rather than the "milestone" version - I'll try get a patch out for this.

**Comment by aaronliu0130** [comment]
that was done

**Comment by metaad** [comment]
application getting upgrade from G6.0.7 to G6,0.8 (ARP version). but registry entry version is not changing - Waterfox 115.7.0 (x64 en-US). this is same for both G6.0.7 & G6.0.8. could you please help us with this issue.

**Comment by aaronliu0130** [comment]
@metaad That would be a product code. What would you need it for?

**Comment by metaad** [comment]
which one can we consider as the version number

**Comment by aaronliu0130** [comment]
The ARP one, of course. The product code is purely internal

**Comment by metaad** [comment]
Okay, Thank you!!
