### ISSUE TITLE
Waterfox website: hoisted.js

### ISSUE THREAD

**Issue by JeanPaulLucien** [MrAlex94/Waterfox#3263]
Do you care how many browser will be possible to work with website correctly? 
I found hoisted.js but did not find what is it. I'm worried because creator who has wrote hoisted.js has dropped Firefox below 91.

I suggest to describe what tasks does hoisted.js and I recommend to not use that, use something other instead or somebody could write something with same feaures.

**Comment by MrAlex94** [comment]
Nothing to do with that library. 
Waterfox uses Astro to statically generate its website.
Hoisting is what [Astro does](https://docs.astro.build/en/guides/client-side-scripts/) when you use `<script>` tags.

**Comment by JeanPaulLucien** [comment]
Javascript is not necessary for websites. JS spends additionally computing capacities of website visitors. 3-rd party scripts decrease compatibility. Yeah, that is all where people spend GBs of RAM and KWtt of energy.

**Comment by JeanPaulLucien** [comment]
![image](https://github.com/WaterfoxCo/Waterfox/assets/24779886/36307d3a-d6bd-4861-a104-e7b16e0700da)
As I said website without issues with Firefox 91+ (summer 2021). I'm here because I'm old-school user.
