### ISSUE TITLE
Chrome Extension pages no longer showing "Add to Waterfox"

### ISSUE THREAD

**Issue by robbely** [MrAlex94/Waterfox#3264]
### What happened?

Probably a recent change with the chrome web store, you are no longer able to try and add a chrome addon to Waterfox with a simple button click (as was previously available).

I also tried this with a clean installation and new profile and still had the same issue.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by FIRECRAFT2534** [comment]
Yea same problem

**Comment by MrAlex94** [comment]
Yes, will need to re-work the browser detection. Added to the list!

**Comment by FIRECRAFT2534** [comment]
> Yes, will need to re-work the browser detection. Added to the list!

Thanks alot.

**Comment by yodaluca23** [comment]
It works on the old version of the Chrome web store, just not the new redesigned version, some websites link to the old one, and it works, but for some reason if you try to get to it manually it redirects to the new one. Any ETA for a fix?

edit, paste "https://chrome.google.com/webstore/old" and you can go to the old version, but still sometimes the add to WaterFox button is glitchy and stuff, I can only get some extensions to install...
