### ISSUE TITLE
Waterfox 6.0.5 - AdBlock Plus add-in is detected on YouTube

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#3270]
### What happened?

The AdBlock Plus add-in is detected by YouTube -

![image](https://github.com/WaterfoxCo/Waterfox/assets/89191739/0aa72ea4-c432-45a4-a1a3-f75cb002e3a3)

This does not happen in Firefox nor Microsoft Edge.

O.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by zeeid** [comment]
Its Not Waterfox Problem, youtube update their ads block detector

i use AdGuard Extension
and update filter adguard
then your youtube is clean 
u can try it

**Comment by technikker** [comment]
Waterfox Devs are not responsible for adblock and other 3rd party extensions you downloaded from the addons store, they are provided by a 3rd party.  You need to send this report to the Adblock+ team, as there is nothing the devs here can do.

or you could try this adblocker, works for me on youtube currently:
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
