### ISSUE TITLE
High CPU usage when opening/playing youtube

### ISSUE THREAD

**Issue by zeeid** [MrAlex94/Waterfox#3272]
### What happened?

Hello
Good Morning

when opening YouTube and playing a video
waterfox CPU usage becomes very large
until it makes my Windows 10 lag
![waterfox high cpu useage](https://github.com/WaterfoxCo/Waterfox/assets/79952361/7ee3bb5d-9b99-42c0-8136-56d91e2e412d)

![image](https://github.com/WaterfoxCo/Waterfox/assets/79952361/ba81ea6e-8ccb-4dde-957c-86b17439fb26)

Please Fix it
Thank you

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by zeeid** [comment]
My PC 
Windows 10 64 Bit
CPU | Intel® Core™ i5-10500H
VGA | NVIDIA GeForce® RTX 3050 4GB
RAM | 32GB DDR4

**Comment by technikker** [comment]
I have seen this issue also.  It is not actually a Waterfox bug.  Youtube has introduced a "feature" into youtube that causes firefox browsers to lag while running the site.  Seems to get worse the more tabs you have open.

By installing a User Agent Switch, and spoofing your browser as a Chromium based browser, the issue resolves.

Try one of these extensions (to your preference) to spoof your browser as being Chrome:
https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/
https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/

I also cleared my browsing data for youtube.com in "Privacy and Security" before changing the UAS, but not sure if this is required or not.

See here for further description:
https://www.youtube.com/watch?v=v4gXhmzQztE

**Comment by technikker** [comment]
Since this seems to be a deliberate act by google to target firefox (by making it seem slow to the average user, so they will switch to chrome), perhaps it's time to consider a built in user agent switch that is automatically enabled for websites known for this issue.

The average user does not want to have to play with extensions and user agent strings just to watch youtube on firefox.

**Comment by zeeid** [comment]
Ohh i see
Thank you for the information

Once again, fraud and injustice is being carried out by Google 🥲

Mozila should make an official statement about this, if they don't want their loyal users to leave

**Comment by technikker** [comment]
No problem, I've created a feature request to hopefully stop this nonsense from happening.

https://github.com/WaterfoxCo/Waterfox/issues/3274

**Comment by zeeid** [comment]
> No problem, I've created a feature request to hopefully stop this nonsense from happening.
> 
> #3274

![image](https://github.com/WaterfoxCo/Waterfox/assets/79952361/c32d17e3-f58f-4ebf-9e3c-c4ec42796a56)
![image](https://github.com/WaterfoxCo/Waterfox/assets/79952361/ee3fdbc8-0942-4725-b390-a76d4306f44a)


its really true google doing fraud and injustice for browser non chromium
i chane user agent to chrome, then the CPU drop from 40% to under 10% and drop to 3% after view minute playing youtube videos

**Comment by ioc2e3** [comment]
> 用戶代理更改

concerned ...

( Changing User Agent ) How long will this method last?
