### ISSUE TITLE
Built in, automatic UAS in response to Google's anti-competitive business practice

### ISSUE THREAD

**Issue by technikker** [MrAlex94/Waterfox#3274]
**Is your feature request related to a problem? Please describe.**
There is mounting evidence that google (and more specifically youtube) are targeting firefox/waterfox with underhanded tactics, specifically by causing youtube to run much slower on firefox based browsers (for some users, others are unable to replicate, much like the issues with adblockers not working)

**Describe the solution you'd like**
A built in / pre installed extension User Agent Switch (UAS).  The built in UAS should support custom UA string per container and per window, as well as "site rules", which apply the custom UA string to a whole domain.  The user should be able to select per container whether site rules take precedence over container/window rules.  While existing UAS extensions exist, as far as I know, they all fall short when it comes to compatibility with both container and site rules together.  With the 3rd party UAS's 2 I've tried, 1 supports container rules, while the other supports site rules, so my proposal would not only resolve the issue, but provide a more customizable UAS tool than currently exists.

Most importantly, the built in UAS should be automatically enabled for websites known for this issue via a site rule that by default overrides container/window rules, to ensure that the average user does not have to concern themselves with this nonsense.

**Describe alternatives you've considered**
There are 2 User Agent Switchers I've tried:
https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/
https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/
Both of these resolve the issue, however if google is going to continue to do this, my concern is firefox/waterfox will lose market share, as the average user does not want to know about User Agent Strings and how to change them via extensions just to watch youtube.  From the standpoint of the average user, without automatic, built in countermeasures, it is much easier just to switch to chrome (ugh, I feel dirty just saying it).  

**Additional context**
bug reports describing the same/similar issue:
https://github.com/WaterfoxCo/Waterfox/issues/3272
https://github.com/WaterfoxCo/Waterfox/issues/3260

**Comment by aaronliu0130** [comment]
I believe bundling ublock origin would be a much better way. Currently I have that and the first YouTube video I clicked loaded in 2 or 3 seconds without a useragent switch.

**Comment by technikker** [comment]
I believe it is possible to solve this issue with uBlock via a custom filter, that is an option too I suppose, however just having uBlock installed is not enough, and did not work for me.  It should be noted that this "feature" does not consistently appear for all users, some are unable to replicate.

Additionally, I experienced high CPU use from youtube, as https://github.com/WaterfoxCo/Waterfox/issues/3272 did, which maybe could be solved by a custom filter, but this is actually a separate issue from the 5 second wait time originally reported.

I guess uBlock is a cleaner solution, but it would have to be proactively updated against google's methods, and the issue is they roll out these "features" progressively, meaning it would take some days or even weeks before the devs here even find out about anything else they do.  I believe I was experiencing the 5s wait time for perhaps a week (I have slow internet anyway), it wasn't until the high CPU usage started that I noticed something was wrong.

Although even if uBlock doesn't solve the problem, I'm still not against bundling it.

**Comment by aaronliu0130** [comment]
Have you updated your filter lists?

**Comment by technikker** [comment]
It's on autoupdate, but that won't prove anything because I'll have to get it to happen again to test it.

The fact that youtube works fine for you doesn't prove anything, because the issue doesn't consistently happen to all users, many were unable to replicate.

**Comment by technikker** [comment]
Nevermind, as more information is available, this seems to be an adblock, not a waterfox/firefox issue.

https://www.theverge.com/2023/11/21/23970721/google-youtube-ad-blocker-five-second-delay-firefox-chrome

**Comment by technikker** [comment]
Nevermind, as more information is available, this seems to be an adblock, not a waterfox/firefox issue.

https://www.theverge.com/2023/11/21/23970721/google-youtube-ad-blocker-five-second-delay-firefox-chrome

**Comment by aaronliu0130** [comment]
It's actually a mix... If rolled out, the feature will introduce a five-second delay to test for adblockers.

**Comment by ioc2e3** [comment]
> 廣告

( really ) don't understand advertisers ...

User ( doesn't want to see ads and be tracked ) ...

What's wrong with that ?

.
