### ISSUE TITLE
Latest Version (G6.0.6) is displaying as version G5.0.2 in the WinGet repository

### ISSUE THREAD

**Issue by Cynyster** [MrAlex94/Waterfox#3276]
### What happened?

I have manually upgraded the latest Version G6.0.6.
Winget is still reporting the installed version as G5.0.2

I have uninstalled Waterfox  and reinstalled with a fresh installed from the Waterfox web site and the issue persists.
<img width="443" alt="Capture" src="https://github.com/WaterfoxCo/Waterfox/assets/17557566/2aa129f8-fe73-4ab4-880a-33c446f0663b">

Note: I do not have Waterfox installed in the default location. All my Apps get installed to d:\programs\

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
WinGet packages are volunteer contributed; so maybe something to file in the winget-pkgs repo?
