### ISSUE TITLE
closing last tab closes the browser

### ISSUE THREAD

**Issue by legacychimera247** [MrAlex94/Waterfox#3278]
**Is your feature request related to a problem? Please describe.**
i'm used to close the last tab on the browser, and go back to the home screen, instead waterfox closes the app, we should have an option to just go to home instead of closing the app, it's seriously frustrating (at least for me :P )

**Describe the solution you'd like**
i would like to have an option that make the browser opening the home screen when closing the last tab, instead of closing the entire app

**Describe alternatives you've considered**
well actually i'm using another browser that let me do this, vivaldi (which is seriously good) but i would love to use something non chromium based, and this is quite preventing me to do that...

**Additional context**
i'm on fedora linux but i guess it does not matter since this function should be system independent...

**Comment by wbak1102** [comment]
Prevent the browser from closing through the last card
about:config
browser.tabs.closeWindowWithLastTab = change to - false

**Comment by legacychimera247** [comment]
thank you, this made my day, althought it should not be this hidden...
