### ISSUE TITLE
Clicking in url outside waterfox not working

### ISSUE THREAD

**Issue by GuerillaUmNeon** [MrAlex94/Waterfox#3279]
### What happened?

Clicking on a link in an app opens a cache file instead of the www url since G6.0.6
Everything works fine with an other browser as default.
![Screenshot_20231125_172311](https://github.com/WaterfoxCo/Waterfox/assets/58876738/08937d08-3723-4c5a-845a-b53bfa41b35a)

Linux OpenSUSE Tumbleweed

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Are you using the official Waterfox tarball or from an unofficial repo?

**Comment by GuerillaUmNeon** [comment]
I am using the official tarball

**Comment by GuerillaUmNeon** [comment]
It was a problem with KDE Plasma. 
Solved using [this](https://www.reddit.com/r/kde/comments/jgm2l4/comment/gdcbna7/)
