### ISSUE TITLE
Disable Control + W from closing tab when used to wrap text

### ISSUE THREAD

**Issue by jabcreations** [MrAlex94/Waterfox#3289]
### What happened?

At some point someone thought it was a good idea to make Control + W close a tab. How do we kill it with extreme prejudice? This is an issue with Firefox 115 ESR too unfortunately.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by thunderstone135** [comment]
Ctrl + W is a universal keyboard shortcut. Meaning it's hardcoded in Windows and not Firefox or Waterfox.
https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec

It's under File Explorer keyboard shortcuts.

If you are adamant in changing any keyboard shortcut to something else, take a look at this article 👇
https://superuser.com/questions/1271147/change-key-bindings-keyboard-shortcuts-in-firefox-quantum

@MrAlex94, if you decide to make changes to keyboard shortcuts, I just want to let you know that some people are already used to specific keyboard shortcuts (especially universal ones). What I suggest is to make an interface to allow users to change keyboard shortcuts or reset them.

**Comment by goodusername123** [comment]
@jabcreations 

Does changing the value of [`browser.closeShortcut.disabled`](https://github.com/WaterfoxCo/Waterfox/pull/3255) in `about:config` solve this issue for you?

**Comment by jabcreations** [comment]
> @jabcreations
> 
> Does changing the value of [`browser.closeShortcut.disabled`](https://github.com/WaterfoxCo/Waterfox/pull/3255) in `about:config` solve this issue for you?

**GLORIOUS! ABSOLUTELY GLORIOUS!**

I did not realize that it was Waterfox specific however I have been using Classic and this is a fantastic fix! Too bad Firefox doesn't use it but whatever, Waterfox Current is replacing Classic as my default browser this week. Thank you guys for having working brains! 😍︀

I should mention to anyone coming across this page that **_I did have to restart Waterfox Current for it to work_** though that is still 100% tolerated since it doesn't take almost a minute to restart.
