### ISSUE TITLE
waterfox G6.0.7 full screen on windows 8/8.1 fullscreen showing taskbar

### ISSUE THREAD

**Issue by wtfiwinomgs** [MrAlex94/Waterfox#3303]
### What happened?

as title says, when watching youtube vids on G6.0.7, clicking full screen on windows 8/8.1 showing taskbar same with pressing F11. need fix ty

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
there are no error or log, just full screen showing windows taskbar
```

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/issues/3246

**Comment by wtfiwinomgs** [comment]
> #3246

so can this be reopened? really wish this would be fixed on next version..
