### ISSUE TITLE
I knew I wasn't losing it

### ISSUE THREAD

**Issue by AnonymousRonin** [MrAlex94/Waterfox#3305]
### What happened?

Well that's disappointing to say the least.  I thought at first I was going nuts but no, my settings are being chanbged without my consent or knowledge.  Ironically it's always the settihgs related to location, tracking, search suggestions etc etc.  I figured out Brave's little slight of hand too, you know why you have to enter all your search quearies in the url bar?  In fact there is no option I'm aware of that allows a homepage searchg box in Brave.  That's how they collect infio from everyone.  You guys just change the settings thinking most won't go back and check.  I liked your browser too, on to the next one.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
If I knew the settings that trigger I would.  And there's too many browser choices to waste time looking thrrough source code.
```

**Comment by MrAlex94** [comment]
The last release has no changes to settings. What did you see change?

**Comment by AnonymousRonin** [comment]
I'm not talking about a release, I'm talking about my settings.  They are continually being undone.  And ironically not in a way I would prefer.  My location is re-enabled everytime I use it.  The boxes for saving my browsing and download history are re-checked.  Now your browser is downloading a copy of everything I download and saving to it's own folder.  I would say these are beyond a bug or two and it seems to follow right along with the nut cases that have ruined firefox.  I'm just over the whole thing.

**Comment by AnonymousRonin** [comment]
You guys are wholly owned buy a data collection and analytics company.  Hmmm, I wonder a company like that would buy a web browser?
