### ISSUE TITLE
"WebUI" project is using the waterfox logo.

### ISSUE THREAD

**Issue by jakenvac** [MrAlex94/Waterfox#3318]
Apologies for raising a "feature request". I thought it was the more apt option vs a bug report.

The "[WebUI](https://github.com/webui-dev/webui)" project is using a modified version of the waterfox logo - I couldn't find any evidence of an agreement where this was allowed.

As a hobbyist graphic designer I'd be upset if I found my works being used without permission so I thought I'd raise it. Please feel free to tell me to mind my own business.

Here's a screenshot of the readme:
![image](https://github.com/WaterfoxCo/Waterfox/assets/9119973/0cc78773-5b37-425e-9279-04ec6756a18d)

I've raised an issue on the webui project here:
https://github.com/webui-dev/webui/issues/291

**Comment by MrAlex94** [comment]
Thanks for bringing this to my attention @jakenvac! I've sent a message across in the issue you've raised and will try find an email to contact them through.
