### ISSUE TITLE
waterfox doesn't download pdf version of form on grants.gov

### ISSUE THREAD

**Issue by totherpage955** [MrAlex94/Waterfox#3319]
### What happened?

i had a grants.gov workspace open and i needed to complete a form as part of the grant application so i downloaded the form which was a secure pdf. in waterfox the file didn't download but a new tab opened. in firefox the file downloaded. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

macOS

**Comment by lazymonkey2** [comment]
in settings -> general there is an option to specify what to do with different applications.
pdf files are set to be downloaded?

**Comment by totherpage955** [comment]
i changed it to download and this fixed the issue thank you
