### ISSUE TITLE
on github bug report form is missing android platform

### ISSUE THREAD

**Issue by lazymonkey2** [MrAlex94/Waterfox#3333]
### What happened?

I want to send bug reports for waterfox on android.
In the guthub form I'm asked "What platform are you seeing the problem on?" but Android platform is missing.
It shows only linux, macOS and windows.
Please add Android too.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by lazymonkey2** [comment]
closed but android still missing:
![image](https://github.com/WaterfoxCo/Waterfox/assets/26486758/f64b4a9c-1793-4915-bdd9-47f5e03d4910)

**Comment by MrAlex94** [comment]
Issues are open on the Android repo :-)

**Comment by lazymonkey2** [comment]
oh sorry I didn't know.
is this one?
https://github.com/WaterfoxCo/Waterfox-Android
