### ISSUE TITLE
"Don’t enable HTTPS-Only Mode" option does not work

### ISSUE THREAD

**Issue by DetachHead** [MrAlex94/Waterfox#3346]
### What happened?

http://www.bom.gov.au does not work on waterfox when HTTPS-Only mode is disabled:

![image](https://github.com/WaterfoxCo/Waterfox/assets/57028336/7e1f7906-9f32-4d45-b591-f2350442e344)

![image](https://github.com/WaterfoxCo/Waterfox/assets/57028336/9d12739a-6f85-45aa-91a7-04675df7b7dd)

according to [this thread](https://connect.mozilla.org/t5/discussions/waterfox-not-displaying-a-weather-website-that-firefox-will/td-p/41079), the solution is to enable https-only mode, then add the website as an exception. this worked for me, but i don't want to have to do this with every http only website i come across.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Could you go to `about:config` and search for `dom.security.https_first` and toggle it to `false` and try then?

**Comment by DetachHead** [comment]
@MrAlex94 that works. should that option be `false` by default then if it's handled by the user-facing https-only setting?

**Comment by MrAlex94** [comment]
So, HTTP only takes precedence, if both are enabled. But realistically it might be worth having `https_first` on and HTTP everywhere off. I'll consider changing but may keep it as is for the time being, and hopefully not too many people experience this edge case.

**Comment by DetachHead** [comment]
That doesn't seem very user friendly though. Currently this means there's a user-facing setting that doesn't do anything unless you navigate to the hidden advanced settings to disable a different flag.

Maybe the user-facing setting should be removed/hidden when that flag is set?
