### ISSUE TITLE
Why do I see Waterfox KDE in Linux Mint GTK?

### ISSUE THREAD

**Issue by timur-g** [MrAlex94/Waterfox#3351]
### What happened?

Using Linux Mint 21.3 GTK, that recently got support for Wayland.
Waterfox from hawkeye116477 PPA, long time OK including upgrades. 
Waterfox upgrade to G6.0.8 went wrong and I had to fix it. After that, I see that Waterfox is KDE, why? 
Previously I think I had waterfox-g-kpe, now I see "transitional package" and really just waterfox-kde and waterfox-wayland. 

Side issus is that on every upgrade I get a new default empty profile, so I have to edit it manually to restore the previous one.

### Version
G6

### What platform are you seeing the problem on?
Linux Mint 21.3

**Comment by hawkeye116477** [comment]
All issues with my packages should go to <https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/issues>. 
In case of package name, that's just renaming to more proper name (it will still work fine on non-KDE), other problems should be fixed now :smile:.

**Comment by timur-g** [comment]
Thanks @hawkeye116477 It is great what you do, good that it was transient issue.
