### ISSUE TITLE
G5: Widevine DRM plugin outdated

### ISSUE THREAD

**Issue by rthom91** [MrAlex94/Waterfox#3366]
### What happened?

Spotify and Peacock TV are now broken, and most likely many others.

I've narrowed it down solely to the Widevine DRM plugin.

 Latest Waterfox G5 version (download) - 4.10.2557.0.
 Latest Firefox/Waterfox G6 version (native) - 4.10.2710.0.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

**Comment by HBunnick** [comment]
Seems to be related to #3210

**Comment by MrAlex94** [comment]
Unrelated; G5 won't receive an updated version of the CDM as it's not compatible.
