### ISSUE TITLE
Broken AUR Installer/Update Package (ArchLinux)

### ISSUE THREAD

**Issue by TrazhCant** [MrAlex94/Waterfox#3383]
### What happened?

When attempting to update via AUR (using yay -Syyu), the process fails.

Terminal output posted in "Relevant log output".

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
:: Synchronizing package databases...
 endeavouros            20.9 KiB  17.0 KiB/s 00:01 [----------------------] 100%
 core                  128.5 KiB   390 KiB/s 00:00 [----------------------] 100%
 extra                   8.3 MiB  6.90 MiB/s 00:01 [----------------------] 100%
 multilib              140.6 KiB   443 KiB/s 00:00 [----------------------] 100%
:: Searching AUR for updates...
:: Searching databases for updates...
 -> Packages not in AUR: gnome-shell-extension-gsconnect45
 -> Orphan (unmaintained) AUR Packages: entityx  stacer-bin
 -> joy2key: local (1.6.3-4) is newer than AUR (1.6.3-3)
:: 1 package to upgrade/install.
1  aur/waterfox-bin  G6.0.8-1 -> G6.0.9-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
 -> Excluding packages may cause partial upgrades and break systems
==> 
AUR Explicit (1): waterfox-bin-G6.0.9-1
:: PKGBUILD up to date, skipping download: waterfox-bin
  1 waterfox-bin                     (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  1 waterfox-bin                     (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: waterfox-bin G6.0.9-1 (Fri 22 Mar 2024 10:07:30 AM PDT)
==> Retrieving sources...
  -> Found waterfox.desktop
  -> Found waterfox-G6.0.9.tar.bz2
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha512sums...
    waterfox.desktop ... Passed
    waterfox-G6.0.9.tar.bz2 ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: /home/nutzhell/.cache/yay/waterfox-bin 
	 context: exit status 1 
	 

:: (1/1) Parsing SRCINFO: waterfox-bin
==> Making package: waterfox-bin G6.0.9-1 (Fri 22 Mar 2024 10:07:31 AM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found waterfox.desktop
  -> Found waterfox-G6.0.9.tar.bz2
==> Validating source files with sha512sums...
    waterfox.desktop ... Passed
    waterfox-G6.0.9.tar.bz2 ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error making: waterfox-bin-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
waterfox-bin - exit status 1
```

**Comment by TrazhCant** [comment]
This has been an issue for quite a while.  I see this somewhat regularly with Arch/AUR in general, but Waterfox in particular has been consistently broken for a long time  (months I think?).  Most of the time a broken package will be corrected by the respective devs within a day or a couple weeks.  Basically, when I see a broken package like this, I don't really report it right away because I presume it's either already reported, or the active devs will discover it in due time anyway.  So I just run yay updates a couple days or a week later and stuff usually is successful then.  In this case, I think it's been broken for 2 versions at this point.  (G608 and G610 is the current version I believe?).  Thanks in advance.  /hugs :)

**Comment by TrazhCant** [comment]
I was able to overcome this error by manually cloning the AUR and making the package.

```
git clone https://aur.archlinux.org/waterfox-bin.git
makepkg -si
```

This resulted in a successful install/update.

**Comment by aaronliu0130** [comment]
Report to the package's maintainer and flag it as out of date. Some time ago the G6.0.9 checksums were changed for some reason.

Also, flag it as out of date since .10 is out anyways.

**Comment by TrazhCant** [comment]
OK flagged, commented, trying to sound all smarty-pants, clearly not a dev.  ;)

**Comment by MrAlex94** [comment]
> Report to the package's maintainer and flag it as out of date. Some time ago the G6.0.9 checksums were changed for some reason.
> 
> Also, flag it as out of date since .10 is out anyways.

We didn't change anything regarding checksums - likely the way the package grabs them has failed, probably due to https://github.com/WaterfoxCo/Waterfox/issues/3394.

But yes, since we don't maintain the packages nothing we can do :-)

**Comment by hawkeye116477** [comment]
Well, sometimes Waterfox tarball packages were like ninja (there was for example problem with building for other OS, so someone removed Linux package and added later again, but it had newer date), so that could be the reason of past problems with checksums (at least those before G6.0.9).

Anyway latest package checksums should be fine. If it will be wrong again, then anyone can mark package as out of date and write.
