### ISSUE TITLE
New children or sibling tabs are not immediatly registered in the sidebar if not opened at the bottom (only recognized after selecting the bottom tab)

### ISSUE THREAD

**Issue by jh34ghu43gu** [MrAlex94/Waterfox#3387]
### What happened?

Opening a new tab via middle click, ctrl click, any of the new tab button besides the independent tab button, new tab in context menu, or with the tab bar (last 2 not shown in attached video) does not appear in the tab tree until the bottom tab is selected (possibly more triggers). Expanding or collapsing the tree that the tab was put into does not do anything and appears as an empty tree. 

Example video: [https://youtu.be/lvasgeOCl58](https://youtu.be/lvasgeOCl58)
Settings for auto-organize at time of recording (the other settings can be seen at 47s in the video): [https://imgur.com/CJIAv1P](https://imgur.com/CJIAv1P)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by njwgh** [comment]
same here. on windows

**Comment by jh34ghu43gu** [comment]
This appears fixed in G6.0.13
