### ISSUE TITLE
Can't get hash for downloads

### ISSUE THREAD

**Issue by hawkeye116477** [MrAlex94/Waterfox#3394]
### What happened?

I can't copy hash for browser download (<https://www.waterfox.net/download/>) using Chromium browsers, for example Vivaldi 6.6.3271.45.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

### Relevant log output

```js
This document requires 'TrustedHTML' assignment.
Uncaught (in promise) TypeError: Failed to execute 'insertAdjacentHTML' on 'Element': This document requires 'TrustedHTML' assignment.
```

From what I read this is some security feature of Chromium browser and maybe CSP would need to be adjusted to fix that.

**Comment by MrAlex94** [comment]
I've opened a support request with Astro: https://discord.com/channels/830184174198718474/1222860158347247629

**Comment by MrAlex94** [comment]
Have fixed this!
