### ISSUE TITLE
About window update button white text almost unreadable

### ISSUE THREAD

**Issue by joatmon3** [MrAlex94/Waterfox#3399]
### What happened?

In the About Waterfox window, when there is an update available, the button to update that says "Update to Gx.x.x" in white text is almost unreadable on the very light blue/white background. I use dark mode in my OS, and Waterfox, and the dark theme, but even if all these are changed to light mode the issue persists. 

An easy fix would probably be to just give the button a non-transparent, darker background, or change the text to a darker color. 
Firefox has a dark background for this window so the issue is not evident there. 
![Screen Shot 2024-03-27 at 09 22 06](https://github.com/WaterfoxCo/Waterfox/assets/791990/e332c349-e475-4cb6-9a0c-637a8141cf51)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

macOS

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/1a3260103ccc9435abab2b84f265b08ae5217ed7
