### ISSUE TITLE
Tabs Sidebar still present in fullscreen

### ISSUE THREAD

**Issue by Jonathing** [MrAlex94/Waterfox#3401]
### What happened?

When in full screen (via YouTube or by pressing F11), the tabs sidebar does not hide with the rest of the UI.

I am on a Steam Deck, using the Flatpak distribution of Waterfox running G6.0.11.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
This has been fixed in G.0.12 due soon.
