### ISSUE TITLE
Addon install failed beause of old user agent

### ISSUE THREAD

**Issue by dfgrgavr** [MrAlex94/Waterfox#3405]
### What happened?

Hello!

I using Waterfox for a long time ago, and i really love it, so thanks the good work! 
G6.0.11

Today i tried to install Enchancer for youtube addon, and it says:
**"You need an updated version of Firefox for this extension"** 
So i tried to downlad the xpi file, and it says:
**"could not be installed because it is not compatible with waterfox 115.10.0"** 
Okay, i installed some user agent switcher, add to firefox button appers to active, but still says:

 **"could not be installed because it is not compatible with waterfox 115.10.0"**

Okay, i modded the manifest.json in the xpi file, and i was able to install, and it works, meanwhile, on the addon setting page says:
**"Enhancer for YouTube™ could not be verified for use in Waterfox. Proceed with caution."**

I tried to set in about:config  **general.useragent.override**  string Mozilla/5.0 (Windows NT 10.0; rv:124.0) Gecko/20100101 Firefox/124.0  but problem still appears.

Any suggestion? 

Thanks in advance.

Have a really nice day!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by wbak1102** [comment]
It's not Waterfox's fault but the extension's

**Comment by dfgrgavr** [comment]
> It's not Waterfox's fault but the extension's.You need to modify the extension
As i wrote: "_Okay, i modded the manifest.json in the xpi file, and i was able to install, and it works,......_"

Still strange why waterfox identifies itself as an almost a year older version of firefox.

**Comment by dfgrgavr** [comment]
> It's not Waterfox's fault but the extension's.You need to modify the extension

    As i wrote: "_Okay, i modded the manifest.json in the xpi file, and i was able to install, and it works_,......"

Still strange why waterfox identifies itself as an almost a year older version of firefox.

**Comment by dfgrgavr** [comment]
> It's not Waterfox's fault but the extension's.You need to modify the extension


As i wrote: "_Okay, i modded the manifest.json in the xpi file, and i was able to install, and it work_s,......"

Still strange why waterfox identifies itself as an almost a year older version of firefox.

**Comment by thunderstone135** [comment]
> Still strange why waterfox identifies itself as an almost a year older version of firefox.

Waterfox has **_always_** been based on Firefox ESR.
This information is available in the **_Waterfox Docs page_** (e.g., [1](https://www.waterfox.net/docs/releases/G4.0.0/) [2](https://www.waterfox.net/docs/releases/G5.0b1/) [3](https://www.waterfox.net/docs/releases/G6.0b1/)).

**Comment by dfgrgavr** [comment]
> > Still strange why waterfox identifies itself as an almost a year older version of firefox.
> 
> Waterfox has **_always_** been based on Firefox ESR. This information is available in the **_Waterfox Docs page_** (e.g., [1](https://www.waterfox.net/docs/releases/G4.0.0/) [2](https://www.waterfox.net/docs/releases/G5.0b1/) [3](https://www.waterfox.net/docs/releases/G6.0b1/)).

I see. Only lthe thirdf link talks about esr, a check some other releases docs too. But okay, then ESR it is.

**Comment by dfgrgavr** [comment]
> > Still strange why waterfox identifies itself as an almost a year older version of firefox.
> 
> Waterfox has **_always_** been based on Firefox ESR. This information is available in the **_Waterfox Docs page_** (e.g., [1](https://www.waterfox.net/docs/releases/G4.0.0/) [2](https://www.waterfox.net/docs/releases/G5.0b1/) [3](https://www.waterfox.net/docs/releases/G6.0b1/)).

I see. Only your third link talks about esr, a check some other releases docs too. But okay, then ESR it is.

**Comment by dfgrgavr** [comment]
Then we can close the case.

**Comment by thunderstone135** [comment]
> Only your third link talks about esr, a check some other releases docs too.

Back in the days, they call it Gecko then version number.

**Comment by juryrigging** [comment]
Just as a small epilogue to this issue, as of an update today the add-on works with Firefox ESR.
