### ISSUE TITLE
Tabs Sidebar showing when Fullscreen Video is active

### ISSUE THREAD

**Issue by CeptForHer** [MrAlex94/Waterfox#3408]
### What happened?

Title pretty much explains the problem. When the tabs sidebar is active, it does not disappear when watching a fullscreen video. This works properly for the normal sidebar(history, bookmarks, etc.), just not the tabs sidebar.
Screenshot below for context:
![](https://anime.ceptforher.com/images/2bvnm.png)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Thanks for reporting! This has been fixed and will be in G6.0.12.
