### ISSUE TITLE
Consider dropping SSSE3 requirement

### ISSUE THREAD

**Issue by the-r3dacted** [MrAlex94/Waterfox#3410]
I did some testing, and found that nothing after SSE2 seems to give any noticeable performance improvement in any browser. Unless there's something I'm not looking at, this requirement should be dropped since it's useless and breaks a lot of still very usable processors.

My testing: https://board.eclipse.cx/viewtopic.php?t=669

**Comment by MrAlex94** [comment]
This is actually the plan; the last few years, the performance improvements have become negligible by specifying higher `march` values.

**Comment by Squall-Leonhart** [comment]
> I did some testing, and found that nothing after SSE2 seems to give any noticeable performance improvement in any browser. Unless there's something I'm not looking at, this requirement should be dropped since it's useless and breaks a lot of still very usable processors.
> 
> My testing: https://board.eclipse.cx/viewtopic.php?t=669

SSSE3 benefits 3D transforms, so look at things like JS model viewers

**Comment by the-r3dacted** [comment]
If it helps something here it would probably be software Motionmark, which shows no change. Might just automatically take advantage of it.

**Comment by MrAlex94** [comment]
> > I did some testing, and found that nothing after SSE2 seems to give any noticeable performance improvement in any browser. Unless there's something I'm not looking at, this requirement should be dropped since it's useless and breaks a lot of still very usable processors.
> 
> > 
> 
> > My testing: https://board.eclipse.cx/viewtopic.php?t=669
> 
> 
> 
> SSSE3 benefits 3D transforms, so look at things like JS model viewers

Definitely, but usually there will be manually crafted code paths to take advantage of SIMD. For example: https://searchfox.org/mozilla-central/search?q=SSSE3&path=&case=false&regexp=false

You'll see it for a lot of the useful instruction sets such as AVX, AES etc. The march/mtune flags are useful for automatic generation of those instructions if they feel code can be compiled to do so, but realistically the performance differences won't be as improved as they would have been historically.
