### ISSUE TITLE
"message-box" has empty font on KDE?

### ISSUE THREAD

**Issue by aaronliu0130** [MrAlex94/Waterfox#3412]
### What happened?

![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/56209f4b-d4aa-427a-bb49-80634c5acb8f)
look at that weird kerning
![image](https://github.com/WaterfoxCo/Waterfox/assets/11874211/612b7ab5-37eb-4e4a-be77-8dd77813658a)
this also happens in firefox but i'm not sure why

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
That is as expected, the change is in commit: [`ac868440b70fe1fffb0de6692316ab252073aa9d`](https://searchfox.org/mozilla-central/diff/ac868440b70fe1fffb0de6692316ab252073aa9d/toolkit/themes/shared/in-content/common-shared.css#253), which landed in v119.

`font: message-box` is essentially [shorthand](https://developer.mozilla.org/en-US/docs/Web/CSS/font#constituent_properties) for `font-family: message-box`, of which `message-box` is a system keyword[^1] which is defined here as the [default GTK font](https://searchfox.org/mozilla-esr115/source/widget/gtk/nsLookAndFeel.cpp#1097) (even for KDE, I suppose?).

Hope that helps!

[^1]: If font is specified as a system keyword, it must be one of: caption, icon, menu, message-box, small-caption, status-bar.

**Comment by aaronliu0130** [comment]
But what if I use Qt?

**Comment by MrAlex94** [comment]
It'll be whatever the system default font is, I believe: https://searchfox.org/mozilla-esr115/source/widget/gtk/nsLookAndFeel.cpp#1029

If we shove it into Claude to explain a bit better:

> This `GetSystemFontInfo` function is used to retrieve system font information from a given `GtkStyleContext` object, which is part of the GTK+ toolkit. The function takes three arguments:
> 
> 1. `aStyle`: A pointer to a `GtkStyleContext` object, which represents the style context associated with a GTK+ widget.
> 2. `aFontName`: A pointer to an `nsString` object, which will be filled with the name of the system font family enclosed in double quotes.
> 3. `aFontStyle`: A pointer to a `gfxFontStyle` object, which will be filled with various properties of the system font, such as style, weight, stretch, and size.
> 
> Here's a breakdown of what the function does:
> 
> 1. It initializes the `style` property of the `aFontStyle` object to `FontSlantStyle::NORMAL`.
> 2. It retrieves the font description (`PangoFontDescription`) from the `GtkStyleContext` using the `gtk_style_context_get` function.
> 3. It sets the `systemFont` property of the `aFontStyle` object to `true`, indicating that the font is a system font.
> 4. It converts the font family name from UTF-8 to UTF-16 and stores it in the `aFontName` string, enclosed in double quotes.
> 5. It sets the `weight` property of the `aFontStyle` object based on the weight value from the `PangoFontDescription`.
> 6. It sets the `stretch` property of the `aFontStyle` object to `FontStretch::NORMAL` (TODO: Set the stretch correctly).
> 7. It calculates the font size in pixels based on the `PangoFontDescription`. If the size is not absolute, it converts the size from pango-points to pixels using the scaling factor from `gfxPlatformGtk::GetFontScaleDPI()`.
> 8. It sets the `size` property of the `aFontStyle` object with the calculated pixel size.
> 9. Finally, it frees the `PangoFontDescription` object.
> 
> Overall, this function is used to extract font information from a GTK+ style context and populate a `gfxFontStyle` object with the relevant properties. This information can then be used by other parts of the application that need to work with system fonts.

**Comment by aaronliu0130** [comment]
Yes, but I'm using Qt theming, not Gtk theming. I'll try checking this in the Arch wiki.

**Comment by aaronliu0130** [comment]
![image](https://github.com/BrowserWorks/Waterfox/assets/11874211/ec487fb8-3e02-4c95-86e4-d87da3fdd787)
@MrAlex94 I've set the default gtk theme and it still doesn't work.
