### ISSUE TITLE
Can't disable "Tabs Sidebar" extension forever

### ISSUE THREAD

**Issue by ChiaYen-Kan** [MrAlex94/Waterfox#3415]
### What happened?

after upgrade to G6.0.12 has "Tabs Sidebar" extension builtin Waterfox
i disable it in add-ons manager, but when restart Waterfox "Tabs Sidebar" is enable again, i need disable it again

how i can disable "Tabs Sidebar" extension forever

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by robvthof** [comment]
I encountered the same issue: restarting Waterfox re-enabled Tabs Sidebar.
I found a solution in the about:config. "browser.sidebar.disabled" is the switch.

**Comment by MrAlex94** [comment]
As mentioned above, setting `browser.sidebar.disabled` to `true` is the way.

**Comment by ThibautPlg** [comment]
I really wish it had been opt-in and not opt-out feature (even more when the opt-out solution is to mess with the about:config page). 
When I'm loading a bunch of tabs from the same domain from my bookmarks, the last thing I'm expecting and wanting is to have a bunch more of useless tabs that I have to close almost immediately. 
Thanks @robvthof for the hint.
