### ISSUE TITLE
Audio / mic does not work from 6.0.13, says "need to enable permissions" 

### ISSUE THREAD

**Issue by timur-g** [MrAlex94/Waterfox#3420]
### What happened?

I use meet.jit.si and usually mic works. 
This morning I upgraded to 6.0.13 and now when I want to log in, it says need to enable permissions" , mic does not work.
I update regulary, so this is a change in the last or some of last version.
Firefox is OK.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
How did you update? Using the tarball or some other way?

**Comment by timur-g** [comment]
Linux Mint. apt update. http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_22.04/ /

Interesting, may be one-time issue, as upon more tries, **now it is working**. I see green "all is working" and mic works in Jitsi.  

| Unrelated, I just noticed that Firefox has audio output test | 
![image](https://github.com/WaterfoxCo/Waterfox/assets/7240617/9be4fc94-c50e-4bb8-89ea-b73795475b70) | while Waterfox has just mic | 
![image](https://github.com/WaterfoxCo/Waterfox/assets/7240617/f5beacf4-a99a-4bf0-9eb7-358883581879)

**Comment by MrAlex94** [comment]
Audio output test might be in a newer version of Gecko, which is why Waterfox doesn't have it. But glad to know it's working!
