### ISSUE TITLE
Still cannot stream

### ISSUE THREAD

**Issue by sja105** [MrAlex94/Waterfox#3464]
### What happened?

Cannot use netflix or Prime.  Been ongoing issue.  Uninstalled reinstalled.  turned off extensions.   still not playing.  I think it was supposed to be fixed in a much earlier version, but it never worked for me.  I have firefox and netflix  plays on that.  just an issue with waterfox.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

macOS

### Relevant log output

```shell
When I try to play I get pardon the interruption
title is not available to watch instantly.  please try another title - 1044
Error code F7121-1331
```

**Comment by sja105** [comment]
I mac Mac Mini M1 OS version 14.5.  

Netflix plays on Safari and firefox, but not on Waterfox.  What could be the issue?

What should I try to fix?

Thanks for advice.

**Comment by knelldev** [comment]
Sadly an issue for a longer time. :) See #3210 

We haven't received any answer on this yet, unfortunately.

**Comment by MrAlex94** [comment]
This has been resolved in G6.0.20! Stream away :-)
