### ISSUE TITLE
Streaming service (Netflix) doesn't work - G6.0.17 Linux x64

### ISSUE THREAD

**Issue by T0MuX** [MrAlex94/Waterfox#3520]
### What happened?

Hi, I can't see any video on Netflix on Waterfox G6.0.17 Linux x64. The DRM option is however checked. I did some tests.

I have both installed Waterfox, and Firefox (128.0.3). My whole system (Artix Linux) and apps are totally up to date. On Firefox, Netflix works out of the box. On Waterfox, I get the following Netflix's error code : F7361-1253-806E0005.

Out of the box, the user agents are : 
Firefox : Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
Waterfox : Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
But I'm not sure if this is relevant because even if I switch the useragent on Waterfox, I still get the same error.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by v-127** [comment]
Having exactly the same issue, Arch Linux and Waterfox.

**Comment by MrAlex94** [comment]
Where did you get Waterfox from? The tarballs should work; otherwise if it’s from a repository I’m not sure it will due to the Widevine signing requirements.

**Comment by v-127** [comment]
> Where did you get Waterfox from? The tarballs should work; otherwise if it’s from a repository I’m not sure it will due to the Widevine signing requirements.

From Waterfox-bin AUR [https://aur.archlinux.org/packages/waterfox-bin](https://aur.archlinux.org/packages/waterfox-bin)

**Comment by MrAlex94** [comment]
Yes unfortunately unless I sit and release official packages, this won't be possible.

**Comment by T0MuX** [comment]
Hi, I got it the same way than @v-127 : AUR package (aur/waterfox-bin).
Do you think it can makes a difference if I try with the compiled one ? (aur/waterfox)

**Comment by hawkeye116477** [comment]
> Do you think it can makes a difference if I try with the compiled one ? (aur/waterfox)

Waterfox-bin just downloads official tarball and adds few shortcuts, so if it doesn't work with official binary, then it won't work also from that. I'd check if some extensions not interfere with Netflix.
You can also check at <https://bitmovin.com/demos/drm/> if Widevine is detected.

**Comment by v-127** [comment]
Would it work if I use the flatpak version?

**Comment by hawkeye116477** [comment]
> Would it work if I use the flatpak version?

Flatpak downloads official tarball and adds few shortcuts, the only significant difference is that it may use other version of ffmpeg package than distro provides, so if it's problem with ffmpeg then maybe it will work, otherwise it should be same.
I haven't Netflix, so can't test, but at least Prime Video works fine for me .

**Comment by MrAlex94** [comment]
I'll close this as drm does work from official builds.
