### ISSUE TITLE
Tab crashing on 6.5.0 Beta 1 - www.theguardian.com

### ISSUE THREAD

**Issue by stu-carter** [MrAlex94/Waterfox#3545]
### What happened?

Hi.

As of the past few hours, I see tab crashed only on one site of many I visit - https://www.theguardian.com/international

It sometimes loads and then when I scroll down half a page, the 'Gah. Your tab just crashed.' screen appears.  Unlike firefox I cannot send or capture a crash dump.  I restarted in 'Troubleshooting mode' but the same issue occurred.

Also occurs in private windows and also if the page loads and I resize the Waterfox window by even a pixel, the tab crashes.

Update - it is now crashing all the time when loading the page.

No issues on Chrome or Edge or Firefox.  Have not tried it with the Waterfox non-beta stream.

Anything I should do to capture diagnostics?

UPDATE - reproducible with 6.5.0 Beta 3

Thanks.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by scgf** [comment]
Still happening here on Waterfox 6.5.0 (macOS 15.1). Doesn't happen on Firefox, LibreWolf or Ghostery Private Browser BUT it is happening in Floorp, which is also based on Firefox ESR.

**Comment by MrAlex94** [comment]
https://github.com/BrowserWorks/Waterfox/issues/3604#issuecomment-2465425415
