### ISSUE TITLE
Session Manager (Michael Kraft) icon not available to add to toolbar

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [MrAlex94/Waterfox#3567]
### What happened?

This is most likely not a bug but rather an user input error.

I have Michael Kraft's Session Manager add-on installed (see below image) but I cannot find where/how (see image below) to get the icon into the toolbar so I can access my sessions.

Would anyone know why this is happening?

![Image](https://github.com/user-attachments/assets/08dd4b1d-f2ee-4641-a235-8605e72a3628)
![Image](https://github.com/user-attachments/assets/0f93b795-4d1d-4485-a4d7-045cba2cb86e)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

macOS

**Comment by Squall-Leonhart** [comment]
this extension is not compatible with Firefox/Waterfox after 56.

**Comment by Napoleon-BlownApart** [comment]
That's a real shame.  As I understand it, the whole idea behind WaterFox when it was forked from FireFox, was to maintain compatibility with the wealth of extensions etc. that were available at the time.
The move to the WebExtensions API, without providing backwards compatibility is rather unfortunate, and a betrayal of its user base.

**Comment by thunderstone135** [comment]
You're barking up the wrong tree dude. If you have complaints, send it to Mozilla.

**Comment by Napoleon-BlownApart** [comment]
I'm not.  I've been using FF for almost 20 years, and the sole reason I went with WaterFox was because the old add-ons would be supported.

Now, I am aware that the decision to move away from XUL was made some time ago, but since WaterFox still shows the Session Manager as active and allows me to configure it I'm wondering why the icon isn't available.

**Comment by thunderstone135** [comment]
While it's true that Waterfox supports old addons, it doesn't mean that they will keep working forever.
At the end of the day, said addons will still need updates and maintenance from their respective developers.
Just look at [Tab Mix Plus](https://github.com/onemen/TabMixPlus). It's only alive today because its developer is still actively updating and maintaining it.
I also used a lot of old addons in the past, but I was forced to ditch them because their developers have gone AWOL.

**Comment by Squall-Leonhart** [comment]
The developer requested a number of api's so they could continue work on this extension, but it fell on mozilla's deaf ears.

https://bugzilla.mozilla.org/show_bug.cgi?id=1427928

**Comment by thunderstone135** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1427928

All I see in the discussion was _**"Were, busy. It's futile to continue. If you game our process, we will suspend your account."**_
Way to go Mozilla; ignore/threaten your users/reporters who you think are not complying with your rules and regulations.

I also reported a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1790173) regarding bookmarks manager, but lo and behold, a lot of naysayers appear and deny my claim even when I have given them steps on how to reproduce and which versions are not affected. ¯|_ (ツ) _|¯
