### ISSUE TITLE
Last 115 ESR Binary Installer

### ISSUE THREAD

**Issue by jabcreations** [MrAlex94/Waterfox#3598]
### What happened?

So I need to do version testing and I can not find the last stable release binary installer for 115 ESR (or "6.0.x" for Waterfox). The waterfox.net website is already linked to 128 ESR (or "6.5").

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by thunderstone135** [comment]
You need to click the dropdown box 👇

![Imgur](https://imgur.com/t8cFwMl.png)

**Comment by jabcreations** [comment]
The top-right Download link goes to that page with the following URL:

https://www.waterfox.net/download/

Got it, long day, thank you TS.
