### ISSUE TITLE
Waterfox Theme not able to set.

### ISSUE THREAD

**Issue by preetmungara** [MrAlex94/Waterfox#3599]
### What happened?

When I try to change the theme of browser to Waterfox, it's not showing any theme, previously it used to show default Waterfox option selected, then changed it to default one, now i can't go back to Waterfox theme. I'm on 6.5.0 (64-bit)

![Image](https://github.com/user-attachments/assets/f230801a-be8b-4f93-bd43-bc1694b07c4e)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

**Comment by hiiiha** [comment]
I also have this issue on both Windows x86_64, Arch Linux x86_64 
(Waterfox 6.5.0)

**Comment by Splitwirez** [comment]
Happening here as well (Kubuntu Linux)

(pure speculation) Looks to me like the options are all still there, just...very, *very* tiny, and with no text labels. That being said, nothing seemed to happen when selecting any of them, even via keyboard navigation.

Tangent: Is the section overview on the right completely trashed in the Look & Feel section for you folks too, or is that only on my end?

**Comment by MrAlex94** [comment]
This will be fixed in 6.5.1. Forgot to pull in the new strings after updating the settings page and it messed everything up!

Please re-open if that's not the case, but did some quick testing and seemed so.
