### ISSUE TITLE
Some labels missing in Settings

### ISSUE THREAD

**Issue by Dim-Tim-1963** [MrAlex94/Waterfox#3603]
### What happened?

Settings, Look and Feel: some labels are missing at dropdowns and buttons, see attached image.![Image](https://github.com/user-attachments/assets/0c1d8783-1b76-4ae6-b770-d14619c44e13)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by Splitwirez** [comment]
Happening here too (Kubuntu Linux)

Is this the same problem as https://github.com/BrowserWorks/Waterfox/issues/3599 ?

**Comment by MrAlex94** [comment]
Duplicate of #3599
