### ISSUE TITLE
56.2.5 (64-bit,linux)  download link broken

### ISSUE THREAD

**Issue by dodona2** [MrAlex94/Waterfox#791]
**Describe the bug**
download result: 404 Not Found

**To Reproduce**
waterfox
download waterfox
-
download result: 404 Not Found

**Expected behavior**
download result: OK

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
Linux
Fedora release 29 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by grahamperrin** [comment]
From <https://blog.waterfoxproject.org/waterfox-56.2.5-release-download#comment-4184044091> (2018-11-08): 

>> … .5 … isn't on the website for linux users.
> 
> Strange. Will have a look, might be a cache issue with the site.

Meta: #582

**Comment by dodona2** [comment]
not a cache issue. Direct downloading using jdownloader or wget also fails:

wget https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-56.2.5.en-US.linux-x86_64.tar.bz2

--2018-11-14 07:53:27--  https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-56.2.5.en-US.linux-x86_64.tar.bz2
Resolving storage-waterfox.netdna-ssl.com (storage-waterfox.netdna-ssl.com)... 151.139.239.36
Connecting to storage-waterfox.netdna-ssl.com (storage-waterfox.netdna-ssl.com)|151.139.239.36|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-11-14 07:53:28 ERROR 404: Not Found.

**Comment by ibuprophen1** [comment]
@dodona2, have you seen the https://github.com/MrAlex94/Waterfox/issues/418? 


~Ibuprophen

**Comment by dodona2** [comment]
you aren't wrong. There is no 56.2.5. Guess there will be no linux builds from now on.

**Comment by grahamperrin** [comment]
> … Guess there will be no linux builds from now on.

I don't share that guess. 

Before 56.2.5: the history of edition of https://github.com/MrAlex94/Waterfox/issues/418#issuecomment-401091893 shows that the distribution of 56.2.4 for Linux was later than the other two distributions.

**Comment by dodona2** [comment]
since today there is a downloadable @56.2.5.

**Comment by pat-san** [comment]
Hello,
It was a few days of waiting, 56.2.5 Linux-64 is finally here!
thank you
