### ISSUE TITLE
REQUEST: Build instructions 

### ISSUE THREAD

**Issue by Kreyren** [MrAlex94/Waterfox#937]
Requesting adding a build instructions for waterfox including runtime and build dependencies to make downstream compatibility less of the hell.

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/wiki/Quick-Build (2016)

NB: 

- #1179 concerning the recent changes to branches
- recent improvement https://github.com/MrAlex94/Waterfox/commit/d8c19a434e5cc007a100db04b8baf4a7ece1cb19

**Comment by MrAlex94** [comment]
I'll be updating the docs soon.
